### ISSUE TITLE
Webhooks or access to external API

### ISSUE THREAD

**Issue by Simulacron3** [Neos-Metaverse/NeosPublic#101]
Is there a mechanism for linking a Neos object to an external service, either running on the user machine or on the Web? I'm particularly interested in dynamic physical and cognitive behavior services for bots, etc.

**Comment by Psychpsyo** [comment]
POST requests exist now and websockets can most likely do what's being asked for here so I'm wondering if it might be time to close this issue down.

**Comment by ProbablePrime** [comment]
I agree on closing this one as I'm not quite sure what is being asked for. 

I have written an article here on our wiki which covers your current options: https://wiki.neos.com/Connecting_Neos_to_Other_Applications

If you have further questions feel free to comment and we can re-open the issue. Thank you!
