### ISSUE TITLE
Suggestion: AxisMultiViewportPanner's viewport arguments should match the order of a RectTransform

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#1048]
I noticed the AxisMultiViewportPanner's Viewport values are reversed from the RectTransform values. When manually setting this up as a Neos user I accidentally misplaced these values because of this reversing. 

I'd like to suggest that they be reversed in the inspector for AxisMultiViewportPanner.

AxisMultiViewportPanner, Viewports:
1. Anchor Min
1. Anchor Max
1. Active

Rect Transform:
1. Anchor Max
1. Anchor Min
...etc

![2020-09-19 02 21 24](https://user-images.githubusercontent.com/8791132/93666547-f8a41380-fa33-11ea-9000-9b02223012bf.jpg)

**Comment by Zandario** [comment]
Seems this has been addressed, can't find the update that did it though.
![19-Friday_Neos_416](https://user-images.githubusercontent.com/34761877/142676573-a25da5b5-65b4-4590-b852-d5269a9d2ae6.png)

**Comment by ProbablePrime** [comment]
I also remember this being addressed.

\o/
