### ISSUE TITLE
Token transfer from non-contact causes issues.

### ISSUE THREAD

**Issue by DanteTucker** [Neos-Metaverse/NeosPublic#1071]
Discovered in the Tetris world. As part of the world KFC is sent to you by a bot. This makes a new message indicator show up on the contacts button which can not be cleared as you don't have an entry in your contacts to view.

**Comment by shiftyscales** [comment]
This should be implicitly fixed by #2674.
> Fixed in 2021.7.22.458, any non-contacts are now filtered when counting unread messages!
