### ISSUE TITLE
People who have sent you a contact request previously (which has been ignored)'s sessions will show up in contact's sessions section

### ISSUE THREAD

**Issue by mralext20** [Neos-Metaverse/NeosPublic#1077]
timeline: a few days ago Rebecca_angel sent me a contact request, witch i ignored. today, their session showed up in the friend's sessions tab of my world browser. 
https://cdn.discordapp.com/attachments/459596128443432961/758485080305303572/2020-09-23_06.08.33.webp https://cdn.discordapp.com/attachments/459596128443432961/758485081232244756/2020-09-23_06.08.24.webp

**Comment by TehTurk** [comment]
Closing please move towards #1769 as it's more fleshed out.
