### ISSUE TITLE
Inspectors, joints and sliders not updating when turned off for host

### ISSUE THREAD

**Issue by Beaned2000** [Neos-Metaverse/NeosPublic#1268]
So the issue is that when an ispector, slider or joint is turned off for the host, they don't function for other users anymore.
The reason why this is a problem is when you want to set up a culling zone where these things would get disabled when a user is not in them. So meaning if you are moving a joint or a slider within those culling zones and the host isn't in there they just don't work anymore.
same goes for inspectors when not active for the host you cant use the drop-down arrows to show the children of the slots.

replicating steps:
make a slot and parent a slider/joint/inspector to it and turn it off with a ValueUserOveride for the host or have a culling zone made that toggles the slot.

**Comment by TehTurk** [comment]
Hmm I've run into this too, wonder if there's a component we could attach to a slot for it to check it needs to update disabled slots? But it might be too ingrained as a behavior. I'd like this but designing systems around this seems most apt.

**Comment by H3BO3** [comment]
It's because host actually updates a lot of these things, especially inspectors. As for sliders and joints, that's also a known issue, it requires Froox to rework the drive release mechanism so it works more independently - As a mitigation for the slider and joint issue, you can check the "DontDrive" bool and it will write-update the items instead, fixing them.

**Comment by Beaned2000** [comment]
well fair enough for the sliders and joint. the workaround for the inspector is doable i know but still something i would like to see changed possably since setting up custom checks for inspectors is annoying

**Comment by TehTurk** [comment]
Yeah likewise, plus there's some behaviors that you'd want active in most situations for locality stuff like that, but it does vary. For Example, Anchors can break if you do set it up intially properly :) but I guess this ties into how Drives kinda work and you need to have the proper Parameters.

**Comment by shiftyscales** [comment]
As H3had noted, this issue is related to reworking the drive release mechanism, for which he made issue #1270 for.

Closing out this issue to merge it with that one as once implemented, it should resolve this issue, and other related ones like #651.
