### ISSUE TITLE
Avatar import with a weird blue tint? 

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#1302]
Was doing an Avatar Import to have a better selection of Public Avatars for Users to start with and found this issue.
![Neos_Ic6xQUCC1E](https://user-images.githubusercontent.com/26357446/98462781-adc99100-2184-11eb-9b47-f849b13e0a2a.jpg)

It was found that..
- Certain Models seem to import this way? This only appears for XieXie's Toon, other Shaders won't have this issue
- The issue clears up if the BoundComputeMethods is computed in a different way, and won't return after switching through the different modes.
- I can send the models if need be, but I also had Vigi be my other pair of eyes, we originally thought it was normals, or some other mesh issue, but we narrowed it down to this.

**Comment by Frooxius** [comment]
Can  you send me the avatar model please? This is not something that could be fixed without it.

**Comment by Frooxius** [comment]
Which one of the avatars that you sent is the one that exhibits this problem? Did you use the toon shader during import or apply it afterwards?

**Comment by TehTurk** [comment]
It was used during import, it was inconsistent so I sent ones that I witnessed it happening consistently.

**Comment by TehTurk** [comment]
I'm going to close this as I haven't seen this in awhile and I think it may have been user error on my part.
