### ISSUE TITLE
seperate default microphone for desktop and VR Mode

### ISSUE THREAD

**Issue by mralext20** [Neos-Metaverse/NeosPublic#1311]
the problem: switching between VR and Desktop mode means that you currently need to switch your microphone. 

a potential solution: have seperate microphone in desktop mode vs VR Mode

**Comment by Frooxius** [comment]
This is planned, but won't happen until we have official support for Desktop mode: https://github.com/Frooxius/NeosPublic/issues/151

**Comment by mralext20** [comment]
consider doing this sooner? with the new loopback audio input devices, the list of input devices has doubled for most people. (i have gone from 4 input devices to 9 devices.

**Comment by Frooxius** [comment]
Either the desktop mode would have to be done sooner for that or I would have to add some hacky way to do it. With the desktop mode, switching between desktop and VR will be dynamic at runtime, so the mechanism for switching audio input device would also be different than what could be implemented now.

**Comment by Frooxius** [comment]
It's not quite this feature, but I've actually created a new audio selection dialog in 2020.11.10.578 that should make it easier to switch between audio devices. Hopefully that'll reduce the current urgency for this feature.

**Comment by mralext20** [comment]
thank you so much ❤️

**Comment by shiftyscales** [comment]
Audio settings are able to be set per-mode as of `2021.2.7.1345`.

`- Audio settings (Master Volume, Noise Gate/Filtering, Normalization and audio input device) are now unique whether Desktop Mode or VR mode is active and will instantly switch as the modes are toggled`
