### ISSUE TITLE
Undo Function Randomly Breaks on Headless

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#1321]
This happens quite frequently but I'm not sure anyone's been able to narrow down *why* it happens.

At some point, the headless will simply stop logging new actions for users, resulting in any attempts to "undo" undoing an action from X long ago, where X could be minutes, hours or even days, depending on when the undo log stopped logging. This is obviously super dangerous given how easy it is to accidentally do something you didn't mean to.

This has been observed in many different worlds on entirely different headless servers, so it's not limited to specific places or a specific installation.

Apparently deleting user's undo queue then having them rejoin fixes the issue for a while, until it eventually breaks again.

**Comment by shiftyscales** [comment]
I've observed this as well, but I haven't ever found a specific replication case for it. The only common scenarios I've ever seen is if a user leaves the session, waits a while, then rejoins it. But trying to brute-force that scenario alone didn't trigger it, so there's likely some other element/mechanism involved.

Do we know with complete certainty it's only headless sessions causing this issue?

**Comment by Frooxius** [comment]
Is there anything in the logs of the user whose Undo steps are broken? Checking the undo queue for anything odd might help too.

We'd definitely need more info or some way to replicate this, I don't really know what it could be otherwise.

**Comment by StarfishHidari** [comment]
I have seen this happen a lot even on non-headless hosts, I am pretty sure this is not headless specific.

Generally when it happens the only way to fix it was to either restart the world or delete the user's undo queue

**Comment by Hayden-da-Serg** [comment]
I've seen this happen a lot, and it's definitely not a headless specific issue. As noted above, the only replication steps I know of are having a user leave, wait for some time then rejoin, but as Shifty also noticed, this doesn't seem to work via brute forcing it.

If I do happen to find any more I will post here as it does often get in the way of working over long periods of time.

**Comment by shiftyscales** [comment]
Hey @Frooxius- per your request, posting here so we remember what I discovered tonight.

As it turns out, undo steps are still being generated properly, but their ordering is incorrect. Older entries are placed in front of newer ones, but they are still being properly generated.

From what you had noted, this is due to ordering based on the ids which would change between different sessions.

**Comment by shiftyscales** [comment]
This was fixed in 2021.1.26.1308.
