### ISSUE TITLE
DateTime variables get converted from UTC to Local on save/load

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#1364]
Before the save:
![1](https://cdn.discordapp.com/attachments/439422161657135106/779052887689920542/2020-11-19_21.35.14.webp)

After the save/load:
![2](https://cdn.discordapp.com/attachments/439422161657135106/779052889796116490/2020-11-19_21.35.54.webp)

DateTime with UTC time offset gets converted to local time offset:
![3](https://cdn.discordapp.com/attachments/439422161657135106/779056740082647061/2020-11-19_21.52.49.webp)

Which would cause problems if you try to extract time components, which uses the displayed time as opposed to explicitly using either UTC or Local:
![4](https://cdn.discordapp.com/attachments/439422161657135106/779058079521046548/2020-11-19_21.58.27.webp)

Or if you subtract two times to get a TimeSpan. In this case I try to calculate how much time has passed since I sent the pulse:
![5](https://cdn.discordapp.com/attachments/439422161657135106/779059736363794485/2020-11-19_22.04.44.webp)

**Comment by shadowpanther** [comment]
I think the DateTime **Kind** (local vs. global) doesn't get saved with the datamodel.

**Comment by ProbablePrime** [comment]
![image](https://user-images.githubusercontent.com/8791132/125008160-c9887e00-e016-11eb-915d-d7bf1c43ac6b.png)

" I can see that saving the world converts DateTime from UTC to Local" - Shadow Panther

So saving the world changes the Kind Property from UTC to Local. 

We'll have to look at the Save/Load routine for this datatype.

**Comment by shadowpanther** [comment]
It changes the property _and_ converts to local time. It's not that "(UTC)" is missing, it's _equal_ to local time in my timezone.
