### ISSUE TITLE
Method of re-centering dash while in the tutorial

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Neos-Metaverse/NeosPublic#1370]
While going through the tutorial, I noticed that while moving around my playspace, I found myself getting annoyingly offset from the dash but not far enough to trigger the UserInterfacePositioner, and normally I'd just close and re-open it to re-center it however the tutorial prevents you from doing this. Maybe have some form of button or gesture that force re-centers the dash on trigger?

**Comment by uyjulian** [comment]
Possibly pressing the dash button will recenter the dash?  

This is the same behavior as what Oculus uses

**Comment by Frooxius** [comment]
Can you just grab it and move it around? That should still work. I don't plan adding a whole different method of re-centering the dash that would only be used briefly for the tutorial.

**Comment by Hayden-da-Serg** [comment]
Not really, as that is based on the original pivot of the dash and is always skewed until the UIPositioner is triggered.

**Comment by shiftyscales** [comment]
Is this ever an issue if a user isn't actively moving around their playspace, @Hayden-da-Serg? It should be in a good position when the user first loads in, is this ever not the case for you?

**Comment by Hayden-da-Serg** [comment]
Ya, staying in one place is fine, it's more so that if I move a bit but not enough to trigger the re-center, then it becomes kinda annoyingly offset.

**Comment by TehTurk** [comment]
I'm going to close this issue as it would just make sense to adjust the component internally and the settings should save. It's one of those where it's not really a dedicated thing, but it's also something that's more of a user tweak on a component.
