### ISSUE TITLE
Avatar creator eye range visualization

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#1384]
To my knowledge the spheres on the avatar creator head are the camera positions, however can the visualizers be shifted to an object that shows their view range? This would help with avatars that have longer noses so the user can tell how much of their nose would be visible in the view. I know this isn't a straightforward thing, but at least some directionality would help.

**Comment by shadowpanther** [comment]
You can adjust the near-clip on the avatar instead. That could be done after the conversion.

**Comment by InsaneGrox** [comment]
Major problem here is that headsets have different view clipping points and different FOVs, so for instance, someone on a quest 1 or rift S would have their viewpoint far back and have a small FOV, while someone with an index would have their viewpoint further forward with a tremendously large FOV in comparison, and don't get me started on the nightmare of pimax HMDs.

**Comment by Earthmark** [comment]
Grox's fov convent does discredit this request pretty strongly, this can't really reliably be shown so I'll close this for now!
