### ISSUE TITLE
User Respawning Nodes

### ISSUE THREAD

**Issue by LeDrascol** [Neos-Metaverse/NeosPublic#1413]
## Is your feature request related to a problem? Please describe.
Respawning users with LogiX is only possible with a (presumably) unintended method involving deleting the user root slot. This is the only way to return a user to the world's spawn point in all cases.

Unfortunately this has the following issues:
- Unsaved changes are lost
- The respawn user permission is ignored
- There is no reliable method of preventing unwanted occurances
- Users may be unparented from the intended user slot

## Relevant issues
N/A

## Describe the solution you'd like
Here are some possible suggestions:

- **Respawn User**: Requires respawn permission, unless self-inflicted. Functions identically to the user list button. Accepts reference for a spawn point.
- **Return User**: Teleport user to a spawn point without deleting user root. Accepts reference for specific a spawn point. Reparents user to the spawn point if the associated setting has been enabled on the spawn point.
- **Get Respawn Point Slot**: Provides reference for user spawn point, if one exists. Provide index if multiple points exist, defaulting to highest weighted slot.
- **Get Respawn Point Count**: Provides integer for the number of valid respawn points.
- **Get Nearest Respawn Point**: Provides slot reference of the nearest respawn point to input coordinate.

These are only sugguestions and not requests.

## Describe alternatives you've considered
Continue deleting user slots.

## Additional context
Updated to use new formatting.

**Comment by TehTurk** [comment]
Pretty sure this is equivalent to just setting the Local Transform of a Slot if a User is Parented to it. I'm not against having this but alot of this is typically handled by the user vs a built in node. The Only ones I see viable are Respawn User. Typically the internal system/locomotion will take care of the rest.
