### ISSUE TITLE
Customizeable World thumbnails 

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#1419]
Ability to customize thumbnail of world for example a custom created picture of a world that looks invity
So you have a cool banner as world preview for example
Like a 360 fun clickbaity looking custom preview that grabs people's attention There are tons of cool worlds but because the thumbails are not customizable it doesn't show of the cool parts of worlds so customizable 360 thumbnails

**Comment by Frooxius** [comment]
There's a few things planned for this. One of them is creating reference object in the world which will be used to take the 360 thumbnail. Supplying a custom 360 one is also a possibility, it could just be referenced by it.

**Comment by epicEaston197** [comment]
my GitHub pose specifies a specific camera to take the photo

**Comment by epicEaston197** [comment]
I want a customizable 2D photo

like this
![unknown (1)](https://user-images.githubusercontent.com/76523692/125196195-e98e8c00-e226-11eb-8655-ed8fafe09ae3.png)

**Comment by epicEaston197** [comment]
and maybe it doesn't have to be a camera and it can be a static image

**Comment by Frooxius** [comment]
This has been added in 2021.9.20.1334! Thanks for report!
