### ISSUE TITLE
Fullbody calibration tool UX Improvements

### ISSUE THREAD

**Issue by Zyro1331** [Neos-Metaverse/NeosPublic#1422]
I've thought of some little details on the Full-body Calibration tool that could be added later. When I go to calibrate my avatar, the yellow reference character is in the center of my playspace. Issue? 

The center of my playspace is right between my bed and floor, when I calibrate It makes me awkwardly place my legs against the bed frame to calibrate. 
If we could get the T-Pose reference to move (while staying ground projected) to the players head, I think that can make an improvement for users with crowded playspaces. 

Another thing is the refs legs are blocked by a lot of avatars legs (especially avatars with digitigrade legs), an overlay material on the T-Pose reference could help a lot.

**Comment by Zyro1331** [comment]
I've updated and edited this issue, as I feel like more improvements can be made later. Just kinda bringing it back up to get some attention it needs.

**Comment by shiftyscales** [comment]
Closing this issue in favor of #2588 and #2589 which separate the work items requested in this issue, and closer follow the tweak template.
