### ISSUE TITLE
Local Web Video Settings

### ISSUE THREAD

**Issue by LeDrascol** [Neos-Metaverse/NeosPublic#1439]
## Is your feature request related to a problem? Please describe.
Videos will always default to a high resolution setting for all users. This can be problematic for bandwidth and other resource use cases, especially for slow connections. Some users are distracted by or otherwise do not want videos to play.

Additionally, many videos are used as music players where the video feed is unused, but not disabled by the world creator.

## Relevant issues
#1439

## Describe the solution you'd like
Here are some possible suggestions:
- Prefer audio only
- Prefer input height, width, or resolution preset
- Disable all videos
- Blacklist videos by URL, channel, title, tags, or other arbitrary factor

These are only sugguestions and not requests.

## Describe alternatives you've considered
- Politely ask all world owners to manage videos responsibly.
- Local controls on default video player

## Additional context
Issue updated with new formatting.

**Comment by Frooxius** [comment]
I can add the first two, but the third one isn't necessary, you should be able to use the Enabled field for this. Those also won't be local overrides by default, the data model never is, but you can just drive them.

Once settings are reworked, we can add global user settings which would allow user to change those settings on their end based on their resources.

**Comment by LeDrascol** [comment]
The enabled field for videos can't be applied as a non-builder, or requires setup on a world level to allow users to opt-out from loading and streaming unwanted videos.

When entering a world with unwanted streaming video, the user is unable to reliably disable videos without adding `youtube-dl.exe` to the system firewall, which causes other issues.

This is most problematic in worlds with always-on 1080p music livestreams, where world hosts refuse to lower the resolution or allow an opt-out. The stream consumes unnecessary resources and bandwidth - especially for limited connections.
