### ISSUE TITLE
DragDrop documents kills analog inputs. rendering trigger and movements invalid

### ISSUE THREAD

**Issue by TeknoCatron** [Neos-Metaverse/NeosPublic#1446]
Drag dropping .mp3 (at this time) from desktop into Neos, Perma kills the analog inputs pipeline from steamvr to neos. Neos will not response to any movement or trigger inputs. having to forcefully shut neos down.
logging back in without shutting down steamvr keeps the bug active.
Entire steamvr has to be taken down in order to restore the inputs that where lost.

[KASAI - 2020.12.5.1396 - 2020-12-07 19_43_44.log](https://github.com/Frooxius/NeosPublic/files/5655812/KASAI.-.2020.12.5.1396.-.2020-12-07.19_43_44.log)
[KASAI - 2020.12.5.1396 - 2020-12-08 00_10_57.log](https://github.com/Frooxius/NeosPublic/files/5655813/KASAI.-.2020.12.5.1396.-.2020-12-08.00_10_57.log)

**Comment by Frooxius** [comment]
This sounds like a bug with SteamVR and not Neos, particularly that it persists even across Neos restarts. I can't replicate this on my end either. I'd recommend reinstalling SteamVR first.

**Comment by TeknoCatron** [comment]
I have not seen this occur anymore and not entirely sure what caused this issue back then
