### ISSUE TITLE
Camera Value Overrides

### ISSUE THREAD

**Issue by The-furf-of-July** [Neos-Metaverse/NeosPublic#1463]
Related to #1277 and #1149

Forgive my lack of knowledge about the rendering engine.

Regarding the issue of controlling what cameras can and can't see, I think a system that functions similarly to user value overrides may be useful.
If this turns out to be a subset of the layer system mentioned in #1277, this would still be a useful implementation of said feature.

Overrides for cameras would function similarly to that of user overrides. You could have a value with a default state of true, and override it to false for cameras that render it/all cameras in the world.
In theory this would allow not just selective rendering (override active state), but other behaviors as well, such as ignoring local/active user exclusive UI, or any other values that are intended to be different between users.

For clarification, I am not requesting that cameras be treated as players (that would be an awful can of worms), I am requesting functionality for cameras that mirrors or mimics these existing features.
Also, the camera would only have one set of values to keep track of. It would not need to determine what users can see what values, everyone who looks at the output of a given camera would see the same thing. 

Ideally you could have an override for individual cameras, and as a result render things differently for different cameras, but in all honesty even being able to control anything about what a camera sees would be huge.

**Comment by Frooxius** [comment]
I'm not sure if I understand what this feature would provide that isn't already provided by the existing and planned systems. Cameras already have an render exclusion list, which allows you to exclude specific items from rendering on the camera. The layer system will implicitly allow for globally excluding larger chunks/parts of the scene.

**Comment by The-furf-of-July** [comment]
It would allow changing things like colors or other types of values for cameras as well.

Best concrete example I have is my eye color, which swaps at random under various conditions, including blinking. The intended probability for it swapping was supposed to be 10% for non-local observers, and much higher for me so I'm able to see it in the mirror. I originally had it set to something like 90%, but that was reflected for cameras as well. 
Overrides for cameras would let me use the same values for non-local users for cameras as well.

A related idea, being able to target something like "local camera" via logix, would allow the other conditions of that eye swap script to trigger, such as when I'm out of view of the camera, or when it's looking at me from behind.

I'm fairly sure there would be other uses for having more information and control of what cameras see, from the object side rather than the camera side. 
Another example use is a blanket opt-out by setting a camera override to deactivate your avatar locally for the camera if someone doesn't want to appear on streams or in photos, rather than needing a camera that specifically ignores them.

**Comment by ProbablePrime** [comment]
I think(I checked some notes i have), that the EyeManager has a reference within its properties to the object it is currently looking at. You can hook this up to blendshapes or other things to make the eyes behave differently when they are looking at a camera.

Additionally, using the Force Eyes on Camera option of the Camera/Streaming window will ensure that the eyes are looking at the camera. 

With both of these combined you can get a quick a good idea of when they are looking at a camera and then make some changes. 

As Froox says anything further would require different rendering layers which is a feature Froox has mentioned before.

**Comment by The-furf-of-July** [comment]
That's for when the eyes are looking at the camera, not what the camera is able to see. Though I suppose it can't be looking at a camera if there is no camera, and that could be useful information. 

That would at least work for my streaming camera, but it would remain an issue for other cameras. Thank you though, I'll add that adjustment to my to do list.

As mentioned in the original post, even if this is a subset of a layering system, it could be a useful functionality for the system to eventually have.

**Comment by shiftyscales** [comment]
The needs of this issue seem like they should be met by the existing linked issues/other eventual planned features as Frooxius had noted.
