### ISSUE TITLE
Equip/Dequip event for ITooltip

### ISSUE THREAD

**Issue by The-furf-of-July** [Neos-Metaverse/NeosPublic#1468]
Currently, it seems only RawData tools can send any events. There are ways around using events for this, but it would be much nicer, as well as more reliable, if they were natively supported.

My ideas for this are:
- nodes for On Equip and On Dequip, that accept an ITooltip input and output an impulse for the corresponding reasons; or
- better support for typecasting ITooltip to RawData, so the Raw Data Tooltip Events node can be used.

I definitely think the former is more reasonable, though the latter would have more functionality.

**Comment by ProbablePrime** [comment]
This would replace a couple of updating relays I have floating around.

I have a Dev Tool, Logix Tool, and Material Tool that i'd love to get equip/dequip events for.

Thanks!

**Comment by TehTurk** [comment]
Redirecting this to #2026
