### ISSUE TITLE
High VRAM usage after short periods of time

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Neos-Metaverse/NeosPublic#1484]
I've seen this issue discussed in the Discord but it appears that it's not logged here yet so I thought might as well.

Recently VRAM usage has been out of whack, sometimes using all 6GB on a mobile 2060 within 30 minutes of Neos being open.

In the case of the screenshot below, Neos has been open for 3 and a half hours, however I haven't loaded many assets and have only been in 4 very small worlds.
![image](https://user-images.githubusercontent.com/25524760/102322517-6e891f80-3f3c-11eb-9524-55e510e78737.png)

**Comment by Frooxius** [comment]
Unfortunately this information doesn't help much without knowing how much is loaded. VRAM usage can vary wildly depending on what you're doing, this could be perfectly normal behavior and you're just going into more memory intense worlds/sessions.

I recommend checking the debug dialog and see how many textures are being loaded. 

What kind of worlds does this happen in exactly? Are any of them freshly uploaded with new textures (including any objects spawned during the session)? They might not have been processed.

Does the usage drop after a few minutes if you close all the worlds?

Does this happen if you just stay in a single empty world if yo u don't do anything?

**Comment by shiftyscales** [comment]
Closing this issue due to a lack of follow-through, and a lack of evidence regarding circumstances the issue occurs in.
