### ISSUE TITLE
Proper Screen/Desktop Mode

### ISSUE THREAD

**Issue by Frooxius** [Neos-Metaverse/NeosPublic#151]
Current screen mode of Neos is very limited and can't access all features that are accessible inside of VR. It is meant mostly for passive and debugging use.

A proper screen mode could be implemented with greater care, to give access to nearly all Neos' functionality from screen. This would include:

- Simulating avatar hands (so they're not weirdly contorted)
- Proper simulation of tooltips (adjustable pressure, circular menus, projection interaction and so on)
- Proper reticle (the current one has a slight offset)
- FPS/Editor interaction mode - either you can use mouse to look and interact with things using the reticle, or the movement can be off by default and you can grab and touch things in the world by hovering on them with mouse cursor (similarly the way it's done in the Unity Editor window for example). This would also allow screen mode on touch screens, e.g. on tablets
- Third person mode - this would let you see your avatar in third person moving around
- Screen-alignable UI's - the UI (or the player) would be aligned with screen perfectly, to ease the interaction with it (prevent any perspective distortion)
- Screen UI overlay to display various information for the player and provide common functionality (possibly replacing the dash with something more suited for screens with traditional menus and buttons)
- Dynamically switching between screen mode and VR - this would allow for hybrid workflow without having to restart Neos or run two instances of it. 

Currently this is a low priority, as Neos is focused on VR, but it's something that we'd like to do in the future. I'd also like to see how much interest is in this from users (particularly Patreon supporters).

**Comment by Arcticgamez** [comment]
would very much like to have this as the hacky desktop stuff keeps getting broken with almost every big update to the point its going to be useless to be in neos any longer as a desktop user (once a VR user but its busted)

**Comment by chemicalcrux** [comment]
I concur. I have had to explain to too many people that the game is largely inaccessible to non-VR users!

Some piecemeal improvements -- particularly, fixing locomotion and giving avatars a default hand position -- would go a long way towards making content accessible to desktop users, even if it's not the full experience.

**Comment by JackTheFoxOtter** [comment]
As someone who started Neos as a desktop user, and still is a desktop user, I'm glad to see this feature becoming priority soon, and thought I'd share some thoughts I've had after messing around and more or less mastering screen mode (even though that's not an achivement I'm especially proud of...)

I like the idea of separating FPS and Editing mode to allow the user to unlock the mouse for more desktop-style interactions. This would make a lot of things more comfortable to work with, the things immediately coming into mind are working on Logix Blueprints (Have a proper 2D-editing space similar to many established node-based editing systems), using inspectors / menus and so on. For editing in the 3D-space, a gimbal like approach seems sensible.

Menus and editing mode aside though, the biggest limitation I've found for desktop users compared to VR users is the missing depth perception. Interacting with objects in the world from first person mode will remain to be a core part of the Neos gameplay experience, and this can be really challenging for desktop users. (For example, if you're holding an object, you have no way to determine if you're scaling it or panning it away from the camera). One of the biggest conceptual challenges will be translating organic 3D input styles into instinctive 2D input methods.

For designing desktop first-person object interactions, I think this should be kept in mind at all times. With no depth perception, how can you make it instinctive to place an object flat on the ground? Possibly by utilizing ray-casts and aligning the object's rotation based on the surfaces normal direction? And how can you make rotating objects as natural it is in VR mode? By integrating features known from 3D editing programs like rotate/scale/move around/along one or multiple axises, allowing to align these axies to world/local/normal directions? It's definitely going to be a really interesting game design challenge.

**Comment by Frooxius** [comment]
Since the desktop is now in a usable state with feature parity for the most part and official supported now, I'm going to close this issue! We'll tackle any new additions, tweaks and fixes with individual issues from now on.
