### ISSUE TITLE
Auto-Updating World Data Nodes

### ISSUE THREAD

**Issue by LeDrascol** [Neos-Metaverse/NeosPublic#1523]
## Is your tweak request related to a problem? Please describe.
Some world data related logix nodes do not automatically update, requiring the use of unfavorable methods such as updating relays, writes, or other forms of pulses to update them. This behavior is inconsistent with other nodes and may be unintended.

## Describe what would you like tweaked
Nodes should output the current value without requiring a manual update.

The following world nodes do not update:
- World Access Level
- World Description
- World Hide From Listing
- World Max Users
- World Mobile Friendly
- World User Count

This list may be incomplete.

## Describe alternatives you've considered
Update the variable every frame.

## Additional context
Updated to use new formatting.

**Comment by ProbablePrime** [comment]
Copying some context from #2734. 

>This isn't something we'd expose like that. If we add mechanism to track the changes for those, we'll hook it directly into this nodes, so they fire change events appropriately, instead of requiring every user to implement that themselves.

So there would be a potential path at some point to look at improving these nodes. 

Thanks!
