### ISSUE TITLE
Oculus viewport offset after disconnect while SteamVR is running

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1529]
## Describe the bug
If an Oculus headset running the Oculus native runtime is disconnected while SteamVR is also running, upon being reconnected the viewport will be offset to the position and rotation where the headset is reconnected.

## Relevant issues
N/A

## To Reproduce
- Use an Oculus headset, e.g. Quest via Oculus Link
- Ensure SteamVR is running
- Launch Neos Launcher from the Steam library and ensure the Oculus Rift/Oculus native runtime is selected
- Disconnect the headset's USB cable
- SteamVR will pop up an error about the device being disconnected
- Reconnect the cable, and re-open Oculus Link
- When the device is reconnected, the viewport will be offset from the avatar based on the headset's new position and rotation

## Expected behavior
The viewport should remain attached to the avatar.

## Screenshots / Video
https://youtu.be/e3H9-8IsarE

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Neos Version: 2020.12.24.35
 - Neos Platform: Windows, Oculus native runtime
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
This issue does not appear to occur if SteamVR is not running (e.g. only Oculus native launched outside of Steam(VR)/without SteamVR running).
[SHIFTYWINDOWS - 2020.12.24.35 - 2020-12-23 19_05_19.log](https://github.com/Frooxius/NeosPublic/files/5737934/SHIFTYWINDOWS.-.2020.12.24.35.-.2020-12-23.19_05_19.log)
[Player.log](https://github.com/Frooxius/NeosPublic/files/5737936/Player.log)

By examining the gizmos/tracked device positions, etc. it appears that Neos doesn't recognize anything as having moved at all. E.g. my viewport is entirely outside of the bounding box of my avatar, and all UI interactions, movement, etc. still operate as though I am in my original position and rotation, it is strictly the in-HMD view that is offset.

## Reporters:
The issue was most recently reported by Little Helper# 2043, although has previously been reported by others including Electronus# 5305.

I accidentally discovered this replication case while checking/verifying other Oculus-related issues that have recently been fixed.

Hopefully this helps!

**Comment by shiftyscales** [comment]
Considering this issue can be mitigated by ensuring SteamVR isn't running, and also the possibility that this is an issue external to Neos itself (possibly Unity-related) I'm marking this as low-priority.

**Comment by Frooxius** [comment]
Yeah this sounds like something external, not sure it's something we could fix on our end, especially since the positions that Neos is getting from the API seem to be still valid, but Unity's rendering is not. It'd be interesting to see if this can be replicated in vanilla Unity application for that, we could report it to them then.

**Comment by FirrSkunk** [comment]
only throwing a comment up here cause I discovered this while working on my own unity stuff, but this has been resolved as of steamVR update 1.18 https://store.steampowered.com/news/app/250820/view/2984179841817311398

**Comment by shiftyscales** [comment]
Ah, fantastic! Thanks for the update, @FirrSkunk. Closing this issue, then. :)
