### ISSUE TITLE
Specific user randomly gets massive, and on respawn fails to spawn and is put into limbo forever

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#1544]
## Describe the bug
A user (PlasmaRaven) often has strange behaviors where their avatar is... unpredictable (either invisible, massive, or doesn't exist), resulting in them being locked in place or unable to move. When respawned in this mode, the user doesn't re-create a user root and the user is forced to quit the game (Unsure on if all of neos, or just the session). They may be unable to hear the world in this state, and either way they're very stuck.

## Relevant issues
Unsure.

## To Reproduce
Have PlasmaRaven hang out for a while, this has apparently plagued them since they started playing.

## Expected behavior
Their experience is a happy one, and if nothing else they can be respawned once they enter this invalid state.

## Screenshots / Video
They sent me two logs, I'm going to include one of them cause the other is 32mb.
The log that's here is what happened in my world, where this behavior occurred and I saw they no longer had a user root (this was confirmed in the inspector, and on their user component as it had no root assigned.

PlasmaRaven's log.
[DESKTOP-8B1L594_-_2020.12.24.35_-_2020-12-30_01_08_58.log](https://github.com/Frooxius/NeosPublic/files/5753716/DESKTOP-8B1L594_-_2020.12.24.35_-_2020-12-30_01_08_58.log)
(The 32mb log is from before that point, let me know if you want that copy as well)

My corresponding log.
[DESKTOP-5HFQ42U - 2020.12.24.35 - 2020-12-29 18_28_36.log](https://github.com/Frooxius/NeosPublic/files/5753720/DESKTOP-5HFQ42U.-.2020.12.24.35.-.2020-12-29.18_28_36.log)

Here is what their user root looked like after I tried to respawn them.
![User No Respawn](https://user-images.githubusercontent.com/1251609/103342561-a749ee00-4a3e-11eb-940f-f40154cfd863.png)
I did not get good diagnostics when the error occurred, they even warned me that it would keep them from respawning but I failed to listen. If it happens again I'll get traces of their hierarchy.

## Bug information (please complete the following information):
 - How often does it happen: Reported as consistently.
 - Neos Version: Beta 2020.12.24.35
 - Neos Platform: Windows, see the logs for the rest.
 - Link to reproduction World/Item: The user is the reproduction item, so duno.
 - Regression: They have been around for a bit, and this has apparently been an issue through their entire stay in Neos.

## Additional context
I had them do a web request with powershell to the neos api, it worked successfully.

## Reporters:
PlasmaRaven U-PlasmaRaven PlasmaRaven#5882
Earthmark U-Earthmark Earthmark#0314

I'm just filling out the report for them.

**Comment by Frooxius** [comment]
Do they have any significant amount of queued packets when this happens? When they get respawned and the user root is not recreated at all, is it missing even from the perspective of the host?

That's probably most peculiar part of this, since the user root should just be remade regardless of everything, since respawn is pretty much a complete wipe of the user. Sometimes if the user has lots of queued packets, they won't "see" themselves recreated until a while later.

Whatever is causing that might be causing the avatar misheavior as well.

**Comment by Earthmark** [comment]
In the case of the logs and the screenshot I'm the host, so if the user root is created by the host then something real strange is happening. 
They said they're creating a GitHub to provide more context, I may have misunderstood some of what happened.

**Comment by PlasmaRaven** [comment]
in my home world it doesnt do it at all its radom when it happens i think

**Comment by PlasmaRaven** [comment]
like i was just on in my friends world and it didnt do it but then evently it probbly will do it again

**Comment by Frooxius** [comment]
What about the queued packets? That's the most important indicator / potential source here. If they have those, it might also take a while for the respawn request to be registered as well.

**Comment by Earthmark** [comment]
I have yet to run into them in a context where the bug is occurring again, once it does I'll have an update for you.

**Comment by Earthmark** [comment]
PlasmaRaven had the bug in my world again, here's some additional details:

On join PlasmaRaven was queuing packets slightly, as is common on join.
![2021-01-01 18 08 14](https://user-images.githubusercontent.com/1251609/103468019-e3fd3a00-4d09-11eb-8b97-52215d633113.jpg)

However, it took a very long time for their avatar to spawn in, so they manually equipped their avatar. I was the host and was present in the world, so this is likely a latency thing related to first join.
We were unable to replicate the avatar spawn delay by having them rejoin the world, however we have not tried rejoining after a server restart (the assets were still in assets).

After they manually equipped an avatar, I think my local system equipped them into an avatar as well. I also think both of these things happened at the same time on our respective machines. This resulted in a duplicate equipped avatar bug, but with a funky side effect.

![2021-01-01 18 19 38](https://user-images.githubusercontent.com/1251609/103468030-0000db80-4d0a-11eb-890c-87b0b0b96c3a.jpg)

Unlike the duplicate avatar bug, one of the spawned avatars had it's scale set back to 1, instead of the standard scale for the avatar, 0.016. This resulted in one of the avatars being massive, and the other being super tiny inside the massive one.

![2021-01-01 18 10 07](https://user-images.githubusercontent.com/1251609/103468034-0a22da00-4d0a-11eb-93b7-88bce6ea0a17.jpg)

![2021-01-01 18 09 24](https://user-images.githubusercontent.com/1251609/103468037-14dd6f00-4d0a-11eb-9271-bd1e841ff203.jpg)
![2021-01-01 18 18 03](https://user-images.githubusercontent.com/1251609/103468039-16a73280-4d0a-11eb-88de-b10bed502f50.jpg)

We tried deleting the massive avatar, part of their leg IK was broken but the regularly sized avatar worked as expected. Past that we attempted to respawn them, and they respawned successfully with a user root.

So, we replicated the mega-avatar case and it looks like a flavor of duplicate avatar equipped bug, while the no-user-root case is still not tracked down yet.

For now they're going to try to not spawn in their avatar on join, and see if that mitigates the mega-avatar bug, however the multi-equipped avatar bug is still a problem here.

**Comment by Earthmark** [comment]
This is most likely due to a very high latency with low throughput condition.

**Comment by Earthmark** [comment]
Part of this behavior apparently happens reliably with Alizard, I will try to get some additional files. Their network also seems more stable.

In the end I do think part of the issue was a network connectivity one, but it seems there may be a side issue related to a user root getting set to null.

**Comment by Earthmark** [comment]
Nevermind, turns out they replaced their avatar and it no longer happens, and their avatar may have had strange systems in it. If I see this live again I'll make a new bug!

**Comment by PlasmaRaven** [comment]
Thats not true I didn't replace my avatar

Sent via the Samsung Galaxy Note20 Ultra 5G
________________________________
