### ISSUE TITLE
Expanded Session Invitation Permissions

### ISSUE THREAD

**Issue by LeDrascol** [Neos-Metaverse/NeosPublic#1548]
## Is your feature request related to a problem? Please describe.
Worlds that have been set to an access level that is above Registered (ex. Private) will prevent the use of invites that have not been sent by the host. 

This has multiple issues:
- Headless servers cannot easily send invites
- Host cannot invite non-contacts
- Host may be unavailable (ex. asleep/away)

The configuration option 'allowUserCloudVariable' will always allow accepting invites, but has different issues:
- Requires a group to set the variable
- Requires a headless host
- Requires manually whitelisting each user

## Relevant issues
N/A

## Describe the solution you'd like
These are multiple possible sugguestions and not requests.

### Solution A
Adding a permission or other type of setting to always specified users to always send invites.

Possible types:
- Anyone can invite
- Contacts of host can invite
- Contacts of Contacts of host can invite
- Only host can invite

### Solution B
The session visibility and join-ability could be separated to allow more fine grained control over access. This would be similar to the Hidden setting, but without removing all visibility.

### Solution C
Allow 'allowUserCloudVariable' for user hosted sessions, and without group cloud variables.

## Describe alternatives you've considered
See above.

## Additional context
Updated to use new formatting.
This change may require #289 (Hard Permissions) to be implemented first.

**Comment by Bontebok** [comment]
Just tossing my hat into this one. I was not aware that the ability to hide a session from listing and join a session from URL was mutually inclusive until today (the option text is somewhat misleading). In reviewing related feature requests, it appears that there are a number of requests that have been tied together ranging from simple to very complex invitation systems, invite requests etc, so I won't gum up the works by submitting another one.

I do recommend that Option B in this request should be considered as in interim solution before overhauling the session/invite system. By splitting up the "Don't show in session lists" option into two separate options, this would provide users the ability to allow session links to remain active, but would allow a world to be hidden from the session listing.

Suggestion on the behavior for option B -

Under world settings - 

"Don't show in session lists" (as-is option)
"Allow users to join from session link" (new option that is grayed out until the above option is checked, value unchecked by default)

By selecting "Don't show in sessions lists" AND by checking "Allow users to join from session link", this would allow session links/orbs to be used to join worlds but would allow the world to remain hidden from both the world session list and from user contacts etc. Thereby creating the ability to keep a world limited to those that have the session link.
