### ISSUE TITLE
Expanded Session Orb Controls

### ISSUE THREAD

**Issue by LeDrascol** [Neos-Metaverse/NeosPublic#1549]
## Is your feature request related to a problem? Please describe.
Session orbs are a nebulous feature with no predictible or controllable behavior. As with other core world features, control for this should be exposed to world hosts.

## Similar issues
Issue #1589
Issue #1419

## Describe the solution you'd like

Potential sugguestions:
- Toggle session orb image screenshots
- - Enable only when world is public
- - Disable in invites
- Set update interval
- Set camera transforms (position)
- Follow user camera (for streaming)

Potential overrides sugguestions:
- Static 2D texture as session thumbnail
- Static 2D image from camera anchor point

Other potential sugguestions:
- Automatically refresh session orb on access level change
- LogiX Node: Force screenshot update

These are only sugguestions and not requests.

## Describe alternatives you've considered
See above.

## Additional context
Updated to use new formatting.

**Comment by SnooperXP** [comment]
Another possible feature to add to this would be a camera or location override, so that when the picture is taken it is always taken from that point / camera.

**Comment by TehTurk** [comment]
I don't know if this would necessarily be added, the Session Orbs are supposed to be automatic a bit more in their usage(Like Portals), and it also acts a deterrent for inappropriate events in worlds, but also supposed to be a glance mechanic at most.

**Comment by Frooxius** [comment]
This wouldn't be feature for the session orbs, those just serve to display the world information, but world itself. I do plan on adding a set of components that will help provide the thumbnails, but there's quite a few things you're requesting in this one, so I'm not sure if we'll cover everything.

**Comment by LeDrascol** [comment]
My suggestions are intended to cover multiple (possibly mutually exclusive) possible outcomes, and not meant to request all listed features. Please do not consider this a strict request.
