### ISSUE TITLE
"Dashboard in use" visual

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1551]
## Is your feature request related to a problem? Please describe.
It is not always apparent when a user is inside of their dashboard which can create some socially awkward situations, and disruptions, e.g. another user approaching the user in their dashboard.

## Describe the solution you'd like
Inspired by the SteamVR dashboard visual that GoodVibes had made, and Nexulan has also been using, a small head-bound visual on the avatar will let other users in the session know when the user is in their dash similar to how the bubble around a user's head appears when they're recording a voice message, or their materials change when they're away from the world/ or their headset.

If possible, it may also be useful to add detection for other dashboards such as the SteamVR and Oculus dash as well.

## Describe alternatives you've considered
Discussed in world with @Frooxius, other issues such as #984 would help with the practical aspect of the dashboard being blocked- but this issue would help deal with the social issues.

Something else worth considering is that there may be contexts in which it doesn't make sense to have it enabled, e.g. in the future if the dashboard positoning can be fixed in place in the playspace/be always open while the user is doing other things.

## Additional context
Screenshots of GoodVibe's implementation of this feature that inspired this request, used to detect when he's in the SteamVR dashboard:

![DashIndicator1](https://user-images.githubusercontent.com/54213390/103436132-4ac90900-4bcd-11eb-9ce9-7af5db4ce156.png)
![DashIndicator2](https://user-images.githubusercontent.com/54213390/103436133-4c92cc80-4bcd-11eb-9206-0c72e9d59bb9.png)

**Comment by TehTurk** [comment]
If this is considered I'd also like to note, please have this option be optional? While it's nice to have a visual like this, it should be also up to the player whether they'd like to present that or not.

**Comment by shiftyscales** [comment]
> 
> 
> If this is considered I'd also like to note, please have this option be optional? While it's nice to have a visual like this, it should be also up to the player whether they'd like to present that or not.

@TehTurk - if it's treated like the other visuals, it could likely just have a material you specify for it in the same way you can customize your whisper bubbles, etc- you could instead 'disable' it by changing the material accordingly.

**Comment by shadowpanther** [comment]
Now that we have nodes for detecting Neos's and System's Dash status (#2640), the visual is easy to add and the community already started doing their own versions. Do we need this out-of-the-box officially on the Avatar Creator (like the whisper bubble) or is the new LogiX functionality enough to cover this issue?

**Comment by TehTurk** [comment]
I would argue the later is good enough. Having a default visual should ultimately be left to users if they "want" it Because I know plenty of people who scroll or pantomine menus when talking and the social implications of knowing someone is in their dash while talking can indicate someone isn't paying attention. (I do this myself but I use my dashboard and multi task quite often but don't want people feeling like they are ignored) @shiftyscales are we ok to close this then?

**Comment by shiftyscales** [comment]
I think until such point as we see mass/widespread adoption of this on avatars, it's probably best left as a community-made extension/tool. As has already been noted, there are easy ways for those that wish to create such a visual to make one, and for those that dont desire it, it'd be easier to just not install something than it would be to install a custom visual to disable it.

I'll consider this as resolved for now.
