### ISSUE TITLE
Open World node misbehaves when trying to send headless user to a session.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1619]
## Describe the bug
When using the Open World node to send a headless user (host user on a headless session) to a different world, it fires the On Open Start event but then doesn't fire any of the others.

## To Reproduce
Open a headless session and create an Open World node. Give the node a session url to an open session and pulse it for the headless user. The On Open Start event will fire but none of the others do and the headless user does not arrive in the specified session.

## Expected behavior
The On Open Fail output should be pulsed as the node indicated that it started opening the world but then didn't finish that.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.17.1026
 - Neos Platform: Probably Any
 - Regression: Not sure

## Reporters:
Cameron#7818

**Comment by Frooxius** [comment]
The OpenWorld node is a bit weird to use on headless in the first place, so I'm not fully sure what to do about this. I can block its functionality on headless altogether, but it's still open as some people are experimenting with this. Joining other worlds isn't really something you can do on headless.

**Comment by Psychpsyo** [comment]
I'd expect it to just not work on a headless user as it does right now but instead of not giving any output after the initial pulse, it'd trigger the on fail output since it failed to open the world for the specified user. That way, logix systems that try to send an arbitrary user can expect the node to always return either success or failure.
