### ISSUE TITLE
Camera in Neos Essentials doesn't rotate portrait oriented pictures.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1620]
## Is your tweak request related to a problem? Please describe.
When taking a picture with the default camera from the Neos Essentials folder, the resulting picture won't actually be rotated by 90° when you rotated the camera while taking it. In-game this is mostly fine but it can get annoying when exporting the picture.

## Describe what would you like tweaked
Make the camera create rotated pictures when it is rotated while taking the picture.

## Describe alternatives you've considered
This could be done via Logix or components with a custom camera but replacing the default one wouldn't be possible.

**Comment by chemicalcrux** [comment]
Specifically, this should be done by setting the Orientation tag in the image metadata. Pretty much any modern application will display the resulting image correctly.

**Comment by Frooxius** [comment]
This is not specific to the camera in Neos Essentials, but rather the underlying InteractiveCamera component. We could add a mode that detects vertical orientation, but it's a bit tricky on how to actually handle this. We could rotate the texture itself, which would be most direct as the data wouldn't need to be interpreted by other software. 

Another is to include metadata, but that does require everything using the texture to actually rotate it.

**Comment by shiftyscales** [comment]
Also related: #1372

I think having a method for detecting a vertical orientation, and rotating the texture data/dimensions of the photo would be the most elegant solution. There doesn't seem any specific need to emulate the processing method/optics of digital cameras in the real world 1:1.
