### ISSUE TITLE
Cloud data storage operations

### ISSUE THREAD

**Issue by Toxic-Cookie** [Neos-Metaverse/NeosPublic#1621]
## Is your feature request related to a problem? Please describe.
There is currently no way of serializing and deserializing generic data from the cloud storage of a user. Any such storage currently must be done using an external server.

## Relevant issues
As mentioned in this [conversation](https://discord.com/channels/402159838827905024/477711742001086505/681131272625717308), collections, serialization/deserialization nodes, and Asset ID are required first.

## Describe the solution you'd like
There should be a section of user storage dedicated to storing generic data that can be read and written to using LogiX. Of course a pop-up window asking if it's okay to do any read or write operations should appear just like they do for http operations.

There should be a way for the user to view this directory of stored data and be able to do things like manually reading, editing, moving, renaming, and deleting data. There should also be a way to restrict data operations by the user or other unauthorized parties to prevent cheating or other mishaps. However, the user should still always be able to manually delete the data outright.

## Describe alternatives you've considered
External servers work for general data storage but it would be incredible to have this natively supported in Neos.

## Additional context
A conversation between me and @Frooxius about [this](https://discord.com/channels/402159838827905024/477711742001086505/681131272625717308) a while ago.

**Comment by StarfishHidari** [comment]
This would be an extremely nice feature to have and would open up a lot of opportunities for interactivity. Having to use an external server for this kind of stuff but it makes maintaining things like that difficult and cumbersome.

**Comment by Frooxius** [comment]
There is something that's planned and partially implemented. Neos has concept of "cloud variables", it is used internally for a few things, like setting your favorite avatar and such.

There are a few main things that need to be designed first - who can create the definitions and how. This is something that could be abused, so some limitations need to be put in place first. This also involves who can actually write into those variables - anyone could make logic that freely writes user's variables, which is another potential source of abuse or people messing up with things.

Another part are bindings - making the system easily accessible and propagate the changes (e.g. if you have a cloud variable that's shared across worlds, you might want it to be updated immediately if any of the worlds mutates it). Adding a push notification system for this would be crucial to do this efficiently.

**Comment by Frooxius** [comment]
Added Cloud Variables in 2021.4.27.1385!
