### ISSUE TITLE
VR Flip Flops (VR Hardware Accessory simulates realtime walking)

### ISSUE THREAD

**Issue by GearBell** [Neos-Metaverse/NeosPublic#1623]
Im not sure how these things go... Im supposed to drop a link for a vr hardware accessory thing?... here, vr flip flops that simulate realtime walking? just an idea for a new interactive thing neos could do. https://www.cybershoes.io/

**Comment by shiftyscales** [comment]
Without an SDK, access to the hardware, or contact/support from their developers, there's not really anything that could be done to integrate this.

The driver for the hardware can be found here: https://store.steampowered.com/app/1222360/Cybershoes/

But it appears this hardware is made more for converting existing experiences than integrating any support directly for it, so there's not really any relevant work that can be done on Neos' end for this.
