### ISSUE TITLE
Headless server requesting shader variants and failing in a loop

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#1629]
## Describe the bug
After shader variants were migrated to neosdb:, headless server tries to retrieve variants of shader it doesn't really need (it doesn't render anything), failing to find those and retrying in a loop. Tens of errors every second in the log:

```
GatherJob for neosdb:///c703f4e66ffdc9c6221631e10e00197d99f85f7c55c5cd0523210a5c5b5f128e.neoshader?variant=00000A02&platform=LinuxOpenGL FAILED! Reason: NotFound
GatherJob for neosdb:///0837e3a34031f69684c7075d913653c4fb2a0b5f414c85e31ea23f0346c6612b.neoshader?variant=00000000&platform=LinuxOpenGL FAILED! Reason: NotFound
GatherJob for neosdb:///6506561ce1855114f98b21544848902f4c3614c398d5ec5128a81cf65eeb2dcf.neoshader?variant=00000002&platform=LinuxOpenGL FAILED! Reason: NotFound
GatherJob for neosdb:///e9373be5f5403c18034405c22530ee0138e55796a95bff7f790c5942ba1979a6.neoshader?variant=00000008&platform=LinuxOpenGL FAILED! Reason: NotFound
GatherJob for neosdb:///df6df774848b4161bdb0d7ff3768e61cf2dc636e572e9b5cbd9ba00e8a9e1e7d.neoshader?variant=00000004&platform=LinuxOpenGL FAILED! Reason: NotFound
GatherJob for neosdb:///91f20b8d2874174c83dcf92c1d15b79ba841e6cdaa160e2c580df090bc0d2080.neoshader?variant=00000003&platform=LinuxOpenGL FAILED! Reason: NotFound
GatherJob for neosdb:///e9373be5f5403c18034405c22530ee0138e55796a95bff7f790c5942ba1979a6.neoshader?variant=00000002&platform=LinuxOpenGL FAILED! Reason: NotFound
```
and so on, repeating every request every several seconds.

## To Reproduce
1. Update headless.
2. Run headless
3. Probably load the world
4. Observe

## Expected behavior
Headless doesn't try to retrieve shader variants (because it doesn't need any), stops trying after several attempts or schedules retries with increasing intervals to not spam the log and flood the cloud.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.21.1068
 - Neos Platform: Linux

## Reporters:
Shadow Panther#5154

**Comment by shadowpanther** [comment]
Resolved after the cloud update. Headless logged some fails on world load, but that only happened once.

**Comment by shadowpanther** [comment]
I guess it wasn't really resolved, as today I found these in the log while hosting the Metaverse Meetup session:
```
GatherJob for neosdb:///f0117668e74e103898ad30f85e6d6302825240be40f8ecfaf7d62b16e0c68590.neoshader?variant=00000130&platform=LinuxOpenGL FAILED! Reason: NotFound
GatherJob for neosdb:///101af37fba0a214e91ec769f866e932e1e639f80996953f2a924386b3af49d54.neoshader?variant=0000004B&platform=LinuxOpenGL FAILED! Reason: NotFound
GatherJob for neosdb:///101af37fba0a214e91ec769f866e932e1e639f80996953f2a924386b3af49d54.neoshader?variant=0000006D&platform=LinuxOpenGL FAILED! Reason: NotFound
GatherJob for neosdb:///f0117668e74e103898ad30f85e6d6302825240be40f8ecfaf7d62b16e0c68590.neoshader?variant=00000110&platform=LinuxOpenGL FAILED! Reason: NotFound
GatherJob for neosdb:///f0117668e74e103898ad30f85e6d6302825240be40f8ecfaf7d62b16e0c68590.neoshader?variant=0000007C&platform=LinuxOpenGL FAILED! Reason: NotFound
GatherJob for neosdb:///f0117668e74e103898ad30f85e6d6302825240be40f8ecfaf7d62b16e0c68590.neoshader?variant=0000004C&platform=LinuxOpenGL FAILED! Reason: NotFound
GatherJob for neosdb:///101af37fba0a214e91ec769f866e932e1e639f80996953f2a924386b3af49d54.neoshader?variant=0000006F&platform=LinuxOpenGL FAILED! Reason: NotFound
```

Constantly repeating, about one line every second.

**Comment by shiftyscales** [comment]
From what I've heard from other cases, I believe this issue resolves itself if a user clears their local database. Has the local database/PC you're using used the GUI/non-headless version of Neos at all?

**Comment by shadowpanther** [comment]
No, that's an entirely headless server, it doesn't have a graphical environment, it doesn't have a GPU, it even isn't connected to a monitor. I can try removing the database tomorrow, as the essential configuration is in the config file. Weird that this issue wasn't there since January, but also I didn't host this world before. My usual world doesn't give me those errors.

**Comment by shiftyscales** [comment]
It would be helpful if there is a particular usage pattern that causes this issue to emerge in the first place I think.

**Comment by shadowpanther** [comment]
Right now I can only say that it started after I added a second world to my headless's config - the one the Metaverse Meetup is taking place in today. I'll try to test if it's reproducible.

**Comment by Frooxius** [comment]
The asset variant system generation was down for a day or so due to a power outage, so it wasn't generating new variants for those. It should be good now, I've started up the machine again. Sorry for the trouble. Reopen if you still encounter the issue.
