### ISSUE TITLE
Retry all current Gather Jobs 

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#1660]
## Is your feature request related to a problem? Please describe.
Sometimes gather jobs fail to load in a decent amount of times making some stuff never load in until you reload the world or wait a significant amount of time.
## Relevant issues
-

## Describe the solution you'd like
Button in the gather jobs menu.
Debug Menu -> Gather Jobs -> "Reload" which would reload all current gather jobs.s

## Describe alternatives you've considered
Reload the world.

## Additional context
-

**Comment by TehTurk** [comment]
This likely won't get added as I've even asked for something like this as well too. Oft not when gather jobs get stuff it's asked to figure out what's causing them to better facilitate their processes

**Comment by Frooxius** [comment]
Unfortunately this is not feasible to do, if the GatherJobs already fail like that, they're gone. This isn't something that should be exposed to user in the first place anyways, as the GatherJobs have their own retry logic already, if that fails several times, the system will assume that the asset can't be gathered and will clear them out, otherwise the performance would degrade over time as they accumulate.

What kind of GatherJobs are failing for you? What URL types are they (neosdb:// local:// http(s)://)? Knowing more about such cases can help make the retry logic more robust and see if there's some missed error handling that leads to them not working.

**Comment by 3x1t-5tyl3** [comment]
So. I don't know how it works in the background. But what I do know is that sometimes with certain connects (I assume due to packet loss) assets gets stuck transmitting data at the very beginning (-1kb or whatever) and just stay stuck there. Though it's difficult to tell exactly what items those are and most often than not it takes a few minutes to clear those out.
That being said. I don't know the dismissal rate. I just know it's in the few minutes range given I'm not sure sometimes if it loads or gets dismissed. That said most typically it's **neosdb** types. I'll try to find more as I go. Though it's difficult to reproduce sometimes.
Feel free to close this issue I'll see what I can find tho.

**Comment by Frooxius** [comment]
Packet loss shouldn't definitely be a factor in this at all, all the transfer methods are using reliable packet transfer, which re-transmits any lost packets.

-1 just indicates that the download/transfer hasn't started yet and it's waiting in the queue. When this happens, are there any assets that are currently transferring at all?

It's interesting that it's the neosdb:// ones, those should generally be pretty robust on the downloads, but from the description it sounds like they haven't even started downloading in the first place. Knowing if there are any active transfers or what the head of the queue looks like would be useful - if you can take a screenshot of the GatherJobs dialog when this happens again that could help diagnose more.

**Comment by Toxic-Cookie** [comment]
I experienced this not too long ago. After crashing in a specific world, I rejoined it and the gather jobs stopped at 50/400. They wouldn't finish and they locked up the rest of the threads so UI was dead as well. The only solution was to clear the cache to force the jobs to gather again.

**Comment by 3x1t-5tyl3** [comment]
https://i.imgur.com/5bUzaPY.png Have a screenshot here. The user who uploaded this left the session.

**Comment by Frooxius** [comment]
I've fixed the issue in 2021.4.9.1114, the transfers should now be much more reliable!
