### ISSUE TITLE
Batch material type conversion

### ISSUE THREAD

**Issue by Veer-NeosVR** [Neos-Metaverse/NeosPublic#1661]
## Is your feature request related to a problem? Please describe.
Yes, when importing a large object with many materials, it can take quite a while to convert the material types to a specific kind, ie: converting PBS metallic to PBS specular needs to be done one-by-one, by hand, with no batch operation available.

## Relevant issues
None found

## Describe the solution you'd like
A batch material conversion option, either in the material tool when holding the root of an object with multiple materials, somewhere in the inspector, or elsewhere wherever relevant.

## Describe alternatives you've considered
N/A

## Additional context
This would be useful in cases where users would want to see what their entire world would look like converted to different material types such as Xiexe toon, PBS Specular, Unlit etc or doing the same to an avatar to ensure all parts and accessories are the same material type.

**Comment by TehTurk** [comment]
To add on from the previous issue just mentioned. Batch Converting would be handy, but the question is how to do it in a consistent manner. Perhaps by while referencing a skinnedmeshrender, being able to use the convert to button on a held reference in some form.

**Comment by RoxyBoxxy** [comment]
Just a FWI issue 1793 has nothing to do with batch converting

**Comment by Frooxius** [comment]
Added in 2021.5.22.1024, thanks!
