### ISSUE TITLE
Light Tip's 'Change Color' dialogue not relative to scale

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1682]
## Is your tweak request related to a problem? Please describe.
The Change Color dialogue on the light tip opens at a fixed size and ignores user/tooltip scale which becomes an issue when people are too big or too small.

## Describe what would you like tweaked
Make the menu spawn at relative scale to either the user or the tooltip itself.

## Describe alternatives you've considered
Keeping it like this and manually scaling the menu every time.

**Comment by shiftyscales** [comment]
A similar issue was just opened for the material tooltip at #2081. Except unlike this issue, that issue overcompensates for the user's scale instead of not compensating for it like this issue.
