### ISSUE TITLE
Deleting an object someone is grabbing onto causes their position to no longer be synced to other clients

### ISSUE THREAD

**Issue by RileyGuy** [Neos-Metaverse/NeosPublic#1725]
## Describe the bug
Deleting an object someone is grabbing onto causes their position to no longer be synced to other clients

## Relevant issues
N/A

## To Reproduce
1) Allow world grabbing
2) Grab onto an object
3) Have someone else pick up the object the other is grabbing onto
4) Delete the object
5) The person who was grabbing the object will no longer have their position synced

## Expected behavior
The position of the user who was grabbing the now-deleted object should still be synced

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.4.348
 - Neos Platform: Any
 - Link to reproduction World/Item: N/A
 - Regression: Yes, before the update that introduced networked user roots.

## Reporters:
Discovered by Shire, brought to June and I's attention

**Comment by Frooxius** [comment]
Fixed in 2021.3.5.176, thanks!
