### ISSUE TITLE
RenderTextAssest Logix Node misbehaves in the Local Userspace

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#1736]
## Describe the bug
I was attempting to make a screenshot utility to make it easy to screenshot your dash in some sort. I ran into some trouble as nothing at all was rendering. I suspect this is due to the RenderToTextureAssest Node

## To Reproduce
1. Setup Camera to Mimic the Dash Camera (Same Excat Settings/Transforms)
2. Input the Selective Render to be either the Visuals or Render
2. Proceed to have Logix activate to Render an Image into a Texture
3. No Matter what the Texture will ignore the dash.
4. Even enabling show Private UI will not enable it to be considered

## Expected behavior
1. Ideally when I pulse the node, it should be rendered into the Texture Object I set with the URL.

## Bug information (please complete the following information):
- Seem pretty consistent, but working with facets within the dash without tools is a bit tricky, so I may have missed some cases.

**Comment by shiftyscales** [comment]
I'm not certain, but this sounds like something that may be by design as a potential security consideration.

**Comment by TehTurk** [comment]
Hmm maybe, but the thing is image data isn't something you can send too easily, and if your ever trying to export data out of the dash your gonna require some sort of access request. I wanted this in mind due to taking screenshots for my dash so I could show or showcase how a dash can look.

**Comment by Frooxius** [comment]
@shiftyscales Is correct, this is intentional security measure. Private UI is excluded from being rendered except in specialized cases, since this could potentially leak personal information.
