### ISSUE TITLE
the cast from url to string seems not to work

### ISSUE THREAD

**Issue by Ardescar** [Neos-Metaverse/NeosPublic#1750]
## Describe the bug
When doing a cast from a URL datatype to String the resulting string is null.

## Relevant issues
didnt find any issues to this

## To Reproduce
Just simply create a cast URL to String.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/63201013/107892069-f9799c80-6f22-11eb-9ea2-37e31fd9e50a.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: several
 - Neos Platform: Any

## Additional description

I tried to save the URL into a string for later use - but it always did only show null.

And before i tried to use fire-on-change on URL and also this didnt work.
So i guess fire-on-change does a internal cast - and also this is affected.

## Reporters:
Ardes - Ardescar#2046

_And i discussed this with:_
3x1t_5tyl3 - 3x1t_5tyl3#0001 
Tekno Catron - Tekno Catron#8745 

## Additionally :
I also encountered this bug several times allready in that same project -> https://github.com/Neos-Metaverse/NeosPublic/issues/918

**Comment by shiftyscales** [comment]
I don't know enough on a technical level yet to know why/if it isn't possible to cast directly between those types- but I do know that if you use `To String` it should solve the needs of this issue.
![2021-02-15 00 43 11](https://user-images.githubusercontent.com/54213390/107923964-14e6a680-6f27-11eb-8058-56965bf2bc95.png)

**Comment by TehTurk** [comment]
I think it might have to do with the object space without an internal cast being considered for the type conversion. I remember it being requested before so you might find more information in the discord or a previous issue @shiftyscales

**Comment by shiftyscales** [comment]
> Uri's are not castable to a string, because they're not a string. Use the ToString node.
https://github.com/Neos-Metaverse/NeosPublic/issues/2464#issuecomment-860100208

**Comment by Ardescar** [comment]
There was also a question for fire on change - if there is a internal cast to something? Because it didnt work.
