### ISSUE TITLE
Current Culture outputs en-US when game is set to Esperanto

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1758]
## Is your tweak request related to a problem? Please describe.
I'm trying to set something based on the user's locale but the Current Culture node doesn't distinguish between Esperanto and American English.

## Describe what would you like tweaked
Make the Current Culture node output a code other than en-US for Esperanto, which should probably be eo or eo-US.

## Describe alternatives you've considered
Not being able to distinguish Esperanto and American English.

**Comment by Frooxius** [comment]
This is unfortunately a limitation of the version of Mono embedded in Unity, it doesn't have proper definition of the Esperanto locale, so it falls back to the English one that's available.

Either the Mono version in Unity needs to be updated or we'll have to move to a more modern .NET runtime which has this properly implemented.
