### ISSUE TITLE
Please explain the functions of, and differences between, the DesktopMousePosition and MousePosition LogiX nodes

### ISSUE THREAD

**Issue by Zyzyl** [Neos-Metaverse/NeosPublic#1762]
## Where have you searched for this information before making this issue?
- Wiki
- Searched for past mentions and also asked in the Discord logix channel
- My own testing

## What information do you need to know?
1. What is the meaning of the float2 output value from each node?
    1. In my testing it appears to be the cursor position in screen pixel units, starting from [0,0]
2. Under what conditions does the float2 output value change?
    1. In my testing I noticed the output for both nodes changes when in screen mode and the Neos window is _not_ focused. Also when using the desktop view in the dash.
    2. When using the desktop view in the dash, which laser point do the nodes respond to?
3. Relevant to 2, do these nodes work in userspace?
4. What is the difference between / intended different use case of these nodes?
    1. In my testing the only difference I have seen is that the Y output appears to have the opposite origin.
5. Any addition information users should be aware of.

## Do you plan to format and contribute the provided information to Wiki?
Yes, I'm asking specifically to help me fill out https://wiki.neos.com/Desktop_Mouse_Position_(LogiX_node) and https://wiki.neos.com/Mouse_Position_(LogiX_node)

**Comment by mralext20** [comment]
my current running theory is the following:
- mouse position is relative to the bottom left of the Neos window
- desktop mouse position is relative to the top left corner of your primary monitor (maybe not the top left of all monitors)

this is further 'proved' by these screenshots: ![](https://this-is-a.stale-me.me/i/i27r.jpg)  ![](https://this-is-a.stale-me.me/i/albn.jpg)

**Comment by ProbablePrime** [comment]
I confirmed this by looking in code. I'm not 100% clear but I can see code that updates the desktop mouse position when you switch between desktops and a few other things like that. 

@Zyzyl you should be able to document these on the wiki now. If you need assistance please do let me know.

**Comment by Zyzyl** [comment]
Ooh, we get assignments now! Thanks Alex and Prime, I'll close this when I've sorted those pages out this weekend.
