### ISSUE TITLE
Add a command to return Transaction history for an account

### ISSUE THREAD

**Issue by mralext20** [Neos-Metaverse/NeosPublic#1766]
## Is your feature request related to a problem? Please describe.
in the united states, it's tax season! as such, i would like a simple way to see a 'ledger' of sorts for the NCR and CDFT transactions against my account.

## Relevant issues
#235 maybe? same root cause of concern. 

## Describe the solution you'd like
a command, capabe of being sent to the Neos Service Account, that would email a json or csv or similar of any NCR/ CDFT/KFC transactions that have occurred. 
## Describe alternatives you've considered
going through my contacts, chekcing the message history for NCR transactions, and building a ledger myself

**Comment by Frooxius** [comment]
Added in 2021.4.9.1114! You can use /requestTransactionHistory <token>
