### ISSUE TITLE
Change wording of the "ban from all sessions" button

### ISSUE THREAD

**Issue by dotuser** [Neos-Metaverse/NeosPublic#1777]
## Is your tweak request related to a problem? Please describe.
This is a simple suggestion for a more precise, shorting wording that could be less confusing to users.

## Describe what would you like tweaked
Recommend change to wording of "Ban from ALL my sessions".

## Describe alternatives you've considered
Recommended wording of "Ban From Hosted" or "Ban From Own Hosted Sessions".

## Additional context
Adding this here as a footnote/idea since it was recently mentioned in the Discord as confusing by a couple users. Clearly low priority, but may be something one could sneak in as part of a larger/normal update.

**Comment by mralext20** [comment]
would probably (after being approved) be worth throwing a pull request on Frooxius/NeosLocale, here are the related lines:

https://github.com/Frooxius/NeosLocale/blob/master/en.json#L375-L376

**Comment by TehTurk** [comment]
This would be more ideal I agree.

**Comment by dotuser** [comment]
A stupidly late PR has been put in.

I forgot about this whoops.
