### ISSUE TITLE
Regression: Cannot Assign Material Reference held by laser in same hand. 

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#1781]
## Describe the bug
Tried to assign a material orb from the same hand I grabbed a reference from. This is not possible currently as I need to use my other hand. This is pretty big as it changes up a lot of the muscle flow.

## To Reproduce
[Steps to reproduce the behavior:
1. Get Material Orb Reference
2. Aim at Material Field
3. Click to Assign
4. Field is not assigned

## Expected behavior
It should assign from one hand.

**Comment by Frooxius** [comment]
What exactly do you mean by material orb reference? Are you getting reference to the material orb slot itself?

**Comment by TehTurk** [comment]
Yes! I'll have the reference in the same hand as I'm trying to assign from. I've found this behavior as an issue with out things as well from Textures, to Font, Sounds etc. I wonder if this was caused by another behavior change.

**Comment by Frooxius** [comment]
Why are you trying to use reference to the material orb slot, rather than reference to the material itself? Or does this happen even with that? I can have a look, but I'm a bit unclear on that reproduction step.

**Comment by TehTurk** [comment]
Ah sorry for the confusion. It's the reference to the Material itself. 
In the original post I mentioned "Material Orb Reference" was because due to the preview.

**Comment by shiftyscales** [comment]
Am I missing something Turk? I can't seem to replicate this issue.


https://user-images.githubusercontent.com/54213390/111252185-cda71080-85cd-11eb-9585-ae90f24fc165.mp4

**Comment by TehTurk** [comment]
Sorry about that! Here is video of me demonstrating the issue, my brain didn't realize it was sole-y laser input. Doh!

https://user-images.githubusercontent.com/26357446/112277414-1ad35400-8c58-11eb-94d6-ab95d9f66430.mp4

**Comment by Frooxius** [comment]
I found what the issue was, should be fixed in 2021.3.27.510, sorry it took so long!
