### ISSUE TITLE
Add Abbreviated Names to Finger Detection Heurestics

### ISSUE THREAD

**Issue by InsaneGrox** [Neos-Metaverse/NeosPublic#1783]
## Is your tweak request related to a problem? Please describe.
Currently, Fingers named with Abbreviations are not detected by Neos's hand detection.

## Describe what would you like tweaked
Add The following Abbreviations for the heurestics
Th/Thm/Thmb for Thumb
Ind for Index
Mid for Middle
Rin/Rng for Ring
Pnk/Pin for Pinky

## Describe alternatives you've considered
Can't really think of any aside from manually setting that up.

## Additional context
Seen several models with naming conventions involving abbreviations that don't get detected, including the Reverse Avali, and the old version of the Bestboy avatar, as well as several models I have created.

**Comment by Frooxius** [comment]
Neos already supports some of these, but I added the remaining ones that it didn't in 2021.2.28.1002

Can you check if it helps with the import? There's a fair bit more involved than just the names, so it might be running into problems elsewhere. If you have 5 fingers it shouldn't care about the names mostly at all.

**Comment by Frooxius** [comment]
In 2021.4.6.764 I've reworked the system a bit, which should ensure that those names are now used, please let me know if there are any more trouble!
