### ISSUE TITLE
Support more standard text editing keyboard shortcuts

### ISSUE THREAD

**Issue by Gawdl3y** [Neos-Metaverse/NeosPublic#1784]
## Is your feature request related to a problem? Please describe.
Currently, editing text in Neos is cumbersome, in part due to it not supporting many of the standard keyboard shortcuts for text fields. Making changes to existing strings is much slower than it could be. As far as I'm aware, the only shortcuts that are supported are for copy (<kbd>Ctrl</kbd> + <kbd>C</kbd>), cut (<kbd>Ctrl</kbd> + <kbd>X</kbd>), and paste (<kbd>Ctrl</kbd> + <kbd>V</kbd>).

## Relevant issues
Issue #136 is about a similar topic, but much more general and seems to be more targeted towards multiline/long text editing improvements. Additionally, this issue is likely much smaller in scope/less complex to implement since it doesn't require any changes to UI due to its nature (purely keyboard input).

## Describe the solution you'd like
Support the following standard keyboard shortcuts whenever editing a text field:
- ~~<kbd>Ctrl</kbd> + <kbd>A</kbd> to select all~~
- <kbd>Ctrl</kbd> + <kbd>Backspace</kbd> to delete to the previous word boundary (delete whole words at a time)
- <kbd>Ctrl</kbd> + <kbd>Del</kbd> to delete to the next word boundary (delete whole words at a time forwards)
- <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Backspace</kbd> to delete the entire line before the cursor
- <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Del</kbd> to delete the entire line after the cursor
- <kbd>Ctrl</kbd> + <kbd>←</kbd> / <kbd>→</kbd> to move the cursor to the previous/next word boundary (skip the cursor around to the next/previous word or end/beginning of current word)
- ~~<kbd>Shift</kbd> + <kbd>←</kbd> / <kbd>→</kbd> to expand/shrink text selection left/right (and also for up/down when multiline improvements are made)~~
- <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>←</kbd> / <kbd>→</kbd> to expand/shrink text selection left/right by word boundary (highlight whole words at a time)

## Describe alternatives you've considered
There are not really any alternatives to this.

## Additional context
These are standard keyboard shortcuts for editing text in applications running in all modern operating systems that I'm aware of, though there are likely some small differences in key combinations for Mac. This will be handy not only for playing on desktop, but also using the virtual keyboard in-game to speed up cursor navigation and such.

**Comment by Frooxius** [comment]
Hmm this is a bit strange, a bunch of these should already be supported. Particularly these two:
- Ctrl + A
- Shift + ← / →

Are they not working for you?

 I can add the rest, but I'm just wondering if there's something else that's wrong.

**Comment by Gawdl3y** [comment]
You're correct, those two are supported. I actually regularly used Shift + ← / →, but I guess I didn't realise that when I originally made the issue. My bad!

**Comment by Frooxius** [comment]
These should all be supported now in 2021.10.17.1326! Thanks!
