### ISSUE TITLE
adding light source import options

### ISSUE THREAD

**Issue by Elektrospy** [Neos-Metaverse/NeosPublic#1794]
## Is your feature request related to a problem? Please describe.
Its not directly related to a problem, i would consider it more like a quality of life feature :smile:

## Relevant issues
not as far as i know

## Describe the solution you'd like
Adding a checkbox under advanced settings of the import dialog,
which enables the inclusion of lights sources contained in the model, 
with similar settings as the light source wizard.

<img src="https://user-images.githubusercontent.com/15101742/109434677-bcc79e00-7a16-11eb-97e3-9755837df81e.jpg" width="300" />

## Describe alternatives you've considered
There are currently two alternatives, but bring there own share of problems. :wink:
- Importing the model into unity and upload trough the sdk into Neos
    - involves additional conversion prior to import, since unity only directly supports fbx files
    - the sdk is experimental and not every user has access to it
- Hand place and tweak all lights
    - time consuming and a lot of unnecessary additional work, if the same was already done on the model prior to bringing it into neos

**Comment by Frooxius** [comment]
Added in 2021.3.5.176, please give it a try. It's a bit tricky, because the light properties do not transfer 1:1 between different formats, so you might need to tweak them some afterwards with the light wizard. Let me know if there are any issues besides that with this.
