### ISSUE TITLE
HTML Tags (`<color>`/etc.) in world names are sent to Steam Rich Presence API instead of being stripped

### ISSUE THREAD

**Issue by shardwolfdotnet** [Neos-Metaverse/NeosPublic#1795]
## Describe the bug
When a user is in a world that contains HTML syntax in the name (e.g. `<color>` tags), the tags are sent as-is to the Steam Rich Presence API. Steam only accepts plain-text Rich Presence captions, so these tags are rendered as-is in the Steam Friends UI. These are unsightly and crowd an area with a relatively small amount of screen real-estate, so they should be stripped before sending to Steam.

## Relevant issues
None

## To Reproduce
1. Join a world containing HTML syntax in its name.
2. Wait for the Steam Rich Presence API to update - AFAICT this takes a minute or so.
3. Have a Steam friend check your status caption in the Friends UI.
4. Observe that the world name shown in the Steam UI contains HTML tags

## Expected behavior
The tags should be removed prior to sending to Steam.

## Screenshots / Video
![Screenshot depicting the existing presence caption sent to Steam Friends](https://user-images.githubusercontent.com/76196468/109447641-f9849c80-79f8-11eb-805b-13568758acf4.png)
For example, the displayed world name is `<color=red>Pleasant Hills: It's calm here</color>` - I'd expect this to be just `Pleasant Hills: It's calm here`

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.28.1210 (estimate, exact client version TBD)
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
It's possible this affects any HTML syntax at all (including escaped HTML entities) as I'm pretty sure I've seen that occur at least once in the past, but I wasn't able to capture that in this repro.

## Reporters:
@shardwolfdotnet [Discord: Shard Wolf#5513]
@earthmark

**Comment by Frooxius** [comment]
Fixed in 2021.3.5.176, thanks!
