### ISSUE TITLE
Non-default system audio device slowly loses sync

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1796]
## Describe the bug
While using a non-default audio output device, the audio will slowly drift out of sync.

## To Reproduce
- Set a non-default audio output device, e.g. for the new screen mode
- Press F8 to toggle the new screen mode/switch to the non-default audio output device
- Wait
- Audio will become increasingly out of sync

## Expected behavior
The audio maintains full sync throughout prolonged use when using a non-default audio output device.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.28.1210
 - Neos Platform: Windows
 - Regression: [Did this work before? No

## Additional context
Toggling back into VR/the system default audio output device, then back to the non-default device will sync the audio until it eventually drifts back out again.

## Reporters:
Shifty#7944

**Comment by Frooxius** [comment]
Fixed in 2021.3.5.176, thanks!
