### ISSUE TITLE
Mirror facet shows menu through it

### ISSUE THREAD

**Issue by Kathok** [Neos-Metaverse/NeosPublic#1797]
## Describe the bug
Main menu interface can be seen through a mirror facet 

## To Reproduce
1. Add mirror facet to main menu
2. Stand in front of the world origin looking through the mirror facet

## Expected behavior
The menu should not be rendered in the mirror

## Screenshots / Video
![image](https://user-images.githubusercontent.com/26034954/109598328-14353f00-7ae7-11eb-9fdb-3abc658d633e.png)
![image](https://user-images.githubusercontent.com/26034954/109598349-20b99780-7ae7-11eb-8f03-bd945a28bb1e.png)
https://cdn.discordapp.com/attachments/439422161657135106/815715194164478002/2021-02-28_17-37-16.mp4
https://www.youtube.com/watch?v=cw69SYLV9-E
## Bug information (please complete the following information):

 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.28.1210
 - Neos Platform: Windows

## Additional context
Only seems to be an show when using desktop mode

## Reporters:
EpicEaston197 (epicEaston197)#0793
Khosumi (Khosumi#3579)

**Comment by Frooxius** [comment]
Should be fixed in 2021.3.5.176! Seems to be general issue with mirrors. I don't have the facet at hand to test, but I'm pretty confident it should be good, Reopen if there's still an issue.

**Comment by Kathok** [comment]
I seem to still be able to see the menu 
![image](https://user-images.githubusercontent.com/26034954/110273839-7684b880-7f9b-11eb-86c0-087bb8804550.png)

**Comment by shiftyscales** [comment]
I believe the facet in question is the `Adjustable Mirror found in Inventory > Neos Essentials > Facets @Frooxius.
neosrec:///G-Neos/R-3121a368-1271-424c-a78e-e22912609261

**Comment by shiftyscales** [comment]
This should definitely be fixed now in `2021.3.12.44`:
> - Fixed Cameras rendering the overlay layer
-- This should fix the mirror facet from rendering the dash while the desktop mode is enabled (re-reported by epicEaston197 and Khosumi)
