### ISSUE TITLE
New Input System does not refresh broken LogiX nodes

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Neos-Metaverse/NeosPublic#1799]
## Describe the bug
While a LogiX node is broken, pressing Secondary does not restore the node to it's original state, rendering the node completely useless and needs to be respawned.

## Relevant issues
None known.

## To Reproduce
- Spawn a LogiX node that can be broken
- Cause the node to error by any means necessary (While True seems to be the easiest)
- Attempt to restore the node by pressing Secondary on it

## Expected behavior
The node should be restore to it's original state to be able to be used again without having to respawn it.

## Screenshots / Video
N/A

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.28.1210
 - Neos Platform: Only tested on Windows, though expect to be on any that the Input System exists on
 - Link to reproduction World/Item: N/A
 - Regression: Yes, before the Input System was introduced in build 2021.2.21.1425

## Additional context
N/A

## Reporters:
Hayden#3180

**Comment by shiftyscales** [comment]
@Hayden-da-Serg - I just tested this, and it's working properly for me. By chance are you using a custom Logix tip, or some other setup that differs from a stock configuration?

https://user-images.githubusercontent.com/54213390/110076962-383c8e80-7d3a-11eb-927f-39b7ca6b7eed.mp4

**Comment by Hayden-da-Serg** [comment]
That's interesting, using the default LogiX tip does work, the only thing that's different about mine is the model.
I'm using a slight visual edit to Ryuvi's default reskins.

**Comment by Aerizeon** [comment]
@Hayden-da-Serg  I've also encountered this issue, but with AlexFromAlaska's multitool - and like in your case, the default LogiX tip worked.

**Comment by Frooxius** [comment]
If I understand this correctly the only difference on the broken LogiX tooltips is the visual? No TooltipMultiplexer and such used at all?

What if you take a working version of the LogiX tooltip and make the same changes to it. Will it break? Identifying any difference between the working tooltip and your version is crucial for this. 

If you could, can you also display the input binding system debug information while replicating and check if there's any difference between the working tooltip and the broken ones?

**Comment by Hayden-da-Serg** [comment]
With a bit more digging this may be a one-off thing, the base version of Ryuvi's Logix tip reskin does not seem to work properly, though everything else functions on it.

I tested a lot of community Multitools as well (H3BO3's, 3x1t_5tyl3s's, The Architech, and the development version of my own) and they all functioned fine, even the auto-generated version of the Logix tip works fine.

The only difference I could see is visual, though I will check again to see if I missed anything.
There also appears to be no differences in the debug information when using the non-functional tool vs. any functional one.

**Comment by Aerizeon** [comment]
@Hayden-da-Serg: I've determined that, at least in the case of alex's tool, it's due to the collider being big enough to encapsulate the tip reference. This may also be the case with your tooltip.

**Comment by Hayden-da-Serg** [comment]
ah, yup it's exactly as @Aerizeon mentioned, though that does make me think, does that mean that refreshing a node does not use the bendy lasers but instead fires it's own raycast? As every other interaction functioned perfectly fine, including picking nodes with secondary action,

**Comment by Hayden-da-Serg** [comment]
Okay, yup just tested, the refresh node function does not use the bendy lasers, so I assume the raycast it fires out is then getting interrupted by the collider of the tip itself.

**Comment by Frooxius** [comment]
Thanks for looking into it, I've made LogiX Tip use the bendy laser in 2021.3.9.130, that should fix the issue!
