### ISSUE TITLE
Rename "LookAT" & "AutoLookAtUser" Component

### ISSUE THREAD

**Issue by Nordwig** [Neos-Metaverse/NeosPublic#1801]
## Is your tweak request related to a problem? Please describe.
The three "LookAT" components are separated in the component browser and the "AutoLookAtUser" is easily missed when you are looking to find a component that looks at things.

## Describe what would you like tweaked
Rename the "LookAt" component groupe so that they will showup near each other on alphabeticel order.
Change:
"LookAt" --> "LookAtPoint" Or "LookAtSlot" Or "LookATPoint/Slot"
"LookAtUser" no change
"AutoLookAtUser" --> "LookAtUserAuto"

## Describe alternatives you've considered
Maybe some other extension for the "LookAt" 

## Additional context
None

**Comment by shiftyscales** [comment]
It sounds like a lot of your underlying issue is down to not being able to find the components easily. For that- it's eventually planned to have searchable component lists, so I don't think changing AutoLookAtUser just so its placed beside the others makes a lot of sense.

It could be said that "LookAtSlot" is slightly more descriptive, but also a bit redundant.

**Comment by Nordwig** [comment]
Thanks for your response shiftyscales.
You are right, a search function in the componant and logix-node browser would be a good solution to my issue. There are some community build search functions already, to have that in the default tools and inspectors would be great.

When im encounter programms i often see the naming scheme like "the basic function" + "Type" or "Additions".
Like "FindUser" + "by Name" or "by adress". 
A bit like with the "Panner" + "1D".

It is nice to have similar acting things close together in a list.
So when u are browsing a list and find a component that seems to fit your needs, you also see the second and third option that might be even better.
