### ISSUE TITLE
Headset presence sensor overrides user away state while in new desktop mode

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1802]
## Describe the bug
Taking off the headset, and switching to the new desktop mode (F8) prevents the user's status from being set to 'Online', attempting to set the status as such will immediately revert it to 'Away'.

## To Reproduce
- Play Neos with a headset equipped with a presence sensor
- Remove the headset
- Switch to the new desktop mode (F8)
- Attempt to change the online mode using the dashboard facet on the home screen

## Expected behavior
The online status should reflect the user's current mode.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 20201.2.28.1210
 - Neos Platform: Windows
 - Regression: No

## Reporters:
Shifty#7944

**Comment by Frooxius** [comment]
Fixed in 2021.3.5.176, thanks!
