### ISSUE TITLE
Anchor locomotion outputting [1.00; 1.00] on primary and secondary axis without input

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1806]
## Describe the bug
Anchor locomotion is outputting [1.00; 1.00] on both the primary and secondary axis even without input from either a VR controller or the keyboard.

## To Reproduce
- Enter an avatar anchor that has an AvatarAnchorLocomotionData node using it (e.g. the Vehicles in GearBell's Toyshop)

## Expected behavior
The primary and secondary axis should output [0.00; 0.00] when no input is being received.

## Screenshots / Video
![2021-03-04 21 29 49](https://user-images.githubusercontent.com/54213390/110072037-fe678a00-7d31-11eb-9561-9178b906d81f.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.5.223
 - Neos Platform: Windows
 - Link to reproduction World/Item: neosrec:///U-GearBell/R-9a9d7de4-282e-48df-a744-bd0123842c1e (Items including GearBell's skateboard, and related vehicles that use anchor locomotion exhibit this issue, moving forward and turning at all times)
 - Regression: Yes, last working on 2021.2.28.1210.

## Additional context
This also occurs on a basic anchor with the Logix node attached as per the screenshot provided. It's not specific to anything GearBell's vehicles are doing.

## Reporters:
H3BO3#7957, Shifty#7944

**Comment by Hayden-da-Serg** [comment]
Ah, good to see this is here, was just about to report it.

**Comment by Frooxius** [comment]
Fixed in 2021.3.5.371 hotfix, thanks for report and sorry for the trouble!
