### ISSUE TITLE
Current Culture node can output a variety of things when game is set to English

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1809]
##Relevant issues
When a user's system is set to a variant of English other than US English, (Canadian or Australian English for example) Neos will set the game to the default English setting (which should be en-US) but Current Culture will still report things like en-CA or en-AU. When the user switches their language to something else and back to 'English', it is then set to en-US.
Note: This issue might not be around anymore as the people who it happened to were around for quite a while already.

## To Reproduce
Presumably, set up a new Neos account on a system that is set to some local variant of English, other than US or UK. (CAnada and AUstralia definitely do it)

## Expected behavior
Neos should only be able to set itself to languages it supports and not report different names for the same language setting.

## Bug information (please complete the following information):
 - How often does it happen: Upon account creation, presumably always if conditions are met
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: don't know
 - Neos Platform: Windows, maybe others
 - Regression: Probably no

## Reporters:
@Cameron#7818 @Keiko#3891 @DAWKY#0001

**Comment by Frooxius** [comment]
This is expected behavior. The node outputs the culture locale of the system of the user, not the chosen language of the user. Changing language will generally override the culture to that language, but you should not rely on it being the same.
