### ISSUE TITLE
Y and Z are swapped in "Screen" mode

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#1810]
Realized this should've been a tweak, not a bug. I apologize. I'm not gonna make a new issue though. If someone could swap it to tweak that'd be nice.

## Describe the bug
When using an ISO keyboard (Example: Swiss layout) the letters "Z" and "Y" are swapped.

## Relevant issues
-

## To Reproduce
1. Have an ISO keyboard
2. Try undoing on screen mode
3. Fail because "ctrl + z" has now become "ctrl + y"

## Expected behavior
Ctrl + Z should do an undo.

## Screenshots / Video
-

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.5.371
 - Neos Platform: Only tested on windows.
 - Link to reproduction World/Item: -
 - Regression: Yes, before the input binding update.

## Additional context
I'm not sure if it's on any ISO keyboard it definetly seems to do this on Swiss Layout though.

## Reporters:
3x1t_5tyl3#0001

**Comment by shiftyscales** [comment]
There are known issues with non-US based key layouts. It's unfortunately not something that can be dealt with directly on our end at this time.

For that, there is issue #624.
