### ISSUE TITLE
Closing Userspace world causes headless client to hang

### ISSUE THREAD

**Issue by glitchfur** [Neos-Metaverse/NeosPublic#1811]
## Describe the bug
When running the headless client, focusing the Userspace world and attempting to close it will make the headless client hang indefinitely. The prompt never returns, and the client must be exited with `Ctrl+C`.

## Relevant issues
I did not find any relevant issues.

## To Reproduce
1. Start the headless client.
2. Run `focus Userspace` or `focus 0`
3. Run `close`
4. The headless client will hang.

## Expected behavior
The headless client should not allow the Userspace world to be closed.

## Screenshots / Video
![Screenshot from 2021-03-08 03-03-37](https://user-images.githubusercontent.com/14147284/110299272-169e0a00-7fbb-11eb-93b4-a84bc6eef2ec.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.5.371
 - Neos Platform: Windows and Linux
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
N/A

## Reporters:
@glitchfur

**Comment by Frooxius** [comment]
In 2021.3.9.130 the Userspace is no longer listed at all, so you can't run commands against it, this should fix the issue. Thanks for report!
