### ISSUE TITLE
Improperly quoted strings causes headless client to hang

### ISSUE THREAD

**Issue by glitchfur** [Neos-Metaverse/NeosPublic#1812]
## Describe the bug
When running the headless client, certain arrangements of quotation marks when used with any command will cause the headless client to hang indefinitely. The prompt never returns, and the client must be exited with `Ctrl+C`.

## Relevant issues
I did not find any relevant issues.

## To Reproduce
1. Start the headless client.
2. Run any of these commands, noting the number of quotation marks:
- `name "`
- `name """"`
- `name "Testing""`
3. The headless client will hang.

## Expected behavior
The headless client should throw an error for all of these instead of hanging, or it should interpret them as it would for other quoted or unquoted strings:
- `name "` should set the world name to `"` (unquoted string)
- `name """"` should set the world name to `""` (quoted string)
- `name "Testing""` should set the world name to `Testing"` (quoted string)

## Screenshots / Video
![Screenshot from 2021-03-08 03-25-35](https://user-images.githubusercontent.com/14147284/110301738-0b98a900-7fbe-11eb-9408-1db10d043f52.png)

This is also applicable to commands that do not take arguments, such as `status`:

![Screenshot from 2021-03-08 03-26-01](https://user-images.githubusercontent.com/14147284/110301824-2bc86800-7fbe-11eb-91fb-796b04db7ab0.png)

Therefore I believe the bug affects all commands.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.5.371
 - Neos Platform: Windows and Linux
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
Running a command such as `name "Testing` without a closing quotation mark will _not_ hang the headless client, but will cut off the last character of the string that was provided.

![Screenshot from 2021-03-08 03-35-05](https://user-images.githubusercontent.com/14147284/110302947-6f6fa180-7fbf-11eb-8420-fa89a9d71122.png)

## Reporters:
@glitchfur

**Comment by Frooxius** [comment]
Fixed in 2021.3.9.130, thanks for the report!
