### ISSUE TITLE
Laser reticle does not take player scaling into account.

### ISSUE THREAD

**Issue by RileyGuy** [Neos-Metaverse/NeosPublic#1817]
## Describe the bug
When scaling, the laser reticle does not compensate for player scale. E.g. when the player is large, the reticle becomes huge even while on the context menu, and while small, the reticle barely changes size at all.

## To Reproduce
Scale and look at your laser reticle, it will behave as I described above.

## Expected behavior
The laser reticle should compensate for player scale.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.9.130
 - Neos Platform: Any
 - 
## Reporters:
Delphox, confirmed by myself.

**Comment by Frooxius** [comment]
Fixed in 2021.3.9.618, thanks!
