### ISSUE TITLE
Setting maxUsers < 1 or > 256 throws an exception in headless client

### ISSUE THREAD

**Issue by glitchfur** [Neos-Metaverse/NeosPublic#1820]
## Describe the bug
When running the headless client, attempting to set the maximum user limit with `maxUsers` to a value less than 1 or greater than 256 will throw an exception.

## Relevant issues
I did not find any relevant issues.

## To Reproduce
1. Start the headless client.
2. Run any of the following:
- `maxUsers 0`
- `maxUsers 257`
- `maxUsers -1`
3. The headless client will throw an exception.

## Expected behavior
The headless client should print a simple error rather than throwing an exception if the provided value is outside the range of valid values. Other commands already do this, such as `focus` and `tickRate`:

![Screenshot from 2021-03-09 15-45-59](https://user-images.githubusercontent.com/14147284/110542720-0a1ace00-80ef-11eb-8278-0a7c90b22ce2.png)

## Screenshots / Video
See below for a screenshot of the exception.

![Screenshot from 2021-03-09 15-47-09](https://user-images.githubusercontent.com/14147284/110542755-16069000-80ef-11eb-9ba2-10e143b7dbc6.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.9.618
 - Neos Platform: Windows and Linux
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
N/A

## Reporters:
@glitchfur

**Comment by Frooxius** [comment]
Fixed in 2021.3.12.44, thanks!
