### ISSUE TITLE
Increase Slider Precision for DynamicBoneChain Stiffness

### ISSUE THREAD

**Issue by H3BO3** [Neos-Metaverse/NeosPublic#1823]
## Is your tweak request related to a problem? Please describe.
When tuning dynamic bones to very specific looks, I often need a very high stiffness value, but not 1. It becomes difficult to tune after 0.99 since I can't tell what values I entered past that, for instance 0.994, etc. The more precise value itself is stored and used in the simulation but I can't see what it was. If I click on the field it just gives me the rounded value as it appears in the field, so the actual/prior value is lost.

## Describe what would you like tweaked
I'm not sure what would be the easiest or best option, so I came up with a few that would work for me.

- When a slider field is clicked on, display the actual value of the field to be modified rather than the rounded displayed value.
- Add additional digits of precision to particular slider fields where it would benefit them, like three digits for the Stiffness value to start with.
- Remap the Stiffness slider range to 0-100 instead of 0-1.

## Additional context
![2021-03-11 02 38 29](https://user-images.githubusercontent.com/62123804/110767093-19933780-8213-11eb-9cc8-f50f94b25b94.jpg)

**Comment by Frooxius** [comment]
Gave it 4 decimal places in 2021.3.12.44, hope it helps!
