### ISSUE TITLE
"Invite" and "restart" commands throw exceptions with no world focused in headless client

### ISSUE THREAD

**Issue by glitchfur** [Neos-Metaverse/NeosPublic#1824]
## Describe the bug
When running the headless client, running the `invite` command (assuming there is a Neos account logged in) or the `restart` command will throw an exception if there is no world currently focused.

## Relevant issues
I did not find any relevant issues.

## To Reproduce
1. Start the headless client.
2. Log in to a Neos account if not logged in already to properly use `invite`.
3. Run `close` one or more times until all sessions are closed and the prompt changes to `NO WORLD>`:
```
Glitch Test Session>worlds
[0] Glitch Test Session             Users: 1	Present: 0	AccessLevel: Anyone	MaxUsers: 32
Glitch Test Session>close
NO WORLD>worlds
NO WORLD>
```
4. Run `restart` and `invite <username>`
5. The headless client will throw an exception for each command.

## Expected behavior
The headless client should print "No world is currently focused" instead of throwing exceptions.

## Screenshots / Video
Running `restart`:

![Screenshot from 2021-03-11 13-05-13](https://user-images.githubusercontent.com/14147284/110844482-162d9980-826f-11eb-89cb-0d8e29d643ee.png)

Running `invite <username>`:

![Screenshot from 2021-03-11 13-06-38](https://user-images.githubusercontent.com/14147284/110844521-204f9800-826f-11eb-82f0-c877bd9096f1.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.9.618
 - Neos Platform: Windows and Linux
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
All other commands handle the case of no world being focused. `invite` and `spawn` may or may not be affected as well. I was unable to test those commands.

![Screenshot from 2021-03-11 13-09-20](https://user-images.githubusercontent.com/14147284/110846451-673e8d00-8271-11eb-8bfe-86bc338e7942.png)

## Reporters:
@glitchfur

**Comment by Frooxius** [comment]
Fixed in 2021.3.16.1287, thanks for report!
