### ISSUE TITLE
Headless server generates invalid startWorlds entries after failing to load invalid template

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#1825]
## Describe the bug
When using the startWorldTemplate command, if an invalid template name is issued (such as "gridspace" instead of "GridSpace"), the command will fail with an error, as expected:
```
startWorldTemplate gridspace
Starting world with preset: gridspace
World preset not found!
```
however, executing `saveConfig` will result in an invalid `startWorlds` entry being written to the config.json:
```
{
      "isEnabled": true,
      "sessionName": null,
      "customSessionId": null,
      "description": null,
      "maxUsers": 32,
      "accessLevel": "Private",
      "hideFromPublicListing": null,
      "tags": null,
      "mobileFriendly": false,
      "loadWorldURL": null,
      "saveAsOwner": null,
      "loadWorldPresetName": "gridspace",
      "forcePort": null,
      "keepOriginalRoles": false,
      "defaultUserRoles": null,
      "autoInviteUsernames": null,
      "autoInviteMessage": null,
      "autoRecover": true,
      "idleRestartInterval": -1.0,
      "forcedRestartInterval": -1.0,
      "saveOnExit": false,
      "autosaveInterval": -1.0,
      "awayKickMinutes": -1.0,
      "autoSleep": true
    }
```

## To Reproduce
1. Start a headless client
2. Once initialization is complete,  issue the command `startWorldTemplate gridspace`
3. This will generate a `World preset not found!` error, as expected
4. issue the command `saveConfig`
5. Inspect the config.json file: there will be an invalid `startWorlds` entry, with the `loadWorldPresetName` set to the invalid preset given in step 2.

## Expected behavior
The failed template should be removed from the configuration's list of worlds before writing the file.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.9.618
 - Neos Platform: Windows

## Reporters:
Epsilion

**Comment by Frooxius** [comment]
Fixed in 2021.3.16.1287, thanks!
