### ISSUE TITLE
Non-host users in "Hidden, Contacts Only World" show on the contacts list as "In Contacts Only World"

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1826]
## Describe the bug
If a host has set the world to "Contacts" and "Don't show in session lists" on the contacts list it will appear properly as "Hidden, Contacts Only World" for them, but any other users in the session will be shown as "In Contacts Only World" instead, regardless of if you have the host user added as a friend or not.

## To Reproduce
- Have a host set a world to "Contacts" and "Don't show in session lists"
- Have at least one friend in the world alongside the host
- Observe the contacts list entries for the host/client that are in the session

## Expected behavior
The world be displayed as "Hidden, Contacts Only World" to all users in the session regardless of if they are hosting or not. "In Contacts Only World" suggests the host isn't currently a friend/contact/is confusing to the user looking through their contacts list.

## Screenshots / Video
Ryuvi, Lewis, myself, and others are all in the same session. Despite this:
![image](https://user-images.githubusercontent.com/54213390/110893870-ab4e8380-82ab-11eb-902e-f0f12b50f475.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.12.44
 - Neos Platform: Any
 - Regression: No

## Reporters:
Shifty#7944, Cyro#5120

**Comment by Frooxius** [comment]
Fixed in 2021.3.16.1287, thanks!
