### ISSUE TITLE
Neos in VR mode steals mouse focus

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Neos-Metaverse/NeosPublic#1834]
## Describe the bug
Whenever Neos is running in VR mode the mouse focus will be stolen, preventing it from being used in other desktop interaction applications such as the SteamVR dashboard until the Neos window is unfocused.

## Relevant issues
None to be found

## To Reproduce
- Launch Neos in VR mode
- Attempt to move the mouse while the Neos window is focused

## Expected behavior
The Neos window should not take control over the mouse while VR mode is active, as this prevents usability in other applications

## Screenshots / Video
N/A

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.16.1287
 - Neos Platform: Windows, but suspected to be on any Desktop version
 - Link to reproduction World/Item: N/A
 - Regression: Yes, before build 2021.3.16.1287, the Neos window would not steal the mouse focus

## Additional context
N/A

## Reporters:
Hayden#3180

**Comment by shadowpanther** [comment]
You can get your mouse back by summoning the Start menu and thus stealing the focus from Neos, but Neos shouldn't lock the mouse at all when it gets the rotation input from the headset.

**Comment by shiftyscales** [comment]
I don't think this issue is quite as simple as just not locking the mouse when VR is in use, because there is potential for mixing input methods that may be desirable, e.g. using the mouse to turn, and keyboard to move even while in VR. A part of the way the input system has been built up allows for quick and instantaneous input switching.

Having to grab the focus from the mouse via pressing start/alt-tabbing, etc. also isn't out of line with how mouse input is handled in other games/engines.

**Comment by shadowpanther** [comment]
No VR game grabs the mouse, thus allowing to interact with the desktop mirror window freely. Perhaps a toggle is needed to explicitly grab the mouse input in VR mode.

This behaviour only changed in the recent version, and it is annoying now.

**Comment by shiftyscales** [comment]
> 
> 
> No VR game grabs the mouse, thus allowing to interact with the desktop mirror window freely. Perhaps a toggle is needed to explicitly grab the mouse input in VR mode.
> 
> This behaviour only changed in the recent version, and it is annoying now.

I realize the frustration @shadowpanther. I use my dashboard desktop daily. I was just noting that the preferable solution would be something a little more elegant than simply never taking cursor control ever.

**Comment by Frooxius** [comment]
I've got a fix coming in the next build for this. Sorry for the inconvenience!

**Comment by Frooxius** [comment]
Fixed in 2021.3.23.231, Neos should no longer be stealing mouse focus while in VR mode. Sorry for the inconvenience!
