### ISSUE TITLE
Override Worldspace Lasers to Controllers If Avatar Hands are stuck

### ISSUE THREAD

**Issue by H3BO3** [Neos-Metaverse/NeosPublic#1835]
## Is your feature request related to a problem? Please describe.
Currently there is behavior for the userspace/dash where the lasers will always work, regardless of if avatar hands are stuck or otherwise separated significantly from the controller locations. A user was having an issue with avatar hands not tracking (specifically the IK weight being set to zero) which prevented in-session interactions, and thus being unable to exit the avatar in question without deleting it. I've also come across this myself when manually constructing avatars.

## Describe the solution you'd like
Apply behavior to worldspace lasers to track to the controllers when they are significantly separated from the hands, same as the dash lasers.

## Describe alternatives you've considered
Some kind of emergency toggle to override lasers to controllers manually.

## Additional context
Suggested by Starry Mic#5427

**Comment by Frooxius** [comment]
Sorry, but this is not possible. The lasers are part of the avatar, so there's a million ways the user could possibly break them and we can't account for all of those.

The userspace lasers will override when the user opens the dash if the position/angle is different enough, allowing them to use the Respawn button or leave the world when this happens.
