### ISSUE TITLE
Turn animations on and off

### ISSUE THREAD

**Issue by VLandrej** [Neos-Metaverse/NeosPublic#1836]
Hi, I'm Neos noob. I'm trying to find out if it's possible, if I upload a 3D model with animation to Neos, to set the animation to start/stop using a button (pulse). Thank you

**Comment by Electronus** [comment]
this is a question better for the discord, how ever it is possible using the playback logix nodes.

**Comment by VLandrej** [comment]
Oh, okay. Thank you :)
