### ISSUE TITLE
Avatarexpressiondriver stops working when switching to a smirk expression 

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#1838]
## Describe the bug
Avatarexpressiondriver stops working when switching to any smirk expression and checkbox is not Turn on able 

## Relevant issues
No

## To Reproduce
[Steps to reproduce the behavior:
1. You have the avatar expression driver and then put in blendshapes then switch to a bunch of different smirk expression will make the whole component disabled and the box is not able to be checked anymore

## Expected behavior
It not breaking 

## Screenshots / Video
https://youtu.be/X0Ba7347JaE
## Bug information (please complete the following information):
 - How often does it happen: always 
 - Does the bug persist after restarting Neos? [Yes
 - Neos Version: the current one 2021.3.16.1287
 - Neos Platform: Any, Windows, Linux, Android/Quest
 - Link to reproduction World/Item: it happens anywhere
 - Regression: yes it didn't do this before the component got updated 

## Reporters:
Alexderpyfox

**Comment by ProbablePrime** [comment]
In your video, your Expression Driver component disables itself, the enabled checkbox is turned off towards the end. 

This sometimes happens when configuring certain components. After configuring them completely just re-enable them using the enabled checkbox.

**Comment by alexderpyfox** [comment]
The checkbox didn't work either tho it is very strange 🤔

**Comment by ProbablePrime** [comment]
In that case do you have a log file? If that box turns itself back off after clicking it, then it means your setup is invalid, usually.

**Comment by alexderpyfox** [comment]
It's the smirk one when that one is in the component list it doesn't want to turn on anymore

**Comment by shiftyscales** [comment]
As Prime had asked, can you please provide the log from the session this occured in from your logs folder at `C:\Program Files (x86)\Steam\steamapps\common\NeosVR\Logs` or wherever you have Neos installed @alexderpyfox?

**Comment by alexderpyfox** [comment]
It didn't occur in a session specific it happens everywhere and is easy to reproduce as you see in the video

**Comment by Frooxius** [comment]
I've got a fix coming, there was a mistake in those two expressions.

**Comment by Frooxius** [comment]
Fixed in 2021.3.23.231, thanks!
