### ISSUE TITLE
Neos does not sanitize names well

### ISSUE THREAD

**Issue by tykodey** [Neos-Metaverse/NeosPublic#1839]
## Describe the bug
Registered names that contain tags like \<noparse\>, \<sup\>, \<color\>, ect will parse the tags in some places such as contacts, inspecting user, and world browser

## Relevant issues
none, i searched for "noparse" and "name" and didnt see anyone find this yet

## To Reproduce
1. Register janky neos name with formatting tags
2. Login to account
3. Look at world browser user list / contacts page / ect

## Expected behavior
Names to not parse their formatting

## Screenshots / Video
my account \<noparse\> https://media.discordapp.net/attachments/821898122111483904/821993144790941701/image0.jpg?width=526&height=702

## Bug information (please complete the following information):
 - How often does it happen: always
 - Does the bug persist after restarting Neos? yes
 - Neos Version: 2021.3.16.1287
 - Neos Platform: Presumably any, only tested on windows
 - Regression: probably

## Additional context
Does not work on nametags in world

Hopefully the account name \<noparse\> stays even if the formatting is fixed as id love to keep it as my headless server name

## Reporters:
KodeyTheNeko#1284 (neos Kodey / \<noparse\>)
Cameron#7818 (neos Psychpsyo)

**Comment by Psychpsyo** [comment]
Note: These aren't parsed in name badges, since name badges get a noparse tag with length inserted, which does skip the /noparse. Some other places, like the user list in the dash's session tab do not do this though so the formatting shows up.

**Comment by Frooxius** [comment]
I've added sanitation to the missing places in 2021.3.23.231 which should resolve this problem. Thanks for the report!

**Comment by tykodey** [comment]
noparse's name is still invisible in my contacts list.
