### ISSUE TITLE
snap turning on oculus go

### ISSUE THREAD

**Issue by pushstartvr** [Neos-Metaverse/NeosPublic#184]
Many times the snap turning seems to only work in one direction - there is always one direction that it works (left or right).  Re-calibrating the controller seems to fix this so it seems dependant on the drift between the headset and the controller.

**Comment by Frooxius** [comment]
I'll probably rework the control scheme for mobile a bit, the current mapping just naively maps the standard controller onto the Touch one, which doesn't seem to work well.

**Comment by kazu0617** [comment]
I noticed this issue when I was looking back through the issues, so I tried it with Oculus Quest. At least I couldn't reproduce it in Oculus Quest, I think I need to check since the Input System has been reworked.

**Comment by Frooxius** [comment]
This issue is no longer relevant, since Oculus Go support was dropped by Facebook and Unity, so we don't support it anymore either.
