### ISSUE TITLE
Prompt never returns after running "restart" command in headless client

### ISSUE THREAD

**Issue by glitchfur** [Neos-Metaverse/NeosPublic#1841]
## Describe the bug
Running `restart` in the headless client restarts a world as expected, but the prompt never returns after the command is done executing. The headless client doesn't allow any further user input and consequently no further commands can be run. The client must be shut down using `Ctrl+C`.

## Relevant issues
I did not find any relevant issues.

## To Reproduce
1. Start the headless client.
2. Run `restart`
3. The headless client will restart the world normally, but the prompt will never return.

## Expected behavior
The prompt should return and allow further input and execution of commands.

## Screenshots / Video
![Screenshot from 2021-03-18 04-28-21](https://user-images.githubusercontent.com/14147284/111610937-e53af080-87a9-11eb-9e8f-808f59bf9f9d.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.16.1287
 - Neos Platform: Windows and Linux
 - Link to reproduction World/Item: N/A
 - Regression: Unsure. I believe this worked in previous versions, but I do not have a specific version number.

## Additional context
N/A

## Reporters:
@glitchfur

**Comment by glitchfur** [comment]
Bug is still present in Neos version 2021.5.29.1365.

**Comment by AshtonSparx** [comment]
Bug is still present on Neos version 2021.7.1.498

**Comment by Frooxius** [comment]
We haven't made any attempts to fix it, we'd have announced and closed the issue otherwise, you do not need to post that it's still present.

If you'd like it to be given higher priority, please use the voting feature, because that makes it sort higher up in the priority list, but extra comments do not.

**Comment by AshtonSparx** [comment]
Sorry froxx! Just wanted to make sure it wasn't lost and forgotten in the sea of Issue creations

**Comment by Frooxius** [comment]
Fixed in 2021.7.11.1002!
