### ISSUE TITLE
Headless client will hang or crash if Steam is force closed

### ISSUE THREAD

**Issue by glitchfur** [Neos-Metaverse/NeosPublic#1842]
## Describe the bug
The headless client will either hang or crash after a few seconds if Steam is force closed while the headless client is still running. This bug only occurs if Steam was running at the time that the headless client was started, as the headless client will have initialized the Steam API. In the case of a crash, the headless client gives an exit code of `1`.

## Relevant issues
I did not find any relevant issues.

## To Reproduce
1. Run Steam (specifically, the regular Steam client, not `steamcmd`).
2. Start the headless client.
3. The state of **Neos VR** in Steam's library should now show as running, indicating that the headless client has hooked into Steam.
4. Attempt to close Steam via the menu bar: **Steam > Exit**.
5. A pop up window will display the message: _Waiting for Neos VR to shut down..._
The headless client does not respond to Steam being shut down. After a few seconds, the **EXIT NOW** button will change from a disabled to an enabled state. Click **EXIT NOW** and Steam will close.
6. The headless client will continue running for a very short period of time. I have observed up to 10 seconds. The headless client will then either hang, or it will crash. The headless client doesn't accept any further user input if it hangs.

## Expected behavior
One of two options:
- The headless client should shut down gracefully when Steam is shutting itself down.
- The headless client should not hang or crash if it loses communication with the Steam client unexpectedly.

## Screenshots / Video
Linux:

![Screenshot from 2021-03-18 05-15-42](https://user-images.githubusercontent.com/14147284/111613513-9773b780-87ac-11eb-838a-138e0db5d709.png)

Windows:

![Screenshot from 2021-03-18 05-18-22](https://user-images.githubusercontent.com/14147284/111613527-9b9fd500-87ac-11eb-9940-eefebcd7a580.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.16.1287
 - Neos Platform: Windows and Linux
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
N/A

## Reporters:
@glitchfur

**Comment by Frooxius** [comment]
I don't think this is something we can really "fix". When using the headless with Steam installed, Neos actually initializes the Steamworks for the Steam Networking Sockets support. This requires Steam to run, so there's no clean way to continue running the headless if you shut that down. The shutdown comes from the Steam library itself, rather than our code, so we don't have much control over that anyway.

The only option is to just don't have Steam installed and running when using the headless if this is an issue.
