### ISSUE TITLE
Allow for use of additional/custom Touch Tip Sources for all touch interactions

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#1845]
## Is your feature request related to a problem? Please describe.
When trying to install an additional Touch Tip Source in my avatar's nose, I replicated the setup from the hand. This new custom Touch Tip is able to interact with checkboxes and touchabledata, but not with buttons (Neos UI, Physical and Touch variants tested).

## Describe the solution you'd like
Touch Tip Source working on buttons properly while being an additional (third and more) Touch Tip for the avatar.

## Describe alternatives you've considered
Moving one of the existing Touch Tips to the avatar's nose, thus removing the touch functionality from one hand.

**Comment by Frooxius** [comment]
This is intentional limitation as a security measure, until we have a robust system to do this securely this won't get implemented, so you'll have to deal with it only working on the hands, I'm sorry.

**Comment by shadowpanther** [comment]
So, why the checkboxes and touchable data work then? Shouldn't that be disabled too?

**Comment by Frooxius** [comment]
No, the protection is only applied for scenarios/interfaces where it's easily abusable and poses a security risk.

**Comment by shadowpanther** [comment]
I think this could be closed as I was since shown the proper method to apply additional touch tips to the avatar.
