### ISSUE TITLE
Addition of a visual impairment badge

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1846]
## Is your feature request related to a problem? Please describe.
On behalf of Zagroseckt#6207 (U-Zagroseckt), the addition of a visual impairment badge would further round out the set of accesibility badges offered, allowing other users to note their visual impairment, and accomodate accordingly for it.

## Describe the solution you'd like
A badge similar in theme to the existing color vision deficiency badge would fill the needs of this badge well:
![visually-impaired-2-568637](https://user-images.githubusercontent.com/54213390/111853656-2d0c6580-88d9-11eb-9048-655d485b7f43.png)
![theeye](https://user-images.githubusercontent.com/54213390/111853662-3695cd80-88d9-11eb-92f2-c36595b196f8.png)

**Comment by Frooxius** [comment]
Yeah we can add these, just need graphic for it to be made in style consistent with the current ones.

**Comment by shiftyscales** [comment]
Added in 2021.6.23.11!
> - Added visually impaired accessibility badge
> -- You can assign or unassign it by sending following commands to the Neos account: /addVisuallyImpaired, /removeVisuallyImpaired
> -- Current badge image made by @ Raith (CytraX) | Programmer, will likely be updated later
