### ISSUE TITLE
Nameplate stuck in 'away' state

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1849]
## Describe the bug
Avatar nameplates will retain their faded 'away' color scheme if the user enters desktop mode after having taken off their headset.

## To Reproduce
- Start Neos in VR
- Remove a headset that has a presence sensor to trigger the away mechanisms (eyes closed/nameplate faded, etc.)
- Press F8 to toggle into the new desktop mode

## Expected behavior
The nameplate retains its usual 'active' coloration while in desktop mode.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.16.1287
 - Neos Platform: Windows
 - Regression: No

## Reporters:
Shifty#7944

**Comment by AshtonSparx** [comment]
Not only that but user is permanently marked as away with logix nodes too, triggering things that is only meant to be triggered when your headset is off (I have little particles and such I have when taking my headset off) -- To combat it, I put my blanket or something to cover the sensor to trick it into thinking I put it back on.

**Comment by Frooxius** [comment]
@AshtonSparx You need to use the IsUserPresent node, not the IsUserPresentInHeadset. The former will properly return true when the user is in the screen mode. 

I have a fix coming for the nameplates in the next build, they were using IsUserPresentInHeadset instead of IsUserPresent

**Comment by Frooxius** [comment]
Fixed in 2021.3.23.231, thanks for report!
