### ISSUE TITLE
Desktop tab on the dashboard not working

### ISSUE THREAD

**Issue by opl-** [Neos-Metaverse/NeosPublic#1851]
## Describe the bug
The Desktop tab on the dashboard shows up as a missing texture on Linux and does not take in any inputs.

## To Reproduce
1. Start the native Linux build
2. Open the Desktop tab
3. The desktop is not visible

## Expected behavior
The Desktop tab should behave as it does on Windows.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/4833621/111928567-49b0c500-8ab4-11eb-9fea-c5103b3868d0.png)
## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Beta 2021.3.16.1287
 - Neos Platform: Linux
 - System: Debian + Steam Linux Runtime

**Comment by Frooxius** [comment]
This is a known problem, currently Desktop view isn't supported on Linux along with several other things at the moment, see the main thread here: https://github.com/Neos-Metaverse/NeosPublic/issues/149

I'm not sure if/when we would support this, as the desktop view uses Windows-specific API's and we'd need to have an equivalent for Linux, which is substantial amount of work.

**Comment by opl-** [comment]
Generally issues are for tracking individual problems, which allows easily finding out what the status of any given problem is. I didn't think to scroll through the 80 comment strong thread littered with general debugging to see if this is to be expected, and I feel like expecting people to do that is a little ridiculous. Having one issue per problem would make everyone's life easier.

**Comment by ykhurshid** [comment]
> Generally issues are for tracking individual problems, which allows easily finding out what the status of any given problem is. I didn't think to scroll through the 80 comment strong thread littered with general debugging to see if this is to be expected, and I feel like expecting people to do that is a little ridiculous. Having one issue per problem would make everyone's life easier.

While I would normally agreed, I could see it becoming a problem if the list of issues get clogged up with problems affecting (let's face it) a tiny percentage of the actual usebase of NeOS, and I say that as an exclusive Linux user.

Back on the topic on hand, @Frooxius [xrdesktop](https://gitlab.freedesktop.org/xrdesktop/xrdesktop) might be something to look into in the future as a potential API for this. It's not quite ready yet since to even use the test versions, you need to install special patched versions of Gnome or KDE but I could see in the future it becoming a bundled in feature with the mainline versions of thse desktop environments.

**Comment by opl-** [comment]
The solution to that already exists: filtering. Labeling issues with Linux would allow users to filter them out using `-label:Linux` (or find them using `label:Linux`). Just because Linux is used by a smaller group of people doesn't mean it should be harder for them to navigate. It's still a (somewhat) supported platform and in my opinion it should get to use the same tools other platforms get to enjoy.

Not tracking these as separate issues also means that voting on Linux specific issues is impossible, which reduces visibility. If the Linux user base is indeed smaller, the amount of votes on the respective issues should reflect that and allow better prioritizing the issues.

That said, I agree that this is not the place to discuss it and frankly, I'm not sure I care enough to keep arguing that an issue tracker should be used to track issues. Ultimately it is up to the maintainers to make this call and best I can do is explain my view, which I already did.
