### ISSUE TITLE
Creating a ValueField of type System.Type crashes the session.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1852]
## Describe the bug
Creating a ValueField of type System.Type crashes the session.

## Relevant issues
#870 as that same problem is what made me try this.

## To Reproduce
1. Inspect a Logix tip.
2. Set the ActiveNodeType to FrooxEngine.ValueField`1[[System.Type, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
3. Spawn a 'node' using that Logix tip.

## Expected behavior
Either nothing, an error or an empty object with a ValueField<Type> on it. Preferably the last one though I understand if that isn't possible.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.16.1287
 - Neos Platform: Probably Any.
 - Regression: Don't think so.

## Additional context
I got to this point because I wanted to store the type output of the StandardController node to detect what controller someone is using.
It'd be neat if that was an enum instead, as mentioned in issue #870

## Reporters:
Cameron#7818

**Comment by Frooxius** [comment]
Fixed in 2021.3.23.231, thanks for reporting!

**Comment by 3x1t-5tyl3** [comment]
I'm sorry to comment on a closed issue. But the "fix" kinda borked *all* writing to it.

So custom functions for logix-tips which automate certain actions are now locked out for us..
Is there a way to prevent the crash whike still allowing us to write into that field?
