### ISSUE TITLE
Strip potentially sensitive info from log files.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1854]
## Is your tweak request related to a problem? Please describe.
Neos log files can currently include the names of users, items and sessions which aren't always intended to be public. Therefore they shouldn't be logged in files intended to be publicly shared on here.

## Describe what would you like tweaked
Remove the names and IDs of items, users and sessions from the Neos logs.

## Describe alternatives you've considered
Keeping these things there and having people potentially share info they thought was private on accident or making an easy way to submit logs to only the developers without giving anyone access to them.

**Comment by Frooxius** [comment]
Logging of this information is essential for debugging, striping it away would make it impossible for us to solve a lot of the problems. We encourage people to share them privately if they can, rather than in public.
