### ISSUE TITLE
Creating reference typed variants of several value type-only components causes crashes

### ISSUE THREAD

**Issue by Zyzyl** [Neos-Metaverse/NeosPublic#1855]
## Describe the bug
Attempting to create or interact with reference typed variants of several different components which should only accept a value type causes crashes.

## Relevant issues
https://github.com/Neos-Metaverse/NeosPublic/issues/724, https://github.com/Neos-Metaverse/NeosPublic/issues/1230 - both fixed. Possibly others too.

## To Reproduce
Attempting to create any of the following via the Add Component dialog with the `Slot` type will immediately freeze and then crash Neos.
- `ValueProxy<T>`
- `SetValue<T>`
- `ValueRadio<T>`
- `ButtonValueCycle<T>`
- `ButtonValueSet<T>`
- `ValueOptionDescriptionDriver<T>`
- `ButtonRelay<T>`

Attempting to create a `ValueMultiplexer<Slot>` happens successfully, however Neos freezes and crashes if you press the 'Add' button.

Attempting to create a (UIX) `Slider<Slot>` crashes the session.

It is also possible to create a `ValueDriver<Slot>`, this seems benign but I don't think it's functional (I couldn't drag and drop references into the fields).

## Expected behavior
It shouldn't be possible to instantiate reference typed variants of these components, similar to how one cannot for e.g. `ValueField<T>`. 

## Bug information (please complete the following information):
 - Neos Version: 2021.3.16.1287
 - Neos Platform: Windows

## Reporters:
Zyzyl#1441
Banane9#5929 noted the ValueProxy issue in Discord which prompted me to look for others

**Comment by Frooxius** [comment]
We already have report for this here: https://github.com/Neos-Metaverse/NeosPublic/issues/1852 It's a general issue, I have a fix coming in the next build.

**Comment by Frooxius** [comment]
Ah nevermind, this is actually different for some of them, sorry, some of them were missing checks in the first place! Fix coming too for those.

**Comment by Frooxius** [comment]
Added validation to all these in 2021.3.23.231, thanks for the findings!
