### ISSUE TITLE
StandaloneRectMesh<AudioSouceWaveformMesh> has very undesiable visual bugs when VideoTextureProvider is the Source

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#1856]
## Is your tweak request related to a problem? Please describe.
When VideoTextureProvider is in the AudioWaveForm, it causes flickering, super stretched waveforms in the mesh when the video is paused, finished or stopped, I also noticed recently as I was recording the video, it causes nearby objects to also flicker while the video is in those states when I Alt-Tabbed.

## Describe what would you like tweaked
I believe this could be a null or negative value issue with either VideoTextureProvider, AudioWaveForm or both when there's no audio coming from an active VideoTextureProvider. Clamping the audio's minimum value should fix this issue.

This behavior doesn't happen when there's no video present.

## Describe alternatives you've considered
I'm not aware of any other alternatives that could fix this issue, I tried enabling OverrideBoundingBox and that seems to have only fixed it causing nearby object flicker.

## Additional context
Video showcasing the visual bugs: https://youtu.be/PIAxQi8zas8

**Comment by AshtonSparx** [comment]
Small Update: I toyed around with some of the VideoTextureProvider's settings, forcing it to use LibVLC as it's PlayBackEngine seems to fix the issue. Which circles the issue directly to Unity Native Playback Engine.

**Comment by Frooxius** [comment]
Should be fixed in 2021.3.27.510, couldn't verify to be fully sure without a replication sample, please reopen if it still persists.
