### ISSUE TITLE
While in the new desktop mode, holding CTRL to walk slower and then pressing S results in a world save

### ISSUE THREAD

**Issue by RileyGuy** [Neos-Metaverse/NeosPublic#1857]
## Describe the bug
When in the new desktop mode, holding CTRL to go slow and then pressing S results in either saving the world, or a save dialogue popping up which is not closable.

## To Reproduce
1. Start Neos in VR mode
2. Press F8 to switch to desktop mode
3. Hold CTRL and press S, the world will either save or a save dialogue will pop up

## Expected behavior
CTRL+S shouldn't save the world, but rather should solely be bound to making you walk slower backwards.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.16.1287
 - Neos Platform: Any
 - Regression: No

## Reporters:
Myself and numerous others who have noted this issue, but that I can't remember at the moment.

**Comment by Frooxius** [comment]
Changed in 2021.3.23.231, thanks!
