### ISSUE TITLE
Remote Touchables Block DevToolTip Laser Gizmo Interaction

### ISSUE THREAD

**Issue by H3BO3** [Neos-Metaverse/NeosPublic#1858]
## Describe the bug
When working around colliders that have a remote touchable on them (mainly seen on anchor click-to-enter components), it blocks the devtooltip laser going to gizmos, even though gizmos should take a very high priority.

## Relevant issues
#841

## To Reproduce
Create a box collider, add a remote touchable to it, select it with the gizmo, and then you can't interact with the gizmo through the collider anymore.

## Expected behavior
The devtooltip laser should almost always pass through to gizmos. Some of the only things I can think of to block it would be toolshelves and then inspectors, in descending priority.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.16.1287
 - Neos Platform: Any
 - Regression: Perhaps? It might have been fine before the big laser rework.

## Reporters:
H3BO3#7957

**Comment by Frooxius** [comment]
Tweaked the behavior in 2021.3.25.399, should be much better, now. Thanks!
