### ISSUE TITLE
When launching from legacy screen mode, new desktop mode context menu inaccessible

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1859]
## Describe the bug
If launched in the legacy screen mode, the context menu is inaccessible in the new desktop mode. Pressing the middle mouse button produces exceptions.

## To Reproduce
- Launch Neos in legacy screen mode
- Switch to the new desktop mode (F8)
- Attempt to open the context menu (MMB)

## Expected behavior
The context menu remains accessible.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.23.263
 - Neos Platform: Windows
 - Regression: No

## Additional context
This likely won't be relevant once the desktop mode is made official and replaces the current legacy desktop mode. If it's not a quick/easy fix, I don't see any specific value in it, and it shouldn't be prioritized/this issue can be closed. It's possibly as a result of legacy desktop mode quirks, e.g. the lack of a proper character controller/locomotions.

A replication log can found here:
[SHIFTYWINDOWS - 2021.3.23.263 - 2021-03-22 22_28_37.log](https://github.com/Neos-Metaverse/NeosPublic/files/6187098/SHIFTYWINDOWS.-.2021.3.23.263.-.2021-03-22.22_28_37.log)

## Reporters:
Rukio#0001, H3BO3#7957, Shifty#7944

**Comment by Frooxius** [comment]
Using new desktop mode with the old one isn't supported.
