### ISSUE TITLE
Pointing a ReferenceMultiplexer<Slot> at a slot's parent can drive that parent to null.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1860]
## Describe the bug
Setting the Target of a ReferenceMultiplexer<Slot> to a slot's parent will drive that parent to null.

## Relevant issues
Didn't find any.

## To Reproduce
1. Create two slots.
2. Add a ReferenceMultiplexer<Slot> to one of them.
3. Set the ReferenceMultiplexer<Slot>'s target to the Parent field  of the other slot.
4. Parent field is now driven to null.

## Expected behavior
Anything that isn't a null parent as I'm pretty sure Neos tries to avoid creating those wherever possible.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.23.231
 - Neos Platform: Windows, probably Any
 - Regression: Don't know.

## Reporters:
Cameron#7818

**Comment by TehTurk** [comment]
I'm aware it may not actually be Null, while the field is driven I think the parent would still be whatever it had prior or it'd be on the root, can you check and see?
