### ISSUE TITLE
Give Desktop Mode it's own Audio Profile for Input and Output

### ISSUE THREAD

**Issue by FlameSoulis** [Neos-Metaverse/NeosPublic#1862]
## Is your feature request related to a problem? Please describe.
This could hold relationships to any audio profiling issues.

## Describe the solution you'd like
This is a QoL request to have Desktop Mode's audio settings be separated into their own profile. This means that when in Desktop mode, the audio devices used can be set to be different from when in VR.

## Describe alternatives you've considered
Only workaround is using an audio manager like VoiceMeter to conjoin all audio devices to a virtual device.

**Comment by Frooxius** [comment]
This has been implemented weeks ago, Neos automatically switches the devices as you toggle between VR and Screen. I've been using it every day without an issue, is this not working for you?

**Comment by FlameSoulis** [comment]
Sounds like this may be a conflict with Screen mode rather than Desktop mode, since launching Desktop mode from the advanced launcher results in a black screen, so I thought it was a place holder. I will test this and respond back with an update.

**Comment by Frooxius** [comment]
Do you mean this option? 
![image](https://user-images.githubusercontent.com/8838625/112179646-28a6bc00-8bfb-11eb-8989-c64ecaab6a7d.png)

You shouldn't be using that at all, as the label of it says, it's for development testing only.

The new desktop mode is currently activated by launching in VR and pressing F8 while it's in development, there's no other proper way to use it yet.

**Comment by FlameSoulis** [comment]
Yes, that is correct. I figured the 'warning' was mostly to explain it was still in development since I didn't want to turn my HMD on while I was going to be in 'desktop mode'.

The labeling of that mode may be another issue that honestly may not require a ticket since the mode is actively in work.

**Comment by shiftyscales** [comment]
When it's ready, the new desktop mode will be replacing it outright/could be launched alone, @FlameSoulis.

We're just making sure there is full feature parity with the existing screen mode functionality before the swap is made.

**Comment by Frooxius** [comment]
No, it's just an internal thing I used for some testing during development, but not something usable outside of that, hence the warning. The option will go away soon.

The audio device switching works as it should in the new desktop mode toggled by F8 for me. Given this is based on misunderstanding, can the issue be closed?
