### ISSUE TITLE
Logging out affects favorited items such as Avatars, Keyboards, Cameras etc

### ISSUE THREAD

**Issue by FlameSoulis** [Neos-Metaverse/NeosPublic#1867]
## Describe the bug
Logging out results in your avatar becoming unfavorited.

## Relevant issues
No related issues could be found (search filter used: _is:issue is:open avatar_)

## To Reproduce
1.  Have an avatar favorited in inventory.
2. Log out.
3. Log back in.
4. Check inventory to see that the avatar has been unfavorited.

## Expected behavior
A favorited avatar should **remain** favorited. Logging out should not change this on the account.

## Screenshots / Video
I Will provide a video soon (have to blur out login credentials)
EDIT:
https://user-images.githubusercontent.com/6835457/112256539-5101db00-8c3a-11eb-95a1-8e67dd7ab76d.mp4

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes (this was also tested by quitting after logging out and signing in from a logged-out state)
 - Neos Version: 2021.3.23.391
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: Unsure

## Additional context
As noted in the video (to be posted soon): it's possible the syncing done on log out could be a possible culprit.

## Reporters:
Discord: Flame Soulis#6005

**Comment by H3BO3** [comment]
I can confirm this happens not only with the avatar but with an inventory-favorited cloud home, which means it may happen with other things as well, like keyboards.

**Comment by Frooxius** [comment]
Fixed in 2021.3.25.399, it was happening to all inventory favorited items/worlds. Thanks for report!
