### ISSUE TITLE
Xiexie toon default light ramp far too bright

### ISSUE THREAD

**Issue by InsaneGrox** [Neos-Metaverse/NeosPublic#1868]
## Is your tweak request related to a problem? Please describe.
Currently avatars using Xiexie toon are overly-bright in worlds where avatars using PBS metallic or specular look fine, to the point of where they can become over-bloomed and glow to the point of being blinding, this is a problem for world lighting as this means I either have to light for PBS or Toon, and I always light for PBS, so currently in my worlds, players using XieXie toon look far brighter than intended.

## Describe what would you like tweaked
Darken the toon ramp a bit, specifically to the point of where the average brightness is in-line with PBS Specular.

## Describe alternatives you've considered
Brighten PBS materials, but this would screw with worlds far too much for it to be a viable solution, another is a maximum brightness clamp specific to Xiexie toon to prevent overblooming.

## Additional Context
Just to test this, spawn a Xiexie toon material orb next to a PBS specular material orb, in 99% of cases, the xiexie toon orb is nearly twice as bright, to the point of scenes where PBS specular looking fine cause Xiexie toon to look like a blooming mess.

**Comment by TehTurk** [comment]
It was actually requested that the ramp was lightened prior because before when it was implemented it was too dark. I would wait for the upcoming Gamma changes before this is considered, feel free to repoke this if it's still an issue.

**Comment by InsaneGrox** [comment]
I still seriously don't think there should be a massive difference in luminance levels between toon and PBS (ideally they should be nearly identical),  but this does seem like something that should come after gamma correction, maybe not outright closing instantly though...
