### ISSUE TITLE
Frame rate affects Game pad look sensitivity.

### ISSUE THREAD

**Issue by LewisSnow** [Neos-Metaverse/NeosPublic#1869]
## Is your tweak request related to a problem? Please describe.
Using Gamepad controls, the look sensitivity is affected by your framerate. The higher the framerate, the more sensitive the control is- vise versa.

## Describe what would you like tweaked
This should not be affected by framerate.

**Comment by Frooxius** [comment]
Fixed in 2021.3.25.399, thanks!
