### ISSUE TITLE
[Regression] Context Menu Quick Swipe Issues

### ISSUE THREAD

**Issue by FlameSoulis** [Neos-Metaverse/NeosPublic#1870]
## Describe the bug
If you hold down the context menu button and then move the selection laser over the menu item, it will no longer quickly activate the menu item when the button is released.

## Relevant issues
Possibly related to any input binding issues

## To Reproduce
1. Hold down the context menu button.
2. Move the laser over a context menu item that can be activated.
3. Release the button.

## Expected behavior
Release the context menu button activates menu item like if the button or trigger is pressed to activate the item if the button is pressed normally.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.23.391
 - Neos Platform: Windows
 - Regression: [Did this work before? Yes, but unable to inform of when it was active

## Additional context
This was relayed by experienced users who noticed the issue.

## Reporters:
Flame Soulis#6005
DeliriousJax#0507

**Comment by Frooxius** [comment]
I'm not sure what you're basing this on, but this was never implemented in the first place. Some people requested it, but instead we're using trigger for the flick activation, not holding the context menu button.

Doing that is not possible on all platforms, as holding the context menu button has a different function, which is why the implementation was not done in the first place.

**Comment by ohzee00** [comment]
Flame Soulis is onto something, I was looking for someone who had a similar issue before posting but they are referring to the swipe gesture like ya mentioned Froox (which you hold trigger for, not context menu button). I can confirm that doing such in VR does not fully work or very delayed, can't really tell.

It seems tooltip context menus work fine but the locomotion/empty hand context menu does _not_ fully work with the hold trigger and swipe gesture, confused me for a while thinking the gesture was removed.

**Comment by H3BO3** [comment]
@ohzee00 Do you happen to have a video? Does it still happen if you do it really slowly? Is there a particular stage it's not working at, like the disk collapsing around the laser hit point when trigger is pulled, or the options not activating even when the disk is dragged all the way through the button?

**Comment by ohzee00** [comment]
> @ohzee00 Do you happen to have a video? Does it still happen if you do it really slowly? Is there a particular stage it's not working at, like the disk collapsing around the laser hit point when trigger is pulled, or the options not activating even when the disk is dragged all the way through the button?

Oh boy, I don't have a video sadly and I don't fully know how to record during VR. Though when I was doing it, the dot for the laser while swiping goes _past_ the original circle in the middle and does not activate the menu item(like locomotion or other buttons), or like you said, the option not activating even when the disk is dragged all the way through the button. Prior to this you just had to touch the button with the laser dot when holding trigger to activate any menu.

**Comment by ohzee00** [comment]
https://user-images.githubusercontent.com/33611545/112276310-f9259d00-8c56-11eb-83c6-16251006e346.mp4

This can be seen in the new desktop mode too.
(Juust got out of VR earlier and stuff needs to be charged so I can't test in VR)

**Comment by TehTurk** [comment]
Thanks for the Video Ohzee! I've renamed the issue to reflect stuff a bit better.

**Comment by Frooxius** [comment]
Thanks for the info! Yeah this behavior is definitely a new bug, I think I know what's happening, I'll try to get fix in the next build.

**Comment by Frooxius** [comment]
Should be fixed in 2021.3.25.399 now, sorry for the trouble!
