### ISSUE TITLE
Volume meter reports volume when playback is paused

### ISSUE THREAD

**Issue by Toxic-Cookie** [Neos-Metaverse/NeosPublic#1875]
## Describe the bug
The volume meter will report a number that isn't 0 when playback is paused in the source.

## Relevant issues
None found.

## To Reproduce
1. Add a volume meter component.
2. Add a volume source to it.
3. Play the audio for a bit and pause it.
4. Notice that the volume is still fluctuating even though playback has paused.

## Expected behavior
When playback is paused, the volume should be 0.

## Screenshots / Video
None.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: It's always been around I think?
 - Neos Platform: Any
 - Link to reproduction World/Item: None
 - Regression: No

## Additional context
None

## Reporters:
Toxic_Cookie#8064

**Comment by Frooxius** [comment]
What are you using as the audio source? I tested this with audio player, but the volume goes correctly to 0.

**Comment by Frooxius** [comment]
Hmm looks like this might be related, are you using the same video source? https://github.com/Neos-Metaverse/NeosPublic/issues/1856

**Comment by Toxic-Cookie** [comment]
It does mainly happen with video texture provider, yes.

**Comment by shadowpanther** [comment]
It's also flickering between two values (probably the last two from when the video was playing) when the video is paused.

**Comment by AshtonSparx** [comment]
Relevant issue #1856

**Comment by Frooxius** [comment]
Ok it should be fixed in 2021.3.27.510 now, thanks for report!
