### ISSUE TITLE
Headless client calculates world running time with an offset when checking for forcedRestartInterval condition

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#1876]
## Describe the bug
If `forcedRestartInterval` is set for the world in the config, the time the world was running for is calculated with an offset equal to timezone offset. This leads to the world that was just started to be instantly restarted if the `forcedRestartInterval` is set to a value in seconds less than the timezone offset:
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/675104/112451300-66742380-8d66-11eb-9cc9-b7f64280747d.png">
<img width="243" alt="image" src="https://user-images.githubusercontent.com/675104/112451318-6b38d780-8d66-11eb-84ab-c880722c73fa.png">
Setting `forcedRestartInterval` to 14400 (4 hours) confirms this as the world restarts after 1 (= 4 - 3) hour. My timezone is GMT+3.

## Relevant issues
Seems mildly relevant to #1364

## To Reproduce
1. In the headless's config, set up a world with `forcedRestartInterval` set to a positive number less than your timezone offset.
2. Run the headless.
3. Oserve the world eternally restarting.

## Expected behavior
World should only restart once `forcedRestartInterval` seconds have passed.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.25.446
 - Neos Platform: Linux headless
 - Regression: No

## Additional context
[Add any other context about the problem here.]

## Reporters:
Shadow Panther#5154

**Comment by Frooxius** [comment]
Ah yeah the calculation was a wrong mix of UTC and Local time, fixed it in 2021.3.27.510, thanks for report!
