### ISSUE TITLE
Ctrl+P desktop gesture does not work with right ctrl

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1877]
## Is your tweak request related to a problem? Please describe.
Left ctrl + P is very hard to hold down while using the mouse. Right ctrl should also work.

## Describe what would you like tweaked
Make right ctrl + P also work.

## Describe alternatives you've considered
Not having right ctrl + P work.

**Comment by Frooxius** [comment]
I made all the Ctrl/Shift/Alt based combinations work with both in 2021.3.27.510, thanks for the suggestion!
