### ISSUE TITLE
Change default DistanceSpace on AudioOutput to Local space

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1880]
## Is your tweak request related to a problem? Please describe.
For scalable objects that have ambient or active audio effects, the current default Global DistanceSpace causes the objects to not respect their scale. It is generally more immersive and intuitive to have objects that have their volume scaled to their size when spatialized. Users currently often build content without considering this option in part due to a lack of awareness of its existence, but also potentially from building content without consideration for scaling.

E.g. for sound effects that are part of an equippable tool, or on an avatar, the sound will remain the same sound regardless of the avatar/tool's scale. With scaling of objects, and avatars such a prominent feature in the engine, I believe using the Local DistanceSpace would be a more suitable default option.

## Describe what would you like tweaked
Default DistanceSpace on AudioOutput to Local from the current default Global.

## Additional context
As discussed during the implementation of the feature #1350 - existing content should remain in the Global DistanceSpace to respect its original behavior, but going forward, new content made by users would see the full benefit of the Local DistanceSpace by default.

And the most important context: I considered this tweak after bouncing around in a scaled down bounce house from GearBell's Toyshop, and noticing it was still playing the sound at full volume even after everyone in the room grew back to normal size.

![Context1](https://user-images.githubusercontent.com/54213390/112567657-77d92200-8d9e-11eb-9aa6-24c13250c05d.png)
![Context2](https://user-images.githubusercontent.com/54213390/112567670-7b6ca900-8d9e-11eb-9e03-4d313c777447.png)

**Comment by Frooxius** [comment]
I can change the default, but existing content will still use the old one. We can't change the behavior on it, for the risk of breaking existing setups (e.g. worlds that have audio sources with scaling already setup).

**Comment by shiftyscales** [comment]
I think it will be a great tweak, thanks @Frooxius!

**Comment by Frooxius** [comment]
Changed in 2021.3.31.528!
