### ISSUE TITLE
Audio Degrading issue

### ISSUE THREAD

**Issue by Jaidendude** [Neos-Metaverse/NeosPublic#1881]
## Describe the bug
Over the course of an hour, audio goes from perfectly clear to broken and static like. This issue resolves itself if swapped into desktop mode with F8

## Relevant issues
Unknown

## To Reproduce
Unknown if it's possible to reproduce for anyone else, but this issue consistently happens to me over the course of an hour. Restarting the game does not fix the issue, but restarting my PC does.

## Expected behaviour
Audio should be consistently clear

## Screenshots / Video
https://drive.google.com/file/d/1uplpQBUdXO_Q1gVg81vHZfgpZHhx0d-8/view?usp=sharing
Audio recording of degraded audio, before pressing F8 and swapping to desktop mode, the issue rectifies itself immediately.

## Bug information (please complete the following information):
 - How often does it happen: Always, started approx. 3 days ago
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.25.446
 - Neos Platform: Windows
 - Link to reproduction World/Item: Happens anywhere
 - Regression: Yes, unsure what build specifically. Last week w/c 15th / 8th Mar it worked.

## Additional context
N/A

## Reporters:
Jaiden#1262

**Comment by Jaidendude** [comment]
Update:

Going into desktop mode when the issue occurs for about 5-10 minutes appears to resolve the audio issue completely.

**Comment by shadowpanther** [comment]
I've encountered the same distortion a bunch of times, but this is not something that happened just a few days ago. I was thinking it's the network bandwidth/stability issue, but that might be this same issue instead. I'll try switching the audio output or going into the desktop mode (which too switched the output) next time I encounter this to see if that gets rid of the distortion.

**Comment by Frooxius** [comment]
We haven't changed anything with audio system since the last week, so I'm unsure what could it be. Given that you need to reboot your PC to solve it, it might be something on your system, rather than in Neos itself.

When this problem occurs, do you have a different audio output device chosen in Neos settings perhaps? If you choose the default one and change the audio device in Windows settings, does the problem persist?

**Comment by Jaidendude** [comment]
After playing for a few hours I've not encountered the issue using the default audio device.

Next time I'm on neos, I'll use my alt audio device, then see if switching it over to default fixes the audio issue.

**Comment by Jaidendude** [comment]
Can confirm that audio degrading goes away when switching back to the default audio output @Frooxius

**Comment by TehTurk** [comment]
Is this still an issue at all? It seems like it might have been an hardware issue vs a Neos Issue.

**Comment by Jaidendude** [comment]
> Is this still an issue at all? It seems like it might have been an hardware issue vs a Neos Issue.

I'll spend some time in Neos tonight and see if the issue is still persistent, I did meet another user who had this issue but it didn't resolve with changing to default output

**Comment by Frooxius** [comment]
I have a potential fix coming in the next build.

**Comment by Frooxius** [comment]
Ok fix is out in 2021.4.17.185, please let me know if the issue still persists!

**Comment by Jaidendude** [comment]
Seems like the issue is still persisting, a friend of mine is also having audio crunching issues. Waterfox#1142

Swapping over to my audio output starts the crackling/crunch immediately, but it isnt nearly as bad as the original recorded audio in the OP. Swapping back to default audio fixes the issue.

**Comment by shiftyscales** [comment]
This issue should hopefully now be dealt with fully as of `2021.4.24.620`. It can be reopened if any other cases ever present themselves.

> - Fixed glitchy/crackling audio when using the Audio Output Device configured in the Settings (reported by @ Zane, @ kleinlowe#2600, @ chemicalcrux, @ H3BO3, @ Shadow Panther [RU/EN, UTC+3], @ Knifa and others)

**Comment by Readun** [comment]
Sadly it seems it didnt fully?
Had it heavily in Keikos world today, but only his Broadcast audio stream. It ... fixed itself after a Minute or two.
Later I noticed very rare cracklings in Honeybees world, when people spoke. 

Still need to watch it closer. 
Its was quite rare for me before the fix aswell, so... a bit hard to reproduce. (Being on Index)
 
If more users will having it, then it might be something else aswell (As in, there were more then one bug that caused the crackeling)

**Comment by Aerizeon** [comment]
Yeah, I also encountered the issue briefly today, for the first time.
Didn't see anything in the logs that seemed relevant.

**Comment by Frooxius** [comment]
Does this affect all audio? Or only voice?

What is the selected option in Audio Output Device in Neos?

**Comment by Aerizeon** [comment]
@Frooxius In my case, all audio at once. It seemed to go away when I closed all other bg worlds.

**Comment by Frooxius** [comment]
What is the selected option in Audio Output Device in Neos Settings when this happens?

**Comment by Aerizeon** [comment]
System default - I don't use the overrides, since you mentioned that they introduce latency.

**Comment by Frooxius** [comment]
In that case this is unrelated to this issue then, since the audio output system that was fixed isn't used at all. Could be just general overload or some other issue.

**Comment by Aerizeon** [comment]
Ah okay, sorry ^^;

**Comment by shadowpanther** [comment]
I encountered voice distortion yesterday while being on desktop (switched from vr) with a non-default audio output selected. Background music seemed to be fine at the same moment, so I'm not sure if this is related.
