### ISSUE TITLE
Pressing Esc on virtual or physical keyboard toggles Dash in VR mode.

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#1883]
## Describe the bug
In VR mode, pressing Escape key on a physical keyboard or a virtual Neos keyboard brings up the Dash, regardless of whether the input focus is in a text field (typing) or not (moving). Escape should only bring Dash in Desktop mode (or at least when not typing).

## Relevant issues
When new input binding was introduced, a bug was discovered and quickly fixed when WASD input in any text field was passed to the locomotion. Not sure if the issue was made for that. Seems like the same is happening here.

## To Reproduce
1. Launch Neos in VR mode
2. (optional) click into a text field so your virtual keyboard pops up and gets you into typing mode
3. Press Esc on either keyboard

## Expected behavior
Esc shouldn't bring up the Dash in VR mode.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.25.446
 - Neos Platform: Windows at least, but most likely Linux too

## Reporters:
Shadow Panther#5154 chemicalcrux#1298

**Comment by 3x1t-5tyl3** [comment]
I feel like all inputs in vr should be mostly disabled (except f8?) until switched to desktop. 🤔 
Just my opinion though.

**Comment by Psychpsyo** [comment]
I like that keyboard inputs still work while in VR cause it a) gives you the option to use a keyboard while wearing the headset and b) gives you the option to use VirtualKey and VirtualMultiKey to bind arbitrary keyboard controls to buttons which is quite nice.

**Comment by Frooxius** [comment]
This is just input priority update issue, where the dash input updates before the typing, so the inputs don't end up blocked by it. I'll have a fix in the next build.

We definitely don't plan on disabling all the inputs in VR. That would break any VR things that use keyboard as well (including typing), but also some usecases - some people (including myself) sometimes use hybrid solution when in VR and using keyboard/gamepad to move around and interact.

**Comment by Frooxius** [comment]
Should be fixed in 2021.3.27.510, thanks for the report!
