### ISSUE TITLE
Facial tracking blendshape heuristics aren't detecting some blendshapes

### ISSUE THREAD

**Issue by sauermon** [Neos-Metaverse/NeosPublic#1884]
## Describe the bug
The blendshapes on an avatar meant for use with facial tracking aren't fully being detected and auto-assigned by heuristics. Namely these blendshapes: Mouth_Upper_Left, Mouth_Upper_Right, Mouth_Lower_Left, Mouth_Lower_Right, Mouyj_Lower_DownLeft, Tongue_Longstep 2, Tongue_Left, and Tongue_Right. The blendshape Mouth_Lower_DownRight is also incorrectly being assigned to Mouth_Lower_DownLeft.

## Relevant issues
An issue relevant to this one is #1830 however this issue mostly refers to the eye tracking blendshapes where as these issues are purely for the facial tracking blendshapes.

## To Reproduce
1. Spawn out the HTC-provided head template with the mouth tracking blendshapes on it.
2. Open the head in an inspector and navigate to the head model slot.
3. Add an AvatarExpressionDriver component.
4. Notice how only 29 blendshapes are auto-assigned, with regards to the blendshapes listed in this report.

## Expected behavior
Expected behavior - and previous behavior for this - is for heuristics to correctly assign all of these blendshapes,

## Screenshots / Video
![2021-03-26_22-35-50](https://user-images.githubusercontent.com/15852289/112708987-a54bcb80-8e83-11eb-8f3d-c11ce94124d3.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.25.446
 - Neos Platform: Any
 - Regression: Yes, Unknown build number, but prior to mid-March 2021.

## Additional context
This issue exists on all avatars I have attempted to setup using the auto-assign from heuristics.

## Reporters:
Ryuvi (Discord: Ryuvi#9094)

**Comment by Frooxius** [comment]
Fixed in 2021.3.27.510, thanks for the report!
