### ISSUE TITLE
Optional "Specialist" Badges.

### ISSUE THREAD

**Issue by InsaneGrox** [Neos-Metaverse/NeosPublic#1886]
## Is your feature request related to a problem? Please describe.
Currently it's hard to tell what people's skillsets are... most people assume the "basics and logix" skillset for everyone despite there being many outliers that specialize in many other things... including things most people generally don't know.

## Relevant issues
N/A

## Describe the solution you'd like
Specialist Badges... basically... optional badges that can be used to show your skillset... examples being
Modeling Specialist (Blender Maya Fusion Ect) (examples include PeterTheThinker Me Ryuvi Staccato and a lot of others)
Lighting/Materials Specialist (probably a sphere with painted on shading and a shadow used for the icon) (Examples include Me Aegis_Wolf and Ryuvi)
Logix/Coding Specialist (Examples include DfgHiatus Coffee and Rubik) (people who know logix very in depth)
Avatar System Specialist (Examples include Me and Turk) (people who know how the avatar system works in depth such as knowing what each Ik value does and how to manually set up nearly everything on an avatar)
Audio/Sound Specialist (Prime example is Lewis_Snow)
NOTE: there are other specializations that exist... these are just examples...
NOTE 2: To prevent badge collectors... I'd suggest only allowing players to choose one or two of these to display... or requiring that players prove that they indeed specialize in those categories.

## Describe alternatives you've considered
A proper profile system so I can display my skillset publicly... that would also work for that purpose.

**Comment by Psychpsyo** [comment]
I'd prefer something like a profile system where people can just write down their skills.

**Comment by Zyzyl** [comment]
Yeah, it sounds to me that this might fit into the social profiles system - see https://github.com/Neos-Metaverse/NeosPublic/issues/110

**Comment by AshtonSparx** [comment]
Yeah, can't really have badges for everything. Would be much better when we get profile bios and you can write a short paragraph about yourself.

**Comment by shiftyscales** [comment]
Mhm. As others have commented, profiles would take care of the needs of this issue. Additionally, it be pretty unwieldly/there wouldn't really be any means to vet who actually is a 'specialist' so anyone could make claim that they're anything if they wanted to. This isn't something that needs to be implemented as an official system, and the community has already made tools to display their own custom badges.
