### ISSUE TITLE
Contacts UI Disapearing When Pressing ESC key

### ISSUE THREAD

**Issue by RueShejn** [Neos-Metaverse/NeosPublic#1888]
## Describe the bug
All text in the contacts screen disappears when closing keyboard opened from the contacts search bar.

## To Reproduce
1.open your dash
2.go to the contacts screen
3.click on the search bar ABOVE your contacts to open your keyboard
4.press the ESC key on your physical keyboard

## Expected behavior
After pressing the ESC key on your physical keyboard all text and all of your contacts will disappear and will not reappear until Neos is restarted

## Screenshots / Video
https://www.youtube.com/watch?v=Pr5VQkxQ5Ug 

## Bug information
[DESKTOP-Q17TSB7 - 2021.3.27.510 - 2021-03-27 10_24_13.log](https://github.com/Neos-Metaverse/NeosPublic/files/6215922/DESKTOP-Q17TSB7.-.2021.3.27.510.-.2021-03-27.10_24_13.log)
 - Happens Every time
 - It dose not persist after Neos is restarted
 - Neos Version: 2021.3.27.510
 - Neos Platform: Windows

## Reporters:
RueShejn#8897

**Comment by Frooxius** [comment]
Fixed in 2021.3.30.508, thanks for report! It was inserting control characters (ASCII ESC), so this probably caused problems in other places too.
