### ISSUE TITLE
Make Desktop Reticle fade faster or adjustable.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1890]
## Is your tweak request related to a problem? Please describe.
I frequently want to take quick screenshots in desktop without the reticle showing and waiting for it to disappear is annoying, especially if I'm trying to screenshot something that's temporary.

## Describe what would you like tweaked
The reticle should almost instantly disappear as soon as I stop touching the mouse as I don't really need it anymore then. (or make the time it takes for it to disappear adjustable)

## Describe alternatives you've considered
Keeping it like this which is not *that* terrible but does get a little annoying quite frequently.

**Comment by Frooxius** [comment]
It's going to be adjustable once we have reworked settings, until then I'm probably going to keep it as it is.

For capturing screenshots I recommend using the Shift+P key combination.

**Comment by Psychpsyo** [comment]
Ok. I just prefer steam screenshots as they don't spawn an image into the world.
