### ISSUE TITLE
Userspace windows don't block Dash Interactions in Desktop mode

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1891]
## Describe the bug
Clicking in a local space menu (like the debug menu) still clicks through to the dash below it.

## Relevant issues
Didn't find any.

## To Reproduce
1. Open the debug menu.
2. Interact with the dash through it.

## Expected behavior
The dash should not receive the inputs.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.27.510
 - Neos Platform: Windows, Probably any
 - Regression: Don't think so.

## Reporters:
@Cameron#7818

**Comment by Frooxius** [comment]
Which mode does this happen in? Is it in VR? Or in desktop?

**Comment by Psychpsyo** [comment]
Desktop, when switching to it from VR.

**Comment by Frooxius** [comment]
I'm sorry, but I can't replicate this. The interaction is correctly blocked when I try. Are there any extra conditions for the replication?

**Comment by Psychpsyo** [comment]
This issue should probably get the Desktop mode label and I was curious if my last post was clear enough to make reproduction possible.

**Comment by Psychpsyo** [comment]
On that note, it seems like this issue is understood now so I'm not sure if the 'Needs More Information' tag is still warranted.
