### ISSUE TITLE
[Regression] triggering a video to play before being loaded prevents audio from loading

### ISSUE THREAD

**Issue by mralext20** [Neos-Metaverse/NeosPublic#1892]
## Describe the bug
when a video player is set to play before it is loaded for a client, the client will not get audio when the video does finally load. 

The recent change resulting from #1875 are the most likely cause of this.

## Relevant issues
[Did you find any existing issues relevant to this one? If you found the same issue, please contribute to that one instead of making a duplicate.]

## To Reproduce
spawn the tutorial panel (neos essentials -> Tutorials -> Tutorial Browser)
select a video 
(here, the panel will automaticly start the video after a second or two.)
the video will play, but without audio. pausing and playing the video will resolve this.

## Expected behavior
the video loads, and audio proper plays. 

## Screenshots / Video

https://user-images.githubusercontent.com/4016295/112736085-f3ed7a00-8f04-11eb-88b2-cc203e9f7fd4.mp4

## Bug information (please complete the following information):
 - How often does it happen:always - video must be set to 'playing' before the video loads
 - Does the bug persist after restarting Neos? yes
 - Neos Version: 2021.3.27.510
 - Neos Platform: tested on Windows
 - Link to reproduction World/Item: `neosdb:///aaebd22409b2bc0b662b525a79982f07b21caaa199cd1d7d44df852ccb7f975f.7zbson`
 - Regression: yes - new in 2021.3.27.510

## Reporters:
discovered by Gpig#7042 , Alex from Alaska#2020

**Comment by mralext20** [comment]
Duplicate of #1887

**Comment by Frooxius** [comment]
Fixed in 2021.3.28.524, thanks!
