### ISSUE TITLE
Expose OrderOffset on Slot [For Plugins]

### ISSUE THREAD

**Issue by Toxic-Cookie** [Neos-Metaverse/NeosPublic#1893]
## Is your tweak request related to a problem? Please describe.
The Slot component does not have a public property to change OrderOffset.

## Describe what would you like tweaked
OrderOffset being changed into a public property just like Name, Tag, etc.

## Describe alternatives you've considered
Getting the sync member could work but is hacky.

## Additional context
This works:
![image](https://user-images.githubusercontent.com/66691163/112739123-910cda80-8f26-11eb-8785-067fb59a6a6c.png)

This doesn't:
![image](https://user-images.githubusercontent.com/66691163/112739117-6d499480-8f26-11eb-8fff-112365bf7516.png)

**Comment by Frooxius** [comment]
Exposed in 2021.3.30.508!
