### ISSUE TITLE
Cannot Access Camera Dialog Windows in Desktop Mode

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#1895]
## Describe the bug
Certain Dialog Windows are not accessible within Desktop Mode.
## Relevant issues
-none-
## To Reproduce
[Steps to reproduce the behavior:
Spawn Streaming/Camera Dialog, does not respect any of the Desktop Mode Setups.

## Expected behavior
I should be able to use it like any other dialog window.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/26357446/112755107-3c607280-8fad-11eb-902e-cec30b767ab6.png)

## Reporters:
Turk

**Comment by Frooxius** [comment]
The dialog is now positioned properly in 2021.3.29.523. However it's still not fully supported, you won't be able to mirror the camera and interactions will be weird. It has to be reworked to work properly.
