### ISSUE TITLE
Number Inputs on top row do not sanitize while typing in InputFields. Allowing Tool Swap when pressed

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#1896]
## Describe the bug
Numpad Input Keys do not sanitize while typing in InputFields. Allowing Tool Swap when pressed. Reported by ChrisWarner and AnythingItDoesn'tReally Matter. 

## Relevant issues
-none-

## To Reproduce
1. Enter into a Typing Field
2. Proceed to use your number keys
3. Watch as the Tools swap while typing

## Expected behavior
It shouldn't be swapping while Typing.

## Bug information (please complete the following information):
Consistent

## Reporters:
ChrisWarner103, AnythingItDoesn'tReallyMatter

**Comment by Frooxius** [comment]
Fixed in 2021.3.29.523, thanks!
