### ISSUE TITLE
Texture Fields do not accept reference Assignments from Desktop

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#1897]
## Describe the bug
Texture Fields in Materials do not accept assignment when held by the laser in Desktop.

## Relevant issues
-none-
## To Reproduce
1. Find A Material
2. Get a Texture
3. Try to assign to the Texture Field while holding with Laser

## Expected behavior
It should be assigning correctly 
## Screenshots / Video
https://i.gyazo.com/fb83790b53d15ee64cf39b7f4c659fff.mp4

## Bug information (please complete the following information):
 Regression occured

## Reporters:
ToMo

**Comment by Frooxius** [comment]
Fixed in 2021.3.29.523, thanks for logging this!
