### ISSUE TITLE
[Logix] OnSave event Node

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#1899]
## Is your feature request related to a problem? Please describe.
Sometimes while creating items I'd like to have logix that deletes itself before it's saved.

## Relevant issues
-

## Describe the solution you'd like
An "OnSaved" event node that gives an impulse from the user who saves the item just before saving the item allowing for "Impulse Propagation" to happen and certain logix to fire. Example: write notes writing into fields, delete slot etc.

## Describe alternatives you've considered
Instead of having logix that fires when saving I just manually do whatever is needed and then save the item.

## Additional context
A perfect example of this is for example tools. I have a tool that I'd like to automate the versioning of and having it done on an "OnSaved" event would make it very easy for me to update the version number. Aswell as a host of other things that would be nice to have automated but not saved with the item in question.

**Comment by Frooxius** [comment]
Added OnSaving node in 2021.3.30.508, let me know if there are any issues with it!

**Comment by 3x1t-5tyl3** [comment]
Thanks for adding this! Though an issue I found with it is that when saving an item it also fires on the object in world and not just on the item which is actually saved.

I would've expected this only to "fire" on the saved version and not the one in world *being* saved. Example:

https://youtu.be/Qx1udPonccc

In this case the world item should still have the logix but the item in my inventory shouldn't.

I can explain it further if this is confusing or weirdly worded. :)

**Comment by Frooxius** [comment]
That's expected behavior. Neos doesn't really differentiate different types of "Saving", it's all pretty much the same kind of process. There's a few other scenarios where saving process runs as well - e.g. when destroying something for undo step or transferring items.

Neos has other higher level mechanisms built for dealing with specific issues like versioning or resetting state, but that requires understanding of what exactly you need to do.

**Comment by 3x1t-5tyl3** [comment]
My initial impression of it was more along the lines of "When user saves item X to inventory, LogiX could fire which would make sure certain things are for example reset, written, deleted etc."

This came as a direct idea of #1898 where it's nice that those get reset. But having also control of what is reset on any arbitrary field before saving would've been nice.

I did have the idea aswell of it being able to just "propegate" the impulse without it affecting the item in world. Though I had no idea of the internal implications of what that could mean.

That said I am fairly certain I can still make this work. Given we also have a way to detect when something get's spawned out.

I do have to say that I'm a bit concerned with the implications this could have with the way neos handles destroying and saving?

**Comment by shiftyscales** [comment]
@3x1t-5tyl3 - you can already reset arbitrary fields through use of Logix/DataPreset/DataPresetValue https://youtu.be/O255_Jlevr4

Or through use of Dynamic variables/DynamicValueVariableReset/DynamicReferenceVariableReset.
