### ISSUE TITLE
Attaching objects to messages in desktop mode sends empty message.

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#1900]
## Describe the bug
When sending messages using the new desktop mode, grabbing an item and opening the dash menu causes the item to be dropped. 
Clicking the "attach item" button in a message window after this point will send that user an empty message.

## To Reproduce
1. In Desktop mode, open the Dash Menu
2. Select the "Contacts" tab
3. Select a user to send a message to
4. Close the dash menu
5. Grab an item from the world
6. While still pressing the grab button, open the Dash Menu
7. While still pressing the grab button, press the "attach item" (+) button in the user's chat
8. Observe that a message is sent, but with no content

## Expected behavior
1. Messages with no content should not be sent
2. The grabbed item should be attached to a message, and sent to the user

## Screenshots / Video
The following is a result of trying to send an image to someone while in desktop mode:

![Example image](http://files.aerizeon.net/sharex/2021/Neos_03-28c1FqR9prKs.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.28.524
 - Neos Platform: Windows
 - Regression: No

## Reporters:
Epsilion

**Comment by Frooxius** [comment]
Sending items through the old contacts list from the new desktop isn't supported, sorry. It'll have to wait for the reworked UI.
