### ISSUE TITLE
Rotatable Slider not working with desktop rotation bindings

### ISSUE THREAD

**Issue by BlazeVR** [Neos-Metaverse/NeosPublic#1901]
## Is your tweak request related to a problem? Please describe.
The "Avatar Creator Hands" are using the Slider component and preventing free rotating on the Desktop mode (pressing E while holding the item and moving the mouse). 

## Describe what would you like tweaked

> Instead of using the Slider component making the Grabbable component on them by default would allow it. 

EDIT: Ensure that Sliders can be properly rotated in desktop mode when set to do such

## Describe alternatives you've considered
See above. 

## Additional context
Confirmed with DeadBot#8760

**Comment by H3BO3** [comment]
I don't think this is necessary, this is an issue with Sliders not working properly with rotation bindings in desktop. If the bindings worked properly for sliders and not just grabbables the issue would be fixed. I'm going to make some edits to the issue to convert it

**Comment by Frooxius** [comment]
Fixed in 2021.3.29.523, this wasn't issue with bindings, but rather how the freeform rotation is achieved. Thanks for report!
