### ISSUE TITLE
Minecraft Locomotion incomplete

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1903]
## Is your tweak request related to a problem? Please describe.
Latest Desktop update brought us Minecraft locomotion (double tap WASD to run). My problem is: There's now not a single key to transition to running anymore, which Minecraft has that bound to CTRL.

## Describe what would you like tweaked
Make CTRL enable run mode in addition to the double tapping.

## Describe alternatives you've considered
Keeping it like this which doesn't really have any advantages over allowing for both.

## Additional context
I use the CTRL method in Minecraft already.

**Comment by Frooxius** [comment]
Minecraft has been only used as inspiration for the keybinds, our goal isn't to completely clone its bindings, since we're not Minecraft and we need to consider other Neos actions. Ctrl is and is going to be used for other actions (e.g. commonly Ctrl+C, Ctrl+V).

**Comment by Psychpsyo** [comment]
What about another key like Alt then?

**Comment by Frooxius** [comment]
Alt already has another planned use as well. We could dedicate one of the letters for running though.

**Comment by Psychpsyo** [comment]
Ok. That'd be good.
