### ISSUE TITLE
Locomotion quick-switching

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1904]
## Is your feature request related to a problem? Please describe.
Opening up the radial menu and navigating to the locomotion modules would be slower than double-tapping jump to enable fly/noclip.

## Relevant issues
Didn't find any

## Describe the solution you'd like
Double-tapping Space should put the player into fly mode or noclip, depending on what's available. (maybe even have an option for which should take priority if both are available) Double-tap on jump doesn't have any other use so it'd just add more options and not inhibit anything.

## Describe alternatives you've considered
Not implementing this and going through the radial menu every time.

**Comment by Frooxius** [comment]
It's planned for the double tap to toggle between last two locomotion modules. It's not possible to do specific locomotion modules in general, as each world can have an unique set of them, so we can't make assumptions on what's available and what's not.

**Comment by TehTurk** [comment]
Can I suggest that we don't use this to swap between locomotions? If users are going to be using these inputs to create modes or addons with this I don't know if necessarily typing that to the Jump button is ideal. For Example if I do Double Jumping it's gonna completely mess with that. Or maybe I want to suppress jumping but have jump do something else on double tap. It's stuff like that.

**Comment by shiftyscales** [comment]
This would be a generally useful change I think, and if a particular user wishes to disable it, they could adjust their bindings accordingly when it's added, @TehTurk.

Similarly, if there is an experience that is dependent on maintaining control of the user's locomotion mode, the creator of the experience can build their experience to ensure they maintain control of the locomotions available to the user.

**Comment by TehTurk** [comment]
No, while your allowing for customizability your impacting what creators and users creatively can do when they are making games or setups for tools, experiences or interactions. Worlds/Locomotion modes do not have control over bindings and shouldn't and throwing the responsibility to the creator is unfair because they need to work around the issue instead of having the tools to address it. Your base keybinds should consider all. I'm aware some key inputs are still in flux but I think having dedicated ones to swap locomotion is fine. Most folks will use the context menu and should. Being able to quickly swap isn't something we have in VR.

**Comment by StarfishHidari** [comment]
I agree with turk in that this would create additional limitations for world creators having to accommodate desktop users in their worlds, no such quick swap function exists in VR and it works fine. Making double tap space bar the default binding with the option to set it to something different doesn't fix the issue of world creators having to design around it.

**Comment by Frooxius** [comment]
Hmm that might actually be better to leave the space for double jump and other actions as default. If someone really wants to rebind it in the future to that, they could, but then they would also deal with the problems with their bindings.

I think just mapping the locomotion module switching to dedicated keys would work better in that case. E.g. we could do something like Shift+1, Shift+2, Shift+3 and such to toggle between them, the way you toggle between tooltips.

Double tapping spacebar is definitely satisfying in games like Minecraft, but Minecraft doesn't have double jump (not counting mods), whereas a bunch of Neos content might.

**Comment by shiftyscales** [comment]
Leaving this issue open until the proposed locomotion quick-switching is integrated, but it's also worth noting that it's possible to make your own systems to toggle locomotion in the meantime.

E.g. I personally have noclip bound to V like in Garry's Mod, and in addition to that, I also have it preserve my momentum from noclip too when switching back to physical locomotion, allowing me to fling myself.
