### ISSUE TITLE
Up-/Down-Arrow Keys in Contacts List to go through Contacts

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1905]
## Is your feature request related to a problem? Please describe.
I intuitively try using up and down arrow keys to switch through contacts in my contacts list which it doesn't do.

## Relevant issues
Didn't find any.

## Describe the solution you'd like
Clicking up and down arrow keys should make you go to the next/previous contact in the contacts list.

## Describe alternatives you've considered
Clicking them one by one.

**Comment by mralext20** [comment]
This is probably unlikely to be implemented until the contacts menu is reworked into a facet based menu ( like the world's menu is right now) 

But I'll wait for froox / shifty to close this out

**Comment by Frooxius** [comment]
Sorry, I don't have any plans to update the old Contacts UI with new features like this, it'll have to be reworked. This wouldn't be likely considered as a thing specific to particular UI anyways, key based navigation is something that's for the general UI framework to deal with instead.
