### ISSUE TITLE
Switching to another tool with desktop shortcuts causes the spawned tooltip to delete itself along with any assets tied to it

### ISSUE THREAD

**Issue by ohzee00** [Neos-Metaverse/NeosPublic#1906]
## Describe the bug
Spawning out a tooltip that holds assets like the material tip also deletes any materials/assets connected to it upon switching to another tool via desktop keys.

## Relevant issues
This also seems to delete any extra spawned tooltips when switching, for example spawning a gun and equipping it then using a desktop shortcut for the dev tip will delete said gun.
 

## To Reproduce
1. Spawn out the material tooltip via your inv
2. Create new material
3. Put the material orb in the material tip
4. Apply material to a object
5. Switch to dev tool tip with 2 (any desktop bind to switch works)
6. Notice that the applied material is deleted and checkerboarded along with the held tool

## Expected behavior
Switching should not delete the assets associated with a spawned tooltip.

Should also not delete the held item in general, though that's less of a issue.

## Screenshots / Video
None really needed.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.28.524
 - Neos Platform: Windows
 - Link to reproduction World/Item: 
 - Regression: Technically not a regression for this system wasn't available before

## Additional context
ArcticGamez mentions being able to do this with _only_ the desktop shortcut tooltips but I can't seem to replicate it. As in, switching from the desktop shortcut material tooltip to the devtip deletes any associated material.

## Reporters:
Original reporter: ArcticGamez#1496

**Comment by Frooxius** [comment]
Fixed in 2021.3.30.508, thanks for report!
