### ISSUE TITLE
Toggle for the quick save feature in the radial menu

### ISSUE THREAD

**Issue by Beaned2000** [Neos-Metaverse/NeosPublic#1907]
## Is your tweak request related to a problem? Please describe.
So every time i find myself miss clicking on the save button on the radial menu trying to equip tools and trying to save screenshots from others. the feature to me is more of an annoyance rather then a help because if i want to save anything i find myself going trough the inventory searching for a location to save it anyway making it kind of pointless because just clicking the green button in the top of the menu is equally as fast.

## Describe what would you like tweaked
i would like to have some way to disable this

## Describe alternatives you've considered
/

## Additional context
I get that this feature is probably mainly added for desktop but in VR it doesn't make much sense to me.

**Comment by Psychpsyo** [comment]
Dito. I also need to reopen my inventory every time I'm about to use the quicksave to pick a folder to save to so it's only really advantageous in desktop.

**Comment by Frooxius** [comment]
I can add a setting, but it'll have to wait for the redesigned Settings UI.

However as noted in the release notes, this is a prelude to planned rework of the inventory UI, which will make the option work in a much more intuitive manner, so that will get better once that's reworked too.

**Comment by Beaned2000** [comment]
hmm while thats pretty good to hear, its probably going to take time i assume. can't we have some sort of temporary solution? since its a recent addition and ive heard quite a few vr users getting annoyed at this addition.

**Comment by shiftyscales** [comment]
No, we can't @Beaned2000. A temporary solution isn't helpful in a situation like this because all it does is effectively waste a developer's time, a resource that's already highly bottlenecked.

It may be inconvenient and awkward in the present moment, but it is transitory. As Frooxius already noted, it is preliminary work towards larger reworks.

Frooxius has also noted a preference to try to tackle the new settings menu soon when it's feasible.

Additional work on the old settings menu takes a lot of his time as it's all hard coded, and as noted, the work will quite literally be scrapped when the menu is redesigned.

**Comment by Beaned2000** [comment]
okay i understand that a rework of the menu first is needed but could we maybe at least have it so that the save to inventory doesn't appear when a tool is soft equipped so i don't keep saving copies of my tools in my main root instead of equipping it?
since that is kind of the main irritating thing about this

**Comment by Frooxius** [comment]
Yeah I can exclude the option for soft equipped items, that seems like a good change in any case.

Sorry that it's going to take a bit, I'm looking into reworking the Settings UI pretty soon, since it comes up so often (no promises yet though!).

**Comment by Frooxius** [comment]
The save item will no longer appear in 2021.3.31.528 when grip-equipping a tooltip. Full toggle will come at later point after settings UI is reworked!
