### ISSUE TITLE
Cannot Exit Facet Edit Mode in Desktop Mode (Your stuck and can't log out)

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#1909]
## Describe the bug
For some folks they have a edit mode facet on their dash. While this isn't the original supported way I do believe the issue of having edit mode not being accessible in desktop to be a bit problematic.

To the point where you can't log out 👀 I'm stuck in Neos Froox help! /s (Sorry for the joke I thought it'd be a nice change of pace)

## Relevant issues
-none-

## To Reproduce

1. Edit Mode Occurs
2. Cannot Exit due to no readily available way to exit 

## Reporters:
Turk, Grost

**Comment by TehTurk** [comment]
I am aware this one is a bit silly, but if going to be handled in some way feel free to close. In just thought this was a really interesting situation to encounter.

**Comment by shiftyscales** [comment]
Am I misunderstanding this issue @TehTurk? The UI edit mode can be toggled on/off with F6. I don't see any indiciation that it's possible to get stuck in this mode.

**Comment by TehTurk** [comment]
Possibly? I wasn't aware of the keybind, so if folks can somehow be able to be aware, it would help. The UI Edit Mode Button has changed a bit on desktop so I wasn't sure which one it was.
