### ISSUE TITLE
Desktop mode object scaling doesn't respect Scalable property of Grabbable component

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1911]
## Describe the bug
While in the desktop mode, scaling an object will ignore the `Scalable` property on the `Grabbable` component, allowing objects to be resized that normally are unable to be while in the new desktop mode.

## To Reproduce
- Enter desktop mode
- Create or spawn a grabbable non-scalable object, e.g. a cube with `Scalable` unchecked
- Grab the object, and scale it

## Expected behavior
- Desktop mode object scaling should respect the `Scalable` property of `Grabbable` components

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.29.523
 - Neos Platform: Windows
 - Regression: No

## Reporters:
epicEaston197# 0793

**Comment by Frooxius** [comment]
Fixed in 2021.3.30.508, thanks!
