### ISSUE TITLE
Opening dash interrupts crouch toggle on desktop

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1912]
## Describe the bug
When crouch is toggled on in desktop mode, opening the dash will make you stop crouching.

## Relevant issues
Didn't find any.

## To Reproduce
1. Toggle crouching on. (double tap C)
2. Open the dash
3. You are no longer crouching.

## Expected behavior
A toggled crouch state should persist even if the dash is opened.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.30.514
 - Neos Platform: Windows, probably any.
 - Regression: Not applicable, new feature

## Reporters:
Cameron#7818, Zaravi#3189

**Comment by Frooxius** [comment]
Fixed in 2021.3.31.528, thanks!
