### ISSUE TITLE
Context menu dismisses itself in screen mode when the user is moving fast

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#1913]
## Describe the bug
If a user in Screen mode is parented to a moving platform, and the speed of said platform is high enough, the user can't operate the context menu because the menu dismisses itself instantly.

## Relevant issues
Not that I know of

## To Reproduce
1. Be in Screen mode
2. Parent yourself to an object that you can stand on (has a CharacterCollider)
3. Make this object move
4. Try to open the context menu

## Expected behavior
Context menu should open and be operable independent on moving speed.

## Screenshots / Video
Parenting myself to a cylinder with a Panner3D moving up with speed Y100, then speed Y50 (works at speed Y25):
https://cdn.discordapp.com/attachments/439422161657135106/826531218970378240/2021-03-30_21-53-48.mp4
Same cylinder with a Spinner speed Y180:
https://cdn.discordapp.com/attachments/439422161657135106/826532673455259668/2021-03-30_22-05-17.mp4
World URL:
http://cloudx.azurewebsites.net/open/world/U-Shadow-Panther/R-c3191f02-953c-40a4-bea4-3f551ca56fa0

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.30.508
 - Neos Platform: Windows, but I expect it to behave the same on others
 - Link to reproduction World/Item: http://cloudx.azurewebsites.net/open/world/U-Shadow-Panther/R-c3191f02-953c-40a4-bea4-3f551ca56fa0
 - Regression: No

## Reporters:
epicEaston197#0793 Shadow Panther#5154

**Comment by epicEaston197** [comment]
I was the one who discovered this bug and started the conversation on it

**Comment by epicEaston197** [comment]
I was the one who discovered this bug and start of a conversation on it

**Comment by Frooxius** [comment]
Should be fixed in 2021.4.5.911, please reopen if it persists, as I wasn't able to fully replicate this.
