### ISSUE TITLE
Add PingPong for Panner 1-4D Components

### ISSUE THREAD

**Issue by Toxic-Cookie** [Neos-Metaverse/NeosPublic#1915]
## Is your feature request related to a problem? Please describe.
The Time Int Driver component has an option to PingPong the value which is really handy. However, Panner 1-4D doesn't have this option.

## Relevant issues
None.

## Describe the solution you'd like
Add a PingPong option to Panner 1-4D

## Describe alternatives you've considered
There are a number of ways to work around the problem of not having PingPong available on Panner 1-4D but adding this feature would be a nice quality of life addition.

## Additional context
![image](https://user-images.githubusercontent.com/66691163/113105038-03471e80-91b6-11eb-869b-8cff36f057ab.png)

**Comment by Frooxius** [comment]
Added in 2021.8.13.612, thanks!
