### ISSUE TITLE
Contacts message history loads indefinitely

### ISSUE THREAD

**Issue by Medravr** [Neos-Metaverse/NeosPublic#1916]
## Describe the bug
In the Contacts Menu when clicking on a specific user the right hand side say's "Loading" indefinitely. This was for both the Medra to Creator Jam and Creator jam to Medra Accounts. Because the menu indefinitely loads no messages can be seen or made--including invites.

## Relevant issues
No

## To Reproduce
This is account specific and I think the answer is in the logs. Will be sending.

## Expected behavior
Message system should display message history and buttons.

## Screenshots / Video
![Neos_2021-03-31_04-01-38](https://user-images.githubusercontent.com/46054550/113112384-1d452900-91d7-11eb-8f01-e68a644258d3.png)

## Bug information (please complete the following information):
It happens always.

## Reporters:
Medra

**Comment by shiftyscales** [comment]
I am having this issue between myself, and Somaro. I believe for me, it's one-way though. Only I am unable to read his messages. When I first noticed it, he was able to send me messages and invites without issue, but my message list wouldn't load from him.

Not sure if it's a relevant factor, but - I believe I hadn't sent a message to/received a message from Somaro in probably at least a year prior.

Do you know what the conversation history was like between the Creator Jam, and Medra accounts, @Medravr?

**Comment by shiftyscales** [comment]
I produced a log for this issue by:
- Launching Neos
- Navigating to my contacts
- Repeating the following steps a few times in a row:
-- Selected Somaro in my contacts list and waited 30 seconds
-- Deselected Somaro in my contacts list and waited 10 seconds
- After repeating this process 3 times I immediately exited Neos
[SHIFTYWINDOWS - 2021.3.31.528 - 2021-03-31 13_54_47.log](https://github.com/Neos-Metaverse/NeosPublic/files/6239457/SHIFTYWINDOWS.-.2021.3.31.528.-.2021-03-31.13_54_47.log)

Other notes:
- Tried loading on a new DataPath/Cache path, but it appears to have had no positive effect on the issue. The message history remains stuck.

**Comment by Medravr** [comment]
> 
> 
> I am having this issue between myself, and Somaro. I believe for me, it's one-way though. Only I am unable to read his messages. When I first noticed it, he was able to send me messages and invites without issue, but my message list wouldn't load from him.
> 
> Not sure if it's a relevant factor, but - I believe I hadn't sent a message to/received a message from Somaro in probably at least a year prior.
> 
> Do you know what the conversation history was like between the Creator Jam, and Medra accounts, @Medravr?
There is almost entirely invites coming from the Creator Jam > Medra side. I think there has been some test messages when this was having problems (sometime within the past week). It occurred on Sunday and has persisted.

**Comment by Frooxius** [comment]
Does the message history stay stuck for specific users only? From the log it seems like it's just a transient networking error, but with that I'd expect the issue to clear up at some point. 

@Medravr Can you get me the log please as well so I can check if there's the same thing happening as with Shifty?

**Comment by shiftyscales** [comment]
Medra sent me a log in DM, I'll forward it to you, @Frooxius.

**Comment by shiftyscales** [comment]
And yes, it appears to be specific to only certain users on the contact list. E.g. in my case, it's Somaro I have the issue with, in Medra's case, it's mutual between his Medra, and Creator Jam accounts.

**Comment by Frooxius** [comment]
I've made tweaks to retry logic in 2021.4.2.690 and added more throughput to the cloud infrastructure, seems like the database was getting too throttled in some cases. Reopen if the issues still persist!
