### ISSUE TITLE
The new head and hands are too bright

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#1919]
## What topic do you want to discuss?
The new VR Head and Hands that just got released.

## Goal of discussion
Discuss their design for any ideas, suggestions or issues

## Discussion:

They're too bright. Blinding almost in lower level conditions.

**Comment by TehTurk** [comment]
I do like the new designs, I feel the emission on the material is enough for them, and the lights really aren't required. 

I do feel like the Profile Pictures are a good indicator but it feels confusing as the headsets should be more neutral.
To also note most folks won't have profile pics for a good while, and by then they'd be in their own choice of avatar. Making the Profile pics being there somewhat null.

It'd be neat if the Neos Bot Face was on the headset like  | _ | in some way.

**Comment by Hayden-da-Serg** [comment]
Woops, accidently commented in #1920, but same thoughts still carry over.

**Comment by shiftyscales** [comment]
Ryuvi has confirmed that she has just updated the default head and hand models to be less bright. Thanks for the feedback!
