### ISSUE TITLE
Desktop Dash is problematic sometimes in 2D, Can we use it in 3D?

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#1921]
## Is your tweak request related to a problem? Please describe.
Currently, there are some interactions that will be address for the 2D Dash, I was wondering for those of us who may be used to the 3D interactions, can we get the 3D Dash but with Desktop Mode?

## Describe what would you like tweaked
A way to toggle between Desktop Dash and 3D Dash, I figured this would be handy as the rest of the UI is fleshed out and we have a safe fallback for certain operations.

## Describe alternatives you've considered
-none-

**Comment by Frooxius** [comment]
Sorry, I don't plan on adding support for this, it adds a lot of development burden to work properly.

**Comment by TehTurk** [comment]
Oh? Is there a reason that it wouldn't work out too well? Asking for clarity too. I figure it wouldn't be too different from what was there Prior no?
