### ISSUE TITLE
Notification sounds very quiet

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1924]
## Describe the bug
Notification sounds play very quietly, likely as a consequence of #1880 in changing the default audiospace to local.

## Relevant issues
#1880

## To Reproduce
- Receive a notification

## Expected behavior
Notification sounds play at their previous volume (either in global space, or their corresponding slot size be scaled accordingly to compensate.)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.31.528
 - Neos Platform: Windows
 - Regression: Yes, regression in 2021.3.31.528

## Additional context
Replication case confirmed with the help of Cyro# 5120.

## Reporters:
AshtonSparx# 5050

**Comment by shiftyscales** [comment]
Ah, yes. Inspecting the `Notifications` slot in userspace, it has a scale of `0.001420455` which is likely the source of this issue.

**Comment by Frooxius** [comment]
Yeah it was the scaling, should be back to normal in 2021.4.2.690, thanks!
