### ISSUE TITLE
Make mouse sensitivity adjustable for Screen mode

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#1927]
## Is your tweak request related to a problem? Please describe.
My mouselook speed is *very* slow. Usually in action games I have to adjust mouse sensitivity to 2-3 times the default value to get the speed that is comfortable for me.
There is also a sharp contrast between look speed and freeform cursor speed (in Dash and Context menu) that makes me dismiss my Context menu several times before I manage to slow my fingers enough to keep the cursor in the circle.

## Describe what would you like tweaked
Add a setting to adjust mouselook speed.

## Describe alternatives you've considered
Looking up for some additional software that would modify my mouse movenent speed, forcing me to readjust Windows's mouse speed/acceleration to match my current one.

## Additional context
https://cdn.discordapp.com/attachments/439422161657135106/827207043303473162/2021-04-01_18-42-35.mp4

**Comment by Frooxius** [comment]
Mouselook speed is planned to be exposed in the reworked Settings.

However there shouldn't be any difference between freeform cursor and the dash cursor, they're the same cursor actually - that's using your system pointer speed. We could make that one adjustable as well, but we'd have to simulate the cursor ourselves - right now it represents the position of your actual system cursor over the Neos VR windows, so we don't control how fast it goes.

**Comment by shadowpanther** [comment]
No, the freeform/dash cursor is fine, it uses the desktop's mouse speed. The mouselook speed is what needs adjusting - it is very slow in comparison with freeform/dash cursor speed.
In fact, when I move my mouse a certain amount, I expect the mouselook to cover the same distance (relative to the background) as the freeform would. Right now it feels 5-10 times slower.

**Comment by Frooxius** [comment]
Ah yeah that one will be adjustable for sure!
