### ISSUE TITLE
World Crash in Among Us Map (Permissions Related?)

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#1931]
## Describe the bug
When another users joins a specific world(The Among Us map), The host of the world experiences a world crash after a short delay.

## Relevant issues
Not that I could find unfortunately.

## To Reproduce
Steps to reproduce the behaviour:
1. Open the specified World(neosrec:///U-Maddmaxkz/R-b316d62d-2415-4ab1-91f5-e03d966d190e)
2. Invite another User to the world
3. Observe that it crashes

## Expected behaviour
I'd expect the world to not crash

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.31.528
 - Neos Platform: Windows
 - Link to reproduction World/Item: neosrec:///U-Maddmaxkz/R-b316d62d-2415-4ab1-91f5-e03d966d190e
 - Regression: Not entirely sure

## Additional context
While I'm not sure if this is actually a bug, or if it is a problem with the world setup, I'd still like this to be looked at. 

We're not entirely sure that We'd be able to narrow down what the problem with the world would be without some help. There's clearly something happening in the Logs which I'd like the team to look at. From there you might be able to identify if this is a bug or if its a problem with the world and point us in the right direction. 

We'd appreciate any assistance here. Even if that's just to point out the area we might be able to look into.

Here's a few logfiles from:
Lucas(This is a clean log file and has no other sessions): [DESKTOP-P0VSIH4 - 2021.3.31.528 - 2021-04-01 21_57_45.log](https://github.com/Neos-Metaverse/NeosPublic/files/6247166/DESKTOP-P0VSIH4.-.2021.3.31.528.-.2021-04-01.21_57_45.log)
Nexulan(This has other sessions but the last session appears to be the Among Us map): [log](https://i.probableprime.co.uk/210401-haTezwi6fHIjdY7igHfn.log)

## Reporters:
Nexula, LucasRo7, MAX-KZCLOUD, Me

**Comment by Frooxius** [comment]
From the preliminary look, it seems like it's somehow related to avatar permission validation, which thinks the host isn't allowed to change an avatar (either on themselves or another user, I'll need more info to know). I'll have to look into this deeper and possibly instrument the build a bit.

Do you know what was changed with the avatar permissions in the world or if they're modified to not be standard? It's definitely a bug in Neos, it shouldn't crash like this under any circumstances, but knowing what was changed could help investigation on my end.

**Comment by ProbablePrime** [comment]
Thank you!, Some info that may help.
1. We have the ability to spawn items turned off for everyone
2. We have transferring items out turned off for everyone
3. In the user spawner we have blocked cloud avatars and defaulted everyone to use an avatar in the world (The Among Us Avatar)

**Comment by Frooxius** [comment]
I've added some extra diagnostics in 2021.4.5.911, would you be able to replicate the bug again and send me the log from that please?

**Comment by LucasRo7** [comment]
Ok, I did it again in the new version, here's the log:
[DESKTOP-P0VSIH4 - 2021.4.5.1003 - 2021-04-05 17_47_15.log](https://github.com/Neos-Metaverse/NeosPublic/files/6260638/DESKTOP-P0VSIH4.-.2021.4.5.1003.-.2021-04-05.17_47_15.log)

**Comment by Frooxius** [comment]
Thanks! Should be fixed in 2021.4.6.764 now, please give it a try and let me know if you run into any other issues!
