### ISSUE TITLE
Audio streaming panel distance space should be global by default instead of local

### ISSUE THREAD

**Issue by marsmaantje** [Neos-Metaverse/NeosPublic#1932]
## Describe the bug
The default distance space of the AudioSource on the Audio streaming panel is local by default causing the audio to be inaudible when it is spatialised.

## Relevant issues
#1924 and #1880

## To Reproduce
1. Start streaming audio
2. try to hear the sound when it is spatialised

## Expected behavior
The distance space on the audio output should be global instead of local, or the slot it is under should be propperly scaled for the audio output to be audible.

## Screenshots / Video
![20210402220456_1](https://user-images.githubusercontent.com/60362806/113450099-860eea00-93ff-11eb-94da-d51377a2bd9a.jpg)

## Bug information:
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.2.690
 - Neos Platform: Any
 - Regression: 2021.3.30.508

## Reporters:
marsmaantje#3356
Elektrospy#0645

**Comment by kaileiBubble** [comment]
same issue

How often does it happen: Always
Does the bug persist after restarting Neos? Yes

**Comment by Frooxius** [comment]
The audio space was changed the local so it scales appropriately with the object, so we don't want to change it back to global. Instead I made sure that the audio output doesn't have the canvas scale on it by moving it to the root in 2021.4.5.911, which should fix the underlying issue.
