### ISSUE TITLE
Don't release sprint speed while a directional key is held

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1933]
## Is your tweak request related to a problem? Please describe.
Sprinting is released when the key that initiated the sprint is released rather than when all directional keys have been released. E.g. if you initiate the sprint by double tapping forward (W) and start to strafe, or move backwards, sprinting is dropped until you double tap the corresponding direction you are switching to rather than maintaining the sprint state while changing direction.

## Describe what would you like tweaked
Maintain the sprint state while moving in any direction.

## Describe alternatives you've considered
An alternative key to initiate sprint, e.g. double tap of the shift key which can be held at all times even when changing direction, or a key to toggle sprinting so all movement is in the sprint speed without double-tapping.

**Comment by Frooxius** [comment]
Extended the input system to support this in 2021.4.5.911, should now behave better, thanks!
