### ISSUE TITLE
HUD does not scale properly on displays narrower displays.

### ISSUE THREAD

**Issue by CheesecakeCG** [Neos-Metaverse/NeosPublic#1935]
## Describe the bug
The sides of the menu are cut off on 5:4 and 4:3 monitors when the game is fullscreen.

## To Reproduce
Open NeosVR in desktop mode.
Resize the window so it's narrower.

## Expected behavior
The main menu should either fill the screen responsively or scale to always show all of it contents. Fitting the width on narrower monitors, fitting the height on wider monitors.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/32441086/113459892-f0666100-93e4-11eb-9060-47942fce4257.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.2.690
 - Neos Platform: Any (only tested on Linux)
 - Regression: Yes (in the old desktop mode)

## Reporters:
hare_ware#4880

**Comment by Frooxius** [comment]
Fixed in 2021.4.5.911, thanks!
