### ISSUE TITLE
Sprinting FOV speed tweak

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1937]
## Is your tweak request related to a problem? Please describe.
This is more of a qualitative/feel issue, but the FOV expansion while sprinting feels slightly disorientating.

In comparison to other implementations such as in Borderlands 2, the transition in FOV is much too slow/sluggish.

This has the result of feeling like you are still moving after you have stopped as the camera zooms back in, making it appear you are getting closer to objects in front of you.

## Describe what would you like tweaked
Drastically shorten the time to modify the FOV while sprinting to somewhere around 100-150ms from the approximately 400ms or so it currently takes in Neos.

## Additional context
From looking at some 60 FPS footage of both Neos and Borderlands 2, it appears Neos takes somewhere around 26 frames (at 60 FPS) ~400+ms to fully transition between the walking and sprinting FOV.

In Borderlands 2, this is considerably snappier at around 9 frames ~150ms to fully transition between the walking and sprinting FOV.

Neos: 

https://user-images.githubusercontent.com/54213390/113463329-0a4e7680-93da-11eb-8e03-850782de4247.mp4

Borderlands 2:

https://user-images.githubusercontent.com/54213390/113463349-1fc3a080-93da-11eb-9fcc-6ed23ef13313.mp4

**Comment by Frooxius** [comment]
This is a bit antithetical to how the FOV adjustment actually works. It's not based on time, but on the current movement input. The FOV change is proportional to how much the movement speed is above the default (1). I'll see what I can do, but this is a bit tricky.

**Comment by Frooxius** [comment]
I found the issue, I put really low smoothing on it, should be better in 2021.4.5.911, thanks!
