### ISSUE TITLE
Show timezone in DateTime Display node

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#1938]
## Is your tweak request related to a problem? Please describe.
There is no way to know what timezone the DateTime is currently stored in apart from converting it to UTC/Local/Unixtime/etc. and comparing the values. So, "01/01/1970 00:00:00" could mean my local midnight, UTC midnight, or even US West midnight.

## Describe what would you like tweaked
Show the timezone offset in the DateTime Display node and in other places where it would be beneficial (inspector on DateTime value, etc.). E.g. something like "01/01/1970 00:00:00 UTC+3".

## Describe alternatives you've considered
Not showing the offset and causing confusion and frustration.

## Additional context
That actually might help to understand the cause #1364 better.
And avoid stumbling on something like this (photo by Banane9#5929):
![image](https://user-images.githubusercontent.com/675104/113465438-a4dfa180-943c-11eb-97d9-c1246a931097.png)

**Comment by Frooxius** [comment]
I'm sorry, but this is not actually possible. DateTime contains no information about the TimeZone (other than whether it's UTC or not), so it's not possible to display the offset from it, since it's something that's external to it and up to you to manage.

You can find some more info on this here: https://stackoverflow.com/questions/576740/get-timezone-from-datetime

**Comment by shadowpanther** [comment]
Okay, maybe show if it's UTC or local then? Even that would avoid a lot of confusion.

**Comment by Frooxius** [comment]
That could be misleading as well. Problem with "Local" is that it's not necessarily "Local" to you. So it would display "Local", but the time would still be wrong. Maybe we could add "UTC" there when it's specifically that, but you'll still have to make sure you handle timezones explicitly.

**Comment by shadowpanther** [comment]
That's the reason I ask - I already encountered at least twice the situation where I couldn't distinguish the local time from GMT, one in #1364 for example. Having an explicit indicator that this here time is/isn't GMT would help debugging a lot.
