### ISSUE TITLE
Primitive mesh editing gizmo misbehaves with a DevToolTip under a tooltip multiplexer

### ISSUE THREAD

**Issue by du27y** [Neos-Metaverse/NeosPublic#1941]
## Describe the bug
The new projection mode of the DevToolTip misbehaves when editing a primitive mesh if the DevToolTip is on a tooltip multiplexer

## To Reproduce
1. Add a DevToolTip to a tooltip multiplexer
2. Equip the tooltip multiplexer
3. Set the DevToolTip to Projection mode
4. Create a new box
5. Aim laser at green dot
6. Press trigger

## Expected behavior
The projection mode works as intended

## Screenshots / Video
https://rairu.zapto.org/nextcloud/index.php/s/Yw5HCSxBd678zW4
Video by RaiRu# 1459

https://user-images.githubusercontent.com/54213390/113522241-cc755d80-9553-11eb-97c2-85a537806321.mp4

Video by Shadow Panther# 5154

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.2.690
 - Neos Platform: Any
 - Link to reproduction World/Item: neosrec:///U-ItsDusty/R-7834919f-a45d-44c5-a513-f925de70f557 
    PRISM Public\PRISM Multitool\PRISM Multitool 01-03-21 LTS
 - Regression: No

## Reporters:
Shadow Panther# 5154
ItsDusty# 0001
RaiRu# 1459

**Comment by Frooxius** [comment]
This was general problem due to multiplexer not passing the new behavior needed for the gizmos properly, it affected all gizmos. Should be fixed in 2021.4.5.911.
