### ISSUE TITLE
"Cleanup Unused Assets" forces disabled SkinnedMeshRenderer to become visible on headless

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1944]
## Describe the bug
On a headless session, "Cleanup Unused Assets" will trigger a bug when ran which causes a disabled SkinnedMeshRenderer to become visible again despite their `Enabled` field being set to disabled.

## To Reproduce
- Join a headless session
- Load an avatar directly from the inventory (favorite avatar, or lightning bolt quick equip)
- The avatar must have been previously saved with a SkinnedMeshRenderer disabled
- Let Cleanup Unused Assets run (for testing puposes, set it to a low value like 10 seconds)
- After Cleanup Unused Assets runs, the disabled SkinnedMeshRenderers will become visible

## Expected behavior
- SkinnedMeshRenderers that are disabled are not visible

## Screenshots / Video
[If applicable, add screenshots or a video to help explain your problem.]

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.2.690
 - Neos Platform: Windows
 - Regression: No

## Additional context
Some notes and discoveries made by myself and Cyro:
- It appears this issue is reliably triggered on headless
- We could not reproduce it on a newly made gridspace session he was hosting
- It appears to specifically affect avatars that are directly/quick equipped from the inventory that were saved with a SkinnedMeshRenderer disabled
- External/non-avatar objects are not affected
- Avatars that are spawned into the world will not exhibit this issue, even if held in the hand/parented under the user, or equipped through the context menu- it appears to specifically affect avatars equipped directly

## Reporters:
Kal# 9429 - Originally discovered, and reported the issue
Cyro# 5120 - Discovered the crucial replication step/relation to "Cleanup Unused Assets"/helped identify scenarios in which it does/doesn't occur

**Comment by Frooxius** [comment]
Should be fixed in 2021.4.5.911, sometimes the Enabled properly and some others wouldn't reapply. Please check if the issue still persists and reopen if so, I wasn't able to properly replicate this in my own conditions.
