### ISSUE TITLE
Add a local/UTC indicator to DateTime display node

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#1946]
## Is your tweak request related to a problem? Please describe.
We don't have a way to easily distinguish whether the DateTime value is in the local timezone or in UTC timezone.

## Describe what would you like tweaked
As a followup to #1938, I would like to request adding an indicator of DateTime value being local or UTC in the DateTime display node.

## Describe alternatives you've considered
Debug DateTime issues by using a combination of other logix nodes, like converting the value to UTC and calculating the difference.

## Additional context
#1938 was closed and the following discussion didn't lead to reopening it.

**Comment by kazu0617** [comment]
I think it can resolve with showing DatetimeKind in Display of Datetime.
![image](https://user-images.githubusercontent.com/6259214/113638988-26d90000-96b3-11eb-96c0-452fcac6ea37.png)

**Comment by ProbablePrime** [comment]
Hmm, I can do something here. On it.

**Comment by ProbablePrime** [comment]
![image](https://user-images.githubusercontent.com/8791132/124579177-bce00c00-de03-11eb-8eb8-febb659be7e2.png)

This will only display if you specify the last input as UTC. 

Local is far too confusing to rely on :)

There's also an Input/Operator that outputs the kind as I didn't want string matching to happen again. 

This is subject to review but we'll see.

**Comment by ProbablePrime** [comment]
This was released in: 2021.7.6.1154

Thank you!

**Comment by ProbablePrime** [comment]
Whoops
