### ISSUE TITLE
Expose MazeGenorator's Generate button to Logox

### ISSUE THREAD

**Issue by Kal47** [Neos-Metaverse/NeosPublic#1950]
## Is your tweak request related to a problem? Please describe.
No

## Describe what would you like tweaked
Expose the logix impulse on the interface card for the MazeGenerator component Generate button.

## Describe alternatives you've considered
At the moment I cannot think of any alternatives to have a low permissions user generate a new maze besides inspector hacking which is not very clean.

## Additional context
MazeGenerator componanat is in Generators -> MazeGenerator

**Comment by Frooxius** [comment]
Added in 2021.4.6.764!
