### ISSUE TITLE
Logix interfaces driving itself

### ISSUE THREAD

**Issue by xYreous** [Neos-Metaverse/NeosPublic#1955]
## Describe the bug
when working on logix and pulling out an interface card i noticed that it would start driving itself, and it seems to happen because realigning it using trigger also pulls the wire out from wherever my laser was pointed and upon letting go it will plug the wire into its source making it drive its own value

## Relevant issues
none

## To Reproduce
1. pull out a logix interface
2. while holding with laser click trigger to realign
3. in most cases it ends up pulling out a wire and driving itself

## Expected behavior
Before a recent update what would happen is i would realign the interface and it wouldnt try to drive itself

## Screenshots / Video
![image](https://user-images.githubusercontent.com/56841853/113638703-5264d780-962c-11eb-8cff-b5652dbad4c6.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.5.1003
 - Neos Platform: Windows
 - Link to reproduction World/Item: none
 - Regression: yes, not sure which version exactly but it worked before this i believe https://discord.com/channels/402159838827905024/469131434628612116/828653634718793758

## Additional context
none

## Reporters:
xYreous#9690

**Comment by Earthmark** [comment]
I've seen this behavior used as a way to make user independent values, where a value is self driven through a ?: node. I don't recall the exact times I've seen this, but while it makes a cycle it's a sometimes used cycle.

**Comment by 3x1t-5tyl3** [comment]
Gonna agree with @Earthmark here. I've used this plenty times myself to create self driving logix with a terniary node. It's incredibly usefull when used correctly.

**Comment by Psychpsyo** [comment]
While it is useful, it should only happen when you want it to. Clicking trigger to realign the currently held interface card to an axis shouldn't even try to interact with the interface card.

**Comment by Frooxius** [comment]
Fixed this in 2021.4.6.764, thanks!

**Comment by Hayden-da-Serg** [comment]
While this does fix aligning nodes, it also makes it impossible to work on an avatar's logix while said avatar is equipped, I personally do this all the time to quickly iterate and test, however with this change I cannot do that. Maybe instead of checking for a user it checks if it's grabbed?
