### ISSUE TITLE
Component to drive a value, based on what camera is rendering.

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#1957]
## Is your feature request related to a problem? Please describe.
Many avatars with larger heads end up looking like they're getting executed by hanging when their perspective point is too far forward and they are looking down, but those avatars often need a very far forward head position to avoid seeing the inside of their own face without a near clip.

This is often mitigatable with near clip, however many users seem to want the ability to see things close to their face, just not their own face from the inside. Some avatars would also require a very large near clip, especially avatars that deviate more from human-ish head structures.

## Relevant issues
Unsure of any, I did a pass but didn't see relevant ones.

## Describe the solution you'd like
The best case I can see, is a component that provides a different slot transform during the eye view render pass of a particular selected user. It would continue to be the normal value during camera and mirror renders, but during the head render it would be different, I've got no idea if this is possible though.

## Describe alternatives you've considered
A bool that is true only during that render pass to be routed through boolean value drivers, however I get a feeling that's even more problematic of a request as it would require multiple components to execute between different render passes (which feels non-viable based on my understanding).

A local user based scale transform, however it makes the users head collapsed in mirrors and cameras from their own perspective.

## Additional context
The ability to configure a value to be different for a given render pass would be really useful for horror maps, or having decorations attached to an avatar only viewable through lenses kind of thing.

This would remove the ability for the user to see their own nose, but I've encountered users where that causes motion sickness. So for these users their current choice is looking rather executed when looking down, not seeing anything within a foot of their face, being motion sick, or some combination of those to varying degrees (like a slight near clip, a bit less hanged-neck, and still seeing the tips of their nostrils).

**Comment by shadowpanther** [comment]
That also might be used to hide custom private UI on the avatar (wrist menu, face camera, etc.) and render it only for main game camera.

**Comment by Frooxius** [comment]
I'm sorry, but this is not technically possible. Rendering is fully decoupled from the data model, there's no concept of "render pass" like that, you can't make any modifications to the data model from rendering code at all, since it technically runs independently (and partly in parallel) to the data model updates.

I do have general plan for concept that would allow submitting per-camera/view overrides to the renderer which would allow achieving similar effects and solve the same problems in a way that's compatible with the architecture of Neos, but I need to think that one through more.
