### ISSUE TITLE
Notification sounds should use "ignore reverb zones"

### ISSUE THREAD

**Issue by StarfishHidari** [Neos-Metaverse/NeosPublic#1958]
## Is your tweak request related to a problem? Please describe.
When in a reverb zone in a world, notifications react to the reverb zone, so if the reverb zone makes things very echo-ey or bass-ey, the notification will be as well.

## Describe what would you like tweaked
Notification sounds should have "ignore reverb zones" set

## Describe alternatives you've considered
Cant think of any alternatives

**Comment by Frooxius** [comment]
Changed in 2021.4.14.1059, thanks for the report!

**Comment by Ruikio** [comment]
It looks like this is no longer completed as Notifications still seem affected by reverb zone. Also to add on, muting/unmuting is being picked up with reverb. As well as Broadcast mode (I think there is a way in game to stop broadcast from being affected though.)

Anything UI should 100% not be picked up by reverb.
