### ISSUE TITLE
Bug/Regression: Scaling with Widget allows pull but not push in VR.

### ISSUE THREAD

**Issue by DeliriousJax** [Neos-Metaverse/NeosPublic#1965]
## Describe the bug
While attempting to scale an object using the in world scaling widget via dev tooltip, it seems we can scale up by moving the center point away, but there is no way to push the scale down by pushing in.

## To Reproduce
Simply try to scale an object up or down in world using the widget.

## Expected behavior
Ability to scale objects smaller.

## Bug information (please complete the following information):
 - Always happens.
 - Persists after restart.
 - Neos Version: Tested and confirmed presence of issue as of April 5th 2021.
 - Neos Platform: Windows.
 - Regression: This use to work and is to my best guess, likely a result of input and interaction updates regarding Desktop mode.

## Reporters:
DeliriousJax

**Comment by shadowpanther** [comment]
That only happens with a new Projection mode, the old Tip mode is fine. Scaling with a projection mode makes no sense at all, as the "handle" point you start to move is right there at the centre white box.

**Comment by DeliriousJax** [comment]
Ah thanks for the mention @shadowpanther ! Looks like it just needs to detect whether the person is in desktop or vr automatically and give Jr an initial state because switching from projection mode was very unobvious. But I'll try and spread word on any further confusion to help new/unaware users as well.

**Comment by Frooxius** [comment]
I'll change the behavior so it scales up when you move along the positive axes and scales down then you go in the opposite direction in the projection mode. This is what Unity and other tools do as well.

**Comment by Frooxius** [comment]
Implemented proper scaling in 2021.4.14.1059! The global scale gizmo can now scale both up and down in desktop and VR with the projection mode!
