### ISSUE TITLE
Neos Wiki & Neos.com is down

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#1966]
## Describe the bug
https://wiki.neos.com/index.php?title=Main_Page doesn't load, and times out.
Neos.com doesn't load and times out.

## To Reproduce
Try loading the wiki or the main site.

## Reporters:
Lots of users in #wiki.

**Comment by kazu0617** [comment]
Both worked correctly in japan. A bit of downtime?

**Comment by ProbablePrime** [comment]
It appears to be a bit unstable right now, some users are seeing it up and some are seeing it down.

**Comment by shadowpanther** [comment]
Which is probably a network issue somewhere between said users and the site itself. Not much could be done with that.

**Comment by ProbablePrime** [comment]
Looks to be recovering and nothing that the Team could do. Will close later tonight.

**Comment by Aerizeon** [comment]
@ProbablePrime This seems to be a recurring issue, so perhaps we should see if there's some underlying problem causing it?

**Comment by TehTurk** [comment]
Closing following Prime's comment.
