### ISSUE TITLE
Crouch toggle behaviour in Desktop (Screen) mode

### ISSUE THREAD

**Issue by Nammi-namm** [Neos-Metaverse/NeosPublic#1970]
## Is your tweak request related to a problem? Please describe.
In Desktop mode, the C key currently needs to be double pressed to toggle crouch. I've talked with several new users I've mentored do find it unintuitive. Your view bobs heavily when engaging it, it can look 'glitchy' from a third party perspective. You dip down, then dip up, then dip down again.

## Describe what would you like tweaked
An option to have Crouch (toggle) operated by a single press, a good solution without a tickbox in settings would be if there's a single press, its a toggle. If there's a continuous press(longer than a normal keyboard press) then it works as hold. Games like Halo: Master Cheif Collection do a hybrid system like this for their zoom mechanic.

## Describe alternatives you've considered
An alternative is having this customizable in a desktop mode settings panel, or just having toggle crouch, no hold at all as an option. Another option is having double press be used for prone if prone is something Neos would benefit from/require, asides from having prone on a dedicated key. Just an idea.

**Comment by Frooxius** [comment]
Changed in 2021.4.9.1114!
