### ISSUE TITLE
Mentor Meeting Summary - Inventory and New User Quality-of-Life tweaks

### ISSUE THREAD

**Issue by dfgHiatus** [Neos-Metaverse/NeosPublic#1971]
# Mentor Meeting Summary - Inventory and New User "Quality-of-Life" tweaks

This post is a collection of ideas and requests from the NeosVR Mentor meeting that took place 4/7/2021. If this needs to be broken up into separate posts please let me know and I will see it done.

## Is your feature request related to a problem? Please describe.
1) Sometimes, a new user will accidentally delete the "Neos Essentials" or "Essential Tools" not knowing what they do. Likewise, no description is given about the items in these folders aside from their name.
2) When joining a new user in the MTC, some users are surprised or even frightened when another user joins them. 
3) New users are often unaware of Neos Mentors and their role in the community

### Make "Neos Essentials" and"Essential Tools" un-deletable
1) A proposed solution would be to make "Neos Essentials" and"Essential Tools" un-deletable. While this may pose an issue for users who like to organize their inventory, this may be a suitable option once inventory management is more implemented. 

### Add Descriptors for Items on Hover
1) (cont.) Likewise, a simple solution for item descriptions would be to add an item descriptor in the inventory - Something that appears when a user hovers over an item after 2 seconds for instance.

### Add a distinct join notification for MTC worlds
2) Adding a join notification message and/or sound would aid this issue. 

### Add a "Summon Mentor Button" to MTC worlds (with categories)
2) (cont.) Similarly, adding a "Summon Mentor Button" to MTC's would better enable new users to get help and setup. Additionally, having categories would help specify what the user would need help with (full body calibration, avatar importing, etc.).

### Describe the mentor role more to new Users
3) The mentor role could be described in places like the MTC, Steam Page, Wiki, etc. Some of these places already have descriptions such as the MTC.

Likewise, certain "Days" could be hosted:
- Resource day: No time set. A meetup to contribute any tutorials and resources for new users to use to add to "The Starter Pack" folder. objects will be sorted and added if/when needed
- Mentor Workshops: days where mentors can come and learn from other mentors in a low pressure environment to hone their skills in understanding NeosVR in its totality.
- Mentor Help Days: Dedicated days where mentors meet up and hang out in a named world, encourage users to come to these if they don't feel okay getting 1 on 1 help from a mentor.

## Relevant issues and Alternatives considered
Relevant issues and Alternatives were discussed during the meeting. I will provide additional context if necessary.

## Additional context
N/A

**Comment by TehTurk** [comment]
Heyo! So there was a miscommunication when I said folks should throw some of the ideas from the mentor meeting at the github, I'm gonna go through this and have them be individual issues so it's more focused and considerations for the future are there :)

**Comment by 3x1t-5tyl3** [comment]
I was about to comment on this.. ;_;

**Comment by TehTurk** [comment]
Sorry! DFG made an oopsie and I'm fixing this by splitting up the issues. I encouraged the issues brought up to be made into issues and it was misunderstood to just summerize them all when this kinda doesn't really help as you want the issues to be seperate and trackable.
