### ISSUE TITLE
Saving a folder with an invalid Folder Record will make the folder non-deletable.

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#1973]
## Describe the bug
A folder link with the name "Essential Tools" when given a wrong record URL for example a youtube link will not be deletable.

## Relevant issues
-

## To Reproduce
1. Spawn any folder with the "letter" icon.
![grafik](https://user-images.githubusercontent.com/61988002/113926788-ec737e00-97ec-11eb-84c4-932046640962.png)
2. Change the URL of the folder to a non-neosrec.
3. Save folder
4. Reload inventory
5. Delete folder
6. Reload inventory
7. The folder re-appears and cloggs up space for no reason.

## Expected behavior
Delete should be delete.

## Screenshots / Video
![grafik](https://user-images.githubusercontent.com/61988002/113926908-1331b480-97ed-11eb-8ea6-09e122e75585.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.6.931 though it existed for atleast 4 months.
 - Neos Platform: Any
 - Link to reproduction World/Item: See above
 - Regression: No

## Additional context
I would really like to be able to delete these folders as they take up space for no reason.

## Reporters:
3x1t_5tyl3#0001
Though I know of a few users who have the same issue, namely I know jeana has atleast 6 copies herself in her folder.

**Comment by Frooxius** [comment]
Fixed in 2021.4.9.1114, you should be able to delete them now!
