### ISSUE TITLE
UIX: When Inventory is reworked Default Folders should be protected from deletion

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#1974]
## Is your tweak request related to a problem? Please describe.

New Users will often sometimes accidentally delete folders, this will be a problem as it cuts off their access unless they meet another user. 

## Describe what would you like tweaked
Folder Protection to some degree to prevent user error

-originally by dfghiatus

**Comment by Frooxius** [comment]
The rework of the UI will get rid of the inventory folders, they are just a hold-over before we have a proper system for distributing the common tools and items. I don't think it's worth the development time implementing this for the old one.

**Comment by TehTurk** [comment]
Uh Froox, this is an issue to write down and mark for the future not for right now as a consideration for a problem we have right now. 

So you can be aware and consider this issue for the future when designing the system. Going to reopen this and remove the tag. If you have another idea feel free, it's just right now there's no good way for users to throw suggestions or considerations for upcoming design work.

**Comment by Frooxius** [comment]
I think you misunderstood. The goal is to get rid of using default inventory folders completely, they will be replaced by the workshop and facets. We won't need folder protection in the future, because we won't have folders to protect.

**Comment by TehTurk** [comment]
Hmm I see. I do kinda wish there was an easier way to see what ideas are considered for the future with some upcoming reworks or feature upgrades. By that answer most folders would mainly become shared not a focus of the main inventory.
