### ISSUE TITLE
Control+Z undo action shouldn't toggle walk speed

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1979]
## Is your tweak request related to a problem? Please describe.
While undoing actions with control + z in the desktop mode, the walk speed toggle (Z) activates.

## Describe what would you like tweaked
Suppress the walk speed toggle while performing key combination actions.

## Describe alternatives you've considered
The walk toggle could potentially be moved elsewhere, but this isn't a preferable solution.

**Comment by FlameSoulis** [comment]
Can confirm that Ctrl+Z does result in walk speed being changed, while still properly undoing the actions performed.

**Comment by Frooxius** [comment]
The Undo/Redo haven't been moved to the new input binding system yet, so it wasn't checking for collisions. Now they're part of the new input binding in 2021.4.9.1114, which should fix this problem!
