### ISSUE TITLE
Some Child items have priority when saving it's Parent

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#1984]
## Describe the bug
When you're saving an item that you're holding, it'll save it's attached child instead.

## Relevant issues
Couldn't find any.

## To Reproduce
1. Have an object with a Grabber & a collider. In my case was a UIX canvas with information.
2. Parent an object like a public folder onto it, mine had a grab instancer
3. Save what you're holding
4. Check your inventory and see that it saved the attached public folder instead of what you were actually holding

## Expected behavior
It should save the item you're actually holding, and everything attached to it, without prioritizing stuff like public folders and saving that instead

## Screenshots / Video
[If applicable, add screenshots or a video to help explain your problem.]

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Beta 2021.4.9.1119
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: Never tried this before.

## Additional context
Parenting the public folder anywhere else on the canvas doesn't seem to affect how it's saved. It prioritizes the folder regardless of it's position in the Hierarchy 

## Reporters:
AshtonSparx#5050

**Comment by shiftyscales** [comment]
Does this behavior also occur if you grip the reference to the slot in the inspector instead of physically holding the item, @AshtonSparx?

**Comment by AshtonSparx** [comment]
Saving the item through the inspector seems to save the whole object properly, but saving while holding, regardless if I use the context menu or with the Green + only saves the public folder that's attached.

**Comment by TehTurk** [comment]
I've been aware of this bug for quite sometime, it's been a bit of a silly one so never thought to report it. Because in some situations it's let the average user not be able to save an object, that maybe you don't want folks saving due to versioning of tools or otherwise. So I can confirm it happens often.

**Comment by AshtonSparx** [comment]
Neos version 2021.5.17.909 fixes this issue
