### ISSUE TITLE
CPU Spikes cause Precedually generated meshes (Such as UIX) to stop updating

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#1985]
## Describe the bug
When the CPU is under heavy load or has sharp spikes, everything related to UIX or procedural meshes like AudioWaveForm will stop updating. This stretches from Context menu, Dashboard, Laser, ect. The colliders will still summon when opening but interaction stops working and visuals don't appear. It's rather inconsistent and happens randomly when under load (I could be in my world and get red bar CPU spikes in FPSVR application and this problem presents)

## Relevant issues
N/A

## To Reproduce
1. Be in a world under heavy load (Happens more often when my CPU Usage with a Ryzen 7 2700x gets 50-100+ms frame time)
2. Wait awhile, and suddenly you can't open context menu, dashboard UI stops updating, ect.

## Expected behavior
Under heavy CPU load, UIX should always be reliable. If you need to leave the world, join someone else, ect, you can't because nothing is responding.

## Screenshots / Video
May supply one soon if it happens

## Bug information (please complete the following information):
 - How often does it happen: Sometimes
 - Does the bug persist after restarting Neos? No, until CPU get's hammered again
 - Neos Version: 2021.4.9.1119
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: This has happened for quite a while, it wasn't always like this but within the past month or 2 is when I noticed it happening more. Especially since i started attending crowded worlds for events.

## Additional context
When I manage to switch to my homeworld (or even local home that's basically empty) the problem is still persistent and i have to basically wait it out to fix itself or restart Neos.

## Reporters:
AshtonSparx#5050

**Comment by Frooxius** [comment]
This is a bit tricky, because if your system is heavily overloaded like that, it's not technically a "bug", it's just a symptom of your system having too much to do. The systems for procedural meshes, UIX and other bits are heavily multithreaded for performance.   The UI specifically even runs on high priority to take precedence over other tasks where possible, but if the system gets overloaded this degrades.

There isn't too much that can be done specifically for this, other than doing some more balancing and general optimizations around the system. We could force the system to be single threaded and synchronous with a lot of work, but that would make the problem even worse, meaning you'd just freeze completely before it updates.

We'll be doing more optimizations over time and balancing which should improve this behavior, but I'm not quite sure what to do about this specific issue. Having system under heavy load and expecting things to stay responsive isn't really feasible expectation. If the system is overloaded, it's overloaded, best we can do is prevent it from getting to that point

Understanding what causes heavy load on your system would help - what do the background jobs looks like? What's your CPU/core utilization when this happens? Things like that.

**Comment by AshtonSparx** [comment]
When this happens and such, I can take some screenshots of what's going on with the system of task manager, so you can better understand what's happening, and possibly help prevent or lower the chances of it getting to that point, like you mentioned <3

**Comment by Frooxius** [comment]
It might help a bit, though usually I'd need a lot more in depth information that Task Manager doesn't provide. When this happens again, could you make sure Neos window is focused and mash the F9 key for a while? That will print out a snapshot of background tasks to the log file, which can give more info about what's currently overloading the background processing.

**Comment by AshtonSparx** [comment]
Good afternoon (Or morning) @Frooxius - had the issue again, here's my logs you've requested, I wasn't able to close the game properly but I mashed the F9 key while nothing was rendering. When attempting to close the game so I can grab the logs, it stopped responding. I waited a bit, it still wouldn't respond so I had to end it's task.

Requested Log
[DESKTOP-SPEUN1P - 2021.4.9.1119 - 2021-04-11 14_42_06.log](https://github.com/Neos-Metaverse/NeosPublic/files/6292994/DESKTOP-SPEUN1P.-.2021.4.9.1119.-.2021-04-11.14_42_06.log)
:

**Comment by AshtonSparx** [comment]
[DESKTOP-SPEUN1P - 2021.4.14.1059 - 2021-04-14 19_48_05.log](https://github.com/Neos-Metaverse/NeosPublic/files/6314899/DESKTOP-SPEUN1P.-.2021.4.14.1059.-.2021-04-14.19_48_05.log)
Here's another full log of it happening, Seems line 3738 exceptions were being thrown like crazy which could be causing the issue.
Looking at the other log, around the same exception is happening too when UI randomly stops working

**Comment by AshtonSparx** [comment]
[DESKTOP-SPEUN1P - 2021.4.14.1059 - 2021-04-16 11_24_02.log](https://github.com/Neos-Metaverse/NeosPublic/files/6327215/DESKTOP-SPEUN1P.-.2021.4.14.1059.-.2021-04-16.11_24_02.log)
A Third one just in case...

**Comment by AshtonSparx** [comment]
[DESKTOP-SPEUN1P - 2021.4.17.185 - 2021-04-18 18_22_43.log](https://github.com/Neos-Metaverse/NeosPublic/files/6332455/DESKTOP-SPEUN1P.-.2021.4.17.185.-.2021-04-18.18_22_43.log)
Line 3146 the same issue persists. I abandoned every world I was in. Still broken.

CPU Usage super low, watching FPSVR, 5ms CPU frame-time with huge random spikes every few ticks. Clicking on debug menu freezes Neos and stops responding.

**Comment by Frooxius** [comment]
It looks like there's a heavy lock contention on the local database, which is locking up the background threads as they wait on IO. I'll have to rework these bits a bit to avoid that. In the meanwhile it might help to clear the local database and make sure it's on a fast drive (e.g. SSD).

**Comment by AshtonSparx** [comment]
I have Neos & Neos Cache in an M.2 NVME SSD .. I don't know how much faster I can get .. I can clear my cache and move it off of my windows Drive and put it in my secondary M.2 NVME SSD

**Comment by Frooxius** [comment]
If you already have it on a fast drive then it should be good, I was just suggesting to put it on one if it isn't there already. Might be the size of it too. They're only mitigations, a proper fix will take a bit to rework some bits to avoid the contention from happening in the first place.

**Comment by AshtonSparx** [comment]
No worries Frooxius, thank you <3

**Comment by Frooxius** [comment]
This should now be mostly fixed in 2021.4.24.620 with rewrite of the local database system. Please let me know if you still experience issues. Sorry it took a bit!
