### ISSUE TITLE
hitting C to crouch is not reliable

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#1987]
## Is your tweak request related to a problem? Please describe.
hitting C to crouch is not reliable I hit C but my character still stands up

## Describe what would you like tweaked
hitting C to toggle crouching has too short of a delay before it becomes hold to crouch
I hit C and sometimes I do not crouch

## Describe alternatives you've considered
there is no alternative 

## Additional context
 https://cdn.discordapp.com/attachments/439422161657135106/830197409262469200/2021-04-09_17-45-33.mp4

**Comment by Frooxius** [comment]
I've increased the interval slightly in 2021.4.14.1059, hopefully this helps!
