### ISSUE TITLE
Vulkan on Windows

### ISSUE THREAD

**Issue by TheLazyHatGuy** [Neos-Metaverse/NeosPublic#1988]
I noticed that the Linux build uses Vulkan and it would be great if this was an option on Windows as in my experience Vulkan performs a lot better than OpenGL

**Comment by shiftyscales** [comment]
Last I recall, the Linux build does not use Vulkan, it uses OpenGL. There are also things currently blocking the switch to Vulkan. There is already an issue open for this topic, #312.
