### ISSUE TITLE
Dynamic Bone Chains breaks globaly, when deleting trackers off the User Root

### ISSUE THREAD

**Issue by Readun** [Neos-Metaverse/NeosPublic#1992]
## Describe the bug
Dynamic Bone Chains breaks globaly for everyone, when deleting the trackers off from the User Root.
They Disable themself for everything in the world and can't be reenabled until that User's Root itself gets deleted or respawned.

## To Reproduce
Delete the Tracker Slots on the User root (Not using the Red delete button)

## Expected behavior
Disabling the Full-Body tracker position.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes, can be reproduced.
 - Neos Version: Currently on 2021.4.6.931 but I noticed that bug already for some weeks.
 - Neos Platform: Windows
 - Regression: Yes, but not sure since when.

## Reporters:
Readun, Tekno Catron

**Comment by Frooxius** [comment]
Do you have a log file for when this happens? It's likely some exception that turns them off.

**Comment by AshtonSparx** [comment]
@Frooxius 
[DESKTOP-SPEUN1P - 2021.4.9.1119 - 2021-04-10 14_11_21.log](https://github.com/Neos-Metaverse/NeosPublic/files/6290510/DESKTOP-SPEUN1P.-.2021.4.9.1119.-.2021-04-10.14_11_21.log) here's a clean log file of it happening, spawned in the world, calibrated, deleted the trackers from my user root, dynamic bones stop working.

**Comment by Readun** [comment]
Here is mine aswell. 
It also happens with the Red delete button aswell.
[READUN-PC - 2021.4.9.1119 - 2021-04-10 21_12_01.log](https://github.com/Neos-Metaverse/NeosPublic/files/6290600/READUN-PC.-.2021.4.9.1119.-.2021-04-10.21_12_01.log)

**Comment by Frooxius** [comment]
Fixed in 2021.4.14.1059, thanks for report!
