### ISSUE TITLE
Free cursor escapes context menu bounds if cursor is moved too fast while being opened

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1993]
## Describe the bug
The free cursor can escape the bounds of the context menu if the cursor is moved too quickly while opening the context menu.

## To Reproduce
- Press the middle mouse button to open the context menu while moving the mouse fast enough to escape its bounds before its animation has finished

## Expected behavior
- The cursor is contained to the bounds of the context menu, or the context menu is auto-dismissed if the cursor is not interacting with it

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.9.1119
 - Neos Platform: Windows
 - Regression: No

## Additional context
- The context menu can be properly dismissed/interacted with if the cursor is moved back within the bounds of the context menu.

## Reporters:
Shifty# 7944

**Comment by Frooxius** [comment]
This is intentional mechanism, because the menu was getting auto-dismissed when this was happening by accident or system issues (e.g. on Linux when it wouldn't get positioned right). Moving the cursor back to the menu once it's open and out again will auto-dismiss again.
