### ISSUE TITLE
Desktop key bind change for deleting.

### ISSUE THREAD

**Issue by LewisSnow** [Neos-Metaverse/NeosPublic#1997]
## Describe what would you like tweaked
I feel CTRL-SHIFT-D is good but also inconvenient, I think it'd be best to still have the 'DEL' key function as delete alongside the new key bind.

## Describe alternatives you've considered
Either move the key bind back to 'DEL' or have both key binds function the same

## Additional context
I personally find it far faster and comfortable to use 'DEL' for deleting.

**Comment by TehTurk** [comment]
Seconded, in most cases your not going to actively use such keybinds like this, but use key macros on a mouse to access certain keybinds like this.

**Comment by ohzee00** [comment]
I can see both being very convenient, the del key is pretty intuitive but CTRL-SHIFT-D allows you to delete things without moving one of your hands off somewhere. So I agree to both binds being there, even if it is a bit redundant.

**Comment by AshtonSparx** [comment]
I forth this, I'm super used to using the DEL key for removing things, 3 button combo is a little stinky. Both options working along side each other would be perfect for both worlds.

**Comment by StarfishHidari** [comment]
I'd really like to still have del function as delete, it's intuitive and feels a lot more convenient, I don't mind ctrl+shift+d also deleting, it would just be nice to have both.

**Comment by Psychpsyo** [comment]
Adding to the 'more intuitive' comments here. Especially when teaching new users, telling them to press the delete key to delete is something that instantly makes a lot of sense and is easy to remember while Ctrl+Shift+D is more awkward to press and to remember.

**Comment by Frooxius** [comment]
Yeah I can re-add the Delete key, it's no problem for both keybinds to be active at the same time. Ctrl+Shift+D is mainly so you can do it more conveniently with the left hand without moving too far away from WASD.

**Comment by LewisSnow** [comment]
> Yeah I can re-add the Delete key, it's no problem for both keybinds to be active at the same time. Ctrl+Shift+D is mainly so you can do it more conveniently with the left hand without moving too far away from WASD.

Thanks froox!

**Comment by Frooxius** [comment]
Added Del key as alternate binding 2021.4.14.1059 again!
