### ISSUE TITLE
Desktop mode not working

### ISSUE THREAD

**Issue by win189** [Neos-Metaverse/NeosPublic#1998]
IMPORTANT: PLEASE REPLACE OR DELETE (if not relevant) ANY TEXT IN BRACKETS [Like this] AND THIS ONE AS WELL

## Describe the bug
using Oculus quest 2 in either Virtual desktop or oculus link trying to activate desktop mode Whites out the screen 

## Expected behavior
normal desktop experience

## Screenshots / Video
![image](https://user-images.githubusercontent.com/24577138/114291662-3fe90480-9a57-11eb-911b-f32495a79ec4.png)
![image](https://user-images.githubusercontent.com/24577138/114291671-4aa39980-9a57-11eb-9d1c-ebb5157f5870.png)
![image](https://user-images.githubusercontent.com/24577138/114291683-57c08880-9a57-11eb-954a-f71dcf2fb183.png)

## Log Files
[DESKTOP-Q5Q0ES2 - 2021.4.9.1119 - 2021-04-10 23_25_32.log](https://github.com/Neos-Metaverse/NeosPublic/files/6291171/DESKTOP-Q5Q0ES2.-.2021.4.9.1119.-.2021-04-10.23_25_32.log)
[Player-prev.log](https://github.com/Neos-Metaverse/NeosPublic/files/6291172/Player-prev.log)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version:  2021.4.9.1119
 - Neos Platform: Windows,
 - Link to reproduction World/Item: [Optional, but can speed up response for more complex reproduction cases]
 - Regression: [Did this work before?] Yes 

## Additional context
steps were taken With Shiftys direction
Clearing local database/being logged out works successfully  But once logged in Goes back to Whiteout multi-account tried on accounts Fuzy Sidwell  and then recleared  and tried with win189 both Yielded the same result

Bringing my account to Stock standard No Favs Only loading local home yielded same result

if you load the Mirror addon u can see your self but white boarders

## Reporters:
Fuzy Sidwell

**Comment by TehTurk** [comment]
Also recently had this from Mars https://i.imgur.com/PmMwT6O.png It seems like if it's within a Camera space it'll behave, so maybe it's similar to a UIX canvas not intializing?

**Comment by marsmaantje** [comment]
Here is the log linked to the screenshot posted by Turk
[DESKTOP-B3HHEBC - 2021.4.14.1059 - 2021-04-15 15_26_38.log](https://github.com/Neos-Metaverse/NeosPublic/files/6318410/DESKTOP-B3HHEBC.-.2021.4.14.1059.-.2021-04-15.15_26_38.log)

**Comment by marsmaantje** [comment]
Well, I discovered why the screen was complete white for me.
My desktop FOV was set to 0, causing me to only see the center pixel.

**Comment by win189** [comment]
My Desktop Fov was set To "Nan" ?Issue  is now Resolved thank you all very much.

**Comment by shiftyscales** [comment]
This issue was also a duplicate of #1981. The underlying cause was discovered to be that the input field for the desktop FOV accepts a value of 0 instead of the minimum 10 the slider is clamped to.
