### ISSUE TITLE
In the eye manager, prioritize it looking at people/things directly infront of you

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#1999]
IMPORTANT: PLEASE REPLACE OR DELETE (if not relevant) ANY TEXT IN BRACKETS [Like this] AND THIS ONE AS WELL

## Is your tweak request related to a problem? Please describe.
[A clear and concise description of what the problem is. Ex. I'm always frustrated when ...]

## Describe what would you like tweaked
[A clear and concise description of what you want to happen.]

## Describe alternatives you've considered
[A clear and concise description of any alternative solutions or features you've considered.]

## Additional context
[Add any other context or screenshots about the tweak request here.]

**Comment by ProbablePrime** [comment]
This is already supported by the EyeManager, you can adjust various weights and settings to configure what it looks at. 

Try tweaking this values: 
![image](https://user-images.githubusercontent.com/8791132/114292378-f68eba00-9a42-11eb-937a-384d6a41eed5.png)

**Comment by shiftyscales** [comment]
Additionally, there is another issue regarding tweaking the default eye manager values. #1597.

I'd suggest if you have any specific suggestions you wish to make after experimenting with the values, you post them there. Closing this issue as a duplicate.
