### ISSUE TITLE
DestroyWithoutChildren does not respect DestroyRoot

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2001]
## Is your tweak request related to a problem? Please describe.
A slot with a DestroyWithoutChildren component which is parented underneath a slot with a DestroyRoot component is only deleting itself, not the DestroyRoot.

## Describe what would you like tweaked
DestroyWithoutChildren should delete its DestroyRoot if it can find one.

## Describe alternatives you've considered
Having a toggle or another component which does this or doing it from logix.

**Comment by 3x1t-5tyl3** [comment]
Probably related issue: #1461
