### ISSUE TITLE
Voice Light Intensity for updated Head and Hands Default Avatar too high

### ISSUE THREAD

**Issue by MR-Alex42** [Neos-Metaverse/NeosPublic#2002]
IMPORTANT: PLEASE REPLACE OR DELETE (if not relevant) ANY TEXT IN BRACKETS [Like this] AND THIS ONE AS WELL

## Describe the bug
The new head and hands default avatar shows a very intense light for voice visualization.
This is very annoying, especially when multiple people are talking.
Also and each light source lowers the performance

## Relevant issues
See bug description.

## To Reproduce
Just spawn a user with the new default avatar and start talking.

## Expected behavior
Much lower intensity and ability to switch off the voice light or exchange it with an emissive texture on the HMD avatar.

## Screenshots / Video
Non needed.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: All versions after the avatar update.
 - Neos Platform: Windows, not tested on other platforms.
 - Link to reproduction World/Item: None.
 - Regression: [Did this work before? Yes with the old avatars.

## Additional context
None.

## Reporters:
MR-Alex

**Comment by TehTurk** [comment]
From what I'm aware Ryuvi tweaked day of when this issue was made, please let us know if this is still occuring.
