### ISSUE TITLE
Changing audio output device to a high (96000 Hz) sample rate crashes Neos

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2004]
## Describe the bug
Changing the audio output device in Neos has been reported by numerous users to cause crashing. Previously I was unable to replicate this on my end, but I've found I am able to now.

## To Reproduce
- Select audio output device
- Change from "Use System Default" in my case my Yeti headphones at 16 bit, 48000 Hz to my Vive Pro earphones at 24 bit, 96000 Hz.
- The Unity crash dialog pops open, and Neos locks up

## Expected behavior
The audio device switches the device (and bit depth/sample rate) accordingly.

## Screenshots / Video
[If applicable, add screenshots or a video to help explain your problem.]

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.9.1119
 - Neos Platform: Windows
 - Regression: No

## Additional context
[SHIFTYWINDOWS - 2021.4.9.1119 - 2021-04-12 09_26_23.log](https://github.com/Neos-Metaverse/NeosPublic/files/6298325/SHIFTYWINDOWS.-.2021.4.9.1119.-.2021-04-12.09_26_23.log)
[error.log](https://github.com/Neos-Metaverse/NeosPublic/files/6298328/error.log)
[Player.log](https://github.com/Neos-Metaverse/NeosPublic/files/6298330/Player.log)

- It appears the issue is dependent on a change in sample rate specifically
- - I crash if my Vive Pro speakers are set to 24 bit, 96000 Hz, but also if I set it to 16 bit, 96000 Hz.
- - If I set them to 16 bit, 48000 Hz prior to launching Neos the crash does not occur, and the crash also does not occur if they are set to 24 bit, 48000 Hz.
- - It also appears it is specifically 96000 Hz that is causing the issue, and not just any arbitrary increase in sample rate. Setting my Yeti speakers to 16 bit, 44100 Hz, and the Vive Pro speakers to either 16 bit, 48000 Hz, or 24 bit, 48000 Hz and the issue does not occur.
- If I launch Neos with the Vive Pro speakers as the default output device, it is fine, but if I still then click on them in the audio output device menu, Neos will also crash
- The issue also occurs in both screen mode, and VR if the aforementioned condition of switching from a default device of 48000 Hz to one with 96000 Hz is met
- It's possible it might occur under other conditions/might be device specific in some form when Rabbuttz had initially reported the issue to me, they were selecting a device set to 16 bit, 44100Hz - but since the switch to my Vive Pro Eye, I am now able to reliably replicate this issue with the aforementioned conditions

## Reporters:
Shifty# 7944, Cyro# 5120, Tatsu Kimiero# 3109, Hayden# 3180, httmj# 3473, Rabbuttz（あむ）# 9966, Alex Thorin# 9381

**Comment by Banane9** [comment]
Found a Unity Editor Issue that might be related (editor crashes when changing system sample rate)

https://issuetracker.unity3d.com/issues/audio-editor-crashes-on-changing-system-sample-rate-when-audio-track-preview-is-being-played-in-timeline-window

**Comment by Frooxius** [comment]
Fixed in 2021.4.17.185, thanks!
