### ISSUE TITLE
"IgnoreRaycasts" on floor colliders prevents initialization of locomotion

### ISSUE THREAD

**Issue by IanCorvid** [Neos-Metaverse/NeosPublic#2008]
## Describe the bug
When loading a world in which the 'floor' colliders have "IgnoreRaycasts" toggled on, players will find themselves unable to move for a lengthy amount of time in any locomotion type other than Noclip or Teleport, the latter of which functions normally if given a raycast-able surface to target.

For Desktop mode, WASD and Space cease to function for motion, Mouse-based rotation and C button crouching still function. After approximately five minutes locomotion will finally take effect and the player can move normally under any locomotion.
For VR Mode, Shifty has confirmed the bug persists there as well.

## To Reproduce
1) Create a new world or open an existing one.
2) Turn "IgnoreRaycasts" ON for any existing colliders beneath the player, leaving no raycastable material between the player and the bottom of the world.
3) Save the world, close it, and reopen it.
4) Attempt to move

## Expected behavior
I would presume that Raycasting has no effect on locomotion initialization. 

## Bug information (please complete the following information):
-Happens always, easily reproduced
-Event persists for approximately 5min before it it somehow auto-corrected and the player is able to move normally. If the player has moved using Noclip and then returned to any gravity based locomotion they will fall as is normal
-Neos Beta 2021.4.9.1119
-Reproduction world provided by Shifty: http://cloudx.azurewebsites.net/open/world/U-Shifty/R-454af0b8-315c-4390-ac2c-0f58328d3ce4

## Reporters:
Shifty#7944 - Provided additional testing and proof of bug's effect in VR mode.

**Comment by Electronus** [comment]
Would love some clarification on this, I seem to recall this is intended, and done to ensure the floor collider is loaded to prevent players form falling through the unloaded floor.

**Comment by shiftyscales** [comment]
@Electronus - I believe that is what the InitializationColliderRoot slot on PhysicalLocomotion is for, but in my testing, even setting the ground collider's slot on that field didn't prevent the issue from occurring.

**Comment by Banane9** [comment]
@Electronus interesting, because I've seen some people (with FBT) fall through the floor when spawning, even on an almost empty grid space world

**Comment by shadowpanther** [comment]
@Banane9 that's what happens if you keep spawn position to default Feet instead of proper GroundProjectedHead. This should be set as a default already!

**Comment by Frooxius** [comment]
This is intentional, ray-casting is necessary to initialize the locomotion, because it uses it to check when the collider below the user has been loaded, so they don't start falling through the world on startup.

Generally I'd **strongly** advise against disabling Raycasts for locomotion colliders, they're used for more than just this, there's variety of different checks and some modules (e.g. Teleport also relies on raycasts).

If you really need to, you can configure MinInitializationDelay and MaxInitializationDelay properties on the PhysicalLocomotion to skip the initialization check, but again to reiterate, I **strongly advise** against going this route, it's not how the system is designed and you'll break a lot more things than this anyways and cause accessibility issues.

**Comment by Banane9** [comment]
> 
> 
> @Banane9 that's what happens if you keep spawn position to default Feet instead of proper GroundProjectedHead. This should be set as a default already!

Well evidently it wasn't, or something else was ducking it up, as it was a brand new template world 😅

**Comment by shadowpanther** [comment]
> > @Banane9 that's what happens if you keep spawn position to default Feet instead of proper GroundProjectedHead. This should be set as a default already!
> 
> Well evidently it wasn't, or something else was ducking it up, as it was a brand new template world 😅

What I meant, the request to change the default already exists (#1342), and it seems like a simple change, yet it still isn't changed.

**Comment by Banane9** [comment]
> 
> 
> > > @Banane9 that's what happens if you keep spawn position to default Feet instead of proper GroundProjectedHead. This should be set as a default already!
> > 
> > 
> > Well evidently it wasn't, or something else was ducking it up, as it was a brand new template world 😅
> 
> What I meant, the request to change the default already exists (#1342), and it seems like a simple change, yet it still isn't changed.

Ahhhh, I see! Upvoted that :D
