### ISSUE TITLE
New user "Baby Mode" - Locked down avatar interactions to maintain presence of self

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2010]
My guess is this is going to be bucketed with the hard permission system, I figure this can be considered a request for this feature out of that system.

## Is your feature request related to a problem? Please describe.
I've received direct feedback from a user that it is very disconcerting to have their avatar resized or grabbed without their consent, for this particular user they brought up that they experienced a large amount of unease (and said they almost did not return) when one of their first experiences was users mutating their avatar without their express permission.
They eventually returned due to a request of a friend.

## Relevant issues
#289 #1228

## Describe the solution you'd like
Something that is added to a new user on start that prevents tools and such from modifying that avatar in these ways (and probably more):
 * Changing the scale of a user
 * Parenting an object to a user
 * Changing a users scale
 * Force-anchoring a user

The user in particular requested this using the term "Baby mode", where it's almost like an extended tutorial mode where they opt-out of that mode when they have their legs, but until then they have safety systems to prevent new user overload and discomfort.

Similarly they requested a form of preventing users from getting too close, I described to be similar to VRChat's "Safe mode" where it doesn't render avatars too close to the user. However, I think this is somewhat out of the scope of this feature request as this is only about mutations to the users own avatar, not affects to external users avatars. (although considering it as well would be appreciated!)

## Describe alternatives you've considered
Keep this a social issue - This does address the root problem, however I think we've been lucky that most of the use of the funky tools isn't malicious (at least that we know of, which is survivor bias).
However I know some users enjoy these kind of toys where as others find it very discomforting. I figure the request can stand in as a hard no signal, that a user can opt out of when the user is aware of what they're getting themselves into. 

## Additional context
I think even veteran players may re-enter this mode at times if they don't want to be toyed with, depending on the mode's features.

This request may have the negative side effect of not being in this mode being grounds for consent, but I think if this is considered a training wheels thing culturally that concern may be mitigated.

It probably shouldn't be called baby mode, but it's the terms the user used, and it's easier to remember and reference in discussions.

**Comment by Frooxius** [comment]
This is a bit tricky one, there's some problems with this that might not make it viable:

- There are lots of different ways to mess with the user than even outlined if you have the proper permissions to do so in the session. We won't ever be able to account or protect against them all in a general way. We can add protections to some common things, but people will always find some other ways if they want to when they're builders.
- You can't differentiate legitimate in-world interactions from the ones that cause distress on a technical level. Take parenting objects to user, changing their scale or anchoring them. These can be proper functional parts of a game world for example or some interactive experience and having this mode on would completely break those experiences.

I think the better way to go around this might be the permission system and having users visit more locked down sessions. Perhaps in those we could have a template that disallows those things by default. If the user goes to a game world or something that needs those, then those would be enabled. When new user starts we could nudge them to those safer sessions. Having a more visible panic button that the user is familiarized with in the intro tutorials could probably help too.

It would also be with self moderation tools. Being able to block, kick or report the offending person. This goes back to this being a social problem, there will be lots of ways to harass an user too, so if we teach them early how to use those tools, that might make them more comfortable.

**Comment by Zyzyl** [comment]
I feel the trade-off here is very similar to the question of who gets final say on which post-processing options are enabled, world creators or end users. A toggle / set of settings to determine the extent to which others could interact with a user's avatar would be very nice, but I completely see how that could be gamebreaking in various contexts. 

If the general solution to this is to make full use of the permissions system, would it be possible to better expose certain session permission settings to people before they join worlds e.g. in the world browser? Hard to do in a neat way, but it might be reassuring to know that 'Builder' permissions were unavailable to anyone in a session or item spawning was disabled for all roles etc.

**Comment by Frooxius** [comment]
This is a fair bit harder than post processing, because this more often than not could result in complete functional breakage. E.g. consider even basic things, like environment navigation. Say you step into an elevator that anchors/parents you as it moves. If the user had this disabled, they'd just get bounced around horribly or fall through the map.

You can't really make much of a distinction between what's the "others" and what's the "environment", because somebody can just put an item into the environment that does the undesired interaction.

The best way to handle that with permission system would be to either prevent other users from bringing in any components/LogiX that can affect the user this way or marking it as "untrusted", unless it was marked to be as part of the world (in a way that you can't easily spoof). It'll still depend on the world you're visiting though, if you go into a sessions where the host has full control, you'll still run into trouble, at which point it'll be best to leave and find another world that's more neutral grounds.

**Comment by ProbablePrime** [comment]
Can we please not call users "Babies" or refer to them in anyway like that? 

I feel the larger permission changes are what's needed here, which is what Earthmark you were afraid of. The issues presented here are largely cultural and I'd hate to prevent users who are looking for Neos' freedom when they join only to find themselves locked.

I've noticed a trend which started in Neos Essentials but is growing(my folder will be subject to it soon), of removing shrink rays, kockback guns and even Loud noise generators from public folders and placing them elsewhere(private public folders worlds etc). 

This does only move the problem elsewhere but it is helping slightly. It won't prevent a well informed user from finding the stuff though.

On my first few days of VRChat I ran around as public avatars desperately waiting to rank up so I could upload my content that I worked hard on. Lets please try not to make Neos have this waiting period.

**Comment by SnooperXP** [comment]
I’m assuming an approach like the Windows User Account Control dialogues could be a better compromise? Allowing the user to give informed consent when an action is occurring, or a world is requesting to allow certain controls to allow it to run?

I’m unsure if that’s a bit too much in terms of implementation of scope; but would something of that direction be a feasible approach?

**Comment by Frooxius** [comment]
Yeah it definitely doesn't fix the problem, it'll probably get worse with the Workshop/Marketplace where things will be searchable (although we can also do some moderation there to push the more disruptive items lower).

I definitely don't want to add a waiting period to Neos. Everything will come to the choice for the user. If they want more protections enabled on their account, they can, if they want to take them off, they'll be able to as well. Same with hosts, if they want to lock down their sessions, they have that choice for worlds they host.

E.g. if you want to make a crazy session and toy with everything, you can start it up right after joining Neos. But it'll be up to others if they join you or not.

**Comment by Frooxius** [comment]
@SnooperXP That's unfortunately not feasible for when the actions are already running. These actions are too low level and don't have a wait to "wait". It's like asking for user permission for some random part in the middle of a complex operation. E.g. with the Windows analogy it'd be like asking the user if the currently running thread has permission to switch context back to kernel. 

The user would need to be warned before they join the world. I think the approach with either filtering out or marking as "untrusted" for the unwanted components will work best for this. For stuff that's part of the world it needs to work immediately, there's no space to wait for user's permission when it's already running.

**Comment by Earthmark** [comment]
This reminds me of fine grained permissions systems that interfaces like wasi and projects like Fuchsia are moving towards.

Perhaps an item can be categorized as different things based on the apis it uses? For instance to spawn an object that contains an anchor user logix node, the world must allow use of that permission. An object can be categorized based on the superset of the features it contains. It could be a disallowed feature just doesn't work unless allowed, that would allow feature fallbacks.
(For instance an auto anchor could still be spawned, but could only act as a user clicked anchor if the auto anchor permission isn't allowed).

Similarly a world could declare that it contains those kinds of features. I think they can often get a bit verbose, so that may be going too far in the other direction than it is now, but something to at least think about.


Baby mode was the descriptor used by the particular user.  They felt they didn't have enough time to group into the ecosystem before putting them into experiences that were overloading.

The primary experiences being:
* Avatar importing, which they considered should be simple and to them was considered feature that a new user would need to do. I see that as hopefully getting mitigated by the marketplace when it comes around.
* User show and tell, when the showing involves modifying the users own body. That is the purpose of this feature request, give a new user a point where they can opt into advanced features that could possibly result in discomfort.
* They felt there was a large number of menus that were felt confusing to the user. I'm unsure if they have joined since the new tutorial experience, so this may be resolved. But either way this is not covered by this feature request.

**Comment by uyjulian** [comment]
Would it be possible to have both a userspace avatar and worldspace avatar? The worldspace avatar would normally be synced with the userspace avatar, and the userspace avatar can only be controlled by movement or locomotion module. If the worldspace avatar gets out of sync with the userspace avatar, it would be resynced when the locomotion module is used again

**Comment by Bellimora** [comment]
One thing I get the general impression of in neos permissions system as it stands is if you give someone an inch of perms you give them a mile.  If I disable rezzing entirely I can keep things clean, but then nobody can do silly without asking for a permissions elevation.

As someone who moderates a couple scenes I'd rather much like the ability to allow people to rez stuff and use the inspector but have it limited to a personal slot hierarchy for each user and their stuff limited as such too.  Limit their inspectors to that slot-space too.  Call it non-builder rezzing or something.  And I don't know maybe if you're feeling saucy make it so friends' personal hierarchy's may interact.

That way my build continues to act as normal since it exists outside of any personal hierarchy.  

Heaps of griefy mess can be easily deleted since it's forcefully sequestered inside a personal hierarchy slot tree from which it cannot escape (bonus points if such trees collapse out of existence on logout since these are non-builders we are talking about.)

And some random twerp wanting to bully a random new user by resizing them and throwing them over the horizon cannot do so, unless I happened to have elevated that random twerp's permissions to a level where they can build/interact outside of their personal hierarchy.

And we don't introduce a heap of messy prompts to the equation.

But I might be digressing from the topic too much here...

**Comment by Frooxius** [comment]
That is pretty much what I was outlining above - the hard permission system would allow for more fine grained control - you'd disallow people with certain roles from bringing certain types of components (including LogiX) into the world. E.g. preventing anything that does parenting (or restricting what can be parented), anchoring, applying physics forces and so on. 

We a topic for that over here: https://github.com/Neos-Metaverse/NeosPublic/issues/289

**Comment by Earthmark** [comment]
Sounds like this is to be resolved in hard permissions!
