### ISSUE TITLE
Dynamic Variables don't work for a few frames after being duplicated.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2012]
## Describe the bug
When duplicating a slot with a dynamic variable on it, the variable isn't usable for a few frames.

## Relevant issues
I couldn't find any.

## To Reproduce
1. Create a slot and add a dynamic variable and space to it.
2. Make a Logix setup that duplicates the slot and tries to read the dynamic variable on the duplicate within the same pulse.
3. It wont be able to read it.

## Expected behavior
The variable's value should get read as usual since the component exists on the duplicated slot.

## Bug information (please complete the following information):
 - How often does it happen: Always.
 - Does the bug persist after restarting Neos? Yes.
 - Neos Version: 2021.4.9.1119
 - Neos Platform: Probably any, tested on Windows.
 - Regression: No.

## Reporters:
Cameron#7818 (though a bunch of people have run into this issue in the past.)

**Comment by Frooxius** [comment]
This seems a bit strange, there's not really any mechanism that would delay them being initialized for several frames. Right after duplication seems plausible, but several frames is really odd. How many does it take for them to initialize? Is the number consistent? Do you have a replication item/world for that?

**Comment by H3BO3** [comment]
I've seen this too, though in my case it was creating variables on a newly duplicated space. I had to delay execution on it by a number of updates in order to get it to work properly. I'll run some tests later.

**Comment by ukilop** [comment]
Ok this I actually have some experience on, afaik dynamic _variables_ don't need time to setup, they can be duplicated, moved spaces, and written to all in 1 frame.
Dynamic _Spaces_ on the other hand, need 3 frames to setup.
My usual run-in with that is duplicated a space with variables already on it, (same slot).
It always needs exactly 3 frames to 'initialize'. my usual workaround if I don't want to wait, is to write to the variables of the template before duplicating but that's not always an option.

**Comment by Zyzyl** [comment]
I've made a reprex here neosrec:///U-Zyzyl/R-8e073b29-2f22-4dac-8bbb-6200bb52cfaa

There are 2 examples showing the requirement for a delay before anything can be read from / written to a DynamicVariableSpace after it's created / loaded.
1) Some LogiX triggered by an OnLoaded node attempting to read from / write to DynVars in the World DynamicVariableSpace
2) A similar setup where a target slot with a DynamicVariableSpace is duplicated and then one attempts to read / write to dynamic variables on the newly duplicated slot.

**Comment by Psychpsyo** [comment]
With there now being a reproduction item, why is this issue still under "Needs More Information"?

**Comment by Zyzyl** [comment]
@Psychpsyo Just to get absolute confirmation the reprex reproduces the issue for multiple people, would you mind opening the world and checking?

**Comment by Psychpsyo** [comment]
How do I do that? Just pasting the link didn't work.

**Comment by Zyzyl** [comment]
You can put the URL in a string input node and then provide that as the URI input to an Open World LogiX node.

**Comment by Psychpsyo** [comment]
As I have absolutely no idea what I am supposed to look at in that world, I have made a simplified setup that shows the issue:
![theIssue](https://user-images.githubusercontent.com/60073468/115544842-6141c000-a2a3-11eb-9a22-a41e70da8f23.png)

I'll also be sending this to Froox in-game.

**Comment by shiftyscales** [comment]
It's better to have a public folder link to the problematic object, or host it in a world that is openable by anyone instead of directly messaging him, @Psychpsyo. Everything relevant to this issue (or any other) should be kept exclusively to GitHub as much as possible to make it easier to organize the information.

**Comment by ukilop** [comment]
The 3 frames are very much still needed,
discussion in discord proving this: https://discord.com/channels/402159838827905024/501866888964341790/940751561813012550
public folder containing example:    neosrec:///U-VoidPaw/R-9ee3ed02-6007-4446-ba19-1dde99c7bb55
