### ISSUE TITLE
Avatar creator not using the correct "Eye" bone

### ISSUE THREAD

**Issue by svenrubio** [Neos-Metaverse/NeosPublic#2013]
## Describe the bug
The eye bone doesn't seem to work if there are other bones on the avatar with "Eye" on the name. For example, in my model, the eye seems to use "UnderEye_L/R" instead of "Eye_L/R"

## To Reproduce
Have a model with multiple armature bones that include the string "Eye"

## Expected behavior
For it to use the correct "Eye" instead of "UnderEye"

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.9.1119
 - Neos Platform: Any
 - Regression: No

## Reporters:
Neos: Sveny!
Discord: Sveny#0621

**Comment by shiftyscales** [comment]
Can you please provide a model that exhibits this issue that could be used for testing/replicating the issue while imported, @svenrubio?

**Comment by svenrubio** [comment]
I'll try and quickly find or make one myself for demonstration, as the one I am having issues with is a paid model and the license will not allow me to share it.

I can tell you however, that renaming "UnderEye" to just "UnderE" has fixed the issue, and the eye is now correctly bound.

**Comment by Frooxius** [comment]
Fixed in 2021.6.8.685, thanks! Not sure if there are any other names that are causing issues since you only mentioned UnderEye. If you can't provide the model itself, the hierarchy list should be sufficient in case there's more.
