### ISSUE TITLE
"Ctrl+Shift+D" not able to delete anymore

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2014]
## Describe the bug
Ctrl+Shift+D is unable to delete anymore.

## Relevant issues
-

## To Reproduce
1. Hold item
2. Try to delete with Ctrl+Shift+D
3. Fail

## Expected behavior
Deletes item.

## Screenshots / Video
-

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.14.1059
 - Neos Platform: Only tested on windows
 - Link to reproduction World/Item: -
 - Regression: Yes. Previous build.

## Additional context
CTRL seems to lock the cursor and D moves the user without deleting the item.

## Reporters:
3x1t_5tyl3# 0001

**Comment by Toxic-Cookie** [comment]
CTRL + Shift + S also doesn't save anymore.

**Comment by AshtonSparx** [comment]
Can confirm, anything regarding the CTRL+ ... all no longer work with build 2021.4.14.1059

**Comment by Frooxius** [comment]
Fixed in 2021.4.17.185, sorry for the inconvenience!
