### ISSUE TITLE
Pressing Alt + Tab to switch to another application engages Third Person Mode

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#2016]
## Describe the bug
I'm a prolific Alt-Tabber, currently Alt-Tabbing in desktop mode will enable Third Person.

## Relevant issues
https://discord.com/channels/402159838827905024/439422161657135106/831969981628547123

## To Reproduce
1. Launch Desktop Mode
2. Alt-Tab to another window
3. Observe that Alt+Tab enables third person mode

## Expected behavior
I'd expect Alt-Tab to not have such a drastic effect on Neos as I'm just trying to alt tab around

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.14.1059
 - Neos Platform: Any

## Additional context
This might be difficult to change, but Alt-Tab is a very common scenario and It would be nice if something can be done.

## Reporters:
KodeyTheNeko#1284, Me

**Comment by 3x1t-5tyl3** [comment]
#2015 Probably related as froox mentioned alt is a temporary key.

**Comment by ProbablePrime** [comment]
Excellent, Closing for that one then.
