### ISSUE TITLE
Finger setup tool

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#2019]
Just a tool that allows you to setup hands after the avatar is already been made and when finger bones are wrong then you can run a hand setup tool after renaming it in-game  then apply the hand setup tool  to fix the fingers

**Comment by TehTurk** [comment]
This isn't really a thing. It's expected for your avatar to have a consistent naming convention. If fingers break it's usually another thing entirely.

**Comment by ProbablePrime** [comment]
You can manually set up fingers after avatar creation, Its basically covered here: https://youtu.be/b8kAZFlmCCw

Just a couple of components.
