### ISSUE TITLE
Friends API returns 500 internal server error

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#2021]
## Describe the bug
I'm aware the HTTP Apis are not stable and might change but I'm still exploring them for some automation efforts.

When i try to accept a friend request, I just can't seem to. I don't have much information from the webserver to go on.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/8791132/114802191-1f1ff800-9d52-11eb-8d04-c9017588ca11.png)
![image](https://user-images.githubusercontent.com/8791132/114802213-29da8d00-9d52-11eb-9a01-84787e241635.png)

This is Postman, which lets me make HTTP requests without any need for much code. Headers and the request body are shown. If you're unfamiliar with Postman and need assistance please let me know.

## Bug information (please complete the following information):
This section is largely N/A, but generically, it happens all the time and on any version.

## Additional context
I'm probably doing something very wrong here, like missing a property or a header, I'm just not sure. I'm once again aware that the HTTP APIs are somewhat unstable and subject to change. I'm just frustrated by randomly changing things with the hope that this might start working. 

So i'd like to request any info that's available.

## Reporters:
Just me.

**Comment by ProbablePrime** [comment]
We tried some additional variations: 
![image](https://user-images.githubusercontent.com/8791132/114914058-bc247480-9dd6-11eb-826d-f9bd66335a3c.png)
![image](https://user-images.githubusercontent.com/8791132/114914094-c5154600-9dd6-11eb-959f-4ed7348c3211.png)
![image](https://user-images.githubusercontent.com/8791132/114914123-ca729080-9dd6-11eb-9838-adefc3f2f3ff.png)


You can see the conversation here: https://discord.com/channels/402159838827905024/453478758956138527/832123261147414539

**Comment by Frooxius** [comment]
I've looked into this, it's a bug on our end. If the target user was never logged in, they were missing a Status entity, which the friend update tried to access. I've fixed this and pushed new update to the API, the call should succeed now (assuming everything else is correct).

Let me know if there's still issue.

**Comment by ProbablePrime** [comment]
This resolved it, I'll eventually need to send status updates but didn't need them at the time. Thank you for the patch!

**Comment by Frooxius** [comment]
You don 't need to worry about that, part it gets initialized automatically once you start sending them.
