### ISSUE TITLE
Third person context menu inaccessible at user scale of 0.75 or less

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2022]
## Describe the bug
While in the third person view, the context menu is inaccessible if the user scale is below 0.75

## To Reproduce
- Change your scale below 0.75 by any means
- Open the context menu while in the third person camera view and attempt to interact with it

## Expected behavior
- The context menu remains interactible at all user scales

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.14.1059
 - Neos Platform: Windows
 - Regression: No

## Additional context
It appears that a user scale larger than 1 does not produce this issue.

## Reporters:
Shifty# 7944, epicEaston197# 0793, ChrisWarner103# 8178

**Comment by Frooxius** [comment]
Fixed in 2021.4.17.185, thanks!
