### ISSUE TITLE
Allow "TooltipMultiplexer" to interact with "RawDataToolTip" Events

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2024]
## Is your feature request related to a problem? Please describe.
My problem right now is, that it requires quite a bit of setup to get "Equipping" and "Dequipping" events for TTMP's.
And even then they're unreliable in certain scenarios or require delays to make sure they fire correctly.

## Relevant issues
#1388 #1164 #1157 

## Describe the solution you'd like
- A way for "RawDataToolTipEvents" to interact with the TTMpxer.
- "ToolTipMultiplexerEvents" LogiX node. (Similar to RawData)

## Describe alternatives you've considered
Use logix which can be unreliable 10-20% of the time.

## Additional context
-

**Comment by TehTurk** [comment]
Redirecting to #2026
