### ISSUE TITLE
IK Heuristics Tweak - Accept "Hip" as hips bone

### ISSUE THREAD

**Issue by H3BO3** [Neos-Metaverse/NeosPublic#2025]
## Is your tweak request related to a problem? Please describe.
I've seen a few issues in the past couple weeks related to avatar heuristics skipping the hips bone when it is named "hip". The biped detection does not throw an error and so it causes very weird stretching when the resulting avatar is moved.

## Describe what would you like tweaked
Accept "hip" as the hips bone, the first in the chain. This also needs to be done with the context that the two thigh bones could be named "hip_left" and "hip_right" and variants thereof.

## Describe alternatives you've considered
None, short of reworking biped detection to be able to manually map bones ingame while detection is happening.

## Additional context
https://discord.com/channels/402159838827905024/439421735474036738/832287226154450984
This is a recent conversation where this issue happened, with rig hierarchy and bone names shown, plus a video of the resulting issue.

**Comment by Electronus** [comment]
I have seen this multiple times over the last couple weeks it seems to be a common thing.

**Comment by Frooxius** [comment]
Do you have any sample models that I could use for testing? This is a bit tricky one, because some models use "hip" for the upper leg, so it's a bit ambiguous and I'd need a model to iterate on.

**Comment by Drafy07** [comment]
> Do you have any sample models that I could use for testing? This is a bit tricky one, because some models use "hip" for the upper leg, so it's a bit ambiguous and I'd need a model to iterate on.

heya , i am the owner and maker of the gryphon model , if you add me onto discord i could send you over the fbx (discord : Drafy#1176)

**Comment by shiftyscales** [comment]
Closed in favor of #3057 which has additional information including a sample model for testing.
