### ISSUE TITLE
Tooltips besides RawDataToolTip have a hard time with events, (ToolMultiplexer, anything IToolTip Based)

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#2026]
## Is your feature request related to a problem? Please describe.
Currently most tooltips don't have something akin to RawDataToolTip Events, where in issues #1468 there is a request for dequip/equip nodes while in issues #2024 it's similar but applies to Multiplexer directly.

## Relevant issues
#1388 #1164  #1157 #1468

## Describe the solution you'd like
If possible 2 options could happen,

We just have individual events for IToolTip such as De/Equip 

- OR -

Something of an overload or a new node akin to RawDataToolTip Events or something similar where it can take in any IToolTip and Reference into the proper node for what a tooltip might have associated with it. (A ToolTip Events Node)

## Describe alternatives you've considered
Looking back from my experience trying to do something manual with a Standard Controller has proven to had it's benefits but also has it's issues at times when some events are not tied directly to a pulse.

## Additional context
This was made after seeing both issues #1468 and #2024 and realize they were similar in nature and could be compounded.

**Comment by 3x1t-5tyl3** [comment]
I would like to mention this would go beyond just "Equpping" functions. But extend to ToolUpdates, secondary, primary ect. The same outputs the RawDataTooltip has.

**Comment by Frooxius** [comment]
We can add Equip/Dequip events as those are general, but updating of the tool, secondary and primary cannot be accessible, as those are processed by arbitrary logic of the tooltip, which can differ wildly between each one of them.

RawDataTooltip is designed to specifically forward these raw data, but most other tooltips are not, as we can't make assumptions about what they will be doing based on those actions. Instead we can offer ways to expose specific functionality to those particular tooltips based on what's needed and what they do, so it fits into their functionality well, but that would require us knowing more about your usecases.

**Comment by Frooxius** [comment]
This has been implemented by ProbablePrime in 2021.9.1.643! Thanks for the request!
