### ISSUE TITLE
Closing inspector with selected text field blocks access to the dashboard by escape key

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2032]
## Describe the bug
If you close an inspector on the desktop mode after having clicked on a field to edit it without pressing enter, the binding for escape remains blocked, and the dashboard is inaccessible until you open another inspector/editable field, and deselect the field.

## To Reproduce
- Select an editable field (e.g. a field in an inspector)
- Close the inspector while the field is still selected (cursor blinkng)
- Locomotion, and other bindings are restored as expected, but the dashboard toggle key (Escape) is 

## Expected behavior
The dashboard key is unblocked when the editable field is destroyed/closed.

## Screenshots / Video
I took before and after pictures to try and spot the differences between the input bindings using the debug input bindings settings, but as far as I can see they're identical.

Dashboard Unblocked:
![DashboardUnblocked](https://user-images.githubusercontent.com/54213390/115067934-6e773d00-9ea6-11eb-913f-f947d5392c6f.png)

Dashboard Blocked:
![DashboardBlocked](https://user-images.githubusercontent.com/54213390/115067969-7800a500-9ea6-11eb-8068-e1b15a5f541c.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.14.1059
 - Neos Platform: Windows
 - Regression: Unknown

## Additional context
I tried this behavior in VR and discovered that the virtual keyboard remains open while the editable field is closed this way. So it is likely the virtual keyboard being open (even if invisible in the desktop mode) that is blocking the escape key from opening the dashboard.

## Reporters:
Shifty# 7944, Cyro# 5120

**Comment by Frooxius** [comment]
Fixed in 2021.4.17.185 thanks for report!
