### ISSUE TITLE
Missing locale string drivers and descriptions

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2033]
## Is your tweak request related to a problem? Please describe.
Despite there being a locale key for the description of the NoclipLocomotion (Locomotion.Noclip.Description) there is not a description field to drive on the locomotion module with it. Additionally, in the template worlds, e.g. gridspace, locomotion modules are not setup with locale string drivers by default for some locomotions, e.g. Noclip, Teleport.

Additionally, by default in new worlds, NoclipLocomotion does not have locale string drivers.

## Describe what would you like tweaked
Add a description field to NoclipLocomotion, and add locale string drivers that are missing from the template worlds.

## Additional context
I observed these things while updating an old world of mine.

**Comment by Frooxius** [comment]
This is normal, LocaleStringDriver presence isn't necessary, because the module internally provides a translation key that's used to fetch and display translated name. Last time I checked all those names are properly translated in the UI (e.g. opening context menu).

Lack of LocaleStringDriver on itself is not necessarily an error.

Did you notice any of the names actually not being translated in those cases when you switch the UI language?

**Comment by shiftyscales** [comment]
Yes. I created the following screenshot by opening a new GridSpace template while my locale was set to Japanese (ja):
![GridSpace Missing Locale](https://user-images.githubusercontent.com/54213390/115076597-a33cc180-9eb1-11eb-8da3-703c01277f5c.png)

I checked on the context menu, and yes, the translated keys appear properly there. So I suppose it's specifically just the slot names in the inspector that aren't translated as I would expect which is what stood out to me.

**Comment by Frooxius** [comment]
That's normal, the slot names aren't supposed to be translated. They're only translated on the modules which use the name of the Slot as the name, but Noclip and Teleport provide this implicitly.

**Comment by shiftyscales** [comment]
Yeah, That makes sense. I assume the Noclip.Description is displayed somewhere in the UI (or will eventually be)? It makes sense now that you don't have a description field for the NoclIpLocomotion component either though, since there's not really any properties to edit on it. This can probably be closed up, then?

**Comment by Frooxius** [comment]
Yes that's not displayed anywhere right now, but will likely be at some point.
