### ISSUE TITLE
Hide Unique Hardware IDs from the Session

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#2034]
## Is your feature request related to a problem? Please describe.
A user on the Discord, was trying to understand why Neos exposes the Unique Light House Ids to the world model and people within the session.

Showing these can lead to [Device Fingerprinting](https://en.wikipedia.org/wiki/Device_fingerprint) which can be a privacy issue.

## Describe the solution you'd like
Any IDs shared to a Neos Session should where possible isolated or replaced such that should a user wish to they can not be identified later by any method.

This issue is quite a lot larger than just those IDs as there are other unique identifiers. However there is an option to reset some of those identifiers by Logging Out or Reinstalling Neos.

## Describe alternatives you've considered
Some Discord users are stating that you can rename those IDs by modifying the controllers using a tool. This isn't an experience we should force users to go through.

## Additional context
**I get that this is a weird one. I understand your initial reaction, I had it too.** 

I'd like to encourage anyone reading to think beyond the here and now and to think about the future of Neos and the future of your privacy within that. Beyond that think about Privacy within VR in a similar way you might think about Browser Privacy.

Neos is trying to use techniques and solutions in a lot of other places which lead to a somewhat decentralized approach and protecting privacy is usually a part of this approach.

Privacy is a complex area with a lot of opinions and problems. 

If you've ever installed Ad Block or a cookie blocker add-on, or complained about the data policies of other companies then you should view this item in a similar way. 

Just because someone isn't doing something with this today, doesn't mean someone can't in the future.

## Links and Resources
- This can test your Browser and usually Uniquely fingerprint it - https://coveryourtracks.eff.org/
- https://clearcode.cc/blog/device-fingerprinting/
- https://privacybee.com/blog/what-is-device-fingerprinting-and-how-do-i-prevent-it/

## Source
From a conversation here: https://discord.com/channels/402159838827905024/439422161657135106/832724220714549337

Made on behalf of that conversation.

**Comment by SnooperXP** [comment]
I’m agreement here, if there are any unique identifiers that are needed by a session they should either be randomized per session, or just truncated and not sent from the client. We should be hyper vigilant about preventing device fingerprinting outside of any necessary means by the Neos servers, and even on that side I would be like any and all information that is being sent there to be directly called out in some fashion, and (there probably is) a policy in place that would prevent any on sale of this data or disclosure to third parties as well.

**Comment by Aerizeon** [comment]
Unfortunately, there's no other way to "Map" trackers if you want to use them in LogiX for something else, except by searching the user root by a known name.

If this gets changed, I'd suggest adding some way to either pass through the SteamVR Node assignment, or allow for some way of assigning a custom persistent name, so that it can be referenced.

**Comment by ProbablePrime** [comment]
In response to @Aerizeon we can use Neos Generated ID. This ID would change if Neos is re-installed.

There are many possibilities.

**Comment by Frooxius** [comment]
Yeah we can replace the ID's with a Neos generated ones that would get wiped on database wipe. We already do something similar to some other identifiers to avoid exposing them to other users.

There will still be some things that you can use, that represent the identity of the user in some form though, it can't be eliminated fully since then you wouldn't be able to communicate at all, but these we can definitely anonymize.

**Comment by ProbablePrime** [comment]
If the user is logged in, in some fashion that's ok that's their choice and their identity. 

Its just their desire and I guess right to vanish completely that would likely involve logging out anyway.

**Comment by Frooxius** [comment]
The ID's should now be obscured in 2021.4.24.620 and change every time database is reset, let me know if there are still any issues!
