### ISSUE TITLE
New Logix node for user based impulse.

### ISSUE THREAD

**Issue by candypheonixIO** [Neos-Metaverse/NeosPublic#2036]
Would it be possible to make a new node that allows you to input a user and impulse to have it come from that user? Just so we don't have to make bulky systems that use boolean latches and fire on true nodes to do this.

An example use-case, _and one that I'm currently in need of a node like this for is_; mass value user override assigning, I want to use a for-loop but this poses an issue since I have to use the 'ghetto' boolean latch and fire on true method, which will fall behind on the for loop when trying to assign a group of people to a valueuseroverride.

**Comment by H3BO3** [comment]
Related to #338
