### ISSUE TITLE
Reference card of a slot unable to be plugged into multiplex node

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2051]
## Describe the bug
Trying to plug a slot into a multiplex node (no matter what type it is of currently) does not do anything.

## To Reproduce
[Steps to reproduce the behavior:
1. Create slot and make ref card of it.
2. Make a multiplex node.
3. Try to multiplex the slot by just plugging it in.

## Expected behavior
A Ref should get created and connect the slot into the multiplex node.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.17.185
 - Neos Platform: Windows, probably any
 - Regression: Don't know.

## Additional context
Upon further inspection it seems like the "Ref" slot does get created but without having any components or children.
Also, plugging the slot into a node which specifically wants an input of type slot works and the resulting arrow can be connected to the multiplex.

## Reporters:
Cameron#7818

**Comment by ukilop** [comment]
I've played with this before, I think the wire you drag from the top of any interface simply can not change a nodes' type

**Comment by Psychpsyo** [comment]
But this also happens when the multiplex is already of type Slot.

**Comment by Etherealflux** [comment]
I've described this issue in #1567. There are two separate problems:

* As ukilop said, interface cards can't cause a node to be cast under any circumstance. The reverse is also true: plugging a wire into an interface card cannot produce a cast. The types have to match exactly.
* As Psychpsyo said, interface cards can't plug their Slot output into a multiplex node under any circumstance.

I didn't know it was generating an empty Ref slot, though. Is an exception happening, or is it silently failing?

**Comment by chemicalcrux** [comment]
I've described this issue in #1567. There are two separate problems:

* As ukilop said, interface cards can't cause a node to be cast under any circumstance. The reverse is also true: plugging a wire into an interface card cannot produce a cast. The types have to match exactly.
* As Psychpsyo said, interface cards can't plug their Slot output into a multiplex node under any circumstance.
I didn't know it was generating an empty Ref slot, though. Is an exception happening, or is it silently failing?

**Comment by Psychpsyo** [comment]
Did some more testing with Ukilop and this also affects the format node and expanded ?? nodes. (not 2-input ?? nodes)
Meanwhile a slot interface can normally cast the 'body node slot' node to type slot.

**Comment by RobertBaruch** [comment]
Also happens with Pick Random node:

1. In LogiX, spawn out a Pick Random node.
2. Spawn a Get Parent slot node, or any other node that takes in a slot.
3. Connect the Pick Random node's output to that node's input. The Pick Random node should now be typed for Slot.
4. Spawn an interface card for any slot.
5. Attempt to connect the interface card's Slot to any Pick Random node's input.
6. Note that the connection cannot be made.

Workaround: Use any node that has a Slot input. Connect its input to the interface card Slot. Now connect the resulting reference to the Pick Random input.
