### ISSUE TITLE
ReferenceCopy<IAssetProvider<FrooxEngine.ITexture2D>> does not accept StaticTexture2D as a source

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2055]
## Is your tweak request related to a problem? Please describe.
A ReferenceCopy<IAssetProvider<FrooxEngine.ITexture2D>> does not accept a StaticTexture2D as a source even though ReferenceMultiDriver does. I feel like the two should behave exactly the same in that regard.

## Describe what would you like tweaked
Make ReferenceCopy accept the same types as ReferenceMultiDriver.

## Describe alternatives you've considered
There might be a way to do what I'm trying to do with just a ReferenceCopy of a different type.
If not, a ReferenceMultiDriver that drives just one reference can be used in place of a ReferenceCopy. (though this feels wrong for obvious reasons)

**Comment by Frooxius** [comment]
Unfortunately this is not possible, ReferenceCopy<T> Source needs to be a sync reference, which StaticTexture2D is not. Its job is to copy target of source reference to target reference.
