### ISSUE TITLE
Some images have odd artifacts

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2060]
## Describe the bug
Large image files (seen it on 4-8k-ish ones) sometimes have small black dots scattered all over them that appear when getting close to the image.

## Relevant issues
Didn't find any.

## To Reproduce
1. Look at the reproduction item below in Neos. The artifacts should be obvious when viewing it close-up

## Expected behavior
The image should look normal.

## Screenshot
![artifacts](https://user-images.githubusercontent.com/60073468/115457679-213bf800-a225-11eb-8d01-35a3a62a315b.png)

## Bug information (please complete the following information):
 - How often does it happen: Sometimes
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.17.185
 - Neos Platform: Windows, probably any.
 - Link to reproduction NeosDB image: neosdb:///329f2d105d7d6ecde6915f8decaa916a837928fbbe100e5b9527907506e56bcb.webp
 - Regression: Don't know but it has been around for a long time.

## Additional context
I've mainly seen these on .webp images, though I had a .jpg do the same earlier today. It is possible to mostly mitigate the artifacting by increasing the PowerOfTwoAlignThreshold on the image.

## Reporters:
Cameron#7818

**Comment by Readun** [comment]
Another one with that issues is the Facetracking Guidline Picture.

**Comment by shiftyscales** [comment]
I believe this might potentially be because the texture is a non-power of two resolution (4065x10665) @Psychpsyo. I tried changing the PowerOfTwoAlignThreshold to 0.24 and it resolves the issue.

I also tried scaling the image up slightly to 4096x10746 and reimporting, and that also resolved the issue.

**Comment by shiftyscales** [comment]
It also appears that this only affects particular crunch compressed formats, and only on the first/closest mipmap.

Forcing the PreferredFormat to some types such as RawRGBA, BC3_Crunched, BC1_LZMA, BC3_LZMA do not exhibit the issue. Similarly, if disabling CrunchCompressed or enabling Uncompressed the issue also does not appear.

**Comment by Psychpsyo** [comment]
Is there a way to force an image to be one of these by default? (since converting them takes a while.)

**Comment by shiftyscales** [comment]
What do you mean 'by default'? Do you mean on import? Otherwise, like I said, that's what the "PreferredFormat" setting on the StaticTexture2D can do. But personally I'd recommend either changing the PowerOfTwoAlignThreshold, or manually resizing the image so that it's a power of two on one of the axis. E.g. slightly scaling it up to 4096x10746 as I noted above.

**Comment by Psychpsyo** [comment]
Well, when switching the preferredFormat, Neos has to calculate for a while to bring the image into that format. I was wondering if that waiting time could be skipped by somehow already having the image in that format when (in my case) putting in its link.

But since this isn't the preferred way to handle this, I'll look into the other two some more.

**Comment by Psychpsyo** [comment]
> 
> 
> It also appears that this only affects particular crunch compressed formats, and only on the first/closest mipmap.

I've just encountered an image which has this on the (I think) second closest mipmap. I'd send an image but it's loaded from localhost so it wouldn't show up and syncing it to the Neosdb makes the compression disappear.

**Comment by shiftyscales** [comment]
It has to calculate it for a while because those variants need to be generated on the cloud, then downloaded. The variant generation should be a one-time thing per asset. Otherwise, it's just downloading the variants that are already generated, @Psychpsyo.

As noted though- the best solution would probably be making sure the original asset uses a proper power of two scaling (you might notice that changing the PreferredFormat also changes the final resolution slightly much in the way adjusting the PowerOfTwoAlignThreshold does as well.)

**Comment by Psychpsyo** [comment]
I'll probably go with scaling them then. Thanks for the help.

**Comment by Psychpsyo** [comment]
So I've now imported a bunch more images of the same size. Scaling them to 4096x10746, didn't fix it and made Neos scale them to 4096x10748. So I tried scaling them to that before importing and there is still some that show artifacts. That said, when I synced them to the cloud, all the artifacts disappeared. Apart from the ones on one image which I accidentaly put in the wrong folder so I had to delete and reupload it which re-introduced the compression. So here is my neosdb link to the 4096x10748 texture with compression artifacts, in the hopes that this'll be able to pinpoint the cause of this further:
neosdb:///8dd880ec84ebbf59b4a9ba630fd4fa4a3463b5d9c0bcd008692e895685e72609.webp

**Comment by Psychpsyo** [comment]
> Forcing the PreferredFormat to some types such as RawRGBA, BC3_Crunched, BC1_LZMA, BC3_LZMA do not exhibit the issue. Similarly, if disabling CrunchCompressed or enabling Uncompressed the issue also does not appear.

Since I reverted to changing the format, as the scaling solution did not work:
This same issue also happens to at least BC3_Crunched, BC3nm_Crunched, BC3nm_LZMA, BC6H_LZMA and ETC2_RGB_Crunched.
At this point, Neos was using over a gigabyte of memory and crashed SteamVR but I think it is fair to say that the type of compression is largely irrelevant.

**Comment by Psychpsyo** [comment]
Also, and I'm not sure if setting the preferred compression to BC1_Crunched silently overrides whatever the CrunchCompressed boolean is doing but I had artifacts show up with this configuration as well.

**Comment by Psychpsyo** [comment]
I've just ran into another case of this, this time on a picture that is around 1K large. Just import the following image, selecting "Image / Texture" on the import dialogue. Once the image finishes loading, the artifacts appear next to the borders and text, all over the image.
![Eny6nZMXYAAC9Ih](https://user-images.githubusercontent.com/60073468/149877491-cfcb5151-2b74-45fa-9ff8-3b89684d2f79.png)
