### ISSUE TITLE
IgnoreCase on Find Child By Name doesn't work properly

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2064]
## Describe the bug
When setting the Find Child By Name node to MatchSubstring, it will always ignore case, no matter what IgnoreCase is set to.

## Relevant issues
Didn't find any.

## To Reproduce
1. Create Find Child By Name node
2. Set MatchSubstring to true and IgnoreCase to false
3. Observe that it finds child nodes with different capitalization from what ou entered.

## Expected behavior
It should respect case when matching substrings.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.17.185
 - Neos Platform: Windows, probably any
 - Regression: Don't know

## Reporters:
Cameron#7818

**Comment by shiftyscales** [comment]
This was fixed in `2021.4.24.620`:
> - Fixed FindChildByName node always ignoring case when matching substring, even when told not to (reported by @ Psychpsyo)
-- Existing instances will have True input node automatically plugged into IgnoreCase if they are setup with MatchSubsting (based on report by @ Shifty | Quality Control Lead and @ Cyro)
