### ISSUE TITLE
Vive trigger needs to be held to fly slowly

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2065]
## Describe the bug
When in noclip on Vive controllers, you need to hold the trigger down to move slowly. This used to be the opposite.

## Relevant issues
#691 confirms that this was intentional.

## To Reproduce
1. Use Vive wands
2. Go into noclip
3. Move around

## Expected behavior
Pulling the trigger should be for going fast, not the other way around.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.17.185
 - Neos Platform: Windows, probably any
 - Regression: Yes, not sure when exactly though.

## Reporters:
Cameron#7818

**Comment by Frooxius** [comment]
This was changed intentionally with the new Input Binding system to be consistent across locomotion modules.
