### ISSUE TITLE
Eye manager reports eye position as 0,0,0 when eye position tracking is lost

### ISSUE THREAD

**Issue by kulzae** [Neos-Metaverse/NeosPublic#2068]
## Is your tweak request related to a problem? Please describe.
The Eye manager currently moves my eyes to a rotation located up inside my head when i close my eyes, this means for a split second before and while my eyes are closed they are at a very weird rotation and then have to rotate back as soon as my eyes open

## Describe what would you like tweaked
Either a setting or default behavior to keep the last known rotation before the eye position data was lost (sudden zeroing of position)

## Describe alternatives you've considered
Using logix to edit this behavior

**Comment by shiftyscales** [comment]
Issue inspired by a solution Cyro had implemented for himself to prevent his eyes from snapping forward whenever he would blink.
![image](https://user-images.githubusercontent.com/54213390/115579185-c2a16900-a27a-11eb-9948-c5cd92848917.png)

This solution couldn't account for if a user were to reposition their eyes with their eyes closed- but as a default behavior, retaining the last known eye angle while the eyes are closed is a cosmetic enhancement in a majority of circumstances.

**Comment by RileyGuy** [comment]
I can make a solution that accounts for one eye being closed so that it follows the other, if that would help as a mockup.

**Comment by Frooxius** [comment]
I've checked the eye tracking code and it was actually using wrong bitmask for checking the validity of eye tracking data, so it was letting some of the invalid data through. Should be good in 2021.4.24.620 now. When one of the eyes doesn't track it also uses the direction from the other one.

Let me know if there are still some issues with this!
