### ISSUE TITLE
On Saving node changes not visible in inventory preview

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2070]
## Describe the bug
When modifying an item with the On Saving node, changes made by that pulse do not show up in the Inventory preview of the item.

## Relevant issues
#2069 might be related.

## To Reproduce
1. Make something that gets visually modified by the pulse of an On Saving node.
2. Save it.
3. See it not look modified in your inventory.

## Expected behavior
The preview should reflect the state of what actually got saved, not what it looked like right before it got saved.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.17.185
 - Neos Platform: Windows, probably any.
 - Link to reproduction World/Item: Sent to Froox in-game.
 - Regression: Don't know, probably not.

## Reporters:
Cameron#7818

**Comment by shiftyscales** [comment]
As Frooxius has noted on issue #2069, not everything is guaranteed to be finished by the time the saving processs has completed.

If you wish the object to have a specific appearance in the inventory, I'd suggest making a custom inventory thumbnail for the object: https://youtu.be/LoLPED9oJrU
