### ISSUE TITLE
The notification sound when making a new neos account is very loud and startling

### ISSUE THREAD

**Issue by StarfishHidari** [Neos-Metaverse/NeosPublic#2073]
## Is your tweak request related to a problem? Please describe.
When you make a new neos account, the neos bot sends you 6 messages in the moment, including a KFC donation. All of the notification sounds play at once and stack on top of each other making it really loud and startling. I can imagine it's really unsettling for new players making a new account for the first time, it sends my heart racing from how startled I get each time I've had to do it (from registering accounts for headless servers and such).

## Describe what would you like tweaked
I am not entirely sure what the best solution would be, I just looked to see if someone had mentioned this before and didn't really find anything so I'm writing this. Maybe upon account creation limit the notification sounds sometimes? Just for the first set of messages after creation. Though with that suggestion it might have issues and I'm not sure how you'd limit the notifications in a way that makes sense.

**Comment by shiftyscales** [comment]
Starting a new user's online status on 'busy' for the first launch/if they're in the tutorial/have just created their account? It would suppress the notifications, and is also relevant to their initial interactions/setup.

**Comment by shadowpanther** [comment]
As an alternative (proper?) solution, make the notification system play only one sound at once. Sometimes you receive a bunch of notifications at the same time, especially if you were out of your headset for some time. Limiting sound playing to one instance would solve this.

**Comment by Frooxius** [comment]
@shadowpanther's correct, the sound should just simply play once. Added this behavior in 2021.4.24.620, thanks for report!
