### ISSUE TITLE
Add "ToString" LogiX Node to "String" category 

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#2075]
## Is your tweak request related to a problem? Please describe.
Many new users who are introduced to LogiX seem to expect the `ToString` Node to be under the `String` category.

This is especially confusing given the presence of `ToTimeString` under `String > Quick Format`, which would seem to indicate that it is the appropriate location to expect the `ToString` node.

A few other existing users have echoed experiencing similar issues.

## Describe what would you like tweaked
Add an additional category path, so that the `ToString` family of nodes exists in both the `Operators` and `String` categories.

## Describe alternatives you've considered
* Continue the way things are now, with `ToString` only appearing in `Operators`

**Comment by Electronus** [comment]
yeah ill throw my support in. this has been a consistent annoyance with me.

**Comment by Frooxius** [comment]
Added in 2021.4.24.620, thanks!
