### ISSUE TITLE
LogiX Nodes should have an ObjectRoot

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2076]
## Is your tweak request related to a problem? Please describe.
Alot of times when I want to do more complex things with logix nodes in an inspector it is always a pain to have the "go to object root" button only for the logix nodes not to be able to do that.

## Describe what would you like tweaked
Add an ObjectRoot to all LogiX-Nodes which would be added and removed with the visuals of the node.

## Describe alternatives you've considered
Don't.

## Additional context
I'm not sure really what else to say it's just an absolute pain everytime to click the button.. oh shit you went to far go back and repeat 3-4 times *instead* of just having an object root.

Edit: Typically this is to rename the node or give it a color to indicate something special, like it's an input field as to not unpack the entire logix or similar things in order to more simply indicate things for those nodes.

**Comment by Aerizeon** [comment]
Preferably this component would be attached automatically on spawn/unpack, and removed when packed (so as not to interfere with anything looking for ObjectRoot, and so that it is easy to correct for cases where you select "Remove all Child Object Roots" on something higher in the hierarchy.)

**Comment by Frooxius** [comment]
ObjectRoot isn't suitable for LogixNodes, it's specifically for things that are objects, but LogixNodes are just components at the core and there can be  multiple of them on same slot. Tracking and managing ObjectRoots with unpacking would get really messy and hard to deal with and that's not how we solve problems.

Instead, we can make the inspector be more aware of LogiX nodes specifically and open those up automatically.

**Comment by Frooxius** [comment]
Added this behavior in 2021.4.24.620, thanks!
