### ISSUE TITLE
Userspace Laser is separate from actual tooltip laser on avatar

### ISSUE THREAD

**Issue by GearBell** [Neos-Metaverse/NeosPublic#2077]
Userspace laser for dashboard and keyboard is separate from the actual laser on the avatar and is pointing in a different direction from the tooltip laser. Normally players like to point the tooltip from the fingertip forward, but my userspace laser on my left hand somehow is separate and is a full 75 degrees pointed in another direction, making navigating the dashboard and the keyboard unusable. It occurs on specific avatars rigs. It does not happen for older or different avatars. It occurs upon building the avatar and is permanent. Understandably my rigs are strange, however I am using an old rig that Ive used many times before and somehow this one, with the same exact rig, does the seperate laser thing. And only in the left hand. so far it seems to "correct" itself when i rotate the tooltip a bit closer to aiming at the userspace laser.

**Comment by Electronus** [comment]
To give more Information, the laser separation is technically intended, to keep you dash usable even if your avatar lasers cant reach it.

**Comment by shiftyscales** [comment]
Yeah, as noted, that's a safety mechanism that was introduced to prevent users from being unable to access their dashboard if their avatar's hands/lasers were bound/inaccessible. It only takes effect when the position/rotation of the avatar's lasers are *way* out of alignment with the userspace ones.

It might be worth trying to reparent the laser under the hand proxy slots on the avatar to see if that changes the behavior at all? I'd be curious to see any avatar(s) that are affected by this issue if you have a public folder containing some that could be tried.

The avatar's rig itself shouldn't really be too much of a factor as long as the hand/finger/laser positions and rotations are relatively close to matching the userspace lasers.

(Although as noted, there is quite a wide tollerance that should account for a majority of cases unless they are way out of alignment.)

**Comment by Frooxius** [comment]
This is intentional behavior. The userspace checks if the world lasers are close enough, but if the angle or distance is too different, it'll override the position. This is to prevent world from breaking access to the private UI. We can tweak this behavior somewhat, but I'd need to know more about cases where it's not behaving well and perhaps have some sample avatars.

**Comment by H3BO3** [comment]
Gearbell has been unable to replicate this or hasn't had it come up again, closing the issue.
