### ISSUE TITLE
Add an AssetMetadata Component for the VideoTexture

### ISSUE THREAD

**Issue by Kal47** [Neos-Metaverse/NeosPublic#2080]
## Is your tweak request related to a problem? Please describe.
It is not.

## Describe what would you like tweaked
The addition of an AssetMetadata Component for the VideoTexture in order to find the resolution and aspect ratio of the VideoTexture as well as other useful information.

## Describe alternatives you've considered
Attempting to use the AssetMetadata2D component does not work, and I cannot think of any way to get that information.

## Additional context
This would allow everyone retrieve detailed information on the video texture  there by allowing for smarter video players and other objects.

**Comment by 3x1t-5tyl3** [comment]
Potentially with access to the url? Read and write? 🤔

**Comment by Frooxius** [comment]
Added in 2021.4.24.620 along with ITexture2DAssetMetadata, thanks! ^^
