### ISSUE TITLE
De-equip or store custom tooltips while switching tools in desktop mode

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2083]
## Is your tweak request related to a problem? Please describe.
Following up from #1906 - if a user is holding a custom tool, and they press a number key to select a development tool, the custom tool is destroyed with no means to undo/re-equip it.

## Describe what would you like tweaked
When equipping a tool with the quick-switch keys, the current tool could be de-equipped into the world.

## Describe alternatives you've considered
Storing the custom tool, and re-equipping with the (1) key.

## Additional context
Reported by RueShejn# 8897 after a tool swap caused him to inadvertently lose progress on the custom tool he was building.

**Comment by ProbablePrime** [comment]
I have a fix in review. Thanks

**Comment by Frooxius** [comment]
Merged in 2021.7.31.1211, thanks!
