### ISSUE TITLE
Logix Tip spawns Logix Node when grabbing logix relax and switching laser modes

### ISSUE THREAD

**Issue by SnooperXP** [Neos-Metaverse/NeosPublic#2084]
## Describe the bug
With a LogixTip equipped while grabbing and moving a relay with a laser, when you double tap the trigger to switch the laser to  switch the laser to "free move" (unsure what this mode is called, the orange turns from red to orange), the laser switches to this mode but the LogixTip also spawns whichever Logix Node is selected by the LogixTip.

## Relevant issues
I did not find any related issues open or closed with a quick cursory search.

## To Reproduce
1. Equip a LogixTip
2. Spawn out any two logix nodes that can be connected
3. Connect these nodes so that there is a logix link
4. With the laser, grab anywhere on this link to spawn a relay
5. Whilst grabbing to move this relay, double tap the trigger to switch the laser into the "free move" mode
6. Notice that the laser switches mode, but that a node is also spawned at the tip of the LogixTip

## Expected behavior
When switching laser modes while moving a logix relay, the logix tip does not spawn the selected Logix Node.

## Screenshots / Video
[![](http://img.youtube.com/vi/jOZojijGiyk/0.jpg)](http://www.youtube.com/watch?v=jOZojijGiyk "Neos VR - Logix Tip Free Move Bug Replication")

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Beta 2021.4.24.849
 - Neos Platform: Any
 - Regression: No

## Additional context
This is a minor inconvenience, however since my personal Logix workflow involved the use of many relays and being able to organize my logix to increase readability, this impacts me frequently.

As such, since it only seems to be impacting me, it should not be held at a high priority if it's a difficult issue to fix.

## Reporters:
```
Snooper#0001
```

**Comment by Frooxius** [comment]
Fixed in 2021.5.25.1225, thanks!
