### ISSUE TITLE
Desktop Mute Toggle

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2085]
## Is your feature request related to a problem? Please describe.
Desktop has a lot of open key buttons, having a keybind for toggling mute would be nice - M Key could be used to toggle mute

## Relevant issues
#320 could be used along side Push To Talk

## Describe the solution you'd like
Add a key bind for toggling the user's voice mode state to Mute. M is suggested. 

Could switch between Push To Talk - Mic Always on [Default] - Press To Talk in settings

## Describe alternatives you've considered
Switch the key to something else that's not currently binded to another function.

## Additional context
N/A

**Comment by AshtonSparx** [comment]
As of Neos Update 2021.8.2.936 We now have push to talk! :D My suggestion (Others can maybe tip in) could possibly double tap V to toggle between being muted and unmuted. While muted, hold V to speak as per normal.

**Comment by shiftyscales** [comment]
@AshtonSparx
As was mentioned on #320:
> Once we have UI for adjusting input bindings it will allow customization.
As well as in the patch notes:
> It's quite simple now and will have a bunch more added to it, but hopefully it'll help now as well.

This will not be prioritized until then, sorry. The current method was a quick implementation to cover some of the initial needs of those that have requested this feature.

**Comment by Frooxius** [comment]
Added in 2021.8.12.1293! I left it on the M key, I hope it doesn't make people mute themselves by accident though. If it does we can change it to something like Ctrl+M or something, but we'll see, let us know if you run into some issues!
