### ISSUE TITLE
Type IField<FloatQ> give invalid quaternion

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2087]
## Describe the bug
These specific components have invalid quartonion of (0;0;0;0) producing invalid results when using them.
A valid q would be (0;0;0;1)

Where T is floatQ
Bad quaternion:
Components such as ValueMultiplexer<T>, DataPresetValue<T>, DynamicValueVariableDriver<T>, UserDistanceValueDriver<T>, ValueUserOverride<T>, ValueMultiplexer<T>

UIX Slider<floatQ> Value and min are invalid, whereas Max and vibrationthreshhold is valid.

Good:
DynamicValueVariable<T>, BooleanValueDriver<T>

*This is an incomplete list. There's a possibility that there's more that don't do this correctly either. This is just a list that we found while scouring for about 5 minutes.*

Assumption is also that none of non-<T> are invalid but those of <T> are good.

## Relevant issues
Not found any.

## To Reproduce
1. Add any of these components
2. Inspect the values
3. They're invalid

## Expected behavior
For them to be valid quatornion. (XYZW should always add up to 1)

## Screenshots / Video
![grafik](https://user-images.githubusercontent.com/61988002/116030693-72504f80-a65c-11eb-9775-9144f16330ae.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.24.849
 - Neos Platform: Only tested on windows, expect to not work anywhere else.
 - Link to reproduction World/Item: -
 - Regression: Unknown.

## Additional context
[Add any other context about the problem here.]

## Reporters:
3x1t_5tyl3#0001, ukilop#4463

**Comment by Frooxius** [comment]
I've made the fields initialize to valid quaternion where possible in 2021.4.28.1415, but not every case can be accounted for as some are implicitly created and initialized. Some already had the initialization like DataPresetValue, so I'm not sure why did you see invalid one in those cases.
