### ISSUE TITLE
Desktop reticle texture set to repeat not clamp

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2092]
## Is your tweak request related to a problem? Please describe.
The desktop reticle looks janky as you can see the top of its texture at the bottom of it.
![desktopreticlerepeat](https://user-images.githubusercontent.com/60073468/116096085-44452c80-a6a9-11eb-9782-36ac8861f92f.png)

## Describe what would you like tweaked
Set its texture to clamp instead of repeat as the reticle should not repeat.

## Describe alternatives you've considered
Not doing this, which there is no reason for.

## Additional context
This same thing applies to ref arrows as noted in #1093

**Comment by Frooxius** [comment]
Tweaked in 2021.4.28.1415, thanks!
