### ISSUE TITLE
Inspector should show field names, not their types.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2093]
## Is your tweak request related to a problem? Please describe.
When looking at something like drive targets in an inspector, it is often tedious to figure out, where those go as they say what type they are but not the name of the field referenced.
The type is, in my opinion, almost completely useless since, if I got the name instead, I'd know what type it is since I'd know what exact field it is.

## Describe what would you like tweaked
Change the labels for referenced fields in an inspector to show the field's name instead of its type.

## Describe alternatives you've considered
Not doing it which just sounds less useful.

## Additional context
Here's an example of what I'm talking about:
I don't care that these are all some Sync`1, that doesn't tell me anything. If they had their names (Rotation, Scale...) it'd be way more useful.
![image](https://user-images.githubusercontent.com/60073468/116099332-26c59200-a6ac-11eb-896a-54e6990aea1c.png)

**Comment by Frooxius** [comment]
Added in 2021.4.27.1385, thanks!
