### ISSUE TITLE
Importing models with no armatures causes a crash on Linux

### ISSUE THREAD

**Issue by Frozenreflex** [Neos-Metaverse/NeosPublic#2096]
## Describe the bug
Importing models that have no armature on Linux crashes the game.

## To Reproduce
1. Export any model from Blender that has no armature, I've tested with FBX and DAE and they both crash.
2. Open the model and go through the import menu
3. When you press "start importing", the game will lock up and crash, sometimes it crashes before the import icon appears and sometimes after

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.24.620
 - Neos Platform: Linux

## Additional context
The error from player.log is attached.
 [error.txt](https://github.com/Neos-Metaverse/NeosPublic/files/6378912/error.txt)

## Reporters:
Fro Zen#8796

**Comment by Frooxius** [comment]
Can you give 2021.5.13.384 a try please? It includes latest version of Assimp from source.

**Comment by Frozenreflex** [comment]
Tested just now, I managed to import a bone-less OBJ just fine without crashing. Seems to have fixed the bug.
