### ISSUE TITLE
RandomBool LogiXNode

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2097]
## Is your feature request related to a problem? Please describe.
Not really. I just found a few different uses for it and thought to document it. This is fairly low priority tbh.

## Relevant issues
-

## Describe the solution you'd like
A LogiXNode that has:

- Input (float 0-1): Chacne between 0 (none) and 1 (all the time) to give a
- Output (Bool) true if input is constant 1

Example: If the value is set to 0.2 the "true" statement would fall 20% of the time and false 80% of the time.
Default should be 0.5 ergo "coinflip" odds

## Describe alternatives you've considered
Seperate logix though this would be nice to have as a native implementation.

## Additional context
-

**Comment by shiftyscales** [comment]
For what it's worth, you can already do this fairly easily at least, @3x1t-5tyl3.
![2021-04-27 18 59 19](https://user-images.githubusercontent.com/54213390/116334954-ec7ef200-a78a-11eb-86a9-7b8a90c8ffcc.png)

**Comment by Frooxius** [comment]
Added in 2021.4.28.1415!
