### ISSUE TITLE
The character moves forward and doesn't stop.

### ISSUE THREAD

**Issue by BARI0926** [Neos-Metaverse/NeosPublic#2102]
Hello, I am a Korean who started Neos vr for the first time.
This writing can be strange because it used a translator. I'm sorry.
When I log on to neosvr, I can't stop walking forward. Move your mouse and it'll come back.
I can't enjoy neosvr because I can't move freely. Please help me.

**Comment by Electronus** [comment]
Make sure you don't have a gamepad/ console controller connected!

**Comment by BARI0926** [comment]
ㅇ0ㅇ I didn't think about it at all.
Thank you very much for your help.
