### ISSUE TITLE
Favorited Avatars are not being favorited

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2106]
## Describe the bug
When trying to favorite an avatar, it doesn't try to Sync the favorite anymore. When you get respawned, switch worlds, your back to the last avatar you favorited before this started happen.

## Relevant issues
N/A

## To Reproduce
1. Favorite an avatar
2. Switch worlds/respawn
3. Behold. The avatar you didn't favorite.

## Expected behavior
Usually the cloud would sync the new favorite when you clicked it. But it doesn't anymore

## Screenshots / Video
Null

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes]
 - Neos Version: 2021.4.24.849
 - Neos Platform: Any
 - Link to reproduction World/Item: Null
 - Regression: Used to work before 2021.4.24.849

## Additional context
Null

## Reporters:
AshtonSparx#5050

**Comment by H3BO3** [comment]
Froox is aware of this issue and a fix will be present soon. Closing out this issue https://discord.com/channels/402159838827905024/439422161657135106/836611831064952872

**Comment by H3BO3** [comment]
Sorry, just saw conversation that this may still not be fixed. Reopening for further reports

**Comment by H3BO3** [comment]
Confirmed myself that this still appears to be broken.

**Comment by Frooxius** [comment]
Ooops, I messed up the type validation on those variables, should be good now, sorry for the inconvenience!
