### ISSUE TITLE
Deleting laser/related components no longer respawns user

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2107]
## Describe the bug
Deleting the slots required for use by lasers on an avatar will no longer respawn the user.

## To Reproduce
- Inspect your user root
- Remove/delete slots containing the laser components
- The laser can no longer be activated/the context menu can't be used and the player isn't automatically respawned

## Expected behavior
The user is respawned, or required components necessary to use the laser/context menus, are re-generated, or protected from deletion.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.24.849
 - Neos Platform: Windows
 - Regression: Yes, I believe this behavior might have broken around the time of the input system switch.

## Reporters:
Shifty# 7944, Vegasx# 0420

**Comment by Frooxius** [comment]
This is normal. This wasn't specifically a feature before, the user only gets deleted when an unexpected exception gets thrown in the core  update mechanisms, but not everything will do that and delete the user as a result.
