### ISSUE TITLE
ButtonValueShift "WrapAround" does not wrap around in reverse properly

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2108]
## Describe the bug
ButtonValueShift "WrapAround" does not wrap-around in reverse order when given -1 as delta instead it wraps around in the negatives instead of the given value range the user gives with the "min" and "max" values.

## Relevant issues
None

## To Reproduce
1. Use ButtonValueShift
2. Set the delta to -1 to go backwards
3. Enable "WrapAround"
4. Observe how it goes below the "min" value and becomes useless at this point.

## Expected behavior
WrapAround should go from min to max or max to min.
As this would be used to create "Enum" values. Or similar things.

## Screenshots / Video
![grafik](https://user-images.githubusercontent.com/61988002/116316379-257e8d00-a7b2-11eb-8059-c41bc93b6a81.png)
![grafik](https://user-images.githubusercontent.com/61988002/116316455-42b35b80-a7b2-11eb-8de4-5fa0a6149188.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.24.849
 - Neos Platform: Windows only tested
 - Link to reproduction World/Item: neosdb:///a39752a3aef293543a5c4bebd62d569a699131a57876865686fee20fbcd03cd8.7zbson
 - Regression: Unknown. But presumeably no.

## Additional context
-

## Reporters:
3x1t_5tyl3# 0001

**Comment by Aerizeon** [comment]
Currently, to make it work as expected, you have to invert the min and max fields. (and offset the max value)
![example](http://files.aerizeon.net/sharex/2021/2021-04-27_18-12-Neos_1XrlvhUsuK.png)

Similarly, when going in the opposite direction, the max value also has to be offset, but positively 
![example2](http://files.aerizeon.net/sharex/2021/2021-04-27_18-14-Neos_iudxecGLL9.png)

In both of these example cases, the range is [0,80]

**Comment by 3x1t-5tyl3** [comment]
> 
> 
> Currently, to make it work as expected, you have to swap the min and max fields, and offset the (now) max value.
> ![example](https://camo.githubusercontent.com/8fb7eecd0401153e556eb30d06266b16762a2fbb0585543ba432be7d618cb8c0/687474703a2f2f66696c65732e616572697a656f6e2e6e65742f7368617265782f323032312f323032312d30342d32375f31382d31322d4e656f735f3158726c76685573754b2e706e67)
> 
> Similarly, when going in the opposite direction, the max value also has to be offset, but positively
> ![example2](https://camo.githubusercontent.com/6116d8a5db295ac2bb877b39bdde24c9553be4de23eb8584995c4920ebac4681/687474703a2f2f66696c65732e616572697a656f6e2e6e65742f7368617265782f323032312f323032312d30342d32375f31382d31342d4e656f735f697564786563474c4c392e706e67)
> 
> In both of these example cases, the range is [0,80], but have to be defined as [-1,81] to function as expected.

I don't disagree that this is an option but this seems extremly convoluted and entirely unexpected behaviour still. And I'd rather have a proper fix than a bad workaround :P

**Comment by Aerizeon** [comment]
Oh no, I agree.
I was just placing this here to potentially help with debugging the issue, since it highlights how the button functions in practice.

**Comment by Frooxius** [comment]
Fixed in 2021.4.28.1415, thanks!
