### ISSUE TITLE
"Write Cloud Variable" node unable to write with "anyone" permission

### ISSUE THREAD

**Issue by Eearslya** [Neos-Metaverse/NeosPublic#2110]
## Describe the bug
If you attempt to write to a cloud variable that has a `write` permission of `anyone`, and provide a user ID other than your own, the node will pulse `OnWritten`, but the value will not persist to the cloud.
If you immediately perform a cloud variable read after writing, it appears that the variable is fetched from a local cache and will return the value you intended to write. However, waiting several seconds for the cache to invalidate and reading again will show that the cloud variable's value has not changed.

## Relevant issues
None.

## To Reproduce
1. Create cloud variable of any type.
2. Set all permissions (list, read, write) to "anyone".
3. Write to the cloud variable using the logix node, providing a `VariableOwnerId` that differs from your own user ID.
4. Wait 10-15 seconds.
5. Read the cloud variable. The result will contain the value of the variable prior to the attempted write.

## Expected behavior
As explained in the latest write-up, the "anyone" permission should mean "absolutely anyone can change anyone's value".

## Screenshots / Video
None.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.27.1385
 - Neos Platform: Windows
 - Link to reproduction World/Item: None
 - Regression: No

## Additional context
None.

## Reporters:
Eearsslya#7831

**Comment by Frooxius** [comment]
Who owns the created cloud variable definition? It it User or a Group?

As per release notes, User groups can only ever be mutated by the user owning the value. Group variables do not have this limitation:

-- User-defined variables cannot be written to by anyone else other than the user owning the value (in other words you cannot write value on behalf of another user). Group variables don't have this limitation

**Comment by Frooxius** [comment]
Additionally, how are you reading the cloud variable back? If you're reading it through command or on different instance, 10-15 seconds might not be enough, the propagation of writes is buffered and can take longer to reach other users.

**Comment by Eearslya** [comment]
Ah, that's my bad entirely. The variable I was testing was indeed a user-defined variable. I must have missed that bit of information.

In that case, I should probably open a new issue, as I believe the "Write Cloud Variable" node should be returning `OnFail` in this scenario.

As for the "cache" issue I was describing, I was still in the same session, I just used another "Read Cloud Variable" node. Even if the write fails permission checks, it still returns as if successful, and if you immediately use the Read node afterwards, the result returns immediately (which makes me think cache) and appears to be the value you erroneously wrote, until you try again several seconds later.
