### ISSUE TITLE
FogBoxVolume Material uses Scale of the Object instead of Transform (BoxMesh)

### ISSUE THREAD

**Issue by Mattyrogue** [Neos-Metaverse/NeosPublic#2115]
## Describe the bug
Discovered when trying to create a swimming pool using Procedural Meshes, attempting to create water fog the FogBoxVolume creates a 'negative fog within fog' when applied to a BoxMesh, as shown by a random occlusion artifact roughly the scale (1,1,1) of the object it inhabits.

This also has the side-effect of affecting ReflectionProbes, causing them to reproject the negative FogBoxVolume outside the volume itself against the render queue.

In order to eliminate this, the scale of the object has to be used as it's size instead of the Procedural Mesh BoxMesh's own inherent Size transforms.

This may have also have the same effect with StaticMeshes when used as non-standard geometry for a FogBoxVolume, further limiting its usage.

## Relevant issues
No relevance found.

## To Reproduce
1. Create a FogBoxVolume material.
2. Apply said FogBoxVolume material to a 1,1,1 scale BoxMesh
3. Change the size of the BoxMesh to a size larger than 1,1,1

## Expected behavior
The FogBoxVolume doesn't cancel out the BoxMesh's own FogBoxVolume in a 1,1,1 scale cube and instead adopts the size of the Procedural Mesh rather than becoming a visual artifact within the volume that both corrupts ReflectionProbes and also the surrounding FogBoxVolume.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/74799067/116484960-0e0ed500-a882-11eb-8a3f-5873579b9bdd.png)
![image](https://user-images.githubusercontent.com/74799067/116484881-e455ae00-a881-11eb-9545-e70274863c07.png)
![image](https://user-images.githubusercontent.com/74799067/116484893-e9b2f880-a881-11eb-81a8-b0339edc52cc.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.27.1385
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: No

## Reporters:
MattyK, Zandario, Groxxy (partially responsible for the discovery of this bug.)

**Comment by Frooxius** [comment]
This is expected behavior, you need to use it with box mesh that's [1;1;1] exactly for it to work correctly and instead scale the object itself using the transform. It cannot be used with any other mesh given how the fog rendering and the graphical pipeline works (it's not aware of spatial structure of the mesh).

**Comment by Mattyrogue** [comment]
Unfortunately, I was not aware of this expected behavior over the course of using it the past year or so (and had previously defaulted to simply trying to occlude the artifact), and FogBoxVolume's existence solely as a Material and not an Object in the New Object Creator would lead many to think otherwise. 

A better way to clarify it's function would be a 'Scale' Float3 within the component itself, with a target to point to.

Furthermore, there is no documentation about this interaction in the Neos Wiki.
