### ISSUE TITLE
Add an Asset Frame style component for world orbs

### ISSUE THREAD

**Issue by StarfishHidari** [Neos-Metaverse/NeosPublic#2118]
## Is your feature request related to a problem? Please describe.
When building systems to connect sessions together, it would be very nice if we could just drop a world orb onto a spot and we'd be able to get the session ID from that world orb. We can't really do that at the moment due to not having component access so we have to manually type in session ID's in order to make session connecting systems.

## Relevant issues
n/a

## Describe the solution you'd like
A component similar to an asset frame, that when a session orb is placed on it would grab the session url, or the world url, record url, etc. Basically providing information about the world that we can then interact with

## Describe alternatives you've considered
ref hacking stuff which isn't a good solution at all, and just manually typing in session url's

**Comment by mralext20** [comment]
probably best to be handled along with #933 - close as duplicate?

**Comment by Frooxius** [comment]
Yes, this would be handled more generally by #933
