### ISSUE TITLE
Cloud Variables wrong handling of Group Names with spaces

### ISSUE THREAD

**Issue by MR-Alex42** [Neos-Metaverse/NeosPublic#2125]
## Describe the bug
Spaces are not handled correctly when there are the only parameter in GroupVar statements.

## Relevant issues
None.,

## To Reproduce
1. The Neos user needs to be a Neos Group member.
2. The Neos user needs list permission for the Cloud Variable.
3. The Group name includes spaces.
4. Enter listGroupVars "Groupname" in AdminX console. Groupname has space character in it like "Virtual Germany".
Neos: Group doesn't exist.
5. Enter listGroupVars Groupname in AdminX console
Neos: Lists all Cloud Variables for the Group that the user has access to.

## Expected behavior
Neos lists the CloudGroupVars for Group names with spaces correctly.

## Screenshots / Video
Not required.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes.
 - Neos Version: 2021.4.29.1307
 - Neos Platform: Any.
 - Link to reproduction World/Item: Not required.
 - Regression: No.

## Additional context
Please  provide some naming conventions for Cloud Variables like possible path length and which characters are allowed.
Also provide examples how to pass values correclty like for a float3 you need to enter [1.0;1.0;1.0].

## Reporters:
AlienInArea51, MR-Alex

**Comment by Frooxius** [comment]
Since the command was only ever using one argument, it didn't require the quotes around the name, so `/listGroupVars Virtual Germany` would work.

I've changed the behavior so it's consistent with other commands now, thanks!
