### ISSUE TITLE
Cloud variable with variable_owner write permission can be written from the world

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2133]
## Describe the bug
Using the ActiveUser component variants, you can write a cloud variable which should only be written from the "safe" context (Dash)

## Relevant issues
None

## To Reproduce
1. Create a cloud variable with write=variable_owner perm
2. In the world (on your avatar), add a component ActiveUserCloudValueVariable and set it to use said var
3. Try changing the value of the variable

## Expected behavior
Value is discarded because it is written in the "unsafe" context

## Screenshots / Video
<img width="971" alt="Screenshot 2021-05-02 03 01 24" src="https://user-images.githubusercontent.com/675104/116797946-921bc380-aaf3-11eb-896d-358491e290ce.png">

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.29.1307
 - Neos Platform: Any
 - Link to reproduction World/Item: [Optional, but can speed up response for more complex reproduction cases]
 - Regression: Not sure, might be since the ActiveUser variants were introduced

## Reporters:
Shadow Panther#5154

**Comment by Frooxius** [comment]
Yes, it was specifically problem with the ActiveUser variants. Fixed in 2021.5.4.471, thanks!
