### ISSUE TITLE
Allow benefits of Patreon tiers without NCR

### ISSUE THREAD

**Issue by TiamatKefir** [Neos-Metaverse/NeosPublic#2134]
## Is your feature request related to a problem? Please describe.
No.

## Relevant issues
N/A

## Describe the solution you'd like
Suggestion to make "Non-NCR" versions of Patreon tiers, for people who do not want to handle cryptocurrency, but still want to support the team and receive other benefits such as storage. If the tier has an NFT tied to it, the "Non-NCR" version could have it removed as well, if it isn't viable to have one without the other.

## Describe alternatives you've considered
Having people ask the team personally to have NCR removed (after they receive) or omitted on pledge.

## Additional context
N/A

**Comment by Frooxius** [comment]
I'm sorry, but we don't plan on making this available. It's something we considered before, but it would cause significant amount of complications with Patreon, the integration and other related things.

We do plan on making options available to directly get storage and other benefits without Patreon though, we have an issue for that here: https://github.com/Neos-Metaverse/NeosPublic/issues/1616

However you do not have to handle cryptocurrency at all with Patreon, it goes into a Neos-managed wallet, removing any complexity from you.
