### ISSUE TITLE
Desktop reticle disappears when in use

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2135]
## Is your tweak request related to a problem? Please describe.
When right-clicking a lot in desktop without moving the mouse, the desktop reticle will disappear, forcing you to move the mouse before continuing.

## Describe what would you like tweaked
Make the desktop reticle disappear timer not only factor in mouse movement but also right-clicking.

## Describe alternatives you've considered
Keeping it like this which is annoying every now and then.

## Additional context
#2105 is basically this but already closed.

**Comment by Toxic-Cookie** [comment]
Not sure if it's a bug or not but I've also noticed that if the reticle disappears and you try to click or something to get it back, it doesn't come back. You have to move it for it to show up again.

**Comment by Psychpsyo** [comment]
> 
> 
> Not sure if it's a bug or not but I've also noticed that if the reticle disappears and you try to click or something to get it back, it doesn't come back. You have to move it for it to show up again.

I feel like that's alright since when it's gone you can't see where exactly you'd be clicking when it reappears.
