### ISSUE TITLE
Separate Group Worlds from Owned Worlds in World Menu

### ISSUE THREAD

**Issue by dotuser** [Neos-Metaverse/NeosPublic#2136]
## Describe what would you like tweaked
Split off worlds owned by a group you're a member of into their own tab or menu, or add the ability to filter them out.

## Additional context
It's gotten really difficult to find the few worlds I do own in two pages of one map with bad versioning from a group I am a member of, this made me think how helpful it'd be if we could.. Just hide group worlds, or move them to their own tab.

**Comment by Frooxius** [comment]
Filtering the worlds like this is already supported. Select "My Worlds" and then "Custom" to customize the filter. Then under "By Owner" put your username.
