### ISSUE TITLE
Pick Random LogiX node inputs not connecting to slots

### ISSUE THREAD

**Issue by RobertBaruch** [Neos-Metaverse/NeosPublic#2137]
## Describe the bug
In Logix, when the type of Pick Random node is Slot, the inputs do not want to connect to Slot interface cards.

## To Reproduce
1. In LogiX, spawn out a Pick Random node.
2. Spawn a Get Parent slot node, or any other node that takes in a slot. 
3. Connect the Pick Random node's output to that node's input. The Pick Random node should now be typed for Slot.
4. Spawn an interface card for any slot.
5. Attempt to connect the interface card's Slot to any Pick Random node's input.
6. Note that the connection cannot be made.

## Expected behavior
A reference to the slot is created and connected to.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.29.1307
 - Neos Platform: Windows
 - Link to reproduction World/Item: 
 - Regression: unknown

## Additional context
Workaround: Use any node that has a Slot input. Connect its input to the interface card Slot. Now connect the resulting reference to the Pick Random input. 

## Reporters:
Xekri

**Comment by H3BO3** [comment]
This is related to #2051 , could you post your findings there instead?

**Comment by RobertBaruch** [comment]
Done.
