### ISSUE TITLE
definition_owner should not be invalid for user cloud variables

### ISSUE THREAD

**Issue by Toxic-Cookie** [Neos-Metaverse/NeosPublic#2139]
## What topic do you want to discuss?
`"-- Write permissions on User-defined variable cannot be anyone or definition_owner anymore to reflect their limitations (Group defined variables do not have this restriction)"`

What the purpose of this is since the restrictions really narrow down the use cases since you either have to spend enough money to get groups, or use the *one* access type available.

There are several use cases where the average user would want to make use of this but can't due to the restrictions in place. For example, how would one create a user cloud variable to keep track of high scores in a game world and ensure that nobody is able to cheat?

## Goal of discussion
Figure out a suitable solution that keeps the average user in mind for their use cases as well.

## Discussion:
My first thought for a solution would be simply removing the restriction all together but I'm not sure how possible that is considering how things may work internally.

## Users that also share this concern:
- Epsilion
- DrFrank
- QueenHidi

Reference: https://discord.com/channels/402159838827905024/439421735474036738/837900388627513354

**Comment by Frooxius** [comment]
This is a security measure to prevent abuse of the system and causing issues in the infrastructure, as any user would be able to mass store values for every single other user in Neos. This permission level won't be made available to Users because of that. Groups are ok, because they are more gated. It does restrict the use-cases, but security and stability of the cloud infrastructure takes priority.

There are more fine-grained permissions coming in the next build, which will allow more scoped write access for Users too - e.g. being able to write value to other users, but only if they're your contact. This will allow for more use-cases for user variables, while also keeping restrictions to prevent run-away abuse of the system.

**Comment by Toxic-Cookie** [comment]
Yeah that makes sense. Thanks for explaining!

**Comment by Frooxius** [comment]
2021.5.4.471 added new permission levels which should add a lot more flexibility to User defined variables: 

- Added allowUserCloudVariable configuration option for auto-startup/headless worlds which allows using cloud variable to always allow user into a session (based on the same request above)
-- The cloud variable needs to be of type bool and set to true for given user
-- This is equivalent of the user being sent an invite - they can join regardless of MaxUsers limit and even if the session is set to Private (they need to obtain)
-- Same recommendations as above apply, please make sure you use the right cloud variables that you have proper control over
- Added new cloud variable permissions to provide more flexibility (this resolves some issues brought up by @Epsilion, @DrFrank, @Robyn (QueenHidi), @Toxic_Cookie and others)
-- definition_owner_only and definition_owner_only_unsafe
--- These mean that the variable value can only exist (and be written to) by the owner of the definition (meaning other users cannot have a value at all), making it useful for "central" annoucement variables
--- These permissions work with User defined variables as well
-- definition_owner_only_contacts and definition_owner_only_contacts_unsafe
--- The variable value can be written to only by the definition owner for any user who is an accepted contact of the definition owner
--- This permission is valid only for User defined variables and allows for the tagging use-case of cloud variables without needing a group
-- variable_owner_only_contacts and variable_owner_only_contacts_unsafe
--- This allows anyone who is a contact of given value owner to read/write given value (meaning your contacts can read/write your value)
--- This is valid permission for both User and Group variables
