### ISSUE TITLE
GravitySpace always in Global Space under user

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2142]
## Describe the bug
DynamicBoneChains that are under a user will always have theri gravity calculated in global space when under a user.
E.g. the hair on my avatar will shift downward further the smaller I am.

## Relevant issues
None I am aware of.

## To Reproduce
- Grab an object using a DynamicBoneChain with the GravitySpace set to Local Space or Parent Space
- Observe the object's gravity shifts to the same position as if it were using Global Space

## Expected behavior
- The object should respect the GravitySpace regardless of whether it's under a user or not

## Screenshots / Video

https://user-images.githubusercontent.com/54213390/116837033-a60c0780-ab7d-11eb-9e8f-4ca578244c4e.mp4

https://user-images.githubusercontent.com/54213390/116836874-22eab180-ab7d-11eb-9ff8-1fce4e588efa.mp4

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.29.1307
 - Neos Platform: Windows
 - Link to reproduction World/Item: neosrec:///U-Shifty/R-6482e691-475c-4d00-a6bc-d5d79bbd8b67
 - Regression: No

## Additional context
I had first noticed this issue as anytime I would scale my avatar down, my hair would sink into my eyes. Afterward, I investigated and discovered setting the GravitySpace should account for this, but doesn't while the DynamicBoneChain is under a user root for some reason.

## Reporters:
Shifty# 7944

**Comment by Frooxius** [comment]
This is intentional, there's a property UseUserGravityDirection that overrides the space based on the user's current gravity/space. This is so in worlds with radial or flipped gravity, the dynamic bones automatically pick it up and move appropriately.

Try unchecking this option, which should make the gravity behave the same when it's under user and when it's not.

**Comment by shiftyscales** [comment]
Thanks for clarifying!
