### ISSUE TITLE
Cloud Variables of String return null if more than 256 characters written

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#2143]
## Describe the bug
I wrote a sequence of 257 characters Cloud Variable of String:8192, which succeeded - however, when trying to read back this variable, a Null string is returned, even though `OnRead` is fired.
**While I was experimenting with this bug, I seemed to change the functionality slightly, see below for more information**

## To Reproduce
1. Create a Cloud Variable:
 * Type: String:8192
 * Read: anyone
 * Write: variable_owner_unsafe
2. Use WriteCloudVariable\`1 Node to write 256 characters to the variable defined in (1)
3. Use ReadCloudVariable\`1 Node to read the variable defined in (1) - note that it fires `OnRead` and returns the correct string.
4. Use WriteCloudVariable\`1 Node to write 257 characters to the variable defined in (1)
5. Use ReadCloudVariable\`1 Node to read the variable defined in (1) - not that it fires `OnRead`, however it returns a NULL string

**While I was experimenting with this bug, I seemed to change the functionality slightly**
I changed the variable type to `String` and then back to `String:8192`

Now, WriteCloudVariable\`1 triggers `OnFail` for lengths greater than 256, even if the variable is defined as `String:8192`, however setting the string to be 257 characters or more through the Neos Bot causes ReadCloudVariable\`1 to fail in the manner indicated above (with a null result)

## Expected behavior
[A clear and concise description of what you expected to happen.]

## Screenshots / Video
![Example](http://files.aerizeon.net/sharex/2021/2021-05-03_03-10-Neos_stcjKM0Apb.png)

## Bug information (please complete the following information):
 - How often does it happen: Sometimes
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.29.307
 - Neos Platform: Windows
 - Regression:  Unsure

## Reporters:
Epsilion

**Comment by Frooxius** [comment]
Fixed in 2021.5.4.471, thanks!

**Comment by Toxic-Cookie** [comment]
I had this happen to me when I was experimenting! I knew I wasn't crazy! I'm glad this is fixed now.
