### ISSUE TITLE
User head output device is not set to screen when switching from VR to desktop.

### ISSUE THREAD

**Issue by Toxic-Cookie** [Neos-Metaverse/NeosPublic#2144]
## Describe the bug
The title

## Relevant issues
No.

## To Reproduce
1. Enter VR.
2. Get out of VR and switch to desktop.
3. Notice that head output device still reports VR.

## Expected behavior
When switching from VR to desktop, the output device should be accurate.

## Screenshots / Video
None.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 4.29.1307
 - Neos Platform: Any
 - Link to reproduction World/Item: None
 - Regression: No.

## Additional context
None.

## Reporters:
Toxic_Cookie#8064, Rukio, Shifty

**Comment by Frooxius** [comment]
It's not supposed to, this property indicates the device mode that Neos was initialized with, it's not a dynamic value.

As per release notes, you should use the "User VR Active" node to determine if the user is currently in VR or in screen. Using HeadOutputDevice is generally not recommended for anything.
