### ISSUE TITLE
Quad Mesh: UV Offset doesn't work on Back side when Dual sided

### ISSUE THREAD

**Issue by ukilop** [Neos-Metaverse/NeosPublic#2145]
## Describe the bug
As title says, the UV Offset field on a QuadMesh doesn't work on the back side of the quad when set to dual sided
## Relevant issues
Couldn't find any.

## To Reproduce
Give a material with a texture to a Mesh Renderer that is using a QuadMesh.
Apply UVOffset to QuadMesh. it works.
set quad to dual sided.
UVOffset does nothing to the back side

## Expected behavior
For UVOffsets on QuadMesh to be applied to both sides
## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 4.29.1307
 - Neos Platform: Windows
 - Regression: not sure

## Reporters:
ukilop and 3x1t-5tyl3
(sorry this issue posted with title only initially, accidently hit enter when typing title)

**Comment by ukilop** [comment]
... imminently getting mixed results after more testing. trying to figure this out.

**Comment by Frooxius** [comment]
Fixed in 2021.5.5.159, thanks!
