### ISSUE TITLE
Logix Node Idea: +/-

### ISSUE THREAD

**Issue by ukilop** [Neos-Metaverse/NeosPublic#2146]
## Is your feature request related to a problem? Please describe.
semi-frequently Ive been have annoyances with editing/setting up a particular pattern of logix,
a pattern in which 2 value are needed, both values being offset from either 0 or another value by the same amount just one positive one negative.

## Describe the solution you'd like
It would be nice if we had a single logix node to accomplish this, both for ease of setting up and for editing.
I made a quick mock up for visual explanation:

![2021-05-03 01 16 36](https://user-images.githubusercontent.com/1341270/116857250-1ccaf400-abc2-11eb-97ad-77d932065d7a.jpg)

In this example, the first input being X and second input being Y,
the first output would be X+Y
and second output being X-Y
It would also be nice if this node would work for packed values like a float3

suggested defaults to these inputs being 0 for both

Idea by KierDran and Ukilop

**Comment by Frooxius** [comment]
Added in 2021.5.4.471, thanks!
