### ISSUE TITLE
Move the Local Database and Cache to the Steam program folder

### ISSUE THREAD

**Issue by H3BO3** [Neos-Metaverse/NeosPublic#2147]
## Is your feature request related to a problem? Please describe.
Users do not understand how the local DB operates by default. This has resulted in a lot of issues where people cannot find it on their own and are confused when a reinstall does not fix things. Here is a list of the advantages this would have:

- The DB/cache would always be in the same install location as the game itself, letting people implicitly manage where those directories are. This way, people would be more considerate of drive space, especially without knowing Neos is just going to take a lot of space on their OS drive by default.
- A reinstall of the game would delete the DB/cache, causing the game to actually reset instead of just using the same file. I have personally answered over a dozen questions since the recent database upgrade a few months ago, all of them requiring a database reset because the upgrade broke and caused Neos to just close whenever it was loaded. Many of these people attempted to reinstall the game, but it did nothing because the same broken files were still being loaded. It's hard to say how much damage this has caused for people trying to return to Neos after some time but the game just wouldn't start for them. The people who join and ask in the discord are the ones who actually figure something else is probably going on, and there have been a LOT of them.
- People can more easily find the DB/cache for clearing or reset if they so desire, since everything is contained within a single directory.

## Describe the solution you'd like
Have the local database and cache be kept inside the steam application folder. 

## Describe alternatives you've considered
- For the DB upgrade process to be more robust, including auto-resets if load failure is detected (This would be a good idea regardless)
- Better exposure of the DB/cache to be presented to the user, including in-game interfaces to move and reset it

## Additional context
![Screenshot_416](https://user-images.githubusercontent.com/62123804/116911324-f2018f80-ac03-11eb-98bc-7ab9cdec5b61.png)

**Comment by Frooxius** [comment]
This won't be implemented, Steam install location should not ever be used for user data like this, you never want your user data be stored with your software installation.

E.g. your example with it being deleted when you reinstall Neos - this is a very bad thing to do. Imagine loosing all your Unity projects when you reinstall Unity.

The database is in the right place it needs to be for standard Windows applications, we will not move it.

If users are having trouble clearing it up, then we should update tutorials or add some shortcuts/utilities for that instead.
