### ISSUE TITLE
Local Database Automatic Reset

### ISSUE THREAD

**Issue by H3BO3** [Neos-Metaverse/NeosPublic#2148]
## Is your feature request related to a problem? Please describe.
Currently if the database gets corrupted due to a failed upgrade, Neos simply refuses to start and closes itself.

## Relevant issues
Continuing from #2147 , where I detail having to answer many questions related to this and the damage this is likely causing to users who can't return to Neos because it won't start for them, and who don't take the incentive to investigate further

## Describe the solution you'd like
If a startup failure or read failure is detected, Neos automatically backs up the current database file and starts a new one, essentially refreshing the whole system.

**Comment by 3x1t-5tyl3** [comment]
Related to #58

**Comment by Frooxius** [comment]
This is already implemented and the database will reset/repair when possible. However given the nature of bugs it's not possible to account for every potential breakage. We need logs and diagnostics to determine what went wrong and make corrections. Do you have any cases where the reset wouldn't work?

**Comment by H3BO3** [comment]
Only by subject, @3x1t-5tyl3 

@Frooxius This does not work way more times than is comfortable, given the 19+ times I had to relay information for a manual reset to users whose game just wouldn't start. The most common sign I saw was that Neos closed itself on the Initializing AudioSystem stage. https://discord.com/channels/402159838827905024/439421735474036738/837769273148833812
I presume it's not actually the AudioSystem, but what occurs right after. In every case of this, resetting the database fixed it.

My instinct is to NOT ask the user just wanting to start the game for a bunch of debug information when I know exactly what the problem is, but I can try on the next one if they are alright with it, since I am confident there will be one. My point is that there needs to be a robust failsafe that catches this behavior and automatically performs a reset for them.

**Comment by Electronus** [comment]
I will also try to get some debug information. I do not care to guess how many users I have had to tell to reset their database, for various reasons, even those who has just installed the game.

**Comment by Frooxius** [comment]
@H3BO3 I understand that, but I still need information about what went wrong so I can actually make changes to prevent it. There already are failsafes in place, but there's also lots of things that could go wrong too. Without understanding what went wrong (it might have nothing to do with the database in the first place) I won't be able to fix it or add failsafes for it.

**Comment by H3BO3** [comment]
I will attempt to gather logs and information from a player having trouble the next time I see it. How much information is necessary @Frooxius ? Do you need unity logs, Neos logs, potential crash dumps, etc?

**Comment by Frooxius** [comment]
As much as you can get. Ideally both Unity and Neos logs. If there is crash, get the crash dump as well. Anything that happened too. Everything that helps narrow it down to something specific, because right now it's more realm of "There's a bug somewhere in the database system or maybe in some other subsystem that's somehow related" and that's not really something very actionable.

**Comment by H3BO3** [comment]
@shiftyscales Yes, most of these people are returning users who haven't played for at least a few months, which lines up with the time of the DB upgrade. However, none of them have mentioned a database upgrade, or forcing Neos to close, it always just did it on its own. I would have remembered if they had. I've encountered what could be a few anomalies with Neos not starting in a similar manner despite it having been their first time? Or so they say. But I haven't pried into that kind of info.

**Comment by Frooxius** [comment]
I think it's probably not the repair process. Generally even if you stop that mid-way, Neos will start next time, but you'll just be missing some data.

Does this always primarily affect users who haven't played in a while? It might very well be something going on with the DB upgrade process that breaks things.

**Comment by H3BO3** [comment]
@Frooxius That's the pattern I've been noticing. The common scenario goes - "Hey, I haven't played Neos for a few months/a year/some time occurring before the DB encryption upgrade. Neos closes once it gets to Initializing AudioSystem." I give them the database reset instructions and it always fixes it for them. Here is a video of someone attempting to start Neos in this scenario https://discord.com/channels/402159838827905024/439421735474036738/837769273148833812

**Comment by Frooxius** [comment]
@H3BO3 I see. Unfortunately the video isn't really sufficient, I'd still need the logs from that case to see what's going on. Might be something odd with the upgrade process, but hard to tell what.

**Comment by H3BO3** [comment]
I've reached out to the most recent player with this issue that I helped, hopefully in time to get the unity logs. I'll ask the next user who has this problem for their information as well, will update when I have something

**Comment by H3BO3** [comment]
I have collected logs related to this issue with relevant exceptions located in the Player.log files. DMed to Frooxius.

**Comment by Frooxius** [comment]
Thanks! I found the culprit, it actually doesn't have anything to do with the database itself, but rather an upgrade process for audio settings got broken after the API was changed to async/await, so none of the database corruption detection methods got triggered (because the DB wasn't corrupted).

I've got a fix coming in the next build.

**Comment by Frooxius** [comment]
Fixed released in 2021.5.4.471! This should fix cases of users who haven't played in a while not being able to launch Neos, since it would affect everyone who last launched before the new desktop mode, before the audio settings were reworked, but after the database API was fixed.

Feel free to open more issues if users run into other problems at startup.

**Comment by H3BO3** [comment]
Very neat! I'll keep an eye out for further forms of this behavior cropping up
