### ISSUE TITLE
Desktop can't set ProfileImage

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2154]
## Describe the bug
As a title says, Desktop mode can't se ProfileImage after implement current desktop mode.

## To Reproduce
1. Spawn Images whatever setting profile photo.
2. Try to set Image through SimpleProfileFacet.
3. can't set image after spawn this facet as new facet or put default facet that shows as Home.

## Expected behavior
set profileimage correctly.

## Screenshots / Video
![temp_Set Photo](https://user-images.githubusercontent.com/6259214/117002886-19994a80-ad1f-11eb-996e-be9e454d138b.png)

## Bug information:
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.4.471
 - Neos Platform: Any
 - Link to reproduction World/Item: SimpleProfileFacetPrecet in Neos Essential/Facets
 - Regression: Yes, before implement current desktop mode.

## Reporters:
kazu ( Discord: kazu#7215 ) / Holy_Water ( Discord: Holy#1824 ) / ChameleonO2 ( Discord: ChameleonO2#6665 )

**Comment by Frooxius** [comment]
This simply hasn't been implemented yet, but it's planned.

**Comment by Frooxius** [comment]
This is now possible thanks to change in 2021.7.21.402, which keeps grabbed items held while dash is opened!
