### ISSUE TITLE
CurrentRoleLevel LogiX Node

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2157]
## Is your feature request related to a problem? Please describe.
It's currently required to "ToString" a user to get a role which is inconsistent (and as of 2021.5.4.471 not possible for host specifically).
![grafik](https://user-images.githubusercontent.com/61988002/117030647-222e5880-ad00-11eb-914b-4943f378e25d.png)

Thus creating issues when wanting to code stuff with roles in mind.

## Relevant issues
#670 ?

## Describe the solution you'd like
"CurrentRole" logix node which would go from 0 to 5 (or higher if more get added in the future?)
0 Admin
1 Builder
2 Moderator
3 Guest
4 Spectator

This could aid in tool creation to allow tools to not be used until a level high enough is given (as an example) or give the user a way to tell what their current role is on their own UI's or similar. This could further aid in users wishing to display their current role to indicate that they're currently in build mode or similar.

## Describe alternatives you've considered
Checking the users "Role" through stringing the user.

## Additional context
-

**Comment by Frooxius** [comment]
Sorry this won't be implemented, as it's inherently unsafe. You should never, ever base your security or permission roles on a check like this.

The permission system works by doing validations and checks at the data model level and it's designed to it can be made more robust and configurable over time, so anything to do with permissions will be implemented that way. Doing the checks in the items can easily be bypassed by just removing the check.

Additionally you can't use indexes like that. Each world configures permissions differently and they can potentially have different numbers of roles too, which would break any security you base on this (if it wasn't inherently broken anyway).

https://github.com/Neos-Metaverse/NeosPublic/issues/1487
