### ISSUE TITLE
Name Bone Collider Slots "<Body Part> Collider"

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#2158]
## Is your tweak request related to a problem? Please describe.
Users when importing avatars are noticing the Colliders which are added to various body bones and mistaking them as extra/duplicated bones within their rig. This can cause confusion

## Describe what would you like tweaked
If the automatically generated Bone Colliders could be named "`<body part> Collider`" it might be clearer that these parts are just colliders and not actually bones.

## Describe alternatives you've considered
Additional documentation about these slots, I'll do this anyway :)

## Additional context
https://discord.com/channels/402159838827905024/439421735474036738/839233245983539275 is the most recent occurrence but I see it once in awhile.

**Comment by Frooxius** [comment]
Changed in 2021.5.6.453, thanks!
