### ISSUE TITLE
Permissions component that controls visibility of slots for given permission levels

### ISSUE THREAD

**Issue by StarfishHidari** [Neos-Metaverse/NeosPublic#2159]
## Is your feature request related to a problem? Please describe.
I would like to be able to make it so that only people at certain permission levels (i.e; builder and above) can see certain objects in my world. As an example I have a control panel that I would like only builders and above to be able to see, while it would be hidden for anyone that does not have that role level.

I would like to be able to provide a slot to a permissions component, similarly to how touchable permissions work, and be able to drive it's visibility using that. Being able to use a tag system like with touchables could be nice as well.

Originally I assumed I would be able to do that with logix but realized there isn't a way to get a user's permission level, and after reading #2157 and #1487 I understand that would be incredibly insecure and isn't a good way of going about it.

So would working this functionality into the permission system work better and avoid the security concern?

## Relevant issues
#2157
#1487

## Describe the solution you'd like
A permissions component that when provided either a slot or tag could control whether a given permission level can see that slot (meaning it would locally disable that slot for them). I assume this would also mean it would have a whitelist/blacklist function similar to how the touchables permission component work.

## Describe alternatives you've considered
Using cloud variables to control who can see things, but that is a bit more clunky to use to do what I want.

**Comment by 3x1t-5tyl3** [comment]
This seems to be a thing for after hard permissions? #289

**Comment by Frooxius** [comment]
I'm sorry, but this won't get implemented either for same reasons - it's fundamentally insecure. All permissions handle security by independently validating the changes and behaviors from the actual content, so no matter what happens with the content itself, the permission can ensure its behavior. If it's just a check like that, it cannot be made properly secure and you should never build security systems in such manner.

**Comment by shiftyscales** [comment]
Additionally, this could also already be implemented by utilizing the "Is User In Edit Mode" Logix node to create things that are only displayed while in Edit Mode which is only accessible to builders, @StarfishHidari.
