### ISSUE TITLE
UI camera can focus on context menu

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2160]
## Describe the bug
The UI camera can focus on the context menu while it is opened, and upon closing and reopening it will send the camera into the distance an increasing amount each time. The camera can be restored by exiting the UI camera.

## To Reproduce
- In desktop mode, open the context menu
- Focus the context menu with the UI camera key combination
- Close and re-open the context menu
- Eventually the camera will begin to fly off in the direction the context menu is opened
(This occurs most reliably when looking straight down.)

## Expected behavior
The context menu should not be focusable, or the focus should clear when the context menu closes.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.4.471
 - Neos Platform: Windows
 - Regression: No, newly introduced behavior with the UI camera

## Additional context
Not a high priority since it can be escaped by exiting the UI camera mode.

## Reporters:
Shifty# 7944

**Comment by Frooxius** [comment]
This is no longer possible in 2021.5.6.453!
