### ISSUE TITLE
Laser unable to interact with UIs in UI camera mode if opened from the back

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2162]
## Is your tweak request related to a problem? Please describe.
If you activate the UI camera from the back side of a UI, e.g. inspector, or node browser, you are unable to interact with the UI because the avatar's lasers hit the back side of the UI, requiring the user walk around to the front of the UI.

## Describe what would you like tweaked
If the user's lasers could be moved to the camera position, or if they could be relayed from the perspective of the camera, it would ensure UIs are more reliably interactible regardless of the position they were focused from.

## Describe alternatives you've considered
Teleporting the avatar into a fixed position in front of the UI while focusing on it.

## Additional context
You can also run into this issue if your avatar is moved by any means.

**Comment by Frooxius** [comment]
This now works in 2021.5.6.453!
