### ISSUE TITLE
Locomotion not blocked while in UI camera

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2163]
## Is your tweak request related to a problem? Please describe.
While in the UI camera mode, the player can move around, creating potential issues such as #2162.

## Describe what would you like tweaked
Lock the player's locomotion while in the UI camera to ensure they will be in the same position when they exit the mode.

## Describe alternatives you've considered
Resolving #2162 by moving the laser position to be relative to the camera would mean this is less of an issue.

**Comment by Frooxius** [comment]
This is simply not implemented yet, it's coming in the next build.

**Comment by Frooxius** [comment]
This has been implemented in 2021.5.5.159 now!
