### ISSUE TITLE
Disable player scaling while moving UI camera

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2165]
## Is your tweak request related to a problem? Please describe.
If the user has scaling enabled, and they zoom the camera in/out with the control + scroll binding, their avatar will scale with the same input.

## Describe what would you like tweaked
Disabling/suppressing user scaling while moving the UI camera/in the UI camera mode.

## Describe alternatives you've considered
The user disable scaling prior to entering the UI camera mode

**Comment by Frooxius** [comment]
This is same as this: https://github.com/Neos-Metaverse/NeosPublic/issues/2163 It's part of locomotion system.
