### ISSUE TITLE
Default new texture 2d resources to clamp instead of wrap

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2167]
## Is your tweak request related to a problem? Please describe.
I often see blending artifacts around the edge of transparent photos when they have wrap enabled, due to what I think is the picture wrapping from a transparent side to a non-transparent side.
This also happens with non-transparent images, but it is the most noticeable with transparent.

To my knowledge while wrap is commonly a useful setting with walls and structures, for avatars and photos I believe wrap may be an unexpected behavior that results in some small artifacts along the image edge when looking at it from farther than a few feet away.

## Describe what would you like tweaked
For photos taken in Neos, and for imported textures, set the repeat mode to clamp, instead of wrap by default.

## Describe alternatives you've considered
Leave it as is, which results in visual artifacts along the sides of images when looking from far away. 

Have cameras be able to set the wrap on captured photos, however this does not resolve the issue for imported photos, which are often people's personal photos where wrap would not be applicable.

Have importing a picture prompt for wrap or clamp, but this may result in excessive button pushing.

## Additional context
Doing this only with photos may be a good resolution as well, but it is quite common that I see artifacts along the edge of photos and users are unaware that the clamp/wrap difference resolves the issue.

This make make it less straightforward to import repeating textures, as users who do not know about the setting may be confused.

**Comment by ProbablePrime** [comment]
I would agree with Photos, but I would not agree for textures. 

Having textures clamp can lead to oddities in materials.

**Comment by Earthmark** [comment]
I figured with avatars and complex uv wrapped objects clamp would be valid, do avatars and such expect wrap?

**Comment by ProbablePrime** [comment]
Avatars usually not, But lots of terrain, furniture, walls etc would have detrimental changes here.

**Comment by Frooxius** [comment]
Clamp definitely shouldn't be the default for textures, since a lot of things rely on Wrap instead and it's pretty standard default behavior across engines. Often textures can be tiled or mirrored.

Typically for things like sprites and photos we can set it to Clamp, but we should do that only in cases where we know that it's desired behavior.

**Comment by Earthmark** [comment]
Sweet, the main goal of this was to resolve the cases I've seen of cutout photos having an odd border from wrap-around, as the wrap artifact is very noticeable from the rest of the area being transparent.

Would it be viable for cameras to have a checkbox to take clamp instead of wrap photos then? 
As an additional thing, have the default camera use that option, or have it be a configurable option?

**Comment by H3BO3** [comment]
maybe just photos could be set to clamp? no need to do it to all textures

**Comment by Earthmark** [comment]
I figure it's not really possible to figure out what's a photo and what's a normal texture, so I figure go by where the texture is from.

**Comment by H3BO3** [comment]
neos can just set the type after the photo gets taken, I don't know if old photos could be upgraded

**Comment by Frooxius** [comment]
Yeah we can just set it on photos when it's taken, I'll add that in the next build! If you find more things that should have clamp by default specifically and currently don't, let me know and I'll see if I can set them to be so!

**Comment by Psychpsyo** [comment]
One other thing that should have clamp by default is Logix arrows, as mentioned in #1093

**Comment by Frooxius** [comment]
Ok they should be clamp now! Thanks! The LogiX is a separate issue.

**Comment by Psychpsyo** [comment]
Just noticed that the Fly mode visual isn't clamp either:
![image](https://user-images.githubusercontent.com/60073468/119537503-64403c80-bd8a-11eb-8238-c461fa8e572f.png)

**Comment by shiftyscales** [comment]
If you wish to report this, please do so as a new/separate issue rather than as a comment on an old issue, @Psychpsyo.

But on a similar issue #1093 Frooxius has noted:
> Yes, this is a known issue, but hasn't been prioritized. The textures need to be switched to Clamped in a bunch of different places to avoid these artifacts. The whole LogiX visuals are planned to be reworked at some point in the future, so it might not really get fixed for this version since it doesn't technically break anything.
