### ISSUE TITLE
When I turned on the Neos vr on Steam and tried to enter it, the screen came out for a while and then turned off. How do I do it?

### ISSUE THREAD

**Issue by gamegame233** [Neos-Metaverse/NeosPublic#2169]
### Describe the bug
When I turned on the Neos vr on Steam and tried to enter it, the screen came out for a while and then turned off. How do I do it?

## Relevant issues
[Did you find any existing issues relevant to this one? If you found the same issue, please contribute to that one instead of making a duplicate.]

## To Reproduce
[Steps to reproduce the behavior:
4. See error]

## Expected behavior
[A clear and concise description of what you expected to happen.]

## Screenshots / Video
[If applicable, add screenshots or a video to help explain your problem.]

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: [version number]
 - Neos Platform: Windows
 - Link to reproduction World/Item: [Optional, but can speed up response for more complex reproduction cases]
 - Regression: Did this work before? Yes 

## Additional context
[Add any other context about the problem here.]

## Reporters:
[Usernames / Discord handles of anyone (including yourself) who has reported/replicated this bug (will be used to credit in release 
[DESKTOP-OQTFSD4 - 2021.5.5.159 - 2021-05-05 19_12_59.log](https://github.com/Neos-Metaverse/NeosPublic/files/6426438/DESKTOP-OQTFSD4.-.2021.5.5.159.-.2021-05-05.19_12_59.log)

**Comment by H3BO3** [comment]
Dealing with this issue in DM and walking through standard troubleshooting procedure, and collecting Unity logs in case of further database issues.
