### ISSUE TITLE
Camera Movement while "zoomed" in: scales with userscale instead of objectscale

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2170]
## Describe the bug
Camera movement speed with ctrl+right click scales with userscale.

## Relevant issues
#151

## To Reproduce
1. Scale yourself smaller or bigger
2. Focus any uix canvas
3. Try moving around while scaling yourself (or while scaled at all)

## Expected behavior
It should move dependant on object scale not Userscale

## Screenshots / Video
-

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.5.159
 - Neos Platform: Windows
 - Link to reproduction World/Item: -
 - Regression: No regression

## Additional context
-

## Reporters:
3x1t_5tyl3# 0001

**Comment by Frooxius** [comment]
This is intentional, object scales differ wildly and would cause a lot of inconsistency to the movement speed. Having them related to user scale keeps it more consistent. You should generally be at the scale you want to edit at.
