### ISSUE TITLE
Make ESC leave blitted to display texture

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2179]
## Is your tweak request related to a problem? Please describe.
The SendToDisplay tip is useful for watching videos on desktop but currently, when a texture is blitted to display, pressing ESC opens the dash behind it with no indication of it.

## Describe what would you like tweaked
ESC should instead un-blit the texture from the display (what secondary does as well currently)

## Describe alternatives you've considered
Keeping it like this which can be confusing or just making ESC not open the dash which would also fix the issue of getting stuck with a texture blitted to display and no way out cause there is your open dash behind it.

**Comment by Frooxius** [comment]
I'm sorry, this is not possible, the blitting component is more low level than that and used as internal mechanism for other systems, so it doesn't integrate with user input like that. I'd recommend to not use the SendToDisplay tip, as it's likely to be just removed at some point and use the UI aligned camera instead.

**Comment by Psychpsyo** [comment]
Then it'd be nice if the UI aligned camera was able to zoom in on video players instead of just zooming out so we can make them cover the entire screen.

**Comment by Frooxius** [comment]
You should be able to zoom in on those. Are the players perhaps very small? There's a limit on how close you can get at the moment.

**Comment by Psychpsyo** [comment]
Thanks, that was the issue.
