### ISSUE TITLE
Focusing UI camera on a held object will change focus to grabbing user's hand after the object is released

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2180]
## Describe the bug
If a user focuses their UI camera on an object that is being held by another user, their perspective will shift to the grabbing user's hand if the user releases the object the camera was focused on.

## Relevant issues
None I'm aware of.

## To Reproduce
- Have a user grab a focusable object e.g. a photo
- Focus the UI camera on the object held by the other user
- Have the user release their grab and drop the focused object

## Expected behavior
The camera view would remain focused on the held object.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.5.159
 - Neos Platform: Windows
 - Regression: No

## Additional context
Discovered by accident when focusing on a photo that was being laser-held by German gunner (SketchStorm-8# 0527). The UI camera can still be exited as normal to re-focus the camera on the object to work around this issue if it comes up.

## Reporters:
Shifty# 7944, German gunner (SketchStorm-8# 0527)

**Comment by Frooxius** [comment]
This has been fixed in 2021.5.6.453!

**Comment by shiftyscales** [comment]
This appears to still be an issue, sorry. I checked with Aegis_Wolf# 5227 after a report from MattyK# 8239 and Kiovo# 5446, and it occurs with both physical grabbing and laser grabbing.

By the look of things, the camera is anchored to the parent space of the UI that is focused on (e.g. Aegis' hand) so the instant he lets go, the camera maintains its same relative position to his hand.

**Comment by Aerizeon** [comment]
This also occurs when the object is destroyed while being held by another user.
