### ISSUE TITLE
[Desktop Mode] Dashboard limitations (drag & dropping of images/objects)

### ISSUE THREAD

**Issue by strchsr** [Neos-Metaverse/NeosPublic#2181]
**Description:**

Desktop users cannot modify their Neos profile picture, or drag objects to their Inventory without first using a command line on launch with Steam (-LegacyScreen), as their Dashboard is now in a fixed position. Ctrl+S still allows for objects to saved to the player's inventory.

**Relevant Issues:**

[#2154](https://github.com/Neos-Metaverse/NeosPublic/issues/2154)

**To Reproduce:**

1. Spawn an image/object in the game world.
2. Attempt to grab the image/object with RMB and drag it onto the Dashboard/Inventory.
3. Image/object becomes unselected due to Desktop mode Dashboard being in a fixed position, and taking 'focus' of the screen. Legacy mode allows for the Dashboard to be 'floating' instead of fixed, allowing one to look away from it, and then select/drag objects to it.

**Bug information (please complete the following information):**

How often does it happen: Always
Does the bug persist after restarting Neos? Yes
Neos Version: 2021.5.6.453
Neos Platform: Any
Link to reproduction World/Item: Any object/picture in Desktop mode.
Regression: Yes; workaround is to use the command line "-LegacyScreen" via launch settings in Steam.

**Reporters:**
Starchaser (Discord: Starchaser#5936) (Telegram: Starchaser)

**Comment by 3x1t-5tyl3** [comment]
Duplicate to #2154 #2155 ?
Desktop mode is not quite finished and still needs certain things to be implemented.

**Comment by strchsr** [comment]
Not sure about #2155 but I mentioned #2154 in it, and found a workaround through -LegacyScreen. Can't imagine it'd be too hard to add a toggle to the settings for Desktop mode to use "legacy Dashboard"; since -LegacyScreen also takes away the middle click functionality (locomotion settings, etc.)

**Comment by Frooxius** [comment]
We already have issues for those. Desktop mode is in development and not everything is implemented yet, I suggest just being patient.

LegacyScreen mode is an old mode that was used for debugging and isn't supported for desktop gameplay, but was only designed for internal use. It will be removed at some point.

**Comment by strchsr** [comment]
> LegacyScreen mode is an old mode that was used for debugging and isn't supported for desktop gameplay, but was only designed for internal use. It will be removed at some point.

Well, I assume this will be after Desktop mode is further developed? Since the only reason I used -LegacyScreen was so I wouldn't have a fixed Dashboard so I'd be able to set a Profile image, haha.
