### ISSUE TITLE
Uncheck AvatarProtection on AvatarCreator when in Local Home

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2184]
## Is your tweak request related to a problem? Please describe.
When in the local home, opening the avatar creator automatically checks "protect avatar" which causes the create button to be greyed out.

## Describe what would you like tweaked
Uncheck the "Protect avatar" button when in the local home. With a warning that the avatar is being created without protection? (Though this could be generalized)

## Describe alternatives you've considered
Make it generally easier to spot why the create button is greyed out might be good. I've seen plenty of users recently trying to import to the local home and wondering why the button is greyed out.

## Additional context
-

**Comment by Frooxius** [comment]
This won't get changed, as it could lead to users not protecting their avatars by accident. Originally it was unchecked which lead to a lot of people having unprotected avatars by accident, this way at least it forces people to stop and think that they're doing something they don't necessarily want.

We generally advise against using Local for editing like this anyway, the avatar creation should be done in user's Home, so we won't be optimizing for building in Local.
