### ISSUE TITLE
Guests can toggle gizmo mode buttons

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2188]
## Describe the bug
Guest users are able to change the gizmo mode of selected objects, e.g. setting it in scale, rotation, etc. mode.

## Relevant issues
None I am aware of.

## To Reproduce
- Join a session in which you are a guest, and a gizmo exists
- Click on a gizmo mode toggle button

## Expected behavior
Gizmos remain fully uninteractible by anyone without builder permissions.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.6.453
 - Neos Platform: Windows
 - Regression: No, as far as I'm aware this behavior has always existed

## Additional context
Discovered in a session with Maliceowo while I was teaching about enabling the mesh scaling mode on primitive box meshes, only to realize I was a guest afterward but could still interact with it.

Not really a significant issue as the gizmo itself can't be used by the guest user, it's just a potential minor annoyance for whomever might wish to work with the gizmo.

## Reporters:
Shifty# 7944, Maliceowo

**Comment by ProbablePrime** [comment]
This was fixed in: 2021.7.6.1154

Thank you for the report!
