### ISSUE TITLE
AvatarExpressionDriver Horizontal/Vertical Min/Max defaults

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2205]
## Is your tweak request related to a problem? Please describe.
When loading in an avatar with pos/negative expressions (vertical/horizontal) the vert/hor shapes are assigned but values have to be changed manually.

## Describe what would you like tweaked
Add default -1 min and +1 max for Vertical and Horizontal blendshapes in the ExpressionDriver.

## Describe alternatives you've considered
-

## Additional context
-

**Comment by Frooxius** [comment]
Under what conditions would these be assigned? When you add an expression it doesn't have those horizontal shapes as default, you need to switch to those manually, so it's not really possible to have Min/Max default in such cases.

**Comment by 3x1t-5tyl3** [comment]
Not really.. I have 4 different shapes which are like that see screenshot below and they got auto-assigned..

Under that same auto-assignment I also figured that these hor/ver shapes always have a -1 to 1 range one might aswell auto-assign it.

![grafik](https://user-images.githubusercontent.com/61988002/117568796-badb2480-b0c2-11eb-80ed-eaf917dcf652.png)

**Comment by Frooxius** [comment]
I see what you mean, I didn't realize that you were getting them auto-assigned. That's more of an unintended consequence of the heuristics, but I can see what I can do to override the defaults for those during auto-assignment.

**Comment by 3x1t-5tyl3** [comment]
Yeah I copied the values from the inspector 1:1 and it detected all of them perfectly. :)

**Comment by Frooxius** [comment]
Made the changes in 2021.5.13.384, thanks!
