### ISSUE TITLE
AvatarExpressionDriver still activating blendshapes if DataSource is "Null"

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2207]
## Describe the bug
The AvatarExpressionDriver particularely still keeps values for Vertical and Horizontal expressions when DataSource is "Null"

## Relevant issues
#2205 At most.

## To Reproduce
1. Have Facetracking
2. Null the "DataSource" in the ExpressionDriver

## Expected behavior
Values become zero when DataSource is Null

## Screenshots / Video
-

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.8.440
 - Neos Platform: Windows
 - Link to reproduction World/Item: -
 - Regression: Not AFAIK

## Additional context
-

## Reporters:
3x1t_5tyl3# 0001

**Comment by Frooxius** [comment]
Fixed in 2021.5.13.384. It wasn't activating blendshapes, but rather setting it to the Min value, now it resets to 0 instead.
