### ISSUE TITLE
Failing to join contacts+ "World.Error.OnlyContactsOfContacts"

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2210]
## Describe the bug
Invited to Contacts+ session failing to join, requiring multiple join attempts

## Relevant issues
#2116

## To Reproduce
1. Receive an invite to Contacts+ session
2. Attempt to join from invite
3. Fail to join
4. Read The Logs

## Expected behavior
Join without an issue

## Screenshots / Video
First attempt Line 943
[DESKTOP-SPEUN1P - 2021.5.6.453 - 2021-05-07 16_58_20.log](https://github.com/Neos-Metaverse/NeosPublic/files/6446678/DESKTOP-SPEUN1P.-.2021.5.6.453.-.2021-05-07.16_58_20.log)

## Bug information (please complete the following information):
 - How often does it happen: Sometimes
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.8.445
 - Neos Platform: Windows
 - Link to reproduction World/Item: Visit posted log
 - Regression:

## Additional context
Spamming the same invite eventually worked after multiple failed attempts

## Reporters:
AshtonSparx, Froppy

**Comment by shiftyscales** [comment]
Please contribute to the existing issue, #2116 since it appears to be heavily related to that, @AshtonSparx. Additionally this issue requires logs from both the user and the session host, please provide both.
