### ISSUE TITLE
Additional Logix bits spawn at LogixTip instead of on the same plane as other Logix

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2211]
## Describe the bug
Spawning a drive node (e.g. from a blendshape) causes the drive node to spawn at the LogixTip instead of in the same plane as other nodes.

Logix interfaces also spawn outside of the plane of the Logix.

## Relevant issues
#2164 

## To Reproduce
- Grab a reference to a value, e.g. blendshape, or component
- Create a drive node or Logix interface

## Expected behavior
The drive node/Logix interface should be created on the same plane as the other nodes.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.9.179
 - Neos Platform: Windows
 - Regression: No

## Reporters:
Shifty# 7944

**Comment by Frooxius** [comment]
Fixed in 2021.5.13.384, should all now spawn in the same plane, thanks!
