### ISSUE TITLE
Add "Bake Static Mesh" Tooltip to allow for quick optimisation of complex objects

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Neos-Metaverse/NeosPublic#2212]
## Is your feature request related to a problem? Please describe.
When building a world builders might decorate it with dynamic and customizable assets that only need to be configured once, and will afterwards be a permanent part of the environment. These assets might contain armatures to be posed by the user and / or blendshapes to be adjusted to fit the individual requirements of the builders. These assets still contain information about bones, weights, armatures and shape keys which from that point forward will effectively remain static, increasing the object's complexity and load time while reducing performance.

## Describe the solution you'd like
My proposal to give builders the ability to easily optimize these assets in their worlds is the addition of a new "Bake Static Mesh" tooltip, which when used will bake the selected object into a new static mesh object while conserving current vertex positions and removing the armatures, shape keys and potential drivers like the VRIK component.

## Describe alternatives you've considered
Recently the feature to bake non-driven blendshapes has been implemented, which allows for more selective control than the proposed feature, however it requires manual efforts and deeper knowledge from the builder, which could potentially keep some builders away from optimisation efforts. I think a one-click solution would heavily increase the useability of mesh baking features. As far as I am aware there is no armature equivalent to this functionality.

## Security concerns
It needs to be ensured that no license information / avatar protection gets lost along the baking process to prevent people from abusing this tooltip to copy and save otherwise protected assets and avatars.

**Comment by ukilop** [comment]
Something worth noting that I discovered recently:
The glue tip can bake objects as well, you also don't need to use the drag and glue visual, 
if you grab a slot reference with the glue tip and press secondary it will glue/bake/skinned bake the selected slot

**Comment by Frooxius** [comment]
This would have to be added as a processing option for SkinnedMeshRenderer in the inspector first, then we could expose it through the tooltip. It's possible, although it might not necessarily be worth the optimization.

If you have 20 different poses of the same mesh, all of them are still using the same underlying mesh data. If you bake them, then  you end up with 20 different meshes, that all have to be downloaded and loaded into memory, which might end up costing more.

I'll still add this option, but it's just something to be aware of when using such tool.

**Comment by Frooxius** [comment]
This has been added in 2021.9.16.105 now! You can bake skinned meshes into static ones either directly through the inspector or with the Glue tooltip using the "Bake Meshes" mode.
