### ISSUE TITLE
Neos crash on startup

### ISSUE THREAD

**Issue by wmhilton** [Neos-Metaverse/NeosPublic#2214]
## Describe the bug
Game crashes during initialization of Froox engine, last word I see shown on screen is "...LocalDB".

## To Reproduce
Just happens on my computer apparently.

## Log Files

[WILL-PC - 2021.5.9.179 - 2021-05-10 22_56_42.log](https://github.com/Neos-Metaverse/NeosPublic/files/6456259/WILL-PC.-.2021.5.9.179.-.2021-05-10.22_56_42.log)

[Player.log](https://github.com/Neos-Metaverse/NeosPublic/files/6456265/Player.log)

I did not find a Crashes folder at %USERPROFILE%\AppData\Local\Temp\Solirax\NeosVR 🤷🏻‍♂️ 

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.9.179
 - Neos Platform: Windows

## Reporters:
@wmhilton / wmhilton#8108

**Comment by wmhilton** [comment]
Resetting the database as described in [6.4](https://discord.com/channels/402159838827905024/679725405254844416/704548547550511136) did resolve the issue! So I am OK 👍🏻

**Comment by H3BO3** [comment]
I already knew a database reset would solve this problem and had diagnosed it in the discord, failed to be specific enough on my part when requesting logs. I have collected the relevant log file, directed it to Frooxius, and closed the issue.
