### ISSUE TITLE
Spawning tools through the number rows leaves "Holder" slots behind

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2220]
## Describe the bug
When spawning tools through the 1-9 keys (desktop) the spawn leaves a "holder" slot behind on UserRoot.

## Relevant issues
-

## To Reproduce
1. Press any number on the number row to spawn a tool
2. Observe the "Holder" slot still being there

## Expected behavior
"Holder" slot get's removed after serving it's purpose

## Log Files
-

## Screenshots / Video
![grafik](https://user-images.githubusercontent.com/61988002/118023565-f6454f80-b35d-11eb-8c0b-5ca3b86898dc.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.9.179
 - Neos Platform: Windows
 - Link to reproduction World/Item: -
 - Regression: N/A

## Additional context
Given items spawn with the holder slot and not directly when saved while holding instead of through the inspector while holding the slot ref. Thus creating the holder slot which doesn't get removed?

## Reporters:
3x1t_5tyl3# 0001

**Comment by Frooxius** [comment]
Fixed in 2021.5.13.384, thanks!
