### ISSUE TITLE
Undo manager un-packed Logix value Changes

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2221]
## Is your tweak request related to a problem? Please describe.
When setting values in un-packed Logix, you can't undo any changes which is problematic, especially when trying to grab those value cards in desktop mode, because you can easily accidentally drag numbers/strings into a field it's not meant for, not remember what was originally in the node and... you're lost.

## Describe what would you like tweaked
For changes in un-packed logix to be applied to the undo manager. So if you do an oopsie, it can be undone.

## Describe alternatives you've considered
I'm not sure about any alternatives, but i'm open to conversation.

## Additional context
[Example Video](https://youtu.be/VvGYTm-62cs)

I haven't been able to find a similar or duplicate issue of this with any quick searching in Open/Closed issues. 
However, I did find #203 this but it doesn't include content in the nodes.

**Comment by Frooxius** [comment]
The undo should already work, there's not much specific for LogiX from other text fields.

**Comment by H3BO3** [comment]
I've noticed this too.

**Comment by AshtonSparx** [comment]
It doesn't work for any of the LogiX types, as shown in my example video. It doesn't create an undo step

**Comment by Frooxius** [comment]
Yeah I relabeled this as a bug since it's broken functionality that should be there. I'll look into it.

**Comment by AshtonSparx** [comment]
Thank you Froox! <3

**Comment by Frooxius** [comment]
Fixed in 2021.5.13.384!
