### ISSUE TITLE
CloudValueField with locally driven Path not local.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2222]
## Describe the bug
I am locally driving the variable name in a CloudValueField and it seems to always spit out the value from the variable that the host has driven into the CloudValueField.

## Relevant issues
Didn't find any.

## To Reproduce
Create two cloud variables of the same type. (in my case uri)
Fill them with different values.
Locally drive the variable in a CloudValueField to both of these for two different people in the same session.
See that the value in the field is the same for both users.

## Expected behavior
If a CloudValueField locally references a different value than it does for the host, the field should not have the host's value in it.

## Bug information (please complete the following information):
 - How often does it happen: Always.
 - Does the bug persist after restarting Neos? No.
 - Neos Version: 2021.5.9.179
 - Neos Platform: Windows, probably any.
 - Regression: Don't know

## Reporters:
Cameron#7818

**Comment by Psychpsyo** [comment]
Note: The value the CloudValueField is linked to also does not appear driven which might be part of the problem.

**Comment by Frooxius** [comment]
You can't use CloudValueField like this, the value is synced between all users. If you want each user to get their own unique value use CloudValueVariableDriver.

**Comment by Psychpsyo** [comment]
But CloudValueVariableDriver gets a user's value for a variable. I can't use it to locally get a group's value for a variable. (doesn't let me specify VariableOwnerId)

**Comment by Frooxius** [comment]
I can add override to the CloudValueVariableDriver. Why are you looking to override path for every user though? This sounds to me a bit like an anti-pattern.

**Comment by Psychpsyo** [comment]
I have two uri cloud variables, pointing to two images that are regularily updated (two becuase it's an English and a Japanese version) and am overriding which one a user loads based on their set language.

**Comment by shiftyscales** [comment]
It sounds to me like you're after #1480 @Psychpsyo.

**Comment by shiftyscales** [comment]
It sounds like you're after #1715 which you've already requested, @Psychpsyo.

**Comment by Psychpsyo** [comment]
In the end, yes. That'd be the right solution for this specific problem.
But I feel like that locally driving what cloud var someone accesses probably has more use-cases than just this one.
