### ISSUE TITLE
Additional Procedural Meshes

### ISSUE THREAD

**Issue by Dirko3000** [Neos-Metaverse/NeosPublic#2224]
## Is your feature request related to a problem? Please describe.
Like many others, I prefer the simple in-game modeling workflow, but have found the selection of available basic 3D shapes to work with a bit lacking for making a number of things.

## Relevant issues
Not that I could find

## Describe the solution you'd like
The addition of a number of new procedural 3D models to work with including:
- half sphere
- bowl (half sphere with a another half sphere "dug out" from the center)
- bevel cylinder
- hollow cylinder (cylinder with a cylinder taken out of the center to form a pipe)
- torus and "hollow cylinder" with adjustable "arc" degrees similar to the "BevelSoliRingMesh" in the "Neos UI Meshes" folder (allowing to have 3/4 of a ring, 1/2 a pipe, etc)
- cube with a round hole through the center (allowing for walls to have a round hole or arching doorway)

## Describe alternatives you've considered
I've been told several times to just make the shapes I want in Blender, however this is a flawed solution as this would only be of any help to me once, and the resulting static meshes would not be nearly as flexible or useful for various purposes as procedural meshes.

## Additional context
The addition of a number of the above suggestions would greatly improve the ability to model in-game and the ability to have creations be more dynamic in their shape through component or logix interactions with the model parameters.

**Comment by ProbablePrime** [comment]
@Dirko3000 Can you update your issue to use the template that is presented when you create an issue of this type?

The template is very important to keep everything clear and provide a healthy discussion. Thank you

**Comment by shadowpanther** [comment]
From the "other" set:
- ConeMesh already has two radii properties (RadiusBase, RadiusTop). Also that makes ConeMesh unoptimized in its default form because half of the tris have zero size.
- Cube with cylinder cut is a heavy operation, because the number of vertices of cube and cylinder differ and the engine would have to optimize tris to make the transition face.

Most (all?) of those would be possible if we ever get binary operations, but I'm not sure whether those would be feasible for realtime engine.

**Comment by Dirko3000** [comment]
Fixed template, and removed the cone suggestion (was unaware the cone already had the parameter I wanted). Thanks.

**Comment by Frooxius** [comment]
We can add those, but generally it'd be better to make issues for each unique mesh. Doing them all as one batch is a much bigger work chunk than doing a few here and there, so it probably won't get prioritized as soon.

**Comment by Dirko3000** [comment]
> We can add those, but generally it'd be better to make issues for each unique mesh. Doing them all as one batch is a much bigger work chunk than doing a few here and there, so it probably won't get prioritized as soon.

Would it be better to do that at this point? I can if you like.

**Comment by ukilop** [comment]
I have separated them into multiple Issues.
Also added my own suggestions to each.
Decided not to do "cube with circular hole" as that seems too specific/complicated

**Comment by Dirko3000** [comment]
oh, word. Thanks.

**Comment by shiftyscales** [comment]
In this case, I'll close out this issue in the effort of redirecting attention to the individual requests.
