### ISSUE TITLE
Default freeform camera position to current camera position (or global position) whenever it is entered

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2225]
## Is your tweak request related to a problem? Please describe.
Presently, the freeform camera maintains its global angle and relative position to your avatar. If you move your avatar, the freeform camera will be toggled into a less predictable position/view.

The primary issue stems from cases where the freeform camera has been moved a significant distance away from the avatar, and/or when the avatar then is moved a significant distance away from its previous position.

It is a bit disorientating to have to figure out where your current view is.

## Describe what would you like tweaked
It would be preferable that the freeform camera either maintained the previous camera position from the first/third/UI camera viewpoint, or it maintain the same global position so it is not moved when the avatar is moved.

I could see potential use-cases for both. My preference/what I feel should be default would be to use the current camera position, as then users that have moved their avatar to a point of interest could then take their current viewpoint, and use that as the basis for their freecam position.

**Comment by Frooxius** [comment]
Made changes in 2021.5.16.886! When activating from UI Aligned camera view it still remembers the last position, but first and third person will use the current as a reference.
