### ISSUE TITLE
Add a setting that prevents builder from changing roles in headless sessions.

### ISSUE THREAD

**Issue by lavender-snow** [Neos-Metaverse/NeosPublic#2227]
## Is your feature request related to a problem? Please describe.
There are situations where you want to allow session participants to use tooltips, but you do not want to allow them to change roles.
I want to prevent someone I don't know from being set up as a builder in a Contact+ session.
If it is a user's session, the host user can disable it from below, but not in headless mode.

Roles
->BuilderPermissions
->UserPermissions
->AllowAssignRole

## Relevant issues
probably #289

## Describe the solution you'd like
Allow change the "AllowAssignRole" for each role using console commands or configuration files.

## Describe alternatives you've considered
Allowing "AllowAssignRole" to be changed from a command or a configuration file will allow tooltips to be used while preventing users from changing roles in a headless session.

**Comment by shiftyscales** [comment]
Permissions are stored on the world itself. If the world permissions are modified in the saved copy of the world that is to be hosted by the headless client, you can already accomplish this, @lavender-snow.

**Comment by Frooxius** [comment]
Yes, this is already supported, you uncheck the AllowAssignRoles on UserPermissions that's assigned to the builder role. Generally though that's not advisable, as it's not fully secure way of ensuring that, giving someone Builder gives them a lot of power.

You just need to modify the roles in the world itself, we are not doing a separate permission system for Headless to avoid fragmentation of the code and confusion.
