### ISSUE TITLE
Plugging broken outputs into a Drive node causes it to be deleted.

### ISSUE THREAD

**Issue by chemicalcrux** [Neos-Metaverse/NeosPublic#2236]
## Describe the bug
Outputs from nodes can become broken if an exception is thrown during evaluation. If one of these outputs is connected to a Drive or Drive Playback node, the node is deleted.

This also causes the destruction of Drive arrows.

## Relevant issues
This was found while testing #2219 

## To Reproduce
1. Get a broken output (see Screenshots)
2. Plug it into a Drive node
3. The node is deleted
4. Fix the output
5. Plug it into a Drive node
6. Break the output
7. The node is deleted

## Expected behavior
Not entirely sure. It would be reasonable for the drive to end (which would still destroy Drive arrows), but the LogiX nodes probably shouldn't disappear!

Just "freezing" the drive wouldn't quite make sense, since the value being used to drive can no longer be calculated.

## Log Files
[CRUX - 2021.5.13.433 - 2021-05-13 10_18_33.log](https://github.com/Neos-Metaverse/NeosPublic/files/6473332/CRUX.-.2021.5.13.433.-.2021-05-13.10_18_33.log)

Lots of instances of the bug here. The very end of the log contains an example.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/8015368/118145034-1ebf5f00-b3db-11eb-8b90-02613c3facf9.png)

If a Drive or Drive Playback node is connected to the broken float output, it disappears. 

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.13.433
 - Neos Platform: Any
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
Preventing broken outputs would make this bug irrelevant, but there are a number of ways to cause them.

## Reporters:
Just myself.

**Comment by Frooxius** [comment]
Th is is intentional, there's a cleanup mechanic in case of errors and exceptions to prevent log-spam. Drive nodes in particular clean themselves up when they become invalid. 

Just make report for the broken nodes themselves please, that's what needs to be fixed instead.

**Comment by chemicalcrux** [comment]
This also applies to the LogiX nodes that let you drive and un-drive a field. Are those also intended to be destroyed, rather than just cancelling the active drive?
