### ISSUE TITLE
The 'Description' input to the CreateSpawnUndoStep LogiX node doesn't appear to do anything

### ISSUE THREAD

**Issue by Zyzyl** [Neos-Metaverse/NeosPublic#2237]
## Bug description
There is a string input named `Description` for the CreateSpawnUndoStep LogiX node the value of which does not appear to affect anything about how the node operates.

## To Reproduce
1. Spawn a Create Spawn Undo Step node
2. Create some slot (e.g. Dev tip > Create New > 3D model > Box) and provide that as the `Target` input to the node
3. Create a string input node with arbitrary text (e.g. "Test") and connect it to the `Description` input of the node.
4. Fire an impulse to the node's `Create` input and observe an undo entry is successfully created.
5. Note that, regardless of the `Description` input the displayed description of the undo step in the radial context menu is "Spawn `Target slot name`"

## Expected behavior
By analogy to the `Description` input on the Create Undo Batch and Begin Undo Batch nodes I'd expect the `Description` input to control the text displayed by the undo button on the radial menu.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.13.433
 - Neos Platform: Windows
 - Regression: Unknown

## Reporters:
Zyzyl#1441

**Comment by Frooxius** [comment]
Fixed in 2021.5.15.697, thanks!
