### ISSUE TITLE
User Freecam Active Node

### ISSUE THREAD

**Issue by LeDrascol** [Neos-Metaverse/NeosPublic#2238]
## Is your feature request related to a problem? Please describe.
Currently there is no reliable method for determining if a user is using remote camera functionality. The visual is easy to disable, and no other reliable detection methods are available.

## Relevant issues
None.

## Describe the solution you'd like
Possible (mutually exclusive) solutions to this problem:
- New logix node: User Freecam Active (bool)
- New logix node: User Desktop Camera Mode (enum)

## Describe alternatives you've considered
Ask every user when and if they're using freecam.

## Additional context
None.

**Comment by Frooxius** [comment]
Added these two nodes in 2021.5.17.871 which should help cover the usecases:

- Added UserActiveViewTargettingController node (under Users) which outputs the currently active view targetting controller (first person, third person, UI camera, Freeform and any future ones) (based on request by @LeDrascol)
- Added UserViewReferenceActive which indicates if given user has currently active view reference (based on request by @LeDrascol)
