### ISSUE TITLE
Disable camera visual for video players

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2239]
## Is your tweak request related to a problem? Please describe.
While watching videos in a group, it is possible for a user's camera visual to obstruct the screen for other users.

## Describe what would you like tweaked
Either disable a user's camera visual while UI focused on a video player, or tweak the logic to ensure the visual is hidden more reliably in this scenario.

## Additional context
This issue came up while watching meme videos in Veer's session (the best possible context.)

**Comment by Frooxius** [comment]
Why is the camera still appearing? Is your avatar too far away from the video? Can you provide any examples of when it's appearing and how close is the avatar positioned?

**Comment by shiftyscales** [comment]
It usually is just when the screen is made larger and is a little distance away (e.g. while watching videos in a group as is a pretty typical activity in our circles.)
![2021-05-14 23 08 43](https://user-images.githubusercontent.com/54213390/118350087-c044ce80-b509-11eb-97d4-0e6c81095000.png)
![2021-05-14 23 10 31](https://user-images.githubusercontent.com/54213390/118350088-c33fbf00-b509-11eb-8cbf-986a62e3bd26.png)

POV of a position I was standing in where my camera was visible after entering the UI edit mode:
![2021-05-14 23 07 57](https://user-images.githubusercontent.com/54213390/118350266-950eaf00-b50a-11eb-8201-c8426515b49c.png)

**Comment by Frooxius** [comment]
Ah I see thanks! Hmm, I think I could factor the size of the UI into the computation of the visibility distance, that way it'll be a bit smarter in such cases and hide the camera if the UI is big enough within the FOV.

**Comment by Frooxius** [comment]
Ok made the tweaks in 2021.5.16.886, the visibility should now be based on the size, so this scenario should be better. Let me know if you still run into issues with it!
