### ISSUE TITLE
E rotate should freeze mouse cursor when in freeform and UI aligned cam.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2240]
## Is your tweak request related to a problem? Please describe.
When E rotating a thing in freeform or UI aligned camera mode, it is impossible to not also push it around.

## Describe what would you like tweaked
Make the E rotate mode also freeze to position of the cursor.

## Describe alternatives you've considered
Not doing this.

**Comment by Frooxius** [comment]
Added in 2021.5.15.697, thanks!
