### ISSUE TITLE
Some Multi LogiX nodes (Multi Lerp, Multi Cosine Lerp, etc.) produce broken output from a NaN input

### ISSUE THREAD

**Issue by chemicalcrux** [Neos-Metaverse/NeosPublic#2243]
## Describe the bug
LogiX nodes that select from a list of items, such as Multi Lerp and Multi Cosine Lerp, will produce broken outputs when given a NaN input.

## Relevant issues
This is the error that prompted #2236 .

## To Reproduce
1. Plug a NaN into a Lerp node's Lerp input
2. The output is now NaN
3. Hit + to turn it into a Multi Lerp Node
4. The output is now broken

## Expected behavior
The output should still be NaN

## Log Files
[CRUX - 2021.5.13.433 - 2021-05-14 09_40_37.log](https://github.com/Neos-Metaverse/NeosPublic/files/6479135/CRUX.-.2021.5.13.433.-.2021-05-14.09_40_37.log)

## Screenshots / Video
![image](https://user-images.githubusercontent.com/8015368/118279209-de261b00-b498-11eb-87d3-5660a8c6b42e.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.13.433
 - Neos Platform: Any
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
N/A

## Reporters:
Just me.

**Comment by 3x1t-5tyl3** [comment]
similar to #1158 ?

**Comment by chemicalcrux** [comment]
I was just looking at that issue, actually. I think this is a separate breakage, but I *can* use it to cause a very similar problem:

1. Create a Display for the output of an untyped Demultiplex node
2. Plug in a broken int to the Index input
3. Plug in a float input to the Value input

![image](https://user-images.githubusercontent.com/8015368/118280739-7bce1a00-b49a-11eb-929f-dd3607c7d937.png)
![image](https://user-images.githubusercontent.com/8015368/118280760-7f61a100-b49a-11eb-9550-373ff54bf57e.png)

An exception occurs while iterating over a list (probably the outputs) and prevents the old component from being removed. This leads to other...unusual situations, such as inconsistent outputs (only one output stays broken when resetting the broken nodes; the others get a value)

![image](https://user-images.githubusercontent.com/8015368/118280853-956f6180-b49a-11eb-9ffc-ce99e8c9847d.png)

**Comment by chemicalcrux** [comment]
Correction on that: the broken input is irrelevant; it does this as long as you have at least one wire plugged into an output of the Demultiplex mode when it tries to cast itself.

I will check for existing issues and then open a new one for that if there aren't any.

**Comment by Frooxius** [comment]
Should be fixed in 2021.5.15.697, thanks!
