### ISSUE TITLE
LogiX interface cards spawn additional copies for every user in the session

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2244]
## Describe the bug
This is a long-standing bug that was mentioned a lot of times, but still there is no open issues on it that I can find. I propose this to be the issue to track this bug so it would be fixed.

## Relevant issues
Issues on similar topic, but not exactly: #2066, #1128, #1491

## To Reproduce
1. Be in a session with more than one user
2. Work with LogiX - create, use interfaces, pack, unpack
3. Observe additional interface cards being spawned. The exact number is usually equal to the user count in the session for each unique card.

## Expected behavior
Additional cards won't spawn.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.13.433
 - Neos Platform: Any
 - Link to reproduction World/Item: 
 - Regression: No

## Additional context
There is a button to clean all interfaces in the world, but it doesn't distinguish between working interfaces and extra copies. There was a community-made tool to only remove extra interfaces (Ukilop's), but it stopped working after the recent patch that removed one of the "hacky" ways to properly clean up interface cards.

## Reporters:
Shadow Panther#5154

**Comment by Banane9** [comment]
Would be great if this got fixed, getting spammed with a bunch of useless and flickering interfaces is supremely annoying, especially if you then try to move them out of the way...

**Comment by AshtonSparx** [comment]
Not only the hassle of manually removing the cards but the lag of them duplicating per user, and the lag intensity being multiplied further if there's a lot of logix being unpacked at once

**Comment by Frooxius** [comment]
This is actually same issue as https://github.com/Neos-Metaverse/NeosPublic/issues/1128, the answer is unfortunately same one - with the design of the system this is pretty tricky to fix (it technically cannot be fixed on itself), as it requires some general changes to the whole engine update loop and event sequencing. I can look into doing that soonish, but it's pretty big task.

Solving this problem properly requires redesign of the mechanisms.
