### ISSUE TITLE
Demultiplex node fails to delete its old component when casting if outputs are already connected

### ISSUE THREAD

**Issue by chemicalcrux** [Neos-Metaverse/NeosPublic#2245]
## Describe the bug
Trying to cast a Demultiplex node when one of its outputs is already connected to something will cause it to double-up. The old and new nodes will be overlapping, retaining their original connections.

## Relevant issues
#1158 is the same end result, but for a different node.

## To Reproduce
1. Create a Demultiplex node
2. Drag out a display from one of its Dummy outputs
3. Plug any other type into one of its inputs
4. Two copies of the node are now stacked on top of each other (in the same slot)

## Expected behavior
The connection to the input should be refused. Alternatively, the incompatibly typed output wires should be cut.

## Log Files
[CRUX - 2021.5.13.433 - 2021-05-14 10_30_21.log](https://github.com/Neos-Metaverse/NeosPublic/files/6479435/CRUX.-.2021.5.13.433.-.2021-05-14.10_30_21.log)

## Screenshots / Video
![image](https://user-images.githubusercontent.com/8015368/118285545-8e971d80-b49f-11eb-9bfa-5f8edcefdd71.png)

## Bug information
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.13.433
 - Neos Platform: Any
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
This would probably happen to any other LogiX node with an arbitrary number of data outputs, but I can't think of any others.

## Reporters:
Just me.

**Comment by Frooxius** [comment]
Looks like this is due to an exception in the swapping process, which doesn't fully finish. Do you have a whole log please? It seems like the one you provided is cut-off. It might be enough for diagnosis, but if you can send full one in case that can help when I look deeper into this.

**Comment by chemicalcrux** [comment]
I did it again; it looks like that was indeed the last line of the log. The very next line is about exiting Neos.

[CRUX - 2021.5.13.433 - 2021-05-15 00_44_01.log](https://github.com/Neos-Metaverse/NeosPublic/files/6482137/CRUX.-.2021.5.13.433.-.2021-05-15.00_44_01.log)

**Comment by Frooxius** [comment]
Fixed in 2021.5.15.697, thanks!
