### ISSUE TITLE
Make avatar always look at plane in UI aligned camera mode.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2249]
## Is your tweak request related to a problem? Please describe.
When doing logix in UI aligned camera mode, as soon as I hover off of a node, my avatar looks at whatever background thing I am now 'pointing at'.

## Describe what would you like tweaked
Make the avatar instead look at the point on the 'plane' I am UI-aligned to that my cursor is hovering over, even if no actual UI is there.

## Describe alternatives you've considered
Not doing it which isn't a huge problem. But in general, when in UI aligned camera, I'd imagine focus to always lie on the 'plane' I am focused to.
Also, as soon as clicking on background stuff and interacting with it, the avatar can start turning towards it.

**Comment by Frooxius** [comment]
Why do you want this behavior specifically? This was the previous behavior, but it led to the avatar being posed at awkward angles in some cases when interacting or pointing at things that do not lie in the plane. 

I could specifically make the avatar stop focusing when not actively interacting with anything like the Freeform camera does though.

**Comment by Psychpsyo** [comment]
I just noticed it today when doing UI-aligned logix with my avatar standing behind it and it just kept turning around every time I hovered off of a node.
