### ISSUE TITLE
Contacts List Filtering

### ISSUE THREAD

**Issue by LeDrascol** [Neos-Metaverse/NeosPublic#2250]
## Is your feature request related to a problem?
No.

## Relevant issues
This issue may be required to wait until the contacts UI rework.

## Describe a possible solution
The ability to filter users in the contacts list similarly to the worlds list. This would allow narrowing down and sorting cluttered user lists by common criteria.

Some possible examples:
* Can be joined
* World access levels
* Online status type
* Pending status (requests)

## Describe less favorable alternatives
* Scrolling the contacts list more
* Having less contacts
* Not looking at the contact list

**Comment by Frooxius** [comment]
Yeah the reworked Contacts UI will have some filtering/grouping options, most of these should be covered. The joinability and world access seem like good ones too!
