### ISSUE TITLE
World crash: "Node has been disposed, cannot enumerate its inputs"

### ISSUE THREAD

**Issue by chemicalcrux** [Neos-Metaverse/NeosPublic#2253]
## Describe the bug
I crashed out of a world as I was plugging Demultiplex nodes together to gather info for #2243 .

## Relevant issues
None seen.

## To Reproduce
I have not managed to reproduce the crash. I was connecting some nodes at random when the world abruptly closed.

## Expected behavior
....no crash? (:

## Log Files
[CRUX - 2021.5.13.433 - 2021-05-14 09_40_37.log](https://github.com/Neos-Metaverse/NeosPublic/files/6487476/CRUX.-.2021.5.13.433.-.2021-05-14.09_40_37.log)
The crash occurred on line 24835. The most pertinent lines are:

```
10:09:02 AM.083 (120 FPS)	Unhandled Exception when updating world: Fen's Den. State Running, Refresh Stage: LogixUpdates, Init State: Finished, SyncTick 199303, StateVersion: 398606
Dumped world state to: D:/caches/neos/cache/Cache\k702dxi6jcyrzp7q.lz4bson
System.InvalidOperationException: Node has been disposed, cannot enumerate its inputs!
Element: IDAFEAE00, Type: FrooxEngine.LogiX.Operators.Demultiplexer`1[BaseX.dummy], World: null, IsRemoved: True, IsDestroyed: True, IsDisposed: True, Enabled: True
```

## Screenshots / Video
N/A

## Bug information (please complete the following information):
 - How often does it happen: Only Once
 - Does the bug persist after restarting Neos? No
 - Neos Version: 2021.5.13.433
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
This sounds like some kind of race condition; it's trying to read stuff on a node that was already destroyed. I tried to reproduce it by creating and destroying massive numbers of demultiplex nodes, including ones plugged into each other, but nothing happened.

It's possible that this was related to the broken output I was getting in #2243 ; there was an exception about that two seconds before the crash.

I can send the dumped world state via Discord if it might be useful.

## Reporters:
Just me.

**Comment by Frooxius** [comment]
Fixed in 2021.5.16.886! It's probably not something that'd happen too often, but there should be a guard against this kind of bug resulting in a whole world crash now.
