### ISSUE TITLE
regression, inspector spawns at wrong rotation when creating empty object

### ISSUE THREAD

**Issue by DanteTucker** [Neos-Metaverse/NeosPublic#2256]
## Describe the bug
A regression. when creating a new empty object the inspector spawns facing a fixed direction. it used to spawn facing you.

## To Reproduce
Using a dev tip. create a new empty object

## Expected behavior
Inspector should spawn facing you

## Reporters:
Dante

**Comment by DanteTucker** [comment]
A note. To see the correct behavior create a new particle system rather than a empty object. it appears that is unaffected

**Comment by Frooxius** [comment]
Fixed in 2021.5.16.886, thanks!
