### ISSUE TITLE
Scroll does not work on the Linux Build in Screen Mode. 

### ISSUE THREAD

**Issue by JellyOsaurus** [Neos-Metaverse/NeosPublic#2257]
The bug is easily reproducible since this has happened to me on multiple linux distributions, including Ubuntu and Arch. But the scrolling does not work with your scroll wheel. The expected behavior is for it to work just like the scrolling in Windows 10. 

https://user-images.githubusercontent.com/22872180/118376437-c58f3100-b57c-11eb-9f1d-ac7f9f7894c1.mp4

**Comment by Frooxius** [comment]
- I don't quite understand what's going on in the video. Is the scroll not doing anything at all? Or is it scrolling, but then immediately moving back?
- Does the scroll work on any Linux Distros for you? Specially Pop OS? 
- Does this affect everything or just UI interfaces? E.g. does scaling grabbed item with scroll work?
- If you spawn the MouseScrollWheelDelta LogiX node, what values does it give you when you try to scroll?

**Comment by JellyOsaurus** [comment]
The scroll is not sensitive enough to scroll through the UI, nothing is immediately moving back, that is me trying to scroll up and down on things that need to be scrolled like the dash and scaling yourself. This has been happening on many distros, including PopOS 20.04 LTS.. It affects everything, including scaling in the 3D space and the UI. Here is a clip of what im getting from the MouseScrollWheelDelta logix node 

https://user-images.githubusercontent.com/22872180/118381037-ba97c900-b59b-11eb-9d2c-e95691beb724.mp4

**Comment by Frooxius** [comment]
I see. Do you have Windows on the same machine? Could you perform comparison of that with the same test, see if the numbers are significantly bigger?

It looks like on Linux the scroll isn't scaled by the system resolution, as it is on Windows, so when Neos compensates for it, it becomes really small.

**Comment by JellyOsaurus** [comment]
Here is a windows comparison, the numbers are different. 

https://user-images.githubusercontent.com/22872180/118427454-12106480-b682-11eb-8728-7ca6b76209ef.mp4

**Comment by Frooxius** [comment]
Thanks! I've bumped up the sensitivity for Linux in 2021.5.17.871, let me know if that helps!

**Comment by JellyOsaurus** [comment]
It helps so much! it makes scrolling usable! 

One extra tidbit i just noticed after trying is that scrolling is in reverse, so scrolling down scrolls content up, and vice versa, on this build. Do you want me to open up another issue for this one?

**Comment by shiftyscales** [comment]
Yes, that would be best handled as a separate issue, @JellyOsaurus. Since it appears the underlying issue for this one is resolved, I'm going to close it out now.
