### ISSUE TITLE
Avatar Animation Overide. 

### ISSUE THREAD

**Issue by Electronus** [Neos-Metaverse/NeosPublic#2258]
## Is your feature request related to a problem? Please describe.
I a few users have come by the discord asking how to Change the animations their Avatar uses either in an anchor, or for things like walking especially in desktop mode.  

## Relevant issues
#48 #1763  

## Describe the solution you'd like
A way to animate Avatars with premade animations to replace or supplement current systems for things like walking animations. 

## Describe alternatives you've considered
You could tweak IK so it looks better, but most users don't know how to do that.  You could animate Proxies but that is janky and could cause issues. You could just not have it. 

## Additional context
This has come up a few times in the last day or so. People coming from Second Life will be looking for features like this.

**Comment by shiftyscales** [comment]
I don't think this issue really adds anything specific over the existing ones you've linked, @Electronus. As was mentioned in #1763 by Frooxius, a majority of the work required to do something like this would require the work of #48.

**Comment by Electronus** [comment]
I wasn't sure, so figured I'd put it up!
