### ISSUE TITLE
Selecting something with the Ctrl+Click camera UI selection and trying to align to the plane instead aligns to the parent object.

### ISSUE THREAD

**Issue by RileyGuy** [Neos-Metaverse/NeosPublic#2259]
## Describe the bug
When you are focused on a UI such as a LogiX node that is under a parent, trying to align the object so that it's flat on the plane instead aligns the object to the forward direction of the parent.

## To Reproduce
Spawn a LogiX node.
Pack it under something that's rotated at an odd angle.
Unpack the node.
Focus on it with Ctrl+Left click
Attempt to align the object.
The object will align to the parent instead.

## Expected behavior
The object should align facing the camera and be flush with the working plane.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.15.697
 - Neos Platform: Any
 - Regression: No, I believe this may have been broken since implementation, though I can't be sure.

## Reporters:
Myself

**Comment by Frooxius** [comment]
It was using the Up direction of the parent, it now uses the actual Up direction of the UI, which should improve overall usability of the UI camera. Thanks! 2021.5.16.886
