### ISSUE TITLE
Standalone 360 cursor

### ISSUE THREAD

**Issue by pushstartvr** [Neos-Metaverse/NeosPublic#2260]
The cursor can no longer select anything on the menu after all the cursor/laser updates.
The resolution/sensitivity is also too high and cannot be resolved with third party sensitivity settings (mouse sensitivity).
It's too hard to select small items.

Latest version as of date of this comment

Username: Blanka

**Comment by Frooxius** [comment]
I've upgraded the mode to use the new Desktop mode stuff in 2021.5.17.871, hopefully this helps! It's also been renamed to "Screen 360".

Let me know if you run into some other issues!
