### ISSUE TITLE
GetDefaultUserScale

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2261]
## Is your feature request related to a problem? Please describe.
It's currently not possible.

## Relevant issues
-

## Describe the solution you'd like
A logix node "GetDefaultUserScale" which gets the **default** usescale. Specifically when a user has the "DefaultUserScale" component.

## Describe alternatives you've considered
Users to have a dynvar on them which is unreliable.

## Additional context
-

**Comment by RileyGuy** [comment]
I'm curious as to what the use-case for this would be.

**Comment by 3x1t-5tyl3** [comment]
When setting a users scale and you want to reset it to their default state which might not be 1.
You have to store it which might be incorrect.

**Comment by Frooxius** [comment]
Added in 2021.5.16.886, thanks!
