### ISSUE TITLE
Server Down Issues

### ISSUE THREAD

**Issue by BARI0926** [Neos-Metaverse/NeosPublic#2262]
![Inked20210516234254_1_LI](https://user-images.githubusercontent.com/83263433/118401469-d33dd700-b6a0-11eb-84ff-14cc8a2f1841.jpg)

Help me, please.

**Comment by Frooxius** [comment]
The servers are up, this seems like a local issue.

Is your system time correct? You could try syncing your Windows time and see if that fixes the issues.

**Comment by BARI0926** [comment]
Windows time is synchronized well Is there any other way?

**Comment by Enverex** [comment]
Is your timezone set correctly? Even if your time is correct, if the timezone is wrong then it will still break.

You probably want to hop on Discord though as the GitHub is for reporting bugs rather than general Neos help.

**Comment by shiftyscales** [comment]
Due to lack of a response, I'll be closing up this issue. Should the OP still require assistance, I advise they ask around in our Discord at https://discord.gg/neosvr as it's a better channel for technical assistance anyway.
