### ISSUE TITLE
Not being able to use Neos UI With Vive Finger Tracking

### ISSUE THREAD

**Issue by LabeVR** [Neos-Metaverse/NeosPublic#2263]
## Is your feature request related to a problem? Please describe.
Not being able to use Neos UI With Vive Finger Tracking

## Describe the solution you'd like
Making a set of gestures to accomodate the use of vive finger tracking in the ui and in the movement system

## Additional context
A screenshot of what could be the gestures is attached to this thread

Gesture For opening The main ui
![image](https://user-images.githubusercontent.com/72945521/118402948-79231e80-b66c-11eb-8ec0-e5a1af95f59d.png)

Gesture For Context menu
![image](https://user-images.githubusercontent.com/72945521/118403021-c901e580-b66c-11eb-8c5a-53d25ed17a40.png)

Highlight And Selection
![image](https://user-images.githubusercontent.com/72945521/118403098-1e3df700-b66d-11eb-8d4a-743be6261e6e.png)

Teleport Aim and Shoot
![image](https://user-images.githubusercontent.com/72945521/118403188-8987c900-b66d-11eb-9e12-6275a7ca4173.png)

**Comment by shiftyscales** [comment]
There is already an issue for this- #1456. Thanks for your submission.
