### ISSUE TITLE
Make 'Deselect All' only deselect your own and unowned gizmos.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2266]
## Is your tweak request related to a problem? Please describe.
The DevTip 'Deselect All' option currently deselects every gizmo in the session. This can be annoying when working on unrelated things from what someone else is working on, making it deselect their gizmos as well.

## Describe what would you like tweaked
Make 'Deselect All' only clear your own gizmos and gizmos of which the user has left the session.

## Describe alternatives you've considered
1. Keeping it like this which is mildly annoying at times.
2. Making custom tools that can selectively clear gizmos, which people have already done. But not everyone wants to use custom tools.

## Additional context
The 'Allocating User' node recently introduced the necessary functionality for this to happen.

**Comment by Frooxius** [comment]
Hello. This is planned to be solved by having a proper selection management system, which will replace the current method where each tool only knows its own single selection. I've added this to the roadmap here: https://github.com/Neos-Metaverse/NeosPublic/projects/7
