### ISSUE TITLE
Add a Metadata/License setter tool or LogiX node

### ISSUE THREAD

**Issue by RobertBaruch** [Neos-Metaverse/NeosPublic#2267]
## Is your feature request related to a problem? Please describe.
I'd like to import several thousand icons for use by others. However, some are CC0 and some are CC-BY. For the icons that are CC-BY, I need to add the Metadata/License component to them, but there doesn't seem to be a way to do this en masse.

## Relevant issues
https://github.com/Neos-Metaverse/NeosPublic/issues/243

## Describe the solution you'd like
Until we have component introspection/access via LogiX, perhaps a Metadata category for LogiX with two nodes: Set Metadata and Get Metadata?

## Describe alternatives you've considered
Manually handling several thousand files :( I'd also really not write a c# plugin for this, since that wouldn't really resolve the issue (that we'd like this functionality in-game)

## Additional context
https://game-icons.net/

## User
Xekri

**Comment by Frooxius** [comment]
We're already planning to add a License / Object ID system that will let you tie licensing/ownership metadata to objects and assets that should take care of this problem. You can find the main issue here: https://github.com/Neos-Metaverse/NeosPublic/issues/21
