### ISSUE TITLE
World Crashed for me only

### ISSUE THREAD

**Issue by RueShejn** [Neos-Metaverse/NeosPublic#2268]
## Describe the bug
World crashed only for me and kicked me to my home world

## Log Files
[Player-prev.log](https://github.com/Neos-Metaverse/NeosPublic/files/6490829/Player-prev.log)
[DESKTOP-Q17TSB7_-_2021.5.16.886_-_2021-05-16_20_38_57.log](https://github.com/Neos-Metaverse/NeosPublic/files/6490830/DESKTOP-Q17TSB7_-_2021.5.16.886_-_2021-05-16_20_38_57.log)

i was told to point out line 32759 and below

## Bug information:
 - Neos Version: [2021.5.16.886]
 - Neos Platform: windows

## Additional context
Was shot with a kill laser at time of crash

## Reporters:
@RueShejn #8897

**Comment by shiftyscales** [comment]
It appears #2270 is another instance of this issue.

**Comment by Frooxius** [comment]
Fixed in 2021.5.17.871, thanks!
