### ISSUE TITLE
LogiX node for primary controller chirality

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#2269]
## Is your feature request related to a problem? Please describe.
This would allow for control schemes which reliably select the user's primary or secondary controller - allowing for gestures and inputs to default to a user's hand that is less likely to be in use.

## Relevant issues
Unknown.

## Describe the solution you'd like
A LogiX node that returns the local user's primary controller `Chirality` so that it can be passed directly to the `StandardController` or other controller nodes.

Optionally an input to change the node to display the non-primary `Chirality`, or a separate node for that purpose.

## Describe alternatives you've considered
Default to Chirality: Right, since most users will use that as the primary controller.
Have a settings system that allows for configuration of primary controller.

## Additional context
None.

**Comment by chemicalcrux** [comment]
What would this do for desktop users?

**Comment by Aerizeon** [comment]
@chemicalcrux does the `StandardController` node ever return any input for desktop users? I've never checked it.

Presumably it would still return whatever is in the user's settings though, regardless of input type.

**Comment by chemicalcrux** [comment]
Ah, of course: you're just pulling it from settings. That sounds good.

I tried it after switching to desktop mode (booting up in VR). The StandardController node says it's active with a `FrooxEngine.VirtualController`, although it doesn't seem to produce output when I click or press secondary.

**Comment by 3x1t-5tyl3** [comment]
For desktop: It gives an output depending on "PrimaryController".
Example: 
![grafik](https://user-images.githubusercontent.com/61988002/118507043-2873fa00-b72e-11eb-87f8-caa51473b8a5.png)

The bottom controller node gives me an output if I have it set to left. Top one for right.

**Comment by Frooxius** [comment]
Added UserPrimaryHand in 2021.5.17.871, thanks!
