### ISSUE TITLE
Killing yourself with a certain LightSaber crashes you from the World

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#2270]
## Describe the bug
A particular lightsaber when used to kill yourself will crash you from the world. you'll end up in your Local Home. With a message about an exception

## Relevant issues
Many issues like this exist, I couldn't find anyone that's particularly like this.

## To Reproduce
1. Spawn the item from my public folder, its In Public-ProbablePrime/Bug Repros/CrashSaber
2. Turn it on (Equip and Primary)
3. Stab yourself in the face with the saber.

## Expected behavior
I expect to die and respawn but I don't expect to be crashed from the world.

## Log Files
[ALFRED - 2021.5.16.886 - 2021-05-16 17_20_24.log](https://github.com/Neos-Metaverse/NeosPublic/files/6491255/ALFRED.-.2021.5.16.886.-.2021-05-16.17_20_24.log)

Look around 22:02:04.856 for the Crash.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.16.886
 - Neos Platform: Windows
 - Link to reproduction World/Item: Public-ProbablePrime/Bug Repros/CrashSaber

## Reporters:
Me, OH⅄ƎHOHO⅄#1662

**Comment by shiftyscales** [comment]
Hmm- based on the exception at line 3311 in the log, I'm pretty sure this is the same issue as #2268.

**Comment by Frooxius** [comment]
Yes, this is the same issue, I'm closing this one ad Duplicate, will close the other when it's fixed. Thanks for report!
