### ISSUE TITLE
Multi Inverse Lerp

### ISSUE THREAD

**Issue by chemicalcrux** [Neos-Metaverse/NeosPublic#2271]
## Is your feature request related to a problem? Please describe.
Yes. I want to interpolate between 2D coordinates, and this would be a very convenient way to do it.

## Relevant issues
None found.

## Describe the solution you'd like
A way to plug more than two points into `Inverse Lerp`. The output would be the same as an `Inverse Lerp` node using the two values that the `Value` input is in between.

I am fine with bogus output if the inputs are not in strictly ascending or descending order. The regular `Inverse Lerp` node can already generate NaNs and Infinity, so a NaN output if you give it unsorted values would make sense.

## Describe alternatives you've considered
* `ValueGradientDriver<T>` lets me interpolate between many points. I originally thought its input had to be normalized to 0..1, but that is not the case. This actually makes it perfect for my use case; the only reason I'd need the node is to do the same thing in LogiX.
* I can use things like `Index Of First Match` to select the correct inputs, but that requires a comparison node for every value and gets messy.

## Additional context
Just as an example: this is an interpolation between [2,1] and [5,3]:

![image](https://user-images.githubusercontent.com/8015368/118506263-2a709580-b6fb-11eb-9ba5-e298159207af.png)

A `Multi Inverse Lerp` node would let me use more than two points here.

**Comment by Frooxius** [comment]
This is a bit tricky, because this inherently introduces ambiguity. Say you have points 0, 5, 2.  If you give it value 3, does that lie between 0...5 or 5...2? Both are valid solutions.

What are you trying to achieve with this? It sounds like there might be different solution for the underlying problem.

**Comment by chemicalcrux** [comment]
I was just advised by Banane9 on the Discord that I can get almost exactly what I need from `ValueGradientDriver<T>` -- you can just plug in the X values as the positions and assign incrementing values to each one. It even winds up working properly if the entries are out of order.

![image](https://user-images.githubusercontent.com/8015368/118507893-a9b29900-b6fc-11eb-978d-f2f073294d87.png)

This interpolates from [0,0] to [3,3] to [5,0].

> What are you trying to achieve with this? It sounds like there might be different solution for the underlying problem.

I am doing basic animations with blendshapes. I want to interpolate between values at specific times -- e.g., quickly ramp up to 1, then slowly drop to 0.7, then quickly drop back to 0.

The above `ValueGradientDriver<T>` trick is very close to what I need. The only issues are that I can't do smooth interpolation (e.g. cosine lerp) with it, and that it's not directly usable in LogiX.

A `Multi Inverse Lerp` node would accomplish the same thing as the first gradient driver in that picture. The existing `Multi Lerp` node can already do the job of the second one.

>This is a bit tricky, because this inherently introduces ambiguity

I'd be okay with it just emitting a NaN, since unsorted inputs would produce more than one solution for the equation.

**Comment by chemicalcrux** [comment]
As an alternative, just adding a way to set the curve used by the `ValueGradientDriver<T>` component would be great. I could open a separate issue for that.

**Comment by Frooxius** [comment]
Hmm yeah, it would be better in general, probably best solution there is to actually have component that interpolates value along a curve.

MultiLerp just isn't function that's directly invertible, as the inverse results in potentially multiple valid solutions, so I don't think we can add it in some sensible way.

**Comment by chemicalcrux** [comment]
Yeah, that sounds smartest. I will look into opening an issue for that if one doesn't exist.
