### ISSUE TITLE
HP Omnicept API support

### ISSUE THREAD

**Issue by InsaneGrox** [Neos-Metaverse/NeosPublic#2275]
## Is your feature request related to a problem? Please describe.
Currently the HP reverb G2 Omnicept's eye/lip tracking sensors are unused in neos.

## Relevant issues
#1140

## Describe the solution you'd like
Support for HP's API to be implemented to drive the eye manager & expression driver.

## Describe alternatives you've considered
#1140

## Additional context
NOTE: I do not actually own a reverb G2 omnicept... I'm simply making this issue since the omnicept version of the reverb G2 recently came out... I may however consider buying this HMD later down the line if the HTC vive pro 2 doesn't get an eye tracking version. The HP reverb G2 omnicept is purchasable by consumers so supporting this HMD's eye/lip tracking features would make sense. (especially because the HTC vive pro eye & facial tracker are already supported)

**Comment by shiftyscales** [comment]
APIs and other resources are available through hp's Developer Portal for the Omnicept: https://developers.hp.com/omnicept

From what I've read, it can be integrated/redistributed for free with a 'Core' license. https://h20195.www2.hp.com/v2/GetDocument.aspx?docname=4AA7-8437ENW

There would still be time required to actually investigate the viability of implementation of the hardware into Neos' existing systems.

**Comment by Frooxius** [comment]
Added the eye tracking support in 2021.5.19.1273! Currently untested with HW, but worked with emulator (what I could test). So far there are no traces of lip tracking unfortunately. I could add Heart rate too if you want, I'd have to think about how to handle that one in general though, I'd make a separate issue for it as well as one for lip tracking once they make it available!

**Comment by ProbablePrime** [comment]
For some clarification(for the next person who comes through here). When Frooxius mentioned lip tracking. I got a little confused. 

So it seems like HP themselves don't have any documentation or resources available regarding the lip tracker on the HP Omincept. Check: https://developers.hp.com/omnicept/docs/unity/sensors For more.

**Comment by shadowpanther** [comment]
To clarify, API only provides the raw [camera image](https://developers.hp.com/omnicept/docs/unity/sensors#cam), the software part for expression recognition/tracking is not there (yet?).

**Comment by Frooxius** [comment]
Yes. There's nothing that would provide actual lip tracking weights in the SDK that I could find. Until HP provides that functionality or there's a 3rd party one that we could utilize, we cannot integrate this.
