### ISSUE TITLE
Settings menu to customize video, audio and other settings

### ISSUE THREAD

**Issue by cubiform** [Neos-Metaverse/NeosPublic#2276]
## Is your feature request related to a problem? Please describe.
It's currently not possible to change your graphics, audio and other settings (ie. disable motion blur, degrade graphic settings, enable push to talk, etc).

## Describe the solution you'd like
A settings menu, just like in every other game, that allows you to toggle settings like VSync, PTT, graphics, motion blur, etc)

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by 3x1t-5tyl3** [comment]
#322 seems fairly well related to this.

**Comment by H3BO3** [comment]
Neos already does have a settings menu, it's just that particular settings are not exposed (Graphics, motion blur), or particular mechanisms that would require a setting still need to be implemented (PTT). If you have specific feature requests you would like to make, please open issues for them if they do not already exist. The settings menu is also due for an overhaul, which should help with the addition of new settings in the future: https://github.com/Neos-Metaverse/NeosPublic/projects/2#card-61033408 Motion blur in particular is related to issue 322, as 3x1t just mentioned.
