### ISSUE TITLE
Allow Mouse Wheel Scrolling when in FreeCam mode

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2279]
## Is your tweak request related to a problem? Please describe.
You're unable to scroll UIX and of the sort while in Freecam mode, only when you're in aligned mode

## Describe what would you like tweaked
I'd like to be able to scroll things while in Freecam mode, not just First Person, Third Person & aligned mode

## Describe alternatives you've considered
Not allowing me to scroll in freecam mode.

## Additional context
Null

**Comment by Frooxius** [comment]
Ah this was a bug with improperly defined input bindings, fixed in 2021.5.19.1273, thanks!
