### ISSUE TITLE
Add User Voice to the Freecam Visual

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2281]
## Is your tweak request related to a problem? Please describe.
I would like for user's voices to be applied to their freecam camera, people expect their voices to come from where they see, and to me this would make sense.

## Describe what would you like tweaked
I would like the default Freecam visual to have the user's voices coming from it, while disabling the one on their avatar so their voice wont be heard twice.

## Describe alternatives you've considered
I'm not sure of any alternatives

## Additional context
Currently, only your hearing comes from the visual, but your voice doesn't.

**Comment by shiftyscales** [comment]
As explained in the patch notes for the release of the freeform camera (build 2021.5.13.384), this is already a planned addition.

- Added initial version of Freeform Camera mode, which allows to freely move view around independently of the character
-- To activate/deactivate, press the F6 key (note this is tentative and the keybinds will change in the future)
-- When activated, the mouse cursor is freed, allowing you to freely interact with items, gizmos and other elements
-- To pan/move around, first hold the Ctrl and then the Right Mouse Button. You can use WASD, C and Space to move the camera in this mode
-- Note that you can let Ctrl go after holding the right mouse button, it will keep the pan/move mode active
-- By holding left mouse button you can make the character turn towards the current cursor hit and use locomotion to walk around (movement in this mode is relative towards the cursor, meaning W will walk towards where your cursor hits on the screen)
-- More behaviors are planned:
--- Focusing a specific object in the world and being able to orbit it around
--- **Having the voice come out of the view proxy when it's sufficiently far away**

https://discord.com/channels/402159838827905024/469131434628612116/842288372482310164

**Comment by AshtonSparx** [comment]
Thank you! I forgot that part of the patches (And I read them too when it was first released) <3

**Comment by mralext20** [comment]
this should stay open, to track the known issue.

**Comment by shadowpanther** [comment]
I would suggest keeping both sound sources, but playing only one that is locally closer. So that you can continue to talk to the avatar while the free camera works somewhere else. To be fair, that would also require for the freecam user to be able to hear from both places that could be disorienting a bit.
I'm not sure what is the best way to do this in a situation where the "mind" gets disconnected from the "body". Give the proxied voice a "walkie-talkie" filter to signify that the user is not entirely here, for example, and vice-versa for the hearing proxy of the freecam user.

**Comment by Frooxius** [comment]
This has been added in 2021.5.20.1063 now!
