### ISSUE TITLE
Mipmap toggle for textures

### ISSUE THREAD

**Issue by InsaneGrox** [Neos-Metaverse/NeosPublic#2282]
## Is your feature request related to a problem? Please describe.
Currently there is no way to completely disable mipmaps on a texture... While this is bad practice for textures that are used in the environment... This should still be an option as it is useful for UI textures. Icons. Particles. Light cookies. as well as skyboxes.
The problem is that mipmaps on UI & icons cause them to become blurry & unreadable at times... while skyboxes just eat more VRAM (which does not help because of how high res they have to be to look good already)...

## Relevant issues
N/A

## Describe the solution you'd like
A checkbox that disables mipmap generation entirely on a texture... This would both be useful for saving VRAM by disabling mipmaps on textures that do not need them (such as UI/Icons) and possibly even usable for a stylistic effect when re-creating old video game graphics... (or dealing with already low res textures)

## Describe alternatives you've considered
1: Setting all of the UI to use anisotrophic filtering which eats both VRAM and preformance by comparison...
2: Mipmap levels setting... This would be preferrable as you'd be able to specify the maximum amount of mipmap levels on a texture... this would be useful since let's be honest... going all the way down to 4x4 is a bit overkill & excessive in most cases.
3: #924 - I guess this would alleviate the VRAM cost from mipmaps? though it wouldn't fix the actual problem of "why are there mipmaps on my UI that does not need them"

## Additional context
N/A

**Comment by Frooxius** [comment]
This can be added, but for UI I don't think it's a good solution, since you'll get aliasing instead of bluriness. You could either use MipMap bias or we could look into exposing different MipMap filters that could produce sharper results.

**Comment by Frooxius** [comment]
Added MipMap toggle as well as MipMapFiltering in 2021.5.20.1063, thanks!
