### ISSUE TITLE
LogiX Node to Get Slot's Fields

### ISSUE THREAD

**Issue by seif1** [Neos-Metaverse/NeosPublic#2285]
# LogiX Node to Get Slot's Fields

## Is your feature request related to a problem? Please describe.
It is currently impossible to use the CreateFieldUndoStep, CreateTypeFieldUndoStep, Driver, and Tween LogiX nodes on slots or fields without a hardcoded reference.

## Relevant issues
#243

## Describe the solution you'd like
Implementation of a LogiX node which allows you to input a slot, and it gives you the fields for that slot (Name, Parent, Tag, Active, Persistent, Position, Rotation, Scale, OrderOffset).

## Describe alternatives you've considered
Instead of accepting only a slot type, it can accept any reference, and the outputs can change based on the fields relevant to that type, 
- for a slot, it would be the same as above, 
- for a IComponent, it could give that components persistent, UpdateOrder, and Enabled fields, 
- for a reference to a valueField component, it could give the Value IField.

**Comment by Frooxius** [comment]
This falls under the Component access for LogiX: https://github.com/Neos-Metaverse/NeosPublic/issues/243
