### ISSUE TITLE
UserInterfacePositioner does not track view

### ISSUE THREAD

**Issue by seif1** [Neos-Metaverse/NeosPublic#2286]
# UserInterfacePositioner does not track view

## Is your tweak request related to a problem? Please describe.
Currently, the UserInterfacePositioner component always follows the head of the avatar, regardless of if they are using the desktop camera modes.

## Describe what would you like tweaked
Checkboxes added to the UserInterfacePositioner component that lets the user choose which view targeting controllers should be tracked.

## Describe alternatives you've considered
- This component should follow the view of the user at all times.

**Comment by Frooxius** [comment]
It now uses view by default in 2021.5.19.1273! You can toggle old behavior using UseHead. Thanks!
