### ISSUE TITLE
Allow InventoryLink components to be disabled

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#2288]
## Is your feature request related to a problem? Please describe.
Currently, when saving a grabbed object that contains an `InventoryLink`, even if it is disabled, the `InventoryLink` will be saved instead of the object as a whole.  If the `InventoryLink` target is null, nothing will be saved.
This does not occur when saving from the inspector.

## Relevant issues
#1984

## Describe the solution you'd like
Have `InventoryLink` respect its enabled/disabled state, such that it will not save as a folder if it is disabled
and/or
Have an option on the `InventoryLink` such that it only overrides the rest of the object if the component is directly on the item being grabbed, and the Target is not null.

## Describe alternatives you've considered
Coaching users on how to save items via inspector, in worlds where they have build permissions
Coaching users on how to create `InventoryLink`s manually from URL, in worlds where they have build permissions.

## Additional context
Inspired by question from art0007i

**Comment by Frooxius** [comment]
Enabled is now respected in 2021.5.19.1273, thanks!

**Comment by ukilop** [comment]
...it still populates the "Copy Link" button into context menu
