### ISSUE TITLE
OAuth Logins Look Super Sketchy

### ISSUE THREAD

**Issue by Geenz** [Neos-Metaverse/NeosPublic#2293]
## Is your tweak request related to a problem? Please describe.
At present, OAuth logins look incredibly sketchy.  Between the lack of Neos branding, to the azurewebsites URL - an average user is likely to think this is a fake website trying to steal their Neos credentials.

## Describe what would you like tweaked
Addition of Neos branding to the OAuth page, and if possible moving it over to the `neos.com` domain- preferably `auth.neos.com` or similar.

## Describe alternatives you've considered
Explaining to users of external tools that it's legit.  Though, this usually falls apart.

## Additional context
This is brought over from ConCat and VBLFC's feedback regarding OAuth.  There's a high level of concern that by directing users to the OAuth login page it's tempting fate as far as user reaction.  Additionally, having unbranded OAuth pages like this is seen as bad practice due to the increased chances of someone successfully phising people's accounts.

**Comment by ProbablePrime** [comment]
I agree, I should be able to update the look and feel a little bit to provide more Neos Branding.

**Comment by Frooxius** [comment]
The domain is already planned, we just need to create a subdomain at account.neos.com and move the website there, I'll be talking to Karel about that.

However the branding of the website is trickier, we'd need somebody to do a design. I could throw a logo there at least for now.

**Comment by ProbablePrime** [comment]
Logo sounds good. Perhaps a footer update too.

**Comment by Geenz** [comment]
> 
> 
> The domain is already planned, we just need to create a subdomain at account.neos.com and move the website there, I'll be talking to Karel about that.
> 
> However the branding of the website is trickier, we'd need somebody to do a design. I could throw a logo there at least for now.

Yeah, I think just slapping our logo on it for now is fine as far as branding.

**Comment by Frooxius** [comment]
The website is now available at https://auth.neos.com thanks to @Karel-Owen-Watts setting up the subdomain and the certificates. Just need to make it look a bit more official visually now :D

**Comment by ProbablePrime** [comment]
![image](https://user-images.githubusercontent.com/8791132/119250917-3e335600-bb58-11eb-8432-276157f056bb.png)

Some previews, nothing rocket science or ground breaking here. Just giving a lick of paint that increases user confidence. 

A larger, more fully featured website would require some sort of basic design from the team but this will be good for now.

**Comment by Frooxius** [comment]
Thank you, merged in and live as of 2021.5.23.985 now! Should look a lot less sketchy now hopefully! :D
