### ISSUE TITLE
AvatarPoseSmoothLerp freaks out while holding in desktop

### ISSUE THREAD

**Issue by Beaned2000** [Neos-Metaverse/NeosPublic#2294]
## Describe the bug
Whenever an object has a AvatarPoseSmoothLerp on it, it freaks out when you hold it in desktop with.

## Relevant issues
/

## To Reproduce
[Steps to reproduce the behavior:
1. Attach the AvatarPoseSmoothLerp component.
2. Attach the GrabbableAvatarPoseFilter component (to make it work).
3. Make sure the object is grabbable.
4. Grab the object in desktop mode with.

## Expected behavior
It lowering the sensitivity of the mouse input or/and smoothing out the motion.

## Log Files
/

## Screenshots / Video
The video only shows in third person but it also happens in firstperson (just harder to show)

https://user-images.githubusercontent.com/29598202/118804583-27b1a400-b8a5-11eb-9b5e-7ed07147bbb5.mp4

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2020.5.17.909
 - Neos Platform: Windows
 - Link to reproduction World/Item: /
 - Regression: /

## Additional context
When the item is made into an equippable, it seems to sort off work as intended (this might be laser related maybe?)

## Reporters:
Beaned#1111

**Comment by Aerizeon** [comment]
Duplicate of #2153

**Comment by Beaned2000** [comment]
woops my bad will close this one
