### ISSUE TITLE
1D variant of "Distance" LogiX node

### ISSUE THREAD

**Issue by Honzackcz** [Neos-Metaverse/NeosPublic#2295]
## Is your feature request related to a problem? Please describe.
I found out that the Distance node doesn't have 1D variant that can be sometimes useful or at least more elegant/efficient.

## Relevant issues

- 

## Describe the solution you'd like
Just adding the 1D variant of Distance node. It is basically simple mathematical operation: X = |A - B| 

## Describe alternatives you've considered
Right now you can do the same with minus and abs node.

## Additional context
![unknown](https://user-images.githubusercontent.com/76910833/118828263-66535880-b8bd-11eb-8904-fbc37fbb95af.png)

**Comment by Frooxius** [comment]
Added in 2021.5.19.1273, thanks!
