### ISSUE TITLE
LookAtUser does not respect TargetAtLocalUser when in freecam Mode

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2296]
## Is your tweak request related to a problem? Please describe.
Currently, when TargetAtLocalUser is on and you're in freecam mode, it does not respect other camera modes & look at your current viewpoint. 

## Describe what would you like tweaked
For TargetAtLocalUser to be able to target FreeCam camera

## Describe alternatives you've considered
Have a separate Bool to allow the component to target Freecam mode enabled users. So things like nameplates still look at the users regardless of what mode they're in

## Additional context
This would also need to be done to AutoLookAtUser

**Comment by Frooxius** [comment]
Added "View" as another target in 2021.5.20.1063. Instances that targeted Head are auto-updated for this so they always look at the view, but you can change it back if needed.
