### ISSUE TITLE
TextRenderer AutoSize formatting is sometimes erratic and skewed

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#2297]
## Describe the bug
When the TextRenderer component is given certain length words or strings, it often skews the box entirely and makes a mess of the layout.

## To Reproduce
1. Create a TextRenderer component.
2. Create a box around the bounds to see where they should be.
3. Enable the two AutoSize options and then enter text of different lengths.

## Expected behavior
Formatting should remain consistent and scaling should apply correctly.

## Screenshots / Video
Lots of text: fine.
![image](https://user-images.githubusercontent.com/958670/118854543-c0a7e580-b8cc-11eb-838b-7bed84fca410.png)

Medium amount of text: skewed.
![image](https://user-images.githubusercontent.com/958670/118854572-cb627a80-b8cc-11eb-988b-096b38685de9.png)

Small amount of text: fine.
![image](https://user-images.githubusercontent.com/958670/118854613-d5847900-b8cc-11eb-8cc2-b895f0b05f6e.png)

Medium amount of text: fine.
![image](https://user-images.githubusercontent.com/958670/118854668-dd441d80-b8cc-11eb-90b6-d20be39931ef.png)

Medium amount of text: skewed.
![image](https://user-images.githubusercontent.com/958670/118854716-e6cd8580-b8cc-11eb-8d25-19e697cea0d4.png)

Finally a GIF showing how one character causes (or breaks, depending on how you're looking at it) the formatting.
![TextIssue](https://user-images.githubusercontent.com/958670/118854798-fbaa1900-b8cc-11eb-8b1a-05fe0e8ddc44.gif)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Regression: No

**Comment by Frooxius** [comment]
Is this consistent or random? E.g. if you erase and add the same character, does it always produce the same offset?

What exactly does "skew" and "mess of layout" mean in this context? It seems like it might be offsetting the text incorrectly in the last one? The static images don't look necessarily wrong to me, so I'm not fully sure what I should be looking for.

**Comment by Enverex** [comment]
Consistent in that if you type the same text again, it'll skew again, so it's 100% repeatable with the same text. Seemingly random in terms of what can trigger it in the first place (I assume it's due to the size of the contents, so not really random).

By "skew" I mean suddenly everything ends up offset to the right, even the boundary of the text box shifts down and right compared to when it's working properly. The text should be (and is when it's working properly) centred on the screen in the example images. both vertically and horizontally.

In my animation, you can see it's centred until I remote the E, at which point it suddenly jumps down and right, no-longer being centred.

**Comment by Frooxius** [comment]
I see thanks! Can you send me a reproduction item or the font used for this? I haven't really seen this behavior, so I'd need a way to replicate it to see what's going on.

**Comment by Enverex** [comment]
Here's the font from the example pictures above. If you have trouble recreating it, I can send you the text box in game too.
[MUSICNET.zip](https://github.com/Neos-Metaverse/NeosPublic/files/6518293/MUSICNET.zip)

**Comment by Frooxius** [comment]
Fixed in 2021.5.22.1024, the auto-size code wasn't properly respecting the bounds alignment, causing small random offsets. Should be good now!
