### ISSUE TITLE
AvatarPoseSmoothLerp not lerping on RawDataToolTip items when equipped

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2300]
## Describe the bug
AvatarPoseSmoothLerp does not apply it's lerp on equip if the equip happens when clicking on a RawDataToolTip and then "Equip" on the context menu.

## Relevant issues
#2153 #2299

## To Reproduce
1. Trigger click on the tool to bring up the context menu on the tool
2. Press "Equip" 

## Expected behavior
The filter should apply it's lerp to the hand.

## Log Files
Nothing in the logs.

## Screenshots / Video
Will supply video/item tomorrow am going to sleep and don't wanna lose progress but still have this recorded.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.19.1330
 - Neos Platform: Windows
 - Link to reproduction World/Item: Will supply video/item tomorrow am going to sleep and don't wanna lose progress but still have this recorded.
 - Regression: No clue.

## Additional context
-

## Reporters:
3x1t_5tyl3# 0001

**Comment by Frooxius** [comment]
This seems like a normal behavior, how are you installing AvatarPoseSmoothLerp? I don't believe we have a way to install pose filters on Equip right now.

**Comment by Frooxius** [comment]
This is not a supported feature, pose filters aren't (and cannot) be installed like this, they require extra information like install Priority. Components like GrabbableAvatarPoseFilter are required to install them on an action (in this case grabbing). I'd recommend making a request for component to install pose filters on Equip if you'd like this functionality.

**Comment by 3x1t-5tyl3** [comment]
Closin gin favor of a request then.
