### ISSUE TITLE
Export Image to Desktop as PNG changes the colours of the image

### ISSUE THREAD

**Issue by Cataena** [Neos-Metaverse/NeosPublic#2301]
## Describe the bug
Some textures, when saved to desktop as png, shift their colours. This was noted by both Lucaedr (in March) and myself today. Vegasx, Zeffy and I tried to save my avatar's texture to desktop as png, but it shifted to lighter colours.

## Relevant issues
Not that I could find.

## To Reproduce
[Steps to reproduce the behavior:
1. Spawn image out in world
2. Export to desktop, with PNG as the file type.
3. Look at the image on your desktop, it has very different colours from the original Neos image.

## Expected behavior
You should be able to export the exact image, they should be identical.

## Log Files
Let me know if you need these for this issue.

## Screenshots / Video
![image](https://cdn.discordapp.com/attachments/439422161657135106/844739541922480138/20210519205044_1.jpg)

![image](https://user-images.githubusercontent.com/76889792/118913359-4d679900-b8f7-11eb-9bb3-a44b1aa0fc86.png)

## Bug information (please complete the following information):
 - How often does it happen: Only on this image, for all users 
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.19.1330
 - Neos Platform: Windows
 - Link to reproduction World/Item: Can send in Neos, don't want to attach my custom skin
 - Regression: Never used export feature before this

## Additional context
Rue made the texture for me in Substance Painter, but we tested many other Substance Painter files and this still seems to be the only one that we found with the issue.

## Reporters:
Cataena#3067 Lucaedr#4319

**Comment by Frooxius** [comment]
This is what usually happens with high bit depth that don't get tonemapped properly. Can you send me examples so I can have a look at what's their format and make corrections?

**Comment by Frooxius** [comment]
Fixed in 2021.5.22.1024, thanks!
