### ISSUE TITLE
EquipableAvatarPoseFilter - AvatarPoseFilter for items that are equiped

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2303]
## Is your feature request related to a problem? Please describe.
Not possible.

## Relevant issues
#2299 #2300 #2153 

## Describe the solution you'd like
A seperate component to be able to install AvatarPoseSmoothLerp (and similar filters if there are any that I missed?) on equipabble items such as RawDataToolTip or similar.

Ergo "EquipableAvatarPoseFilter" for being able to equip the item through ContextMenu, Laser-drag-in or similar.

## Describe alternatives you've considered
Custom behaviour through logix by grabbing the hand targets which might not work on users who have renamed them causing it to break.

## Additional context
As noted in #2300 this request is upon sheer impossibility.
Further info is also in #2299.

**Comment by Frooxius** [comment]
Added in 2021.6.7.794!
