### ISSUE TITLE
Integer variant for "Repeat" LogiX node

### ISSUE THREAD

**Issue by Honzackcz** [Neos-Metaverse/NeosPublic#2304]
## Is your feature request related to a problem? Please describe.
I found out that the Repeat node doesn't have integer variant that can be sometimes useful or at least more elegant/efficient.

## Relevant issues
- 

## Describe the solution you'd like
Just adding the integer variant of Repeat node.

## Describe alternatives you've considered
Right now you can do the same with float variant of Repeat node and converting int to float/float to int.

## Additional context
![unknown](https://user-images.githubusercontent.com/76910833/119008208-404bb800-b992-11eb-9dc9-fa588ebc3ab5.png)

**Comment by Frooxius** [comment]
Added in 2021.5.20.1063, thanks!
