### ISSUE TITLE
InventoryLink populates the "Copy Link" context menu option when Disabled

### ISSUE THREAD

**Issue by ukilop** [Neos-Metaverse/NeosPublic#2306]
## Describe the bug
Title

## Relevant issues
#2288

## Expected behavior
"Copy Link" should not appear in context menu when InventoryLink is disabled

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 5.20.1063
 - Neos Platform: Windows

**Comment by Frooxius** [comment]
Fixed in 2021.5.22.1024, thanks!
