### ISSUE TITLE
Does NeosVR use a template for FinalIK/VRIK default values?

### ISSUE THREAD

**Issue by mxkris** [Neos-Metaverse/NeosPublic#2307]
## Where have you searched for this information before making this issue?
NeosVR discord server, google, github, NeosVR wiki

## Which part of the system do you need information on?
FinalIK/VRIK

## What information do you need to know?
Does NeosVR use a default FinalkIK/VRIK settings .json before applying values from the auto-detect/config when importing an avatar? If so, can you provide them?

## Do you plan to format and contribute the provided information to Wiki?
I would be more than happy to.

**Comment by Frooxius** [comment]
No, there is no .json file involved at all. All the parameters are setup and initialized from the rig itself, using a combination of heuristics and fine-tuned defaults that should produce good base behavior for most avatars.

**Comment by mxkris** [comment]
Thank you for your reply and sharing these insights. Some follow-up questions:

For the sake of the testing I'm trying to do, when an avatar is imported and set up in Neos, are the IK values stored anywhere in a local file that is human readable? If so, where are those files located?

The reason I ask is I want to see if the configuration that is generated by Neos could potentially be applied to override the defaults used by LIV. If the values are only visible within the client, I could just view the values there and transfer them over to the LIV settings by hand if necessary.

I know this is relatively off topic from Neos so any additional information you are willing to provide is very much appreciated.

Worth noting, Neos seems to handle IK much better than LIV; you folks did a great job with that. Potentially being able to use neos as a tool to help me better understand/configure my avatars for VR in general would be awesome.

**Comment by Frooxius** [comment]
They're unfortunately not easily accessible in a human readable format outside of the inspector. The IK itself has also been significantly modified, so it has numerous tweaks and fixes in the way it operates to improve its behavior and there are more behaviors on top of it, so even with the same values you won't likely get the same results.

**Comment by mxkris** [comment]
Understood, thanks again.

I assume said modifications are proprietary; is this correct, or are you able/willing to share the kinds of changes that were made?

**Comment by Frooxius** [comment]
The changes are proprietary and unfortunately not compatible with anything outside of Neos anymore, since the original code was reworked to support Neos' own architecture and data model.

**Comment by mxkris** [comment]
Got it.

Thank you kindly for your time, insights and transparency.
