### ISSUE TITLE
UI Aligning to UIX panels makes UI visuals un-readable

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2314]
## Describe the bug
When aligning to UIX panels, the panels Z-fight like crazy, viewing them any other way on desktop mode & VR looks fine.

## Relevant issues
None I could find

## To Reproduce
1. Use desktop mode (Either start in Desktop or press F8 in VR)
2. Go to basically any UIX panels & UI Align (CTRL+Left Click onto it)
3. Preview the Z-Fight

## Expected behavior
Should not Z-Fight when looking at UI straight on with UI Align

## Screenshots / Video
![image](https://user-images.githubusercontent.com/53165730/119211922-3190fe00-ba83-11eb-979d-6ccc7fd1bb0a.png)
![image](https://user-images.githubusercontent.com/53165730/119211958-70bf4f00-ba83-11eb-9d8f-2a9b15bbb96c.png)
![image](https://user-images.githubusercontent.com/53165730/119212035-fd6a0d00-ba83-11eb-8298-53af047e87e3.png)

## Bug information (please complete the following information):
 - How often does it happen: Sometimes
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.20.1063
 - Neos Platform: Windows
 - Link to reproduction World/Item: --
 - Regression: No

## Additional context
It seems to mostly happen to any UIX that has a material, however, the last image in Screenshots, has no material but has sprites so idk

## Reporters:
AshtonSparx#5050

**Comment by Aerizeon** [comment]
Are you setting the material offset up properly?

**Comment by AshtonSparx** [comment]
Background
![image](https://user-images.githubusercontent.com/53165730/119213706-3491eb80-ba8f-11eb-8872-d41d8b371de0.png)
Behind Panel
![image](https://user-images.githubusercontent.com/53165730/119213716-4d9a9c80-ba8f-11eb-86b4-675ef23d78b7.png)

**Comment by Aerizeon** [comment]
Originally, they were supposed to be 1/1
Now it's supposed to be 1/100 (based on builtin UIX)

**Comment by Frooxius** [comment]
@Aerizeon Is correct, you need to setup your materials properly for this. Recommended values are 1 and 100 to avoid Z-fighting, particularly when the camera is perfectly aligned with the view.

If you experience this with any default UI's reopen the issue, but otherwise it's something content creators need to do when making customized UI's.
