### ISSUE TITLE
Integer/Byte variant for "0 1" LogiX node

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2315]
## Is your feature request related to a problem? Please describe.
I found out that the 0 1 node doesn't have integer variant that can be sometimes useful or at least more elegant/efficient.

## Describe the solution you'd like
adding the integer variant of 0 1 node.

## Describe alternatives you've considered
Right now you can do the same with float variant of 0 1 node and converting int to float/float to int or byte.
![float-to-int-for-01](https://user-images.githubusercontent.com/6259214/119223946-154e9900-bb37-11eb-9bb1-0add12c1fee4.png)

## Additional context
When I asked the Japanese community about this before, many people (including myself) said that they would like to see it if it were possible, so I created this as an issue.

**Comment by shadowpanther** [comment]
You can also do this for any type with `?:` node. Also, how would the overload work in this case? The node doesn't have an overloadable input. I guess the only option would be to have separate `0 1` typed nodes in the LogiX picker.

**Comment by kazu0617** [comment]
Yeah, I also this things, add an option, or change the type to integer since 0 1 is assumed to be an integer (but in this case, you will need to inject something like the previous "Get Slot by Name" update).

**Comment by Frooxius** [comment]
This is a bit tricky. The common use-case for this node is for Lerp nodes, when you need to lerp between the values. Changing it to integer would cause the same problem as above - a cast would be inserted in all those cases, converting integer to float.

There could potentially be a separate integer version, but we'd need to differentiate it somehow. What are your use-cases where you need this node to be integer?

**Comment by shadowpanther** [comment]
Just changing `0 1` into an int node would be much worse, as usually it plugs into something like a blendshape drive or a smooth lerp.

**Comment by ukilop** [comment]
`0 1f` and `0 1i`? one of my use cases is to 0 1 the index of a 2length demultiplexer, two channels of data, 0 does nothing, 1 crosses the channels 
![2021-05-23 07 33 35](https://user-images.githubusercontent.com/1341270/119260621-3fd13e00-bb99-11eb-83b7-91eccb3483be.jpg)

**Comment by kazu0617** [comment]
> maybe `0 1f` and `0 1i` to differentiate?

yeah, that is what i want to say.
You don't need to replace it (in fact, I don't think replacing it is very practical, as Frooxius said).

**Comment by Honzackcz** [comment]
> maybe `0 1f` and `0 1i` to differentiate? one of my use cases is to 0 1 the index of a 2length demultiplexer, two channels of data, 0 does nothing, 1 crosses the channels
> ![2021-05-23 07 33 35](https://user-images.githubusercontent.com/1341270/119260621-3fd13e00-bb99-11eb-83b7-91eccb3483be.jpg)

Instead of using demultiplexer will be way more easier to use `?:` node.

**Comment by Epimonster** [comment]
I've actually needed this on multiple occasions, the most obvious use case I can think of is for two element multiplexers which have their index driven by an integer. For example, toggleable materials that are based on a boolean could be connected using an integer 1 0 node instead of casting a float 1 0 node. while it is not 100% necessary it would be a nice enhancement.
