### ISSUE TITLE
Cosine curve preset option for Tween node

### ISSUE THREAD

**Issue by Dirko3000** [Neos-Metaverse/NeosPublic#2316]
## Is your tweak request related to a problem? Please describe.
There is no option in the tween node for a Cosine curve where the transition starts slow and accelerates to full speed, opposite of the existing Sine option which starts at full speed and slows to a stop.
All that is available is Linear, Smooth, Smoother, and Sine.

## Describe what would you like tweaked
The addition of a Cosine curve preset on the Tween logix node, allowing for animation to ease in, but not out.

## Describe alternatives you've considered
Other than trying to manually construct this behavior with some kind of math and lerp, there doesn't seem to be any decent way to do this.

## Additional context
I came to Neos from Anyland, which has a large focus on tweened 3D transitions/animation of shapes, and the only transition option which is missing from Neos's tweening that Anyland has is the slow-start curve, which would be Cosine I believe.

_EDIT:_ Not sure if the "feature request" tag would have been more appropriate or if "tweak" as I put it is accurate.
_EDIT 2:_ Not actually sure if cosine is the right description for easing in, but I don't know what else to call it, so I am not going to bother trying to reword it. I am sure the idea got across.

**Comment by Frooxius** [comment]
Added in 2021.5.23.985 thanks!
