### ISSUE TITLE
TextRenderer Hard-Wraps Unnecessarily

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#2317]
## Describe the bug
Odd/inconsistent choices are made regarding text wrapping, especially unnecessary hard line-breaks on words.

## Relevant issues
This is in a similar vein to https://github.com/Neos-Metaverse/NeosPublic/issues/2297 and still exists after that fix.

## To Reproduce
1. Create a text box.
2. Write different length strings into it.
3. Ensure auto-height/width are enabled.

## Expected behavior
For the font size to shrink if words cannot fix into the allocated bounds, word breaks could be expected on VERY long words, but nothing to this extent. I've tried this with several different fonts and the issue persists so it doesn't seem to be font specific.

## Screenshots / Video
Examples of it working as expected:
![image](https://user-images.githubusercontent.com/958670/119236718-d9183a00-bb30-11eb-9fc9-95f4fde5217a.png)

![image](https://user-images.githubusercontent.com/958670/119236761-1bda1200-bb31-11eb-8435-e6fcba7b37d0.png)

Example of it not working properly:
![image](https://user-images.githubusercontent.com/958670/119236873-aa4e9380-bb31-11eb-8d4e-a86856afd110.png)

Interestingly it decides to hard-wrap the same word in this scenario:
![image](https://user-images.githubusercontent.com/958670/119236808-5479eb80-bb31-11eb-8f5d-2daa5ee8aec5.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Regression: No

**Comment by Frooxius** [comment]
What is the configuration of the text renderer used to replicate this? Do you have a sample that you can send me?

Usually this can happen if the minimum allowed size is reached and it cannot fit in the text anymore.

**Comment by Enverex** [comment]
Size is set high so that if there's only a small amount of text, it'll still fill the text-box.

![image](https://user-images.githubusercontent.com/958670/119242789-d3cee580-bb58-11eb-9f19-bb188ba89785.png)

**Comment by Frooxius** [comment]
I see. Can you send me a sample that reproduces this problem with the improper wrapping please?

**Comment by Enverex** [comment]
Sent yesterday FYI.

**Comment by Frooxius** [comment]
Thanks! I was able to find two major bugs with the text rendering that were responsible for this, the sizing and layout should now be stable in 2021.5.23.985!
