### ISSUE TITLE
Possible Windows memory leak (regression?)

### ISSUE THREAD

**Issue by RobertBaruch** [Neos-Metaverse/NeosPublic#2318]
## Describe the bug
On startup, Neos used 3GB. After a few hours of messing about with Logix, staying in a single world, the process eventually reached 6GB and swapping caused noticeable pauses. My main activity was writing and running Logix and packing and unpacking Logix with Ukilop's Redprints.

## To Reproduce
1. I dunno, run Neos for a while? Run it under the equivalent of valgrind except for C#?

## Expected behavior
Muh memory! Stop using it all!

## Log Files
[DESKTOP-CQBEQLG - 2021.5.20.1063 - 2021-05-22 07_36_45.log.zip](https://github.com/Neos-Metaverse/NeosPublic/files/6527290/DESKTOP-CQBEQLG.-.2021.5.20.1063.-.2021-05-22.07_36_45.log.zip)

There seem to be a lot of `Enumerating reachable nodes has reached a disposed node!` in there, that were not present yesterday.

## Bug information (please complete the following information):
 - How often does it happen: Only Once
 - Does the bug persist after restarting Neos? Unknown, restarting loaded a newer version.
 - Neos Version: 2021.5.20.1063
 - Neos Platform: Windows
 - Link to reproduction World/Item:
 - Regression: None that I can tell. I've often done this same thing and not had such a bad leak. Yesterday I didn't seem to have this problem.

## Reporters:
Xekri

**Comment by Frooxius** [comment]
What makes you think this is a memory leak? That usage doesn't seem too unusual for usage, especially when doing things. Does it keep rising unstoppably? Do you have any graphs or information over time on what the usage is like?

**Comment by RobertBaruch** [comment]
The only thing is that I've never had stuttering this bad when it was just me in my world doing Logix stuff, and when I checked the memory usage, the process had taken all the free memory. I just assumed the stuttering was due to swapping. When I quit and restarted, the problems went away, as did the large memory usage. I'll see if I can get a graph.

**Comment by RobertBaruch** [comment]
After several hours of working, I haven't experienced any rapid increase in memory.
