### ISSUE TITLE
float3 version of greater than and less than nodes

### ISSUE THREAD

**Issue by art0007i** [Neos-Metaverse/NeosPublic#2319]
## Is your feature request related to a problem? Please describe.
Currently you have to unpack and compare each value individually and then if necessary pack the boolean values again

## Relevant issues
none found

## Describe the solution you'd like
The greater than and less than nodes should change to the float2, 3 and 4 versions and output bool2, 3 and 4

## Describe alternatives you've considered
![image](https://user-images.githubusercontent.com/19620451/119255526-9e5be380-bbbc-11eb-8265-3edd4778622a.png)

## Additional context
This is what I would expect them to look like
![image](https://user-images.githubusercontent.com/19620451/119255537-afa4f000-bbbc-11eb-8045-dedef93a457a.png)

**Comment by Frooxius** [comment]
Added in 2021.5.23.985, thanks!
