### ISSUE TITLE
bool2, 3 and 4 versions of bitwise operators

### ISSUE THREAD

**Issue by art0007i** [Neos-Metaverse/NeosPublic#2320]
## Is your feature request related to a problem? Please describe.
Currently there is no good way of performing bitwise operations on bool2, 3 and 4 instead I have to unpack them perform each operation individually and pack the boolean values again

## Relevant issues
none found

## Describe the solution you'd like
bool2, 3 and 4 versions of the bitwise operators (and, nand, or, nor, xor, xnor, not)
bit shifts could be added

## Describe alternatives you've considered
![image](https://user-images.githubusercontent.com/19620451/119256370-ae75c200-bbc0-11eb-8b8f-70ed685898e5.png)
![image](https://user-images.githubusercontent.com/19620451/119256378-b897c080-bbc0-11eb-83e7-aeee0870b2d4.png)

## Additional context
This is what I would expect them to look like
![image](https://user-images.githubusercontent.com/19620451/119256442-14624980-bbc1-11eb-98fc-ec727a72d804.png)

**Comment by Frooxius** [comment]
Added in 2021.5.23.985, thanks!
