### ISSUE TITLE
Neos VR keeps shutting down initializing sequence.

### ISSUE THREAD

**Issue by KiriyanS2K** [Neos-Metaverse/NeosPublic#2322]
## Describe the bug
Neos VR keeps shutting down initializing sequence(first loading screen) since first launching.

## Log Files
[Player.log](https://github.com/Neos-Metaverse/NeosPublic/files/6528116/Player.log)
[DESKTOP-5H8P8JE - 2021.5.22.1024 - 2021-05-23 21_57_33.log](https://github.com/Neos-Metaverse/NeosPublic/files/6528117/DESKTOP-5H8P8JE.-.2021.5.22.1024.-.2021-05-23.21_57_33.log)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Latest
 - Neos Platform: Windows
 - Regression: No

## Additional context
No log created in Temp folder.

## Reporters:
Whitespears (리얀#1117)

**Comment by Frooxius** [comment]
It seems that SteamVR initialization is failing. Which version of SteamVR are you running?

**Comment by KiriyanS2K** [comment]
Running SteamVR 1.16.10 which is lastest I presume.

**Comment by KiriyanS2K** [comment]
Fixed. One of DRM app called "Fasoo DRM" was preventing Neos VR launching, So I uninstalled it then the game is working now.

**Comment by Frooxius** [comment]
Aah thank you for the info, glad you got the issue resolved!
