### ISSUE TITLE
UIX Exception when Saving Avatar

### ISSUE THREAD

**Issue by H3BO3** [Neos-Metaverse/NeosPublic#2326]
## Describe the bug
Asai Hatsuyo#8612 encountered a UIX exception right when they saved their currently worn avatar with the blue button in the inventory. Only the inventory window broke, the other parts of the dash seemed to operate correctly.

## To Reproduce
I don't know if there's exact or reliable reproduction steps. I've never seen this before.

## Log Files
[ASAIHATSUYOSPC_-_2021.5.22.1024_-_2021-05-23_16_49_54.log](https://github.com/Neos-Metaverse/NeosPublic/files/6528508/ASAIHATSUYOSPC_-_2021.5.22.1024_-_2021-05-23_16_49_54.log)

(Exception occurs at line 573)

## Screenshots / Video
![image](https://user-images.githubusercontent.com/62123804/119269213-c3982400-bbb3-11eb-9839-803ddd51943f.png)

## Bug information (please complete the following information):
 - How often does it happen: Seen only once
 - Does the bug persist after restarting Neos? No
 - Neos Version: 2021.5.22.1024
 - Neos Platform: Any

## Additional context
Can't add much else, but I was wondering if the exception was something solvable. If this seems like a fluke, race condition, or other unreliable issue, I can close this out, but I wanted to get the bug and exception logged for if this comes up in the future, or if anyone else has seen something like it.

## Reporters:
Asai Hatsuyo#8612 H3BO3#7957

**Comment by Frooxius** [comment]
Hmm this seems a bit odd, there's some other exceptions with other stuff before that too, it almost seems like some stuff was corrupted. Did they have anything like custom facets or anything like that? 

We'd probably need to find a way to replicate this or see if this happens often, otherwise it might not be worth investigating.

**Comment by H3BO3** [comment]
Asai says their dash is unchanged. I'll reopen if I get more info.
