### ISSUE TITLE
Protect Skyboxes from being Changed

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#2329]
## Is your tweak request related to a problem? Please describe.
Some users accidentally or on purpose change the skybox of a world you're in when using a material tool. A method to prevent this would be desirable.

## Describe what would you like tweaked
Some mechanism to protect skybox changing.

## Describe alternatives you've considered
I tried adding MaterialApplyPolicy to the Skybox slot but this doesn't work.

**Comment by Frooxius** [comment]
Merged in 2021.9.13.981, thanks!
