### ISSUE TITLE
auth.neos.com can't change password if username contains space

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2333]
## Describe the bug
While trying to change my password through recently introduced https://auth.neos.com/ website, I got this error:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/675104/119344064-e0aa2100-bc9f-11eb-8800-7df520fb09f0.png">

## Relevant issues
#2293(?)

## To Reproduce
1. Go to https://auth.neos.com/
2. Try to change your password
3. Get the error

## Expected behavior
Password changes to a new one

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Link to reproduction World/Item: https://auth.neos.com/Identity/Account/Manage/ChangePassword
 - Regression: Not sure

## Reporters:
Shadow Panther#5154

**Comment by Frooxius** [comment]
Fix released in 2021.7.1.437! Note that names containing unicode characters (Japanese, Russian, Korean, Czech and so on) will still not work, we're looking into more general solution for this.
