### ISSUE TITLE
Headless client throwing an exception when trying to load a particular world

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2335]
## Describe the bug
When trying to open a session of Avatar Station world, headless server throws an exception and doesn't start the session.

## Relevant issues
None found

## To Reproduce
1. Start a headless server
2. Try to load this world `startWorldURL neosrec:///G-United-Space-Force-N/R-71344877-e209-4ce6-98d7-b54070723285`
3. Observe the exception, the session doesn't start

## Expected behavior
World loads, session starts

## Log Files
[bea021ac7495 - 2021.5.23.985 - 2021-05-24 01_59_48.log](https://github.com/Neos-Metaverse/NeosPublic/files/6534099/bea021ac7495.-.2021.5.23.985.-.2021-05-24.01_59_48.log)
Relevant exception after `20:18:35.103    Requesting gather for: neosdb:///26c32554d085c6512e6b312df170b106830293f35ed6bd31ddc20c2010ff802e.7zbson`
The headless itself is still running, so there's no stopping the headless at the end.

Update, full log:
[bea021ac7495 - 2021.5.23.985 - 2021-05-24 01_59_48.log](https://github.com/Neos-Metaverse/NeosPublic/files/6534724/bea021ac7495.-.2021.5.23.985.-.2021-05-24.01_59_48.log)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.23.985
 - Neos Platform: Linux Headless
 - Link to reproduction World/Item: neosrec:///G-United-Space-Force-N/R-71344877-e209-4ce6-98d7-b54070723285
 - Regression: Unsure, but there were headless servers hosting this world before.

## Additional context
https://discord.com/channels/402159838827905024/619845139770376192/846397707504582686

## Reporters:
Originally reported by Torrn#9267
Confirmed and filed by Shadow Panther#5154

**Comment by shadowpanther** [comment]
Also, looks like the same exception happened when a user joined an existing session. I'll post the full log after I restart the headless next time, as I see other exceptions popping too.

**Comment by Frooxius** [comment]
Fixed in 2021.5.24.1203, thanks!
