### ISSUE TITLE
TooltipMultiplexer does not provide correct chirality

### ISSUE THREAD

**Issue by Sharkmare** [Neos-Metaverse/NeosPublic#2339]
## Describe the bug
Tooltip Multiplexer returns "-1" when passed into "Tooltip equipping side" Logix node instead of returning the currently active tools chirality (or r eturning its own chirality for that matter if there is no active tool)

## To Reproduce
[Steps to reproduce the behavior:
1. Make a multitool
2. Pass the multiplexer into "Tooltip equipping side"
3. "-1"

## Expected behavior
"Left" or "Right" Chirality based on the current active tool.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.24.1203
 - Neos Platform: Any
 - Regression: No clue

## Reporters:
Dragon Shark

**Comment by 3x1t-5tyl3** [comment]
![grafik](https://user-images.githubusercontent.com/61988002/119497147-83c46e80-bd64-11eb-9a15-e83e9e5e57a1.png)
Requires an updating relay.

**Comment by Sharkmare** [comment]
> ![grafik](https://user-images.githubusercontent.com/61988002/119497147-83c46e80-bd64-11eb-9a15-e83e9e5e57a1.png)
> Requires an updating relay.

Huh, that's strange since the regular tooltip does not, thanks exit, guess that explains that.
