### ISSUE TITLE
Filter Invalid on float2, 3 and 4 should only filter invalid values

### ISSUE THREAD

**Issue by art0007i** [Neos-Metaverse/NeosPublic#2341]
## Is your tweak request related to a problem? Please describe.
The filter invalid node will use all 3 axes of the fallback if one of the input values is invalid.

## Describe what would you like tweaked
I think it would be more intuitive and useful if it instead filtered out the invalid values and leave the valid ones alone.

## Describe alternatives you've considered
![image](https://user-images.githubusercontent.com/19620451/119533345-07db1e00-bd86-11eb-891c-ed3258ee9972.png)

## Additional context
Since this changes how a node behaves it would be necessary to do this to get the old behavior back.
![image](https://user-images.githubusercontent.com/19620451/119534177-eaf31a80-bd86-11eb-86fd-000de02e3872.png)

**Comment by Frooxius** [comment]
This is intentional behavior, if any of the components is invalid, then the whole vector is considered invalid, as any operations that use multiple components (e.g. Normalize, Cross, Dot  product...) would produce invalid results anyway.
