### ISSUE TITLE
Chirality on RootContextMenuItem

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2344]
## Is your feature request related to a problem? Please describe.
Not exactly a problem, but right now menu items injected via RootContextMenuItem appear for both hands' context menus.

## Describe the solution you'd like
A 'Chirality' property that allows to only inject context menu item for left/right/primary/secondary/both hands.

## Describe alternatives you've considered
Tracking which context menu button the user clicked via LogiX and enabling/disabling menu items depending on that.

**Comment by Frooxius** [comment]
Added in 2021.6.7.794!

**Comment by shadowpanther** [comment]
Thank you for reopening.
Primary/Secondary filters are missing on Chirality, which should account for user's Primary Hand setting instead of specifying Left or Right.

**Comment by Frooxius** [comment]
Added ExcludePrimary and ExcludeSecondary in 2021.6.8.685!
