### ISSUE TITLE
Inv items missing

### ISSUE THREAD

**Issue by peterthethinker** [Neos-Metaverse/NeosPublic#2345]
## Describe the bug
[A clear and concise description of what the bug is.]

I had a video and 4 pics in 
\Inventory/Show and tell.

I made a Dir tree 
\Inventory/Media/Show and tell
I proceeded to spawn in a  blank new world   the items and then One by one  re-save them in 

\Inventory/Media/Show and tell
all was green and  synced ...... I closed the word and  the rest of the night I was able to  spawn items from 
\Inventory/Media/Show and tell

  today I get on and  
\Inventory/Media/Show and tell

is empty 

## Expected behavior
[ If the UI's asset  says i am all good and synced  then  I would hope there is a a check to make sure the data is fully moved  and stable ]

## Bug information (please complete the following information):

 - How often does it happen: [Always, Sometimes, Only Once]  Once
 - Does the bug persist after restarting Neos? [Yes/No]    yes 
 - Neos Version: [version number]  20201.5.25.1225
 - Neos Platform: [Any, Windows, Linux, Android/Quest] W10 
 - Link to reproduction World/Item: [Optional, but can speed up response for more complex reproduction cases]
 - Regression: [Did this work before? Yes (which build?) / No]

**Comment by peterthethinker** [comment]
OK I cleared the  catch and the files are back and are working
but if I reboot or  simply close neos then  on next  launch  the files are gone

 again if I clear the catche then they are back
 
 
 Ive spawned them in to a spare world and saved the world in hopes that it  preserves them.

**Comment by peterthethinker** [comment]
OK assets are IN that world and work ok.  ... hmm

**Comment by peterthethinker** [comment]
anddd now its happing with 
\Inventory/Media/Films

**Comment by shiftyscales** [comment]
>Cloud Update
> Pushed a small bugfix to the cloud, that prevented big assets from syncing properly.
> 
> Bugfixes:
> - Fixed large assets (typically over 1 GB) failing to sync properly due to upload finalization timing out in the last phases of upload

I think this update released by Frooxius today may help alleviate this issue. Feel free to reopen/comment if problems persist.
