### ISSUE TITLE
Can't plug ContextMenuItemSource into Button Events node.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2346]
## Is your tweak request related to a problem? Please describe.
The ContextMenuItemSource component relays button effects like a button would but it cannot be plugged into the Button Events node, which makes using it in combination with Logix a bit annoying.

## Describe what would you like tweaked
Make it possible to plug ContextMenuItemSource into the Button Events node like any other button.

## Describe alternatives you've considered
1. Not doing this. (can't see a reason not to myself)
2. Specialized logix nodes for this specifically (sounds unnecessary)

**Comment by 3x1t-5tyl3** [comment]
Relevant discord link from yesterday: https://discord.com/channels/402159838827905024/731903736028332083/846864232678555718

**Comment by shiftyscales** [comment]
Frooxius has stated his intent to have this implemented in the next build.

**Comment by Psychpsyo** [comment]
Since the last update fixed this, I'm closing down the issue here.
