### ISSUE TITLE
Add Login as NeosID in auth.neos.com

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2347]
# Is your feature request related to a problem? Please describe.
Idk, i think this feature is already planned, and/or current website is just temporary.

## Relevant issues
#2293 ? 

## Describe the solution you'd like
current auth.neos.com can't login through neosid, so if using password manager, it can't use it at now.
so i think login form also allow e-mail `and ID(Neos UserId)` is better.

## Describe alternatives you've considered
just create password manager strings like as (U-kazu to ***@***.com)

## Additional context
if just temporary, sorry.

**Comment by kazu0617** [comment]
In the meantime, if it is possible, please label it [Website] if anyone can label it, as it is more of a WebSite side than a mainframe side enchancement.

**Comment by Frooxius** [comment]
This has been implemented, you can now login with your Username, ID or email on auth.neos.com as you can in Neos!
