### ISSUE TITLE
Add a min and max user scale value to the Metaverse Training Center tutorial world

### ISSUE THREAD

**Issue by ohzee00** [Neos-Metaverse/NeosPublic#2348]
## Is your tweak request related to a problem? Please describe.
New users are told to test out the scale functionality during the tutorial, which while is fun and nice to show off, is problematic being that the world does not have a max or min scale, causing users to get either too small or too big while scaling themselves.
 
This can cause horrible floating point errors or in the case of a user on the discord, accidentally hitting a teleporter to another MTC world due to being too big.

## Describe what would you like tweaked
Adding a min and max scale value to the LocomotionPermissions component in the Metaverse Training Center tutorial world.

Honestly I'm unsure what the value should be exactly, from rough testing a min scale of .05 and a max of 7 seems to be fine though that's up for debate.

## Describe alternatives you've considered
I don't think there is any alternatives, being the functionality for limiting the scale of the user is in every world and can be semi-easily added from what I understand.

## Additional context
![image](https://user-images.githubusercontent.com/33611545/119677987-2f28fe00-be0d-11eb-8691-3bbade197225.png)
The current defaults for the tutorial world which currently does not have any min or max scale applied to it.

**Comment by AshtonSparx** [comment]
I can second this. When users discover they can resize themself without restraint, they either
A) Become the size of a mountain. Even saw an incident in the discord where the user was big enough, they actually went through the portal without actually finishing the tutorial.

Or

B) Become floating point small and don't know how to fix themself (Reset Scale)

**Comment by ohzee00** [comment]
Fixed recently by Aegis Wolf, there should be limits for the max and mix scale for the MTC worlds.
