### ISSUE TITLE
Allow secondary to get "Type" input

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2349]
## Is your tweak request related to a problem? Please describe.
It's not possible to get that node unless you explicitly use the nodebrowser.

## Describe what would you like tweaked
Being able to use secondary to get an input node (same as floats, color ect..)

## Describe alternatives you've considered
-

## Additional context
![grafik](https://user-images.githubusercontent.com/61988002/119694331-6f0fd580-be4d-11eb-9088-9529873acc8a.png)
I'm updating my MultiTool at the moment to use proper "Type" checking and noticed this.

**Comment by Frooxius** [comment]
Added in 2021.6.7.794!
