### ISSUE TITLE
LogiXTip - WireDragTarget not returning to it's zero-position properly in Screenmode

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2351]
## Describe the bug
The "WireDragTarget" in VR resets to the TipReference point. In screen mode the target does not do that and as such can cause weird visuals when wanting to customize the visual of the drag target. See Screenshots (1).

## Relevant issues
#2203

## To Reproduce
1. Use projectionmode in screen
2. Inspect the slot to see it's not zero'd out.

To note: In VR this works as expected. The target get's zero'd back out and goes back to the TipRef location.

## Expected behavior
Same as VR to return to its 0-point ergo the TipRef.

## Log Files
None.

## Screenshots / Video
![grafik](https://user-images.githubusercontent.com/61988002/119833805-b48cdb00-beff-11eb-8bf7-9b8041d51fad.png)
https://user-images.githubusercontent.com/61988002/119833929-cff7e600-beff-11eb-829f-7af756748677.mp4

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Beta 2021.5.25.1225
 - Neos Platform: Only tested on Windows.
 - Link to reproduction World/Item: neosdb:///2dc4b48109121efa0d190c36dfd173cb632a700fba3b1215dfdd2d348e0a94b1.7zbson
 - Regression: N/A

## Additional context
-

## Reporters:
3x1t_5tyl3# 0001

**Comment by shiftyscales** [comment]
In investigating this, I believe this behavior is related to the UI camera mode/maintaining the cursor on a plane when repositioning objects/nodes.

Given that the WireDragTarget is a slot managed by an internal property (namely, _tempWireTarget) this seems like a somewhat strange usage pattern though.

I'd advise either repositioning the visual yourself (similar to what I did with the label on the desktop version of the Logix tip), or otherwise making a GitHub issue requesting a custom visual for the cursor position.

**Comment by 3x1t-5tyl3** [comment]
> 
> 
> In investigating this, I believe this behavior is related to the UI camera mode/maintaining the cursor on a plane when repositioning objects/nodes.
> 
> Given that the WireDragTarget is a slot managed by an internal property (namely, _tempWireTarget) this seems like a somewhat strange usage pattern though.
> 
> I'd advise either repositioning the visual yourself (similar to what I did with the label on the desktop version of the Logix tip), or otherwise making a GitHub issue requesting a custom visual for the cursor position.

Fair. Just found it a bit odd as (atleast I think) neos strives for feature parity between screen and VR so I just thougt the behaviour felt a bit weird that screen keeps it a ways away while vr gets a proper reset.

**Comment by 3x1t-5tyl3** [comment]
I'm not sure what to think of this and It's another one of these "We expose this eventhough you shouldn't touch it in the first place."
Thus making me question why bother exposing stuff like this in the first place?
