### ISSUE TITLE
Videos with more than 2 audio channels (5.1 or 7.1) don't play properly via Unity Native

### ISSUE THREAD

**Issue by Gawdl3y** [Neos-Metaverse/NeosPublic#2353]
## Describe the bug
Playing videos via the Unity Native player that have greater than 2 audio channels, such as 5.1 (6 channels) or 7.1 (8 channels) results in a crackling noise that completely overpowers all other sound in the game when in VR.

## Relevant issues
_Vaguely_ related to #1532 in that they're both misbehaving audio, but that's about it.

## To Reproduce
1. Import/stream a video in Neos that has greater than 2 audio channels
2. Ensure the VideoTextureProvider is using Unity Native
3. Play the video

## Expected behavior
The audio should play normally, with no severe crackling/static and without overwhelming all other audio in the game when in VR (regardless of spatialization).

## Log Files
[SCHUYLER-DT - 2021.5.25.1225 - 2021-05-27 20_32_56.log](https://github.com/Neos-Metaverse/NeosPublic/files/6557489/SCHUYLER-DT.-.2021.5.25.1225.-.2021-05-27.20_32_56.log)

## Screenshots / Video
https://user-images.githubusercontent.com/279900/119914539-5b886b80-bf2e-11eb-89c4-792c987fdd2c.mp4

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.25.1225
 - Neos Platform: Windows (haven't tested others)
 - Link to reproduction World/Item: Available to send directly upon request (it's not free/public media)
 - Regression: No

## Additional context
Frooxius requested I open this issue. I hadn't in the past because my assumption, and what I had heard from other sources, was that there wouldn't be anything Neos could do about this problem since Unity Native is somewhat of a black box.

I've tested the exact same video with the audio encoded the same way (AAC, 48KHz sampling rate) but remuxed down to stereo from 5.1, and it doesn't have the problem.

## Reporters:
Gawdl3y / Gawdl3y#4269

**Comment by Enverex** [comment]
This also seems to happen with single channel (mono) audio. It'll crackle, play at the wrong speed (higher pitched) and skip around. Could be the same problem, if not then it sounds at least similar.

**Comment by Frooxius** [comment]
This should now be fixed in 2021.6.7.794, the videos seem to play properly. Let me know if you find any that still give you issues, as I didn't test a full range of audio types!
