### ISSUE TITLE
360 camera mode launches regular mode

### ISSUE THREAD

**Issue by pushstartvr** [Neos-Metaverse/NeosPublic#2356]
As the title says.  It has only been happening since the last update I think.

**Comment by shiftyscales** [comment]
How were you launching Neos? From a desktop shortcut? Or from the Neos launcher? It appears that the command line argument has been changed from `Standalone360` to `Screen360`. If you pass `-Screen360` as a command line argument it launches into the 360 screen mode without issue.

I've also updated https://wiki.neos.com/Command_Line_Arguments with the renamed command. Please feel free to comment if you continue to run into issues, and we could look further into what might be going wrong with your particular setup.

**Comment by pushstartvr** [comment]
Hi shifty, I'm referring to the 360 camera, not stand alone 360.
Cheers
