### ISSUE TITLE
ValueOptionDescriptionDriver cant't drive ContextMenuItemSource's Sprite

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2364]
## Describe the bug
Trying to use ValueOptionDescriptionDriver to simplify the menu, I found out that the Sprite field of the new ContextMenuItemSource can't be driven by it.

## To Reproduce
1. Try to paste ContextMenuItemSource's Sprite field into ValueOptionDescriptionDriver's Sprite ref field

## Expected behavior
Sprite field is being driven

## Screenshots / Video
![image](https://user-images.githubusercontent.com/675104/120045676-3d4b6a00-c019-11eb-86fd-736ddf33c2b1.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.25.1225
 - Neos Platform: Any
 - Link to reproduction World/Item: 
 - Regression: No

## Additional context
Wanted to minimize the number of components on a single menu item.

## Reporters:
Shadow Panther#5154

**Comment by ProbablePrime** [comment]
Could you try driving the image field of the sprite provider instead? Does that work?

**Comment by shadowpanther** [comment]
Tried that, it doesn't work either

**Comment by ProbablePrime** [comment]
Thanks!, I took a look at the types here and need to try some stuff in Game. I will get back to you here.

**Comment by ProbablePrime** [comment]
I took a look and tried various options and couldn't get this to work. It looks like we'll need some form of Neos change if we want this to happen.

**Comment by seif1** [comment]
This appears to also affect the ReferenceOptionDescriptionDriver.

There is a alternative you can do to get this working for now
FrooxEngine.ReferenceCast`2[FrooxEngine.IAssetProvider`1[FrooxEngine.Sprite],FrooxEngine.SpriteProvider]

Using a reference cast to change the type in this way, you can put the source of the ReferenceCast into the DescriptionDriver, and the ContextMenuItemSource's Sprite into the Target

**Comment by Frooxius** [comment]
This was because OptionDescriptionDriver works with more general interface, but the ContextMenuItem was specifically SpriteProvider. I updated all references to use the general interface instead in 2021.6.8.685, which will now make it work!
