### ISSUE TITLE
Now Neos Website mixing neosvr.com and neos.com

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2367]
## What topic do you want to discuss?
The title says it all.
When I go to Neos.com, the button that says "Wiki" gives me access to "wiki.neos.com", but the button that says "Sign in" gives me access to `account.neosvr.com`.

After that, when you click on the "Sign in" button, it is `account.neosvr.com` that is actually accessed, but the link to the Neos logo on this page is `account.neos.com`, and the link to the Wiki is `wiki.neosvr.com`.

>タイトルの通りです。
>Neos.comにアクセスしたとき、Wikiと表示されているボタンからアクセスできるのは "wiki.neos.com"ですが、Sign inからアクセスできるのは`account.neosvr.com`です。
>
>その後、Sign inをクリックした際に実際にアクセスされるのは`account.neosvr.com`ですが、このページに表示されているNeosロゴのリンクは`account.neos.com`になっており、Wikiのリンクは`wiki.neosvr.com`になっています。

## Goal of discussion
I remembered that I had written about the change in branding somewhere before, but a quick search on GitHub for that content did not turn up anything. Therefore, I think the goal of this discussion is to officially confirm those contents and have them unified in one way or the other.

>以前どこかでブランディングについて変更になったと書いていた記憶があったのですが、その内容をGitHubで簡単に検索しても出てきませんでした。そのため今回の議論のゴールはそれらの内容を正式に確認し、どちらかに統一してもらうのが議論のゴールだと考えています。

**Comment by ProbablePrime** [comment]
Thank you for reporting this, I double checked "auth.neos.com" which is the new OAuth website and this does not have this error. So it looks like the main website just needs updating to this new domain in a few places.

Thank you!
