### ISSUE TITLE
Change "Cleanup Interval" values.

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2368]
## Is your tweak request related to a problem? Please describe.
If you set the cleanup interval away from the current default (300) the new max is 120 seconds.

## Describe what would you like tweaked
3 solutions that come to mind

1: Change the default value to 120 as well.
2: Change the default maximum value to 300.
3. Set the max value even higher (15 minutes as an example) for users who want to run the cleanup even less frequently if they so choose to.

## Describe alternatives you've considered
-

## Additional context
-

**Comment by Frooxius** [comment]
Increased the maximum to 3600 (1 hour) in 2021.6.7.794, thanks!
