### ISSUE TITLE
Logix: Dynamic Variable Input node type name not consistent with rest of Dynamic Variable nodes

### ISSUE THREAD

**Issue by RobertBaruch** [Neos-Metaverse/NeosPublic#2370]
## Is your feature request related to a problem? Please describe.
The Dynamic Variable Input text uses the .NET type name rather than the type name that other Dynamic Variable nodes use. This is inconsistent and confusing.

For example, in this screenshot we see Int32 for int. You'll also see Single for float.

![Dynvar Output Ex](https://user-images.githubusercontent.com/1783950/120079205-b7a2db00-c067-11eb-9de4-cbd2dd03eb2c.jpg)

## Describe the solution you'd like
I'd like to see Dynamic Variable Input use the same type names that the other Dynamic Variable nodes use.

## Describe alternatives you've considered
Deal with it 🙃

**Comment by Frooxius** [comment]
The naming is now consistent in 2021.6.8.685, thanks for report!
