### ISSUE TITLE
Disable GrabSpheres while in Desktop mode

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2374]
## Is your tweak request related to a problem? Please describe.
When you're in desktop mode (Regardless of F8 or Screenmode) your grab Spheres are still active, which can get rather annoying when trying to grab something with your laser. Many times have I grabbed inspectors that were too close to my hands, or some other random object when trying to grab something else.

## Describe what would you like tweaked
For your avatar's GrabSpheres to be disabled while in Desktop Mode.

## Describe alternatives you've considered
Not to disable GrabSpheres while in desktop mode. Or have an option to disable it for desktop mode.

**Comment by TehTurk** [comment]
I would suggest instead of disabling them, possibly exploring options for the hands to be used in desktop mode, recently in the bhaptics event where players would be climbing for the special event was an issue. Debug Desktop User Made options had something for this, and I'd like to see maybe it carry it over if we can.

**Comment by H3BO3** [comment]
it still makes sense that they should be disabled when not in use

**Comment by AshtonSparx** [comment]
> 
> 
> I would suggest instead of disabling them, possibly exploring options for the hands to be used in desktop mode, recently in the bhaptics event where players would be climbing for the special event was an issue. Debug Desktop User Made options had something for this, and I'd like to see maybe it carry it over if we can.

Debug desktop users also had no use for their hands, so people made use for those hands. With the new desktop, your hands are used internally for lifting and lowering tools you have equip. Trying to make any use of it, or taking control of your hands make it hard to do anything actual desktop mode aside from... "Petting" with the legacy system Lucas made.

**Comment by Toxic-Cookie** [comment]
I agree. It's infuriating every time I grab something with one of my hands down by my side instead of my cursor.

**Comment by Frooxius** [comment]
Disabled in 2021.7.21.402! You can still grip into the environment if you really want, but you won't accidentally grab items in the world in desktop.
