### ISSUE TITLE
LogiX node for create, delete and configure components inside slots.

### ISSUE THREAD

**Issue by demonzla** [Neos-Metaverse/NeosPublic#2375]
## Is your feature request related to a problem? Please describe.
Wanted LogiX component for create, delete and configure components inside slots.

## Relevant issues
In some cases, we need to change components, remove them, or create them inside slots wit LogiX to create tools or content. 
 
## Describe the solution you'd like
LogiX nodes for create, delete and configure components inside any slots.

## Describe alternatives you've considered
LogiX nodes that are used to enable or disable components are ineffective for some tasks.

**Comment by ProbablePrime** [comment]
Hey @demonzla this is covered by a larger item #243 so I'll close this as a duplicate.

Thank you for your suggestion.
