### ISSUE TITLE
Flick-selecting in the main context menu causes custom submenus to misbehave when in VR

### ISSUE THREAD

**Issue by Gawdl3y** [Neos-Metaverse/NeosPublic#2376]
## Describe the bug
Flick-selecting a custom submenu entry on the main context menu results in the custom submenu that opens up being stuck on-screen (doesn't go away after the laser leaves) and being unable to flick-select any of the items in it. This issue only occurs in VR - it seems to behave properly in desktop.

## Relevant issues
#2377 

## To Reproduce
1. Have an avatar/other item with a custom submenu added to the root context menu
2. Open the context menu
3. Flick-select the custom item that opens the custom submenu
4. The submenu that opens no longer auto-closes when moving the laser off, and flick-selection doesn't work in it

## Expected behavior
The custom submenus should behave identically to the vanilla ones, such as the locomotion submenu. Moving the laser off of them should cause them to close, and flicking should work properly even after flicking on the main context menu.

## Log Files
N/A

## Screenshots / Video
Correct behaviour (locomotion submenu):
https://user-images.githubusercontent.com/279900/120103571-3eb28a80-c11e-11eb-9496-132a96dccfa6.mp4

Incorrect behaviour (custom submenu):
https://user-images.githubusercontent.com/279900/120103579-496d1f80-c11e-11eb-9bd0-73ae9f92c0e9.mp4

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.29.1365
 - Neos Platform: Any (but only tested on Windows)
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
N/A

## Reporters:
Gawdl3y / Gawdl3y#4269

**Comment by Hayden-da-Serg** [comment]
Not sure if this could be related, but custom submenus also cannot be used if the laser in the respective hand is disabled.

**Comment by 3x1t-5tyl3** [comment]
> 
> 
> Not sure if this could be related, but custom submenus also cannot be used if the laser in the respective hand is disabled.

That's definitely a seperae issue. I've been looking into them. Seems to be seperate from this one so probably a good idea to open a seperate GH about it :p

**Comment by Frooxius** [comment]
Fixed in 2021.6.7.794, thanks!
