### ISSUE TITLE
Custom context menu submenus don't preserve their hand/position when opened

### ISSUE THREAD

**Issue by Gawdl3y** [Neos-Metaverse/NeosPublic#2377]
## Describe the bug
When opening a custom submenu, its position resets to the current hand position of the hand that clicks the item to open it.

_Expanded:_

When clicking the item to open the submenu with the same hand that the context menu is already open in, its position moves slightly to the current position of the hand.

When clicking the item to open the submenu with the opposite hand that the context menu is already open in, its position relocates entirely to the hand that clicked the menu.

## Relevant issues
#2376 

## To Reproduce
1. Have an avatar/other item with a custom submenu added to the root context menu
2. Click the custom item to open the custom submenu
3. The context menu repositions itself

## Expected behavior
The context menu should always maintain its initial position when entering custom submenus, just like the vanilla submenus (like locomotion) do.

## Log Files
N/A

## Screenshots / Video
Correct behaviour (locomotion submenu):
https://user-images.githubusercontent.com/279900/120103963-32c7c800-c120-11eb-9194-521bf07ab7ab.mp4

Incorrect behaviour (custom submenu):
https://user-images.githubusercontent.com/279900/120103968-38251280-c120-11eb-8f61-ca26c7e8ac50.mp4

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.29.1365
 - Neos Platform: Any (but only tested on Windows)
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
N/A

## Reporters:
Gawdl3y / Gawdl3y#4269
Psychpsyo / Cameron#7818

**Comment by Frooxius** [comment]
This is same underlying issue as https://github.com/Neos-Metaverse/NeosPublic/issues/2376, I'm closing this one. I'll close the other once fix goes out.
