### ISSUE TITLE
Context Menu Item Source with a Null label completely breaks Context Menu

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Neos-Metaverse/NeosPublic#2378]
## Describe the bug
When the Label on ContextMenuItemSource is set to a Null string, any Context Menus the item appears in becomes completely unusable.

## Relevant issues
None to be found

## To Reproduce
- Add a ContextMenuItemSource under User Root with an accompaning RootContextMenuItem
- Click the button next to the text field in the Label field to null the string
- Attempt to open and interact with Context Menu

## Expected behavior
The Context Menu Item should just display with no text whenever the field is Null

## Screenshots / Video
![image](https://user-images.githubusercontent.com/25524760/120104699-05c0e880-c113-11eb-897b-efb7a1e7442e.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.29.1365
 - Neos Platform: Windows, though suspected to be on any
 - Link to reproduction World/Item: N/A
 - Regression: This has been the case since Context Menu injection was implemented in 2021.5.25.1225

## Reporters:
Hayden#3180

**Comment by Hayden-da-Serg** [comment]
I also forgot to mention that the Context Menu also does not re-center when opened whenever it is in this state.

**Comment by Frooxius** [comment]
Fixed in 2021.6.7.794, thanks!
