### ISSUE TITLE
User Context menu Sub-menus Can't be used when laser is disabled

### ISSUE THREAD

**Issue by Electronus** [Neos-Metaverse/NeosPublic#2379]
## Describe the bug
Default context menu submenus are able to be used when the laser is disabled, user made ones however can not. 

## Relevant issues
#2376 #2377 #2378 

## To Reproduce
[Steps to reproduce the behavior:
1.disable laser
2.open user made submenu
3.be unable to interact

## Expected behavior
That you would still be able to use the menu

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.29.1365

## Reporters:
Electronus#5305 Hayden#3180

**Comment by ukilop** [comment]
similar problem for tooltips that don't use laser such as shape tip

**Comment by Frooxius** [comment]
How are you opening those user made submenus?

**Comment by ukilop** [comment]
normal trigger click for me

**Comment by Electronus** [comment]
same normal trigger click

**Comment by Psychpsyo** [comment]
> 
> 
> How are you opening those user made submenus?

I just add a submenu, have it open with a root menu item by being on the same slot as that root menu item and it applies. (This whole setup is on the avatar I have equipped)
Can currently verify this for desktop mode, using a left-click on the root menu item source to open the submenu.

**Comment by Frooxius** [comment]
No I mean, what is the exact setup to use to open the submenu? Are you opening it on a random button press? Or from item in the root menu?

**Comment by Psychpsyo** [comment]
From an item in the root menu.

**Comment by Electronus** [comment]
Ah its the same set up as the one in Primes tutorial, an item n the root. I wasn't aware you could open on  a random button press.

**Comment by Frooxius** [comment]
Fixed in 2021.6.7.794, thanks!
