### ISSUE TITLE
Some file types get place in the World Root slot after importing instead of User Parent slot

### ISSUE THREAD

**Issue by KyuubiYoru** [Neos-Metaverse/NeosPublic#2380]
## Describe the bug
Some file types get placed in the World root slot instead of the User parent slot after importing them, for example wav, ogg, flac, otf, ttf, zip. (This list is not complete)
Others like png, fbx, mp4 work fine and get placed in the same slot with the User.
This only happens on Import, spawning always places the objects in the User parent slot.

## To Reproduce
[Steps to reproduce the behavior:
1. Move the User to a different Slot
2. Import a any file of type wav, ogg, flac, otf, ttf
3. Look into the Root hierarchy

## Expected behavior
Imported files should be just like Spawned Objects placed in the parent Slot of the User who Imported them.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.29.1365
 - Neos Platform: Windows
 - Regression: Unknown

## Additional context
I discoverd the problem after Building a "Collection Creator" to sort and display larger amounts of Objects that depents one having all imported objects in a certain slot with the User.

## Reporters:
KyuubiYoru/ Kyuubi#3630

**Comment by Frooxius** [comment]
All asset types should now be placed in the user's space in 2021.6.7.794 now, thanks!
