### ISSUE TITLE
World save not saving things that people are holding

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2382]
## Is your tweak request related to a problem? Please describe.
So, when a world is saved (or set to autosave), if someone happened to hold something while it was saving, that item won't be saved with the world. This can be problematic if the item should be saved and was just being moved while the autosave kicked in.

## Describe what would you like tweaked
Make worlds save things that people are holding, preferably under the slot they were last under. (or maybe wherever they'd go if the user let go)

## Describe alternatives you've considered
Not doing this. (since holding stuff is sometimes used to prevent things from saving with the world)
Being careful when manually saving worlds and maybe adding some indication that an autosave is about to happen so that people can let go of what they're holding.

## Additional context
This became an issue in the past when something that was connected to other systems in the world wasn't saved because of this, nulling some references in the process and therefore breaking things in the saved version of the world.

**Comment by H3BO3** [comment]
I wouldn't want this. When I want to save a world that people are doing things in or showing off something, I often ask them to pick it up just for a bit so it won't save with the world. I feel that by using autosave you have accepted all risks of unannounced saves.

**Comment by 3x1t-5tyl3** [comment]
Yeah no. I tell people if I work on a world to drop the stuff that's part of the world and hold the stuff that isn't so I can safe my world without their garbage in it.

**Comment by Psychpsyo** [comment]
Good point. But then I still think that the autosave should announce itself. Cause the thing that sparked this just now was me, wanting to leave a session open for a bit while I'm gone. I wouldn't be able to save it in that time so I considered putting on autosave but decided not to for this reason.

**Comment by H3BO3** [comment]
Having a way to play a sound or make some other announcement prior to an autosave sounds like a great feature and worth a separate issue.

**Comment by Psychpsyo** [comment]
Should I close this one down since I wouldn't even want it myself now?

**Comment by H3BO3** [comment]
Yeah, that's fine
