### ISSUE TITLE
Screen mode (Desktop mode) can't export/send to anyone.

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2388]
I found an issue related to this problem in #2155 .

## Describe the bug

When using the Screen mode, it was not possible to export objects using the file browser.

At the same time, it was not possible to send objects using contacts.

## Expected behavior

I would like to see some sort of indication to export in a format similar to [Save to Inventory].
If this is too redundant, it may be possible to generate a ContextMenu like [Save to Inventory], [Send to Friend], or [Export this Object] when the user does something like middle-clicking while holding down Shift.

_Originally posted by @kazu0617 in https://github.com/Neos-Metaverse/NeosPublic/issues/2155#issuecomment-851212692_

**Comment by Gawdl3y** [comment]
While this is still a deficiency of desktop mode, I feel that adding these functions to the context menu wouldn't necessarily be the correct route to go, as that's going to result in easily overcrowding the context menu. Additionally, those two functions are used *far* less often than saving to your inventory.

I personally think that an alternate implementation should be sought, such as tracking the most-recently-grabbed item and allowing that to be used for any of those [+]-style buttons in the dash (inventory, messages, and exporting) without having to keep the grab active. Perhaps the [+] buttons could be greyed out when there hasn't been anything grabbed or the last-grabbed item is protected, too?

There's probably a better way to implement these as well, that's just the first thing that comes to mind for me.

**Comment by Psychpsyo** [comment]
Maybe make the 'save to inventory' context menu option turn into the other two depending on what tab you have selected in your dash. Wouldn't make it that much less convenient since even now, I almost always need to open my inventory to save stuff to ensure that it goes to the right folder.
Also, it'd be nice if the save option indicated what folder / what person an item is going to, though that'd be problematic as it'd be visible to everyone in the session as soon as someone opens their context menu.

**Comment by alexderpyfox** [comment]
What if you made a button that holds the item like when holding it in VR so like a grip keybind so it gets put in the holder slot and then you can press send

**Comment by Frooxius** [comment]
This will be addressed when the File Browser and other UI's are reworked. Currently those UI's are built with VR in mind, which causes issues like this.

**Comment by Frooxius** [comment]
With some recent changes, it ended up being pretty simple to keep things held in desktop when dash is opened, which just makes those actions work now again! :D Released in 2021.7.21.402

We'll still redesign some of the interactions with those UI's being reworked, but hopefully this helps in the meanwhile!
