### ISSUE TITLE
Headless Server Cannot Save Newly Created Worlds

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#2389]
## Describe the bug
When creating a world on headless from the live command line, saving simply doesn't work, it'll produce a generic failure message.

## Relevant issues
None.

## To Reproduce
1. Create new world from template on headless command line.
2. Try to save.

## Expected behavior
For the word to save to the cloud.

## Log Files
None generated.

## Screenshots / Video
```
Worlds>startWorldTemplate "Basic Empty"
NetworkInitStart
Starting running world:
User Joined EnverexBot World 4. Username: EnverexBot, UserID: U-EnverexBot, MachineID: 3eqxf_36huqlpjlpqvqlza
User Spawn EnverexBot World 4. Username: EnverexBot, UserID: U-EnverexBot, MachineID: 3eqxf_36huqlpjlpqvqlza
World running...
EnverexBot World 4>name "Test Save World 1"
Test Save World 1>accessLevel Private
World Test Save World 1 now has access level Private
Test Save World 1>save
Cannot save focused world!
Test Save World 1>
```

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.29.1365
 - Neos Platform: Linux,
 - Link to reproduction World/Item: N/A
 - Regression: No

**Comment by shadowpanther** [comment]
I want to add that if you start the session from template via the config file, it allows you to save, the issue is only with saving the world created interactively on the fly.

**Comment by Frooxius** [comment]
This is not a bug, it's simply not something that can't work. Save operation saves in-place, meaning there needs to be an existing record for that world. This is same as in graphical client, if you create a new world, you first need to "Save As" to create a record, after which you can "Save".

To do this, use the `saveAsOwner` property in the configuration file to make the headless save the world first, after which you'll be able to use the save command to save your changes.

**Comment by Enverex** [comment]
> Save operation saves in-place, meaning there needs to be an existing record for that world.

If this works via the config file, is there some reason it can't work when a world is created at runtime in the same way?
