### ISSUE TITLE
Headless client stops syncing attempts after getting a 503 from the Cloud

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2390]
## Describe the bug
I noticed that my headless failed to idleRestart the world again (covered in #1649) and tried to restart it. Found out that in the time it ran without the world (half a day) it didn't attempt to sync it. Looking through the log, found that the last attempt to sync failed with 503 error, and no more attempts were made after that:
```
06:22:50.553    Upload failed: ServiceUnavailable - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Service Unavailable</h2>
<hr><p>HTTP Error 503. The service is unavailable.</p>
</BODY></HTML>
```
The world synced after the client was restarted, which in turn allowed me to restart the world at last.

## Relevant issues
#1649

## To Reproduce
1. Run a headless client
2. Periodically save the running world to the cloud
3. On sync, get a 503 (maybe other too) error
4. Notice that no sync attempts are made after that until full client restart

## Expected behavior
Headless client attempts to sync after the error.

## Log Files
[bea021ac7495 - 2021.5.29.56 - 2021-05-29 05_16_36.log](https://github.com/Neos-Metaverse/NeosPublic/files/6571453/bea021ac7495.-.2021.5.29.56.-.2021-05-29.05_16_36.log)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes (I noticed unsynced state before)
 - Neos Version: 2021.5.29.56
 - Neos Platform: Linux (Any?)
 - Link to reproduction World/Item: N/A
 - Regression: No

## Reporters:
Shadow Panther#5154

**Comment by shadowpanther** [comment]
In addition, when I was having connection problems recently, the sync stopped retrying too, which forced me to restart the headless twice - first to make it sync, second to actually load the preconfigured world.

**Comment by Frooxius** [comment]
I've added retry logic to 502, 503 and 504 in 2021.6.7.794, this should make this a fair more robust in case of transient errors like this. Thanks!
