### ISSUE TITLE
Reverb G2 Omnicept eye tracking inverted left to right

### ISSUE THREAD

**Issue by YeCaptainKidd** [Neos-Metaverse/NeosPublic#2394]
## Describe the bug
The left to right is inverted on the Reverb G2 Omnicept, the up and down are correct.

## To Reproduce
[Steps to reproduce the behavior:
1. I use my finger or someone else uses their finger as a point for my eyes to follow.
2. When I look to my right IRL, my avatar as well as the Neos FaceBot avatar looks to its left.

## Expected behavior
When I look to the right the avatar should look to the right as well.

## Log Files
[DESKTOP-EBB273I - 2021.5.29.1365 - 2021-05-31 00_04_13.log](https://github.com/Neos-Metaverse/NeosPublic/files/6572582/DESKTOP-EBB273I.-.2021.5.29.1365.-.2021-05-31.00_04_13.log)

## Screenshots / Video

https://user-images.githubusercontent.com/85099564/120250004-8d9d1480-c231-11eb-85a8-e68ff7c4c158.mp4

## Bug information (please complete the following information):
 - How often does it happen: [Always]
 - Does the bug persist after restarting Neos? [Yes]
 - Neos Version: [2021.5.29.1365]
 - Neos Platform: [Windows]
 - Link to reproduction World/Item: []
 - Regression: [Did this work before? No]

## Additional context
[]

## Reporters:
[In Neos- CaptainKidd, in Discord- CaptainKidd#6330]

**Comment by Frooxius** [comment]
Does this happen only with your avatar specifically or also with any of the default ones from Neos Essentials? This might be issue with the way the avatar is setup rather than the headset, but if it happens with all avatars we can eliminate that possibility.

**Comment by shiftyscales** [comment]
Any update on this, @YeCaptainKidd?

**Comment by YeCaptainKidd** [comment]
Sorry I just seen this message but I have tested with the face and eye tracking avatars in the Neos essentials folder and it does it with them as well.

**Comment by YeCaptainKidd** [comment]
Sorry haven’t been on due to a lot of work but I just jumped on right now to check and the left to right is still inverted, and that is testing with the Neos bot in the essentials folder under face and eye tracking ready.

**Comment by shiftyscales** [comment]
So it sounds that the eye tracking inversion on the G2 Omnicept happens with all avatars then, @Frooxius.

**Comment by Frooxius** [comment]
Ah thank you for the info, we'll just flip the axis then!

**Comment by Frooxius** [comment]
Fixed in 2021.7.23.529, thank you!
