### ISSUE TITLE
Recategorize Float2/3/4 driver to Transform > Drivers

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#2396]
## Is your tweak request related to a problem? Please describe.
Currently `Float2Driver`, `Float3Driver`, and `Float4Driver` are in uncategorized, which is difficult to scroll through.

## Describe what would you like tweaked
Move  `Float2Driver`, `Float3Driver`, and `Float4Driver` to Transform > Drivers

## Describe alternatives you've considered
Having a separate category for these components, since they operate on individual components of a  float2/3/4.
or
Leaving them as-is, if they aren't intended to be used, and documenting as such.

## Additional context
It doesn't seem many people are aware they exist, since they're buried in uncategorized - Moving these somewhere more visible may help with that.

**Comment by Frooxius** [comment]
Categorized in 2021.6.7.794, thanks!
