### ISSUE TITLE
Setting SpeedOverride to 0 (the default value) completely breaks context menu

### ISSUE THREAD

**Issue by asakleiman** [Neos-Metaverse/NeosPublic#2397]
Setting SpeedOverride to 0 on a ContextSubMenu component breaks the submenu. You have to completely respawn to fix it.
![20210601041251_1](https://user-images.githubusercontent.com/14934674/120314537-324e3f00-c290-11eb-8fce-fc8c47cf9c90.jpg)

**Comment by Frooxius** [comment]
Should be fixed in 2021.6.7.794, thanks!
