### ISSUE TITLE
Context Menu Items do not properly update visual when changing the Sprite Provider

### ISSUE THREAD

**Issue by seif1** [Neos-Metaverse/NeosPublic#2408]
## Describe the bug
Context Menu items do not properly update their visual when the Sprite in the ContextMenuItemSource

## Relevant issues
None that I found

## To Reproduce
1. Have a item with a ContextMenuItemSource, RootContextMenuItem (where the item is the ContextMenuItemSource), and 2 SpriteProviders (one of which is referenced in the Sprite field of the ContextMenuItemSource
2. Parent the item under a user root and open context menu
3. Change which SpriteProvider is referenced in the ConntextMenuItemSource
4. See that the visual on the context menu arc does not update

## Expected behavior
The visual on the context menu arc should update if the Sprite Provider is changed

## Screenshots / Video
![Neos_hg3seXiSfy](https://user-images.githubusercontent.com/7923429/120560547-bbac6100-c3b7-11eb-9735-9338424cf06d.png)
![OiSOinLo3Y](https://user-images.githubusercontent.com/7923429/120560627-e3032e00-c3b7-11eb-9735-13e73ddccb91.png)

## Bug information (please complete the following information):
 - How often does it happen: Always* (see additional context)
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.29.1365
 - Neos Platform: Windows
 - Link to reproduction World/Item: neosrec:///U-seif1/R-48d3fc0b-a6aa-40c2-8aab-e136e5dc5c68
 - Regression: Unknown

## Additional context
This only occurs when giving the ContextMenuItemSource a different SpriteProvider, it does not occur if you change the texture of the SpriteProvider you are using (Example item has both cases)

## Reporters:
Axius#4743
seif1#6014

**Comment by Frooxius** [comment]
Fixed in 2021.6.7.794, thanks for report!
