### ISSUE TITLE
Collider <-> RayCast interaction and output

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2410]
## Is your feature request related to a problem? Please describe.
Currently impossible. And I'm not sure if it's even feasable.

## Relevant issues
#2061, #232 See more context below.

## Describe the solution you'd like
A way for us to get raycast interactions **from** a collider.
Ergo "OnCollision" (or potentially a new node?) which outputs if a raycast has hit the collider and with coordinates ect.

## Describe alternatives you've considered
Don't really have any besides plugins.

## Additional context
There's no way currently for a simple interaction between a collider (for example a monster in a field) to interact with raycasts. It always is one way only. This is frustrating and most system right now in neos need to (at the very least) reparent an empty object or similar to achieve anything and can't just rely on the physics interactions that are already built-in. Though I suspect BepuV2 will be a pre-requirement for this given that it's going to be ugpraded anyhow.
Exact implementation of this one is a bit tricky as I don't quite understand the physics system but I'm fairly certain that these interactions should be possible and would optimise current system that rely on reparenting.

Edit: Systems can use also DynamicImpulseTriggers, but again this is more of a workaround than a proper implementation.

**Comment by RileyGuy** [comment]
Why *not* use dynamic impulses though? It seems fairly simple to set up and serves the same purpose while being just about as efficient. What makes it a workaround compared to the solution you suggest? It would be a very similar amount of work. Also afaik, raycasts (I could be wrong) don't actually interact with colliders or physics at all. Raycasts are moreso just a test to see if a line intersects with a triangle mathematically.

**Comment by Frooxius** [comment]
Unfortunately this isn't something we can implement, as it doesn't exist as a concept in most physics engines (including the planned BEPUv2).

Raycasts are just queries on the spatial structure, they do not modify or trigger it in any way and having that implement would present a huge performance overhead.

The idiomatic approach is to perform your query and then send messages to the objects of interest. This is the approach you'd use in most game engines and it's how the physics engines and their API's are designed.

If you need two way interaction, then you need to actually use colliders to trigger collision events, those are optimized for that usage pattern.
