### ISSUE TITLE
"Leg Up" on Kirin Avatar by HaruMaki, Limited to left Leg only. 

### ISSUE THREAD

**Issue by CaelThunderwing** [Neos-Metaverse/NeosPublic#2413]
## Describe the bug
Anywhere from a few seconds to a minute on avatar equip, the left leg breaks in the IK, and Rotation gets set to 0,0,0 pulling it Straight up by the foot on the left leg only. 

## Relevant issues
None aware of. 

## To Reproduce
[Steps to reproduce the behavior:
1. Quick Equip avatar or Rez and equip
2. Move around or Wait till recast with Floor check. 
3. Leg Breaks

## Expected behavior
Expected to not get my left leg thanos-snapped, Jokes aside, Leg should be planted to ground just like the right (im not a full body user (Quest 2 via Virtual Desktop)

## Log Files
(no notable Exceptions were in the log files, Avatar isnt throwing any related IK Errors)

## Screenshots / Video
![2021-06-03 21 13 01](https://user-images.githubusercontent.com/3792137/120742974-0ae0b780-c4c6-11eb-99fc-dfa128774a6c.jpg)

## Bug information (please complete the following information):
 - How often does it happen: [Always]
 - Does the bug persist after restarting Neos? [Yes]
 - Neos Version: 2021.5.29.1365
 - Neos Platform: [Windows]
 - Link to reproduction World/Item: Will be Submitted Privately
 - Regression: N/A

## Additional context
Original Avatar *IS* a Paid content but permission on Discord for Debug purposes to submit. 

## Reporters:
CaelThunderwing#4280 H3BO3#7957 HaruMaki#8888 (Avatar creator & Permission given for Asset submission for debugging)

**Comment by H3BO3** [comment]
Public folder link containing replication item DMed to Frooxius.

**Comment by ProbablePrime** [comment]
Thank you for submitting this I am just mentioning #2177 just in case its related. It may not be but its good to link together items.

**Comment by H3BO3** [comment]
It's possible it is related, doesn't seem to go as high in Earthmark's case though... I've seen the single-leg-foot-on-head with my bat avatar too, and I was wearing that and noticed the issue a loooong time ago

**Comment by CaelThunderwing** [comment]
ATM the only News on the matter as i've posted in the Help Channel in the discord is that Joule Spark had found a way to kinda, "Hodge-podge" a temp solution, but it had the effect of ever-so-slightly tilting the Avatar. That is by setting "ForceUseFeetProxies"

as well, we noticed since they have full body tracking, it broke and attempted to solve itself on its own a few times but would keep "LegUp"ing,  but when Joule stood up and moved even slightly. it went to normal.

**Comment by Frooxius** [comment]
This was same issue as https://github.com/Neos-Metaverse/NeosPublic/issues/2177, should be fixed in 2021.6.7.794 now. Let me know if you still experience issues! Thanks for report!

**Comment by Earthmark** [comment]
This and #2177 are both still in play, but bug is still happening to both avatars. It seemed like the issue was fixed yesterday for a bit, unsure what happened.

**Comment by Frooxius** [comment]
I looked into this and it turns out that I'm a dummy. I made the fix into an auto-generated file, rather than the generation template, so when I made another build yesterday, the fix got reverted back.

Re-fixing it again in the next build, at least it's not something new and tricky! Sorry!

**Comment by Frooxius** [comment]
Re-added the fix in 2021.6.9.396, sorry for the trouble! Let me know if you still run into issues, but hopefully it'll be good now, I made sure to edit the right file this time xD
