### ISSUE TITLE
IsLocalUserFocused for UIX Canvases

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2415]
## Is your feature request related to a problem? Please describe.
It's currently not possible to get if user is "focused" ergo if a user is interacting with a UI Canvas. This means in general interacting with it. Such as just hovering with the laser over any element of the UI

## Relevant issues
#1309 #299 #2018 #2138 #1129 

## Describe the solution you'd like
A local boolean to know if a user is -as above mentioned- "looking at" at a UIX canvas. Or something akin to knowing if a user is looking and/or interacting with the canvas at all.

## Describe alternatives you've considered
LogiX though that one is fucky and would get the user even looking at the UI through other objects which is not ideal. Or requires a constant raycast to be fired to check for interactions.

## Additional context
This could also lead to disabling functions for the sake of performance if a user is not using a UI as a further step to improve performance of specifically large systems.

This could potentially also need a "IsAnyUserFocused" as a non-local value to know if any user at all is interacting with a Canvas.

**Comment by Frooxius** [comment]
What problem are you trying to solve with this?

UIX Canvas doesn't have such concept. Only certain elements can be focused, like text fields, which will make them accept text input. However this doesn't apply to the whole canvas, which is not focusable on itself.

**Comment by 3x1t-5tyl3** [comment]
Maybe focused isn't the right word here I apologise. It's more about if a user is "using" a canvas at all. Ergo if their laser is hovering over any part of the canvas.

There's a few bit's of logix that have "FireOnChange" events which requires a user (LocalFireOnChange can't be used in my scenario as I'm needing to use a constant write). Such as constantly updating a value (for example for sliding effects, scroll elements and similar) on the canvas depending on the input of the user.
Thus requiring me to get a user and the closest I can get to that rn is "NearestUserHead" which is not ideal as the closest user may not be the user who interacts with it. This particularely creates an issue where the UI freaks out if it's a user interacting with the UI who isn't firing the logix.

I can also disable the entire interactability except for the closest user to make sure on the closest user can actually use it though that seems like a hacky way to do this sort of thing..

I might be going about all of this also the wrong way.
