### ISSUE TITLE
Automatic out-of-bounds teleport resets avatar scale to 1, ignoring DefaultUserScale

### ISSUE THREAD

**Issue by Gawdl3y** [Neos-Metaverse/NeosPublic#2419]
## Describe the bug
The default out-of-bounds teleport behaviour when falling out of the world resets the scale of the user to their avatar's default scale, ignoring any DefaultUserScale component. The reset scale context menu button is immediately available to use to reset back to the scale specified by DefaultUserScale.

## Relevant issues
None

## To Reproduce
1. Add a DefaultUserScale component to an avatar with a scale of something other than 1
2. With that avatar equipped, fall out of the world
3. Upon being teleported back, your scale is reset to 1

## Expected behavior
The user's scale resetting should respect the DefaultUserScale component rather than going back to 1.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.29.1365
 - Neos Platform: Any
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
I'm assuming that the scale resetting is intentional, in case somebody scaling too small or too large was the cause of them falling out of the world, but DefaultUserScale should probably be respected rather than the scale being reset to 1.

## Reporters:
Gawdl3y / Gawdl3y#4269

**Comment by Frooxius** [comment]
Do you have any spawn areas defined in a world where this happens? It seems like only worlds without spawn areas would be affected by this, which I can fix, but not sure if that will still result in issues.

**Comment by AshtonSparx** [comment]
If it could result in issues, you could possibly, as an alternative to forcing it natively in worlds without spawn points, have it defined in the world permissions as a bool to, rather people should re-spawn scaled 1 or respect default scale, that also gives the freedom of allowing that for certain roles

**Comment by Frooxius** [comment]
Should be fixed in 2021.6.7.794!
