### ISSUE TITLE
ContextMenu - Option to not re-center the context-menu

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2420]
## Is your feature request related to a problem? Please describe.
Currently for my Tool I'm using a "paging" system to allow for multiple pages in my context menu. This makes so that if you want to get to page 3 you're gonna end up moving the context menu every time which can get annoying.

## Relevant issues
#2379 #2378

## Describe the solution you'd like
An option for the ContextMenuItem do disallow re-centering of the context menu (open the center of the menu where the previous one was). See video below.

## Describe alternatives you've considered
-

## Additional context
https://youtu.be/Crd5Nl3W-l8
As seen in this video the context menu starts moving further and further away which can be annoying for paged menu's like mine.

The first tool is an old tool with LogiX based injection; the new one is with the neos-native injection.
Having the capability of doing it like the previous one where it wouldn't re-center would be extremly nice and I'd rather have a proper implementation than more jank with logix.

**Comment by Frooxius** [comment]
Added in 2021.6.7.794!
