### ISSUE TITLE
NeosBot - CloudVariable argument documentation

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2426]
## Where have you searched for this information before making this issue?
ProbablePrime's videos, the wiki, #questions-help and bunch of other users.
The bot commands are not well documented and need more of it to make it easier to understand for the "normal" user rather than just staff.

I'm also well aware that these commands are only until we get a proper interface. Though until then I'd like to still document it into the wiki for easier user experience for others who run into the same issues.

More context in the questions-help on the discord from this message upwards:
https://discord.com/channels/402159838827905024/439421735474036738/851254254127153193

## Which part of the system do you need information on?
The extend that the NeosBot (Contact) needs the cloudvariable argument.
Ergo if I try to make
_/createGroupVar G-Exitian Test.Path1_
the bot accepts it. But if I tried
_/createGroupVar G-Exitian Test.Path1 string:8192_
the bot yells at me with "Invalid" argument.

Having more info on what the bot **exactly** accepts and rejects would be nice.

## What information do you need to know?
What does the bot accept and what does it reject?
Does it accept only certain "variants" of creating variables?

## Do you plan to format and contribute the provided information to Wiki?
Ofcourse. It'll be added to the CloudVariable page.
https://wiki.neos.com/Cloud_Variables

**Comment by ProbablePrime** [comment]
In the context of commands () denote optional arguments and <> denotes required.

Specifically for createGroupVar:
* `/createGroupVar <group> <path>` - takes 2 arguments and succeeds
* `/createGroupVar <group> <path> <type>` - is invalid as there is no form of this command which takes 3 arguments. 

For the larger `/createGroupVar <group> <path> <type> <default value> <read perms> <write perms> <list perms>`

All 7 arguments are required for it to work.

I'll update things around to make this clearer. Generically I don't recommend the full 7 argument command though as its harder to reason about.

**Comment by ProbablePrime** [comment]
I am closing this, if you have further comments or questions please let me know
