### ISSUE TITLE
Setting to prevent custom menus spawning on hands with equipped tool

### ISSUE THREAD

**Issue by Electronus** [Neos-Metaverse/NeosPublic#2429]
## Is your feature request related to a problem? Please describe.
The Context menu can already be crowded with some tools, adding more arcs tends to make it worse so having  away to disable custom ones without shutting it off entirely would be a nice feature. 

## Relevant issues
I though #2344 but the additions due to it can't be used in they way I want. 

## Describe the solution you'd like
Some way of disabling the context menu per hand, dynamically, either by it detecting if a tools is equipped on that hand, or by allowing cirality to be written via logix/components. 

## Describe alternatives you've considered
Disabling it entirely with a tool equipped but this is inconvenient.

**Comment by shiftyscales** [comment]
This can be made very easily in Logix, but I could certainly see the appeal in exposing an option for this.

**Comment by Electronus** [comment]
It would need at least a input made with this type.  
![image](https://user-images.githubusercontent.com/64871170/121085844-fe02e300-c7a7-11eb-831d-9131781c8022.png)

or register- something so that I can tell it what hand to appear on.

**Comment by Frooxius** [comment]
Added "ExcludeOnTools" in 2021.6.8.685, thanks!
