### ISSUE TITLE
Can't use "Chirality?" nullable for ValueCopy or drives and similar

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2430]
## Describe the bug
When trying to do a valuecopy or a BooleanValueDriver for Nullable chirality it fails and tells me that type is invalid.

## Relevant issues
#2344 

## To Reproduce
1. Make a valuefield
2. type "System.Nullable`1[FrooxEngine.Chirality]"

## Expected behavior
A proper Nullable chirality valuecopy similar to "float?" "float3?" ect,

## Log Files
Empty logs.

## Screenshots / Video
![2021-06-07 17 16 51](https://user-images.githubusercontent.com/61988002/121043454-f0a02580-c7b4-11eb-9462-18ebfcd2fd30.jpg)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Beta 2021.6.7.794
 - Neos Platform: Windows
 - Link to reproduction World/Item: -
 - Regression: No regression

## Additional context
Not sure what the problem is but I know that this is the first FrooxEngine nullable.

I tried a few BaseX types such as float's and RefID just out of curiosity.
I'm not aware of any other FrooxEngine nullable

## Reporters:
3x1t_5tyl3# 0001

**Comment by Frooxius** [comment]
You'll need to quality assembly for this type to work. Use `System.Nullable`1[[FrooxEngine.Chirality, FrooxEngine]]`

**Comment by 3x1t-5tyl3** [comment]
fffff I forgot those existed. Apologies. Thanks!
