### ISSUE TITLE
FloatQRegister stores invalid quaternion when generated

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2432]
## Describe the bug
The FloatQRegister node when spawned has an invalid quaternion (0,0,0,0) stored when generated, requiring a valid quaternion be written to it before it can be used.

## Relevant issues
#2431, #2087

## To Reproduce
- Create a FloatQ storage Logix node from Variables > Storage
- Pull out its display output

## Expected behavior
The node is generated with a valid starting quaternion.

## Screenshots / Video
![2021-06-07 10 44 16](https://user-images.githubusercontent.com/54213390/121065346-8324d280-c77d-11eb-87c6-f0702f0dd93e.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.6.7.922
 - Neos Platform: Windows
 - Link to reproduction World/Item:
 - Regression: No

## Additional context
Discovered while trying to find another method to achieve the goal mentioned in #2431.

## Reporters:
Shifty#7944

**Comment by Frooxius** [comment]
Fixed in 2021.6.8.685, thanks!
