### ISSUE TITLE
"Pressing" Events breaks after moving the cursor

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2435]
## Describe the bug
When using "Pressing" to get impulses out of a contextmenuitem the pressing event breaks when moving the cursor (VR or desktop doesn't matter)

## Relevant issues
- Didn't find any

## To Reproduce
1![grafik](https://user-images.githubusercontent.com/61988002/121104433-5961bf00-c802-11eb-9bc8-b50ec6efb522.png) Make a root context menu item with a submenu item
2. Try using the "pressing" event-

## Expected behavior
Pressing continues to fire constantly until you let go.

## Log Files
Nothing found.

## Screenshots / Video
![grafik](https://user-images.githubusercontent.com/61988002/121104437-5bc41900-c802-11eb-8a04-5fb76ba7e3a3.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Beta 2021.6.7.922
 - Neos Platform: Windows
 - Link to reproduction World/Item: `neosdb:///64dda8a957eb8fbdcdf7778b158db266a424ce5af8532024770e6266791f9ee5.7zbson`
 - Regression: No regression.

## Reporters:
3x1t_5tyl3# 0001

**Comment by Frooxius** [comment]
This isn't actually a bug, when you move the cursor that breaks the press event, because buttons by default require the cursor to be still.

We could add option so you can disable this behavior on the buttons that you need it keep pressing as long as it's held.

**Comment by ukilop** [comment]
I swear I made an issue for this already, couldn’t find it so I’ll reiterate here. I’d like an option to expose the ‘pass through vertical/horizontal motion’ checkboxes on the button component in the context menu.
 
This issue would be solved with the ability to change those checkboxes natively

**Comment by 3x1t-5tyl3** [comment]
> 
> 
> I swear I made an issue for this already, couldn’t find it so I’ll reiterate here. I’d like an option to expose the ‘pass through vertical/horizontal motion’ checkboxes on the button component in the context menu.
> 
> This issue would be solved with the ability to change those checkboxes natively

Yes I agree here. I just tested it and this literally would fix the problem I'm facing.
