### ISSUE TITLE
Method to disable the double tap to sprint

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Neos-Metaverse/NeosPublic#2439]
## Is your feature request related to a problem? Please describe.
I personally don't use the double tap to sprint, and any time I'm activating it is purely accidental.
Most of the time I rapidly tap direction keys to precisely adjust my position, however this constantly triggers sprinting, and it completely throws me off. 

## Relevant issues
None to be found

## Describe the solution you'd like
I would like a setting to disable double tap sprint.

**Comment by Frooxius** [comment]
This will be implicitly handled by the input binding system, which will let you reconfigure these. Closing this one as duplicate: https://github.com/Neos-Metaverse/NeosPublic/issues/1314
