### ISSUE TITLE
ButtonValueShift<floatQ> doesn't rotate target as expected

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2441]
## Describe the bug
Following up from #2431, it appears that ButtonValueShift<floatQ> still does not operate as expected. Based on what happens when trying to shift the value, it appears that internally it might be adding the quaternions instead of multiplying them.

## Relevant issues
#2431

## To Reproduce
- Create a ButtonValueShift<floatQ> on a button (e.g. TouchButton)
- Add a floatQ target value

## Expected behavior
The rotation should shift by the desired delta.

## Screenshots / Video
https://user-images.githubusercontent.com/54213390/121250561-b6895f00-c85a-11eb-80e4-73872a91586d.mp4

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.6.8.685
 - Neos Platform: Windows
 - Regression: No

## Additional context
As noted in the original issue, this is in the context of rotating an object each time a button is pressed.

## Reporters:
Shifty#7944

**Comment by Frooxius** [comment]
Changed the behavior in 2021.6.10.457, quaternions should now be multiplied!
