### ISSUE TITLE
Expose "PasstThroughVertical/HorizontalMovement" for Context menu items

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2443]
## Is your tweak request related to a problem? Please describe.
It would make what I wanted in the closed issue #2435

## Describe what would you like tweaked
Expose:
PasstThroughVerticalMovement
PasstThroughHorizontalMovement

For the UIX context menu item.

## Describe alternatives you've considered
-

## Additional context
See #2435 this would potentially also get rid of a few different things that I notice issues with that I haven't had the time to look into yet.

**Comment by Frooxius** [comment]
Added "AllowDrag" option in 2021.6.10.457 which should take care of this.
