### ISSUE TITLE
LogiX Node "GetContextMenuOpen"

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2445]
## Is your feature request related to a problem? Please describe.
Currently to detect if a ContextMenu is open or not we still have to do the old way of contextmenu injection.

## Relevant issues
-

## Describe the solution you'd like
A LogiXNode that gives a boolean output "true" while the context menu is open on a given user.

## Describe alternatives you've considered
LogiX that is likely to break.

## Additional context
This one of the methods and I feel like havig this exposed as a proper implementation is just better in many ways.
There's already a slew of users doing it in a similar fashion adding this logix back where in reality we should be able to just get rid of it.

![grafik](https://user-images.githubusercontent.com/61988002/121325068-9668a700-c911-11eb-9b5c-0e5a88e68266.png)

**Comment by Frooxius** [comment]
Added in 2021.6.10.457!
