### ISSUE TITLE
Handle Oculus/SteamVR on Oculus HMDS more gracefully

### ISSUE THREAD

**Issue by InsaneGrox** [Neos-Metaverse/NeosPublic#2446]
## Is your tweak request related to a problem? Please describe.
Currently when using an Oculus HMD which runtime it decides to use seems to make no sense... with some users trying to run through SteamVR getting forced to use the oculus runtime... meanwhile users trying to use the oculus runtime are forced to use SteamVR... This is a problem because we have people trying to use FBT with oculus HMDS wondering why their trackers aren't showing up in-game... and the other half are people dealing with framerate degredation from something they're likely not even aware of... and the only fix for both parties is to add a specific launch parameter to the launch options... (or a launcher that causes steamVR to launch into theatre mode and breaks everything)

## Describe what would you like tweaked
For the method of choosing runtimes to be made easier on the end user... I thought of a way of figuring out what the user's intent is based on a few simple checks...

If the user has the oculus runtime installed
If the user is NOT running SteamVR
If both checks succeed... use Oculus runtime... otherwise use SteamVR... no exceptions excluding desktop mode. (Anyone running SteamVR before they run neos obviously wants to run Neos through SteamVR)

## Describe alternatives you've considered
Making it easier to specify which runtime you prefer... possibly in-game setting? I still think the former would be more effective though since new users on oculus HMDS using vive trackers and playspace calibrator will actually see their trackers in-game instead of troubleshooting for an hour and then getting pissed because all they had to do was type in some very specific text into an obscure text box in steam that's not easily accessible... or use a launcher that's not VR friendly. (and likely will cause steamVR to enter theatre mode)... 

## Additional context
I myself do NOT own an oculus HMD so most of this is based on other's accounts of what happens... however if I did have an oculus HMD I'd be pretty annoyed with this since I'm the type of person who'd be using ALVR with a quest... which runs through steamVR natively and fully supports skeletal hand tracking.

**Comment by Frooxius** [comment]
This one's a bit tricky, since the initialization of runtimes is mostly handled by Unity and the runtimes themselves, it's not something we do on our end (and generally shouldn't).

With auto-detection the Oculus runtime is tried first, then the SteamVR one. This already performs some of the checks that you propose, if the Oculus Runtime is not used, it means that it has for some reason refused to initialize. I'd need more information - logs (including Player.log) from such case, since it sounds like there's rather something going wrong.

One thing we could potentially do is check for running SteamVR process and skip the Oculus initialization in that case, that could account for some of the problems.

Unfortunately it's not possible to make this in-game setting though, that's too late to perform the switch since it was already initialized at that point.

**Comment by Frooxius** [comment]
Yeah I can do that one.

On the cases of Oculus users wanting Oculus and getting SteamVR though I don't know. Oculus is always initialized first on auto-detection, so that's failing for some reason.

**Comment by InsaneGrox** [comment]
> Yeah I can do that one.
> 
> On the cases of Oculus users wanting Oculus and getting SteamVR though I don't know. Oculus is always initialized first on auto-detection, so that's failing for some reason.

weird part is I've heard reportedly forcing it fixes it for them... so that means something in those cases is causing Neos to give up before it can initialize even though it can initialize. hopefully someone can give logs for when that happens and when they force it and it works for comparison.

**Comment by H3BO3** [comment]
Yeah, I definitely haven't seen that one as often.

**Comment by Frooxius** [comment]
> 
> 
> > Yeah I can do that one.
> > On the cases of Oculus users wanting Oculus and getting SteamVR though I don't know. Oculus is always initialized first on auto-detection, so that's failing for some reason.
> 
> weird part is I've heard reportedly forcing it fixes it for them... so that means something in those cases is causing Neos to give up before it can initialize even though it can initialize. hopefully someone can give logs for when that happens and when they force it and it works for comparison. (I think Enverex might be able to help here)

That seems really strange. Oculus is always initialized first. We don't have any logic that would "give up", that's all handled Unity/Oculus side. It sounds like it might just be failing randomly, but they have assumed that forcing it was what fixed it, even though it didn't. I'd definitely need logs to be able to tell more.

**Comment by Frooxius** [comment]
I've added the better handling in 2021.6.10.457 when SteamVR is detected to be running, hopefully it helps. If you get information about Oculus not wanting to initialize I'd recommend opening a bug report for that, I'm going to close this otherwise since there's not much else we can do now.
