### ISSUE TITLE
ExternalSlotSaver crashes game when saving if target is a parent

### ISSUE THREAD

**Issue by seif1** [Neos-Metaverse/NeosPublic#2452]
## Describe the bug
ExternalSlotSaver causes crash when target slot is a parent of the slot with the component

## Relevant issues
None

## To Reproduce
1. Create a slot
2. Create a child for that slot
3. add ExternalSlotSaver to the child slot
4. target the parent slot in the ExternalSlotSaver
5. Save the object

## Expected behavior
That it would not crash when saving

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.6.10.457
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: Not that I know of

## Reporters:
seif1#6014

**Comment by Frooxius** [comment]
Fixed in 2021.7.1.437, thanks for report!
