### ISSUE TITLE
Add a "reload locale" to the locale menu

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2455]
## Is your feature request related to a problem? Please describe.
Currently it's impossible to translate Neos in realtime. This can be especially useful when wanting to do quick itterations with large texts as we also do formatting for things like the streaming room and similar.

## Relevant issues
-

## Describe the solution you'd like
A reload button in the "Choose your language" section so we can more easily reload our locale.
OR
Alternatively a start parameter which would constantly (once a second) reload the current locale.
(Obviously with Lag being expected)

## Describe alternatives you've considered
Reboot neos.
Or type it out in neos which has the problem that with long text it's really hard to see where my cursor is or to do large formatting of text/copy pasting etc.

## Additional context
Realtime translation is a lot easier if we can also adjust the text in realtime. Not being able to do so dampens how quickly a locale can be performed with proper formatting. 

Errors like these are more easily found when seen in-game rather than in a text editor.
![grafik](https://user-images.githubusercontent.com/61988002/121695941-d7a4b680-cacb-11eb-8107-1b163ece3574.png)

**Comment by Frooxius** [comment]
Hmm something like this could potentially be added, I'm thinking what might be the best solution. Technically we can watch the file system changes and when the file is modified, trigger the reload. Normally the changes don't occur, so it wouldn't even need anything special from your end, other than changing the file.

**Comment by 3x1t-5tyl3** [comment]
That would be the preffered approach this could make translating much easier given the changes happen 1:1 allowing one to use any external editor instead of just having to reload as-well. Though I can see some issues if the translation file get's edited in ways that neos might not like.
![grafik](https://user-images.githubusercontent.com/61988002/121717690-bfd82d00-cae1-11eb-8266-4f2a87c1c8d4.png)

**Comment by Frooxius** [comment]
The locale should now auto-reload whenever the file gets changed in 2021.6.14.1031, hope it helps with translating!
