### ISSUE TITLE
Check for an existing ban of a user before banning them (Headless client)

### ISSUE THREAD

**Issue by glitchfur** [Neos-Metaverse/NeosPublic#2457]
## Is your tweak request related to a problem? Please describe.
Users can be banned multiple times via the `banByUser` or `banByID` commands, causing them to "stack". This can be verified with `listbans`. Users must be unbanned the same number of times as they have been banned for the user to be able to join a session again.

![Screenshot from 2021-06-11 21-26-25](https://user-images.githubusercontent.com/14147284/121762583-63363b80-cafc-11eb-8480-fc286efb7b45.png)

## Describe what would you like tweaked
Please add a check and subsequent error message that prohibits banning a user who has already been banned, similar to attempting to unban a user that has not been banned.

## Describe alternatives you've considered
I do not have any alternative solutions.

## Additional context
N/A

**Comment by Frooxius** [comment]
Fixed in 2021.6.14.1031! Thanks!

**Comment by glitchfur** [comment]
Thank you for fixing this. It works as intended, but I have found another situation that causes bans to stack. The steps to reproduce this are:

1. Start a headless client, join the session from Neos.
2. Ban yourself using either `banByName` or `banByID`. You'll remain in the session.
3. Ban yourself again with `ban`, which applies the ban again and removes you from the session.
4. There are now two bans for the same user. Both need to be removed to be able to join again.

`ban` should perform the same check for an existing ban that `banByName` and `banByID` does.

Screenshot for reference:

![banstack](https://user-images.githubusercontent.com/14147284/122001605-30977780-cd76-11eb-9853-9e13c1391ac0.png)
