### ISSUE TITLE
Ability to DENY access to headless public/contacts/etc sessions based on access cloud variable

### ISSUE THREAD

**Issue by Gawdl3y** [Neos-Metaverse/NeosPublic#2459]
## Is your feature request related to a problem? Please describe.
Currently, there is no way to override a user being allowed to connect to a session if they meet the usual criteria (contact of the host when set to contacts only, no requirements if set to anyone, invites, etc). The ability to do this would be very useful for a lot of use-cases, the biggest one being events run in Neos. 

## Relevant issues
None

## Describe the solution you'd like
A mode switch to allow the cloud variable specified in `allowUserCloudVariable` (or a separate variable) to override the default access checks entirely, denying access to the session if the value of the variable for the connecting user is `false`, and *only* ever allowing access if the value is `true`. This should take precedence over all other checks, including invitations. Ideally, there should also be a way to return a custom error message when they're denied access that displays on their client as part of the connection failed message.

## Describe alternatives you've considered
Requiring everybody to friend the headless user is an option for very small operations, but doesn't scale well at all for larger events with multiple hosts. It also doesn't allow anybody to see details about the sessions before they're contacts.

## Additional context
This is something we (VBLFC staff & volunteers) discussed with some of the Neos staff already, I just wanted to get this issue put in to make sure it doesn't fall off the radar.

**Comment by shadowpanther** [comment]
This was added in 2021.6.14.1204

> - Added `denyUserCloudVariable` to world startup configuration, which allows denying join access to users via a cloud variable
> -- This functions similarly to `allowUserCloudVariable`, except when the value for given user is true, they will be denied access
> -- This always takes precedence over other variables
> - Added `requiredUserJoinCloudVariable` to world startup configuration, which requires a cloud variable to be set to true for given user so they can join
> -- You can set a custom deny message via `requiredUserJoinCloudVariableDenyMessage`
> -- If the variable isn't set to true for given user, they won't be allowed access
> -- Setting the variable to true won't automatically grant access (unlike `allowUserCloudVariable`) and will still need to pass other rules - public access, session user limit and so on
> -- `allowUserCloudVariable` takes precedence over this one, allowing to always allow given user access
> -- This variable is useful for controlling access to a session, without bypassing the session max user limit and providing a custom message (requested by @Geenz | Graphics Programmer on behalf of VBLFC)

**Comment by ProbablePrime** [comment]
Confirming this was added and should meet the requirements, @Gawdl3y please ping me here or contact me or the team via any other means if there is an issue with this functionality.

Thank you!
