### ISSUE TITLE
ValueGradientDriver "overflow" option

### ISSUE THREAD

**Issue by Honzackcz** [Neos-Metaverse/NeosPublic#2461]
## Is your tweak request related to a problem? Please describe.
When I want to regulate intensity of a color, ValueGradientDriver can do it well, but it cannot increase color intensity over input color values (like multiplication do).

## Describe what would you like tweaked
Graph is for case with single float value.
![image](https://user-images.githubusercontent.com/76910833/121782109-4d7e5000-cba8-11eb-8473-7a2dfa53ef8c.png)

## Describe alternatives you've considered
Whole ValueGradientDriver can be replaced with LogiX to get this functionality.

**Comment by Frooxius** [comment]
We can make it so it extrapolates the last values, but the extrapolation will likely just be linear (follow in a straight line) based on the last two values in the gradient, meaning any complex curve you can have defined won't be followed.

**Comment by Honzackcz** [comment]
> We can make it so it extrapolates the last values, but the extrapolation will likely just be linear (follow in a straight line) based on the last two values in the gradient, meaning any complex curve you can have defined won't be followed.

This is what I want from it. And I know that anything else then linear will not really work.

**Comment by Honzackcz** [comment]
I got an idea for another alternative: Instead of a ValueGradientDriver we can use a LinearMapper. In that case there will have to be a color variant of LinearMapper. Now there is only 4D mapper that works same but cannot be connected to a color.

**Comment by shadowpanther** [comment]
> I got an idea for another alternative: Instead of a ValueGradientDriver we can use a LinearMapper. In that case there will have to be a color variant of LinearMapper. Now there is only 4D mapper that works same but cannot be connected to a color.

Yes please, that would simplify a large number of setups!

**Comment by Frooxius** [comment]
Ok I added the LinearColorMapper in 2021.6.14.1031!
