### ISSUE TITLE
UIX - Add Image when adding a Mask

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2462]
## Is your tweak request related to a problem? Please describe.
It's annoying to add an image everytime I'm adding a "mask" to create scrollers or similar.

## Describe what would you like tweaked
Add an "Image" component whenever a "Mask" is added and no image is present.

## Describe alternatives you've considered
-

## Additional context
![grafik](https://user-images.githubusercontent.com/61988002/121784367-fc745900-cbb3-11eb-8342-2c852e578994.png)

**Comment by Frooxius** [comment]
Added in 2021.6.14.1031, thaks!
