### ISSUE TITLE
Read/Write Cloud Variable logix node text incorrect

### ISSUE THREAD

**Issue by Lexevolution** [Neos-Metaverse/NeosPublic#2469]
## Describe the bug
The name text on the Read/Write Cloud Variable LogiX nodes do not display the data type, but only displays "Variable`1".
This is inconsistent behaviour compared to the Read/Write Dynamic Variable LogiX nodes.

## Relevant issues
None.

## To Reproduce
Steps to reproduce the behaviour:
1. Open the LogiX node browser through a LogiX tooltip
2. Go to Variables
3. Select either Read or Write Cloud Variables
4. Choose any data type
5. Spawn out the LogiX node
6. Observe the inconsistency

## Expected behaviour
An expected behaviour example would be if "int" was chosen as the data type for the Read Cloud Variable node, the spawned LogiX node would be called "Read Cloud int".

## Log Files
N/A

## Screenshots / Video
![2021-06-13 23 41 03](https://user-images.githubusercontent.com/31176843/121810371-fa89c300-cca3-11eb-90a0-dc2b1ab997d9.jpg)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.6.10.457
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: Unsure

## Additional context
N/A

## Reporters:
IGN: Lexevo
Discord: `Lexevo#0876`

**Comment by Frooxius** [comment]
The labels are now nicer in 2021.6.14.1031!
