### ISSUE TITLE
A way to non-destructively cleanup local database

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2473]
## Is your feature request related to a problem? Please describe.
There are reports from different users that their Neos.litedb file is taking quite a lot of space and currently there's no way to clean/shrink it without entirely deleting it. My database is 2.5Gb, Psychpsyo's is over 5Gb, etc. While the cache and assets folders could be manually/automatically cleaned up of old files, the database is in one big chunk and not serviceable.

## Relevant issues

* #58

## Describe the solution you'd like
A way to manually trigger the database cleanup, probably as a commandline option because I suspect the database has to be in an unused state for proper cleanup/compress cycle. The process would remove any records marked as already synced to the cloud and other leftovers, then compress the structure to get rid of the unused empty space.

Even better way would be for Neos to automatically clean up and shrink the database once in a while, alongside with cleaning up the Cache and Assets folders.

## Describe alternatives you've considered
Delete the database once in a while, losing the settings, dash customisations and logging in afresh.

## Additional context
https://discord.com/channels/402159838827905024/439421735474036738/853939198452039711

**Comment by Frooxius** [comment]
This is planned for the automatic cache and asset management, which will delete any assets from both database and harddrive if they reach certain storage/age limit. It'll be automatic task, but the plans is to be able to say "Trim the cache to 10 GB" through some interface.

Implementing it is a bit bigger chunk of work though to implement the actual trimming and management mechanism, so it'll have to be prioritized appropriately. After that command-line and such is just question of interface for this functionality.

**Comment by dfgHiatus** [comment]
Hey all, I've created a workaround for this issue: https://github.com/dfgHiatus/CacheGetClapped
