### ISSUE TITLE
Rename UV Displace Map and Offset Map to Flow Map or alternatively create parity between the two names

### ISSUE THREAD

**Issue by Epimonster** [Neos-Metaverse/NeosPublic#2474]
## Is your tweak request related to a problem? Please describe.
Both "UV Displace Map" and "Offset Map" found in PBS_Displace Metallic/Specular and Unlit respectively serve the same function which is to displace a texture based on data in the red and green channels. They both act identically when configured to default settings, and as such it is confusing to give them two separate, Neos specific names.

## Describe what would you like tweaked
UV Displace map and Offset Texture should both be renamed to Flow Map for more clarity as to their function.

## Describe alternatives you've considered
Alternatively, a name could be chosen that is applied to both. If both were renamed to either Offset Texture or UV Displace Map it would be more clear they serve the same function.

## Additional context
Flow Map is a much more common term than UV Displace Map and Offset Texture. While neither are wrong upon googling "flow map game shader" you can find numerous resources and tools to create flow maps as well as art assets available for purchase that serve as flow maps and would work in Neos. Googling "uv displace map game shader" you can find tutorials on how to make a shader similar to  the one on Neos but no available information on maps for them. The same issue applies to "offset texture map" and "offset map game shader." Additionally within Neos, a lot of people who I've told about this have been surprised to learn that the shader supported data in both the red in the green channels, assuming that since the Vertex displace map found in the same shader worked only on one channel that the UV Displace Map was also similar. Upon me mentioning that it functions similarly to a flow map the confusion was cleared up and they understood what it's function was, as it's a more commonly used term both in the unity development space and outside.

![20210608210004_1](https://user-images.githubusercontent.com/44652736/121943478-3c078600-cd17-11eb-9f6c-941775b23698.jpg)

Sorry if this is a bit hard to read. The image more serves to demonstrate that there is no observable difference between these shaders when configured identically.

This change is being suggested by Gareth48 (Gareth48#3428)

**Comment by Frooxius** [comment]
Thank you for the suggestion, but "Flow map" isn't a correct term for these as they're technically not flow maps, although they are similar.

Typically flow map results in actual "flow" over time, but these are static offsets/displacements, so their names reflect that. They also follow general naming convention of other things in Neos

**Comment by Epimonster** [comment]
Okay, cool that's a distinction I wasn't aware of, but is it possible they could at least be renamed to the same name across both shaders? Keeping them two different names when they serve the same function is rather confusing.
