### ISSUE TITLE
World Permission To Disable Custom Context Menus

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2478]
## Is your feature request related to a problem? Please describe.
I would like a world permission that disables the use of Custom Context Menus. If there's a way to separate it from tools and it just being on a user, that would make this twice as better. Mainly because these menus can be used to bypass Spectator Permissions. 

## Relevant issues
None I could find through quick searching

## Describe the solution you'd like
A world permission that can disable custom context menus. Perhaps even a bool so you can include/exclude custom menus on tooltips so it'll remain flexible. To avoid conflict, have all roles allowed by default. So the world creator can choose if they want to disallow the use.

## Describe alternatives you've considered
Unsure of any alternatives but open to feedback.

## Additional context
As awesome as the new menus are, they can be used to bypass world permissions to toggle stuff on yourself, play audio at will, ect

**Comment by Electronus** [comment]
I have to admit this is part of why I at least was excited about them, so I could for example toggle my wings when in spectator mode.

**Comment by shadowpanther** [comment]
Same as @Electronus, my wrist menu didn't allow me to change my avatar's color settings in spectator mode, so I transferred it partly to Dash via cloud vars and partly to context menu. Not allowing users to use custom menus would prompt for other solutions, which would again circumvent this permission.

**Comment by shiftyscales** [comment]
I don't think this is a good solution. People will use context menus for any number of controls, and if you are going to strip them of that, you might as well also just prevent them from loading their cloud avatar using the existing permissions.

If someone wishes to utilize malicious functionality, they can do it just by having Logix on their avatar, they don't need to utilize the context menu for this. They could even use Logix to inject buttons into the context menus, which brings you right back to the start.

Hard permissions #289 could take care of quite a few of the needs of this issue, and for everything else, world hosts can deal with users directly by utilizing the existing permissions of the permission system, or using other moderation tools they have available to kick/ban, etc.

If anyone is in violation of the guidelines, they can also be reported through a ticket at https://moderation.neos.com/.
