### ISSUE TITLE
VelocityHapticFilter component

### ISSUE THREAD

**Issue by RyuviTheViali** [Neos-Metaverse/NeosPublic#2479]
## Is your feature request related to a problem? Please describe.
This component would solve a problem where the intensity of haptic feedback per haptic sample point would need to change based on its velocity.

## Relevant issues
There are no relevant issues.

## Describe the solution you'd like
This component would work in tandem with the HapticVolume component. Given a minimum intensity, maximum intensity, and velocity multiplier (or possibly minimum and maximum velocities), any haptic sample points in the volume would have their individual intensities driven by their local velocity.

## Describe alternatives you've considered
A current alternative to this proposal is an implementation in LogiX, which as it stands is not as performant as it could be.

## Additional context
No additional content.

**Comment by Frooxius** [comment]
Added in 2021.6.18.4, thanks!
