### ISSUE TITLE
CylidricalDistanceHapticFilter Component

### ISSUE THREAD

**Issue by RyuviTheViali** [Neos-Metaverse/NeosPublic#2480]
## Is your feature request related to a problem? Please describe.
Currently when constructing haptic trigger volumes based on cylinders or circles, there is no way (without utilizing LogiX) to have a cylindrical shell in which haptics are triggered.

## Relevant issues
No relevant issues.

## Describe the solution you'd like
A component which, either given the collider's axes, or given an arbitrary axis defined in the component, and a minimum and maximum radius, confines the haptic feedback to a cylindrical shell around the given axis. Similar in behavior to RadialDistanceHapticFilter.

## Describe alternatives you've considered
This can be implemented in LogiX, but the performance is not as optimal.

## Additional context
No additional context.

**Comment by Frooxius** [comment]
Added in 2021.6.18.4, thanks!
