### ISSUE TITLE
Default format node to spawn with one input

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#2481]
## Is your tweak request related to a problem? Please describe.
When spawning a format node from strings, it starts with 0 Inputs which can make the node look a little confusing. The + Button intersects the node name

## Describe what would you like tweaked
Tweak the node to start/be spawned with one input

**Comment by Frooxius** [comment]
Released your tweak in 2021.6.18.4 thanks! :D
