### ISSUE TITLE
Add an InputCount output to Impulse Multiplexer

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#2482]
## Is your tweak request related to a problem? Please describe.
Regular Multi-plexer has a count output. This is useful sometimes to alter information based on how many values there are available.

## Describe what would you like tweaked
Add an InputCount output to ImpulseMultiplexer

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by Frooxius** [comment]
Released in 2021.6.18.4, thanks!
