### ISSUE TITLE
Add Min/MaxRange & Linear/logarithmic options to RandomAudioClipPlayer

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2484]
## Is your tweak request related to a problem? Please describe.
When wanting to use RandomAudioClipPlayer component. It allows you to set a weight of its likeliness to play, its Min/Max Volume, speed and Spacialize. But there's no Min/Max Range. And rather if it's Linear or logarithmic.

## Describe what would you like tweaked
I would like Min/Max range to be added to the Clips List of RandomAudioClipPlayer and Linear/logarithmic options

## Describe alternatives you've considered
I don't think there would be any alternatives to this that I can think of on the top of my head.

## Additional context
These are the only options it has currently
![image](https://user-images.githubusercontent.com/53165730/121990971-b9111a80-cd6c-11eb-8b3e-1e558f179c81.png)

**Comment by Frooxius** [comment]
This can be added. There's a few ways though, would you want each clip to have different range and rolloff? Or would this be better as global setting?

Maybe if I make them nullable by default it could work well to override it for individual clip, while having global settings for the rest.

**Comment by AshtonSparx** [comment]
I like that option ^w^ would also make it not break existing RandomAudioClipPlayer's being used

**Comment by Frooxius** [comment]
Added in 2021.6.18.4!
