### ISSUE TITLE
Display user IDs alongside usernames with "users" command (Headless client)

### ISSUE THREAD

**Issue by glitchfur** [Neos-Metaverse/NeosPublic#2485]
## Is your tweak request related to a problem? Please describe.
`banByID` allows for banning a Neos user by their user ID, however there isn't a way to obtain a user's ID prior to banning them in the headless client itself. The only command I have found that lists user IDs is `listbans`.

## Describe what would you like tweaked
Add a column to the `users` command that lists the user IDs of all the users in the focused session.

## Describe alternatives you've considered
An alternative solution would be to add a command that performs these lookups separately.
**Example:** `lookupID GlitchFur` would return `U-GlitchFur`.

## Additional context
N/A

**Comment by Frooxius** [comment]
Added in 2021.6.18.4, thanks!
