### ISSUE TITLE
Add existing ban check to "ban" command (Headless client)

### ISSUE THREAD

**Issue by glitchfur** [Neos-Metaverse/NeosPublic#2486]
## Is your tweak request related to a problem? Please describe.
This is an extension of issue #2457.

Bans can still be stacked if a user is banned using `banByName` or `banByID` first (which does not remove them from the session), and then banning them again with `ban`. The steps to reproduce this are:

1. Start a headless client, join the session from Neos.
2. Ban yourself using either `banByName` or `banByID`. You'll remain in the session.
3. Ban yourself again with `ban`, which applies the ban again and removes you from the session.
4. There are now two bans for the same user. Both need to be removed to be able to join again.

## Describe what would you like tweaked
`ban` should perform the same check for an existing ban that `banByName` and `banByID` does.

## Describe alternatives you've considered
I do not have any alternative solutions.

## Additional context
Below is a screenshot of the double ban.

![banstack](https://user-images.githubusercontent.com/14147284/122115082-a852ba00-cde9-11eb-8d2f-5e4ee10ff277.png)

**Comment by Frooxius** [comment]
Should be fixed in 2021.6.20.36, it'll now add the extra ban data when banned with `ban` command rather than duplicate, let me know if you run into any more issues! Thanks!
