### ISSUE TITLE
Recategorize ScaleTransition component

### ISSUE THREAD

**Issue by Sox-NeosVR** [Neos-Metaverse/NeosPublic#2490]
## Is your tweak request related to a problem? Please describe.
I used a combination of alot of components then later on i discovered it can all be done with this single component.

## Describe what would you like tweaked
'ScaleTransition' Component to be moved from Uncategorized to Transform->Drivers.

**Comment by Frooxius** [comment]
Recategorized in 2021.6.18.4, thanks!
