### ISSUE TITLE
Make String Formatting respect the Neos language setting

### ISSUE THREAD

**Issue by Banane9** [Neos-Metaverse/NeosPublic#2492]
## Is your tweak request related to a problem? Please describe.
I'm using Neos with English UI, on a German locale Windows. Thus, everything gets displayed in english - except when string formatting gets involved. As shown in the screenshot below, the am/pm formatting for 12h times gets displayed as `nachm.` for afternoon in German. The other significant thing this affects is formatting of floating point values: for example Uki's redprint label reads version 1,0 for me, rather than 1.0 for others in the session.

![Nachm. formatting instead of pm for 12h time](https://user-images.githubusercontent.com/2124570/122180191-7cd2dc80-ce88-11eb-8f79-0554fbe60d64.jpg)

## Describe what would you like tweaked
It would be nice if setting the language inside Neos would also set the process locale accordingly.
From NET 4.5 on this should just require one line, shown below. Before that, it requires setting it for the main thread and any other (relevant) threads when they get created.

```CSharp
System.Globalization.CultureInfo.DefaultThreadCurrentUICulture = System.Globalization.CultureInfo.GetCultureInfo("en-US");
```

## Describe alternatives you've considered
Invariant culture could be used for formatting by default, if not specified as an input otherwise. Tying it to the language (or an additional setting) by default seems more suitable.

**Comment by Banane9** [comment]
As tried with ShadowPanther, the formatting is also inconsistent between ToString and the Format node.

```
1.0 -> ToString -(1.0)-> ParseFloat -> 1.0
1.0 -> Format({0}) -(1,0)-> ParseFloat -> 0/fail
```

**Comment by ProbablePrime** [comment]
I can take this.

**Comment by ProbablePrime** [comment]
- ToString uses `InvariantCulture`
- A lot of items use the default(Not Specified) option(Which defaults to CurrentCulture?):
	- Format 
	- ToTimeString (String->QuickFormat)
- The new Nodes I was working on in: https://github.com/Neos-Metaverse/NeosPublic/issues/2600 use `CurrentCulture` so i'll confirm this before pushing those.
- A lot of random nodes, use not specified. I'm not sure of the expectations of how that works when not specified so I dont want to touch these but just mentioning:
	- ReplaceFirstSubstring
	- StartsWith
	- etc

My preference here is to standardize them but I was wondering if expanding the use of the Culture nodes we have in these nodes might be another option. 

For example including a Culture input on Format on:
- Format
- Parse

etc could solve your issues.


Please share some thoughts, I'll also speak to the team.

**Comment by ProbablePrime** [comment]
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305#rule-description

Covers a CSharp rule that has a good set of "Best Practices" to follow here. Its also flagging a lot in our code base D:

**Comment by Banane9** [comment]
>For example including a Culture input on Format on:
>
>*Format
>*Parse
>
>*etc could solve your issues.

That would work, ideally with invariant culture being the default. Just had it again the other day that some json hacking using the Format node fell apart because it was run on a culture that formats decimals with comma. Was made by someone that didn't have that problem, of course.

**Comment by Banane9** [comment]
Coming back to this, that would also follow point three of the quality rules you've linked above, letting the "consumer" of the data decide which culture to use for formatting, as the nodes can't know how their data is being used. And it seems to be a fair assumption, that anyone can read the invariant culture formatting and the usage as data should be the default, if output to the user isn't implied through plugging a "local culture" node or some other source for the formatting culture into it.  
Automatically fixing any improper usage of Format with float inputs to build json or other data messages seems like the better option, preventing errors on systems that don't happen to match invariant culture for formatting, while it also shouldn't influence readability for anyone.

**Comment by ProbablePrime** [comment]
I just submitted a Code Change which adds format providers to:
1. ToTimeString
2. Format
3. FormatTime
4. FormatDate
5. FormatTimespan

The default value in all cases is CurrentCulture.

**Comment by Banane9** [comment]
>The default value in all cases is CurrentCulture.

Frankly I think this will just lead users to produce buggy code when formatting data into json and such. I.e. someone with `.` as separator will build it, see it works fine without any culture input and then it will still break when it's used by someone with `,` as separator.

I think it's better to make CurrentCulture a conscious choice for when you know you're using the text for displaying to other users and want it formatted accordingly.

**Comment by Banane9** [comment]
I can see the reluctance to switching this from how it works in C#, but there I've not seen it used to format data like people do in Neos. This also wouldn't be the first time, as the ToString node currently formats with InvariantCulture, rather than the CurrentCulture which would be the case in C#.

**Comment by shadowpanther** [comment]
> Frankly I think this will just keep users producing buggy code when formatting data into json and such. I.e. someone with `.` as separator will build it, see it works fine without any culture input and then it will still break when it's used by someone with `,` as separator.

Then it'd be the issue of educating the users and fixing the items. "Works on my machine" is a bad excuse for bad code. Making the culture switch by default would break current behaviors.

**Comment by Banane9** [comment]
>Then it'd be the issue of educating the users and fixing the items. "Works on my machine" is a bad excuse for bad code. 

Exactly, hence I think it'd be a good idea to make the defaults be as independent from the user's machine as possible. ToString uses InvariantCulture by default too, after all.

>Making the culture switch by default would break current behaviors.

As I've explained before, I think that would only have the potential to "break" visuals, with anyone still able to read it, while fixing other items.  
However afaik it is possible to insert nodes and such to adapt changes, so in this case a CurrentCulture node could be added as input for the format.

**Comment by Zyzyl** [comment]
Would it also make sense to add a field (maybe an Enum?) to the various non-LogiX components which take format codes? Ones off the top of my head would be:
- ValueTextFormatDriver<T>
- MultiValueTextFormatDriver
- FloatTextEditorParser
- IntTextEditorParser
- QuantityTextEditorParser

**Comment by Banane9** [comment]
Definitely, I would say.

**Comment by ProbablePrime** [comment]
I'll double check the current default when it is not provided. We will have to stick to the current default with the option of providing the opposite value regardless of what it is.

This is because we cannot break any existing setups, no matter what people's thoughts are we have to prioritize sticking to current behaviour as much as possible. That's how Neos is designed. In some cases we won't make a change if we don't have a path for backwards compatibility. 

As for the components. I'll take a look what we can do.

@Banane9 please be careful with double posting. if no one has replied please edit your previous post.

**Comment by ProbablePrime** [comment]
The current default culture is CurrentCulture, so my change will keep the current behaviour unless you overwrite it.
