### ISSUE TITLE
Hidden sessions do not properly show metadata/previews

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#2495]
## Is your tweak request related to a problem? Please describe.
Currently if a session is hidden you can't get anything Metadata wise in form of users, preview, or even stats/world name. Usernames as well too. 

## Describe what would you like tweaked
Metadata available through hidden sessions.

## Describe alternatives you've considered
There aren't much. You can do other session types but sometimes you kinda need this for things such as gates, or instances. 

## Reporters:
Turk
Epsilon
Gawdly

**Comment by Frooxius** [comment]
This is intentional, that's pretty much what hidden means - you don't get information about the session. If you don't want the metadata to be hidden, don't mark the session as hidden.

**Comment by TehTurk** [comment]
Hmm thats fair! I just ran into this problem of where I can't have a private public session in a way that is only accessible through setup or links. (We ran into this for VBLFC and I wanted to alleviate some of the issues we ran into)

**Comment by TehTurk** [comment]
Would it be okay to reopen a different issue but focus on a new one for Private Public Space in some way? We want sessions being open, but accessible through another world only. Lobby -> Unlisted/Unseen Public Instance To give context.

**Comment by Aerizeon** [comment]
@Frooxius I'd like to be able to configure it such that I can still get the Metadata for a session (so it can be scraped), and it be publicly accessible, but not show up in the session list for everyone in neos. 

I can't really think of any way to accomplish that at the moment.

**Comment by Khosumi** [comment]
> I'd like to be able to configure it such that I can still get the Metadata for a session (so it can be scraped), and it be publicly accessible, but not show up in the session list for everyone in neos.

That should be off by default, if it is to be considered.

**Comment by Frooxius** [comment]
Yes, that would be better for another mode/toggle. However "private public session" is self-contradictory, it can be only one or the other.

E.g. even if it's not listed by default, it can be trivial to get the session data and it can be displayed in different public places, so it must be treated as a public one - the mechanism won't guarantee you actual privacy, it'll just be a cosmetic. This also means it'd have to follow same guidelines as public sessions.

Hidden sessions provide a safety/privacy mechanism by not sending any data to the cloud in the first place, which ensures that nobody can get this data, since it doesn't exist in the first place.

**Comment by TehTurk** [comment]
Understandable thank you. 

I get that, but I'm talking less the hard underlying technicalities and more how folks actively see, use, and interact with these systems and how they see it. Thanks for clearing it up at least. I'll make a new ticket shortly.

**Comment by Aerizeon** [comment]
@Khosumi Absolutely - it wouldn't be an intuitive configuration for most people
@Frooxius For our use cases, that level of security isn't required. Someone joining directly into one of the worlds wouldn't cause any issues, its just preferred that they pass through the "hub" world first

**Comment by Frooxius** [comment]
@TehTurk Yes, that's where my concern actually lies. If people who do not look into technical details see "Private" in the description, they might take wrong assumptions about its security and level of privacy and misuse the feature.

This mechanism won't guarantee privacy, so that shouldn't be used as part of the wording at all to avoid giving people the wrong idea.

**Comment by Aerizeon** [comment]
@Frooxius perhaps "Unlisted public session" or something along those lines?

**Comment by TehTurk** [comment]
Understood! I was gonna ask if we could somehow rename some of the session settings in a way to reflect that maybe? But that might be better for another issue 
Running idea of Private as "Invite Only" and Hidden as "Secure/Hidden" so folks can get the memo easier.

**Comment by Aerizeon** [comment]
Honestly, I think for the scenarios it's going to be used in, it's not explicitly necessary to expose it in the client UI - It would work just fine as a headless configuration option, since that's generally how these types of worlds would be setup.

**Comment by Frooxius** [comment]
I wouldn't put "Secure/Hidden" in there either. If you get direct link to it, you can still access the session, it doesn't add extra security. For that "Private" should really be used for anything that needs to be really secure.

Hidden already excludes some of the security mechanisms, so you can get people you don't want joining. It's just that the proposed mode would be even less so secure.

**Comment by TehTurk** [comment]
Hmm I see I just wanted the wording to be more clear and understanding to folks because people do wonder what each mean and why they are similar. Because I know folks currently see Hidden/Private as a the same kinda. But Technically they arent.

**Comment by Frooxius** [comment]
I understand that, but the proposed names would make it even more misleading. We don't want to consider people "Hidden" to be secure either, it's really Private / Invite only for anything secure. Hidden just means that no data gets sent to the cloud, meaning you can have session with content that would normally break our public guidelines.

**Comment by Aerizeon** [comment]
Would it be particularly difficult to implement a hub world system of some kind natively?

Neos having that as a native feature (where certain worlds are accessible only from the hub, and the hub can display information about users in those worlds) would negate the need for the specific feature we're requesting, however it seems like it'd be more of a complex/long term item.

**Comment by Aerizeon** [comment]
I feel like "Unlisted Public Session" is a fairly accurate brief description, although it may be difficult to translate.

**Comment by TehTurk** [comment]
@Frooxius Hmm I see thanks again still  I'll think on it more.
