### ISSUE TITLE
Focused Session Info Source

### ISSUE THREAD

**Issue by LeDrascol** [Neos-Metaverse/NeosPublic#2498]
## Is your feature request related to a problem? Please describe.
Currently, it is difficult to gather information related to a session such as user count, access level, is headless host, and other common world data. The component SessionInfoSource provides all these things, but is restricted to listed headless sessions with custom IDs.

## Relevant issues
#1523 - For logix based alternatives

## Describe the solution you'd like
A component equivalent to SessionInfoSource that provides data for the current session.

An example of this is the component NeosVersion, which provides convenient detailed information about the session's version.

## Describe alternatives you've considered
Use a large amount of logix and updating relays.

## Additional context
N/A

**Comment by Frooxius** [comment]
What makes you say that SessionInfoSource is restricted to listed headless sessions with custom ID's? There's no such restriction in place, you can place dynamic session ID there as well and it should work.

One thing I can add is "SessionID" to FocusedWorldStatus, which you can then feed into SessionInfoSource and get the info for the focused session.

**Comment by LeDrascol** [comment]
> 
> 
> What makes you say that SessionInfoSource is restricted to listed headless sessions with custom ID's?

Please pardon my potential ignorance on this matter.

In all attempts to use the component, it has only been successful when using a headless with a custom session ID. This is implied to be the intended behavior in update **2020.7.31.1099** where it is listed as a companion feature to "custom persistent SessionIDs".

Attempts were made to use this component with multiple sessions - headless and user hosted - using the format provided in the **2020.7.31.1099** update notes. None have been successful.


> 
> 
> One thing I can add is "SessionID" to FocusedWorldStatus, which you can then feed into SessionInfoSource and get the info for the focused session.

Unfortunately, as FocusedWorldStatus cannot be used outside a facet, it would not help this situation. The goal of this feature request is to improve the accessibility of component-based setups used entirely in-session.

A possible alternative is a "use current session" option for SessionInfoSource which will automatically insert the current session's ID.

**Comment by Frooxius** [comment]
Added more info to FocusedWorldStatus in 2021.6.18.4 including SessionId. SessionInfoSource will now also show session info for private/hidden sessions if they're hosted/opened locally, so that should fix up the issues!
