### ISSUE TITLE
Document allowed characters for dynvars, dyn impulses

### ISSUE THREAD

**Issue by RobertBaruch** [Neos-Metaverse/NeosPublic#2500]
## Where have you searched for this information before making this issue?
The wiki

## Which part of the system do you need information on?
LogiX, dynamic variables, dynamic impulses

## What information do you need to know?
What are the allowed characters in:
* a dynamic variable name
* a dynamic variable space name
* a dynamic impulse name

## Do you plan to format and contribute the provided information to Wiki?
No, because I don't know what the allowable character set is.

## Additional background
I've sometimes shot myself in the foot by adding things like hyphens to names, and then had to debug when this didn't work. For example, attempting to read a dynamic variable name "xxx-E" will not find it, even though that is the name of the dynamic variable. However, "xxx_E" will work if that is the name. Thus, clearly "-" is not in the set of allowable characters.

I have to wonder if the unspoken assumption is that the restriction on names is that of [C# variables](https://www.tutorialsteacher.com/csharp/csharp-variable). If that is the case, this should be clearly documented.

**Comment by ProbablePrime** [comment]
Hey @RobertBaruch, Thanks for your request. Here's some info from patch notes and discord.

Froox talks in the Patch Notes about the standard variable Spaces:
World Roots have "World", User roots have "User" - https://discord.com/channels/402159838827905024/469131434628612116/756105022235738172
Userspace(Your dash and other private UI) has "World" - https://discord.com/channels/402159838827905024/469131434628612116/756722790031294565
"You cannot use punctuation and symbols in the variable or space name except for ., _ and   (space)" - https://discord.com/channels/402159838827905024/469131434628612116/756105014337994763

I can add these to the wiki for you soon. Does this answer your question?

**Comment by RobertBaruch** [comment]
Yeah, this is pretty good info! Thanks!

**Comment by ProbablePrime** [comment]
I've edited the article here: https://wiki.neos.com/Dynamic_Variables#Naming_Restrictions

To include this information more clearly. 

The rest of the article does need more tidy ups but this should help you.
