### ISSUE TITLE
Add WriteBack support to PlaybackPositionDriver

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#2506]
## Is your tweak request related to a problem? Please describe.
It would be nice to be able to connect `PlaybackPositionDriver` directly to a Slider, and control a video/audio playback position directly via WriteBack

## Describe what would you like tweaked
Add WriteBack support to the `PlaybackPositionDriver` component, so that Slider changes will cause the target video's playback position to change - Similar to how the stock NeosUI Video player functions.

## Describe alternatives you've considered
* Slider (or driven RectTransform for UIX) for a visual effect, and a separate button to be used with `ButtonPlaybackSeeker`

* Using LogiX to drive playback from Slider Position, and using LogiX to handle a separate visual effect

**Comment by Frooxius** [comment]
Added in 2021.6.20.36, hope it serves well!
