### ISSUE TITLE
No way to create a LogiX Cast from an interface card of a Slot to IWorldElement

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2512]
## Describe the bug
When trying to connect a Slot interface card to an Allocating User node's input, I wasn't able to directly pull the wire with a cast.

## To Reproduce
1. Get any slot (I created a box)
2. Inspect, pull out the slot's interface with the LogiX tip
3. Spawn an Allocating User node
4. Try to connect the slot card's header (Slot) to the Allocating User's IWorldElement input (see screenshots below)

## Expected behavior
A wire is created with a Cast Slot->IWorldElement

## Screenshots / Video
I had to spawn an extra node with a Slot-type output
![image](https://user-images.githubusercontent.com/675104/122674377-8b4d2b00-d1dd-11eb-9c93-1999a141dab8.png)
To do exactly what I was trying to do - connect the wire
![image](https://user-images.githubusercontent.com/675104/122674404-b20b6180-d1dd-11eb-88af-3ce22dcdd763.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.6.20.53
 - Neos Platform: Any
 - Link to reproduction World/Item: 
 - Regression: No

## Additional context
https://discord.com/channels/402159838827905024/501866888964341790/856147310542716938

## Reporters:
Shadow Panther#5154

**Comment by chemicalcrux** [comment]
Some related issues: #1567 #2051
