### ISSUE TITLE
Show if a user is silenced or not with "users" command (Headless client)

### ISSUE THREAD

**Issue by glitchfur** [Neos-Metaverse/NeosPublic#2517]
## Is your tweak request related to a problem? Please describe.
There is currently not a way to see which users in a session are silenced or not from the headless client console.

## Describe what would you like tweaked
Please add a column to the `users` command that shows if each user in the focused session is silenced or not with a `True` or `False`.

## Describe alternatives you've considered
I do not have any alternative solutions.

## Additional context
N/A

**Comment by Frooxius** [comment]
Added in 2021.7.1.437!
