### ISSUE TITLE
 Joint/Slider DontDrive defaults True

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2524]
## Is your tweak request related to a problem? Please describe.
This checkbox avoids host-dependency issues related to the drive release mechanism.
And I think these issue also related: #1270 #2185 

## Describe what would you like tweaked
in Slider/Joint component updates by host normally, but this will some issue in headless.
and this component also found in avatar creator, so some newcomers confusing for this issue.

so i think if this checkbox turns on will solve this problem.

## Describe alternatives you've considered
"DontDrive" turns on as Slider/Joint component uses, but little hard for newcomers.

## Additional context
N/A

**Comment by kazu0617** [comment]
@H3BO3 , you got the title changed, I didn't notice! Thank you very much.

**Comment by H3BO3** [comment]
just realized it was still a bit redundant, fixed it!

**Comment by shiftyscales** [comment]
I don't think this should be implemented just to work around the issue. What needs to be done is to have the underyling issue itself addressed, and there are already topics open for them.

Are there any reasons you have thought of for making this tweak outside of working around the buggy behavior?

**Comment by kazu0617** [comment]
Please see #2185 re-produce 3.
> 3. Set DontDrive to True (I always toggle this on because I want to avoid host-dependency issues related to the drive release mechanism

And I run Headless for tutorial, that world also include how to setup avatars.
But if Don't drive defaults off, these one is so buggy.

**Comment by shiftyscales** [comment]
I understand the reasons for why you are making this request, @kazu0617 - I was wondering if there were any *other* reasons for why you were making the request past those already listed.

**Comment by shiftyscales** [comment]
The proper solution for this is #1270 which will implicitly fix this, and other issues. Marking this as a duplicate. I will see if this issue can be considered more heavily for prioritization.
