### ISSUE TITLE
Seated Mode to be kept in Settings

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2527]
## Describe what would you like tweaked
Currently, Seated Mode is initialized to False at startup, and then you can use Seated Mode by manually setting it to True if necessary.
However, some people use Seated Mode on a regular basis (myself included), and those people often forget to turn Seated Mode on and find that it is broken.
For this reason, I would like to see the Seated Mode setting kept in Settings, or a Bool setting item such as "Seated Mode Defaults true" added, so that if it is true, Seated Mode is automatically turned on at startup.

> 現在、Seated Modeは起動時にFalseで初期化され、その後必要があれば手動でTrueにすることでSeated Modeを使用することができます。
> しかし、人によっては普段からSeated Modeを使用している場合があり（自分もそうです）、そういった人の場合、よくSeated Modeをオンにし忘れて崩れていることに気づくことがあります。
> そのため、Seated Modeの設定をSettingsで保持しておくか、あるいは「Seated Mode Defaults true」といったBoolの設定項目を追加し、もしTrueの場合は起動時に自動でSeated Modeをオンにするようにしてほしいです。

## Describe alternatives you've considered
I have to turn it back on every time I boot up. I often forget.
> 起動のたびにOnにし直す。よく忘れます。

**Comment by shiftyscales** [comment]
Thanks for the suggestion. This is a duplicate of #939.
