### ISSUE TITLE
Tweak email recovery code message to eliminate confusion/invalid entries of the code

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2528]
## Is your tweak request related to a problem? Please describe.
A couple of users have reported to me that the recovery code they were given isn't working. On feedback from 🅱um🅱le# 0124 in Discord, I had learned that the recovery code has a trailing period after it that users can mistake for one of the characters when they copy and paste it into Neos.

## Describe what would you like tweaked
Remove the trailing period from the end of the recovery code as its inclusion can lead to invalid entries of the code when a user copies and pastes the line.

## Describe alternatives you've considered
-

## Additional context
As noted, this has come up at least a couple of times now that I am aware of now that I know what the issue is.

**Comment by Frooxius** [comment]
Made changes in 2021.7.1.437. Also made the recovery shorter to make it easier to work with, but it only lasts 15 minutes (after that you get a new recovery code).
