### ISSUE TITLE
Setting AlphaHandling mode on PBS Displace *the wrong way* does something... permanently bad to the material.

### ISSUE THREAD

**Issue by RobertBaruch** [Neos-Metaverse/NeosPublic#2530]
## Describe the bug
I started with an existing, working PBS Displace Metallic material. I created a new PBS Displace Metallic material, copied the textures, and used the right-arrow on AlphaHandling mode to set from Opaque to Alpha Clip. I set the level to 0.5, and everything looked fine.

However, when I did the same thing, but used the *left-arrow* on AlphaHandling mode to set from Opaque, through Alpha Blend, to Alpha Clip, the material turned black, "Waiting to Apply" was true, and never applied.

## Relevant issues
No

## To Reproduce

1. Start with an existing PBS Displace Metallic material that has Alpha Clip on it.
2. Create a new PBS Displace Metallic material.
3. Copy the Albedo and Normal textures from the original material into the new one.
4. Set the AlphaHandling mode to Alpha Clip, but use the *left-arrow* to do it.

## Expected behavior
Once Alpha Clip is set, Alpha Blend should stop trying to apply itself, since it seems to hang.

## Log Files
[DESKTOP-CQBEQLG - 2021.6.23.11 - 2021-06-25 12_35_53.log](https://github.com/Neos-Metaverse/NeosPublic/files/6719002/DESKTOP-CQBEQLG.-.2021.6.23.11.-.2021-06-25.12_35_53.log)

## Screenshots / Video
See [video](https://www.youtube.com/watch?v=FgP11aRiUpM).

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.6.23.11
 - Neos Platform: Windows
 - Link to reproduction World/Item: 
 - Regression: I think PBS Display Metallic is new?

## Reporters:
Xekri

**Comment by Frooxius** [comment]
There was an issue with the asset variant server due to outage, so it looks like it took a while before the variant was computed. Are yous till experiencing this problem? I've tested it on my end and it should work now.

**Comment by RobertBaruch** [comment]
Thanks, I confirm it is working now.
