### ISSUE TITLE
Explanation for a bit of the PBS Displace Shader/Material

### ISSUE THREAD

**Issue by RobertBaruch** [Neos-Metaverse/NeosPublic#2531]
## Where have you searched for this information before making this issue?
Youtube (Froox's [video](https://www.youtube.com/watch?v=VNQr_k0H0MY))

## Which part of the system do you need information on?
PBS Displace Specular shader

## What information do you need to know?
How does the vertex displacement operate? Specifically, we have the following inputs:
- A texture map. This seems like it has a size (square) and an intensity (0-1?)
- Magnitude. I think this is just a multiplier for the intensity.
- Bias. I think this is added to the intensity (but before or after the magnitude is applied?)
- Map scale and offset.

The question I have is, how are the vertices of the mesh modified, given a fixed magnitude, bias, xy scale, and xy offset.

Froox's demo shows the leaves of the trees kind of breathing in and out, or curling in and out. My model that I imported from sketchfab seems to have its leaf meshes broken into two and mirrored, so that any vertex displacement results in the leaves pulling themselves apart from the middle. Not the effect I'd go for.

So, I'd like to know what exactly the displacement is doing to the mesh, mathematically.

I'm pretty sure the world space vertex offset affects the offset based on the global world space, rather than locally. Again, understanding what the formula is would help.

Finally, UV map displacement. Froox didn't use this in his demo, presumably because the UV map doesn't need to be messed with, but it would be great to understand how the UV map is distorted.

## Do you plan to format and contribute the provided information to Wiki?
If I could just get a description, I could document it on the wiki.

**Comment by Frooxius** [comment]
Displacement is just moving the vertices along their normal. For this effect to produce results you want, you need to prepare your mesh accordingly - UV map it properly and make sure that geometry is continuous or that normals of discontinuous geometry point in the same direction so it doesn't get pulled apart.

The texture doesn't need to be square, almost no texture in Neos has this requirement, except in some rare cases like light cookies.

Displacement along the normal is calculated pretty much as follows:
`Vertex.Position += Vertex.Normal * (TextureIntensity * Magnitude + Bias)`

Map Scale and Offset work the same as they do for all other materials - just apply offset and scaling to the texture relative to the UV.

**Comment by RobertBaruch** [comment]
How about the world scale offset? I see that it's a color texture, so presumably it's a map of G(x,z) -> (r,g,b) where G(x,z) is the global position of the material's slot in x,z only (so the height doesn't matter?). What does (r,g,b) affect in the formula?

**Comment by RobertBaruch** [comment]
https://wiki.neos.com/PBS_DisplaceSpecular#Usage

**Comment by Frooxius** [comment]
The WorldSpaceVertexOffsetMap is used to compute an offset when sampling the vertex displacement texture based on the position of the object/vertex in the world along the XZ plane. The R channel produces X offset and G channel Y offset.

Instead of using the mesh UV's, the XZ position of the object/vertex is used to sample this texture. TextureScale and Offset work the same for this as well. The sampled value is then multiplied with the magnitude and added as offset when sampling VertexDisplaceMap.

**Comment by RobertBaruch** [comment]
Got it, thanks. I hope the wiki reflects all this accurately!
