### ISSUE TITLE
In desktop mode, undoing a grabbed item that was deleted by "destroy selected" parents item to holder.

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#2537]
## Describe the bug
If an item is deleted using the developer tooltip's "Destroy Selected" while holding the item and then the delete is undone, the item will be parented to the user's holder, and must be deleted manually.

## Relevant issues
None

## To Reproduce
1. Create new cube (3D Model > Box)
2. Select cube with developer tooltip
3. Grab cube and select "Destroy Selected"
4. Confirm destroy
5. Press CTRL+Z to undo the destroy operation
6. Item will be parented to holder, and must be destroyed or reparented manually.

## Expected behavior
Object should return to previous parent, similar to how regular grab destroy functions.

## Log Files
No relevant entries in log file

## Screenshots / Video
[Video](http://files.aerizeon.net/sharex/2021/2021-06-27_20-07-zWZEg6BoTS.mp4)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.6.23.11
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: No

## Reporters:
Epsilion

**Comment by Frooxius** [comment]
This is correct behavior. 

"Destroy Selected" is more raw destruction that's independent of grabbing (e.g. it can destroy things that aren't even grabbable and that can be under your avatar). Undoing it will restore the item to its state when it was destroyed, which is parented under you. This behavior happens in VR as well, not just in Desktop.

When using "Destroy Selected", simply don't grab the item when destroying it, it's not necessary.

**Comment by Aerizeon** [comment]
It is still unexpected that it will return to the user's holder slot, and isn't able to be removed.
