### ISSUE TITLE
Spawn() in RandomObjectSpawner seems not Action

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2538]
## Describe the bug
from some builds ago, Spawn() in RandomObjectSpawner can't pull from Inspector, and it'll break some Spawn System.

## Relevant issues
I searched "RandomObjectSpawner" but can't find it.

## To Reproduce
1. Add RandomObjectSpawner from inspector.
2. try to pull Spawn() action.

## Expected behavior
this action can pull from Inspector, i think.

## Screenshots / Video
https://twitter.com/y_esnya/status/1409019767873175552?s=20

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.6.23.11
 - Neos Platform: Windows (maybe any)
 - Regression: idk

## Reporters:
kazu ( kazu0617#7215 )/ esnya ( esnya#5247 )

**Comment by Frooxius** [comment]
Fixed in 2021.7.1.437, thank you for the report!
