### ISSUE TITLE
Option for TextEditorParser components to accept empty string

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2539]
## Is your tweak request related to a problem? Please describe.
TextEditorParsers (IntTextEditorParser, FloatTextEditorParser...) seem useful, though so far, every time I wanted to use them, I felt the need for them to accept and empty field in addition to the specified range, serving as a sort of 'none' or 'any'.
This currently doesn't seem to be possible.

## Describe what would you like tweaked
Add a boolean to IntTextEditorParser and FloatTextEditorParser that specified whether or not they accept an empty field.

## Describe alternatives you've considered
1. Not using them. While this would be ok-ish for my cases, the validation would still need to happen elsewhere in the system, adding more complexity.
2. Making a custom system that basically recreates this functionality with the added acceptance of empty

## Additional context
My specific use-cases so far are numeric inputs in a search query (empty would mean 'match anything') and Sudoku, where empty would be the default before a value is filled in.

**Comment by Frooxius** [comment]
What exactly do you mean by this? What would accepting empty field involve?

They represent int or float datatypes, which don't have concept of "none", so empty string won't translate to any valid number. We could make it reset to some "default" value, but that's potentially a bit odd.

**Comment by shadowpanther** [comment]
I can only imagine adding nullable float and int types and making editors use them.

**Comment by Psychpsyo** [comment]
Having versions that resolve to nullables would be a clean solution. For the other ones, empty string could turn into NaN (for floats) or into either a preset or definable default, like 0. Being able to define a default value would give more freedom though, like setting it to -1 on a field that accepts values 0-something.
