### ISSUE TITLE
Inspector Style Inconsistent Between Position,Rotation,Scale

### ISSUE THREAD

**Issue by junebun** [Neos-Metaverse/NeosPublic#2550]
In the Inspector UI, Rotation follows a completely different style than Position and Scale.

![image](https://user-images.githubusercontent.com/68768136/123711615-bf0ffc80-d83e-11eb-9cef-7ecaf4e0c6cb.png)

When creating the Rotation field for the inspector UI, an extra horizontal layout is spawned because **FrooxEngine.QuaternionMemberEditor** creates its own.

Position and Scale use **FrooxEngine.PrimitiveMemberEditor** which has an inconsistent style with Rotation for several reasons:

- Labels are centered instead of aligned left like all other displays
- Labels and Input fields have no min size, while others have a min size of 24 (excluding x for some reason which has no min size)
- Input fields have a flexible size of 100 while others have a min size of 10

Can be fixed by modifying these behaviors in the BuildUI method on either one or both to conform.

Example of **FrooxEngine.QuaternionMemberEditor** conforming to the existing layout:

![image](https://user-images.githubusercontent.com/68768136/123711994-668d2f00-d83f-11eb-8530-517af42740a8.png)

@junebun on Github
June#1991 ("Dukington" in neosvr server) on Discord
Dukington on Neos

**Comment by ukilop** [comment]
this is just quaternions, and this happens _everwhere_ id love to see this unified

**Comment by Earthmark** [comment]
Personally I prefer it different, so you know you're dealing with a quaternion instead of a vector.

**Comment by junebun** [comment]
Nothing about the styling indicates that it is a quaternion aside from knowing about this bug with them. The text inputs could be styled, or colored to indicate type, but not setting up min sizes and inconsistent text alignment are not a good indicator of type.

**Comment by Hayden-da-Serg** [comment]
I believe this is actually a regression, I don't remember when it happened but the elements used to be in line, it may be when the hints were added.
The Quaternion inputs used to be aligned with everything else before *something* changed.

**Comment by shiftyscales** [comment]
I can't find the relevant Froox quote on it at the moment- but this is something that came up well over a year ago I believe.

Basically- there isn't an easy way to deal with this now as all of the UI is generated from code.

This won't be prioritized/worked on for the current iteration of the inspector UI.
