### ISSUE TITLE
Haptics Manager sets up feet haptics to only default to the left side.

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#2553]
## Describe the bug
It seems the haptic manager for the legs only defaults to the left side.

## To Reproduce
1. Start up Neos with Haptic Setup
2. Look at the Leg Manager, both left and right leg will default to left
3. If not tweaked, people will notice their right foot haptics not responding.

## Expected behavior
Both legs should be working for their respective side.

## Bug information (please complete the following information):
- Always happens

## Reporters:
Turk, AlexVR, RueShejn

**Comment by Frooxius** [comment]
Fixed in 2021.7.1.437, thanks for report!
