### ISSUE TITLE
ContextMenuSubmenu can traverse into user root but not start in a user root

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2556]
## Is your tweak request related to a problem? Please describe.
A ContextMenuSubmenu with SearchWholeHierarchy won't show any items when it's ItemsRoot is inside another user's user root but is fine traversing into the user root if the ItemsRoot is on a slot above it.

## Describe what would you like tweaked
Make the ContextMenuSubmenu not traverse into user roots anymore when searching the hierarchy.

## Describe alternatives you've considered
1, Keeping this inconsistency. (Can't see why this would be desirable.)
2. Making it work when starting in another user's user root. (Seems to not be the desirable solution, judging by the reactions of other users when pointing this out.)

**Comment by Frooxius** [comment]
Fixed in 2021.7.1.437, all items under another user should now be properly ignored. Thanks!
