### ISSUE TITLE
Give Inspectors, NodeMenu, Full Body Calibrator, Legacy Inventory and Avatar Creator Object Roots

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2557]
## Is your tweak request related to a problem? Please describe.
When doing things that search for Object Roots, things like the mentioned in the title don't come with Object Roots. Raycasting them when finding out what object it is usually just gives you "Content" because thats the collider it hit.

## Describe what would you like tweaked
I would like for the mentioned above to have Object Roots to make finding the roots much easier to find. I think this will be a very easy patch.

## Describe alternatives you've considered
Not sure what other alternatives there could be. Rather straight forward.

## Additional context
I totally forgot most of these never came with an Object Roots for what ever reason. I was creating a moderation tool that tries to get the object root, but always only showed "Content"

**Comment by AshtonSparx** [comment]
I forgot to add, that video players spawned in from links, also don't come with object roots.

**Comment by Frooxius** [comment]
Added Object Roots to those and bunch of others in 2021.7.1.437!
