### ISSUE TITLE
Request: Add slight arm and leg movement in desktop mode

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2561]
## Is your feature request related to a problem? Please describe.
When a user in desktop mode is not moving their arms and legs are fully static, and they feel more lifeless than desktop mode in other platforms. 

## Relevant issues
Desktop mode in general, oddly I can't find any existing issues besides that one. I figured this would be reported already, if it has been then this is likely a duplicate.

## Describe the solution you'd like
Some common system for arm and feet random movement, kind of like how the the eye driver improves life like nature of an avatar, but for limbs.

## Describe alternatives you've considered
Hand integrating animations or movement equations into avatars, this is being discounted as it would not resolve the issue globally, and while it would be possible to fix this for myself it would not resolve the issue for others (and desktop mode is becoming quite common!)

## Additional context
This is an open ended request, but I can attach examples of this kind of movement from other platforms if requested.

Some take this quite far to the point it would be possibly problematic in neos, such as animations where people adjust their non-existent headsets.

**Comment by Frooxius** [comment]
This is already planned, we have a card for it on our roadmap, along with other things planned for the desktop mode: https://github.com/Neos-Metaverse/NeosPublic/projects/3#card-61033046

Currently not prioritized though, as we put more desktop features on hold in favor for BEPUv2 and other things.

**Comment by Earthmark** [comment]
Sweet, I'll close this as a card exists then!

**Comment by epicEaston197** [comment]
I would love for this to be a toggle
