### ISSUE TITLE
Filter for "Random Worlds" In the World Browser

### ISSUE THREAD

**Issue by PointerOffset** [Neos-Metaverse/NeosPublic#2566]
## Is your feature request related to a problem? Please describe.
The current world browser does a good job raising fresh worlds, featured worlds, and places that are currently active and popular. However it can be very difficult to discover old worlds or more obscure worlds as the current filter selections don't appear to offer full results. Not to mention digging through many pages can be a chore anyway.

Because of this, older worlds or worlds that simply don't get lucky enough to get attention when they are recently published can fall by the wayside and remain undiscovered without a lucky search result. Worlds that may be considered more historically interesting or worlds that might simply be curious, obscure discoveries can also go almost entirely unnoticed. The current rate of new world publishing doesn't make this a huge problem, as it takes a while for results to get entirely pushed out of view. Over time this will only get worse though.

## Describe the solution you'd like
I'd like to see a filter added to the World Browser that includes a random selection of worlds. To address the problem in particular, it may make sense to filter for a random selection of worlds that have not been visited within the past few months.

In terms of actually populating the listings, I can see this working a couple of different ways.

1. Results are populated the first time a user opens the Random filter and remain static through their current session in Neos. This way a user can look at the random selection being presented, and if they find multiple options interesting they can feel secure knowing their options won't change until they restart Neos.

2. Results are populated every time a user switches to the Random filter. This means a user could lose track of options they may have been looking at, but makes it trivial to get a new set of results they don't find anything of interest in their current results.

3. Results are populated the first time a user signs into Neos for a 24 hour period (or other time period) and remain static. Even through restarting Neos and beginning a new session within that period. The nature of finding random worlds may mean running into something unstable and causing a crash. This would prevent users from accidentally losing other results they might've found interesting but didn't get to visit before crashing and having to generate new results.

4. Results are generated in the cloud periodically and every user receives the same random results until another set of results is generated. There may be a Neos API endpoint that generates a random seed value which varies every few hours. Everyone would get the same seed and, therefore, the same results. That's just one idea, but the point being there could be an endpoint in the Neos API that the Random Worlds filter can call to for results. If there are concerns with many users making expensive filter requests that are all different, this may be a solution. This would also mean that all users can observe the same results, potentially resulting in interesting community engagements if a particularly interesting set of results show up and everyone can easily observe them and discuss/explore them together.

## Describe alternatives you've considered
As I understand it, there are ways to get a random published world selection. However I don't think they'd be considered reliable so far as I know. Users could try searching worlds with off-the-cuff key worlds to try and find something interesting too, but that solution is imperfect. Not all relevant worlds may show up depending on keywords or descriptions. It's just a matter of luck. It's also not as fun or easy for those who just want to roll the dice and see what they come across if they have to come up with a search term and don't have anything in mind.

## Additional context
There is definitely a lot of fun to be had in Neos when it comes to world discovery. Sometimes you can come across things that are completely surprising and impressive. Sometimes you can find things that are half-baked and unfinished. Either way, they can often be inspiring or just a fun adventure. I also think this would give unnoticed worlds a second chance at discovery or even give worlds that had their day in the lime light a second chance to shine years down the road.

**Comment by GearBell** [comment]
I agree we need a way to have a random world selector. Either a tab featuring Random Worlds between 50-100 randomly picked worlds that the list scrambles hourly so theres no need for repeats or perhaps even a button in the dashboard Worlds tab that will summon a singular Random World orb, cause thats all you need to work with per world hop.

**Comment by shadowpanther** [comment]
Remember that quite a large number of published worlds would probably be just gridspaces with a couple of random objects that deserve being lost to time.

**Comment by GearBell** [comment]
doesnt matter - thats a chance the Random World hopping adventures will take. It comes with the territory.

**Comment by Yugioh-web** [comment]
We need this!

**Comment by Frooxius** [comment]
Would it be a big problem is the randomized order is same for every user? It could change every hour or so (maybe more frequently even), but if two users look at it at the same time, they'll get same shuffled order.

That would probably be the most way to handle this efficiently on our end, as we could just keep generating random shuffle order, that could be used to sort the results. All the other filters and search properties would still be able to apply as well.

**Comment by shadowpanther** [comment]
If I understand correctly, that would reshuffle the whole list of published worlds every hour, and then you could browse through that list in the same manner as with the existing published list?
For example, a user would be able to switch to that random order and then filter by "sea" or "space" tag?

**Comment by GearBell** [comment]
i dont think anyone minds if its the same order. coordinating the next world would be useful there. But can the random world feature be in an easy to find place please? The worlds tabs settings in the dashboard are confusing enough as it is.

**Comment by Frooxius** [comment]
Yeah pretty much. We'd just add another field to the records that'd just be a random number, that would get periodically re-assigned on the cloud.

We'd put this as another category in the Worlds tab, something like "Shuffle". It would also be a sorting option in the advanced settings.

**Comment by GearBell** [comment]
If it makes it easier, would a new tab called Random Worlds help with showing only about 50 or 100 worlds and reshuffling that? I dont know how UI works so i dont know if as a filter, reshuffling the entirety of Published Worlds would make neos more chunky....

**Comment by GearBell** [comment]
Amazing! This will let people really open up neos!

**Comment by shadowpanther** [comment]
> If it makes it easier, would a new tab called Random Worlds help with showing only about 50 or 100 worlds and reshuffling that? I dont know how UI works so i dont know if as a filter, reshuffling the entirety of Published Worlds would make neos more chunky....

What Froox describes is having another button in the Worlds tab (alongside Active, Published, Games, Art, etc.) that would show you random worlds. Internally all those buttons are just filter presets for the list itself to use.
Advanced button gives you full control over the filter options, there would be the additional option to use the random sort order.

**Comment by Frooxius** [comment]
The easiest for us is the way I described above. It fits well with the existing systems and doesn't make anything more chunky. The only caveat is that everyone will have the same random order at the time, rather than the order being unique for each user.

**Comment by GearBell** [comment]
That sounds alright! We'll just be able to coordinate worlds!

**Comment by PointerOffset** [comment]
I agree with GearBell. Having the random selection be the same for all users may actually be ideal. Everyone can look at the same list and discuss what options are available at a given time. I imagine it like going to a theater with a group of friends without having a specific movie in mind. You can look at the listings and figure out what seems most interesting together.

**Comment by Frooxius** [comment]
Added in 2021.8.13.612! There's now a "Shuffle" category in the World browser. If you want to go a bit more advanced, you can use the "Random" order in the advanced setting for anything else.
