### ISSUE TITLE
New Logix Node: Local Boolean Latch

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2568]
## Is your feature request related to a problem? Please describe.
There's been many times I wanted to have something toggle locally for a user with logix, but haven't really been able to find an efficient method that wasn't "hackie" or un-optimized and/or un-reliable method

## Relevant issues
None that I could find with a quick search

## Describe the solution you'd like
For a fully localized Boolean Latch logix node

## Describe alternatives you've considered
I have no idea..

## Additional context
A use case that I know drove a member mad was regarding the cat band. Wanting to alternate the cat's hand on what hit the drum. With a normal boolean latch, it pulsed for every user causing the hand to spaz out every time it alternated hands based on what ever condition they had to switch the hands.

**Comment by H3BO3** [comment]
This will be handled with local writes and other various logix localness integrations

**Comment by shiftyscales** [comment]
Yes, as noted above, there is a project card for this. https://github.com/Neos-Metaverse/NeosPublic/projects/15#card-61393175

**Comment by AshtonSparx** [comment]
Since there is a project card for this, I shall close this as the request is not required. If it should be open, please feel free to re-open this! Thanks guys 👍🏻
