### ISSUE TITLE
Unable to localize certain texts on the session information window

### ISSUE THREAD

**Issue by InnocentThief** [Neos-Metaverse/NeosPublic#2579]
## Describe the bug
The values for  "World.Detail.Uptime" and "World.Detail.PublishDate" and "World.Detail.ModifyDate" can not be localized.

## To Reproduce
1. Open up the Session Information Window
2. The value for "World.Detail.Uptime" shows "1 minutes 52 seconds"
2. The value for "World.Detail.PublishDate" shows "537 days ago"
3. The value for "World.Detail.ModifyDate" shows "21 days ago"

## Expected behavior
The value should be localizable (eg. {days} day(s) ago) => "vor {2} Tagen"

## Screenshots / Video
![image](https://user-images.githubusercontent.com/65510170/124357300-1c2ef800-dc1b-11eb-8751-090dcdb25419.png)

## Reporters:
InnocentThief#5548

**Comment by shadowpanther** [comment]
I think this issue is better suited for https://github.com/Neos-Metaverse/NeosLocale

**Comment by InnocentThief** [comment]
I'll move them all over to NeosLocale. Thx

**Comment by InnocentThief** [comment]
Moved over to NeosLocale
