### ISSUE TITLE
Any information of Assets/StaticSavedObjectProvider

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2582]
## Where have you searched for this information before making this issue?
I checked [NeosWiki](https://wiki.neos.com), [NeosUpdates](https://discord.com/channels/402159838827905024/469131434628612116) but nothing.

## Which part of the system do you need information on? / What information do you need to know?
Any information of `Assets/StaticSavedObjectProvider`. I think this is used for 7zbson loader but idk how to use it for.
so I want to use it in neos and if can, plz show how to use it.

## Do you plan to format and contribute the provided information to Wiki?
Yes. I'll create wiki page after this issue solved.

**Comment by kazu0617** [comment]
I would appreciate any information you can give me. If you have any questions, please feel free to contact me at any time, or if the information is something that cannot be published yet, such as Uncategorized, that would be sufficient. If so, I'll put that in the wiki and close the issue.

**Comment by Frooxius** [comment]
Unfortunately there's not a direct way to use it right now. The only usage is to pre-download some objects and their assets so they load faster, but I don't think we're actively using it even internally at this moment.

It's an old thing that has been added in the past, but I forget the exact reason.

**Comment by kazu0617** [comment]
Thanks for answering... So if I turn on Bool in PreGather and specify Uri, it will load the item once it enters the world, even if I don't have it spawned? (If so, I thought it could be used for something else.)

**Comment by shiftyscales** [comment]
@kazu0617 - as Frooxius noted, there's no way to use it right now.

**Comment by kazu0617** [comment]
> 
> 
> @kazu0617 - as Frooxius noted, there's no way to use it right now.

But @Frooxius Also says `The only usage is to pre-download some objects and their assets so they load faster.`

**Comment by kazu0617** [comment]
I'm going to close it now that I've gained some knowledge and have completed the wiki entry.
