### ISSUE TITLE
Additional Procedural Mesh Request

### ISSUE THREAD

**Issue by Mysticporo** [Neos-Metaverse/NeosPublic#2594]
Can we get additional procedural meshes in the Assets component such as:
Hollow Tube
Epsiloid Sphere/ "Egg Shape"
Half Sphere/Dome

**Comment by shadowpanther** [comment]
"Hollow tube" is a cylinder without caps, can already do that
Half sphere -> #2228

**Comment by GearBell** [comment]
We need tubes as in thickness control. Currently, we do not have that option.

**Comment by ukilop** [comment]
Hollow Tube -> #2230
Half Sphere/Dome -> #2228
