### ISSUE TITLE
Camera Dialog Twitch Panel Buttons don't work.

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#2599]
## Describe the bug
The header buttons on the Twitch Panel are now Grey and don't function when pressed.

## To Reproduce
1. Open your camera dialog from the home screen of the dash
2. Click on the twitch button to open the twitch dialog
3. Observe that the twitch panel buttons are now Grey and don't respond to clicks

## Expected behavior
That the Twitch Buttons work.

## Log Files
[ALFRED - 2021.7.6.1336 - 2021-07-07 00_58_51.log](https://github.com/Neos-Metaverse/NeosPublic/files/6775402/ALFRED.-.2021.7.6.1336.-.2021-07-07.00_58_51.log)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.7.6.1260
 - Neos Platform: Any

## Reporters:
LemonCement, Fuzzy, me.

**Comment by ProbablePrime** [comment]
Taking an initial poke at this one.

**Comment by TehTurk** [comment]
One thing I'd like to add/note. It doesn't seem like the Twitch Chat also likes to be a facet (unless the breaking ties it into the issue). Because my popout twitch chat, and a free facet seem to be linked in someway. I'll typically use this when having to monitor chat. Don't know if the info would help, but it's something to note.

**Comment by ProbablePrime** [comment]
Thanks for the info, That's unfortunately completely unrelated. Could you please open another GH issue for it.

**Comment by ProbablePrime** [comment]
Fix should be in the next build. That was fast!

**Comment by Frooxius** [comment]
Released in 2021.7.7.1419, thanks!
