### ISSUE TITLE
Additional QuickFormat Nodes

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#2600]
## Is your feature request related to a problem? Please describe.
The folder LogiX/String/Quick Format only has one node right now To Time String. This Node confusingly takes a Float (usually Input/T) and returns a Time String.

It would be good to have some additional quick formatting nodes to speed up displays. The Format node is great for custom displays but for newer users more Quick Formats would be good as the Format node is very confusing.

## Describe the solution you'd like
Additional Quick Formatting Nodes:
- Rename To Time String? Its unclear what it does with the current name
- Time to String:
	- Uses a default format string of Hours:Minutes
	- Has Boolean option for showing Seconds/Milliseconds
	- Has Boolean Option for being in 24 Hour Clock. When false it would add AM/PM
- Timespan to String:
	- Has boolean option for Showing Seconds/Milliseconds
- Date to String
## Describe alternatives you've considered
Better documentation of the format node?

## Additional context
Requested by Myself, I'm Erin and Epsilion.

**Comment by ProbablePrime** [comment]
![image](https://user-images.githubusercontent.com/8791132/124743080-35ad9980-ded2-11eb-8354-25f1b043a70d.png)

Some stuff I'm playing with.

**Comment by Frooxius** [comment]
Merged in 2021.7.21.127, thanks!
