### ISSUE TITLE
Spawning Public Folders & Streamer Camera pictures bypass No Spawn Permissions

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2603]
## Describe the bug
When you're a spectator, you can spawn public folders using the Envelop Button in your inventory & Streamer Cameras screenshot function also bypass No Spawn permission.

## Relevant issues
None That I could Find

## To Reproduce
1. Be put as spectator
2. Click on the envelop on a public folder, it should spawn
3. Open your stream camera, click on the Settings Cog, enable Spawn photo in the world
4. Take a picture

## Expected behavior
When you don't have spawning permissions, none of these should spawn the item in the world

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.7.6.1260
 - Neos Platform: Any
 - Link to reproduction World/Item: N/A
 - Regression: This has always worked as far as I know

## Reporters:
AshtonSparx#5050

**Comment by AshtonSparx** [comment]
> 
> 
> Can you verify: "Streamer Cameras screenshot function also bypass No Spawn permission"?
> 
> In: #934 Froox made some tweaks here and looking at the code I see the appropriate restrictions in place.
> 
> It does still spawn the photo, but it uses a system called "Local Slots" which I admit is the first time I've seen this or heard of it so I'm not sure how it works. At a guess its probably a slot that only you can see that is not synchronized.
> 
> Its a bit late, so I'm heading off but give this a try in a world with another user and your setup. Can they see the photo that is spawned?
> 
> I've fixed the other one in the same set of changes as #3134 though, that's under review :)

Just tried it and it's patched!

**Comment by Frooxius** [comment]
Merged in 2021.10.17.1326, thanks everyone!
