### ISSUE TITLE
Smooth Turn Exclusive Mode is not very exclusive

### ISSUE THREAD

**Issue by H3BO3** [Neos-Metaverse/NeosPublic#2614]
## Is your tweak request related to a problem? Please describe.
I and several other users have noticed that Smooth Turn Exclusive mode does not prevent forward/back movement while turning.

Currently it seems that if the joystick Y is past a certain threshold, smooth turning turning is prevented as the X value is suppressed - However, the inverse is not true. The joystick being pushed to the side so turning is engaged does not prevent Y motion from still applying if the joystick is slightly pushed up or down while turning. Even though it is usually slow it is still noticeable.

## Describe what would you like tweaked
Divide the joystick into 90-degree cardinal quadrants. If the joystick vector is within a respective quadrant for either smooth turning or forward/backward movement, the other action cannot apply.

## Describe alternatives you've considered
Unsure. I don't know the code that actually handles the vectors. Maybe use similar logic with an X axis threshold to suppress forward/backward movement when turning? Whatever will make smooth turn exclusive mode truly exclusive. When turning, you should not be able to move forward/backward at the same time, and the inverse should also be true.

## Additional context
https://discord.com/channels/402159838827905024/439422161657135106/835796677397970984

Kaptain Krunch#4672 requested an even more restrictive mode in which the right joystick does not move the user forward/backward at all, only the left, leaving the right joystick reserved for smooth turning. I am not sure how feasible this is, but perhaps the changes I'm suggesting would help with restricting unwanted inputs.

**Comment by Frooxius** [comment]
Fixed in 2021.7.9.1222, thanks!
