### ISSUE TITLE
Recurring Notifications in Contacts Menu

### ISSUE THREAD

**Issue by Lucaedr** [Neos-Metaverse/NeosPublic#2616]
## Describe the bug
In neos after a significant amount of spam from one user, the contact is now displaying 20 notifications on every login. This can be cleared by attempting to "read" the messages even though there is nothing new in it.

## Relevant issues
Didn't see any...

## To Reproduce
1. Find a partner
2. Have someone spam you with a huge amount of messages in a short period of time
3. can try reading them all but they all come in more quickly than what neos was able to comprehend.
4. Logout/login and each time you relog 20 notifications will be on the contacts.

## Expected behavior
Should not display any notifications as there is no new messages.
[A clear and concise description of what you expected to happen.]

## Log Files
The last time I had a new person do this was in September however another person by the name of KodeyTheNeko on Twitch was having the same exact issue.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/47595482/125141867-30c03400-e0e4-11eb-8baa-5b123942866c.png)
![image](https://user-images.githubusercontent.com/47595482/125141872-361d7e80-e0e4-11eb-956d-44a827e02ea6.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Current and all previous since October
 - Neos Platform: Known on Windows.
 - Link to reproduction World/Item: none
 - Regression: n/a

## Additional context
Like I mentioned, KodeyTheNeko is another user that has been experiencing this issue. 

## Reporters:
Lucaedr
KodeyTheNeko on Twitch (not sure about discord username)

**Comment by Sox-NeosVR** [comment]
I had this issue a while back, my fix for it was logging out of my account and logging into another account and then switching back to my main account.

This is not a proper solution but just a quick workaround.

**Comment by Frooxius** [comment]
I can't replicate this on my end, no matter what I try, the notifications get cleared up properly. Are there more conditions to this?

- There were significant changes to the messaging system recently, does the issue still occur as of right now?
- How much is "huge amount"? I tried with around 260 messages, but that wasn't sufficient
- Does this happen when you're offline while they send them or when you're both online and you receive them in realtime? I tried both, but neither reproduced the issue.

**Comment by Lucaedr** [comment]
Interesting Sox... I don't have a secondary account so I couldn't try this... I did log out previously and have had a full reinstall of windows since. 

But Also @Frooxius it took probably 500 messages to get to the point that it was sufficient and the user was using UIX spam in order to send enough fast enough. I don't know if it was the amount that allowed it to get to that point or if it was the volume and that it is much more difficult to do now. I'm not 100% sure whether it was offline or online that it actually caused the notifications to recur on every login as I believe he sent messages during both.

**Comment by Frooxius** [comment]
Ah I see, I think I know what it is now. There's a limit of 512 messages being read and the system won't split the requests up right now. I'll make fixes in the next build.

**Comment by Frooxius** [comment]
Should be good in 2021.7.11.1002, let me know if issues persist!
