### ISSUE TITLE
Clarify Intended Behaviour of "Destroy Selected"

### ISSUE THREAD

**Issue by kawaiiamber** [Neos-Metaverse/NeosPublic#2621]
## Is your tweak request related to a problem? Please describe.
The current labels on the `Deselect All` and `Destroy Selected` seem to either not clearly indicate their intended behaviour or have unexpected behaviour. Currently - if you select an item, hit `Deselect All`, then `Destroy Selected`, it will destroy that item. Currently, it seems that `Delected All` just deletes the gizmos and doesn't actually write a Null reference to the current gizmo that's selected. I've heard on the discord that this is actually expected behaviour. This has caused confusion over the intended behaviour with me and some other new players. The closest issue I was able to find somewhat related is [#2266](https://github.com/Neos-Metaverse/NeosPublic/issues/2266).

## Describe what would you like tweaked
If this is indeed the expected behaviour, perhaps `Destroy Previous Selection` will better convey the intended behaviour in the sense that even if you deselect everything, it will still destroy the last thing you had selected. If this is not the intended behaviour, then write a reference of null to the currently selected gizmo in addition to destroying the visual gizmos upon hitting `Deselect All`.

**Comment by Frooxius** [comment]
It shouldn't destroy the item once you deselect it, this is a bug. Should be a simple fix though.

**Comment by Frooxius** [comment]
Fixed in 2021.7.11.1002, thanks!
