### ISSUE TITLE
I want to specify a thumbnail photo for a World

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#2622]
## Is your feature request related to a problem? Please describe.
we cannot have a thumbnail for a World the best that we can do is stand somewhere interesting

## Relevant issues
we cannot have a thumbnail for a World 

## Describe the solution you'd like
so what it would be like we would make a camera and then specify the camera as a thumbnail camera
on Save

## Describe alternatives you've considered
already described above

## Additional context
the camera could also be edited so it would take a photo on save or not

for example this is what the preview would look like ![unknown (1)](https://user-images.githubusercontent.com/76523692/125195874-b39cd800-e225-11eb-8f98-5774cc1eff33.png)

**Comment by Frooxius** [comment]
We already have issue for this here: https://github.com/Neos-Metaverse/NeosPublic/issues/1419

**Comment by epicEaston197** [comment]
oh sorry
