### ISSUE TITLE
Users set to invisible should still add to a session's user count

### ISSUE THREAD

**Issue by jonnyawsom3** [Neos-Metaverse/NeosPublic#2627]
## Is your tweak request related to a problem? Please describe.
I keep on trying to join worlds that say they have a slot free but then it tells me the session is full because people set to invisible aren't included in the user count

## Describe what would you like tweaked
Only have invisible users be excluded from the user list but still included in the user count

## Describe alternatives you've considered
I notice discord's rich presence correctly includes them (A session saying 15 out of 16 on Neos says 16 of 16 on Discord) so right now I'm using my friend's profile to tell when I can join, obviously not a great workaround if you don't have discord or a friend in the session

**Comment by shadowpanther** [comment]
Invisible users actually **do** add to the sessoon count. I often see session count showing one number of people, but when I count the names of the people in the session, I come up with a number less than that. And then I see the invisible person in the session preview.
The users **not** included in the session count are actually the AFK ones.

**Comment by jonnyawsom3** [comment]
I know about AFK/away users, in the example I said I was talking about the away users combined with active ones for simplicity. It said 14 (+1 away) out of 16

**Comment by shadowpanther** [comment]
That's weird, was it changed recently? I always saw the count including invisible users.

**Comment by TehTurk** [comment]
Hmm can you get pictures of this? I remember the player count still being accounted for the overall session info.

**Comment by jonnyawsom3** [comment]
I can try, ideally when some of my contacts are online I could ask them to test it

**Comment by shadowpanther** [comment]
![image](https://user-images.githubusercontent.com/675104/125347849-1b593d00-e364-11eb-90ff-2919cda5be76.png)
Here's the example, I see 6 users while I see 5 names. This has always been true for me.

![image](https://user-images.githubusercontent.com/675104/125348034-62473280-e364-11eb-9eb8-66d7d8f52ff5.png)
Here's another one, with 9 names, 8 present and 3 afk. One of the afk is also invisible.

**Comment by TehTurk** [comment]
Hmm okay, unless you have any objections @jonnyawsom3 I see no reason to have the issue open, let me know what would be most ideal or if the issue is different from what we are talking about.

**Comment by jonnyawsom3** [comment]
Maybe it was just from high server load during the convention, unfortunately I still don't have anyone around to test it right now (And the most full server still has 6 slots empty) so I suppose I'll close the issue unless I see it again

**Comment by Aerizeon** [comment]
I definitely saw this during VBLFC - so I wonder if some other configuration was impacting it.
