### ISSUE TITLE
Access to previous versions of the same world (versioning worlds, rollback)

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2630]
## Is your feature request related to a problem? Please describe.
There is a problem that when privately or collaboratively building a world, there is no way to, at the same time:
- keep the world saving often (to keep the lost part of the work to a minimum)
- have previous versions of the world and the ability to roll back in the case of an emergency
- avoid doing manual saving of named copies of the world and maintaining the acceptable number of stored versions

## Describe the solution you'd like
Having a native versioning system that would allow to go back to one of the previously saved copies of the same world (probably some limited number of copies to not put too much strain on the cloud) and to save this loaded earlier copy either as a new current version of the same world (same ID/URL) or as a separate copy (save as).

As a bonus, the ability to "pin" certain versions of the world (like building milestones) so that those would not be automatically removed.

## Describe alternatives you've considered
Having to manually save the world as a new copy once every several minutes. Having to manage and clean up the previously saved copies.

## Additional context
I initially posted this idea in Discord: https://discord.com/channels/402159838827905024/477711742001086505/864122191696101416

**Comment by shiftyscales** [comment]
Frooxius' response from the Discord:
> It's something we'd like to add, but it's a bit more complex than that. Worlds aren't just a single asset, they have a record with metadata and they pin numerous other assets.
> 
> That all needs to be preserved, otherwise you might not be able to load the world properly again if some of the assets get deleted.
> Main thing is to do it efficiently. Right now pinning computes a diff between old and new and only handles changes, but doing that across multiple versions is a bit more complicated to do without overhead.

You had already covered it in point three, but for the moment, that is the required workflow to meet these needs- have one publsihed/finalized copy of the world, and one working copy. Whenever you hit an internal milestone, use 'save copy' to put that aside, and continue to work on the working copy (with autosave enabled).

Whenever you are at a milestone you are ready to publish, you can overwrite the original world (which unfortunately seems to be a lesser known mechanism) so you can update the published copy without needing to worry about unintended changes getting pushed.

To overwrite a world, hold the (new) world orb in your hand, and click on the (old/published) world orb to bring up an overwrite option on the context menu.

This means that you only need to keep two copies of the world (one published + one working) plus whatever milestones you wish to use as backups for however long you need them.

**Comment by shadowpanther** [comment]
I know the current workflow, the request is for a more convenient one to avoid manual management of saves.
And the intention here is to allow autosave to run often, while also avoiding a disaster of autosaving the world just after some breaking change was made (intentionally or unintentionally). In your workflow, a disaster like that would roll you back to the last published milestone, which could mean losing hours of work.
