### ISSUE TITLE
Option for log file location in configuration file (Headless client)

### ISSUE THREAD

**Issue by glitchfur** [Neos-Metaverse/NeosPublic#2634]
## Is your tweak request related to a problem? Please describe.
The headless client has command line parameters for overriding the location of the data, cache, and log file folders to be used. **DefaultConfig.json** also has `dataFolder` and `cacheFolder` keys to specify these custom locations in the configuration file itself, but no such option exists for providing a custom location for log files.

## Describe what would you like tweaked
Please add an option, such as `logsFolder`, to the configuration file which allows for specifying a custom location for log files without having to provide the location on the command line.

## Describe alternatives you've considered
I do not have any alternatives at this time.

## Additional context
None.

**Comment by Frooxius** [comment]
Adde in 2021.7.21.127, thanks!
