### ISSUE TITLE
Static identifier for "focusing" running sessions (Headless client)

### ISSUE THREAD

**Issue by glitchfur** [Neos-Metaverse/NeosPublic#2635]
## Is your tweak request related to a problem? Please describe.
At the moment there are two ways to reference a session when "focusing" it in the headless client: Either by world index or by session name. However both of these values are volatile. Session names can be changed in-game, and world indexes shift around as sessions are started or closed. Consequently, in some situations world names or indexes would have to be looked up before each `focus` to avoid errors caused by attempting to focus a nonexistent session, and to avoid focusing the wrong world.

## Describe what would you like tweaked
Please add a way to focus sessions using an identifier that doesn't change. Session IDs are already static and allowing their use in the `focus` command would be one way to implement this tweak (the below output is theoretical):
```
Glitch Test Session 1>worlds
[0] Glitch Test Session 1           Users: 1	Present: 0	AccessLevel: Anyone	MaxUsers: 32
[1] Glitch Test Session 2           Users: 1	Present: 0	AccessLevel: Anyone	MaxUsers: 32
Glitch Test Session 1>focus S-7e077866-6d8e-4b4f-8f89-14580673b021 (Session ID of "Glitch Test 2")
Glitch Test Session 2>
```

## Describe alternatives you've considered
An alternative solution could be to prevent reuse of indexes for worlds that were closed so that indexes remain permanent for other worlds. Example: Three sessions are running with indexes `0`, `1`, and `2`. The world at index `1` is closed. The list of worlds as shown by the `worlds` command should show indexes of `0` and `2`, instead of `0` and `1`.

## Additional context
I feel that this would primarily be useful in situations where a script is being used to control the headless client by issuing commands to its console and capturing the output. Being able to focus different sessions using an unchanging value would be more reliable and efficient than having to continuously check for changed world indexes or names.

**Comment by Frooxius** [comment]
Should now be implemented in 2021.7.21.127, thanks!
