### ISSUE TITLE
Steam Overlay / Oculus Dash detection

### ISSUE THREAD

**Issue by GrayBoltWolf** [Neos-Metaverse/NeosPublic#2640]
## Is your feature request related to a problem? Please describe.
Not directly an issue, just a quality of life improvement for visuals. When a user opens the Steam overlay or Oculus dash it is not shown in game as is the case on similar VR games. Others in the world have no way to know the user has essentially "ALT + TAB"ed out of the game.

## Relevant issues
Related indirectly #1551.

## Describe the solution you'd like
Interested to see a logix node to detect if the user has opened the SteamVR Overlay or Oculus Dash. Could be related to the existing user flags "presentInWorld", "presentInHeadset", or "VrActive". Other VR games will display the user as away when opening a game overlay, could be presented as a logix option for a user to indicate when they open an external overlay.

## Describe alternatives you've considered
Other solutions utilize detecting controller movement to indicate the SteamVR overlay has been launched. This solution is a workaround and requires a certain timeout period to detect lack of controller movement. This solution also does not work for Oculus users as controller movement is still prevalent when in the Oculus Dash. 

## Additional context
Consideration for the Neos team, maybe game overlay detection could be a bool as part of the SimpleAwayIndicator component  on the avatar, or more simply just allowing a Logix node if the user wishes to build this functionality into their avatar.

**Comment by Frooxius** [comment]
Added new nodes in 2021.7.21.127, hopefully they serve well!

- Added IsNeosDashOpened LogiX node (under Users) which indicates whether given user has their Neos dash opened
- Added IsPlatformDashOpened LogiX node (under Users) which indicates whether given user has platform-specific dash opened (SteamVR dash or Oculus) (based on request by @Shifty | Quality Control Lead, GrayBoltWolf)
