### ISSUE TITLE
Massive unsafe Bloom due to Clowd varables 

### ISSUE THREAD

**Issue by peterthethinker** [Neos-Metaverse/NeosPublic#2641]
## Describe the bug
[users are able to  drive RGBA to  Unsafe Malicious   Levels with the new Varable . ]

## Relevant issues
[Did you find any existing issues relevant to this one? If you found the same issue, please contribute to that one instead of making a duplicate.]

## To Reproduce
[ Drive the  Color values to max ]

## Expected behavior
[not  burn my eyes out .]

## Screenshots / Video
[

![image](https://user-images.githubusercontent.com/65923672/125639312-f5c0b3d0-5267-48fe-8f68-0fb3700133a9.png)

## Additional context
[Perhaps a  cap on values to not allow for super duper easy  Abuse ]

## Reporters:
[thanks to art0007i and Rubix the fox and Me

**Comment by art0007i** [comment]
to clarify the reproduction: 
write an absurdly high value to the cloud variable `G-Neos.CustomUserColor`
then the default avatar that uses this value will be insanely bright

**Comment by Banane9** [comment]
Are you saying you can set that to an overdriven color for yourself, or are you saying someone else can set it on someone?

**Comment by RyuviTheViali** [comment]
Value limiting can be added to the default avatar, however given that the cloud variable is just a color value, like other variables it can be set to any value. Limiting has to be done outside the variable.

**Comment by RyuviTheViali** [comment]
This issue has been fixed and pushed to the default avatar. Values are now limited between [0;0;0;1] and [1;1;1;1].

**Comment by Earthmark** [comment]
this may not be fixed with the gloves

**Comment by RyuviTheViali** [comment]
The hands and view camera are clamped as well.

**Comment by peterthethinker** [comment]
YAY   ! thankyou!
