### ISSUE TITLE
Headless Auto Save Tweek

### ISSUE THREAD

**Issue by win189** [Neos-Metaverse/NeosPublic#2646]
### Is your feature request related to a problem? Please describe.

the Main problem with a headless is that small to large groups who want to build a world where they can have revisions can not truly use a headless as if you use autosave it saves over the existing world when using autosave unlike servers Like mine craft where the world gets saved in a new file each time

This causes Problems as if someone let's say crashes the world in an unrecoverable state and autosave saves. every bit of work is Lost in that world as the save is overwritten.

### Describe the solution you'd like

a Version Like a system where the headless can launch to the newest version by default and then in-game an admin could "Rollback" to a Previous save provided there was enough space in the headless storage ( depending on if it was set to Cloud or local) and in the configuration could State how many saves  a group would like to maintain based on their storage amount or number of hours to go back as a sudjestion

### Describe alternatives you've considered

not use a headless and only have one person in group work on the world at a time and cause slowdowns in work flow

**Comment by shiftyscales** [comment]
Thanks for the suggestion, @win189 - another recent issue, #2630 was requesting a similar implementation, so I will mark this issue as a duplicate and direct all further conversation toward that issue instead.
