### ISSUE TITLE
TipJar Cooldown should be Local

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#2652]
### Is your tweak request related to a problem? Please describe.

Some users are using TipJars in scenarios where **multiple users**(distinct users) might want to tip in quick succession. 

This is frustrating right now as the timeout that exists on the TipJar seems to be global as in only ONE user can tip every 60 seconds.

### Describe what would you like tweaked

These users have requested that the tipjar's cooldown be moved to local so it becomes each user can only tip once every 60 seconds.

### Describe alternatives you've considered

I've looked at the code here and I don't really know why this cool down even is global technically but its been reported as global multiple times.

### Additional context

Reported by I'm Erin and a few others I forgot.

**Comment by Frooxius** [comment]
This is really strange, because the cooldown already is local.

Does this happen with the vanilla component? What is the setup like, is it being triggered through a button or through collider or something else?

**Comment by ProbablePrime** [comment]
I spoke to those involved, it looks like this was a missunderstanding.
