### ISSUE TITLE
Headless host doesn't show in the session user count, but is counted towards the session user limit

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2653]
### Describe the bug?

A session hosted on the headless shows one user less in the World Browser, but the headless user is still counted for the purpose of limiting the number of users in the session.

### Relevant issues

#2627 might be caused by this

### To Reproduce

- Start a headless session
- Set maxUsers to 1
- Find the session in the World Browser (would show 0 out of 1)
- Try to join the session (would say session is full)

### Expected behavior

Either the headless host is counted for the purpose of displaying the number of users, or is not counted towards the session user limit.

### Screenshots

![image](https://user-images.githubusercontent.com/675104/125955090-9ba07ec3-9250-4dcc-bc6a-6e73aea6b012.png)
![image](https://user-images.githubusercontent.com/675104/125955104-338ed67a-654f-40f3-be1e-a6fd0560d760.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.7.11.1002

### What Platforms does this occur on?

- [X] Any
- [ ] Windows
- [ ] Linux
- [ ] Android / Quest

### Did this work before?

No

### Reporters

Shadow Panther#5154, Kulza#8623, Fuzzy#5786

**Comment by Frooxius** [comment]
Should be fixed in 2021.7.21.127, let me know if you run into any more issues!
