### ISSUE TITLE
Deactivated tooltip templates can be pulled off of avatars

### ISSUE THREAD

**Issue by zkxs** [Neos-Metaverse/NeosPublic#2655]
### Describe the bug?

My avatar has a few tooltip templates on it parented under a deactivated slot. If I am sitting on a grabbable anchor and someone pulls me to their hand with the analog stick, it will yank one of these tooltips and equip it to their hand. This is troublesome, as it breaks my avatar's Logix and I cannot find any workaround to prevent this behavior.

### Relevant issues

No

### To Reproduce

1. Create a new slot on an avatar
2. Deactive the slot
3. Parent any tooltip under the slot
4. Equip the avatar and sit on a grabbable anchor
5. Have someone pick you up with a laser grab and pull you onto their hand

### Expected behavior

Deactivated tooltips should be exempt from the lasergrab pull equip functionality.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.7.11.1002

### What Platforms does this occur on?

- [ ] Any
- [X] Windows
- [ ] Linux
- [ ] Android / Quest

### Did this work before?

No

### Reporters

- runtime / zkxs#1039
- Erin / xYreous#9690

**Comment by shiftyscales** [comment]
Thanks for reporting. This issue is highly related to #2499 and #766, so I will be marking this as a duplicate/would advise you to direct your attention towards those existing issues, please.
