### ISSUE TITLE
Refine/tweak user feet reactivity conditions

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2670]
### Is your tweak request related to a problem? Please describe.
There are a few conditions in which feet reacting to other users is undesirable because it looks/acts strangely. Primarily this occurs when users are standing close to each other, e.g. hugging, a smaller user walks under/between a larger user's legs, etc.

### Describe what would you like tweaked
Modify the logic for when feet rise up/collide to exclude cases when both users are grounded.

Perhaps interactivity in that scenario could be constrained to just interactions with the hands?

### Describe alternatives you've considered
Use FeetIgnoreOtherPlayers, the current easiest way to work around this issue at the expense of removing that reactivity from the avatar.

### Additional context
This was previously brought up as issue #676.

**Comment by shiftyscales** [comment]
An issue for this already existed: https://github.com/Neos-Metaverse/NeosPublic/issues/676

I had closed it because changing the default is the wrong way to handle this issue.

What Frooxius had to say on the previous issue:
> I don't think this is a good idea, because I often see the feet being reactive to other players being one of the positives that people like about Neos, as it shows high level of interactivity. If it's hidden behind a setting, most people won't know about this functionality.
> 
> What can instead be done is refine the reaction, so the feet will ignore the player under certain conditions that look weird, but not in others.

https://github.com/Neos-Metaverse/NeosPublic/issues/676#issuecomment-643580092

**Comment by SnooperXP** [comment]
Would including an advanced option on the avatar creator be a suitable compromise or does something like that already exist?

im making an assumption that you’re wanting to remove it from avatars you’re creating, and the pain point here is having to go through, find, and disable it every time?

**Comment by Sox-NeosVR** [comment]
I think leaving the setting as off by default would be the best option, mainly because when people see it as an issue they would instinctively ask other users if it is a toggleable option where as if it was off it wouldn't be as obvious that it even exists until you really snoop through the components that are on the avatars root slot.

**Comment by shiftyscales** [comment]
> 
> 
> Would including an advanced option on the avatar creator be a suitable compromise or does something like that already exist?
> 
> im making an assumption that you’re wanting to remove it from avatars you’re creating, and the pain point here is having to go through, find, and disable it every time?

I would think in the eventual scope of component access, we will eventually see user-made utilities to automate various tweaks/changes without the need to dig through inspectors/components on existing avatars, no need for it to be included in the avatar creation process itself.

**Comment by AshtonSparx** [comment]
It is a nuisance having to go into every one of my avatar's root (Which is Neos freezing inducing every time it's selected) I make (and for others who hate it) is really bothersome, having an option in the avatar creator or model import that turns it on for you (Leaving it disabled by default would be fine, as in, let them stand on you) even if it's hidden in advance option or something during import could be a compromise.

**Comment by shiftyscales** [comment]
@AshtonSparx - please be mindful of the language you use, and keep issues and comments objective. I understand that the issues reported can be frustrating- but emotion should be left at the door when creating issues. Stick to being objective, and just presenting the facts.

**Comment by AshtonSparx** [comment]
My apologize. That wasn't my intent at all! I fully apologize if that's the way I came off of.

**Comment by Frooxius** [comment]
I've done a bunch of tweaks in 2021.9.20.1334 which should now behave much better. We might need to do a few more tweaks if there are issues with it when it gets tested, but I'm closing this for now!
