### ISSUE TITLE
Contact list doesn't show non-contacts that you have unread messages from

### ISSUE THREAD

**Issue by win189** [Neos-Metaverse/NeosPublic#2674]
### Describe the bug?

one day another person and I were fooling around and they sent me a bunch of invites and 7 of them doesn't seem to want to clear off even though
I have read all messages
I have No Contacts requests
I have all known Bots friended

I have cleared %USERPROFILE%\AppData\LocalLow\Solirax\NeosVR 
in hopes that it is a client side bug

### Relevant issues

No, i have asked shifty and in the discord and no one was able to help solve the issue

### To Reproduce

for me its auto on login

### Expected behavior

to not have it saying unread message

### Screenshots

![Neos_eYjffslY9x](https://user-images.githubusercontent.com/24577138/126412160-bd6e7c85-dd1e-499e-a336-5962cbc855d3.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.7.11.1002

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

**Comment by Frooxius** [comment]
Can you press the F9 key please and send me the log? It should print message starting with "Unread Status.", which will contain information about where are the unread notifications coming from.

**Comment by win189** [comment]
[DESKTOP-Q5Q0ES2 - 2021.7.21.142 - 2021-07-21 02_42_23.log](https://github.com/Neos-Metaverse/NeosPublic/files/6853368/DESKTOP-Q5Q0ES2.-.2021.7.21.142.-.2021-07-21.02_42_23.log)

**Comment by win189** [comment]
The Person with Seven messages was a Contact removed from my contact a while ago there were no messages from the person when i removed the contact but they seemed to have been able to message me afterwords

**Comment by win189** [comment]
OK i fixed the Issue Myself 

For those who are experiencing messages from people you have removed from your contacts that may have sent messages to you after you removed them or that you didn't read the messages and removed the person from your contacts menu Please do the following 

Log into neo`s 
Press F9 then Close NEo`s
go to your logs folder  typically in "C:\Program Files (x86)\Steam\steamapps\common\NeosVR\Logs"
Open the newest log file
do CTRL+F to bring up the Find Dialog and search for "Unread Status. Unread Message Count"
just below that you will have a list of users of anyone you have unread messages with 
Log into neo`s 
Copy and paste the names from the Log to bring up their account 
Click on their name in the contacts list and browse the messages tell there all read
repeat for any other contact in there  
and now complete and enjoy the rest of your say on neo`s

**Comment by shadowpanther** [comment]
While finding contacts in the log allows you to read their messages, I feel that Contacts system should show such messages from users that are not your contacts.
That would also solve the common issue of receiving invisible messages from njbank and NeosFishing while playing Japanese games.

**Comment by shadowpanther** [comment]
I've changed the title of the issue to more closely reflect the underlying issue.

**Comment by shiftyscales** [comment]
> 
> 
> I've changed the title of the issue to more closely reflect the underlying issue.

Thanks @shadowpanther - there is also an existant issue #1482 that is requesting a mechanism for non-contacts to send/receive messages.

It's something that will be planned for the Contacts UI rework, and won't be fixed in the current UI.

**Comment by Frooxius** [comment]
Fixed in 2021.7.22.458, any non-contacts are now filtered when counting unread messages!
