### ISSUE TITLE
Holding an item and opening your dash leaves the item held until you close the dash

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2676]
### Describe the bug?

When in VR, while holding an item, opening your dash means you can't let go of the item till you close your dash.

### Relevant issues

N/A

### To Reproduce

1) Hold An Item
2) Open Your Dash
3) Try to let go of them item
4) Close your dash, it now let's you let go of your held item

### Expected behavior

Allow you to let go of the item while your dash is open

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.7.21.402

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

2021.7.11.1002

### Additional context

Only started happening during update 2021.7.21.402 -- I suppose it was accidental for this to happen while in VR and not just in desktop mode. 

### Reporters

AshtonSparx#5050

**Comment by shadowpanther** [comment]
Updated the title and marked as a regression

**Comment by Frooxius** [comment]
Fixed in 2021.7.21.1394 patch, sorry for the trouble!
