### ISSUE TITLE
Reverb Zone Presets Are Non-functional

### ISSUE THREAD

**Issue by RyuviTheViali** [Neos-Metaverse/NeosPublic#2678]
### Describe the bug?

The presets available in the ReverbZone component for reverb presets no longer function, having no effect on the reverb zone's controls.

### Relevant issues

No relevant issues.

### To Reproduce

Open an inspector, and attach a ReverbZone component to an empty object. Click on any of the reverb zone's presets to see they are non-functional.

### Expected behavior

When a preset is chosen, it changes the reverb zone's sliders to what the preset gives.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.7.21.402

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### Additional context

I'm unsure when the presets broke, but it has been this way for a handful of updates now.

### Reporters

Ryuvi (Ryuvi#9094)

**Comment by Frooxius** [comment]
Fixed in 2021.7.22.458, thanks for report!
