### ISSUE TITLE
On-Launch Desktop Login Window

### ISSUE THREAD

**Issue by bitchcakes** [Neos-Metaverse/NeosPublic#2679]
### Is your feature request related to a problem? Please describe.

For those of us that:
- Launch from desktop, then put on headset
- Launch from headset, but have a complicated password that's either typed or stored in a password manager
- - In the case of a password manager, juggling between headset on and off to get your password pasted in the correct field is currently a pain
- Prefer to not use virtual keyboards or switch back and forth between VR and keyboard for password or 2fa entry
- Have no idea if they'll end up launching the game before or after they put on the headset

I suggest an on-launch desktop login.

### Describe the solution you'd like

While Neos starts up, an additional desktop window pops up that allows the user to log in and input 2fa code. Logging in can be done through either the headset or this window. Upon successful login, via HMD or keyboard, the window dismisses. 

This allows users to type in their 2fa code or paste their password without having to juggle between flatscreen and HMD.

This could be a possible launch command toggle, as there are some cases where users won't want the window to pop up.

### Describe alternatives you've considered

USB security key login
Secure USB macro login device of some sort?
Software macro 

Thanks in advance for your consideration! Y'all are the best damn dev team I've seen.

**Comment by Frooxius** [comment]
Why do you need an additional window for the login instead of just using the main Neos window? You can just toggle from VR to Screen mode with press of the F8 key.

Adding an extra window would require significant additional engineering, as we don't have a mechanism for that right now, so it's unlikely this would get prioritized anytime soon and I'm not sure what benefit it provides over just using the existing login dialog.

**Comment by bitchcakes** [comment]
Ahh, I've not used desktop before and didn't realize it was quickly toggled. The last I had heard was that you needed to hold F8 and it was a permanent mode to switch into. In that case, this is pretty much all set. 

Thanks!
