### ISSUE TITLE
[Regression] Play One Shot is not working.

### ISSUE THREAD

**Issue by orange3134** [Neos-Metaverse/NeosPublic#2680]
### Describe the bug?

Play One Shot is not working.
It only works when the Static Audio Clip is displayed in the Inspector.

### Relevant issues

I couldn't find a related issue.

### To Reproduce

1. Create a new Slot in Inspector and attach the StaticAudioClip component.
2. Connect the StaticAudioClip to the PlayOneShot node.
3. Close the Inspector or select another Slot in the Inspector.
4. When I run this LogiX, there is no sound.
5. View the Slot with the StaticAudioClip attached again in the Inspector and run this LogiX. I can hear the sound.

### Expected behavior

I should be able to hear the sound even when I close the Inspector.

### Screenshots

Video showing that no sound is played unless it is displayed in the Inspector
https://youtu.be/H07_woZFpwE

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.7.21.1394

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

2021.7.21.402

**Comment by Frooxius** [comment]
Fixed regression in 2021.7.22.458, thank you for the report!
