### ISSUE TITLE
Phantom account when using remember me option

### ISSUE THREAD

**Issue by kodxana** [Neos-Metaverse/NeosPublic#2684]
### Describe the bug?

When I use remember me option every time I restart Neos I'm logged in on some no name account (it has no name standard account, but funny it has my friend list but it's not able to join sessions). To have it work I need log out of that account and manually login to my account.

### Relevant issues

None

### To Reproduce

1. Login to game (Use option remember me)
2.Load to game and exit.
3. Start game again (and I get error here)

### Expected behavior

I should be logged to my account every time I open Neos

### Screenshots

![image](https://user-images.githubusercontent.com/16674412/126623573-54deb4bf-5216-4677-b3e2-6e1d73692720.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.7.22.458

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

Not sure but it's about 1 month

### Reporters

Madiator#2011

**Comment by shadowpanther** [comment]
Logs are sent to Shifty by Madiator#2011

**Comment by shiftyscales** [comment]
The logs you had sent me were captured on version 2021.7.21.402. Does this definitely occur on the latest build, @kodxana?

Would you be able to make a cleaner replication log by starting Neos so it's in that state, then exiting Neos?

Is the issue resolved if you log out, and back-in mid-session?

If you don't use 'remember me' and log in each time, does the issue also not occur?

**Comment by Frooxius** [comment]
It seems like the profile facet might've gotten stuck for some reason. Meaning you are fully logged in, but the UI that shows your profile got stuck and hasn't refreshed to respect that status.

Have you made any changes to your dash? You could try the "Reset Dash" option in the launcher to refresh it.

**Comment by kodxana** [comment]
Funny thing recent update fixed problem. Now I get login to my account (with showing Patreon status and also I'm able to join sessions) though my local home is my local instance rather than world I set as my home.

**Comment by shiftyscales** [comment]
> 
> 
> Funny thing recent update fixed problem. Now I get login to my account (with showing Patreon status and also I'm able to join sessions) though my local home is my local instance rather than world I set as my home.

Thanks for the update on the issue, if anything like this happens again, please re-open the issue, or make a new one.

When you set a home world- that is your cloud home you are setting, not the local. You should load into your cloud home by default when you launch Neos unless you've used the command line argument to prevent it from loading. Otherwise, you can also always access your cloud home from the facet on the home screen of your dashboard.
