### ISSUE TITLE
Logix Node for teleporting user to a given position, with a given orientation.

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#2685]
### Is your feature request related to a problem? Please describe.

Currently, teleporting a user to specific coordinates in a world from LogiX requires calculating the offset between their playspace center, and their avatar's feet position.  

Setting the user to face a specific direction requires some complex transform math, resulting in their userroot being rotated and positioned such that their existing position and orientation in the user root ends up coinciding with the target position and orientation. 

### Describe the solution you'd like

A LogiX node that has inputs for Target Position and Target Orientation, which results in the user being positioned at the given coordinates, with the given rotation.

This seems like it could use code similar to the "Jump" button in the Session > Users tab.

Alternately, LogiX nodes that help calculate User Root transforms based on desired avatar position/rotation would be nice.

### Describe alternatives you've considered

Calculating this manually in LogiX, which is time-consuming, and results in a not-insignificant amount of code.

**Comment by Frooxius** [comment]
I think what would be most fitting here is having "Set" variants of the various Users/User Root nodes, like HeadPosition, HeadFacingDirection, FeetPosition and so on.

This is what Neos uses internally to pose the user, e.g. it wants to place their feet (whether actual or simulated) at particular point, or make sure that user is facing certain way, so exposing those in LogiX would work well.

**Comment by Aerizeon** [comment]
That seems like it'd work, and having the ability to set the position in terms of things other than feet sounds like a nice bonus as well.

I hadn't really looked into how Neos handles teleportation too deeply, so I wasn't aware it did that ^^

**Comment by Frooxius** [comment]
Added a whole bunch in 2021.7.23.529!

-- SetHeadFacingDirection
-- SetHeadFacingRotation
-- SetHeadPosition
-- SetHeadRotation
-- SetHipsPosition
-- SetHipsRotation
-- SetFeetPosition
-- SetFeetRotation
