### ISSUE TITLE
Logix node: BoundingBoxEncapsulate: overload for 2 bounds

### ISSUE THREAD

**Issue by ukilop** [Neos-Metaverse/NeosPublic#2688]
### Is your feature request related to a problem? Please describe.

I`d like to create a bounding box that is the union of two other bounding boxes.

### Relevant issues

none found

### Describe the solution you'd like

an overload like this, similar to the Encapsulate Rect node above
![2021-07-22 19 43 23](https://user-images.githubusercontent.com/1341270/126725807-121c02ba-3477-47fd-a6fa-ee45ff1c849a.jpg)

### Describe alternatives you've considered

my current setup
![2021-07-22 19 39 16](https://user-images.githubusercontent.com/1341270/126725954-583a5c93-5147-4010-b19d-aa341a78ca35.jpg)

### Additional context

creating Issues in vr is hard ;-;

**Comment by ukilop** [comment]
physics/colliders tag?

**Comment by shadowpanther** [comment]
> physics/colliders tag?

Bounding box is part of physics?

**Comment by Frooxius** [comment]
Hmm this is odd, this overload already exists, but doesn't seem to auto-swap. I'm looking into why.

**Comment by Frooxius** [comment]
The nodes couldn't actually overload, because the inputs are named differently. I just split them up, so you now have Encapsulate Point and Encapsulate Bounds in 2021.7.23.529! Thanks!
