### ISSUE TITLE
Add type selector for BodyNode for both `Enum to Int 1` and `Int to Enum 1` in node browser

### ISSUE THREAD

**Issue by Titancube** [Neos-Metaverse/NeosPublic#2690]
### Is your feature request related to a problem? Please describe.

There are selectors for other types in node browser for ``Enum to Int `1`` and ``Int to Enum `1`` but I couldn't find a one for `BodyNode`.
Type of `BodyNode` already exists when loading the node through component attacher, but there's no way to load it in node browser.

### Describe the solution you'd like

Add a type selector for `BodyNode` for both nodes like other types.

### Describe alternatives you've considered

I cannot think of other ways to do this rather than putting it in node browser.

**Comment by Frooxius** [comment]
Added in 2021.7.23.529, thanks!
