### ISSUE TITLE
Allow disabling of non-active controllers

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2691]
### Is your feature request related to a problem? Please describe.

A user came in who has stick drift on an xbox controller plugged into their PC, they don't want to use the controller with neos, but they don't want to need to unplug it either.

This is a minor feature request and don't mind unplugging it, but I figure others may run into this as well.

### Relevant issues

Unsure

### Describe the solution you'd like

No idea,.

### Describe alternatives you've considered

They unplug the controller every time, they're fine with this but I figure this is good to bring up.

### Additional context

NebulaWolfie was the user encountering the problem.

**Comment by Frooxius** [comment]
We already have issue for this here: https://github.com/Neos-Metaverse/NeosPublic/issues/2196

**Comment by Earthmark** [comment]
My bad, I had searched for controller but didn't see that one somehow... Thanks for deduplicating!
