### ISSUE TITLE
Allow string comparison in Logix

### ISSUE THREAD

**Issue by zkxs** [Neos-Metaverse/NeosPublic#2703]
### Is your feature request related to a problem? Please describe.

There is currently no built-in way (that I'm aware of) to compare strings to each other by their natural ordering. While there's a workaround, it's rather complicated and requires adding a bunch of extra Logix to something just to perform a string comparison.

Off the top of my head one big use case for string comparisons is sorting algorithms. I've got some insertion sort Logix that could really use this feature.

### Relevant issues

None found

### Describe the solution you'd like

Allow string inputs to `<`, `>`, `≤`, and `≥`

### Describe alternatives you've considered

Logix to iterate over each character in two different strings until either one of the characters differs or one of the strings ends, and then at that point compare the current characters' UTF values.

**Comment by Frooxius** [comment]
Added the nodes in 2021.7.31.1211! Thanks!
