### ISSUE TITLE
Avatar dequips when using full body calibrator with head-and-hands avatar

### ISSUE THREAD

**Issue by torch89** [Neos-Metaverse/NeosPublic#2704]
### Describe the bug?

I'm having a bug when i hit calibrate my avatar in full body calibrator it kicks me out of my avatar

### Relevant issues

n/a

### To Reproduce

* Start Neos
* Load a Polytar avatar (my custom one, but the default from Engi works too - confirmed) (actually, any head-and-hands avatar seems to trigger it)
* Open Fullbody Calibrator
* Click Calibrate Avatar
* You avatar dequips, leaving you as an orange body overlay with a pair of default hands and no head

### Expected behavior

Avatar stays equipped, calibration starts.

### Log Files

[VIXEN - 2021.7.25.489 - 2021-07-29 23_29_04.log](https://github.com/Neos-Metaverse/NeosPublic/files/6903432/VIXEN.-.2021.7.25.489.-.2021-07-29.23_29_04.log)

### Screenshots

![image](https://user-images.githubusercontent.com/675104/127562317-2e6bbbc6-285c-441b-8580-6c1f9c04cfbe.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.7.25.489

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

neosrec:///U-Engi/R-73fb5f55-df8c-478d-8047-d72deb1c014e

### Did this work before?

Unsure

**Comment by shadowpanther** [comment]
@torch89 could you provide some logs or replication steps? The issue doesn't seem to affect anyone else, so either you are doing something weird or something is broken with your PC/Neos/account/avatar.

Could you try equipping one of the public avatars (like a skeleton, for example) and repeating your steps?

**Comment by Beaned2000** [comment]
Try to also isolate any issues by doing this in your own session with no users in it and if necessary in a freshly made world. as shadow said providing a log would be best so we can see if there are any issues popping up in there.

**Comment by shadowpanther** [comment]
[VIXEN - 2021.7.25.489 - 2021-07-29 23_29_04.log](https://github.com/Neos-Metaverse/NeosPublic/files/6903432/VIXEN.-.2021.7.25.489.-.2021-07-29.23_29_04.log)

Replication case:
* Start Neos
* Load a Polytar avatar (my custom one, but the default from Engi works too - confirmed)
* Open Fullbody Calibrator
* Click Calibrate Avatar
* You avatar dequips, leaving you as an orange body overlay with a pair of default hands and no head

Replication item: neosrec:///U-Engi/R-73fb5f55-df8c-478d-8047-d72deb1c014e

Screenshot:
![image](https://user-images.githubusercontent.com/675104/127562317-2e6bbbc6-285c-441b-8580-6c1f9c04cfbe.png)

**Comment by shadowpanther** [comment]
Yes, after opening the calibrator, it's "Skip and adjust avatar". Sorry for not naming the button correctly, I work in another locale and don't always check the original name of the button.
The button is not disabled, so it's possible to click it and be forced out of your avatar, which in the case of the default headset-and-hands would also mean losing the avatar to easily get back into.

**Comment by Frooxius** [comment]
Ah thanks. I made it so it gets grayed out properly, so that should solve the issue!

**Comment by Frooxius** [comment]
Fixed in 2021.8.2.936, thanks!
