### ISSUE TITLE
Minecraft worlds auto climb

### ISSUE THREAD

**Issue by Moonblazer** [Neos-Metaverse/NeosPublic#2708]
### Is your feature request related to a problem? Please describe.

I make and import minecraft worlds to NEOS. one of the issues regarding when the obj file is imported is that slabs, stairs, and to an extent, dirt paths are impossible to climb without making invisible collision boxes for every form of elevation change. This can end up being frustrating when there is many stairs and slopes needing separate collision boxes to act as ramps for seemless

### Describe the solution you'd like

have an advance import setting for obj files that auto adds stairs or slabs based on available height

### Describe alternatives you've considered

n/a

**Comment by Frooxius** [comment]
I'm sorry, but this isn't something that's possible to implement on our end, the OBJ file contains purely geometry, so we cannot tell what's what - everything is just a bunch of triangles. The format and structure of the geometry can also differ widely depending on what tool you export from.

I'd recommend checking if you can adjust some tooling for exporting Minecraft maps, that will generate separate collision geometry during the export, when the block data from Minecraft world are available.

You can also try the built-in Minecraft world importer with Mineways, but you'll have a bit less control over things. However it does setup some of the collisions automatically, although currently it doesn't do ramps.
