### ISSUE TITLE
Asset loading is extremely slow when Neos is locked to one core

### ISSUE THREAD

**Issue by iamgreaser** [Neos-Metaverse/NeosPublic#2709]
### Describe the bug?

When Neos is locked to one core, asset loading is extremely slow. (See "Additional context" for the reason why I'm doing this.)

Two cores are enough for things to be at least somewhat smooth.

### Relevant issues

No, not really.

### To Reproduce

For Linux: When launching Steam, launch from the command line via `taskset` like so:
```
taskset -c 0 steam
```

Then launch Neos VR from there.

This has not been tested on other OSes and I don't know how one locks a task to one core on Windows.

### Expected behavior

I would expect Neos to perform only slightly worse, and I would at least expect the font to load today.

### Screenshots

I was about to say that absolutely nothing loads, but then some stuff loaded part way through writing up this bug report.

![image](https://user-images.githubusercontent.com/138113/126933041-18374ab1-b673-44a7-9eb0-c41158aee290.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.7.25.489

### What Platforms does this occur on?

Linux

### Did this work before?

I Don't Know

### Additional context

This was done as an attempt to diagnose the crashes I've been getting (e.g. #2702) by providing an environment which is less prone to race conditions actually manifesting.

I have confirmed that this is specific to Neos VR, as I also tested locking everything to one core with The Talos Principle which works completely fine. (On the other hand, I'm pretty bad at jumping over that one exit gate in A3... wait, you mean it *isn't* a parkour game?)

### Reporters

GreaseMonkey.

**Comment by Frooxius** [comment]
Thank you for the report, however this isn't something that we'll be devoting development time to.

Neos is designed as multi-threaded application, if you restrict it to a single core, it will only be able to use spare cycles, which means that a lot of tasks will simply not have enough time to progress quickly.

Designing Neos to work well on single-core systems would pose a significant engineering overhead for something that's a bit too niche, given that even a decade old hardware typically has at least 2 cores. I'd recommend to not restricting it to a single core, it's not designed for that.
