### ISSUE TITLE
A way to restore default locomotion modules from LogiX

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2711]
### Is your feature request related to a problem? Please describe.

We have a way to install custom locomotion modules on a target user, even to remove the existing ones while doing so (thus limiting the user to a custom set of locomotion modules independent of the world-provided ones). What we don't have is a neat way to (automatically) restore the default modules.

### Describe the solution you'd like

A new node, `Install Default Locomotion Modules`, taking just the user input and maybe "preserve existing modules" optional bool one.

### Describe alternatives you've considered

Adding another input to `Install Locomotion Modules` node that would reinstall the world-provided modules instead of adding a slot-referenced one.

### Additional context

This idea was brewed in a discussion between myself, Azavit#2360 and Shifty, following Azavit's own implementation via searching for world's locomotion modules by name which is not very efficient and foolproof.

**Comment by Zyzyl** [comment]
DAWKY and I were just talking about the need for something like this. Ideally our set of LogiX-accessible functionality would be expanded to:
- resetting a user's installed modules to the world defaults
- installing a custom locomotion and avoiding duplication (i.e. using something like the current ClearExisting input) while still keeping the defaults available
