### ISSUE TITLE
Asking Neos bot for /requestRecordUsageJSON returns the plaintext report instead

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2712]
### Describe the bug?

Sending both storage report commands (`/requestRecordUsageReport` and `/requestRecordUsageJSON`) to Neos bot currently returns the same short report, the former in the body of the email, and the latter in the attached .json file.

### Relevant issues

None

### To Reproduce

* Send `/requestRecordUsageJSON` to Neos bot
* Open the emailed file
* (optionally) compare the received file with `/requestRecordUsageReport`

### Expected behavior

A full JSON report being sent.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.7.25.489 (though it's a Cloud problem)

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### Did this work before?

Yes

### If it worked before, on which build?

This was reported yesterday, and was working before that, exact date of breaking currently unknown.

### Reporters

Ukilop#4463, 3x1t_5tyl3#0001, Duskitten#4455, Shadow Panther#5154

**Comment by ProbablePrime** [comment]
I've taken a look at this, there were a lot of changes during the SignalR Update and it looks like we might have broken this then. 

I've traced it to: 2021.7.9.1193

Will be taking a look at our Diffs there.

**Comment by ProbablePrime** [comment]
Ok I have a fix in the queue for Froox to look at.

**Comment by Frooxius** [comment]
Merged fix in 2021.7.31.1211, thanks!
