### ISSUE TITLE
Switching to desktop from VR leaves Is Platform Dash Opened set to True

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2713]
### Describe the bug?

With the recent addition of Dash detection nodes, I've added dash visual to my avatar.
My usual workflow when not using VR immediately is to just launch Neos, wait for it to load with the screen black, then press F8 to switch to desktop mode. That allows me to later switch back to VR without restarting the client.
Now, with the dash visual present, now I see that my Oculus Dash is "opened" in these circumstances, and I see no clear way to distinguish this F8-to-desktop state from VR state to turn off my dash visual.

### Relevant issues

#2640

### To Reproduce

* Launch in VR mode as usual (Oculus runtime)
* Switch to Desktop with F8
* Use `Is Platform Dash Opened` to check whether your dash is opened

### Expected behavior

Platform Dash status is not observed while in Desktop mode.

### Screenshots

![](https://media.discordapp.net/attachments/439422161657135106/869286581947752528/2021-07-26_21.33.06.webp)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.7.25.489

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

**Comment by ProbablePrime** [comment]
This is tricky, is there not a node to detect desktop mode?

**Comment by FroppyVR** [comment]
> This is tricky, is there not a node to detect desktop mode?

User Head Output Device detects screen mode, but it also doesn't appear to work with F8, only native screen. It outputs your VR (steamVR for me) even when in F8 screen.

![image](https://user-images.githubusercontent.com/77127788/127049054-6a291dd9-531e-4ca1-9870-2431b9111b88.png)

**Comment by ProbablePrime** [comment]
Thanks Froppy. I'm out of Neos atm and there are so many nodes I wasn't sure. I'm still not entirely sure.

Ideally here we'd need to find a way to detect screen mode. Sometimes in the design of Neos we can make edits to nodes etc but it feels like in this case it might be better to provide that we're in F8 Mode to allow for more complex behavior.

**Comment by shiftyscales** [comment]
@shadowpanther @ProbablePrime @FroppyVR the User VR Active node in users is the proper means to get a user's current VR/desktop status. False is desktop, true is VR. Hopefully this should cover the needs of your issue.

**Comment by shadowpanther** [comment]
Oh, thank you @shiftyscales, I missed this node somehow. All the other ones start with "Is", probably that was why I didn't look at the bottom.
