### ISSUE TITLE
Storage logix nodes for all enums

### ISSUE THREAD

**Issue by xYreous** [Neos-Metaverse/NeosPublic#2715]
### Is your feature request related to a problem? Please describe.

Not exactly a problem but it could be useful to have enum storage nodes

### Describe the solution you'd like

Add storage nodes for all enum types, if not all enums then only the more commonly used ones

### Describe alternatives you've considered

I cant think of an alternative other than adding the storage nodes

**Comment by Beaned2000** [comment]
So to clarify, you are asking for a Storage node for the Chirality type in the form of a ReferenceRegister<T> so you could for example store this by writing into it with a write node right?
Correct me if i'm wrong.

**Comment by ukilop** [comment]
Could this be expanded to generically include all enums? Like an EnumRegister?

**Comment by shiftyscales** [comment]
Do you have any examples of when/how you would use this? E.g. could you show us some of the cases you could have used the node?

**Comment by xYreous** [comment]
@ukilop That sounds like a better idea actually
@Beaned2000 Yes that is what I am asking for

**Comment by shiftyscales** [comment]
It is worth noting that there already exists the Enum To Int`1 and Int To Enum`1 nodes in Math > Enums, @xYreous @ukilop.

This includes the chirality type. So you could put the enum for chirality into an integer, store it in an int register, then restore it later.

**Comment by xYreous** [comment]
@shiftyscales I guess the only one I can think of at the moment is user voice mode, but as far as using the int to enum and enum to int nodes it doesn't make much sense to me as to why we have this rather than enum registers.

**Comment by kazu0617** [comment]
It would be a bit tedious, but it would have been possible to use DynamicVariable to do the saving and retrieving with the Enum type.
Create a blank object and enter the desired Enum type in Add Component > Logix > Variables > Dynamic Variable (Write / Input) > Custom Generic Type Name.

Once you have done this, unpack the EmptyObject and you will have a node that can input and output Enum types.

![image](https://user-images.githubusercontent.com/6259214/127090149-7596aa8c-7be3-413f-8bbd-5146e88026ec.png)

**Comment by Frooxius** [comment]
Added ValueRegister<T> in 2021.7.31.1211, which replaces all the specialized LogiX nodes and supports any value type supported by Neos, including enums. Thanks for report!
