### ISSUE TITLE
Add Option "LanguageCode" in "CurrentLocaleInfo"

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2717]
### Is your tweak request related to a problem? Please describe.

This problem is particularly relevant when translating text in Neos. Normally, the text can be identified by [LanguageCode] to some extent, but the LocaleCode currently retrieved outputs Language and Region together. This means that for some languages, there are more than 10 countries in use, and you need to either describe all of them, or separate them manually using Logix to extract the Language.
If there is a Language-only option, it would be much easier to implement.

この問題は、特にNeos内の文章について翻訳する際に深くかかわる問題です。文章は通常[LanguageCode]で判別することである程度対応できるのですが、現在取得されるLocaleCodeではLanguageとRegionがくっついて出力されます。これにより言語によっては使われている国が10か国以上あることもあり、それらすべてを記述するか、Languageを取り出すために手動でLogixを用いて分離する必要があります。
もともとこの二つのうち、Languageのみのオプションがあるのであればそれを使用した方がもっと楽に実装できるのではないか、となりIssueを出した次第です。

### Describe what would you like tweaked

NET Framework 4.6.2, it is described as follows.
Of these, currently only Name is probably extracted, but the request is to be able to additionally extract Parent or TwoLetterISOLanguageName.

.NET Framework 4.6.2では以下のように記載されています。
これらのうち現在はおそらくNameのみを取り出していますが、ParentかTwoLetterISOLanguageNameを追加で取り出せるようにしてほしい、という要望です。

https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=netframework-4.6.2

### Describe alternatives you've considered

Disassemble with Logix. There is a performance loss and the component can't handle it.

### Additional context

The StaticLocaleProvider may also be soft related to this.

**Comment by Frooxius** [comment]
Added in 2021.7.31.1211, thanks!
