### ISSUE TITLE
Allow defining a coordinate space for Scaler component

### ISSUE THREAD

**Issue by Coffee-Maker** [Neos-Metaverse/NeosPublic#2719]
### Is your tweak request related to a problem? Please describe.

I've been looking for a component that can scale an object to reach a target slot, similar to how the "Stretch To" object constraint works in Blender. I recently found the "Scalar" component which does scale a slot to the distance it is from another slot, but it fails to respect coordinate space.

### Describe what would you like tweaked

I'd like to see a field in the Scalar component that allows defining the coordinate space for the distance calculation.

### Describe alternatives you've considered

This could also be solved by adding an entirely self-contained component for scaling and rotating towards a target point, but it is less granular and therefore less applicable to other potential uses of the Scalar component.

### Additional context

[Example of application and demonstration of the issue](https://i.gyazo.com/d6af978593975b1ea4619058a78cddc6.mp4)

**Comment by Frooxius** [comment]
Added in 2021.7.31.1211, hope it works well! Thanks!
