### ISSUE TITLE
Add parent under user space button in inspector

### ISSUE THREAD

**Issue by Beaned2000** [Neos-Metaverse/NeosPublic#2720]
### Is your feature request related to a problem? Please describe.

Right now in the inspector for a slot there is only an option to parent items under the world root directly. more then often worlds have their own user management where people get sorted under their own slot. so then it would be handy if we had the option to parent an item under the local user space (the direct parent of your user root) of whoever clicked the button on the inspector.

### Relevant issues

none found

### Describe the solution you'd like

For an extra button to be added in the inspector that reparents the selected slot to your user space (the direct parent of your user root)

### Describe alternatives you've considered

N/A

**Comment by shadowpanther** [comment]
As an additional suggestion, make this button first and more prominent than parent under root to lead users to use their local space more (if different from root) instead of littering the world root.

**Comment by Frooxius** [comment]
Added in 2021.7.31.1211 along with some small reorganization. Thanks!
