### ISSUE TITLE
Unequip RawDataTooltips on tool change on Desktop

### ISSUE THREAD

**Issue by bombitmanbomb** [Neos-Metaverse/NeosPublic#2722]
### Is your tweak request related to a problem? Please describe.

In desktop mode tooltip development has some hazards, in that 1 wrong button or missing a input field and all your work is Gone.

### Describe what would you like tweaked

Add a Unequip Behavior when switching to a tool in Desktop mode if a RawDataTooltip is equipped

### Describe alternatives you've considered

Not testing any of my work in fear of accidentally deleting it all

**Comment by H3BO3** [comment]
We actually just found #2083 already exists. Closing this one as a duplicate
