### ISSUE TITLE
Desktop reticle does/doesn't change size based on FOV

### ISSUE THREAD

**Issue by Honzackcz** [Neos-Metaverse/NeosPublic#2724]
### Is your tweak request related to a problem? Please describe.

When changing FOV in desktop mode the reticle will become small with increased FOV and big with low FOV values.

### Describe what would you like tweaked

Desktop reticle should maintain relative size to screen/window when changing FOV.

### Describe alternatives you've considered

Cannot really think about any.

### Additional context

This is how the reticle looks like with FOV values 10; 60; 120.
![image](https://user-images.githubusercontent.com/76910833/127688534-a47ccb2e-e9b6-4993-97e1-cb586ce48ad1.png)
![image](https://user-images.githubusercontent.com/76910833/127688559-f1a8c841-13e3-457f-8e0c-ba4baf4e63ce.png)
![image](https://user-images.githubusercontent.com/76910833/127688574-f7804310-0f53-49b0-abec-dda9df207fbb.png)

**Comment by Frooxius** [comment]
The size is now consistent in 2021.7.31.1211, thanks for report!
