### ISSUE TITLE
Make Avatar Creator Hands a grabbable

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2727]
### Is your tweak request related to a problem? Please describe.

I'm always frustrated when moving the hands on the avatar creator in desktop mode as they are sliders and therefore don't adhere to the same behaviors as regular grabbables do.

### Describe what would you like tweaked

Make the hands on the default avatar creator grabbables instead of sliders.

### Describe alternatives you've considered

Having VR users position the hands for me.
Not doing this, which I don't see a reason for.

**Comment by Frooxius** [comment]
Unfortunately we can't make them grabbable, as that would break the Avatar Creator and some of its behaviors, which require them to stay within the hierarchy.

I'd recommend opening issue on the issues with sliders in desktop mode instead, as that seems to be an underlying issue here.
