### ISSUE TITLE
ValueMultiplexer(FloatQ) creates invalid quaternion values when a new value is added

### ISSUE THREAD

**Issue by Daniel-Luke-Taylor** [Neos-Metaverse/NeosPublic#2728]
### Describe the bug?

The valueMultiplexer(floatQ) component creates invalid [0,0,0,0] quaternions when a new value is initialised. 
This also happens with doubleQ.

### Relevant issues

N/A

### To Reproduce

Reproduction Steps:
1. Create a new valueMultiplexer(floatQ) component.
2. Click to add a new value and don't edit the value.

Steps to see the invalid value:
3. Output the value to somewhere, valuefield works fine.
4. Check the value from the valuefield with the logiX tip and the quaternion will be invalid. 

### Expected behavior

When a new value is added to the multiplexer it creates a valid quaternion. 

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.7.31.1211

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Additional context

If the value is changed manually once added this issue resolves itself. 

### Reporters

Axius#4743 , Shadow Panther#5154

**Comment by ukilop** [comment]
Relevant to #2087

**Comment by Frooxius** [comment]
Did a general change to make sure all fields initialize to proper value, otherwise there would be potentially hundreds of components exhibiting this issue. 

Should be fixed in 2021.8.2.936 as a result. Thanks for report!
