### ISSUE TITLE
[LogiX] Set MeshCollider

### ISSUE THREAD

**Issue by RobertBaruch** [Neos-Metaverse/NeosPublic#2729]
### Is your feature request related to a problem? Please describe.

I have hundreds of objects imported from a single Blender file. I can use the names of the meshes to determine which ones need to have their MeshColliders set to Static + CharacterCollider. I could manually go through several hundred objects and set their colliders, but I would rather be able to do this automatically through, say, LogiX.

### Describe the solution you'd like

A Set Mesh Collider node, with inputs:
* Impulse
* Slot
* Active (bool)
* Offset (float3)
* Type (MeshColliderType)
* CharacterCollider (bool)
* IgnoreRaycasts (bool)

Outputs:
* Impulse

This will look for the first MeshCollider component in the given Slot and set its parameters according to the inputs, except for the Mesh itself.

I think that being able to programmatically change the collider settings would be useful in other scenarios, such as a hidden passage wall that changes from impassable to passable.

### Describe alternatives you've considered

Manually wasting my time setting hundreds of objects to the right collider types, and hope that I don't make mistakes :>

### Additional context

Requester: Xekri

**Comment by Frooxius** [comment]
Thank you for the request, but we don't plan implementing this as a separate feature. This functionality will be implicitly provided by the LogiX Component Access: https://github.com/Neos-Metaverse/NeosPublic/issues/243

We generally avoid adding components for specific actions like this, as there are thousands of components and handling them this way wouldn't be manageable.

In the meanwhile I'd recommend trying out Plugins for automation of certain things - you can write a script to setup the environment the way you want, save the world and then open it on normal version of Neos.

While the documentation is a bit sparse, we have a sample Minecraft to Neos importer here that could serve as a reference: https://github.com/Neos-Metaverse/Minecraft2Neos
