### ISSUE TITLE
toggling your microphone using V in desktop

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#2732]
### Is your tweak request related to a problem? Please describe.

I want to talk with my microphone when using V

### Describe what would you like tweaked

I want to talk with my microphone when using V

### Describe alternatives you've considered

holding down V and not having it be toggled?

### Additional context

this is related to #320 
along with holding down V to talk
I would like to be able to also toggle it using v

**Comment by Frooxius** [comment]
I don't think this is suitable for "Press To Talk", as it usually seems to be used where you only talk while holding the key and having it toggle would require the person to remember the current state.

Better solution might be to add a keybind for switching the voice mode to another, including mute.

**Comment by epicEaston197** [comment]
I would before I believe went to have a toggle for it 
and I usually know when my microphone is muted
maybe added when you get to adding in the hud

**Comment by zkxs** [comment]
Possibly a duplicate of #2085?

**Comment by epicEaston197** [comment]
no it's not a duplicate

**Comment by epicEaston197** [comment]
instead of holding it down it will be a toggle

**Comment by epicEaston197** [comment]
the only thing that I find wrong with that is M to mute and not V

**Comment by shadowpanther** [comment]
#2085 is also asking for a toggle between mute and normal voice mode.
#320 was for push-to-talk (holding the button).
