### ISSUE TITLE
World property change event nodes

### ISSUE THREAD

**Issue by Gawdl3y** [Neos-Metaverse/NeosPublic#2734]
### Is your feature request related to a problem? Please describe.

When using most (any?) of the world property nodes (World Access Level, World Description, World Hide From Listing, etc.), they have to be coupled with an updating relay when using a Fire on True / Fire on False node on them. This isn't completely ideal since each updating relay introduces additional LogiX processing that has to happen on every update (from my understanding). The wastefulness of this is exacerbated by the fact that these kinds of properties change very infrequently.

### Relevant issues

#1523

### Describe the solution you'd like

Event nodes that fire whenever the corresponding world property is changed (On World Access Level Change, On World Description Change, etc.)

### Describe alternatives you've considered

Allowing the existing nodes to cooperate with the existing Fire on True/False/Change nodes without needing an updating relay (this would probably be more ideal/cleaner from a user standpoint, but my assumption (could be very wrong) is that this isn't as feasible to implement)

**Comment by LeDrascol** [comment]
Relevant issue: #1523

**Comment by Gawdl3y** [comment]
Ah, thanks. Guess my search was too specific. I'll leave the decision to close this in favour of that issue up to one of the staff members, as we technically do have two different implementation suggestions, I guess!?

**Comment by Zyzyl** [comment]
I'm not staff, but I'd suggest closing this one and commenting on the older issue with your alternative implementation idea. I'd also suggest giving a few example use cases to guide the Dev team as to how the node's might be used.

**Comment by Frooxius** [comment]
This isn't something we'd expose like that. If we add mechanism to track the changes for those, we'll hook it directly into this nodes, so they fire change events appropriately, instead of requiring every user to implement that themselves.
