### ISSUE TITLE
Sessions will appear in the World tab if there are sessions in the LAN even if they are hidden

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2741]
### Describe the bug?

If you have sessions in your LAN even if you have hidden them, they will appear in the World tab.

For example, you can build headless as Anyone,hiddenSession. In that case, when you launch the client in the same network and check the World tab, you will see only the list in the World tab (you can also join it by clicking on it at the right time).

### Relevant issues

idk.

### To Reproduce

You can set up headless in the same network with the same configuration as above, and start the client to access it at any time.

### Expected behavior

I want it to either not show up or only show up if I explicitly specify it in the custom

### Screenshots

![image](https://user-images.githubusercontent.com/6259214/128162531-15f629b3-5048-4e0a-863c-6432449527d2.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.8.2.936

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Additional context

Since it is a hiddenSession, I feel that it should not be shown in the World tab as it is supposed to be. If it is supposed to be shown, I would like it to be explicitly specified from "Custom" to show it.

### Reporters

kazu / kazu0617#7215

**Comment by shadowpanther** [comment]
hideFromPublicListing tells the headless to not register the session in the Neos Cloud, so it wouldn't be seen by other users.
What you see is how LAN networking works - clients in the same network discover each others' sessions without any external means. If you want to disable this, go to Settings and check "Disable LAN" there. That would make your client to not show other nearby clients' sessions.

**Comment by Enverex** [comment]
Beware of this issue if you do use the "Disable LAN" option - https://github.com/Neos-Metaverse/NeosPublic/issues/2749

**Comment by kazu0617** [comment]
> 
> 
> `hideFromPublicListing` tells the headless to not register the session in the Neos Cloud, so it wouldn't be seen by other users. What you see is how LAN networking works - clients in the same network discover each others' sessions without any external means. If you want to disable this, go to Settings and check "Disable LAN" there. That would make your client to not show other nearby clients' sessions.

Thay's correct. This one seems correctly. 360 viewing and Icon seems incorrect but i think np. i'll close it.
