### ISSUE TITLE
Set User Scale Node Locks Other Users In Place

### ISSUE THREAD

**Issue by Cataena** [Neos-Metaverse/NeosPublic#2745]
### Describe the bug?

When using the "set user scale" node, when used on a user that isn't you, it locks that user in place / rubber bands them to one location while the scaling is occurring. 

### Relevant issues

No

### To Reproduce

When using a set user scale node, have someone else send the pulse and you will be locked in place for the duration of the scaling.

### Expected behavior

We expect the user to be able to move while being scaled. 

### Screenshots

![20210805012411_1](https://user-images.githubusercontent.com/76889792/128297381-f02dcb0f-2c0a-418a-941d-dcc195dddeb8.jpg)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.8.2.936

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

http://cloudx.azurewebsites.net/open/world/U-Cataena/R-b847e4b6-5de1-4278-b8e0-d5a4357a9dfe

### Did this work before?

I Don't Know

### Reporters

@Shifty#7944 @Cataena#3067

**Comment by shiftyscales** [comment]
This is definitely a regression, and I believe likely one that would have come about around the time user's coordinates were switched to streaming in February.

It appears that this issue only occurs when a user sets the scale of any other user other than themself. A potential mitigation could be to migrate the impulse to the user who's size is to be adjusted?

**Comment by shiftyscales** [comment]
This issue appears to have recently been addressed by an update.
