### ISSUE TITLE
I want to be able to animate Dynamic bones

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#2752]
### Is your feature request related to a problem? Please describe.

at the moment it's really hard to animate any Dynamic bones you can really only animate the Root bone

### Relevant issues

you can't really animate Dynamic bones

### Describe the solution you'd like

I want to be able to animate Dynamic bones I want to be able to move the ear around and animated

### Describe alternatives you've considered

what I've done was anime only the bone with his kind of Stephen not too good
this does not look good compared to the images below
being able to animate Dynamic bones like the images below would be amazing
![image](https://user-images.githubusercontent.com/76523692/128614836-de9a5e8f-c562-47b4-b578-78c952506b52.png)

### Additional context

animating something like this would almost be impossible 
this makes it really difficult to actually animate the character right
a video demonstrating the Behavior
https://youtu.be/pt5p3ytbTTY
https://cdn.discordapp.com/attachments/730946706119852044/761571855492186112/unknown.png
![image](https://user-images.githubusercontent.com/76523692/128614710-6f841311-2d35-4b56-9210-93e47ded1518.png)
![image](https://user-images.githubusercontent.com/76523692/128614712-8ea676aa-5c71-4d62-b805-11b8dd96e4a6.png)
![image](https://user-images.githubusercontent.com/76523692/128614745-37074340-b627-41a8-9cab-08ce3b68a18e.png)

**Comment by H3BO3** [comment]
You can "animate" them though. Just drive the transform fields in the bone list, think it's originalrotation that would be the field you're looking for. If an interface doesn't work, you should be able to pull a drive node with the logix tip mode
