### ISSUE TITLE
Update the mentor signal in the MTC rooms

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2753]
### Is your feature request related to a problem? Please describe.

The mentor signal has had a few updates related to localization, better wording, and less failure modes.

If possible please re-integrate the panel using the current provided version.

### Describe the solution you'd like

Panel in the MTC worlds are replaced

### Describe alternatives you've considered

Leave it be or remove it, the first is less preferable, the latter is somewhat OK but may result in some new users not getting help.

**Comment by shadowpanther** [comment]
Mentor Signal was updated yesterday in all three public MTC worlds. I'm closing this for now, feel free to reopen when you release an updated version.
