### ISSUE TITLE
Have User Scale Logix and Components Respect World User Scale permissions

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2758]
### Is your feature request related to a problem? Please describe.

Currently, you can set a min/max scale for a user in the world permissions, how ever, this is only a soft lock as logix & DefaultAvatarScale can easily bypass it.

### Relevant issues

I couldn't find anything regarding this

### Describe the solution you'd like

For an option, a bool perhaps for simplicity to force the min/max scale. Similarly how its done with the Context Menu. Possibly tied to that same mechanism that doesn't allow you to scale using that?

### Describe alternatives you've considered

I guess waiting for "Hard Permissions" or something like that...

### Additional context

Context menu method is soft locked. Hard locking would work like this, but logix/DefaultAvatarScale can't bypass it
![image](https://user-images.githubusercontent.com/53165730/128646580-7fb1b3c9-869c-4311-9410-2851969bc2a7.png)

**Comment by H3BO3** [comment]
Wouldn't it be better just to make DefaultUserScale respect and be clamped by the world permissions? I don't see how this is related to hard permissions at all.

**Comment by AshtonSparx** [comment]
> Wouldn't it be better just to make DefaultUserScale and logix respect and be clamped by the world permissions? I don't see how this is related to hard permissions at all.

That's what I meant, have them respect it. x3

**Comment by H3BO3** [comment]
Perhaps you could change the title of your issue to reflect that better, I think it tripped me up. I would do it myself, but I can't anymore I guess. Second time today that it would have been beneficial.

Perhaps "Have User Scale Logix and Components Respect World User Scale permissions"?

**Comment by Frooxius** [comment]
In 2021.8.13.612 the world permissions should now be respected, thanks for report!
