### ISSUE TITLE
Wallet Logix

### ISSUE THREAD

**Issue by joshua-mir** [Neos-Metaverse/NeosPublic#2770]
### Is your feature request related to a problem? Please describe.

Giving Logix some access to the economy of Neos 

### Relevant issues

related to #145

### Describe the solution you'd like

 a simple logix node that fires an impulse on any balance change of a given user - would be an option for people to start building their own store-type interactions, cash-register style gadgets, and play shopkeeper, prior to a more robust in-game shop system.

### Describe alternatives you've considered

an alternative solution would be to have logix nodes that directly transfer/request token transfer between users [hopefully after some consent step! 😬] and then fire an impulse on success/rejection.

This would be much more powerful but also may create a vector for abuse compared to keeping transfers something users explicitly initiate themselves. 

### Additional context

potential privacy concerns if balances/transfers within Neos are intended to be private, which would potentially need some additional temporary consent mechanism for Logix to be able to access user profile information which sounds like a separate issue.

In order to create any shop/economic/trade system that is actually *safe* for users to use, there would probably also have to be some kind of "container" that can exist, receive tokens, and behave as a user for the purpose of this logix node - also sounds like a separate issue.

**Comment by shadowpanther** [comment]
There's already a TipJar component with a related Tip Jar Events LogiX node:
https://wiki.neos.com/Tip_Jar_Events_(LogiX_node)
Is there any extra functionality that this combination doesn't cover yet?

**Comment by joshua-mir** [comment]
no, you're right, I'm just new, closing this and the second issue I just made 😂

**Comment by shadowpanther** [comment]
> no, you're right, I'm just new, closing this and the second issue I just made 😂

Nothing wrong with being new, but try to run your ideas through #ideas channel of the Discord, you might get some pointers on whether this functionality is already implemented or planned, and somewhat gauge the community interest.
