### ISSUE TITLE
LogiX Event Node request: Emergency Respawn

### ISSUE THREAD

**Issue by win189** [Neos-Metaverse/NeosPublic#2774]
### Is your feature request related to a problem? Please describe.

i would like  a Node that would send an impulse if someone was to do the Emergency respawn

### Describe the solution you'd like

a node that would send a impulse if user dose emergancy respawn

### Describe alternatives you've considered

a 20 pluss node logics to dectect hands  movement and cause lag as it would check For EVERY one in world

**Comment by Electronus** [comment]
While this isn't Emergency respawn directly is IS any time a user spawns. 
![image](https://user-images.githubusercontent.com/64871170/129048106-7876a96e-0ad0-4898-889e-563b5569c920.png)

**Comment by shadowpanther** [comment]
@win189 what is your use-case and why the existing User Spawn node can't be used in it?
User can respawn via different means, it's not always the emergency gesture.

**Comment by kazu0617** [comment]
I agree with shadowpanther, it would be nice to make User Spawn catch Emagency Respawn as well.

**Comment by shadowpanther** [comment]
@kazu0617 what do you mean? User Spawn already catches every way of respawn. Emergency gesture is just another way to _trigger_ the respawn itself.

**Comment by kazu0617** [comment]
> 
> 
> @kazu0617 what do you mean? User Spawn already catches every way of respawn. Emergency gesture is just another way to _trigger_ the respawn itself.

Oh, it's true... what am I saying?
My comments are strange, so ignore them.

**Comment by win189** [comment]
@shadowpanther the use case is simple i would like to be able to create an event a ( stop All Logics ) type thing for someone who used emergency respawn as a sort of safety measure when doing silly things

**Comment by shadowpanther** [comment]
Can't you just do the same with the On Spawn node? That would _also_ catch respawning via Dash.

**Comment by win189** [comment]
that's not the goal of this Project imagine a maze and you stuck in a wall but because you cant grab or noclip or have build rights you would need to Spawn which would put you at the start
with this, i could make it where it grabs where the person is and put them within 10 meters of where they were in the center of the walkway  rather then Start from the Begining

**Comment by win189** [comment]
a simple way of thinking about it is on moded Minecraft were when you Die it leaves a Waypoint to were u died

**Comment by H3BO3** [comment]
Use the user template system to put an OnDestroying node with logix underneath each user, which before they get "killed" stores their current location into an external location, like into a UserValueOverride. You could also have the behavior modify itself depending on what's happening

**Comment by H3BO3** [comment]
Subsequently, when they respawn, you use the User Spawn node to read that location and do what it needs to with it, like move them to a certain spot

**Comment by shadowpanther** [comment]
So, you want to detect the _beginning_ of the emergency respawn gesture, not the actual respawn which happens after user's root slot was already deleted and recreated. That makes more sense, but also that is not what the emergency respawn is for.

I think what you intend to do is better handled by either:
- changing which spawn point the user would be spawned at
- detecting the gesture arbitrarily and using recently added Set <body part> Position/Rotation nodes to teleport the user to the safe spot instead of fully respawning them

**Comment by H3BO3** [comment]
Alternatively, you could use the user template system to inject a context menu option akin to "unstuck", which accomplishes your goal without having to respawn the user.

**Comment by win189** [comment]
NO, i want to Detect the emergency Respawn and the reason is not something i want to put on a public Github i appreciate the suggestions and sorry i cant go into more detail it is a node i find useful and is why i am requesting it

**Comment by shadowpanther** [comment]
Okay, I guess that's all the information we could get.
I still don't think that having a node literally like this is viable/possible, as the emergency respawn is (should be) handled outside of the worldspace and shouldn't be distinguishable from the other means of respawn, but let's see what the Devs think of this.

**Comment by win189** [comment]
upon consideration, i don't feel this would be in the best interest of the community
