### ISSUE TITLE
Exporting Mesh via Ref/Inspector Exports Export Dialogue Instead

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#2780]
### Describe the bug?

Trying to export a mesh via an inspector window, by grabbing the mesh itself, results in exporting the export dialogue window itself, not the grabbed mesh.

### Relevant issues

None found.

### To Reproduce

Grab a mesh via the inspector window via it's "Mesh Renderer" "Mesh:" slot, then try to export using the file dialogue.

### Expected behavior

For the grabbed mesh to export.

### Log Files

Nothing spotted that's relevant.

### Screenshots

Grabbing the mesh via the mesh slot. Keeping it grabbed while going to the File manager and hitting +.
![image](https://user-images.githubusercontent.com/958670/129233027-49fdce02-466d-4ee7-8a0f-00c3ab625861.png)

The result:
![image](https://user-images.githubusercontent.com/958670/129233080-3124c231-be5b-448f-9de1-55a42ac3a778.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.8.2.936

### What Platforms does this occur on?

Windows

### Did this work before?

No

### Additional context

This has been an issue for forever but I forgot to report it long ago.

### Reporters

Enverex#6528

**Comment by Frooxius** [comment]
Should be good in 2021.8.13.612, thanks for report!

**Comment by KyuubiYoru** [comment]
I have the same problem.
https://youtu.be/fJSCwVzrWWo

**Comment by Khosumi** [comment]
![image](https://user-images.githubusercontent.com/26034954/132760974-8dcccc75-8a49-40d1-b2d0-cf0cbe963aa6.png)
Still happening

**Comment by Enverex** [comment]
I was about to report this again. The original issue persists.

On desktop - drag the mesh ref with right mouse (as per the image in the initial post), keep it held down, go to file manager and click the green plus. You'll get an export dialogue for "Mesh" rather than the correct object. Exporting will export the export dialogue, not the held item.

Exporting by grabbing the SLOT instead of the REF works fine.

**Comment by Frooxius** [comment]
I see. This is actually a different issue when you're trying to export the MeshRenderer. The model exporter works at the level of objects, not individual components.

I'll have to see if I can extend it to support filtering and export only a single mesh like this, rather than the entire hierarchy.

**Comment by Frooxius** [comment]
I've extended the mesh exporting to support filtering specific components in 2021.9.13.981. This should now work properly. Thanks for report!
