### ISSUE TITLE
visual impairment badge not shown within session/user menu

### ISSUE THREAD

**Issue by Mysticporo** [Neos-Metaverse/NeosPublic#2782]
### Is your tweak request related to a problem? Please describe.

Yes, currently the Visuallyimpaired Badge doesn't show up within the session/user list which could lead to to user confusion/frustration as to why a user is having diffuculty trying to achieve a task that a person with 20/20 vision may find basic.

### Describe what would you like tweaked

Minor Tweak of adding the Visuallyimpaired badge to the session/user badge list.

### Describe alternatives you've considered

I'm unaware of any at current time of writing.

### Additional context

Although the Visuallyimpaired badge shows up when nametags are active, because you can turn off nametags there is no other way of telling if a user is Visuallyimpaired due to no badge visual being shown within the session/user list

**Comment by Frooxius** [comment]
This was changed in 2021.8.13.612 by @ProbablePrime! Thanks for the report!
