### ISSUE TITLE
Spawn Areas do not respect enabled/disabled state

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#2785]
### Describe the bug?

I was running this into my homeworld, I had the trouble of creating a "personal" spawn for the host, where I had a UVO where one spawn was disabled for me, but then another was active only for me.
I also tried to see if having Spawn Area weight driven or different would affect this but it would not

### Relevant issues

None that I could search and find

### To Reproduce

1. Set up a Spawn area with the value driven off for yourself
2. Set up a backup Spawn as Enabled
3. Respawn yourself, and recognize that the spawn area that is enabled still "works" and doesn't respect the driven value on weight or bool state.
 

### Expected behavior

It should check to see if a spawn is enabled or disabled, and choose the next spawn in the world that is available.

### Log Files

I did not have logs for this, but if need be I get them if need be. The issue was that easy to test I ran into it repeatedly.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Current

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

Turk

**Comment by Frooxius** [comment]
Fixed in 2021.8.13.612, thanks for report!
