### ISSUE TITLE
Smooth Lerp should not be frame rate dependent

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#2787]
### Is your tweak request related to a problem? Please describe.

the problem is if I'm running at a low framerate Smooth Lerps do not function as attended they go twice as fast or they transition immediately causing my emotes to be really Snappy and fast when they are supposed to be smooth

### Describe what would you like tweaked

Smooth Lerp should be smooth at any frame rate within reason 

### Describe alternatives you've considered

*no response*

### Additional context

here's a video demonstrating what I'm talking about
https://www.youtube.com/watch?v=RYiwfmJBlsw

**Comment by H3BO3** [comment]
Smooth lerps compensate for frametime so the transition ends up happening in the same amount of time. If this change were to be made, at lower framerates, your ears would take a long time to transition even if it was smoother.

It's possible that the low framerates could be affecting the dynamic bone simulation as well, that issue has been observed many times, and it is documented at #1790 .

I doubt the fundamental behavior of this node and the associated components that use the same algorithm will be changed. Algorithms like this in games are not framerate-dependent for good reason.
