### ISSUE TITLE
LogiX node: Self

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2790]
### Is your feature request related to a problem? Please describe.

A lot of LogiX setups require to get the active user of an object LogiX is packed on. The LogiX itself could be even transferrable (not require any connections to be reestablished outside of the packing root). The only way to get the active user would be to make a reference to the packing root slot itself and `Get Active User` of that.

### Describe the solution you'd like

A new node `Self` or `Self Slot` or `Get Self` that would return the node's own slot, that could be fed into `Get Active User`, `Get Parent`, `Get Object Root`, etc.

### Describe alternatives you've considered

Pulling out a slot ref for each case like this.

**Comment by PointerOffset** [comment]
I've lost count of the number of times I've had to take a Get Active User node and point the ref at itself for a portable bit of avatar LogiX.

I would love to see either a "Get Active User Self" node or a default behavior on "Get Active User" that references itself unless a ref is specified.

**Comment by AshtonSparx** [comment]
I just have a get active user that references itself x3 I even have it "Prefabed" in my logix folder where they're glued together xD

**Comment by TehTurk** [comment]
Local User kind of works in this way, and usually if there is an active setup there is always getting the Ref's active user which does the same effect. I'm not sure if I follow the need for this node.

**Comment by shadowpanther** [comment]
@TehTurk not at all. Local user always returns the evaluating user for every evaluating user/client. My request is for the node that always returns its slot to get the active user of that slot, which would be the same for every evaluating user.

The need is the pattern that I always have to do with the ref arrow to the packing root slot and Get Active User. Having a node that just returns its own slot would allow to get the same result without setting up the ref arrow. I'm asking for something similar to the `self` object found in some OOP languages.

Ashton's solution would work, but looks like a hack, which _might_ break in some circumstances.

**Comment by TehTurk** [comment]
It does, but typically you can make flows that where it kinda runs on the user themselves typically and only check for that active user as well. Hm I see the potential for it and am game for it, it's just more making sure we "need" the node as well too. 
Maybe there could be an easier way to generate the Ref of an object your holding instead, (Maybe like Grab Logix Node, hit Secondary, it makes the interface) that does similar function but also gives more option too. Regardless can't wait to see what is said for this.

**Comment by ProbablePrime** [comment]
This node is totally possible and follows the paradigms of other nodes. 

I dont think "Gripping" has much to deal with it. Everyone is asking for a node that gets the active user of whatever the object is parented to. This is found in avatars, objects, hats etc all sorts of stuff.

The "Self" node idea is a good one but im not sure if its better to just make things like Get Active User default to "Self" if there's no input. etc.

I'll ask Froox what he thinks and take a look.

**Comment by ukilop** [comment]
> The "Self" node idea is a good one but im not sure if its better to just make things like Get Active User default to "Self" if there's no input. etc.

You mean like the Write Dyn Var node does? :V

**Comment by shadowpanther** [comment]
@ProbablePrime in addition to `Get Active User` defaulting to self, the separate node could be used with `Get Parent Slot`, `Get Object Root` and maybe others.

**Comment by ProbablePrime** [comment]
Yeah Both approaches are quite valid.

**Comment by Earthmark** [comment]
I feel the gripping will be the same behavior we have in DynamicVariableInput and DynamicImpulseReciever, where both of them also rely on the node's slot position (although they are the only two that rely on this right now, this would be the third node to do so to my knowledge).

But this would save a lot of time when doing emote systems, almost all of an emote system can be built logix only, accept for blendshape drives and the active user ref. I know quite a few users avoid the active user ref but this would make it really easy to test with.
With this you could even test blendshape systems by placing the node on your toolshelf while testing, then when testing is done pack it into the avatar and everything is happy!

**Comment by TehTurk** [comment]
Hmm gripping may be not ideal, it was more so a way to placate this but I'm liking more the line of *defaults to self* if nothing is connected. Only question is that might break existing setups as null checks are a thing for some nodes still Apologies on the earlier comment too, I was more sure trying to follow the reasoning behind it. I can't wait to see what's said :)

**Comment by Frooxius** [comment]
Hmm I feel it might be better if we add node that's specifically "The user this node is under". So essentially "GetActiveUserOfThisNode" more or less.

I'm a bit wary on exposing the self Slot, because with certain planned things this might produce a misleading output - e.g. when nodes all get packed onto a single Slot, or become part of a shared "definition" when we get official LogiX functions, so it might lead to some design patterns that would break.

Would this work well enough for you?

**Comment by ProbablePrime** [comment]
That makes a lot of sense. Happy to get it sorted :)

**Comment by shadowpanther** [comment]
@Frooxius yes, for most of my setups, Get Active User Of This Node would work. Parents and object roots I don't use much, that was just an attempt to rationalize the existence of a more general Self node.

**Comment by ProbablePrime** [comment]
`Get Active User Self` is now implemented. I'll get it into testing and review soon. 

No promises yet.

**Comment by Frooxius** [comment]
This has been added by 2021.9.1.643 in ProbablePrime, thanks for request!

**Comment by ProbablePrime** [comment]
This shouldn't have been closed, it requests multiple nodes of which one is the only one created. Re-opening.
