### ISSUE TITLE
Materials fail to load offline

### ISSUE THREAD

**Issue by EIA485** [Neos-Metaverse/NeosPublic#2797]
### Describe the bug?

when starting neos without a internet connection everything is checkerboard

### Relevant issues

none

### To Reproduce

disconnect from the internet then open neos, observe that everything is checkerboard

### Expected behavior

i expected all materials to load normally, this was the previous behavior before a recent update.

### Screenshots

![offline mat](https://user-images.githubusercontent.com/17285570/129460045-b6322820-bbea-4d48-8749-fccc6364286d.PNG)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.8.14.443

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### Did this work before?

Yes

### If it worked before, on which build?

2021.8.2.936

### Reporters

seif1#6014
art0007i#2305
sls#6766

**Comment by 3x1t-5tyl3** [comment]
Seems to be related to a recent security fix?
https://discord.com/channels/402159838827905024/469131434628612116/875492839914614884
"- Added guard against changing shader URL to an unofficial 3rd party variant to prevent content breakage and potential security issues"

**Comment by Frooxius** [comment]
Yes. We'll need to add caching of the validation info.

**Comment by Frooxius** [comment]
This is fixed in 2021.8.18.1077, thanks for the report!

**Comment by kazu0617** [comment]
This bug regression ㏌ Current Build, 2021.8.14.443
