### ISSUE TITLE
In IK Hips get bound to a fake Root bone instead of a child Pelvis bone in avatar

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2800]
### Describe the bug?

An avatar had an extra bone named 'Root' as a parent of their 'Pelvis' bone, where that 'Root' bone was between their feet. However, the IK bound that 'Root' bone to the pelvis slot, instead of the pelvis.
Their avatar walked just fine, but they were also a haptics user, and their chest haptics extended from between their feet up to their neck, which does not correspond to human chest anatomy.

### Relevant issues

#2025
#2029
Any issue that asks about bone naming conventions

### To Reproduce

Have an avatar with an extra bone as a parent of Pelvis called Root, see the IK system bind to Root instead of Pelvis.

I may be able to get a representation of the avatar if needed, the user was importing an exotic pirate and getting a copy may require additional steps.

The avatar structure, sadly some names are guesses cause I didn't write them down at the time.
```
CenteredRoot
  Meshes
  Root
    Pelvis
      Spine
      Left Leg
      Right Leg
```

### Expected behavior

The 'root' slot between the feet is skipped, and the pelvis that has two legs and a spine is used instead.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

No

### Neos Version Number

2021.8.14.443

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Additional context

I ran into this from a user, unsure on the actual replication status of this.
This may require additional validation as to if the bone name is the actual root cause.

### Reporters

Earthmark
Cap'nCurly

**Comment by Frooxius** [comment]
Can you send me sample avatar for this? I need to check how are the bones actually mapped to the geometry on it and test what the heuristics does on this.

The chest haptics sounds like normal behavior, the TorsoHapticPointMapper should cover the entire spine, from the bottom up to the neck.

**Comment by Earthmark** [comment]
I don't have the model for this, I think I'll close this for now unless I find another model showing this behavior.
