### ISSUE TITLE
Neos Translation File User Provided Label  Format

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2823]
### What topic do you want to discuss?

During discussions in Discord it was brought up that under some conditions user made tools can have their translation strings in the [neos translation files](https://github.com/Neos-Metaverse/NeosLocale) instead of needing a custom internal translation system, and without waiting for custom locale files.

The mentor signal was one such acceptable tool, so the migration of the translations from the custom system it currently uses is underway, however there are some questions around what format to use for the translation string labels. 

### Goal of discussion

Decide on a format for translation labels for user generated content in the neos core translation file.

### Discussion:

During conversations with @shadowpanther in the [Earthenworks Discord](https://discord.gg/qcqyYj9a) related to the mentor signal and translation toolkit precursor it currently uses, I proposed a general format of `<owning entity>.<object name>.<contextual path in object>`, also describable as `<who made it>.<What is it>.<Where in it>`.

This provides the link to the Neos team about who 'owns' the string, and gives translators context they can use to find the string they are translating in the target object.

For example, `G-Earthenworks.MentorSignal.Title.Intro`, The group Earthenworks is responsible for changes to the base string, the mentor signal is the entity the group manages, and the string is the title string on the intro page.

This format seemed acceptable, however some questions arose around the first tag.

User ids such as `U-Earthmark` or `G-Earthenworks` would be viable identifiers for myself or the Earthenworks group, but it's not viable for accounts that use non English character names and get assigned a UUID as a user ID, they appear similar to `U-123e4567-e89b-12d3-a456-426614174000` to my knowledge.

We both kinda fell onto that Froox should be asked as getting translations into that file is a very kind offer by him. I think this may be a good place to formally ask, and if nothing else other people may have feedback for this name pattern.

So, I am curious if others have proposals for the first tag, or have suggestions for alternate formats that still provide an ownership link and info on what the string means! Perhaps the identifier is case by case, and just try to give strongest name you can within a reasonable character limit?

**Comment by ProbablePrime** [comment]
I'm not sure that the plan here is to continue to do this. We're doing it for select impactful projects such as the Mentor Signal and the MMC but I don't think we have plans to roll this out any further than that. 

If we did I'm not sure that It would be at a sufficient quantity to warrant this kind of structure. 

As you've mentioned the custom locale files I wanted to link the GHs for it to aid in discussion.
- #1044 
- #1715

**Comment by Earthmark** [comment]
Yes this was discussed in the context of tools that are very  common to Neos, for instance I could imagine tools in Neos Essentials that are use made being included.

I plan to make a toolkit for loading custom translation files for less public objects, but this discussion is specific to the neos core files.

**Comment by Earthmark** [comment]
If this is truly that special case, then I'll consider what format to use, this can just be prefixed with mentor signal if that's all that's needed.

This just means I'll need to work on the toolkit sooner than later, as I had a request to translate the user made tutorial world yesterday and plan to do that, but it'll be toolkit based then instead of through the formal translation system.
