### ISSUE TITLE
Labeller tool's labels should be usable/packable onto LogiX

### ISSUE THREAD

**Issue by The-Honeybee** [Neos-Metaverse/NeosPublic#2830]
### Is your feature request related to a problem? Please describe.

Frequently there comes a time where a system is built... "Differently". If someone is to then forget about the project or turn it towards another person. Without any guidance it can frequently be extremely difficult.

I also suffer from extremely weak memory, and can easily forget my solutions and have to dissect my work only to get lost and overwhelmed.

Currently, although there are methods available to labelling or posting comments onto Logix, these are usually unintuitive, or at least unsatisfying to do, one I am aware of is trying to tie string nodes into works.

### Describe the solution you'd like

If the Labeling tool was able to attach and post comments that would then package onto LogiX, in my own opinion would be the easiest solution to this issue.

### Describe alternatives you've considered

I've also considered that a LogiX rework could be done that would add a feature to the LogiX or it's tooltip then allowing commenting.

**Comment by ProbablePrime** [comment]
Thanks for your suggestion! I'm not quite sure the labeler tip is the correct move here though. Its a really old system and isn't currently compatible with any of the logix based systems. 

Based on: https://github.com/Neos-Metaverse/NeosPublic/projects/15#card-61392773 , We have plans to have our own commentary system that's more like #1662 than the labeler tip. 

I think, I'll unfortunately be closing this one in favour of #1662 and then I'll link #1662 to the card.
