### ISSUE TITLE
Pass through Desktop User Inputs to Standard Controller

### ISSUE THREAD

**Issue by H3BO3** [Neos-Metaverse/NeosPublic#2839]
### Is your tweak request related to a problem? Please describe.

I have some creations that utilize a Grabbable to hold and use them instead of a RawDataTooltip. They pass the Active User to a Standard Controller node. Desktop users cannot use these creations.

### Describe what would you like tweaked

Pass compatible interactions from desktop users through the Standard Controller node, such as Primary, Secondary, Grab, and Menu. Strength could be switched from 0-1 based on the state of Primary, perhaps? Maybe the remaining outputs could be mapped in the future as well.

### Describe alternatives you've considered

A new "Desktop Input" logix node that would provide the aforementioned booleans directly. This is less ideal since previous creations would have to be upgraded, though it would be simple to integrate into new projects.

### Additional context

#2786 may be related. I'm not sure if inputs were passed through before. If that is the case, I may be experiencing the same issue.

**Comment by Frooxius** [comment]
This has been implemented a while ago, Neos creates a virtual controller that feeds the Standard Controller data. I've used a number of items that work thanks to this feature.

Does this not work for you? Can you reproduce it in isolation with a simple setup?

**Comment by H3BO3** [comment]
Alright, just tested and now all of a sudden everything is working. I'll keep an eye out for similar behaviors cropping up.
