### ISSUE TITLE
ValueRegister`1 with self driven

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2847]
### Is your feature request related to a problem? Please describe.

No, not particularly. I just thought it would be convenient to have.

### Describe the solution you'd like

To hold values that don't need to be shared across the network, we now need to create a ValueRegister, add another ValueCopy using the inspector, enable WriteBack, and specify _Value as the Target and Source.
Since the Variables section is now very clean, I thought it would be useful to have a ValueRegister that does this from the beginning if possible.

### Describe alternatives you've considered

Perform the above process. If the solution is other than retrieving a pre-made one, you may need to use a plugin as retrieving the Inspector value is a bit difficult without a plugin.

### Additional context

It's not that high a priority. I just want to see if I can make a process that is currently possible easier. (･ω･

**Comment by shadowpanther** [comment]
This would be covered by local-only LogiX data.
See [the roadmap card](https://github.com/Neos-Metaverse/NeosPublic/projects/15#card-61393175) for more info.

**Comment by kazu0617** [comment]
oof sorry.
