### ISSUE TITLE
After the BEPU2 update, the number of frames required to duplicate DynamicVariableSpace has increased to 3.

### ISSUE THREAD

**Issue by orange3134** [Neos-Metaverse/NeosPublic#2860]
### Describe the bug?

In previous versions (2021.8.18.1077), after duplicating a Slot with DynamicVariableSpace attached, a delay of 2 frames was required before DynamicVariable became writable.
In the current version (2021.8.25.1127) this is now 3 frames.

This issue does not occur under some conditions. As far as I can see, when I physically touch the UIX Button, when I am using the Neos Button.

This seems to break many items and worlds that use Dynamic Variables and duplicates.
As far as I can see, "Neos Fishing", "曲射! Curving Bullets" and "Code: Null [RogueLikeShooting]" are broken.

### Relevant issues

No

### To Reproduce

1. Prepare a slot to be duplicated that contains a DynamicVariableSpace and one or more DynamicValueVariables.
2. Create a UIX button.
3. Create LogiX. Duplicates 1. when the button is pressed and writes Dynamic Variable after 2 frames.
(The entire LogiX is included in the attached video.)

4. If you use the laser to press a button, the write will fail.
5. If you press the button directly with your finger, the writing will be successful.

### Expected behavior

The value should be written correctly.

### Screenshots

https://youtu.be/11aAARAezxQ

The public folder containing the items shown in the video is attached below.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.8.25.1127

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

neosrec:///U-orange/R-ae98e019-8541-4674-8753-4938fbd4e699

### Did this work before?

Yes

### If it worked before, on which build?

2021.8.18.1077

### Reporters

orange, rhenium, yoshi1123_

**Comment by ukilop** [comment]
this still exists btw, seems to only show up when doing heavier operations tho, simple testing for this bug it doesnt appear
