### ISSUE TITLE
Zero width space cannot be used in place of space

### ISSUE THREAD

**Issue by Aesc3625** [Neos-Metaverse/NeosPublic#2868]
### Describe the bug?

This Issue #2846 added zero-width space for translation purposes. However, in Facet and almost all UIs, a normal space will break a line, but a zero-width space will not give the expected behavior.

### Relevant issues

[Zero width space is not respected in text rendering #2846](https://github.com/Neos-Metaverse/NeosPublic/issues/2846)

### To Reproduce

Use zero-width spaces in Facet, Dialog, and UIs.

### Expected behavior

Zero-width spaces can be used for line breaks, etc., just like normal spaces.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.8.27.199

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

**Comment by Earthmark** [comment]
It turns out unchecking the text box horizonal auto size allows the zero width space to break more freely. Try with that check box unchecked?

**Comment by Frooxius** [comment]
@Earthmark That's a good find, the horizontal auto-size wasn't aware of the zero-width space when measuring the longest word size. I've got a fix coming.

**Comment by Frooxius** [comment]
Released fix in 2021.9.8.946, should wrap correctly now even with Horizontal Auto Size. Let me know if you run into any more issues, thank you for the report!
