### ISSUE TITLE
CharacterForceField only works with trigger colliders

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2891]
### Describe the bug?

Observed by Green (KHZard# 1983), the trampoline in the Neos Essentials > Gadgets folder no longer functions.

In testing it I found that if I switched the collider on the slot of the CharacterForceField component to trigger it would activate, but otherwise, any other collider type, even active wouldn't function with this component, regardless of the value of the triggers only setting (which in this context was set to false, presumably supposed to be allowing other collider types.)

### Relevant issues

None I am aware of.

### To Reproduce

- Spawn the trampoline from Neos Essentials > Gadgets
- Attempt to jump on it

### Expected behavior

The existing behavior of bepuv1 is maintained and the CharacterForceField applies the force.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.8.27.914

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

Pre-bepuv2

### Additional context

Discovered when Green spawned out and tried to jump on the trampoline.

### Reporters

Shifty, Green (KHZard# 1983)

**Comment by Frooxius** [comment]
Fixed in 2021.8.29.1240, thanks for report!
