### ISSUE TITLE
Hard Volume Limit on Audio Output component

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2894]
### Is your tweak request related to a problem? Please describe.

I would like the `Audio Output` component to have a component level max volume limit. Recently, started noticing a small influx of old & new items surfacing that intentionally super over drives the volume so loud, that, unless you have your sound effects (or what ever they're set to) 0, it'll blast your ears causing headaches because "Ha ha loud = funny"

### Describe what would you like tweaked

For the `Audio Output` component to have a max volume of 1. 

There's zero need to exceed that, as you start to override the local user's settings. Any existing items that exceed 1, be forced down to 1. If there is a use case to override the user's volume settings. I'm all ears.. no pun intended.

### Describe alternatives you've considered

I currently have no other solutions to this problem.

### Additional context

There's a "Leek" item roaming around that flings the user and **_BLASTS_** the user's ears with a **_WHACK_** sound, people starting to make bass boosted guns with super loud audio that obviously exceeds 1, ect.

**Comment by Frooxius** [comment]
Added this in 2021.8.29.1240. The clamp was happening after the user settings volume was applied, so this change just makes it happen before, so it can't exceed that. Thanks for report!
