### ISSUE TITLE
Video Playback Position is Desynced Between Users on Headless Servers

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#2895]
### Describe the bug?

When playing back a video, users appear to become further and further desynced from each other to the point where the drift can be literal minutes. The longer the video, the more obvious this can become due to the added potential for drift due to the playback duration.

Pausing the video and resuming it causes all uses to be resynced at least at that moment, though they then appear to start drifting again at "some point".

I've observed this using my own complex video setups and simple "pasted in video URL" scenarios.

### Relevant issues

None found.

### To Reproduce

This is the hard part given that the desync is seemingly random. The best way would be to spawn in a long video with a dozen or so people watching. I'd also have some people join and leave throughout to cause Neos to "stutter" and struggle which often desyncs things normally more than they naturally drift.

### Expected behavior

For everyone to say closely synced (with the understandable exception of latency and perhaps the buffer which currently Neos can't do much about).

### Log Files

None appear relevant. Can be provided on request.

### How often does it happen?

Sometimes

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.8.27.914

### What Platforms does this occur on?

Linux

### Did this work before?

I Don't Know

### Additional context

I've marked this as Linux as it's a Linux headless, I'd assume it affects Windows headless too but can't be sure as I can't test that setup.

### Reporters

Enverex#6528 Jolts#6767

**Comment by Frooxius** [comment]
I've pushed a fix to the master clock not being synced in 2021.8.29.1240 which should fix this! Reopen if there are still issues. Thanks for report!
