### ISSUE TITLE
Is Character On Ground now requires an updating relay for drive nodes

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2896]
### Describe the bug?

The node Is character On Ground now requires an updating relay since the bepu2 update.
This apparently broke the glide systems used by some flight systems.

### Relevant issues

None found

### To Reproduce

Create this circuit:
![image](https://user-images.githubusercontent.com/1251609/131273184-c4449f09-0ea6-4cd2-96cc-2235b118a2d2.png)

See that if you jump or go to fly, the upper node doesn't update but the lower node does.

### Expected behavior

Is Character On Ground notifies when the character goes to or leaves the ground.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.8.29.1240

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### If it worked before, on which build?

The parent system worked before the BEPU2 update, I can't see those versions so I can not verify.

### Additional context

Apparently this worked before as the previously working glide circuit used this an in put to a FireWhileTrue, and that does not work with the current update.

There seems to be other issues with the system currently as well, but this is at least one such issue.

### Reporters

Earthmark
Hopolis

**Comment by Frooxius** [comment]
Fixed this in 2021.9.1.643, hopefully it fixes those existing systems. Thank you for the report, let me know if you find any more trouble!
