### ISSUE TITLE
Procedural texture baking fails

### ISSUE THREAD

**Issue by DanteTucker** [Neos-Metaverse/NeosPublic#2899]
### Describe the bug?

When baking a procedural texture, it throws an exception and never completes.

### Relevant issues

N/A

### To Reproduce

1. Create empty object
2. Add SimplexTexture component.
3. Press the bake button at the bottom of the component.

### Expected behavior

Delicious Baked Goodness

### Log Files

[DESKTOP-08NL58O - 2021.8.29.1240 - 2021-08-30 02_49_48.log](https://github.com/Neos-Metaverse/NeosPublic/files/7074778/DESKTOP-08NL58O.-.2021.8.29.1240.-.2021-08-30.02_49_48.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.8.29.1240

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### Reporters

Dante, Snooper

**Comment by Frooxius** [comment]
Fixed in 2021.9.1.643! This was due to the texture not being referenced by anything and thus not loaded. Thanks for report!
