### ISSUE TITLE
LogiX Nodes for sampling 3D Textures

### ISSUE THREAD

**Issue by MR-Alex42** [Neos-Metaverse/NeosPublic#2902]
### Is your feature request related to a problem? Please describe.

I want to encode 3D spatial information into texture data and use if for my own logic.

### Describe the solution you'd like

LogiX Nodes for sampling 3D Textures.

### Describe alternatives you've considered

Implementing a function that takes (x,y,z) as input and outputs a color value.

**Comment by Frooxius** [comment]
Added this in 2021.9.2.676, thanks for request!
