### ISSUE TITLE
Cloud Variables should update immediately between user and worldspace when the variable owner is focused in the world.

### ISSUE THREAD

**Issue by seif1** [Neos-Metaverse/NeosPublic#2905]
### Is your tweak request related to a problem? Please describe.

When changing a CloudVariable in worldspace, or userspace when you are the value owner, unless you are the world host, it still takes a long time for that change to sync to the world.

### Describe what would you like tweaked

The immediate change should apply regardless of if you are the world host, at least as long as you are the owner of the value being changed, and are the one changing it, though preferably it does not need to be the value owner changing it, as long as they are focused in the world.

### Describe alternatives you've considered

Wait for the delay between value change, and update, or wait for the proposed faster update's if cloudvar changes use SignalR

**Comment by shadowpanther** [comment]
As far as I know, Cloud Vars are already syncing between userspace and worldspace. The only delay that I know of is when you update the value through the bot message.

What combination of components did you see this delay with?

**Comment by seif1** [comment]
I am rarely the host of the world, which is when the delay occurs, if you are the host, and the value is updated, it updates into/from your userspace immediately, but if you are not the host, there is the usual cloud variable delay in every case I have worked with (the component set to "onOwnerChange" iirc), I have not done much with the Logix nodes that set/read the value, I usually use the component form

**Comment by shadowpanther** [comment]
Hmm, I use a bunch of cloud vars that I toggle from my dash and that controls the visuals on my avatar. I never had anyone tell me that what I'm switching is not updating, and I usually don't host sessions. So from my experience it all works in sync.

**Comment by shiftyscales** [comment]
Full real time sync of cloud variables is planned, but requires they be transitioned to SignalR.
> This week we have briefly shifted focus from BEPUv2 integration to integrating the SignalR push notification service for our messaging system and other cloud optimizations to improve responsiveness and fix a number of issues, such as message history not loading for certain users.
> 
> Thanks to this new system, the load on the cloud infrastructure has significantly dropped. This should keep the cloud responsive even during busy days with lots of people on and keep scaling as the community keeps growing.
> 
> It also opens up doors for new upcoming features and abilities, like full real time sync for cloud variables, cloud impulses and optimizing other parts of the cloud infrastructure. We also used it to improve security of the moderation system, ensuring that any account restrictions take immediate effect.
> 
> Security and moderation have received some more improvements as well, preventing some cases of ban evasion. You can now also restrict the in-game File Browser to only specific locations, or none at all.

https://canary.discord.com/channels/402159838827905024/439421931830378506/863212163065708574

https://steamcommunity.com/games/neos/announcements/detail/2959411493204454822

**Comment by seif1** [comment]
Yea, I remember the transition being mentioned, guess I will close this issue since that would essentially solve this problem as well.

Thank you both.
