### ISSUE TITLE
Restoring Old Functionality of Inspectors

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2907]
### Is your tweak request related to a problem? Please describe.

Before the desktop overhaul, you used to be able to open the inspector of anything you're looking by pressing I. Which was super useful for quickly opening inspectors.

### Describe what would you like tweaked

I would LOVE for this to return but only when you have a devtip equip. Currently, it already opens the inspector by pressing I. But it only opens one on root, not what you're looking at. 

For a TLDR: `I want, when you have the devtip equip, pressing I auto opens the inspector or what ever you're looking at. Like old desktop mode used to.

### Describe alternatives you've considered

Being able to do it without a devip, if you have permissions to. Either works.

**Comment by Frooxius** [comment]
This has already been asked, but we do not plan on restoring functionality of the legacy desktop mode, as it was never properly supported and used a lot of hacks to achieve its functionality. The new desktop uses unified code so the approach works more or less the same. https://github.com/Neos-Metaverse/NeosPublic/issues/2168
