### ISSUE TITLE
Mathematical function evaluation node or component

### ISSUE THREAD

**Issue by TheBasementNerd** [Neos-Metaverse/NeosPublic#2908]
### Is your feature request related to a problem? Please describe.

It is difficult to build, read, or implement complex mathematical equations with logix

### Describe the solution you'd like

A logix node or a component that can be given an multitude of inputs which each correspond to a variable the equation will use, and a text field into which mathematical functions can be typed in a method similar to how most programming languages handle math (i.e. pow(sqrt(2/x), 4)) in order to create more readable, compact, and reusable equations that can assist in evaluating more complex functions and potentially be input directly into math based elements like procedural meshes, to create our own repeatable and complex objects that aren't attainable through current methods

### Describe alternatives you've considered

I do not consider there to be any alternative available

**Comment by ProbablePrime** [comment]
Thanks for your suggestion, based on the conversation and discussion in #1571 I will be closing this as a duplicate.

Please take your suggestions and ideas to #1571

**Comment by Earthmark** [comment]
While I think this is strongly related, this does seem like a different request than the linked duplicate.

The math language used certainly would be probably the same here, but from my perspective this is a different application of that not yet defined language.

**Comment by Earthmark** [comment]
In the past the jp community had a tool that would create a LogiX circuit that represented a provided equation, dunno where that tool went though.

I would like easy to write math equations, as that would remove a lot of visual noise in math heavy LogiX circuits.
