### ISSUE TITLE
Change DualSided when the photo appears

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2918]
### Is your tweak request related to a problem? Please describe.

この問題が修正されないことで、インポートされた画像やNeosでとった写真が片面からしか持つことができないという問題があります。特に集合写真を撮った後、持つときに非常に面倒です。

This problem is not fixed, which means that imported images and photos taken with Neos can only be held from one side. This is very troublesome, especially after taking a group photo.

### Describe what would you like tweaked

MeshColiderについて、今回のビルドからFrontのみになりましたが、これにより集合写真を撮るときや、画像をインポートしたときに持つことができなくなりました。写真が出現されるときにはDualSidedにしてほしいです。

Regarding MeshColider, it is now only Front from this build, but this makes it impossible to have it when taking a group photo or importing images. This makes it impossible to hold it when taking a group photo or importing an image. I would like it to be DualSided when a photo appears.

### Describe alternatives you've considered

少なくとも公式で出来る方法で出来る代替手段は見つかりませんでした。
I couldn't find an alternative way to do it, at least not in the official way.

### Additional context

This story was given to me by aesc, and I made it after checking it myself. please include aesc when you put it on neos-updates.

**Comment by Earthmark** [comment]
I was in a world where this came up, one additional suggestion was to make the picture a very thin box collider.

**Comment by Frooxius** [comment]
This was fixed up in 2021.9.3.1281! I've changed the photos and images to box collider instead, which should be better performance wide, especially when there's lots of pictures. Thank you for the report!
