### ISSUE TITLE
dynamic bones resulting in crash

### ISSUE THREAD

**Issue by jeanahelver** [Neos-Metaverse/NeosPublic#2919]
### Describe the bug?

game suddenly hard crashes, without crash reporter.

### Relevant issues

happening to other people in sesion but never at the same time.

### To Reproduce

seems to happen randomly

### Expected behavior

nothing.

### Log Files

[DESKTOP-AIKB2GG_-_2021.9.2.676_-_2021-09-02_18_56_11.log.txt](https://github.com/Neos-Metaverse/NeosPublic/files/7101560/DESKTOP-AIKB2GG_-_2021.9.2.676_-_2021-09-02_18_56_11.log.txt)

### How often does it happen?

Sometimes

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.2.676

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

**Comment by SnooperXP** [comment]
Could be related to the already reported issue #2913

**Comment by Frooxius** [comment]
Do you have the Player.log from such crash? I see some exceptions in the log, but they don't seem like they would be the actual cause of the crash.

**Comment by jeanahelver** [comment]
there seem to be no crash logs for any of these. it seems to not create them at all

**Comment by Frooxius** [comment]
Player.log is created and updated continuously at startup regardless of the crash. Here are the instructions how to find it: https://wiki.neos.com/index.php?title=Frequently_Asked_Questions#Player.log_Files

**Comment by jeanahelver** [comment]
[DESKTOP-AIKB2GG - 2021.9.2.676 - 2021-09-03 10_20_14.log](https://github.com/Neos-Metaverse/NeosPublic/files/7104484/DESKTOP-AIKB2GG.-.2021.9.2.676.-.2021-09-03.10_20_14.log)
[Player.log](https://github.com/Neos-Metaverse/NeosPublic/files/7104495/Player.log)

**Comment by Frooxius** [comment]
I've made bugfixes in 2021.9.3.1281, hopefully they help. Please reopen if you still experience issues. Thanks for report!
