### ISSUE TITLE
Animator breaking when used with DynamicSubtitleProvider

### ISSUE THREAD

**Issue by jeanahelver** [Neos-Metaverse/NeosPublic#2920]
### Describe the bug?

the Animator component seems to break or bug out wen used with with DynamicSubtitleProvider.
this seems to happen when the uri changes. the animator would keep running with the previous text or just return null.

### Relevant issues

Enverex seemed to have similar issues.

### To Reproduce

setting up a DynamicSubtitleProvider, Animator and Text field like normal. give it a URI and then changing the URI to another one.

### Expected behavior

changing the DynamicSubtitleProvider URI to change the subtitles.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.2.676

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Additional context

my current fix to the animator is to clear the animators text field and re adding it.

### Reporters

jeana

**Comment by Enverex** [comment]
I had added the breakage to the original GH to keep the chain, but maybe a new issue was required. Here's my comment - https://github.com/Neos-Metaverse/NeosPublic/issues/1260#issuecomment-911895934

**Comment by Frooxius** [comment]
Is there anything in the log files? It sounds like there might be an exception thrown somewhere.

**Comment by jeanahelver** [comment]
[DESKTOP-AIKB2GG - 2021.9.2.676 - 2021-09-03 10_04_35.log](https://github.com/Neos-Metaverse/NeosPublic/files/7104304/DESKTOP-AIKB2GG.-.2021.9.2.676.-.2021-09-03.10_04_35.log)

nothing i can find

**Comment by Frooxius** [comment]
Should be fixed in 2021.9.3.1281, thanks for report!

**Comment by jeanahelver** [comment]
animator seems to still break in ver. 2021.9.9.1144
seems to disable itself wen spawned in the world or wen a new user joins the session.
here's a example world: neosrec:///U-jeana/R-9cb1e5d3-331e-4767-a68b-dd6d29bf4cd1

Reported by: @Epsilion , @AlexFromAlaska , @jeana

**Comment by Frooxius** [comment]
@jeanahelver Can you provide a log please?

**Comment by Psychpsyo** [comment]
Here's my log from joining @jeanahelver 's session since her's didn't have any errors but mine did.
Got asked to send this here:
[logfile.txt](https://github.com/Neos-Metaverse/NeosPublic/files/7146453/logfile.txt)

**Comment by Frooxius** [comment]
Fixed in 2021.9.13.981, thanks for report!
