### ISSUE TITLE
Controllers become disconnected when fullbody trackers are on

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#2924]
### Describe the bug?

This happens when you have the controller get occluded for a bit or if it goes to sleep when wearing fbt when you move it after a while or turn it back on it is disconnected in-game but still moving fine in Steamvr itself so it's definitely a in-game bug

### Relevant issues

It becomes disconnected in-game and doesn't come back till you turn off all trackers first 

### To Reproduce

Basically wear fbt for a while having one controller occluded or go to sleep and then trying to move it results in it not moving anymore in-game or after turning it back when it has to go to sleep it also doesn't move anymore in-game but in steamvr it moves fine 

### Expected behavior

It to move in-game too

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

1.2.3

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### If it worked before, on which build?

1.2.3

### Additional context

It has happened for a while now not sure if anyone else has reported it yet 

### Reporters

Me

**Comment by alexderpyfox** [comment]
It's not version 1.2.3 but it wouldn't let me submit unless it typed something there*

**Comment by Geenz** [comment]
This would be more of a SteamVR issue, not necessarily a Neos specific issue.

**Comment by ProbablePrime** [comment]
Please also see: https://github.com/Neos-Metaverse/NeosPublic/issues/2423

for some additional conversation in this area.

**Comment by alexderpyfox** [comment]
Nah it's appearing in Steamvr fine and moving  but in-game it's stuck in place

**Comment by alexderpyfox** [comment]
They don't become trackers for me only issue is that when tracking gets lost or the controller powers off the controller doesn't track in-game it all is fine in Steamvr and all trackers and controllers are moving where they are supposed to only not in-game there the controller stays at the last place it was detected at

**Comment by alexderpyfox** [comment]
Only fix i found is that if you turn all trackers off and then turn the controller on first and then the trackers it works again so it's something with it loosing tracking and not coming back after

**Comment by Frooxius** [comment]
Can you share a log file from when this happens? Ideally if you reproduce it in a simple session without much going on.

**Comment by shiftyscales** [comment]
Can you also let us know what each of the tracker's role/body node is set to in SteamVR? @alexderpyfox

**Comment by alexderpyfox** [comment]
Yeah I have it here https://youtu.be/uq_3d68ekp8

**Comment by alexderpyfox** [comment]
It shows the 3 trackers where they are supposed to be and the controllers too

**Comment by alexderpyfox** [comment]
Basically all i did to reproduce is launch without having the trackers on and then enable them in-game and then turned one controller off to make it happen quicker and yep after turning it back on it disconnected from in-game but still appeared in Steamvr at the right place (left controller)

**Comment by alexderpyfox** [comment]
For the log do you want player.log?

**Comment by shiftyscales** [comment]
I see you are using those trackers in the 'held in hand' role. Does the issue occur if you assign them as feet/hips?

**Comment by shiftyscales** [comment]
In that same video you had showed, when you choose 'left hand' after the issue occurs, you see it shows one of the vive trackers as the input device.

**Comment by alexderpyfox** [comment]
I think it works normal now after connecting them one by one and setting them to left abd right and waist
