### ISSUE TITLE
Default User Audio Stream bitrate values

### ISSUE THREAD

**Issue by Khosumi** [Neos-Metaverse/NeosPublic#2926]
### Is your tweak request related to a problem? Please describe.

When selecting a bitrate for an Audio Stream, it is impossible to select a nicely defined number for the bitrate.
There should be a selection of commonly used bitrates, such as the following:
    32 kbit/s – generally acceptable only for speech
    96 kbit/s – generally used for speech or low-quality streaming
    128 or 160 kbit/s – mid-range bitrate quality
    192 kbit/s – medium quality bitrate
    256 kbit/s – a commonly used high-quality bitrate
    320 kbit/s – highest level supported by the MP3 standard
    
    Attempting any sort of accurate number is nigh impossible.
![image](https://user-images.githubusercontent.com/26034954/132065630-0eb9cff9-d69f-4a12-9dcc-b922a47b0255.png)

### Describe what would you like tweaked

A selection of commonly used bitrates as radio buttons, and a "Custom Bitrate" which would work as it currently does with the slider.

### Describe alternatives you've considered

N/A

**Comment by Frooxius** [comment]
We can round the number, but the question is why do you want it to be a nice round number? It won't make much of a difference if it's close enough.

Also please note that this isn't using MP3 codec, but Opus instead, which has different bitrate distribution, so the samples you provided don't match.

For example it supports all the way up to 500 kbps, but you also get much better quality at lower bitrates. E.g. 32 kbps with Opus is already good enough for some audio, while speech uses bitrates from 5-10 kbps, 20 kbps is quite high quality speech.

**Comment by Khosumi** [comment]
I was aware it isn't using MP3 for streaming the audio, however it is a point of reference for most people. (At least it is how I perceive it).

There is no particular need in making it a rounded number, it simply bothers me to know my stream is at an odd value.
As far as I am concerned there isn't much more than needs to be said on this, thank you for the reply.
