### ISSUE TITLE
"IsUserSilenced"

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2933]
### Is your feature request related to a problem? Please describe.

Not possible

### Relevant issues

-

### Describe the solution you'd like

A logix node to get if a user has been silenced or not.

### Describe alternatives you've considered

_

### Additional context

-

**Comment by TehTurk** [comment]
Is this for being muted or being silenced? They are different contexts, we ask for the problem for the feature requests usually to see what your trying to solve.

**Comment by 3x1t-5tyl3** [comment]
Not really a problem tho. I'd just like to be able to know if I'm silenced or have the ability to show it on something like a nameplate.
If I meant "mute" I would've asked for mute. Besides we already have a node to get the current voice mode. So that would've been useless.

**Comment by TehTurk** [comment]
That's why I wanted to ask. Because if it's tied to silence, I don't know if that's necessarily a good idea as Silenced is used for Moderation reasons usually within a session. I know we've had precedence of not tying those with Logix to some degree so I don't think it'd be a healthy idea.

**Comment by ProbablePrime** [comment]
I'd rather users knew than didn't. Sure it can lead to retaliation because they're aware that they are silenced but this can also occur if they figure it out through other means.

**Comment by 3x1t-5tyl3** [comment]
The volume slider get's moved anyhow. So it's not like you don't know anyhow. Everyone can see your volume at 0%

**Comment by 3x1t-5tyl3** [comment]
Besides its' the same as being silenced on discord. I really don't see the issue here- Plenty of platforms show you when you're silenced. And if you retaliate then you deserve further action anyhow.

**Comment by Frooxius** [comment]
Added in 2021.9.6.614! Thanks for request!
