### ISSUE TITLE
IsUserFriend Component / LogiX (Userspace Only?)

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2935]
### Is your feature request related to a problem? Please describe.

none.

### Describe the solution you'd like

It is probably not possible to get it under the current circumstances. I would like to have a component, LogiX, that searches for the target UserID and determines if the person is a friend or not.
(I'm envisioning something like CloudUserInfo, which returns a boolean if the user is a friend or not when the user name is entered; LogiX would be something like IsUserPatron).
Since there are security concerns, it may be possible to have it work only in UserSpace (although I personally would like it to work in WorldSpace, returning each value, since it would be less useful).

> 対象のUserIDを検索して、その人がフレンドかどうかを判定するコンポーネント・LogiXが欲しいです。
> (イメージとしてはCloudUserInfoのように、ユーザ名を入力したらフレンドかどうかをBoolで返してくれるものを想定しています。LogiXならIsUserPatronみたいな感じですね)。
> セキュリティ上の懸念事項があるので、UserSpace空間上でのみ動作するのでもよいかもしれません（使い勝手が悪くなるので、個人的にはそれぞれの値を返答する形でWorld空間上で動作してほしいですが）。

### Describe alternatives you've considered

It is probably not possible to get it under the current circumstances.

> 恐らく現状だと取得できないと思います。

**Comment by Frooxius** [comment]
Added this to CloudUserInfo in 2021.9.6.614. You are correct that having this work in worldspace would be a security issue, so it will only provide this information in Userspace. I'm sorry that we can't have this work in worldspace, but I hope this helps regardless!
