### ISSUE TITLE
remove bobool3ol type

### ISSUE THREAD

**Issue by EIA485** [Neos-Metaverse/NeosPublic#2940]
### Is your tweak request related to a problem? Please describe.

when writing plugins for neos vr bobool3ol type is annoying.
normally when typing bool i press b then tab
if am using the namespace baseX and  i type b then press tab i get bobool3ol.
this is vary minorly annoying but im making a report as the fix would be extremely simple and not break anything.

### Describe what would you like tweaked

the bobool3ol type removed as it is not used.

### Describe alternatives you've considered

not using the BaseX namespace

**Comment by Frooxius** [comment]
I'm sorry, but we don't take requests for removal of internal classes and structs. If it wasn't this type, it could be any other from the hundreds of types (e.g. bool2, bool3 or bool4 even), whose removal would have more severe impact on the project.

I'd recommend configuring or using/configuring IDE or plugin with smarter auto-completion. I spend hours (sometimes most of waking hours) writing code for Neos and this has never been an issue.
