### ISSUE TITLE
/priorityIssue not working in Neos Bot

### ISSUE THREAD

**Issue by Lexevolution** [Neos-Metaverse/NeosPublic#2942]
### Describe the bug?

The Neos Bot is not sending a response when I send the `/priorityIssue` command. 

### Relevant issues

No relevant issues found.

### To Reproduce

Type `/priorityIssue #289` to the Neos Bot

### Expected behavior

A response from the neos bot stating that my priority issue vote has been accepted

### Screenshots

![2021-09-06 03 11 47](https://user-images.githubusercontent.com/31176843/132136422-44378ebc-4cb0-4515-8090-750c6aa719a9.jpg)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.4.468

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

Not Sure

### Additional context

I'm not sure whether my vote is actually going through or not, it's just I can't be certain because I'm not getting a response.
Other commands (e.g. `/echo`) work.

### Reporters

`Lexevo#0876`
`Sox#0001`

**Comment by Frooxius** [comment]
The GitHub API was rate limited when you made your attempts. I've made changes in 2021.9.6.614 so an error gets reported in such case now, indicating that you should try again later. Thanks for report!
