### ISSUE TITLE
Log being filled with Authority Time errors.

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#2948]
### Describe the bug?

While connected to a session hosted by a user in Australia (>300ms ping), I noticed that my log was being filled by the following error:

```
11:51:06 AM.471 ( 47 FPS)	Received authority time that's older than the last received one, rejecting. LastReceived: 3289.91202663165, Received: 3289.90802753158.

   at void BaseX.UniLog.Log(string message, bool stackTrace)
   at void FrooxEngine.TimeController.SyncWorldTime(double authorityWorldTime)
   at void FrooxEngine.SyncController.ApplyStreams(StreamMessage message)
   at bool FrooxEngine.Session.ProcessMessage(SyncMessage msg, ulong lastDeltaSyncTime, List<ControlMessage> controlMessagesToProcess)
   at void FrooxEngine.Session.SyncLoop()
   at void FrooxEngine.Session.RunThreadLoop(Action loop)
   at FrooxEngine.Session(World owner)+() => { } [2]
   at void System.Threading.ThreadHelper.ThreadStart_Context(object state)
   at void System.Threading.ThreadHelper.ThreadStart()
``` 

This message is repeated thousands of times, resulting in a 28MB log file at the time of writing.
Every other user in the session also had >300ms ping, and also had these errors in their log.

### Relevant issues

N/A

### To Reproduce

This seems to occur whenever connecting to users where ping times are excessively high.

### Expected behavior

Less verbose logging for this error, or a higher threshold for this error to occur.

### Log Files

Segment of the log for this session, since the original log file is nearly 30MB:

[DESKTOP-QRCPAUB - 2021.9.6.614 - 2021-09-06 11_49_30 - Copy.log](https://github.com/Neos-Metaverse/NeosPublic/files/7117665/DESKTOP-QRCPAUB.-.2021.9.6.614.-.2021-09-06.11_49_30.-.Copy.log)

### Screenshots

![t](http://files.aerizeon.net/sharex/2021/2021-09-06_15-45-Neos_N7Ipry4SP2.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.6.614

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### Reporters

Joffels (who has internet bad enough to get 300+ ms ping)
Epsilion
Psychpsyo

**Comment by Frooxius** [comment]
This is not a bug, the last build had temporary logging added to help diagnose https://github.com/Neos-Metaverse/NeosPublic/issues/2943 It will be removed soon once we gather some data.

**Comment by Frooxius** [comment]
I removed the stacktraces in 2021.9.8.946, which should make it a bit more compact. Once we have the issue resolved I'll remove the logging completely.
