### ISSUE TITLE
UIX Gizmos

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2962]
### Is your feature request related to a problem? Please describe.

Working with UIX is a massive pain if it doesn't immediately do what you want.
"Why is the layout not the way I'd like it to be?" tends to be unreasonably hard to debug, especially if a lot of nested elements are involved.

### Relevant issues

#1566 asks for a similar thing but while proposing a very specific solution.
UI Gizmos are mentioned there but I can't find any other reference to these anywhere. Not on the Github, not on the Discord, not anywhere in game.

### Describe the solution you'd like

Some way for UIX elements to have gizmos, similar to the ones that selected slots currently have. (but 2D, of course)
Additionally it'd be very helpful if these not only indicated the element's bounds but also some info about why the layout is the way it is.
This could include:
- highlighting space taken due to the FlexibleWidth&Height properties
- outlining the MinWidth&Height seperately
- visual indications for horizontal, vertical and grid layouts
- indicators for how far past the canvas borders scrollable fields reach

### Describe alternatives you've considered

Putting up with the annoyance of UIX which is undesireable for obvious reasons.

**Comment by Earthmark** [comment]
I know some existing user made tools exist to do this, I believe uki has one and toxic cookie has one. It may be good to gather what is liked or disliked about those tools to better refine what's wanted.

**Comment by Earthmark** [comment]
That was a fat finger on my phone, thank you phone for having the fix typo button right under close and post.

**Comment by ukilop** [comment]
Psychpsyo and I were talking when he made this post Earthmark :V
General idea was a simple bounding box around the RectTransform that (i belive) every single uix slot requires
