### ISSUE TITLE
Oculus build missing

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2966]
### Describe the bug?

Looks like the android build got stuck again, there's no NeosOculus.apk in the android-preview branch.
There are also two leftover *BEPUv2.apk files version 2021.8.smth from the end of the public testing.

### Relevant issues

Unsure

### To Reproduce

Switch to android-preview branch and update

### Expected behavior

Should have Neos.apk and NeosOculus.apk of the current version

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.8.946

### What Platforms does this occur on?

Android / Quest

### Did this work before?

Yes

**Comment by Frooxius** [comment]
Fixed a build error in 2021.9.9.1144, they should now be building again. Thanks for report!

**Comment by kazu0617** [comment]
Oculus Build Missing Regression in 2021.9.11.1001.

**Comment by Frooxius** [comment]
Hmm I'm not sure what happened, it seems to build on my end. Is it still missing in the latest update?

**Comment by kazu0617** [comment]
> 
> 
> Hmm I'm not sure what happened, it seems to build on my end. Is it still missing in the latest update?

latest update successfully installed. and according steamdb, He said it was delivered properly. Thank you very much.
If there are any more, I will contact.

**Comment by kazu0617** [comment]
@shadowpanther thanks for re-open it. This problem has been fixed in a latest update. I'll let you know if anything else happens, but for now, you can just close it.

**Comment by kazu0617** [comment]
Oculus Build Missing Regression in 2021.9.12.1084.

**Comment by shadowpanther** [comment]
It is instead build 2021.9.12.1069 which is between the previous one and the current one.

**Comment by Frooxius** [comment]
That's normal, I don't always push them 1:1 if they're not compatible, because building them takes time. Once we have CI/CD setup it'll ensure that they're always paired.

**Comment by shadowpanther** [comment]
Okay, I think the issue could be closed for now and reopened when the build gets stuck again.
Automating the build and the build status monitoring would greatly help.

**Comment by kazu0617** [comment]
I'm using with SteamDB( https://steamdb.info/app/740250/history/ ) and watching with distill, these are so helpful to see the latest-build stucking.

**Comment by kazu0617** [comment]
Oculus Build Missing in 2021.10.6.332.

**Comment by shiftyscales** [comment]
Re-opening as 2021.11.10.1253 is missing the NeosOculus.apk on the Steam release.

**Comment by kazu0617** [comment]
how progress for release for Android? I'm not stand at now, but I think no build released from 6 monthes, it also include security issue.
