### ISSUE TITLE
Physical Button Toggle

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2977]
### Is your feature request related to a problem? Please describe.

I want to use the PhysicalButton component for a button press toggle, but I want the visual state of the button to stay pressed down, and when you click it again. It pops back up in it's off state.

### Relevant issues

None that I could find? Using "Physical Button Toggle" search

### Describe the solution you'd like

Either a separate component named Physical Button Toggle that works like Physical Button but instead as a toggle. With an On/Off State 

### Describe alternatives you've considered

Currently, I'm writting to the physical buttons pressed down state which is not a great solution.

### Additional context

Friend is making a boom box and would like a physical button for the switches but needs them to toggle it's pressed down state.

**Comment by mralext20** [comment]
does the very recently added 'hold mode' work for this? 

from the patch notes for 2021.9.8.946, 

> - Added "Hold" mode to PhysicalButton
-- When enabled, every time you press the button, the "IsHolding" will be toggled on and off - the button will remain partially pressed and needs to be pressed again to reset
-- While the button is holding, it can be partially pressed down to indicate this (controllable with HoldDepthRatio)
-- Added helper IsPressedOrHolding field, which indicates whether the button is currently pressed or holding

**Comment by Earthmark** [comment]
Le magical box you want to check! 
![image](https://user-images.githubusercontent.com/1251609/132625434-b9a408e1-fd52-44b5-9f61-496f34e46623.png)

**Comment by ProbablePrime** [comment]
Can confirm that this is how its done, quick video: 
https://i.probableprime.co.uk/210908-ndAT49yIUTKa1wNAKbCr.mp4

We'll close this as implemented. Have fun!

**Comment by AshtonSparx** [comment]
Thank yoou! I wasn't away that's what the box was for and my small brain didn't think of checking it to see what it was <3
