### ISSUE TITLE
Is Character On Ground node fires false if character has physics nodes applied

### ISSUE THREAD

**Issue by TheBasementNerd** [Neos-Metaverse/NeosPublic#2978]
### Describe the bug?

While a user is on the ground, if they are being moved by Apply Character Force or Set Character Velocity, the node Is Character On Ground will fire false during that time. This bug does not occur when pushed by colliders, or walking normally

### Relevant issues

The common avali flight system has been reported broken by many users as the avatar will continue to slide along the ground after landing from a glide, as the glide stays active due to the system not detecting if the user has hit the ground correctly

### To Reproduce

Apply a force to a user using the logix nodes found under the Physics category, and have the user that the force is applied to read out from the node Is Character On Ground, and they will see that it is false

### Expected behavior

The Is Character On Ground should report true whenever the user is on the ground, even if they are being moved by an external source but still contacting the ground

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.8.946

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

2021.8.18.1077

### Reporters

TheCrowDevilsBK#9681

**Comment by H3BO3** [comment]
This makes sense, since any force applied above a very small threshold breaks ground traction. This happened with my flight platform too, I'm likely going to need to manually upgrade the flight loop to fix it. #2900

**Comment by Frooxius** [comment]
This is likely pretty much the same issue as #2900. 

I can tune the system to not break the ground traction until the force exceeds certain amount or tweak the glue force itself, but I'd need to know what exact forces you're applying while this is happening.

**Comment by H3BO3** [comment]
From what I could gather of the old behavior, it seemed like the traction force was applied whenever the character was just touching the ground, even with forces applied. I guess this is a behavior that didn't translate to bepu2

**Comment by Frooxius** [comment]
It's a complete rewrite, so there are some subtle differences in behavior. We can correct some of them, but I need to have a good understanding of the problem first.

**Comment by shiftyscales** [comment]
I have actually noticed this behavior with the Hel-E-Copter as well. In bepuv1 I could spin it up and it would need to pass a certain speed threshold before I'd take off. On bepuv2, pretty much any amount of thrust generated causes me to slide around on the ground not gaining any lift- but not respecting the 'friction' that one would expect/was present in bepuv2.

**Comment by Hayden-da-Serg** [comment]
I still get this with my boosters whenever any amount of force is applied, if I'm applying a force that is weaker than my gravity, I will stay on the ground, but won't have any sort of traction and therefore will slip all over the place

Before Bepuv2, I still had ground traction up until the forces applied were stronger than the gravity, therefore lifting me off the ground. I still felt like traction was applied, even if force was being applied to me.

**Comment by TheBasementNerd** [comment]
It feels like the main issue that arises is, without being able to detect if a character is on the ground while being moved, many systems and possibilities for systems breaks, especially when many might account for movement based on traction against the ground, which would glue you in place in BepuV1 and now slides you around frictionless in BepuV2. Would it be possible to have a middle ground, where contacting the ground results in any physics forces being slowed by a traction amount and pushing out the status that the character controller is on the ground? This seems like the best way to address all the issues, or at least having it just say it's on the ground if the collider is, in fact, having vertical movement affected by the ground

**Comment by Frooxius** [comment]
This should now be fixed in 2021.9.9.1144, thanks for report! Please reopen if the issue persists.
