### ISSUE TITLE
ContextMenuItemSource ButtonEnabled state not respected by Flick selection

### ISSUE THREAD

**Issue by XDelta** [Neos-Metaverse/NeosPublic#2979]
### Describe the bug?

With a context menu button (ContextMenuItemSource) that has ButtonEnabled set to false, the button can still be successfully pressed by flicking to it if Flick selection isn't disabled.

### Relevant issues

Didn't find one.

### To Reproduce

Make a Context Menu with atleast a RootContextMenuItem and a ContextMenuItemSource
Set ButtonEnabled on the ContextMenuItemSource to false
Open the context menu
Use the flick selection circle to select the button, the button gets pressed and triggers whatever action if controls.

### Expected behavior

The ButtonEnabled option should disable the button from all forms of pressing it, at the moment it changes it to the disabled color and prevents clicking it. Flick selection should not be able to press it.

### Screenshots

https://user-images.githubusercontent.com/7883807/132640665-961cea6f-dd61-48d1-925b-16de850b6337.mp4

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.8.1291

### What Platforms does this occur on?

Windows, Linux

### Did this work before?

I Don't Know

### Reporters

Delta#0942

**Comment by Frooxius** [comment]
Fixed in 2021.9.9.1144, thanks for report!
