### ISSUE TITLE
Experienced a Random Hard Crash

### ISSUE THREAD

**Issue by AzoraHusky** [Neos-Metaverse/NeosPublic#2980]
### Describe the bug?

I was busy talking with some people, then all of a sudden I am back in the SteamVR environment. There was no pause, or stuttering, Neos just closed immediately.

### Relevant issues

I am not sure how this happened due to it happening without trying to find bugs and I was just chatting.

### To Reproduce

I have included a log for the for the crash report. Since I was just chatting and not spawning anything, using anything, and nobody else around me crashed.

### Expected behavior

The whole client closes immediately.

### Log Files

[DESKTOP-QL2UJL3 - 2021.9.8.1291 - 2021-09-09 15_35_42.log](https://github.com/Neos-Metaverse/NeosPublic/files/7137169/DESKTOP-QL2UJL3.-.2021.9.8.1291.-.2021-09-09.15_35_42.log)

### How often does it happen?

Sometimes

### Does the bug persist after restarting Neos?

No

### Neos Version Number

2021.9.8.1291

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

The DeSync Lounge

### Did this work before?

I Don't Know

**Comment by epicEaston197** [comment]
if you can also get the player log

**Comment by AzoraHusky** [comment]
[Player-prev.log](https://github.com/Neos-Metaverse/NeosPublic/files/7142447/Player-prev.log)
Here is the Player Log for that session, fortunately I only started up the game once after that.

**Comment by epicEaston197** [comment]
somebody that knows more than me could possibly read it and figure out what went wrong I had this happen to me before

**Comment by Frooxius** [comment]
I've added a guard against this causing a crash in 2021.9.11.1001. I'm not entirely sure what could've caused this crash in this case, looks like something was potentially corrupted, we'd need more instances. The new build has new diagnostics though, so if it happens again we can gather some more data. Thanks for report!
