### ISSUE TITLE
Gizmo Allocating User behaves weird

### ISSUE THREAD

**Issue by minenick123** [Neos-Metaverse/NeosPublic#2981]
### Describe the bug?

When using Allocating User on a gizmo you should get the user who created said gizmo, This works when actively selecting something with the dev tip . The problem arises when using an inspector to select something. The ispector is allocated to a user but the gizmos it spaws are allocated on the host. Same when you select something, open the inspector and close it again and after that open it without selecting something. Then it autoselects the last selection and creates a gizmo that is allocated on host. 

### Relevant issues

Nope

### To Reproduce

Dev Tool -> Select something -> open Inspector -> close inspector -> open inspector without selecting -> check allocating user of the gizmo that got created

Inpsector select a slot -> check allocating user of the created gizmo

### Expected behavior

Any gizmo from a inspector by a user should be allocated by that user and when a gizmo is created from a tool under any circumstance it sould also be allocated by the user who allocated the tool

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2021.9.8.1291

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Additional context

This would allow for some easy user created gizmo management until a better selection system is implemented.

**Comment by Frooxius** [comment]
This is normal, some code and actions run specifically on the host user, so the Allocating User is providing you correct information.

As we rework more systems we'll do more things on the user doing the interactions rather than host, but that's a bigger task over time.
