### ISSUE TITLE
Add "Month of Year"

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2982]
### Is your feature request related to a problem? Please describe.

I need to use a multiplexer. Could be done more efficiently.

### Relevant issues

-

### Describe the solution you'd like

A node similar to "Day of week" just for "Month of year"

Would output the name of the month.

![grafik](https://user-images.githubusercontent.com/61988002/132740792-97dccd5f-8d46-4725-9883-b388345514d4.png)

### Describe alternatives you've considered

-

### Additional context

-

**Comment by 3x1t-5tyl3** [comment]
OH I didn't know! This is older logix. I was too lazy to redo it all. That is **much** better. I'm surprised that day of week exists then? Huh.

Also yes please. Having proper support for those would be nice.

**Comment by ProbablePrime** [comment]
Ok heres 11,12,13: 
![image](https://user-images.githubusercontent.com/8791132/132744099-48388bf5-3b28-4ccc-b3bd-27fd5a0c4303.png)

https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings and https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings and http://blog.stevex.net/string-formatting-in-csharp/

are good resources for format strings.

**Comment by 3x1t-5tyl3** [comment]
Awesome. Closing this. Apologies!
