### ISSUE TITLE
The Slot the Interactive Camera Component is on duplicates itself on root when it's parent is destroyed

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2988]
### Describe the bug?

I made a phone thingy using the interactive camera component so it can work like an actual phones camera. The component isn't on the root of the object (It turns off when the camera isn't selected on the phone). I found when I delete the phone. The Slot the component is on. Regardless if it's off or on, re-parents itself to root.

### Relevant issues

Couldn't find anything regarding the Interactive Camera Component

### To Reproduce

1. Create an empty Object
2. Give that slot a child (Give it a name so it's easily to identify)
3. Put the Interactive Camera Component on that child you just re-named
4. Delete the parent
5. Check root for that slot

### Expected behavior

For it to not push itself on root when ever it's parent is deleted.

### Log Files

Not Required

### Screenshots

Before Deleting `Empty Object`
![image](https://user-images.githubusercontent.com/53165730/132937931-2e52e65d-37d3-4793-ac45-dd96fc370702.png)

After Deleting `Empty Object`
![image](https://user-images.githubusercontent.com/53165730/132937952-436f0f28-d6ce-4110-8b4e-ea519d0805be.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.9.1144

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

AshtonSparx#5050

**Comment by Frooxius** [comment]
Fixed in 2021.9.13.981, thanks for report!
