### ISSUE TITLE
my hand and my HUD stutter in desktop mode

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#2990]
### Describe the bug?

my head and my hand stutter in desktop mode whenever I look around my HUD and my hand what does lag or stutter
I don't know how to get more detail it is kind of stutters

### Relevant issues

no response

### To Reproduce

in desktop mode equip a developer tool and look around with your hand and view

### Expected behavior

my hand and any UI elements I add to my head should say still

### Log Files

not anything relevant I could think about to be found in a log

### Screenshots

a screenshot would not represent this well

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.11.1001

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

no response

### Did this work before?

Yes

### If it worked before, on which build?

2021.9.9.1144

### Additional context

https://www.youtube.com/watch?v=EqjbShHVOMk 
https://www.youtube.com/watch?v=41egUvUuH1U

### Reporters

@epicEaston197#0793 @SeventhVoid#8788

**Comment by epicEaston197** [comment]
I also noticed any accessories on behead also do this for example my glasses

https://user-images.githubusercontent.com/76523692/132965789-67277e1c-c8f2-41be-9a4f-ca3d216e1bc2.mp4

**Comment by MinkyFox** [comment]
I also got the same issue with a friend too.

**Comment by Frooxius** [comment]
Fixed this in 2021.9.12.967, thanks for report!
