### ISSUE TITLE
Add overload to Request Host Access that accepts a Url

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2991]
### Is your feature request related to a problem? Please describe.

I tend to make network systems using a single root url string, and then passing that string through a url cast into a web request. 

The request host access node as it stands now makes this very painful, as you need to parse out the domain, and now the port number, of that access string. This is very error prone, and makes it very difficult to do the right thing and ask for access, as it's so easy to get wrong.

### Relevant issues

#2878
The port restriction that was just added, I think some issues around host access but I can't find them now.

### Describe the solution you'd like

Add an overload to Request Host Access that accepts a single url input, and that input is parsed for whatever pieces of info are needed for the Request Host Access to function properly.
Currently this would be port and domain, however I could see route being added later on, and using the url override would natively support that, where as that would be an additional pin with the current stategy.

### Describe alternatives you've considered

Having a domain, port, and url variable independently.
Considering that I store the url in a cloud variable, that's three variables that encode duplicate data and need to be updated all at once. It is difficult to do that right, and replication speed may leave systems in an invalid state for a time until things coalesce together. This would also take up additional cloud variables.

Manually parsing the url
This is very error prone, and special case dependent due to no regex support and no way to extract the properties from the url itself. To do this I have to make error prone string parsing cases that are just as likely to get things wrong and if the parsing is wrong it'll double ask anyways. I might as well just not ask at all.

### Additional context

I feel this duplicate data is a big reason why people don't use request host access.
As it stands now it's so easy to get the url (and now port) wrong and have it double ask, it may be detrimental to the user experience to use request host access right now. Having Neos itself pull the bits it cares about out of the url would allow the developer to care less about manual url string parsing.

**Comment by ProbablePrime** [comment]
The Uri type has all the parts we need here, so we should consider usin URI here.

We could also add a construct uri node that emulates the current inputs of the node to assist.

**Comment by Frooxius** [comment]
Added those in 2021.9.12.967, thanks for request!
