### ISSUE TITLE
Headless client does not allow access when making HTTP request with explicit port

### ISSUE THREAD

**Issue by WallTack** [Neos-Metaverse/NeosPublic#2993]
### Describe the bug?

Headless client will not allow access to make requests (GET/POST using logix nodes) to a host when any port number is specified, even when the given hostname:port combination is specified in the `allowedUrlHosts` field of the headless config file.

### Relevant issues

No. This began with the update today: `2021.9.11.1001`

### To Reproduce

Start a headless client with `allowedUrlHosts` set to `["localhost", "localhost:8080"]`. Make a GET (or any method) request through the host user (headless client) to `localhost:8080`

### Expected behavior

If the hostname:port combination is specified in the `allowedUrlHosts` config field, the headless client should allow access to it.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.11.1001

### What Platforms does this occur on?

Linux

### Did this work before?

Yes

### If it worked before, on which build?

2021.9.9.1144

### Reporters

WallTack

**Comment by WallTack** [comment]
Upon further testing this only appears to affect `localhost`: making requests to an external IP with `hostname:port` format worked as expected. I don't have time to test this tonight but I suspect that using `127.0.0.1` in place of `localhost` might be a temporary workaround; that, or redirecting to the port you need.

**Comment by Earthmark** [comment]
Thank you for the extra testing, that'll help!

**Comment by Frooxius** [comment]
This should be fixed in 2021.9.12.967, thanks for report!
