### ISSUE TITLE
Add [Match Substring] option in Index Of First Match

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2999]
### Is your tweak request related to a problem? Please describe.

Every once in a while I encounter such a situation, and every time I do, I either repeat Contains or I write down all the patterns.

### Describe what would you like tweaked

Add [Match Substring] option in Index Of First Match.

### Describe alternatives you've considered

Write All Variables of patterns.

**Comment by H3BO3** [comment]
This would only apply to strings, which would apply only to that type of the IOFM node. Perhaps a new node for finding the first substring match would be a better solution

**Comment by shadowpanther** [comment]
@kazu0617 what is your use-case for matching the string against multiple patterns and having a partial match in particular?

**Comment by Frooxius** [comment]
I'm not sure I understand this request exactly. IndexOfFristMatch operates on arbitrary values, rather than strings, so they cannot handle substring matches. Do you want this for any of the string nodes?

**Comment by kazu0617** [comment]
When I confused, I try to detect CurrentLocale through LogiX node `CurrentLocale`, so only this use-case, just add one more LogiX node `CurrentLanguage`.

**Comment by shadowpanther** [comment]
> When I confused, I try to detect CurrentLocale through LogiX node `CurrentLocale`, so only this use-case, just add one more LogiX node `CurrentLanguage`.

For that use-case, you can first get a substring of the first two characters of your locale, and then match that substring to the list of languages, I think.

**Comment by kazu0617** [comment]
It may be a good idea to add more nodes, but in any case, no major problems have occurred, so I will close this Issue once. Thank you very much.
