### ISSUE TITLE
Interactive Camera Component ignores being disabled

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#3000]
### Describe the bug?

The component ignores being disabled and ignores it's slot being disabled

### Relevant issues

N/A

### To Reproduce

Have the component on something (Can use the Neos Camera) and disable it. Take a picture.

### Expected behavior

Should respect being disabled

### Log Files

None Needed

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.12.1084

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

AshtonSparx#5050

**Comment by Frooxius** [comment]
What's your usecase for this? Usually Disabling components just gets rid of their continuous (per frame) behaviors, but their functionality can still be triggered by external actions - e.g. taking picture is one.

**Comment by AshtonSparx** [comment]
I'm creating a phone that has "apps" and stuff. One of them is a camera. When you're not in the camera app, it's supposed to disable the camera. However, when the camera is disabled. You can still hold the phone and press Primary and it still lets you take pictures, which in my use case, isn't supposed to happen.

**Comment by Frooxius** [comment]
I see. That's actually not specific to the InterfaceCamera, but the trigger action being sent to disabled objects. This should now be fixed in 2021.9.14.1024, thanks!
