### ISSUE TITLE
Is Tooltip In Use logix node breaks when the tooltip gets equip

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#3001]
### Describe the bug?

When you equip any rawdatatooltip the node disables logix and un-drives drive fields

### Relevant issues

None i can find

### To Reproduce

1. Make a rawdatatooltip or use the template in runtime's folder referenced in reproduction field. It's the cone.
2. reference the rawdatatooltip with the "Is tooltip in use" logix node in Tools & pullout a display node.
3. equip the tooltip

### Expected behavior

 For normal functionality

### Log Files

No exceptions get thrown in logix

### Screenshots

![2021-09-12 22 33 59](https://user-images.githubusercontent.com/53165730/133015989-e4401db9-2e6c-4179-87c1-46173e4a1e2a.jpg)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.12.1084

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

neosrec:///U-runtime/R-2a8fb0d0-9fb3-4f09-b925-c86517671769

### Did this work before?

I Don't Know

### Reporters

Aegis#5220
AshtonSparx#5050

**Comment by Frooxius** [comment]
Do you have a logfile?

**Comment by ohzee00** [comment]
Using the replication case provided even with the template, I am unable to have any errors with the display nodes, does this still break for you?

**Comment by AshtonSparx** [comment]
I can't seem to replicate it either, which is confusing. Perhaps it had an edge case that caused it? We did exactly what was in the replication steps. The log is rather girthy (2.2mb) and I don't remember time stamps

**Comment by AshtonSparx** [comment]
We've figured it out! It's when you try to use the logix node in a world you're not hosting! It breaks it. There is zero info in the log when the logix turns red

**Comment by Frooxius** [comment]
Thanks, fixed in 2021.9.14.1024!

**Comment by AshtonSparx** [comment]
I know this is minor but the display node breaks when someone grabs the tooltip and doesn't display anything.

![unknown](https://user-images.githubusercontent.com/53165730/144732961-1d2b5c2d-9f48-4b6c-be97-7935803c0707.png)

**Comment by shiftyscales** [comment]
I'm uncertain what you mean/can't immediate replicate it. I'd advise you report that separately as a new issue, @AshtonSparx.
