### ISSUE TITLE
Add Empty String Node in String/*

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#3003]
### Is your feature request related to a problem? Please describe.

When I was checking #3002, I needed to enter Empty for String (if it was null, it wouldn't pass), but I couldn't tell if the Input Node was null or Empty just by looking at the Input Node (I was talking about how hard it was to see this while checking).

> #3002 の確認をしている最中、StringにEmptyを入力する必要があったのですが(nullだと通らない)、Input Nodeを見ただけではそのInput Nodeがnullなのか、Emptyなのかが全く分かりませんでした（確認しながらこんな見づらいことないよって話をしてました）。

### Relevant issues

nothing i think.

### Describe the solution you'd like

When I was checking #3002, I needed to enter Empty as a String (if it was null, it wouldn't pass), but just by looking at the Input Node, I couldn't tell if the Input Node was null or Empty at all. Of course, I understand that there are many such cases, but if special characters are a category of node, I thought it would be nice to have a Node that only spits out Empty.

> #3002 の確認をしている最中、StringにEmptyを入力する必要があったのですが(nullだと通らない)、Input Nodeを見ただけではそのInput Nodeがnullなのか、Emptyなのかが全く分かりませんでした。もちろんそういったケースが多いのはわかりますが、特殊文字がノードとしてカテゴリになっているのであれば、Emptyのみを吐き出すNodeがあってもいいんじゃないのかなと思いました。

### Describe alternatives you've considered

Both use String Input Node. I get the problem above (hard to see).

> 両方ともString Input Nodeを利用する。上の問題が発生します（見づらい）

### Additional context

This Issue checked with Aetoriz, so if write release-note, plz write his/her name with me.

**Comment by Earthmark** [comment]
To clarify, you are wanting a node that specifically emits the empty string, or are  you wanting the string input to have the ability to emit an empty string?

**Comment by Frooxius** [comment]
![image](https://user-images.githubusercontent.com/8838625/133121647-bc64cbee-de17-4073-8c0b-7bdba31cd071.png)

Added new nodes and button to null the string in 2021.9.13.981! Thanks for request :D
