### ISSUE TITLE
For the new String Null button to have an undo step

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#3006]
### Is your tweak request related to a problem? Please describe.

I can sense a lot of users are going to null their strings on accident and would require an undo step to fix it.

### Describe what would you like tweaked

For the String null button to have an undo step

### Describe alternatives you've considered

For precious strings to get nuked on accident and can't undo it

**Comment by Frooxius** [comment]
Added in 2021.9.14.1024! There were some other issues with Undo with Input nodes which should be fixed up as well.
