### ISSUE TITLE
Add Batch File "Install NeosVR on Android Phone" in android-preview

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#3007]
### Is your tweak request related to a problem? Please describe.

none.

### Describe what would you like tweaked

Currently, there are "Install Classroom on Oculus.bat" and "Install NeosVR on Oculus.bat" in Android Build, but they are also available as APKs for regular Android Screen. Therefore, I would like you to prepare "Install NeosVR on Android Phone.bat" as well.As with the other bat, I think you only need to change the APK to be installed.

### Describe alternatives you've considered

Create the following bat file by yourself. It's not difficult, but I thought there was no particular reason not to prepare it, so I used Tweak to create it. I have already created this bat file myself.
```
@echo off
echo Installing...
adb install -r Neos.apk
pause
```

**Comment by Frooxius** [comment]
Added in 2021.9.14.1024, thanks for suggestion!
