### ISSUE TITLE
Gamepad/racing wheel logix node with float values 

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#3009]
### Is your feature request related to a problem? Please describe.

I need this to connect a racing wheel to a creation in-game the pedals have float values and the steering too 

### Relevant issues

Controllers support is added but no logix node to connect it to anything

### Describe the solution you'd like

It to be added 

### Describe alternatives you've considered

Custom logix node.dll but those can't work in multiplayer since it's not local

**Comment by Frooxius** [comment]
We already have topic for this here: https://github.com/Neos-Metaverse/NeosPublic/issues/643 Closing as duplicate.
