### ISSUE TITLE
URI Node crashes if field is empty and enter is presses

### ISSUE THREAD

**Issue by ScarsTRF** [Neos-Metaverse/NeosPublic#3010]
### Describe the bug?

When pressing the URL node and pressing enter, it world crashes everyone except the host unless the event was made by a non host which force closes the worldnonhost

### Relevant issues

#2995 

### To Reproduce

Spawn a URI node and click on the input field then press enter, and the world will crash

### Expected behavior

The URI should just null the value without crashing

### Log Files

[Uploading SCARS-DESKTOP - 2021.9.13.1057 - 2021-09-14 09_14_27.log…]()

### Screenshots

https://cdn.discordapp.com/attachments/439422161657135106/887376802958413824/2021-09-14_17-35-37.mp4

https://cdn.discordapp.com/attachments/439422161657135106/887376824559104110/2021-09-14_17-36-09.mp4

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.13.1057

### What Platforms does this occur on?

Windows, Linux

### Did this work before?

I Don't Know

### Reporters

ScarsTRF#2778 SeventhVoid#8788 Kiovo#5446

**Comment by Frooxius** [comment]
Was everyone in the session on the latest build?

Can you please provide a log? The one in the original message didn't upload.

**Comment by ScarsTRF** [comment]
Yes, the latest build still does it. 2019.9.14.1024

As well the node now spawns disabled automatically.

[SCARS-DESKTOP - 2021.9.14.1024 - 2021-09-14 12_24_31.log](https://github.com/Neos-Metaverse/NeosPublic/files/7164016/SCARS-DESKTOP.-.2021.9.14.1024.-.2021-09-14.12_24_31.log)

**Comment by shadowpanther** [comment]
Looks like it's the same issue as #2995, added to the relevant issues.

**Comment by Frooxius** [comment]
Should be fixed in 2021.9.14.1348, thanks for report!
