### ISSUE TITLE
The new grab options are great! But useless for desktop users.

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#3012]
### Is your tweak request related to a problem? Please describe.

I love the new grab options but desktop users can't use it, so it's another thing in their context menu.

### Describe what would you like tweaked

I would like desktop users to be excluded from having the new context menu button. If you switch back to VR. It re-adds it back.

### Describe alternatives you've considered

Not exclude desktop users from having it

![image](https://user-images.githubusercontent.com/53165730/133343840-f8f7b394-4513-4126-a724-22685c14a575.png)

**Comment by Frooxius** [comment]
I wanted to do this before release, but forgot. It's hidden in 2021.9.16.105, thanks!
