### ISSUE TITLE
SkinnedMeshRenderer bake using BakeMeshMode don't work without bones.

### ISSUE THREAD

**Issue by Aetoriz** [Neos-Metaverse/NeosPublic#3020]
### Describe the bug?

メッシュをベイクする際、BakeMeshモードで以下のどちらかを満たすSkinnedMeshRendererを含んでいるとベイクすることができませんでした。
・BoneListが存在しない。（ShapeKeyのみ存在するSkinnedMesh）
・BoneListよりSkinnedMeshRendererのBonesの数が少ない

同じボーンが指定されていたり、ボーンがNullを指定されている場合は、ベイクすることができます。

(Google translate)
When baking a mesh, it could not be baked if it contained a SkinnedMeshRenderer that met either of the following in BakeMesh mode:
-BoneList does not exist. (SkinnedMesh that only ShapeKey exists)
-Skinned Mesh Renderer has fewer bones than Bone List

If the same bone is specified, or if the bone is specified as Null, it can be baked.

### Relevant issues

None

### To Reproduce

1.任意のSkinnedMeshRendererのBonesを減らす。
2.MeshBakeモードのBakeTipや、SkinndMeshModeがFalseのBakeMeshes nodeでベイクをする。

1. Reduce Bones in any Skinned Mesh Renderer.
2. Bake with BakeTip in MeshBake mode or BakeMeshes node with SkinndMeshMode False.

### Expected behavior

他のSkinnedMeshRendererと同様にベイクされる。
Bake like any other Skinned Mesh Renderer.

### Log Files

[DESKTOP-PFESGVH - 2021.9.16.105 - 2021-09-17 11_27_51.log](https://github.com/Neos-Metaverse/NeosPublic/files/7182554/DESKTOP-PFESGVH.-.2021.9.16.105.-.2021-09-17.11_27_51.log)

### Screenshots

1.Normal
![20210917122311_1](https://user-images.githubusercontent.com/80108653/133720553-55e06723-e45b-46d0-bc01-964af0914377.jpg)
2.Some bone is Null
![20210917122355_1](https://user-images.githubusercontent.com/80108653/133720554-8ad64583-1fac-4ed1-b86b-add9bfca7b24.jpg)
3.Increase Bones
![20210917122458_1](https://user-images.githubusercontent.com/80108653/133720549-fc4a4515-5e48-441e-b22c-8f06aa6833e9.jpg)
4.Decrease Bones
![20210917122424_1](https://user-images.githubusercontent.com/80108653/133720561-a8deb8f0-39e9-4f07-8e12-b07cb3af9d8c.jpg)
5.BoneList is None
![20210917122653_1](https://user-images.githubusercontent.com/80108653/133720562-1693de50-916f-45ff-b61d-db5eb717d728.jpg)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2021.9.16.105

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### Reporters

Aetoriz#1794 (Username: Aetoriz)
orange#1901 (Username: orange)

**Comment by Frooxius** [comment]
Fixed in 2021.9.21.357, thank you for the report!
