### ISSUE TITLE
Is Character On Ground appears to not be communicated over the network

### ISSUE THREAD

**Issue by iamgreaser** [Neos-Metaverse/NeosPublic#3022]
### Describe the bug?

The "Is Character On Ground" node returns False for anyone who isn't using a given character controller.

This can be worked around by writing

### Relevant issues

No.

### To Reproduce

Use the LogiX code in the screenshot, substituting the name in there for your own user. Stand on the ground. Notice how the output of the "Is Character On Ground" node says "True". Now ask someone else what it says. It will, at the time of writing, say "False" for anyone other than yourself.

### Expected behavior

The "Is Character On Ground" node should report the on-ground state of the relevant simulating user across the network.

### Screenshots

![image](https://user-images.githubusercontent.com/138113/133726144-291e4314-269d-4194-8fb5-fe2f5015efe1.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.16.105

### What Platforms does this occur on?

Windows, Linux

### Did this work before?

I Don't Know

### Additional context

This was specifically to drive the flapping speed on the wings on emmy7's avatar.

A workaround is to run a Timer (ticking, say, every 0.1 seconds) for the owning user (I actually used "Local User" and filtered it with an "==" node and an "If" node), and use the impulse out of that to driver a "Write" node into a "bool" variable. Then said variable is used as a substitute for the on-ground state.

The bug has existed for at least the past 2 or 3 days.

### Reporters

emmy7 (applied mechanism to avatar), DarkSugar, ipie4fun, Parziival (these 3 pointed out that the mechanism was broken over the network), GreaseMonkey (built a workaround for this bug).

**Comment by H3BO3** [comment]
This is normal and is not a bug, nor a regression - #714 Use a Fire On Change and replicate the value as desired if other people need to use it as well.
