### ISSUE TITLE
Trigger Colliders don't work for Desktop Users with Raycast Disabled

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#3025]
### Describe the bug?

Ran into this bug tonight with German Gunner. We were wondering why one of our objects we were using for our MMC project was not working correctly for Desktop Mode. We deduced that the trigger collider was not working for him being in desktop mode due to the ignore raycast option being turned on. I can provide the object or recreate it. 

### Relevant issues

None that I could find

### To Reproduce

1. RawDataTooltip a box and turn that box into a trigger Collider
2. Be in desktop mode
3. Try to interact with another user and find out that the trigger collider will not behave as intended. 

### Expected behavior

Ideally the collider should still trigger even though that raycasts are disabled.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Latesr

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

Turk, German Gunner

**Comment by shiftyscales** [comment]
Can you please submit a replication item/world? Your replication steps don't make sense to me. Like- what do you mean by "RawDataTooltip a box and turn that box into a trigger Collider" is the RawDataTooltip necessary for replication in some way? Can you not achieve the same result by just using a box on its own set to a trigger collider and ignore raycasts?

Does this happen both with static/non-static and the auto trigger types?

**Comment by TehTurk** [comment]
I cannot, it seems I can't replicate it even though it was something I had checked last night as it resolved my issue. Apologies on my end. Probably shouldn't be making issues before I go to bed, but if not I'll forget to note them down. I will close this and if I ever find it again I'll reopen a new one. Thank you for the response and time.
