### ISSUE TITLE
DynamicBoneSphereCollider doesn't interact with DynamicBoneChain

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#3028]
### Describe the bug?

An aparent regression, possibly either as a result of the bepuv2 upgrade, or the recent dynamic bone chain work, DynamicBoneSphereColliders placed under an avatar no longer collide with DynamicBoneChains on an avatar.

E.g. my hair clips through my chest because the DynamicBoneSphereColliders in my chest are non-functional.

The green visuals appear in the correct places, and sizes for where the colliders should be but when visualizing the DynamicBoneChain's bones and colliders, they aren't affected at all by the DynamicBoneSphereColliders.

### Relevant issues

N/A

### To Reproduce

- Have a DynamicBoneSphereCollider setup under an avatar using the DynamicBonePlayerColliders component
- Attempt to interact with a DynamicBoneChain using the sphere collider
(The above can be replicated in VR by using the avatar in: neosrec:///U-Shifty/R-67bd3c06-6b06-4186-8f2f-7a9892e86512 )

### Expected behavior

The DynamicBoneSphereCollider should collide with the DynamicBoneChains it touches.

### Log Files

No exceptions/unusual output in the log from a session replicating this issue.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.16.105

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

neosrec:///U-Shifty/R-67bd3c06-6b06-4186-8f2f-7a9892e86512

### Did this work before?

Yes

### If it worked before, on which build?

Uncertain, possibly pre-bepu2

### Additional context

Discovered when I realized that my DynamicBoneSphereColliders weren't interacting with my DynamicBoneChains when they used to.

### Reporters

Shifty

**Comment by Frooxius** [comment]
I'm checking the code for what it might be, is the DynamicPlayerCollision on those bones set to True or False?

**Comment by shiftyscales** [comment]
DynamicPlayerCollisions are enabled, but it didn't appear to work in either configuration from what I saw.

**Comment by Sox-NeosVR** [comment]
so i noticed that recently all the 'Static Colliders' in the DynamicBone component got cleared and i had to re-add them to the list,  not sure on the cause of this but thats what i discovered.

**Comment by Frooxius** [comment]
Fixed this in 2021.9.21.357! The components were never actually fetched from the user so they were just ignored. Thanks for the report!

@Sox-NeosVR That sounds like something else, I'd recommend a separate issue.
