### ISSUE TITLE
Precision Grab on avatars without fingers

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3031]
### Is your tweak request related to a problem? Please describe.

Precision grab does not work on avatars that do not have fingers.

### Describe what would you like tweaked

Add a way to use precision grab without having fingers to determine its position.
(Additionally it'd be neat if this could also be used to override the default positioning even if the avatar has hands.)

### Describe alternatives you've considered

1. Not using precision grab.
2. Adding invisible fingers just for this.
3. Custom logix recreation.

**Comment by Earthmark** [comment]
Having a fixed point may be good for avatars with fingers as well, it may be difficult for users to know where their fingers coverage.

**Comment by Psychpsyo** [comment]
> 
> 
> Having a fixed point may be good for avatars with fingers as well, it may be difficult for users to know where their fingers coverage.

Definitely. Which is what I was getting at with "Additionally it'd be neat if this could also be used to override the default positioning even if the avatar has hands.".
