### ISSUE TITLE
ValueTextFormatDriver<string> allows Source and Text to be the same

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#3037]
### Describe the bug?

When using `ValueTextFormatDriver<string>`, you can set `Source` and `Text` to the same reference, which results in a recursive string modification on each frame.
If the `Format` input has multiple copies of the argument, this results in exponential increases in string length, which can result in the Noes client freezing.

Additionally, this component does not respect its enabled state.

### Relevant issues

None

### To Reproduce

1. Create an empty object
2. Attach a `ValueField<string>`
3. Attach a `ValueTextFormatDriver<string>`
4. Set `Format` to `a{0}` as a safe value. Values containing multiple arguments (such as `a{0}{0}` ) result in a client freeze
5. Set `Source` to reference the ValueField
6. Set `Target` to reference the ValueField
7. Observe that the length of the string increases by one each frame.

### Expected behavior

Component should disable itself when put in an invalid state, or the reference field should reject the connection somehow.

### Screenshots

Before setting source:
![Before](http://files.aerizeon.net/sharex/2021/2021-09-19_01-16-Neos_7Cu10MJHrm.png)
After setting source:
![After](http://files.aerizeon.net/sharex/2021/2021-09-19_01-17-Neos_sjFzZwWwsf.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.16.105

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Additional context

This might be more of a tweak than a bug - but I wasn't sure how to classify it.
I spoke briefly to ProbablePrime, and he suggested that it was something worth reporting.

### Reporters

Epsilion
Psychpsyo
Ukilop

**Comment by Frooxius** [comment]
Fixed this in 2021.9.20.1334. There's also additionally upper cap on the length of the string, currently set pretty large, but should stop unbounded growth.

With hard permission system in the future we'll have a more global and flexible way of handling cases like this.

Thanks for report!
