### ISSUE TITLE
BakeMeshes node removes SimpleAwayIndicator

### ISSUE THREAD

**Issue by orange3134** [Neos-Metaverse/NeosPublic#3038]
### Describe the bug?

Using the BakeMeshes node, setting Destroy Original to False and baking the avatar to Static Mesh will remove the SimpleAwayIndicator from the original.

### Relevant issues

none

### To Reproduce

1. Connect the avatar's root slot to the BakeMeshes node.
2. Make all Boolean inputs False.
3. Run BakeMeshes.
4. SimpleAwayIndicator has been removed from the original.

### Expected behavior

SimpleAwayIndicator is not deleted.
The original will not be changed at all.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.16.105

### What Platforms does this occur on?

Windows

### Did this work before?

No

### Additional context

A video showing that the SimpleAwayIndicator is removed from the original immediately after using Bake Meshes.
https://youtu.be/iX8poks246w

### Reporters

alicewiz
orange

**Comment by Frooxius** [comment]
This has been fixed in 2021.9.20.1334. Thank you for the report!
