### ISSUE TITLE
Additional WebSocket connections on one User to the same destination are send-only

### ISSUE THREAD

**Issue by Banane9** [Neos-Metaverse/NeosPublic#3043]
### Describe the bug?

Currently working on the Spotify status panel to show and control playback details from within Neos.  
Spawning extra ones connects the WebSocket, but they don't receive update data - however they can send commands like pause just fine.  
This also applies across worlds, not just when they're both in one.

### Relevant issues

None as far as I could tell.

### To Reproduce

1. Have a running web socket server that sends data to connected clients and logs incoming data.
2. Connect two WebSocketClients on the same user to the same endpoint.
3. Observe that only the first client receives data, but both can send.

### Expected behavior

Additional WebSocketClients connecting to the same endpoint should behave just like the first, receiving and sending data, in any world.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.16.105

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

Banane9#5929

**Comment by Frooxius** [comment]
Does this not happen if you use external websocket solution/library? E.g. when you use this: https://github.com/sta/websocket-sharp

This sounds like something that might be on the end of the app. The WebSocket connections in Neos are completely independent, so it's possible that the target app simply can't handle multiple destinations that are the same host properly.

**Comment by Banane9** [comment]
It's funny you mention that, because I'm using exactly that library for the project. You can find the WebSocketBehavior class here:  
https://github.com/Banane9/NeosSpotifyStatus/blob/master/NeosSpotifyStatus/SpotifyPlaybackService.cs

I was checking with the console yesterday to make sure that updates were being sent out, but they didn't arrive in Neos.  
This is double confusing also, because @shadowpanther reported that his HRM works fine with multiple connections.

**Comment by Banane9** [comment]
Okay, I have tested with a separate console client and fixed a problem I accidentally introduced during some refactoring today - but the problem in game persists.

I did however forget the funkiest part of this all: After unpacking the logix doing the websocket handling, things work again.
Could this have to do with using a dynamic variable as the input for the event listener nodes?

![WebSocket listener Logix](https://user-images.githubusercontent.com/2124570/133937200-89f2b7e0-9861-45a2-9037-a9881d09a9aa.png)

**Comment by Frooxius** [comment]
> 
> 
> It's funny you mention that, because I'm using exactly that library for the project. You can find the WebSocketBehavior class here:
> https://github.com/Banane9/NeosSpotifyStatus/blob/master/NeosSpotifyStatus/SpotifyPlaybackService.cs
> 
> I was checking with the console yesterday to make sure that updates were being sent out, but they didn't arrive in Neos.
> This is double confusing also, because @shadowpanther reported that his HRM works fine with multiple connections.

No. What I mean is, if you use that library to connect to the Spotify service, same way you do from Neos.

**Comment by Banane9** [comment]
I have done that, check the last comment.

![multiple clients at the same time getting updates](https://user-images.githubusercontent.com/2124570/133939183-a574934e-ddfb-49d0-94d9-b1ef2248afb5.png)

The actual problem is, that the receiver node doesn't fire when messages come in until the logix is unpacked. Once repacked it continues working.

**Comment by shadowpanther** [comment]
Passing an object reference via a dynvar to an event-generating node strikes again? I remember that having problems with controller input nodes.

**Comment by Frooxius** [comment]
Oh sorry I missed that part, I thought it was only on the receiving side. It's a   bit strange, I'll have to have a deeper look.

**Comment by Frooxius** [comment]
> 
> 
> Okay, I have tested with a separate console client and fixed a problem I accidentally introduced during some refactoring today - but the problem in game persists.
> 
> I did however forget the funkiest part of this all: After unpacking the logix doing the websocket handling, things work again.
> Could this have to do with using a dynamic variable as the input for the event listener nodes? Adding an updating relay inbetween made no difference.
> 
> ![WebSocket listener Logix](https://user-images.githubusercontent.com/2124570/133937200-89f2b7e0-9861-45a2-9037-a9881d09a9aa.png)

I'm a little bit confused by this. Do you have two connections or just two event receivers? 

From the screenshot it looks like you've shared it looks like you have a single instance of WebSocketClient shared to multiple receivers.

Is there a way to reproduce this problem to a simplest case? I'd really like to avoid spending time chasing down issues that could be just problem with a complex setup.

**Comment by Banane9** [comment]
Each panel has a setup like that - it's just a websocket event receiver for open / close events at the top and a string message receiver below.

But disregard the multiple connections part anyways, I just forgot about it working after unpacking (and optionally repacking) the logix.

**Comment by Frooxius** [comment]
Can you make an issue with proper simplified repro for the actual problem please?

Since this original issue was caused by error in your setup, we're not likely going to invest more time into it unless we're sure that it's an actual reproducible bug in Neos.

**Comment by Banane9** [comment]
I have commented to add this to the list of known dynamic reference variable issues for #1242, as that's the actual problem.
