### ISSUE TITLE
Filltering options for 'Contacts'

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#3046]
### Is your tweak request related to a problem? Please describe.

Heavy Contact lists. so many times freezes when open "Contact" page.

### Describe what would you like tweaked

I have a contact list of 697 people, but the number of people online these days is about 30. Also, due to the large number of people, when I actually contact a particular person, I don't directly select them if they are offline, but instead type in their name to contact them. Therefore, if we could filter the list when it is generated to only include the 30 or so people who are online, instead of creating a slot for 697 people each time, it would be lighter and easier to view.

>自分の連絡先リストは、697人いるのですがここ最近のオンライン人数は30人程度です。また、人数が多いため実際に特定の人に連絡を行う際、その人がオフラインの場合は直接選ばず、名前を入力して連絡を行うようにしています。そのため、もし697人分のSlotを毎回作るのではなく、オンラインである30人程度の分だけのリストに生成時にフィルタリングすることができれば、動作も軽くなるし見る時も見やすくなると思います。

### Describe alternatives you've considered

I don't know. At least not in a straightforward way.

> ないと思います。少なくとも正攻法では。

### Additional context

I know that Contact Page does UI Overhaul, so it would be great if you could implement it as part of that.

> Contact PageはUI Overhaulを行うことは知っているので、その一環として実装してくれるとありがたいです。

**Comment by epicEaston197** [comment]
I also have the same problem but I was thinking you would only be able to view 50 and if you go down far enough it would load in another 50

**Comment by Frooxius** [comment]
I'm sorry, but I do not plan on adding this functionality to the current contacts UI. We are not making any more incremental changes and tweaks to it.

We plan to completely redesign the contacts UI, which will include this functionality as stated on our roadmap: https://github.com/Neos-Metaverse/NeosPublic/projects/2#card-61033401

**Comment by shiftyscales** [comment]
As mentioned, the UI itself is planned to be reworked in its entirety to addess its various issues. We do not need GitHub issues for things already on the roadmap. Thanks for your suggestion.

**Comment by kazu0617** [comment]
oh sorry. so if i want to sent this issue as priority issue, issue num is #299 not #3046 ?
