### ISSUE TITLE
URI input field crashes the session if a non-host user backspaces the contents

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#3048]
### Describe the bug?

If a non-host user spawns an URI, types something into it and then starts backspacing, the session crashes.

### Relevant issues

* #2995 
* #3010 

### To Reproduce

* Join a session (you must not be the host)
* Spawn an URI input node
* Type something random into it
* (unsure whether needed) Hit Enter to finalize the edit
* Click into the URI input again
* Hit Backspace to delete the contents

### Expected behavior

The session works, the contents of the URI is modified according to user inputs

### Log Files

My headless (the host of the session): [manul - 2021.9.20.1334 - 2021-09-21 03_02_45.log](https://github.com/Neos-Metaverse/NeosPublic/files/7199288/manul.-.2021.9.20.1334.-.2021-09-21.03_02_45.log)
My desktop (the non-host user): [VIXEN - 2021.9.20.1334 - 2021-09-21 02_58_43.log](https://github.com/Neos-Metaverse/NeosPublic/files/7199293/VIXEN.-.2021.9.20.1334.-.2021-09-21.02_58_43.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.20.1334

### What Platforms does this occur on?

Windows, Linux

### Did this work before?

I Don't Know

### Reporters

josh fluffy# 7530
Shadow Panther# 5154
jeana# 0405
bigtin# 8570
bryce101# 6096

**Comment by Frooxius** [comment]
Fixed in 2021.9.21.357, the encoding/decoding of Uri should be a lot more robust now, thanks for the report!
