### ISSUE TITLE
Crashes with no known cause

### ISSUE THREAD

**Issue by Wolfiesmith101** [Neos-Metaverse/NeosPublic#3049]
### Describe the bug?

randomly with no continuity i crash. 

there is no factors surrounding it

no item pullouts, no world changes. just sitting there and suddenly crash its been happing for about two weaks

### Relevant issues

No i have not

### To Reproduce

Unkown? just exisit?

### Expected behavior

i still do not know

### Log Files

[error.log](https://github.com/Neos-Metaverse/NeosPublic/files/7199367/error.log)
[Player.log](https://github.com/Neos-Metaverse/NeosPublic/files/7199368/Player.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

1.9.20.1334

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

entropy#1062

**Comment by Electronus** [comment]
do you have the log from your neos install folder?

**Comment by Frooxius** [comment]
Thanks for the report. This looks like a crash of the Unity engine itself. We another report for this here: #3026 so I'm closing this one as duplicate.

The main thing right now is just updating the Unity engine version itself and seeing if that resolves things, but that's currently blocked by the Color Management update.
