### ISSUE TITLE
Contact List Doesn't Reflect Changes Properly

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#3050]
### Describe the bug?

When sending other people Contact Requests, the status of that request doesn't update unless it's accepted. When the user ignores it, it stays showing as "Request Sent". 

If you remove someone from your contacts (Or they remove you) you'll still show up as each other's contacts, except you(they) can no longer message them(you), see their(your) online status or what worlds they're(you're) in. 

This is problematic and confusing for new users (and even old users) when sorting through your contact list, or trying to join someone but wondering why you can't message them.

### Relevant issues

#2775 not having information update properly when looking at contact request information.

### To Reproduce

1. Send a contact request to a user.
2. Have them ignore that request (Actually pressing the button)
3. See that they remain in your contact list.

1. Have an existing contact remove you
2. See that they're still in your contacts, but message box is greyed out, online status doesn't show or what worlds they have open/focused. `(I know that's intended behavior but the contact shouldn't be in your list anymore)`

### Expected behavior

When ignoring a contact request, it should remove you from their contact list. Not persist as "Request sent"

When unfriending a user, it should remove you from their contact list. So when you'd like to re-add each other. You don't have to make sure you're both removed so the request can be properly sent again. When you're still marked as their contact (because you removed them) they can't receive another contact request until they also remove contact.

### Log Files

/////

### Screenshots

![image](https://user-images.githubusercontent.com/53165730/134106539-eb6993eb-8d09-4abd-a84a-380262b6eff3.png)
![image](https://user-images.githubusercontent.com/53165730/134106555-02b2d010-9320-4b7d-93b9-e9a82fb3651e.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.20.1334

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### Did this work before?

Yes

### If it worked before, on which build?

Every Build I'm Aware Of.

### Reporters

AshtonSparx#5050

**Comment by Frooxius** [comment]
This is intentional behavior to prevent abuse. "Ignore" means just that - it's ignored. You can't tell on your end if they rejected it or not.

Similarly if you remove them from your contact list, removing you from theirs would be invasive and give you sole control, to keep sending them contact requests.

**Comment by AshtonSparx** [comment]
I'm unsure what you mean by abuse. Because you can still tell if they ignored your request or if they removed you. As you can't send them messages anymore. Which will still result in confrontation when both user's find themself in the same world, all this does is cause confusion on the user's end when they go to message someone, but can't. I understand not wanting the user to be able to "Spam requests" but then at that point, it would be a moderation issue regarding harassment. Which would be against Community Guidelines

**Comment by H3BO3** [comment]
> When unfriending a user, it should remove you from their contact list. So when you'd like to re-add each other. You don't have to make sure you're both removed so the request can be properly sent again. When you're still marked as their contact (because you removed them) they can't receive another contact request until they also remove contact.

I have noticed this causing issues. People unfriending someone for various reasons, and later on, they want to be contacts again but the state of the contact is confusing. I hope this system will be reworked to be more-or-less "normal" once User Blocking is in place.

**Comment by Frooxius** [comment]
I don't understand what do you mean. You shouldn't be able to send messages to Contact that haven't accepted in the first place, so you shouldn't be able to tell if they never saw the request or just ignored it.

Harassment is moderation issue, but there is no reason to open up a hole on purpose and increase the number of reports moderators have to deal with.

If not that, it's still confusing if your contact suddenly disappears, so it reverting to unaccepted contact is better behavior than it inexplicably going away.

**Comment by AshtonSparx** [comment]
> If not that, it's still confusing if your contact suddenly disappears, so it reverting to unaccepted contact is better behavior than it inexplicably going away.

Discord already does this by default. If I remove you from my friends list on discord, you vanish for both sides. Doing a quick search can tell you your result if they removed you. 

> I don't understand what do you mean. You shouldn't be able to send messages to Contact that haven't accepted in the first place, so you shouldn't be able to tell if they never saw the request or just ignored it.

My apologize for the confusion, I did not mean that you should be able to send them messages if they ignored your request!

**Comment by Frooxius** [comment]
Neos isn't Discord. There's a number of communication platforms, each with different handling of contacts.

**Comment by H3BO3** [comment]
There seems to be a possible bug that's the root cause of the "confusing" behavior I've been noticing. It follows:

- Person A and Person B are contacts.
- Person A removes person B. Person B does not notice this and their view of Person A's contact listing goes to the "Request Sent" state.
- Person A decides later they want to be contacts with Person B again.
- Person A sends Person B a contact request.
- Person B never sees this contact request since their view of the contact still seems to be stuck on the "Request Sent" state. The bug is here. They never know Person A wants to be contacts again.
