### ISSUE TITLE
Headless client can't save the world (CreateWorldThumbnail)

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#3051]
### Describe the bug?

While trying to save the currently open world (autosave or manual), the headless throws an exception and the save does not happen. The exception mentions CreateWorldThumbnail, so most likely it's caused by the newly added custom thumbnail feature.

### Relevant issues

None that I know of

### To Reproduce

- Run a headless with a world that the headless normally can save (owned by user, cloud save)
- Try to `save` the world or let it do the `autoSave`

### Expected behavior

World saves

### Log Files

[manul - 2021.9.21.357 - 2021-09-21 11_25_13.log](https://github.com/Neos-Metaverse/NeosPublic/files/7201633/manul.-.2021.9.21.357.-.2021-09-21.11_25_13.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.21.357

### What Platforms does this occur on?

Linux

### Did this work before?

Yes

### If it worked before, on which build?

2021.9.16.105

### Reporters

Rucio#0134
Shadow Panther#5154

**Comment by Frooxius** [comment]
Fixed in 2021.9.21.1057, thanks for report!
