### ISSUE TITLE
Default value for ParentValueLink

### ISSUE THREAD

**Issue by guheheP** [Neos-Metaverse/NeosPublic#3060]
### Is your tweak request related to a problem? Please describe.

It's not a big problem, but I am feeling a little inconvenienced about the usage of ParentValue.

### Describe what would you like tweaked

I want to set the default value for ParentValueLink.
Expect the default value to be driven when ParentValue is not found.
Just like DynamicValueVariableDriver.

This allows me to control the value of Grabbable etc. with fewer components when parenting a Slot.

### Describe alternatives you've considered

Add a Default Value to the ParentValueLink

**Comment by Frooxius** [comment]
Added in 2021.9.22.1431, thanks for request!
