### ISSUE TITLE
RTF Formatting Not Stripped When Saving Tags

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#3061]
### Describe the bug?

An automatic feature Neos does behind the scenes is add every word in a world's title into the tags. The problem is, it doesn't seem to strip formatting before it does this and in turn seems to end up saving the keywords of the formatting into the tags too.

### Relevant issues

None found.

### To Reproduce

Use RTF in a world name and then save it, e.g.

This is <color=red>My</color> <color=blue>World</color!

You'll find your tags are now the tags you added yourself, as well as these having been added automatically:
this is color red my blue world

While the words "this is my world" being added are fine, I doubt people want "color red blue" added as well.

### Expected behavior

For rich text formatting to be stripped prior to the automated name parsing being performed.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.6.614

### What Platforms does this occur on?

Windows

### Did this work before?

No

**Comment by Frooxius** [comment]
Fixed in 2021.9.22.1431, thanks!
