### ISSUE TITLE
String Insert Node returns null when index = length

### ISSUE THREAD

**Issue by Banane9** [Neos-Metaverse/NeosPublic#3065]
### Describe the bug?

The String Insert Node returns null when the insertion index is equal to the length of the string that's being inserted into.

Found this with Uki when he showed off his MMC project earlier.

### Relevant issues

None

### To Reproduce

Get a the node, put in a string and set the insertion index to the string's length.

### Expected behavior

The expected behavior would be, that the insertion-string is appended to the end.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.22.1431

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

Banane9#5929
Ukilop#4463

**Comment by Frooxius** [comment]
Fixed in 2021.9.27.743, thanks for report!
