### ISSUE TITLE
Cache/database clean up

### ISSUE THREAD

**Issue by Electronus** [Neos-Metaverse/NeosPublic#3079]
### Is your feature request related to a problem? Please describe.

It is not unusual for a user to come to the discord asking why their data base is corrupting or why they are having other issue, and finding that NEOS has filled their C drive.

I wrote a small program to clean my cache of any files not used in X number of days, but it would be nice if neos did this automatically. 

### Relevant issues

https://github.com/Neos-Metaverse/NeosPublic/issues/58   -this however is about the location and not managing the size

### Describe the solution you'd like

I would like NEOS to clean up its own files that have not been used in a while, perhaps at the same period as the automatic logout. 

### Describe alternatives you've considered

I wrote a program to clean my files for me by access date, but i doubt most useres can be expected to, or could, do the same.

**Comment by Frooxius** [comment]
We already have a topic for that here: https://github.com/Neos-Metaverse/NeosPublic/issues/2473

**Comment by Electronus** [comment]
Ah i was looking for "cache" i see.
