### ISSUE TITLE
I want a component to dynamically override my viewpoint

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3092]
### Is your feature request related to a problem? Please describe.

right now on my avatar I have a interaction to make my avatar sit down but my viewpoint does not move to my head
I also wanted to respect enabled state when it's disabled it will go back to default view point
![image](https://user-images.githubusercontent.com/76523692/134830376-2972294e-65f6-4dd9-b11e-6c63aea2174b.png)

### Relevant issues

none that I could find 

### Describe the solution you'd like

I would like to have a view override component that can accept a empty slot and this will move my viewpoint down or wherever the object is also it will respect enabled state when it's disabled it will go back to default view point

### Describe alternatives you've considered

I don't know this but this is not preferable
this is me pressing F6 and moving my viewpoint down manually
![image](https://user-images.githubusercontent.com/76523692/134830635-df1825fa-8a99-404e-a247-2e8f5afa0753.png)

### Additional context

I don't feel like I need to describe it more 

I don't know if this is already a thing. 
I have spoken to many people and none of them know how to do it

**Comment by shiftyscales** [comment]
This component already exists, @epicEaston197. It is the `AvatarUserRootOverrideAssigner` component which you can find in Users > Common Avatar System.
