### ISSUE TITLE
Why does the 4 bones per vertex limitation exist?

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Neos-Metaverse/NeosPublic#3093]
### Where have you searched for this information before making this issue?

I have looked around the Neos Wiki, and asked around on the Discord, and someone did link a Unity page about `QualitySettings.skinWeights` (linked here: https://docs.unity3d.com/ScriptReference/QualitySettings-skinWeights.html)

### Which part of the system do you need information on?

There appears to be a hard limit on how many bones can be weighted to one vertex, and the only way of really find this is through some very irritating trial and error.

### What information do you need to know?

I'd ideally like to know how many bones a single vertex can be weighted to, and as well as why the limitation exists within Neos.

### Do you plan to format and contribute the provided information to Wiki?

No

**Comment by Frooxius** [comment]
Because support for more than 4 isn't currently implemented as noted in: https://github.com/Neos-Metaverse/NeosPublic/issues/3094
