### ISSUE TITLE
I want nodes to detect if I'm in F5 mode or UI focus mode 

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3095]
### Is your feature request related to a problem? Please describe.

I think what I said makes it pretty clear there is no way to my knowledge to know if someone's in F5 mode or UI Focus mode
so having these nodes would be pretty handy

like a my case I want to know if my viewmodel is active
which I can do
but I can't see if I'm in F5 mode or UI Focus mode
which makes it difficult to manipulate the camera like I want to do
![image](https://user-images.githubusercontent.com/76523692/134942396-7a0b3ec3-4f29-4304-b60f-cad4a15ed5a3.png)
### Relevant issues

none that I can find
### Describe the solution you'd like

I would like the two nodes to act like the user view reference active
![image](https://user-images.githubusercontent.com/76523692/134942094-b9b95bd7-e218-4bbd-9f60-079dc15ba83a.png)

### Describe alternatives you've considered

but this is not very preferable it adds complexity on top of my already complex system it will be more optimized if it was one node
![image](https://user-images.githubusercontent.com/76523692/134956932-b71fbae8-b4fc-4ae6-bce5-0f51bfd82a95.png)

**Comment by Zyzyl** [comment]
See https://wiki.neos.com/User_Active_View_Targetting_Controller_(LogiX_node)

I think that gives you the info you're wanting, if not a bool directly

**Comment by epicEaston197** [comment]
> See https://wiki.neos.com/User_Active_View_Targetting_Controller_(LogiX_node)
> 
> I think that gives you the info you're wanting, if not a bool directly

I don't see those nodes anywhere

**Comment by Earthmark** [comment]
Middle row far left

**Comment by epicEaston197** [comment]
you don't get it that's not an output I want at all

![image](https://user-images.githubusercontent.com/76523692/134950616-3f3c38c9-642b-4867-b367-2b45d1066207.png)

**Comment by H3BO3** [comment]
Just use an enum equality check to get a bool

**Comment by epicEaston197** [comment]
why can this be more simple like the nodes I described it seems a little over complicated

**Comment by Earthmark** [comment]
Drag the output to an == node to get it to use the correct overload, then drag from the other pin of the == node and press secondary, it should create an input pin that you can select a value to compare against.

**Comment by Earthmark** [comment]
That would be significant more straightforward, I agree. I personally have no idea what a `view targeting controller` is so it's opaque to me as well.

Looking at the wiki it does say the enum values are fairly self descriptive though. Perhaps the node could be renamed to more easily suggest what it can be used for?

**Comment by epicEaston197** [comment]
or maybe heavyset a Boolean values

> I agree a node named `is third person` would be significant more straightforward. I personally have no idea what a `view targeting controller` is so it's opaque to me as well.
> 
> Looking at the wiki it does say the enum values are fairly self descriptive though. Perhaps the node could be renamed to more easily suggest what it can be used for?

or maybe the note could be modified to have a set of  4 Boolean values 
1 FirstPerson
2 ThirdPerson
3 Freeform
4 UI_Targetting

**Comment by ProbablePrime** [comment]
I don't think we'll be changing this. 

In Logix and in general programming its much more important to determine exactly what someone is doing. For your setup here, you'd have to do a bunch of AND, OR or NOT operations to get the desired outcome from your proposed node. Setup.

With the current setup you just need a single == node to check exactly which mode you're in.

Its really easy just plug in a ==.

**Comment by epicEaston197** [comment]
> I don't think we'll be changing this.
> 
> In Logix and in general programming its much more important to determine exactly what someone is doing. For your setup here, you'd have to do a bunch of AND, OR or NOT operations to get the desired outcome from your proposed node. Setup.
> 
> With the current setup you just need a single == node to check exactly which mode you're in.
> 
> Its really easy just plug in a ==.

do you mind going into more detail I have nothing to compare it to
![image](https://user-images.githubusercontent.com/76523692/134962029-b2c9c56c-f16f-4658-91ce-e2221d394a8c.png)

**Comment by ProbablePrime** [comment]
Pull a ribbon/wire from the second input to == then push R, it'll spawn an Enum Input node.

Alternatively you can go to Input -> Enum Input and find the same color but the ribbon + R is probably easier.

**Comment by epicEaston197** [comment]
> Pull a ribbon/wire from the second input to == then push R, it'll spawn an Enum Input node.
> 
> Alternatively you can go to Input -> Enum Input and find the same color but the ribbon + R is probably easier.

I am still very confused

**Comment by H3BO3** [comment]
What part are you confused about?

**Comment by epicEaston197** [comment]
![image](https://user-images.githubusercontent.com/76523692/134963560-8e417f68-1639-47c2-8b21-122396a494dc.png)

**Comment by H3BO3** [comment]
It might not be in there. Just pull a ribbon from the other input on the == node and hit R

**Comment by epicEaston197** [comment]
are you talking about doing Biz cuz this does nothing
![image](https://user-images.githubusercontent.com/76523692/134963813-03a31d24-ecd7-403e-bbc4-7ed5d634b17f.png)

**Comment by ProbablePrime** [comment]
Its not an Enum, Easton has every right to be confused. 

Apologies we would need a node here.

**Comment by H3BO3** [comment]
ohhh well I guess that explains it. Sorry Easton

**Comment by epicEaston197** [comment]
you good

**Comment by Aerizeon** [comment]
Wouldn't you just use the new `Type` input node for this? 

And then use that input to construct the type you want to use compare against?

**Comment by epicEaston197** [comment]
![image](https://user-images.githubusercontent.com/76523692/134972564-a95268fd-6843-47b9-a01d-ce68a64e6636.png)


> Wouldn't you just use the new `Type` input node for this?
> 
> And then use that input to construct the type you want to use compare against?
> 
> It appears to be the same color, and from memory that ribbon is for `Type`

one problem it's used for reflection probes

**Comment by Aerizeon** [comment]
It's not an enum, Easton.

It's under Input > Type

**Comment by epicEaston197** [comment]
![image](https://user-images.githubusercontent.com/76523692/134973245-928b155b-b5b0-40b4-b2f8-6ae3c97c0628.png)

**Comment by Frooxius** [comment]
These nodes already exist, the UserActiveViewTargettingController gives you the current controller. Using GetType you can its type and compare against the types defined on the Wiki with the Type node: https://wiki.neos.com/User_Active_View_Targetting_Controller_(LogiX_node)

You're comparing it against completely random unrelated enums, so those won't work and will be different colors because they're random and unrelated.
