### ISSUE TITLE
(Website) Sign-In link on Neos.com and Neosvr.com points to account.neosvr.com which does not resolve

### ISSUE THREAD

**Issue by Bontebok** [Neos-Metaverse/NeosPublic#3096]
### Describe the bug?

The sign-in link on https://neos.com or https://neosvr.com points to account.neosvr.com which does not resolve.

https://account.neos.com/ does resolve, so it looks like the link needs to be updated.

### Relevant issues

I didn't find any entries on Discord or here.

### To Reproduce

Visit https://neos.com or https://neosvr.com and click on the Sign-In link.

### Expected behavior

Reach the account sign in page.

### Log Files

```
dig @javier.ns.cloudflare.com account.neosvr.com

; <<>> DiG 9.16.1-Ubuntu <<>> @javier.ns.cloudflare.com account.neosvr.com
; (6 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 13272
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;account.neosvr.com.            IN      A

;; AUTHORITY SECTION:
neosvr.com.             3600    IN      SOA     javier.ns.cloudflare.com. dns.cloudflare.com. 2038440924 10000 2400 604800 3600

;; Query time: 8 msec
;; SERVER: 2606:4700:58::a29f:2ccc#53(2606:4700:58::a29f:2ccc)
;; WHEN: Mon Sep 27 15:25:25 EDT 2021
;; MSG SIZE  rcvd: 108

dig @serena.ns.cloudflare.com account.neosvr.com

; <<>> DiG 9.16.1-Ubuntu <<>> @serena.ns.cloudflare.com account.neosvr.com
; (6 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 60419
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;account.neosvr.com.            IN      A

;; AUTHORITY SECTION:
neosvr.com.             3600    IN      SOA     javier.ns.cloudflare.com. dns.cloudflare.com. 2038440924 10000 2400 604800 3600

;; Query time: 4 msec
;; SERVER: 2606:4700:50::adf5:3adc#53(2606:4700:50::adf5:3adc)
;; WHEN: Mon Sep 27 15:27:44 EDT 2021
;; MSG SIZE  rcvd: 108



```

### Screenshots

![accountsnotloading](https://user-images.githubusercontent.com/23562523/134973647-eae3a8ea-a1fe-4084-b7b7-411b70a96d34.PNG)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

N/A

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### Did this work before?

Yes

### If it worked before, on which build?

Maybe two weeks ago?

### Reporters

Me: Rucio#0134

**Comment by Bontebok** [comment]
Additionally, the Privacy Policy link on https://account.neos.com/ is also broken.

![badprivacylink](https://user-images.githubusercontent.com/23562523/134975769-5c09eb4e-18bc-41d7-a02e-d473efd7e067.png)
:

**Comment by shadowpanther** [comment]
https://account.neosvr.com worked for me recently (doesn't work at the moment), so this is likely not something intentional.

**Comment by RaithSphere** [comment]
Well spotted, I have passed this over to who takes care of the DNS/Website stuff

**Comment by shadowpanther** [comment]
Looks like account.neosvr.com and wiki.neosvr.com are resolving correctly again.
