### ISSUE TITLE
Error recalculating blendshape normals with smooth shading

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#3098]
### Describe the bug?

Attempting to use the "Recalculate Blendshape Normals (smooth shading) option throws an exception and fails to process. This appears to occur across various avatars, but not all avatars.

I've not been able to identify a specific condition under which some models will work and others won't.

An example avatar I've found this issue occurs with is the eye and lip tracking demo avatar found here: neosrec:///G-Neos-Team/R-d3f68803-8afe-4672-ac50-ef7b341068db

### Relevant issues

#3075 as this bug pertains to functionality introduced to address that issue.

### To Reproduce

Attempt to recalculate blendshape normals with smooth shading on a mesh affected by this bug.

### Expected behavior

Try to recaculate blendshape normals on a mesh that is affected by this bug such as the aforementioned avatar found in the eye and lip tracking demo room: neosrec:///G-Neos-Team/R-d3f68803-8afe-4672-ac50-ef7b341068db

### Log Files

[SHIFTYWINDOWS - 2021.9.27.779 - 2021-09-27 13_18_33.log](https://github.com/Neos-Metaverse/NeosPublic/files/7239104/SHIFTYWINDOWS.-.2021.9.27.779.-.2021-09-27.13_18_33.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.27.779

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

neosrec:///G-Neos-Team/R-d3f68803-8afe-4672-ac50-ef7b341068db

### Did this work before?

No

### Additional context

Discovered while attempting to use this option on my personal avatar.

### Reporters

Shifty

**Comment by Frooxius** [comment]
Should be fixed in 2021.9.28.28, thanks for report!
