### ISSUE TITLE
AvatarUserRootOverrideAssigner does not work if the host auto-loads a client's avatar

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3099]
### Describe the bug?

when a user is spawning in and the host autoquips the Avatar it does not function as expected myviewpoint doesn't move 
to the object and it's only when I equip my avatar that the component functions right

### Relevant issues

none that I could find

### To Reproduce

1. after this save your avatar and favorite it

 ![image](https://user-images.githubusercontent.com/76523692/135012924-5e05ac3d-e526-4735-b209-5b531ea59a0c.png)
2. put the empty slot into the override you will notice that you can go into different camera modes with no problem
but if you equip your avatar and do the same thing it will function fine keep in mind you need to be in a room that you are not hosting ![image](https://user-images.githubusercontent.com/76523692/135013062-ec4fb52f-c246-4236-a64e-10305116523a.png)

### Expected behavior

the component should be able to override myviewpoint even if it's spawned in by another user

### Log Files

will give if requested

### Screenshots

I already provided some above

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.28.28

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

none really go to a place where you are not The Host In

### Did this work before?

No

### If it worked before, on which build?

this did not work before to my knowledge

### Additional context

https://youtu.be/eKSZ11p-fEc

### Reporters

epicEaston197#0793

**Comment by Frooxius** [comment]
Fixed in 2021.9.28.865, thanks for report!
