### ISSUE TITLE
Allow canvases to be unit scale, but still follow size recommendations

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#3108]
### Is your feature request related to a problem? Please describe.

To my knowledge it's currently recommended for canvases to be scaled to 0.001 and you use size to work with it in terms of millimeters.

I feel this works well in terms of ui design, however as canvases normally spawn at unit scale, and a size of over 1k, canvases often make development around them difficult or unwieldily.

The dramatically different scales can play havoc when parenting or applying scale to child slots, such a LogiX being inside a canvas based menu. I've often encountered accidently resetting a scale, and now sub LogiX is massive next time I unpack.

Unit scale seems to be preferred by many neos systems, such as how snappers or tools pivot to unit scale. Canvases are one of the few things I know of that force the user to use a difficult scale, and I think that can be removed from the learning curve.

### Relevant issues

None found

### Describe the solution you'd like

Allow the dpi of the canvas to be modified (although it's likely more easily defined as SizePerMeter or something like that), for existing canvases it's set to the existing density and the current behavior is retained.

In newly spawned canvases it's set to 1000, and allows the visual and physics of the canvas to act like a 0.001 scale is applied (the equation is 1/SizePerMeter) without applying that scale to child slots.

Only canvases spawned from the create new and component add menus would have the value set to 1000.

### Describe alternatives you've considered

Kicking all canvases to be 1000 times smaller, this would break a lot of things, some UIs may require a different dpi anyways.

Keeping this as is - this does get worked around but it's a consistent pain point to users who are unaware or who are not as comfortable dealing with scales. It's also a source of gotchas for when some scale gets odd, such as what's happened to me a few times where LogiX will have been moved back and forth from a slot, and now my hierarchy has oscillating scales of 1000 and 0.001.

### Additional context

This is adding an odd field and I get that's getting into implementation. Feel free to ignore the proposed field if it hurts the request.

If you want the vauge root requirement: I want a canvas that is 1000×1000 to have unit scale, and be 1x1 meters in size so new users don't need to deal with the invisible canvas wall cutting though the map.

**Comment by Frooxius** [comment]
I've added UnitScale in 2021.9.30.912 which should do this, hope it serves well! We might see if we can transition some of our native canvases to this, but it'll take a bit of doing for that. Thanks for suggestion!

**Comment by Earthmark** [comment]
Coorito, thanks for the update!
