### ISSUE TITLE
Missing Logics Node to complete a set -- Handrotation

### ISSUE THREAD

**Issue by win189** [Neos-Metaverse/NeosPublic#3119]
### Is your feature request related to a problem? Please describe.

We have 
-- HeadFacingDirection
-- HeadFacingRotation
-- HeadPosition
-- HeadRotation
-- HipsPosition
-- HipsRotation
-- FeetPosition
-- FeetRotation
-- HandPosition

But No **-- HandRotation** Could we possibly Get that, please

and also the setNode at same time

### Describe the solution you'd like

Completing the full set of nodes

### Describe alternatives you've considered

could do the Longer way like we did before but this way its a full matching set

**Comment by Frooxius** [comment]
Added in 3119 thanks for request!
