### ISSUE TITLE
Write Ref Latch node

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3122]
### Is your feature request related to a problem? Please describe.

when working with references it's kind of difficult to write into the same field twice in two different pulses 
the node would work like Write Latch except it will work with references

example
![image](https://user-images.githubusercontent.com/76523692/135728591-2a9c6e2e-80d9-41da-a394-2a93f30e8a29.png)

### Relevant issues

none that I could find

### Describe the solution you'd like

for the node above to be added

### Describe alternatives you've considered

but both of these feel like unnecessary operations
![image](https://user-images.githubusercontent.com/76523692/135728781-675f035b-658c-43e4-8f25-1f920ecda834.png)
![image](https://user-images.githubusercontent.com/76523692/135728789-ac302fa8-5d27-4dfa-8b7d-a86331a7fda4.png)

**Comment by Frooxius** [comment]
Added in 2021.10.3.784, thanks for the request!
