### ISSUE TITLE
CharacterColliderTip Hits All Colliders underneath an object root

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#3128]
### Describe the bug?

This seems a regression but previously the CC Tip used to only hit the outer most collider that the raycast would detect. Currently when you use it, it hits the Outermost, and then all colliders underneath it. This is problematic because if you hit a slot with a bunch of objects parented underneath it. The entire root becomes a collision park. We ran into this on the Metaverse Hotel map because when you zap the Room, the rest of the objects come with as well. 

### Relevant issues

I'm on mobile and will add later,.but I think it had to do with the recent grabbable tip changes. The CCTip is defaulting to the Root behavior, vs apply on hit as the default. 

### To Reproduce

1. Spawn a Box and a Sphere
2. Parent one under the other
3. Proceed to zap the topmost object with the CCTip, and see as how the entire heiarchy becomes Collidable. 

### Expected behavior

It should only act as an apply on hit vs a object root hit. 

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Current

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### Did this work before?

Yes

### Reporters

Turk

**Comment by shiftyscales** [comment]
I imagine @ProbablePrime could potentially integrate a similar solution to the GrabbableSetterTip that now has an option to apply just to the hit collider.

**Comment by Frooxius** [comment]
This is a bit strange. What you describe is pretty much how it always used to work and how it was designed to work.

I even checked the code and it's been implemented to do this all the way back in 2019, so I don't see how this could be a regression.

We could of course add options for changing its behavior, but I'm a bit puzzled by your claim that this used to work differently before.

**Comment by ProbablePrime** [comment]
I started looking into adding the same behaviour we now have on the Grabbable Setter to it.

We do still need the info here though.

**Comment by shiftyscales** [comment]
I agree, I don't believe this to be a regression. I think Turk is either mis-remembering or has it backwards. Currently, if you hit a collider, it applies it to objects beneath it, but if you hit an object lower in the hierarchy it only apples to that collider only.

However, in the presence of an object root, hitting any collider applies it to the entire hierarchy no matter which is hit. Perhaps this is what @TehTurk ran into? If an object root was in the hierarchy of an object in his world, that would explain his observed behavior.

**Comment by TehTurk** [comment]
Weeeird okay, because I've used it enough that was how the default behavior was to me. Even with ObjectRoots in the past, it would only hit the topmost collider. Apologies for the regression claim then ;-; 

It's probably that @shiftyscales , I honestly hadn't run into this issue too much before because I hadn't scale of my world building hadn't hit super big from my experiences. Yet going through this MMC I ran into the issue since the world was denser and we were using object root more often, normally I'd not have that in most of my projects unless necessary. I only recognized this as an issue because I had multiple users reporting one of the areas was a CC Mindfield and it didn't make sense to me initially how it became like that.

**Comment by ProbablePrime** [comment]
Ok I confirmed that this hasn't been touched that much in the past. 

We should probably discuss it in another issue BUT, I've copied(well restructured) the Object Root logic from the GrabbableSetter tip into this tooltip. While i was at it I also gave it to other tooltips so final list with the "Apply to Object Root / Just Hit Object" stuff:
- [X] GrabbableSetterTip
- [ ] CharacterColliderSetterTip
- [ ] ComponentCloneTip
- [ ] MeshVisibilitySetterTip

Do any additional tooltips need it?

**Comment by shiftyscales** [comment]
ObjectSlicerTip and InteractiveCameraObjectExcludeTip could also potentially make use of this functionality.

**Comment by TehTurk** [comment]
Sorry for the delay. And thank you for the confirmation, apologies that I got it a bit mixed up. 

The only that I see that could also benefit that hasn't been said is the Material Tip, but I know that one is a bit more tricky so thanks Shifty for getting all the different tips that'd benefit from it :)

**Comment by Frooxius** [comment]
Merged changes in 2021.10.11.1175! Thanks for the feedback and implementation!
