### ISSUE TITLE
Addition to issue #3077 for color nodes

### ISSUE THREAD

**Issue by TheBasementNerd** [Neos-Metaverse/NeosPublic#3132]
### Is your tweak request related to a problem? Please describe.

Among the nodes that were added, none of them allow for a quick offset of the hue, saturation, or values of a color. They are able to have a color set or multiplied, however this results in either a hard lock of that bit of the HSV (such as locking it to red) or multiplies it past its point, resulting in the color not just being offset but racing around the HSV wheel rather than simply being offset by a hard amount

### Describe what would you like tweaked

The addition of Add Hue, Add Saturation, and Add Value nodes to the Channels nodes in Color in the node browser, for adding a set amount to each of these rather than setting them to a specific value or multiplying them far past where they're wanted

### Describe alternatives you've considered

The only alternative is to use From HSV and then To HSV with an adder on the hue, however this results in the alpha staying at 1 so any alpha in the color is removed

**Comment by Banane9** [comment]
>The only alternative is to use From HSV and then To HSV with an adder on the hue, however this results in the alpha staying at 1 so any alpha in the color is removed

It would be very useful if those just had an alpha input in the first place 😅

**Comment by Frooxius** [comment]
Added those in 2021.10.5.1054, hope they help!
