### ISSUE TITLE
Local Boolean latch

### ISSUE THREAD

**Issue by Crusher50** [Neos-Metaverse/NeosPublic#3133]
### Is your feature request related to a problem? Please describe.

Currently their is no easy way to localize a Boolean latch without having to check if the impulse is triggered by the local user prior to the Boolean latch or use components to manually localize it. 

### Describe the solution you'd like

A Local Boolean Latch node that is only set, reset and toggled for the local user that is running/impulsed it.

### Describe alternatives you've considered

A work around to this is to use the Value User Override component on the Boolean latch state directly; although this is a tedious way to make the latch localized it does work.

**Comment by shadowpanther** [comment]
This was already requested in #2649 and is on the [roadmap](https://github.com/Neos-Metaverse/NeosPublic/projects/15#card-61393175). Closing this one as a duplicate.
