### ISSUE TITLE
Guests can spawn avatar creator

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3134]
### Is your tweak request related to a problem? Please describe.

Guests can spawn the avatar creator. This seems more like a builder thing.

### Describe what would you like tweaked

They probably shouldn't be able to since they can then turn anything into an avatar. (and in the process make it grabbable)

### Describe alternatives you've considered

Keeping it like this since I haven't seen it be abused much.

**Comment by Dirko3000** [comment]
that is... mildly concerning.

**Comment by epicEaston197** [comment]
yeah you can make entire Maps into avatars for some reason

**Comment by Frooxius** [comment]
Merged in 2021.10.17.1326, thanks for report and implementation!
