### ISSUE TITLE
No Undo step for the avatar creator.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3135]
### Is your tweak request related to a problem? Please describe.

Making an avatar with the avatar creator is not undoable.

### Describe what would you like tweaked

It should be undoable.

### Describe alternatives you've considered

Having it not be undoable.

**Comment by AshtonSparx** [comment]
Unsure how making something into an avatar could be undo-able since it attaches a bunch of components and such to the avatar (To make it an avatar)

**Comment by Psychpsyo** [comment]
> 
> 
> Unsure how making something into an avatar could be undo-able since it attaches a bunch of components and such to the avatar (To make it an avatar)

The same way you undo attaching one component. Just more.

**Comment by Frooxius** [comment]
> 
> 
> > Unsure how making something into an avatar could be undo-able since it attaches a bunch of components and such to the avatar (To make it an avatar)
> 
> The same way you undo attaching one component. Just more.

It's unfortunately much more complicated than that. It not only attaches components, it moves a lot of stuff around, it deletes a lot of stuff and changes a lot of it as well.

The avatar creation process is pretty complex for an undo step to be implemented like this, it wouldn't work without some complex changes and additions to the system and significant time investment.

Typically best way to create undo steps for these complex changes is to simply snapshot the source objects and on undo and then just delete the new one and load back the old one.

I'm still not quite sure if it's worth the time investment on our side though, perhaps when we rework the avatar creator we'll try to incorporate that into the new design.

**Comment by Dirko3000** [comment]
Typically good practice to make a copy of your would-be avatar before running it through the creator.

**Comment by shiftyscales** [comment]
What are your particular reasons for wanting to 'undo' an avatar creation, @Psychpsyo? It feels like there is some particular problem/use-case you're tryng to solve, but am unsure what.
