### ISSUE TITLE
Video Player freezes.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3139]
### Describe the bug?

Sometimes, (quite often actually) when importing videos and playing them, the playback will freeze halfway through for some users in the session. (sometimes all users, sometimes not.)
I can confirm that youtube videos do this but I am not sure if this also applies to videos brought in from a harddrive or a direct link.

Note: The time slider keeps moving, it is just the video that does not.
Also, the video may continue briefly intermittently afterwards.
Pausing and restarting or playing the video usually does not fix this.

### Relevant issues

Did not find any.

### To Reproduce

Import a youtube video (others might work as well, have not checked.) and play it.
At some point through the video the playback may freeze for some people in the session. (30seconds to a minute in-ish. Seems entirely random.)

### Expected behavior

Videos should just play through to the end as they do anywhere else.

### Log Files

[SYSTEM-PURPLE - 2021.10.3.784 - 2021-10-05 08_42_54.log](https://github.com/Neos-Metaverse/NeosPublic/files/7283595/SYSTEM-PURPLE.-.2021.10.3.784.-.2021-10-05.08_42_54.log)

### How often does it happen?

Sometimes

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.10.3.784

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Additional context

I think this used to be not as bad, but I am very unsure of that.

### Reporters

Psychpsyo ( Cameron#7818 )
Emmy7
Many others had this happen to them.

**Comment by Frooxius** [comment]
- Which video playback was active for you when this happened?
- Does this affect only YouTube videos? Or do you have any others?

Problem with YouTube specifically is that sometimes they rate limit the videos, this will happen when playing them with VLC as well. The video playback is generally handled either by Unity or UMP (which is based on libVLC) rather than Neos code, so I'm not sure how much we can do on our end.

If it's issue with the libVLC, we won't likely look into it now, since we plan to switch the playback engine: https://github.com/Neos-Metaverse/NeosPublic/issues/660

**Comment by Psychpsyo** [comment]
> 
> 
>     * Which video playback was active for you when this happened?
> 
>     * Does this affect only YouTube videos? Or do you have any others?
> 
> 
> Problem with YouTube specifically is that sometimes they rate limit the videos, this will happen when playing them with VLC as well. The video playback is generally handled either by Unity or UMP (which is based on libVLC) rather than Neos code, so I'm not sure how much we can do on our end.
> 
> If it's issue with the libVLC, we won't likely look into it now, since we plan to switch the playback engine: #660

It happens with both video playbacks. (unity and libVLC)
And after some testing of other videos, it seems to be only youtube videos.

**Comment by epicEaston197** [comment]
in most cases duplicating the video player will "fix it"

**Comment by Enverex** [comment]
I've had this happen with static external files too. The video visually would be frozen, but the timeline bar was still moving. Seeking/stopping+starting wouldn't fix it. It's as though Neos thought it was still playing, it just wasn't. I didn't report it though as I couldn't find any reliable way to reproduce the issue, it was quite rare.

**Comment by Frooxius** [comment]
@Psychpsyo Hmm if it's only YouTube videos we might not be able to do much, as it can just be the rate limiting that happens sometimes. YouTube changes the handling of the video streams now and then which starts breaking things. I'll see if we can update youtube-dl or switch to a fork that might get better streams as this has happened in the past.

@Enverex The timeline bar is normal. The playback in Neos is authoritative, meaning the actual video playback will always try to "catch up" or skip to where it is. If it's frozen it means that the video playback engine for whatever reason is having some trouble playing it, but Neos will keep updating the desired playback position.

**Comment by Psychpsyo** [comment]
> 
> 
> in most cases duplicating the video player will "fix it" it basically forces the video player to reload

I do know about that but 'most cases' is the keyword here. Earlier today we just gave up on a video after duplicating it the fourth time.

**Comment by Frooxius** [comment]
We switched from youtube-dl to youtube-dlp in 2021.10.5.1054. This fork seems to feature some workarounds for YouTube's throttling as mentioned on their page: https://github.com/yt-dlp/yt-dlp

See if this helps some. I'm not sure if we can do much beyond this though, since the throttling is most likely coming from youtube's end.

**Comment by Psychpsyo** [comment]
So far it seems like it's a lot better now so I'll close this issue for now.
