### ISSUE TITLE
Neos logs give the wrong information if the drive where the cache is, is not connected to the computer

### ISSUE THREAD

**Issue by brodokk** [Neos-Metaverse/NeosPublic#3142]
### Describe the bug?

When the disk, where the neos cache is, is not connected the neos logs give the wrong information. (tooks me sometime, hours, before check neos logs and then a little more before notice that the disk was not connected...)

### Relevant issues

I check on discord and github for a corresponding issue but nothing

### To Reproduce

Having the cache on the second drive, launch one time neos configured with the path to the cache on the second disk it then stop neos before relaunching it with the drive where the cache is not connected to your computer.

### Expected behavior

Instead of having a message like `Another instance of Neos is already running with same data path` maybe just something like `cannot find the D: drive`.

### Log Files

From one of the log file in `C:\Program Files (x86)\Steam\steamapps\common\NeosVR\Logs` folder:

```
9:27:54 PM.495 (  0 FPS)	Argument: C:\Program Files (x86)\Steam\steamapps\common\NeosVR\Neos.exe
9:27:54 PM.495 (  0 FPS)	Argument: -CachePath
9:27:54 PM.495 (  0 FPS)	Argument: D:\TemporaryFiles\NeosCache\
9:27:54 PM.495 (  0 FPS)	Another instance of Neos is already running with same data path (C:/Users/fuck_off_microsoft/AppData/LocalLow/Solirax/NeosVR), shutting down...
```

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.10.5.1054

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

**Comment by Frooxius** [comment]
I think this is misunderstanding on your end. Neos doesn't use the cache path to determine whether another instance is already running - two instances can refer to the same cache location, that's perfectly fine.

However the data path is what needs to be different and that's what it's checking there. You need to override that one with `-DataPath` if you want to run two separate instances.
