### ISSUE TITLE
Hard crash - Cannot access a disposed object MP3Reader

### ISSUE THREAD

**Issue by WallTack** [Neos-Metaverse/NeosPublic#3144]
### Describe the bug?

Sessions running under headless clients will periodically crash.

Relevant portion of the logs:
```
03:54:03.109    Unhandled Exception:

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MP3Reader'.
  at CSCore.Codecs.MP3.MP3Source.Dispose () [0x00015] in <47b8b9dc18a74d30a2e9560ab71b2cf8>:0
  at CSCore.Streams.SampleConverter.SampleToWaveBase.Dispose (System.Boolean disposing) [0x00000] in <47b8b9dc18a74d30a2e9560ab71b2cf8>:0
  at CSCore.Streams.SampleConverter.SampleToWaveBase.Finalize () [0x00000] in <47b8b9dc18a74d30a2e9560ab71b2cf8>:0
```

These are the last lines of the log file (full log linked below), followed by the session and any other sessions the headless is hosting at that time crashing.

### Relevant issues

None that I know of

### To Reproduce

Start this world under a headless client (it starts fine on the normal Neos client): `neosrec:///G-Elysium-Enterprises/R-c869e7b4-5599-46bf-b2a2-c14e66f214f9`

The world will crash immediately.

### Expected behavior

Sessions hosted under headless client shouldn't crash randomly

### Log Files

[ns5005928 - 2021.10.5.1054 - 2021-10-06 03_53_56.log](https://github.com/Neos-Metaverse/NeosPublic/files/7290717/ns5005928.-.2021.10.5.1054.-.2021-10-06.03_53_56.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.10.5.1054

### What Platforms does this occur on?

Linux

### Link to Reproduction Item/World

neosrec:///G-Elysium-Enterprises/R-c869e7b4-5599-46bf-b2a2-c14e66f214f9

### Did this work before?

Yes

### If it worked before, on which build?

2021.10.3.784

### Reporters

WallTack, SeventhVoid

**Comment by Frooxius** [comment]
Fixed in 2021.10.6.332, thanks for report!

Looks like some users were coercing MP3 files to be used as audio clips. MP3 isn't currently supported as native audio format - WAV, OGG and FLAC are. Until the MP3 decoder (https://github.com/naudio/NLayer) stabilizes more we'll keep it disabled.

**Comment by WallTack** [comment]
Did 2021.10.6.332 get pushed? I see it's posted in Discord but I'm still on 2021.10.5.1054 with no updates available on headless client or otherwise

**Comment by Frooxius** [comment]
I ran the publish script again just to be sure. Try restarting Steam and see if it helps.
