### ISSUE TITLE
Extend "Data Preset" component with "WriteBack" button / on Impulse

### ISSUE THREAD

**Issue by Nordwig** [Neos-Metaverse/NeosPublic#3161]
### Is your feature request related to a problem? Please describe.

Updating a "Data Preset" with many entries to new values can be very time consuming, confusing and prone to mistakes.
If you want to create different presets for one setup you can duplicate the preset structure but you have to update the new values manually. Or create a chain of writes to do the job which works but defeats the purpose in a way.   

### Relevant issues

I created a light setup where the User can change values to differ the effect.
And created presets to switch between some effects automatically.
Each preset contains 12 float values and I aimed for 10 Presets so 120 times finding the value in the UIX panel an place it in the correct field. When thinking about float3 values that escalates quickly.
I was ending up with a chain of writes to do the job for me.
But the Presets are not easily User changeable, because having the Logix floating around for each preset seemed to waste full for me. 

### Describe the solution you'd like

I would like to have a "WriteBack" button on the Preset component like the "Set Active".
It copies the momentary value of the referenced Target variable to the "PresetValue" on button press in the inspector.
And that the "WriteBack" button can be used with logix or referenced in a button component "on pressed" ect. .
If the "Data Preset" is used on a button slot. The Button should only interact with the "set Active" as it is now.

### Describe alternatives you've considered

Doing it with write chains as I did mentioned bevor but that can be a very messy setup. 

### Additional context

This would also be useful if updates to Worlds make changes in Presets necessary. 
So you can move the "Game Objects" to a new location place them by hand und just update your Preset to the new coordinates.  So multiple "Data Presets" can be easily create and updated.

Referencing to the [Tutorial video](https://www.youtube.com/watch?v=sEHQKPxQKoo) by ProbablePrime

**Comment by Frooxius** [comment]
Added in form of "SetValues" impulse target, which will load up the current values references. Added in 2021.10.11.1175. Thanks for request!
