### ISSUE TITLE
Unexpected mapping of axis directions (and rotation) when exporting as GLB/GLTF from Blender to Neos

### ISSUE THREAD

**Issue by Zyzyl** [Neos-Metaverse/NeosPublic#3166]
### Describe the bug?

I would expect that the Blender X+, Y+, and Z+ axes would map to the Neos X+, Z+, and Y+ axes if one exports to GLB/GLTF with the 'Y+ Up' option ticked (in Blender). I would also not expect any rotation to be applied to the imported object in Neos. 

However, in my testing it actually seems the Blender X-, Y-, and Z+ map to the Neos X+, Z+, Y+. Models also have a -180 degree rotation applied on the Y axis even though all transforms were 'applied' prior to export from Blender.

### Relevant issues

None that I noticed

### To Reproduce

Export the Tricone object in this zipped blend file
[GLB_test.zip](https://github.com/Neos-Metaverse/NeosPublic/files/7318025/GLB_test.zip) using these settings
![Blender_export_options](https://user-images.githubusercontent.com/66165438/136709725-43e88853-139a-4d71-93b5-f7ea263dab38.png). Files were created with Blender 2.93.5
 
Import as a standard 3D model (metres scale) in Neos. You will notice that the Blender X-, Y-, and Z+ map to the Neos X+, Z+, Y+. Models also have a -180 degree rotation applied on the Y axis even though all transforms were 'applied' prior to export from Blender.
 

### Expected behavior

I would expect that the Blender X+, Y+, and Z+ axes would map to the Neos X+, Z+, and Y+ axes if one exports to GLB/GLTF with the 'Y+ Up' option ticked (in Blender). I would also not expect any rotation to be applied to the imported object in Neos. 

### Log Files

Log file where I opened a simple gridspace world and imported the two models (glb & gltf) in the zip folder attached above.

[DESKTOP-SIS8AVA - 2021.10.6.332 - 2021-10-10 20_59_13.log](https://github.com/Neos-Metaverse/NeosPublic/files/7318030/DESKTOP-SIS8AVA.-.2021.10.6.332.-.2021-10-10.20_59_13.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.10.6.332

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

Zyzyl#1441

**Comment by Frooxius** [comment]
This is normal. Blender uses right-handed coordinate system, while Neos uses left-handed one, so you cannot map the axes directly to each other without extra transformations.

It's actually something that's largely happening on Assimp's side, as it handles some of the remapping of the transforms, though we do some post-processing.

If this is really big issue we could look into changing the mapping somehow, but it would probably require remapping the geometry itself and other things (animations, blendshapes, hierarchy...), which is very time consuming and prone to errors (coordinate systems are pain), so I'm not sure if it'd be worth prioritizing.

**Comment by Zyzyl** [comment]
Ah ok, thanks for the information. If this is actually working as intended then I'll just try to account for it in how I set things up in Blender.
