### ISSUE TITLE
Camera filter flashes when using camera anchor

### ISSUE THREAD

**Issue by orange3134** [Neos-Metaverse/NeosPublic#3174]
### Describe the bug?

When I use the camera anchor, the camera filter flashes and I can't use it.

I'm having trouble with this issue because I want to shoot videos using filters and homebrew overlays.

### Relevant issues

As far as I searched, I couldn't find it.

### To Reproduce

1. Spawn the camera and camera anchor.
2. Press the button on the back of the camera to enable the filter.
3. Move the camera to the camera anchor.
4. The filter flashes fast.

### Expected behavior

The filter should not blink.

### Screenshots

Video recording this issue
https://www.youtube.com/watch?v=DUu8wrhZomo

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.10.6.332

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Additional context

When I'm experiencing this issue, when I check the Inspector, the Main Camera's Exclude Render is flashing fast.

### Reporters

orange#1901

**Comment by Frooxius** [comment]
This should now be fixed in 2021.10.17.1326, thanks for the report!

**Comment by orange3134** [comment]
Thanks for the quick fix!
