### ISSUE TITLE
Add the ability for invisible stencils to cut out visible stencils

### ISSUE THREAD

**Issue by TheBasementNerd** [Neos-Metaverse/NeosPublic#3179]
### Is your tweak request related to a problem? Please describe.

Stencil materials that are invisible (a fully alpha clipped UI_Unlit for example) are unable to clip out a visible stencil, resulting in many possibilities with features of a world or system being hidden or partially visible thus being impossible to achieve

### Describe what would you like tweaked

The ability for a stencil that is not visible to the user to be capable of hiding a visible stencil material

### Describe alternatives you've considered

There are none

**Comment by shiftyscales** [comment]
Basement's reported that her issue is resolved.
