### ISSUE TITLE
'Standard Controller' node misbehaves when given Local User (or local variable in general)

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3183]
### Describe the bug?

When given Local User (or any user variable that differs between clients), the Standard Controller node will output the same for every user, regardless of their value for the variable.
This seems to be due to every user writing their own controller into the output when the node gets set to them.

### Relevant issues

Edit: #819, see my comment below

### To Reproduce

1. Go into a world with multiple people that have different controllers.
2. Plug Local User into a Standard Controller
3. Plug in a Chirality.
4. The node now shows the same for every user.

### Expected behavior

The node should be able to have different outputs for every user if it has different inputs for every user.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2021.10.1.1175

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

neosdb:///756fc49b0c58a231dd7d4e6197b138167f711b0f04d886a059106aa05d2a4545.7zbson

### Did this work before?

I Don't Know

### Reporters

Cameron#7818

**Comment by ukilop** [comment]
neosdb:///e86558d40ca0cd9b5c90892607e4c5626f9090068169267d70b368a1697dcf89.7zbson 
 i have made the work around described in #819
