### ISSUE TITLE
'Count Substring' node

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3189]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I'm trying to count how many of a certain string occur in another string. (recently: counting the number of newlines)

### Relevant issues

Didn't find any.

### Describe the solution you'd like

A Logix node that takes two strings and counts the number of times that one appears in the other, outputting that number as an int.

### Describe alternatives you've considered

Removing all occurrences from the string, then comparing string length with the original.

### Additional context

Ran into this while trying to count newlines.

**Comment by ProbablePrime** [comment]
Also requested by I'm Erin
