### ISSUE TITLE
360 Projection Shader not loading

### ISSUE THREAD

**Issue by Ducky07** [Neos-Metaverse/NeosPublic#3202]
### Describe the bug?

Removed my cache yesterday, and now world previews & skyboxes won't load.

### Relevant issues

https://github.com/Neos-Metaverse/NeosPublic/issues/3030
https://github.com/Neos-Metaverse/NeosPublic/issues/3032

### To Reproduce

Remove your Neos Cache, try and load world previews.

### Expected behavior

For world previews and skyboxes to load in.

### Log Files

[Uploading 4AM - 2021.10.11.1175 - 2021-10-16 17_14_52.log…]()

### Screenshots

![image](https://user-images.githubusercontent.com/26348192/137593920-942eff7d-1865-48c6-8bb3-60dcb6c7bfa5.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.10.11.1175

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

**Comment by Ducky07** [comment]
[Napo - 2021.10.11.1175 - 2021-10-16 17_14_52.log](https://github.com/Neos-Metaverse/NeosPublic/files/7357806/Napo.-.2021.10.11.1175.-.2021-10-16.17_14_52.log)

**Comment by Frooxius** [comment]
Thanks! Looks like the variants got deleted for some reason. They should be regenerated within a few hours (maybe already are). 

I'm still doing some investigation into why they got deleted in the first place, but that will take a bit longer, but they should work for now (or give it an hour or two).

**Comment by AdmiralSoap** [comment]
I just cleared my cache. Now the world previews and the skyboxes are failing to load.

**Comment by ProbablePrime** [comment]
We've got the shader compilation job re-compiling these. It might take a little while to get these available again though. 

You should start to see less issues by now. 

If this is still occurring after waiting a few more hours, please comment again.

**Comment by ProbablePrime** [comment]
We're still experiencing some users reporting this one. We're investigating once again to double check everything is in order.

**Comment by ProbablePrime** [comment]
Should be fixed fixed now.

**Comment by ProbablePrime** [comment]
Closing as this should now be resolved, re-open/make new issue if its still an issue.
