### ISSUE TITLE
Unpublicesing a folder with your own folders as "Orange" folders unpublecises ALL content in all folders

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#3205]
### Describe the bug?

This has caused an issue where my "[Public] 3x1t_5tyl3" was completly unpublisised due to me un-publesising my "3x1t's publics" un-publisised my "[Public] 3x1t_5tyl3" and all of it's contents.
Please look into "Reproduction"

### Relevant issues

-

### To Reproduce

1. Make a folder "A"
2. Publicise the folder "A"
3. Make a folder "B" and publicesise it
4. Save the spawned out copy of folder "B" into folder "A"
5. Unpublisise Folder "A"
6. Folder "A" and "B" will be ALL un-publesised. Including all the content.

### Expected behavior

For it to only work on rooted folders not folders which are just orange

### Log Files

Not applicable here.

### Screenshots

![Neos_mXLFmlr36z](https://user-images.githubusercontent.com/61988002/137623789-0e954e0f-b11f-46e8-b345-12c96c523e8c.png)
![Neos_4Fyrf6Gd6d](https://user-images.githubusercontent.com/61988002/137623790-4ad2b179-fa66-4e4f-b3ff-1324c8f03453.png)
![Neos_8sXJOsakw7](https://user-images.githubusercontent.com/61988002/137623791-9e8ceb7a-61bc-4981-9873-cf0537903a26.png)
![Neos_Hezcdgo2Pd](https://user-images.githubusercontent.com/61988002/137623793-672cd64c-612e-452e-b8c4-725976563e34.png)

![Neos_4WtC0VM1qE](https://user-images.githubusercontent.com/61988002/137623794-982d7d65-a4c2-4775-babe-1da8dc8b9799.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2021.10.11.1175

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

`3x1t_5tyl3#0001`

**Comment by Frooxius** [comment]
Fixed in 2021.10.17.1326, the unpublishing should now stop at links. Thanks for report!
