### ISSUE TITLE
Add headset battery level

### ISSUE THREAD

**Issue by sctanf** [Neos-Metaverse/NeosPublic#3212]
### Is your feature request related to a problem? Please describe.

I would like to be able to monitor my headset battery more easily. I can see my headset's battery level in SteamVR, but I have no method for notifying myself of a low battery, for example. It also doesn't let me display the battery inside the world. 

### Describe the solution you'd like

Add headset battery level and charging status in Neos, which can be accessed in a similar way to that of controllers.

### Describe alternatives you've considered

I can view the battery in SteamVR dash, or with an overlay, but it is not very easy to keep track.

**Comment by Frooxius** [comment]
What headset are you using?

**Comment by sctanf** [comment]
Sure!
Looks like it is working, thank you

**Comment by Frooxius** [comment]
Ah thanks for confirmation!
