### ISSUE TITLE
adding an undo option for logix packing and unpacking

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3248]
### Is your tweak request related to a problem? Please describe.

when I pack Logix sometimes I pack it into a wrong spot and I would like to be able to undo this
### Describe what would you like tweaked

I would Like to undo option for logix packing 

### Describe alternatives you've considered

none

**Comment by Psychpsyo** [comment]
Well, now this is a duplicate of #203.

**Comment by epicEaston197** [comment]
okay closing this one as its a duplicate of #203
