### ISSUE TITLE
Logix Drive node doesn't continually source its value under some circumstances.

### ISSUE THREAD

**Issue by RobertBaruch** [Neos-Metaverse/NeosPublic#3279]
### Describe the bug?

When a drive node drives the position/rotation/scale of a slot from the position/rotation/scale of another slot, it does not continually drive if that other slot comes from a variable node, dynvar input or dynvar read. It *does* continually drive if that other slot comes from a direct reference.

This is highly unexpected. A drive node should continually drive regardless of where its source data comes from.

### Relevant issues

N/A

### To Reproduce

1. Create a drive node that drives the position of a slot.
2. Create a global transform. Input is a different slot, via a direct reference.
3. Connect the output of the global transform to the input of the drive node, and pulse start driving.
4. Note the driven slot will follow the driving slot.
5. Change the direct reference to a Slot variable, write the driving slot to that var, and note that the driven slot does not follow the driving slot.

### Expected behavior

The drive node works regardless of where the data comes from.

### Log Files

[DESKTOP-83DJ9R8 - 2021.10.30.625 - 2021-10-30 12_05_35.log](https://github.com/Neos-Metaverse/NeosPublic/files/7447940/DESKTOP-83DJ9R8.-.2021.10.30.625.-.2021-10-30.12_05_35.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.10.30.625

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

neosrec:///U-Xekri/R-8e023dc1-a3f4-46e9-a19c-878cdbe7dfec

### Did this work before?

I Don't Know

### Reporters

Xekri

**Comment by Frooxius** [comment]
This is somewhat normal, LogiX drives will not force updates every frame, but rather they use the same change event propagation system as the rest of it to trigger changes for efficiency.

Certain nodes do not generate change events though. In some cases it's not possible/efficient and requires updating relay to force the updates, in some cases it's something we could potentially add/improve. I'm a bit confused by the setup though, so I'm not sure where that's coming from. Can you share a screenshot of the setup? That might make it easier to look at.

**Comment by RobertBaruch** [comment]
Here is a working setup:
<img width="983" alt="working" src="https://user-images.githubusercontent.com/1783950/139594866-0c9310e8-ec6c-4910-9c6b-bb7639d39c0b.PNG">

And here is the nonworking setup:
<img width="1119" alt="nonworking" src="https://user-images.githubusercontent.com/1783950/139594872-51f96138-f83e-43ff-ba22-d8d8be00b09d.PNG">

So the nonworking setup is not generating change events while the working setup is?

**Comment by shiftyscales** [comment]
I'd suggest opening a documentation request GitHub issue if you wish to follow up on this.

For now, I'm closing this issue as it sounds like it is functioning as it is supposed to.

**Comment by RobertBaruch** [comment]
Submitted https://github.com/Neos-Metaverse/NeosPublic/issues/3358

**Comment by RobertBaruch** [comment]
I swear that at some point in the past I didn't have to use updating relays for this. I've also spoken to Rucio, and he independently said to me that some things that worked in the past broke, and updating relays had to be added in.
