### ISSUE TITLE
Get Normalized Texture 2D Pixel

### ISSUE THREAD

**Issue by ImErinNeos** [Neos-Metaverse/NeosPublic#3291]
### Is your feature request related to a problem? Please describe.

Im tryin to use pics with different sizes and have to manually normalize them.

### Describe the solution you'd like

A version of Get Texture 2D Pixel that uses a normalized position.

### Describe alternatives you've considered

Manually normalizing the picture dimensions.

**Comment by Frooxius** [comment]
There already is node for this. Use "Sample Texture2D UV". UV's are normalized coordinates between 0.0 and 1.0.
