### ISSUE TITLE
Crash when spawning ToolsFacetPreset in World

### ISSUE THREAD

**Issue by Lexevolution** [Neos-Metaverse/NeosPublic#3304]
### Describe the bug?

When a user spawns in the ToolsFacetPreset in the World, everyone else crashes back to the previous world they were in (or their local home).

### Relevant issues

N/A

### To Reproduce

Spawn the ToolsFacetPreset from the Neos Essentials > Facets folder. Everyone else in the world will be disconnected.

### Expected behavior

For the Facet to spawn and no-one will crash/disconnect.

### Log Files

[Lexevo's Log](https://github.com/Neos-Metaverse/NeosPublic/files/7466978/LEXDESKTOP.-.2021.11.3.481.-.2021-11-03.20_29_37.log)
[DAWKY's Log](https://github.com/Neos-Metaverse/NeosPublic/files/7466980/SNOWFLAKE_-_2021.10.30.605_-_2021-11-03_20_14_50.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.11.3.481

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

2021.10.30.625

### Additional context

If you're the host, and spawn it, you will not crash/disconnect. If you're not the host and spawn it, no errors pop up in the log but will be disconnected due to the host crashing/disconnecting.

This crashes/disconnects people on BOTH the NCR disabled and enabled builds.

### Reporters

`Lexevo#0876`
`DAWKY#4485`

**Comment by Frooxius** [comment]
Should be fixed in 2021.11.3.684. Can you give it a try please?

**Comment by Lexevolution** [comment]
Seems to be working fine when testing with someone on the Steam build! Thanks!
(Me: 2021.11.3.684, them: 2021.10.30.605)

**Comment by Frooxius** [comment]
Ah thank you!
