### ISSUE TITLE
Re-introduce the Debug button in the ToolsFacetPreset

### ISSUE THREAD

**Issue by Lexevolution** [Neos-Metaverse/NeosPublic#3305]
### Is your tweak request related to a problem? Please describe.

In the new NCR enabled build, 2021.11.3.481, the Debug button has seemingly been replaced by the Buy Storage button.

### Describe what would you like tweaked

For the Debug button that used to be in the ToolsFacetPreset to be re-added

### Describe alternatives you've considered

Create my own facet to spawn out the debug dialogue? I'm not sure how to do that though.

### Additional context

This might have been accidentally removed? Or replaced by the new Buy Storage button.

**Comment by Aerizeon** [comment]
As a workaround, if you know how to find Turk's public folder (Turkpublica), they have some redesigned facets which include the debug button.

You'll have to be in VR, and use UI Edit mode to add it though.

**Comment by Frooxius** [comment]
Ooops, I removed it by accident, sorry! Added back in in 2021.11.3.684, thanks!

**Comment by Lexevolution** [comment]
Seems to be working fine when testing with someone on the Steam build! Thanks!
(Me: 2021.11.3.684, them: 2021.10.30.605)
