### ISSUE TITLE
the "look at" component thinks Up Is Down and Down is up in some cases

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3311]
### Is your tweak request related to a problem? Please describe.

when it moves down it moves up
there's no easy way of fixing this
have a checkbox that would invert only up and down movement

![image](https://user-images.githubusercontent.com/76523692/140376658-57570cc6-0800-4096-a9e6-74b37d315f48.png)
![image](https://user-images.githubusercontent.com/76523692/140376710-4c51d3a4-eda1-4a60-97fc-165e6f75db0f.png)

### Describe what would you like tweaked

a checkbox that would invert only up and down movement

### Describe alternatives you've considered

none really if I move it in the right spot it always makes up and down movement inverted
Up Is Down and Down is up

### Additional context

I was making a microphone ik system using look at components but I'm having problems with the up-and-down movement being inverted side-to-side movement is okay it's only up and down

**Comment by Frooxius** [comment]
We'll need to know how it's setup in order to be able to help. From the sound of it might be just improperly setup.

**Comment by epicEaston197** [comment]
all that I am really asking for is a button to invert up and down movement
should I edit the name to reflect this?
and one for side-to-side movement

> We'll need to know how it's setup in order to be able to help. From the sound of it might be just improperly setup.

**Comment by Frooxius** [comment]
I don't think that's something we'd actually add, since it seems like a hack for a problem that should be better solved differently. If we don't understand the exact problem you're having then we can't help you.

**Comment by epicEaston197** [comment]
okay thank you for your understanding I figured it out it was a rotation problem I will close this you issue

> I don't think that's something we'd actually add, since it seems like a hack for a problem that should be better solved differently. If we don't understand the exact problem you're having then we can't help you.
