### ISSUE TITLE
quads and grids should use box Colliders by default

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3315]
### Is your tweak request related to a problem? Please describe.

the main problem here is grids because you can increase the polygon count which could increase computational power
and box colliders are better than mesh Colliders 

### Describe what would you like tweaked

quads and grids should use box Colliders by default

### Describe alternatives you've considered

this isn't too bad I can just click convert to box collider and then that fixes the problem

### Additional context

you could have a grid that could be used for I don't know PBS displacement metallic and it needs to be really high poly in order to give off the effect you want having it be a box collider by default could increase performance

**Comment by Frooxius** [comment]
Using mesh collider is intentional for those. Often Quads/Grids are used with raycasts to be able to sample a UV coordinate and map it to an image or something projected on them. You might also want a single sided collision.

If you want a box collider, I'd recommend setting up a custom template and using that.

**Comment by epicEaston197** [comment]
> Using mesh collider is intentional for those. Often Quads/Grids are used with raycasts to be able to sample a UV coordinate and map it to an image or something projected on them. You might also want a single sided collision.
> 
> If you want a box collider, I'd recommend setting up a custom template and using that.
thank you that makes a lot of sense I will  close this issue
