### ISSUE TITLE
"Get Neos" Logo confusing

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#3320]
### Is your tweak request related to a problem? Please describe.

I heared from friend, in neos.com now changed to direct download link from "Get Neos".
but this icon uses Steam one, so they thoughts "Oh, the neos.com website can download as steam edition, but where is the standalone one?".

So, I think if not join Neos Discord, they can't receive the standalone edition, even though it's actually from the website.

### Describe what would you like tweaked

Change icon to Neos Brand icon one, it's much confortable to see it.
if they don't join Neos Discord even thought, they thinks it can download website from ico.

### Describe alternatives you've considered

Now the Steam edition is back. so in addition above one, if Click "Get Neos", we can check each edition by pull-down menu is also good.

**Comment by epicEaston197** [comment]
I am commenting this for reference
maybe have two buttons get on Steam and get Neos

![image](https://user-images.githubusercontent.com/76523692/140625822-8552322e-73a1-4d8c-9fc4-8f5bdcf00eb1.png)

**Comment by kazu0617** [comment]
> 
> 
> I am commenting this for reference maybe have two buttons get on Steam and get Neos
> 
> ![image](https://user-images.githubusercontent.com/76523692/140625822-8552322e-73a1-4d8c-9fc4-8f5bdcf00eb1.png)

I think for now, but after release Neosine and resolve these (and more) issue, it's better to use pull down menu,cuz' so many buttons.
https://github.com/Neos-Metaverse/NeosPublic/issues/3302
https://github.com/Neos-Metaverse/NeosPublic/issues/3282

**Comment by shiftyscales** [comment]
The icon is no longer the Steam logo resolving the initial confusion. Thanks for the report.
