### ISSUE TITLE
Infinite Login

### ISSUE THREAD

**Issue by SparkplugPlus** [Neos-Metaverse/NeosPublic#3324]
### Describe the bug?

Infinite Login is a bug that's came up before and fixed itself later, and came back up again.

It's as simple as the title is, I can try to login with any combination of letters and numbers, fake accounts that would surely never exist, or my actual account credentials, the result is still the same. 
There is zero communication from the server or the client, and keeps on showing the "Logging in..." message no matter how long I wait.

The only thing the server keeps up is updating the ping and that takes from 1MB to under 200KBs. 

### Relevant issues

As far as I know, nobody's reported on this except me.

### To Reproduce

I've got no clue, but it's happening on my system, and it happens consistently.
System restarts, game restarts, using the standalone, it's all the same.

### Expected behavior

To either: Have the game tell me I put in the wrong credentials or actually log me in. Some form of server feedback.

### Log Files

This log has the broken login bug.
[EPIC-BUG-VR - 2021.10.30.605 - 2021-11-06 16_23_45.log](https://github.com/Neos-Metaverse/NeosPublic/files/7491398/EPIC-BUG-VR.-.2021.10.30.605.-.2021-11-06.16_23_45.log)

This log is from when logging in worked on an earlier version.
[EPIC-BUG-VR - 2021.10.30.605 - 2021-10-31 14_58_29.log](https://github.com/Neos-Metaverse/NeosPublic/files/7491415/EPIC-BUG-VR.-.2021.10.30.605.-.2021-10-31.14_58_29.log)

### Screenshots

![image](https://user-images.githubusercontent.com/58667810/140626770-d338fe40-8078-4c64-a72f-704f080463ae.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.10.30.605

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### If it worked before, on which build?

Beta 2021.10.30.605

### Additional context

I'd like to add that logging in on the website always works perfectly, and I know I'm not outright blocking connections to the API.

### Reporters

bug#6253 / U-Sparkplug

**Comment by Frooxius** [comment]
Do you have any firewall on your system that might be blocking the requests? Or possibly any networking software that could be interfering? 

From the log, it's attempting the contact the cloud and it's not being outright blocked, but the requests just end up timing out (meaning it doesn't get any response). Neos will try to contact the API again when that happens, but they seem to all time out, so it just ends up stuck for a while.

Are you able to try on another PC?

**Comment by SparkplugPlus** [comment]
There's no active firewall or modem-side firewall that could be interfering, since I always have them off.

I could pull out my old laptop and try with that.

**Comment by kazu0617** [comment]
Softly depends on #3323 which occured same thing, infinite logging in.

**Comment by Frooxius** [comment]
If you can test on another computer that could help. I'd check any system firewalls and networking utilities too.

I can't really tell much from the logs, other than the requests just timing out due to not getting any responses from the server.

**Comment by SparkplugPlus** [comment]
hi gang, i have fixed the issue

windows never prompted me to allow 
![image](https://user-images.githubusercontent.com/58667810/140674211-e96c5365-fbfb-4176-9e02-8727c9b5ae7a.png)
these two programs through the firewall and thus blocked me from doing anything

i have no idea why this happened or why i was magically allowed to play for a day despite this issue, which makes this all the stranger but this bug is now fixed

always remember to check your firewall
