### ISSUE TITLE
GeometryLineBrushTip does not respect primary on and off with tooltip simulator

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3325]
### Describe the bug?

I am making a Etch-A-Sketch and the tooltip simulator does not respect primary on and off with the GeometryLineBrushTip 
it's like it Fink's primary was still on previously
and it will refuse to make another stroke

### Relevant issues

none that I would think would be related to this

### To Reproduce

get a GeometryLineBrushTip 
and put it into a tooltip simulator and click the primary box and move the tooltip around and you will see that it is drawing
and click the primary box off
you will see if you move it around it still drawing despite the Box being off

### Expected behavior

GeometryLineBrushTip should not disable the tooltip simulator component

### Log Files

will give if asked

### Screenshots

none

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.11.5.486

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

the box below turns on and off primary
neosrec:///U-epicEaston197/R-e525633e-c08b-47cb-bc20-db5ae4997086

### Did this work before?

I Don't Know

### If it worked before, on which build?

this did not work before to my knowledge

### Additional context

it also funny enough it doesn't put a mesh collider on it
so I can't grab The Strokes 
maybe that's because it doesn't ever let go a 
primary even though the boxes ticked off

it still respects all other values
like strength

https://www.youtube.com/watch?v=Xx-GYmN4l20

### Reporters

epicEaston197#0793

**Comment by epicEaston197** [comment]
I figured out that the tooltip simulator disabled itself
but I did not do anything that would even do this I'm just moving it
![image](https://user-images.githubusercontent.com/76523692/140633559-3122622b-7d70-4c0f-bd29-f9f591ebbe32.png)

**Comment by alizardguy** [comment]
Might be related to #2944 ?

**Comment by epicEaston197** [comment]
Jeana told me that when the strength is 1 it does a stroke and when the strength is 0 it ends the stroke
I thought it was dependent on primary
it depends on how much strength you put into it

> Might be related to #2944 ?

**Comment by Frooxius** [comment]
Brushes do not use the Primary, you need to use the Strength.
