### ISSUE TITLE
The "Create New World" button on tools facet is duplicit

### ISSUE THREAD

**Issue by rampa3** [Neos-Metaverse/NeosPublic#3328]
### Describe the bug?

The "Create New World" button on the tool facet of Dash's Home tab is duplicit, as shown in attached screen snip.

### Relevant issues

Didn't found any. (Used keywords "dash", "tool" and "facet".)

### To Reproduce

1) Open your dash
2) Look at the tools facet - there is the duplicit "Create New World" button

### Expected behavior

Only single instance of the "Create New World" button present.

### Screenshots

![image](https://user-images.githubusercontent.com/68955305/140661659-42c50020-c29f-4215-a0e9-ed59e8743313.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.11.7.784

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### Did this work before?

Yes

### Additional context

From some point of time I am not sure of when it was, the button became duplicit. My hunch is the build when buying storage with NCR became available (2021.11.3.481), but I am not 100% sure about that.

### Reporters

rampa_3#5925, Cataena#3067, SUP3RFlyN1NJA#6120

**Comment by Frooxius** [comment]
Fixed in 2021.11.10.899, thanks for the report!
