### ISSUE TITLE
A way to learn c# and c++ and all kind of other programming languages within neosvr 

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#3335]
### Is your feature request related to a problem? Please describe.

This would be super lit if you could learn all kind of programming languages with others in VR together that can controll things like movement of objects like a cube but Instead of it being just via logix it would be cool to program the raw code in-game of any kind of coding language and connect it and run it in-game to an object this way learning vide would be more accessible to a lot of people incl me who find learning it alone without VR is kinda scary but learning it with friends in VR and learning it just like logix would be really cool 

### Relevant issues

Typescript or something but this one is different from what I want because my request is for multiple programming languages being able to be connected to things in-game whilst coding it in-game with any kind of code weather it be c# or c++ or python basically so you can run and interface any object with any programming languages right inside VR 

### Describe the solution you'd like

Would be really educational 😁

### Describe alternatives you've considered

There is no alternative

**Comment by ProbablePrime** [comment]
Hey Alex,

This is most likely a duplicate as the issues linked in this: https://github.com/Neos-Metaverse/NeosPublic/projects/1#card-35346323 which is full text based scripting.

Currently we're looking into/thinking about Web Assembly which would you to build stuff in most common languages.

As for the learning part, once we have this feature, we'll produce some documentation and information on how to use it of course. A full programming course for a particular language is however, most likely beyond the scope of our team.

Community members might try things though.

**Comment by alexderpyfox** [comment]
Yeah but web assembly isn't c# 😔

**Comment by alexderpyfox** [comment]
Oh wait i didn't know that web assembly could do that my bad
