### ISSUE TITLE
Ability to change password from the website

### ISSUE THREAD

**Issue by sirkitree** [Neos-Metaverse/NeosPublic#3341]
### Is your feature request related to a problem? Please describe.

I'm unable to change my Neos password from the website, neos.com

### Relevant issues

https://github.com/Neos-Metaverse/NeosPublic/issues/154

### Describe the solution you'd like

When I log into Neos.com I'd like a way to be able to change my password, and for that to update my password for logging into the Neos client, the website, and the wiki.

### Describe alternatives you've considered

I can currently do this from the client, which is great, but the convenience of doing this from the website would also be wonderful.

**Comment by Frooxius** [comment]
We already have a topic for it here: https://github.com/Neos-Metaverse/NeosPublic/issues/2132

In short, you can already do this in the new account management website here: https://auth.neos.com

The old website won't be likely updated as it was managed by a 3rd party developer, instead we plan on working on making auth.neos.com the new replacement for it.
