### ISSUE TITLE
Neos Headless Uses a Randomised Port Making it Impossible to Use it Behind a Static Firewall

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#3348]
### Describe the bug?

Neos allows you to specify the ports for sessions, but Neos itself seems to have a port assignment for the core part of the headless which, if inaccessible, will make any session hosted on it unjoinable. Restarting the Neos Headless software seems to result in a random port each time.

Example:
```
udp        0      0 46.4.20.25:38153        0.0.0.0:*                           345903/mono
udp        0      0 0.0.0.0:12101           0.0.0.0:*                           345903/mono
udp        0      0 0.0.0.0:12102           0.0.0.0:*                           345903/mono
udp        0      0 0.0.0.0:12103           0.0.0.0:*                           345903/mono
udp        0      0 0.0.0.0:12104           0.0.0.0:*                           345903/mono
udp        0      0 0.0.0.0:12105           0.0.0.0:*                           345903/mono
udp        0      0 0.0.0.0:12106           0.0.0.0:*                           345903/mono
udp        0      0 0.0.0.0:12107           0.0.0.0:*                           345903/mono
```
Restart - 
```
udp        0      0 46.4.20.25:47719        0.0.0.0:*                           412193/mono
udp        0      0 0.0.0.0:12101           0.0.0.0:*                           412193/mono
udp        0      0 0.0.0.0:12102           0.0.0.0:*                           412193/mono
udp        0      0 0.0.0.0:12103           0.0.0.0:*                           412193/mono
udp        0      0 0.0.0.0:12104           0.0.0.0:*                           412193/mono
udp        0      0 0.0.0.0:12105           0.0.0.0:*                           412193/mono
udp        0      0 0.0.0.0:12106           0.0.0.0:*                           412193/mono
udp        0      0 0.0.0.0:12107           0.0.0.0:*                           412193/mono
```

This means that it's basically impossible to run Neos behind a conventional firewall unless you add a firewall rule manually every time you restart the headless software.

Given that you're able to assign session ports, I assume the inability to assign the main program port is an oversight, or the functionality exists, but isn't documented.

### Relevant issues

None

### To Reproduce

Firewall all ports on a server, allow the session ports but not the randomised main program port that Neos assigns itself. Users will get part the way through the connection process but then hang forever on a connecting state.

### Expected behavior

For all Neos' used ports to be configurable so that Neos can operate inside a secure firewall configuration.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.11.10.1253

### What Platforms does this occur on?

Linux

### Did this work before?

No

**Comment by Frooxius** [comment]
Using random port is perfectly normal - the system will assign a random free port to the application when you don't request a specific port.

Given that you can already specify the ports for sessions - what exactly are you looking to specify port for? I don't know what "main program port" refers to, there's not really anything in Neos that I can think of it could relate to.

**Comment by Enverex** [comment]
In the terminal listing I've provided, you can see that Neos is opening ports for sessions. These are the 12101 to 12107 ports that I'm specifying via the forcePort directive on a per-session basis.

Additionally, Neos is also listening on a random port (38153 on the first run and then 47719 on the second run respectively in the examples I've provided). This is the problem; If this random port is firewalled, connection to the headless will fail. But I can't allow it in the firewall because it appears to be randomised every time the headless is started. But I can't allow it in the firewall as it appears to be randomly chosen at startup and there appears to be no way of specifying it in Neos' configuration. Trying to connect to a headless while this random port is firewalled, even if that specific session's port is allowed, will fail.

At least, that was the case. After several times recreating this issue, it's no-longer happening so not quite sure what's changed there. I'll close this for now and reopen it if I manage to narrow down what was happening (or if it was just a weird quirk somewhere in the firewall).
