### ISSUE TITLE
Multi Plexer Component Replication of Funcionality

### ISSUE THREAD

**Issue by win189** [Neos-Metaverse/NeosPublic#3356]
### Is your feature request related to a problem? Please describe.

Not that i am awawre

### Relevant issues

There is no way to get the inputCount On the Multyplexer Compnent on a Logics interface card

### Describe the solution you'd like

To have the Inputcount on the logics interface card

### Describe alternatives you've considered

use Way to many slots and do it in logics

**Comment by shadowpanther** [comment]
I would guess that component access would cover that implicitly as it would allow to access the array/bucket of inputs from LogiX.

**Comment by win189** [comment]
why Component access  is it that hard to just MAke it match the Logics node Come on 

> I would guess that component access would cover that implicitly as it would allow to access the array/bucket of inputs from LogiX.

**Comment by shadowpanther** [comment]
Because it is making a way to read the existing data vs. adding another property of the component (and tracking down every variation like asset multiplexer) that depends on its configuration.

**Comment by win189** [comment]
![Neos_Pukzydln5w](https://user-images.githubusercontent.com/24577138/141523593-9060090d-02aa-4276-8dc4-556495188e30.jpg)

**Comment by win189** [comment]
I am just Asking for it to be inline with The Logics Node this is not Rocket Sience 

if the Logics node can have access to the index INT and have access to the Input Count 

Then Give me one good Example why  the Component cant which you wont be able to as its Logical that it should be matching

**Comment by shiftyscales** [comment]
As Shadow has mentioned this functionality will be handled impliclty by further development. Even if you had the number of elements listed, you still wouldn't have access to the list itself so you couldn't do anything right now with it until collections are implemented anyway.

**Comment by win189** [comment]
i just want to use the Compnent in a for loop

**Comment by win189** [comment]
which would save on slot useage

**Comment by Geenz** [comment]
@win189 I seem to recall you had a LogiX example that could have been significantly simplified that depended on the total number of values being present being exposed?  Can you show that here?

**Comment by win189** [comment]
Sure I have a Couple of Examples were This is Highly Beneficial  One being my 200 song Jukebox that if they are on the same red print and you move the Multiplexer or redprint your Frames Takes a crap dive to the deep end  and before anyone says well then don't use Red print even open-air that many ribbons is murder

![Neos_zt7JH5AXho](https://user-images.githubusercontent.com/24577138/142090164-937a2449-4019-4eb0-87c2-c6718beaf78a.jpg)
 J


below is a String Check for another project that is ment to check if a string is valid and go grab a asset
![Photo in working onstuff no b](https://user-images.githubusercontent.com/24577138/142094293-b290e006-2377-49d9-97c1-f13037dccdd0.jpg)

i have more im jsut on a time crunch for work 

the other biggest one is my Picture frame
