### ISSUE TITLE
Add method to define modulo behavior in LogiX

### ISSUE THREAD

**Issue by Irick** [Neos-Metaverse/NeosPublic#3363]
### Is your feature request related to a problem? Please describe.

The current method causes unexpected behavior in cases where the user expects IEEE-754 modulus.

### Describe the solution you'd like

I'd love to see a method to choose between at least truncated and floored modulo.

### Describe alternatives you've considered

Building other methods of modulo is possible with existing operators, but it makes me sad.

**Comment by Irick** [comment]
Nevermind, I found Repeat XD

**Comment by mralext20** [comment]
related: #3169
