### ISSUE TITLE
Scaleable UIx nested canvases 

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#3366]
### Is your feature request related to a problem? Please describe.

So I want this feature so you can dynamically scale a canvas inside a UIx menu ie Inspector making the hyarcy list wider and component List smaller when grabbing the center and or like in blender where you scale windows and can put different UIs ontop and scale them and layer them by grabbing the edges or corners of that particular nested canvas so it it's still in one ui but just within the ui multiple sub menus can be shaped this would be super handy for creations 

### Relevant issues

UIx update

### Describe the solution you'd like

This feature

### Describe alternatives you've considered

Mods but then i got told to create a GitHub issue instead

### Additional context

I need this feature

**Comment by ProbablePrime** [comment]
Hey Alex, this system exists. Its called Facets.

When we overhaul the inspectors and other UI, they'll support facets.

Due to this i'll be closing this issue.

As a reminder please search before creating an issue: https://github.com/Neos-Metaverse/NeosPublic/projects/2#card-61036826

**Comment by alexderpyfox** [comment]
No you misunderstood i mean it's an addition to facets where you can scale them on the go not when creating then but like a feature of the UIx itself where you can scale it on a screen like kinda as how it's currently done in the dash but then with overlapping and resizing it by grabbing the corner or the side just like on windows so see it as like on windows desktop screen right act like that is a panel in game object and then you have UIx on it where you can scale pieces of the ui just like on windows with screens where you can drag the corner to scale it up or the side to make it wider or narrow but using that for regular UIx or facets currently facets are only limitedly  scaleable on the dash where it can only be scaled to some forms but it gets grabbed from the dash and becomes a outline of it but I mean like without any edit mode just a regular scaling and resizing and not limited to the dash but for every UIx creation scaling option via laser

**Comment by ProbablePrime** [comment]
Hey Alex, this is also facets by my understanding.

Facet's rescaling/editing is currently tied to UI Edit mode but that may change. We don't really need a new system to facilitate changing their size or position as the facet system already has this.

**Comment by alexderpyfox** [comment]
Yes but the facets do it wrong ATM because you grab the whole facet out when resizing it needs to be grab out and sizing as a sepetate thing to both since grabbing and scaling it for when you want to add one is fine but it needs to be to scale it only and not grab it out at the same time so you can see how it looks directly and without edit mode to scale it

**Comment by ProbablePrime** [comment]
We could potentially separate facet resizing and grabbing later. We do not need to write an entirely new system just to resize facets.

**Comment by alexderpyfox** [comment]
For inspectors the same thing but different where the component list goes narrow and the hyarcy list goes wide when you grab the center part

**Comment by ProbablePrime** [comment]
Yup that's just resizing.

**Comment by alexderpyfox** [comment]
Also resizing on facets is currently only possible from the corner outwards and not from the side to lock it to only sizing in the axys as the side you grab and drag

**Comment by alexderpyfox** [comment]
When it got that then it's good for making ui with that van have sliding panels
