### ISSUE TITLE
Ability to spawn multiple seperated  inventory windows in user space 

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#3367]
### Is your feature request related to a problem? Please describe.

Right now it just mirrors all other inventory ones but I need it to be that each inventory ui menu can be in a different folder 

### Relevant issues

Ui overhaul 

### Describe the solution you'd like

That duplicated inventory UIs don't mirror eachother and ability to make it be both in different folders 

### Describe alternatives you've considered

Mods but then i was told to put a GitHub request instead

**Comment by epicEaston197** [comment]
the menu that you are talking about is a legacy menu and will not be sticking around forever it will be removed at some point

**Comment by alexderpyfox** [comment]
But will the new inventory incl the ability to have multiple of it in user space i want multiple inventory windows in userspace with the new one too so you can be in one folder in one window and the other inventory can be the avatar folder at the same time basically

**Comment by shiftyscales** [comment]
As was mentioned- the inventory is still pending an overhaul- we won't be making additional enhancements to the legacy UI.
