### ISSUE TITLE
Add Translate for "Selection: Singlt/Multi" in DevToolTip

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#3368]
### Is your tweak request related to a problem? Please describe.

Currently, these strings are not available for translation.

### Describe what would you like tweaked

The strings shown in the title cannot be translated. I think they probably forgot to include them in the implementation, so please make them available for translation (at least for "Selection:").

![](https://user-images.githubusercontent.com/61988002/121703125-cc08be00-cad2-11eb-8506-0343a15eb401.png)

### Describe alternatives you've considered

Nothing.

### Additional context

This story was previously posted by @3x1t-5tyl3 on NeosLocale( https://github.com/Neos-Metaverse/NeosLocale/issues/453 , https://github.com/Neos-Metaverse/NeosLocale/issues/454) , but it didn't seem to be tracked, so I'm reposting it here.

**Comment by shiftyscales** [comment]
As you had noted, this issue already exists on the NeosLocale repository. I don't think we need two issues for this.

Enums are not currently localizable/requires them to be implemented- it's not as simple as just adding locale strings like other text.
