### ISSUE TITLE
Localize for Help Message

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#3369]
### Is your feature request related to a problem? Please describe.

We are often told that we don't know how to operate Neos, but the help marks that are supposed to be provided for this are not functioning for non-English speakers.

### Describe the solution you'd like

Localize for Help Message. something are already deprecated, but someone is not depracated, for e.g. V-HACD 2.0 help string added recently.
![Inspector Help](https://user-images.githubusercontent.com/6259214/141970140-fe207a03-b860-4141-8c51-7f880679cde3.png)
![Inventory Help(Deprecated)](https://user-images.githubusercontent.com/6259214/141970252-232b1202-0704-4614-aa90-343f7b1c7898.png)
![V-HACD 2.0 Help](https://user-images.githubusercontent.com/6259214/141970335-9771f93c-c54e-49a7-8d8a-aa9da385a0e5.png)
![New Session Help](https://user-images.githubusercontent.com/6259214/141970435-6b8d9a67-4e1c-4627-8432-4f498b27a15d.png)

### Describe alternatives you've considered

No, it's not. You can prepare it separately, but this is what you get from the button there.

### Additional context

This issue was previously posted by me on NeosLocale( https://github.com/Neos-Metaverse/NeosLocale/issues/656 ). It didn't seem to be getting much attention lately, so I'm posting it here for easier tracking.

**Comment by shiftyscales** [comment]
Hi Kazu- I don't think that cross-posting this issue across both repositories is really appropriate.

That said as well- I don't think it makes sense to localize these. This would be better handled by having hint text/tooltips as per the UI redesign- it's a planned feature, and would likely see these help panels fully deprecated.

If you wish to help in documenting any of this functionality/localizing it- it would likely be best done on the wiki.
