### ISSUE TITLE
For node outputconfusing

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3371]
### Is your tweak request related to a problem? Please describe.

when I am using a For node I often have to second-guess myself because I always think the loop is at the top but no that's when the loop starts but the loop is at the second output which confuses me 

this will probably not be tweaked and just say it's open for documentation which isn't wrong
but still a little confusing
because my brain is like output top start bottom
like how the delay node is

with I think is against the terminology of Neos for example the delay node its output is at the top and where it starts is at the bottom

![image](https://user-images.githubusercontent.com/76523692/142025092-020f7bca-2f49-44ed-9e6c-6cfad7d20fa1.png)

### Describe what would you like tweaked

I would like the start and loop output to be flipped 
this makes way more sense in my head
since this is how all of the notes Act
![image](https://user-images.githubusercontent.com/76523692/142025686-7059ce4c-4ba8-4563-a1b9-9327ba1a91ea.png)

### Describe alternatives you've considered

none really

**Comment by shiftyscales** [comment]
The impulse outputs are currently placed in sequence based on when they will be run. The top most one is when the for loop starts, the middle is for each itteration of the loop inclusively, and the bottom is for the end of the for loop.

The outputs are labelled if you use your Logix tip to aim at them for the time being.

This request wont' be considered, sorry. I hope my post has helped your understanding of why it's ordered the way it is.

Again: They are ordered by where they are in the sequence. You will have one impulse for each of the start and end outputs, and you will have as many loop iteration outputs as you have specified in the for loop count.

![image](https://user-images.githubusercontent.com/54213390/142028762-2d0b1a62-455a-4dcb-b253-642b66e34001.png)

**Comment by Earthmark** [comment]
If you hold a LogiX tool over the pins it'll say what the output name is, currently I think that's the best differentiator.

It's made sense to me that it goes from top to bottom, I can see the case for usage frequency though. 

I think this would break a lot of existing people's workflows though... Conceptually the before and after pins could be re-implemented as a sequence node. That would make the for just have a body, which might be cleaner... But I think this feature has cemented itself pretty well as it is

**Comment by Zyzyl** [comment]
Just for the record, the For node's behavior is documented on the wiki here https://wiki.neos.com/For_(LogiX_node)
