### ISSUE TITLE
Will .net 6 be intergrated it has way better android support as well as very good performance over .net 5

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#3382]
### Is your feature request related to a problem? Please describe.

It's related to rendering engine geenz is working on

### Relevant issues

New rendering engine 

### Describe the solution you'd like

Having .net 6 intergration offers major benefits over .net 5 when it comes to performance and making the android build 

### Describe alternatives you've considered

Not yet

**Comment by Aerizeon** [comment]
As geenz mentioned in the office hours last night, they plan on using dotnet6 for the new engine.

**Comment by alexderpyfox** [comment]
Ah great that's amazing new thanks 🥳
