### ISSUE TITLE
Clicking the version number facet should copy it to the clipboard.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3387]
### Is your tweak request related to a problem? Please describe.

I'm always frustrated when I need to type out my Neos version for bug reports manually.

### Describe what would you like tweaked

Clicking the facet that tells you what version you have should copy said version to your clipboard.

### Describe alternatives you've considered

1. Not doing this. (I don't really see a reason for that though.)
2. Some fancy 'Report a Bug' button that'll bring up the Github bug submission page with stuff like the version number already filled in.

**Comment by epicEaston197** [comment]
something else that you can do and this is what I do is go to the neos updates and copy the most recent version number
![image](https://user-images.githubusercontent.com/76523692/142713290-1e71773e-5f94-4bc4-9956-09209b7574a4.png)
