### ISSUE TITLE
A way to disable the open dash gesture

### ISSUE THREAD

**Issue by art0007i** [Neos-Metaverse/NeosPublic#3399]
### Is your feature request related to a problem? Please describe.

Whenever I press the context menu button with my hand too close to my head it opens the dash instead of the context menu.

### Describe the solution you'd like

Remove this gesture or add a setting to disable it

### Describe alternatives you've considered

n/a

**Comment by Electronus** [comment]
this is a consistent problem for me. Screws me up all the time.

**Comment by DakyDakara** [comment]
Howdy! There is an issue open on this currently. It's: #1130

If you wish to discuss this topic further, move it over to the original GitHub issue.
