### ISSUE TITLE
add ETA to Tween node 

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3406]
### Is your feature request related to a problem? Please describe.

there is no easy way to get the estimated arrival time of a tween node 

### Describe the solution you'd like

I would like an estimated arrival time for the tween Node

### Describe alternatives you've considered

getting the velocity of the object moving and getting a Delta off of it but this doesn't work in some cases where the velocity isn't constant
![image](https://user-images.githubusercontent.com/76523692/143431099-ba6b5f98-1b6b-42f8-a50b-f05cc1e35516.png)

### Additional context

I am making a elevator and I was wanting to have a little display to tell you when you will be arriving but I can't figure out how to get an estimated arrival time to display

**Comment by H3BO3** [comment]
The time you provide to the Duration input on the tween node is how long it will take to complete the tween. This value can be coupled with nodes like elapsed time w/ a few operators to provide a countdown of that value when the tween begins.

**Comment by epicEaston197** [comment]
> The time you provide to the Duration input on the tween node is how long it will take to complete

okay so you're saying if I input 5 seconds it's going to take 5 Seconds to get to its location?

**Comment by Zyzyl** [comment]
I believe so - that's what the documentation says https://wiki.neos.com/Tween_(LogiX_node)

**Comment by ProbablePrime** [comment]
This is correct.

Do you need this issue?

**Comment by epicEaston197** [comment]
> This is correct.
> 
> Do you need this issue with this in mind?

I don't know. 

maybe it could be a float variable that would tell you when it arrives

**Comment by ProbablePrime** [comment]
You can put the output of "Tween Start" into an Elapsed Time node to calculate that.

Minusing the input to tween from the output of Elapsed time will then give you this value.

**Comment by epicEaston197** [comment]
> Minusing the input

I'm sorry the input to what?

**Comment by ProbablePrime** [comment]
The input to duration.

Duration - Elapsed Time output => time remaining

**Comment by epicEaston197** [comment]
> The input to duration on the tween node
> 
> Duration - Elapsed Time output => time remaining

can we move this Discussion into the Discord? so that we don't flood the issue tracker

**Comment by ProbablePrime** [comment]
Here's a video showcasing the solution as I understand it: https://i.probableprime.co.uk/211125-dYjMVA2piT22vvtRqrln.mp4

**Comment by epicEaston197** [comment]
thanks a lot I understand thanks for the help I will issue this you
