### ISSUE TITLE
Ability to give Custom badges

### ISSUE THREAD

**Issue by skywindkitsune** [Neos-Metaverse/NeosPublic#3408]
### Is your feature request related to a problem? Please describe.

The Patreon Custom Badges are only for the user that requested it.

### Describe the solution you'd like

I would like to be able to give the custom badge that comes with the patreon benefit to other users via Neosbot command like the devs are able to with their custom badges.

For example to earn the coffee badge you had to impress coffee with a project, i would like to be able to do the same thing and i think it would be a fun thing to have for Patreon users.

### Describe alternatives you've considered

you could make a fake badge, but it's only for the avatar you wear.

**Comment by shiftyscales** [comment]
This request is probably best served by the existing Group Badge issue #2448.

Coffee's badge has been retired, and no other member of the team has such a badge shared in that way I am aware of. So I don't believe that to be a relevant comparison.

Individuals can message me to claim a custom badge (including one already in use by a friend) if they are of the appropriate Patreon tier and have the permission of the original badge holder to use it in their custom badge slot.
