### ISSUE TITLE
Oculus Quest 2 with steamvr: right controller a and b buttons not detected in neos

### ISSUE THREAD

**Issue by zodywoolsey** [Neos-Metaverse/NeosPublic#3411]
### Describe the bug?

When using my Oculus Quest 2 with Oculus link or virtual desktop, if Neos is launched using SteamVR runtime, the and b buttons on the right controller aren't detected.

Issue doesn't occur in other games or when Neos is launched through the Oculus XR runtime. The workaround I found is to use the standalone version added to steam library with launch args "-RiftTouch".

### Relevant issues

None

### To Reproduce

Launch Neos through steam or standalone launcher using the steamvr runtime without launch args.

### Expected behavior

All controller inputs work appropriately when launched using steamvr.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.11.10.1265

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

2021.11.10.1265

### Reporters

Discord:
zodie#2222
Neos:
zodiepupper

**Comment by FlameSoulis** [comment]
Launched Neos via SteamVR on Virtual Desktop with an Oculus Quest 1 (don't have the second one). Cannot replicate. Buttons all appear to function just fine. Can someone with a Quest 2 confirm this?

**Comment by zodywoolsey** [comment]
I actually discovered that SteamVR applied a random controller config by itself at subs point and it was causing some buttons not to work. Changed the setting to use the default config and it seems to be fixed.
