### ISSUE TITLE
Component Clone Tip doesn't paste components of the same existing type even if data is different

### ISSUE THREAD

**Issue by RobertBaruch** [Neos-Metaverse/NeosPublic#3437]
### Describe the bug?

If there's an object with a particular component, then attempting to clone another component of the same type but with different data into that object doesn't do anything. This is particularly annoying when cloning several DynVars of the same type but different names.

### Relevant issues

N/A

### To Reproduce

1. Create an object with a DynamicSpace, leaving the name empty.
2. Create another object with a DynamicSpace, with name "A".
3. Grab the component from step 2 with the component clone tip.
4. Attempt to copy the component into the object from step 1.
5. Observe that nothing happens.

### Expected behavior

In the example above, I should end up with an object with two DynamicSpaces, one with empty name, and one with "A".

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.11.10.1265

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

Xekri

**Comment by shiftyscales** [comment]
Hi @RobertBaruch - I was unable to replicate this issue. There is a "Single Instance" option in the context menu of the ComponentCloneTip, please ensure this is set to "Off".

**Comment by RobertBaruch** [comment]
Oops, didn't see that. Thank you!
