### ISSUE TITLE
LNL Relay host does not appear to be functional

### ISSUE THREAD

**Issue by Bontebok** [Neos-Metaverse/NeosPublic#3441]
### Describe the bug?

When attempting to force the use of LNL Relay by placing a Neos client behind a Strict NAT and exiting Steam, this results in the inability to connect to any world followed by a red "Failed" message.

I believe the LNL Relay server may not be operational causing a fallback to Steam Sockets when available, or a complete connection failure when Steam Sockets are not available.

### Relevant issues

A handful of users have reported having connection problems across the Neos Discord groups over the past few days and possibly even longer. Some messages indicated that they saw the LNL Relay message seen followed by a Fail. Additionally, this was brought up during Prime's Office Hours which lead to my interest in investigating this further.

Note: I am unsure if this issue relates to any other connection issues related to being disconnected from sessions or being "booted" after joining sessions which is why I am not combining this with other connectivity issues.

### To Reproduce

Utilize a type-3 NAT router such as pfSense, OPNsense, CheckPoint, Cisco ISA etc where the UDP port numbers are not preserved. In my case, I am using an OPNsense router with the "Static Port" option disabled in a custom rule which will preserve UDP ports to enable UDP hole punch connections.

### Expected behavior

After the LNL Relay is displayed, the world should begin syncing.

### Log Files

Attached in comments.

### Screenshots

![image](https://user-images.githubusercontent.com/23562523/145143962-6e54ead7-d931-4562-830b-0c2091e33409.png)
![image](https://user-images.githubusercontent.com/23562523/145143979-6d2f4dc3-c93e-41bf-b1d7-9a3009ad4b7c.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.11.10.1265

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

Unsure as I've made all attempts to not use the LNL Relay by default

### Reporters

Talt - https://discord.com/channels/402159838827905024/439422161657135106/917452431338651668
macromarko - https://discord.com/channels/402159838827905024/439421735474036738/917827455014821928
Duskitten - https://discord.com/channels/402159838827905024/901071679898411059/917570844518125659

**Comment by Bontebok** [comment]
[CARIBOU - 2021.11.10.1265 - 2021-12-07 22_17_28.log](https://github.com/Neos-Metaverse/NeosPublic/files/7673275/CARIBOU.-.2021.11.10.1265.-.2021-12-07.22_17_28.log)

**Comment by Bontebok** [comment]
Here is a video clip showing multiple connections with a client behind a Type-3 (port independent/strict NAT) where this would require connection to a Type-1 (host not behind a NAT) or through the LNL Relay. However, as you can see all connection attempts are failing as the LNL Relay does not appear to be functioning.

https://www.youtube.com/watch?v=-DORwivpV18 [YouTube](https://www.youtube.com/watch?v=-DORwivpV18)

**Comment by Earthmark** [comment]
This is likely strongly related to 
https://github.com/Neos-Metaverse/NeosPublic/issues/3360
https://github.com/Neos-Metaverse/NeosPublic/issues/3357
https://github.com/Neos-Metaverse/NeosPublic/issues/3381

The actual cause may be different, but something possibly shifted the relay to no longer being able to handle the load it's under.
Possibly a change in the lnl library is deferring to the relay more often. More investigation is needed.

**Comment by ProbablePrime** [comment]
Thanks for your reports everyone, We've mitigated some issues with the LNL relay today and our QC tam are double checking things are fixed here. 

Hopefully this one should be good to go :)

**Comment by Bontebok** [comment]
I can report that the LNL Relay is back up, the highlighted green packets are from the LNL Relay. I was able to successfully connect to all worlds I tried behind an Strict / Type-3 NAT. Audio was clear and not broken up, packets were coming in at a smooth and consistent rate.

![image](https://user-images.githubusercontent.com/23562523/146241371-ce006560-d7d0-45e7-ae65-3dabeb721266.png)
