### ISSUE TITLE
Spawn A session orb / copy session url from friends tab.

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#3468]
### Is your feature request related to a problem? Please describe.

currently, session orb can spawn only world browser, but sometimes has a problem. if session sets hidefromlisting, session orb can't spawn normally, and otherwise if i want to spawn a session orb and/or copy session url, currently have to move a world browser and re-search this session.

### Relevant issues

This issue is forused of UI re-design, so might be related #299

### Describe the solution you'd like

Spawn a session orb / copy session id/url from friend tab invitation and world list. 
![image](https://user-images.githubusercontent.com/6259214/146627864-e5bc5745-1389-4bdc-a969-155810115938.png)

![image](https://user-images.githubusercontent.com/6259214/146627607-a3b0f046-f192-41da-85dc-98235ac39d27.png)

### Describe alternatives you've considered

Currently we can check from worldbrowser without session is hidden. if hidden, we can send session url directly or send direct ip to join without this solution.Either way, it's a lot of work.

**Comment by epicEaston197** [comment]
this menu is planned to be overhauled so doing this would be a waste of time 
you can find it here on the roadmap
https://github.com/Neos-Metaverse/NeosPublic/projects/2

**Comment by kazu0617** [comment]
> this menu is planned to be overhauled so doing this would be a waste of time you can find it here on the roadmap https://github.com/Neos-Metaverse/NeosPublic/projects/2

I know. so when UI overhaul prototyping for contacts, please ref this issue.

**Comment by kazu0617** [comment]
I create a mod for resolve this issue.
https://github.com/kazu0617/SessionTweaks

**Comment by kazu0617** [comment]
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/97
