### ISSUE TITLE
Duplicating dynamic bones causes Neos to freeze momentairly

### ISSUE THREAD

**Issue by Anomalous** [Neos-Metaverse/NeosPublic#347]
Creating issue for this per Frooxius's instruction, here's the text from Discord describing the issue:

>I noticed recently that duplicating an object with a bunch of dynamic bones on it freezes Neos for a couple seconds.
>
>I was experimenting with the trajectory node and made a gun that shoots this thing:
>![Image of dynamic bone thing](https://cloudxstorage.blob.core.windows.net/assets/14b08d294b6283d1ad2b0dd06d8026d41c9bc1f78d3fe6f8598ff60cbeba07c0)
>
>Neos would freeze when the slot was duplicated, and by the time everything was drawing again the thing would already be at the end of the trajectory. This is just dynamic bones on non-textured primitives, so it's a nice simple example.

>I think it's about 15 dynamic bones, each with maybe 10 segments?
>Duplicating either via copy on the wrist menu or via LogiX slot duplication both freeze Neos for a second or two, but it's a lot more noticeable when duplication is via gun trigger rather than wrist menu because it's so much faster to do.

I'll be sending Frooxius a copy of the item and the gun that copies and shoots them on a trajectory. It might be useful for someone else to try duplicating the object or using the gun also to see if the same freezing behavior occurs.

**Comment by TehTurk** [comment]
Wouldn't know if we needed a proper topic on this or not, but I've also always noticed duplicating a single object is fast and easy, while anything 20+ or even 50+ as it gets higher duplicating and deleting can also get very very application heavy and will cause freezing or lagging that persists until world restart. or rejoining the session. But situations where it cycles through the slots children index being deleted or duped through logix is a bit faster.

**Comment by Frooxius** [comment]
@TehTurk That's unavoidable, the more objects you duplicate, the more work the system has to do. If you keep increasing the number (especially duplicating already duplicated, so it grows exponentially) it'll have more and more to work through.

There are some things in the duplication that I plan on optimizing (or spawning objects in general), but it will always get more or less slower the more items you duplicate.

**Comment by Frooxius** [comment]
This seems much better now with 2020.12.30.1285 and the duplicate system optimization, although there still seems to be a bit of noticeable glitch. Should I keep this open until some more optimizations are done or are you ok closing this?

**Comment by shiftyscales** [comment]
This seems to be a non-issue by this point, at least on my system. I think this can be closed out.
