### ISSUE TITLE
[Feature] Separated spatialized audio channels

### ISSUE THREAD

**Issue by clarjon1** [Neos-Metaverse/NeosPublic#3474]
### Is your feature request related to a problem? Please describe.

Currently, spatial audio sources are muxed down to be mono, and only a single source point is usable

In other systems (unity for example) i've been able to place spatialized audio channels to have the respective channel come from that location

### Relevant issues

I've been told that some of steam audio's library can assist with handling this by 3x1t_5tyl3 on discord, and i see Froox has an issue open in #2693, however i do not see this usecase being mentioned yet

### Describe the solution you'd like

A UI for placing spatialized channels, perhaps little speaker icons that get spawned when clicking an additional button relating to an audio source to spatial channel sources for placement, and be able to assign them, either thru logix or inspector UI, to the appropriate audio channel (eg left/right/center/rear-left/rear-right/etc)

Users would then be able to place the spatial channel sources around their scenes as they desire, allowing for effects and audio to come from multiple areas in the scene, all from a single audio file or video file or streaming video source, and interact with them with logix as expected

This would allow for video stream players to be able to look at the incoming audio and set the available channels, outputting to the preplaced options as an example, and corresponding logix might be able to see that a video only supports left/right/center audio and set the tagged sources as expected, a mono source could set all tagged to use the same source for the appropriate effect, or whatever handling is coded in by the tool creator

### Describe alternatives you've considered

Creating multiple audio files of audio tracks with it mixed down for the specific audio channels, then syncing up via logix. howver, this is a ton of extra work, and has various syncing issues.

other users, such as for DJ purposes, have multiple live audio streams being fed into neos to simulate this, which is a bit complex to setup, and has a lot of moving parts to complicate things, vs being able to setup a world that'd be able to take a single audio stream and split up the channels and apply to the preset spatial sources automagically.

**Comment by Enverex** [comment]
There is already a ticket open about this, a much older one - https://github.com/Neos-Metaverse/NeosPublic/issues/421

**Comment by H3BO3** [comment]
Closing this as a duplicate since I believe 421 already covers this case, perhaps not the exact implementation that we'll get, but one nevertheless
