### ISSUE TITLE
Midpoint logix node

### ISSUE THREAD

**Issue by Crusher50** [Neos-Metaverse/NeosPublic#3478]
### Is your feature request related to a problem? Please describe.

Currently there is no Logix node that calculates the midpoint between two points.

Although it is still possible to get the wanted result without a node for it, a dedicated node will help with clutter.

### Describe the solution you'd like

A logix node that calculates the midpoint between two points. 

### Describe alternatives you've considered

Although there is no singular logix node to find the midpoint, you can use the midpoint formula to work it out. 
![image](https://user-images.githubusercontent.com/91010433/146939899-dbad698d-7f45-4ae3-aa31-c87f4f2cd5d5.png)

**Comment by shadowpanther** [comment]
Did you try to just `+` your `float3` values without unpacking them?

**Comment by TheBasementNerd** [comment]
This can actually be achieved in a single node using a lerp, putting your two values in the From and the To, and then putting 0.5 in the Lerp input

**Comment by ProbablePrime** [comment]
Try the Avg node. its in Math.

AVG is:  (A + B) / 2.

**Comment by Crusher50** [comment]
@ProbablePrime Avg works

**Comment by ProbablePrime** [comment]
Thanks :)
