### ISSUE TITLE
Avatars don't spawn when host is not in session.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3488]
### Describe the bug?

When the host of a session isn't in the session and people join, their avatars won't load until the host comes back.

### Relevant issues

#3485 seems to stem from the same reason, maybe.

### To Reproduce

1. Join a world with the host not being there.
2. Your avatar won't load until the host comes back.

### Expected behavior

Your avatar should load, regardless of whether or not the host is present.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.11.10.1265

### What Platforms does this occur on?

Windows, Linux

### Did this work before?

I Don't Know

### Reporters

Cameron#7818 (me) and pretty much everyone else I know.

**Comment by Nammi-namm** [comment]
I believe when I was new to Neos about two years back and asked in-game about this behaviour to people more experienced with the game, they told me it was intentional behaviour. If its an issue its been a very longstanding one then.
