### ISSUE TITLE
Equip Avatar Node does not work with RawDataToolTipEvents

### ISSUE THREAD

**Issue by BigRedWolfy** [Neos-Metaverse/NeosPublic#3494]
### Describe the bug?

When using this tool normally the user doesn't equip the avatar (without the destroy slot and the "Destroy Old" input being set to true, nothing happens other than the PlayOneShot audio.

Observed that the node works as intended when using the Pulse node

### Relevant issues

No

### To Reproduce

Use primary with the tool equipped and pointing at yourself or others to observe the bug

Put any slot under a person's avatar into the slot storage node and use the pulse button to see the desired effect

### Expected behavior

When using the tool it should function the same as if pressing the "Pulse" button which is connected to the PlayOneShot Node assuming the Slot storage node has a valid slot under someone's avatar

### Log Files

Message R3ido101#4995 on discord for logs

### Screenshots

![20211228140237_1](https://user-images.githubusercontent.com/1814393/147525563-f25672a4-9bc5-41ad-9d8e-965a1f06df92.jpg)
### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2021.11.7.784

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

neosdb:///d0fe8079ae75bce4a24a86a7b11fb3d0864c39401506fb7135d4b74390e9aeca.7zbson

### Did this work before?

I Don't Know

### Additional context

The avatar being equipped is located on the tool in an inactive slot, however the avatar is not inactive

When the avatar is duplicated the duplicate remains where it is when it doesn't get equipped by the user

Tried with avatars that had avatar protection and no avatar protection

Removed audio portion of the tool and observed the same findings

### Reporters

R3ido101 (Discord: R3ido101#4995)
BigRedWolfy (Discord: Red Wolf#6715)

**Comment by OfficialR3ido101** [comment]
This is not a bug. Forgot to add the dupe slot to root.
