### ISSUE TITLE
Allow CharacterParenter to trigger for Noclip users as well

### ISSUE THREAD

**Issue by marsmaantje** [Neos-Metaverse/NeosPublic#3496]
### Is your tweak request related to a problem? Please describe.

When using CharacterParenters for tracking users, culling objects or moving them with a platform the user needs to be in a physical locomotion. This can cause issues when you want to go into Noclip to take a closer look at things adn the world dissapears.

### Describe what would you like tweaked

It would be nice to have a checkbox on the CharacterParenter to allow for parenting Noclip users as well. By default this would be turned off so no existing maps get broken.

### Describe alternatives you've considered

Write custom logix for parenting users to slots if they are close enough.

**Comment by ProbablePrime** [comment]
Apologies but we won't be implementing this, No Clip is designed from the ground up to avoid any collisions with the environment. 

You can read more about this here: #1143
