### ISSUE TITLE
Dragging URI input into an == node creates string Override.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3560]
### Describe the bug?

When trying to make an == node compare two URIs, the inputs will become String inputs instead of URI inputs and the nodes won't get connected. The same goes for nodes such as not equals, plus, greater than, less than...

### Relevant issues

Didn't find any.

### To Reproduce

1. Get an == node from Operators.
2. Get a Uri input node from Inputs.
3. Plug the Uri input into the ==.
4. Observe the String type == and the missing connection you have not created.

### Expected behavior

The == should have a Uri overload and be able to just compare those as well.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2021.11.10.1265

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

Cameron#7818

**Comment by ProbablePrime** [comment]
I have a branch somewhere that does this, its quite old as i had a bunch of URI modifications in it, so I'll take this into my pile of assigned issues yay.
