### ISSUE TITLE
Sessions that don't exist anymore frequently show in the world browser.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3563]
### Describe the bug?

When checking active sessions (or contacts sessions) the list will quite often include some sessions that haven't been open in days, weeks or months. They frequently appear and disappear from the list and when clicking on them it either shows the user list of who was in there all those weeks ago, it'll say that there's no active sessions or it'll just say (no name) with no picture or user list.

Most of these sessions have thumbnails a lot of the time, except for one which used to but now only shows up as checkerboard.

### Relevant issues

Didn't find any.

### To Reproduce

Start up Neos and watch the Active Sessions or Contact Sessions tab for a while.

### Expected behavior

For only sessions that actually exist and are active to show in Active Sessions.

### Log Files

[SYSTEM-PURPLE - 2021.11.10.1265 - 2022-01-28 10_20_13.log](https://github.com/Neos-Metaverse/NeosPublic/files/7957438/SYSTEM-PURPLE.-.2021.11.10.1265.-.2022-01-28.10_20_13.log)
In this log file, I started up the game, saw Rustybot's home in the sessions despite it not being open and closed the game again.

### Screenshots

![image](https://user-images.githubusercontent.com/60073468/151524456-7a3158f9-0835-4950-87f8-97116e9174d3.png)
![image](https://user-images.githubusercontent.com/60073468/151524463-50c422d2-56c7-478b-afbf-988b81e393c7.png)
![image](https://user-images.githubusercontent.com/60073468/151524476-671fd07d-3792-4ddf-8baa-82fe282b2188.png)
![image](https://user-images.githubusercontent.com/60073468/151524576-a9f03b79-dd9f-42e5-b8c5-c6cf75edfa1a.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.11.10.1265

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

2021.11.10.1265

### Additional context

In the time it took me to write this, I saw at least 5 different sessions that don't exist anymore pop up in Contacts Sessions, then stay for a bit and disappear again.
("The Hive decorating", "tempSpace", "rustybot's home", "Viridian Islands (copy)" and "Kodey's knockoff homeworld")

### Reporters

Cameron#7818

**Comment by JackTheFoxOtter** [comment]
Can confirm, have the same issues with sessions that are ANCIENT (like, many months old).

I did notice that it may be linked to pending friend requests, those tend to sometimes show sessions on them (perhaps the session you met the person in when they sent a request?). I noticed that after highlighting one of those pending friend requests, I saw the old session popping in and out in the world browser.

My assumption is that those are sessions that are cached to still be displayed somewhere (with full session data, like the people that were in at the time it got cached), but stored similarly to normal, active sessions. So it is loaded from cache, a few moments later the game realizes the session isn't active anymore and removes it from the world browser, before it is loaded from cache again. (That would explain the really annoying appearing and disappearing, making browsing worlds quite the hassle sometimes.)

**Comment by Psychpsyo** [comment]
Not sure if the two are related but yes, pending friend requests do keep the other user appearing on the sessions that they were in when they sent the request.
And I just checked: 4 of the 5 non-existent sessions that regularly pop up for me are indeed on some old friend requests as well.
But getting rid of the friend request doesn't seem to stop the session from showing up.
But I also have plenty of old friend requests that have sessions associated with them that don't show up in the world list so it's far from a 1:1 thing.

**Comment by epicEaston197** [comment]
resynchronizing my computer clock fixed it but there is one session that has been closed for over 80 Days and it won't go away for my browser I've been wanting to make a GitHub issue about this but I thought it was a only me problem but it did go away when I resynchronize my computer clock

**Comment by Nytra** [comment]
I made a mod that can detect and hide these sessions https://github.com/Nytra/NeosWorldListSessionHider
