### ISSUE TITLE
Newly uploaded images cannot be loaded back from cloud.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3574]
### Describe the bug?

As of recent (first noticed this on Saturday, 29th of January) uploading and then downloading certain images to/from the cloud has become impossible.
I simply import the image, save the resulting item to the cloud and after that I am unable to spawn it from the cloud.
Instead of the regular image, I receive a 0x0, completely white image. (see screenshot)

This is not entirely reliable, and sometimes the image loads, sometimes it doesn't, but it seems to only affect newly uploaded images; I have not seen this happen to any older images.

### Relevant issues

Didn't find any.

### To Reproduce

1. Import an image.
2. Save it to your inventory.
3. Restart Neos.
4. Spawn the image.
5. Observe that it is entirely white.

### Expected behavior

The image should be able to load.

### Log Files

[SYSTEM-PURPLE - 2022.1.28.1310 - 2022-02-02 06_41_00.log](https://github.com/Neos-Metaverse/NeosPublic/files/7983906/SYSTEM-PURPLE.-.2022.1.28.1310.-.2022-02-02.06_41_00.log)

The relevant error seems to be
6:46:39 AM.783 ( 75 FPS)	Error decoding texture variant: Type: Texture2D, FilterMode: Bilinear, Aniso: 0, WrapU: Repeat, WrapV: Repeat, WrapW: Repeat, MipMapBias: 0, Readable: False, Exact: False, Compression: BC1_LZMA, Quality: 100, Width: 4096, Height: 10748, Mipmaps: True, Filtering: Box, File: D:\NEOS Stuff\Cache\Cache\aschifcf74khwztc, URL: neosdb:///580bad818c094ccd252baa5bc6a4bbde070b453086ccaf138a1a49725bbb6b5b

as that is the right neosdb link to the image & its resolution.

### Screenshots

![image](https://user-images.githubusercontent.com/60073468/152101182-29f907b6-d48a-4ad6-b11c-31f8591e4636.png)

### How often does it happen?

Sometimes

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2022.1.28.1310

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

2021.11.10.1265

### Additional context

The images in question are quite large (4Kx10K) and WEBPs. I have yet to try different formats and resolutions but I currently don't have much time. Sorry for that.

### Reporters

Cameron#7818

**Comment by shadowpanther** [comment]
Do other users see the correct image or white image? Does clearing your cache help? In particular, try removing the file `aschifcf74khwztc` from the cache folder and spawning the image again.

**Comment by Psychpsyo** [comment]
> Do other users see the correct image or white image? Does clearing your cache help? In particular, try removing the file `aschifcf74khwztc` from the cache folder and spawning the image again. Might be the same as #3566

Other people were able to see the image just fine.
I have just now cleared my cache and reattempted this (with a new image) and it still does it.

**Comment by shiftyscales** [comment]
LZMA variant textures were being encoded raw causing this issue to occur, a hotfix has been pushed to the cloud, and a script run to clear out incompatible/variants. They should re-generate when the content is loaded and this issue should be resolved.
