### ISSUE TITLE
Textures (common ones and baked reflection probe cubemaps) Failing to Load

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#3600]
### Describe the bug?

Baking reflection probes appears to work fine, but if you bake a reflection probe on a headless, save the world then reload the world, the cubemap will still be slotted, but will be 0 bytes.

### Relevant issues

None.

### To Reproduce

Host a world on a headless that the headless can save.
Create and bake a reflection probe.
Have the headless save the world.
Reload the world on the headless to refresh the session.
The cubemap will still be in the slot, but the actual cubemap image will be invalid.

### Expected behavior

For cubemaps to save and load as normal.

### Log Files

Example failure after world reload.

```
00:22:45.019 (144 FPS)    Error decoding texture variant: Cubemap, FilterMode: Trilinear, Aniso: 0, MipMapBias: 0, Exact: False, FrooxEngine.CubemapVariantDescriptor, File: C:/Users/ben/AppData/Local/Temp/Solirax/NeosVR\Cache\tc23ll6rhhxxlm1n, URL: neosdb:///057a2edfa5ce775366f06a2b814c7ff7a0fbda0404bc676ee70ad87e55e60452
00:22:45.022 (144 FPS)    Exception decoding texture asset: C:/Users/ben/AppData/Local/Temp/Solirax/NeosVR\Cache\ahobq294wrnyhp69
Variant: Cubemap, FilterMode: Trilinear, Aniso: 0, MipMapBias: 0, Exact: False, FrooxEngine.CubemapVariantDescriptor
VariantIdenfifier: compression=BC6H_LZMA&quality=60&size=256&mips=False
System.Exception: Invalid Cubemap binary version: 3
  at CodeX.BitmapCube.Decode (System.IO.Stream stream) [0x00040] in <17d595f1a18a42ed8193dcc24354befe>:0 
  at CodeX.BitmapCube.Load (System.String file) [0x00007] in <17d595f1a18a42ed8193dcc24354befe>:0 
  at FrooxEngine.Cubemap.DecodeFile (System.String file, FrooxEngine.CubemapVariantDescriptor variant, System.Boolean forceMips) [0x00030] in <4569e221aae944528482d45ba46712b2>:0 
  at FrooxEngine.Texture`5+<LoadTargetVariant>d__37[E,D,C,M,B].MoveNext () [0x005c5] in <4569e221aae944528482d45ba46712b2>:0 

   at void BaseX.UniLog.Error(string message, bool stackTrace)
   at async void FrooxEngine.Texture<FrooxEngine.CubemapVariantDescriptor, CodeX.CubemapVariantDescriptor, FrooxEngine.ICubemapConnector, CodeX.CubemapMetadata, CodeX.BitmapCube>+<LoadTargetVariant>d__37.MoveNext()
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(object stateMachine)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at void BaseX.WorkProcessor.ProcessQueue(ThreadWorker worker, ConcurrentQueue<Action> queue)
   at void BaseX.WorkProcessor.JobWorker(ThreadWorker worker)
   at BaseX.WorkProcessor+ThreadWorker(WorkProcessor processor, Worker worker, WorkType targetWorkType, ThreadPriority priority, int index)+() => { }
   at void System.Threading.ThreadHelper.ThreadStart_Context(object state)
   at void System.Threading.ThreadHelper.ThreadStart()
00:22:45.026 (144 FPS)    Error decoding texture variant: Cubemap, FilterMode: Trilinear, Aniso: 0, MipMapBias: 0, Exact: False, FrooxEngine.CubemapVariantDescriptor, File: C:/Users/ben/AppData/Local/Temp/Solirax/NeosVR\Cache\ahobq294wrnyhp69, URL: neosdb:///057a2edfa5ce775366f06a2b814c7ff7a0fbda0404bc676ee70ad87e55e60452
```

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2022.1.28.1335

### What Platforms does this occur on?

Linux

### Did this work before?

I Don't Know

### Additional context

The asset appears to upload as it syncs, but clearly something goes wrong somewhere. This has been tested in multiple worlds.

**Comment by kulzae** [comment]
Adding comments from the issue i created to merge with this one

Describe the bug?

When loading a world from the cloud it appears that baked reflection probe cubemaps are failing to load or are being wiped from the database. this has occurred multiple times over several days with seemingly no pattern. and has been confirmed by loading the world record from another computer and account with a fresh database. the baked cubemap appears as 0kb grey image

Relevant conversation per Shifty https://canary.discord.com/channels/402159838827905024/439422161657135106/941200321651281920

The linked relevant issue describes on headless save but I am not using a headless nor its the issue appearing on save and instead seems to occur on load

My reasoning for this is i had just experienced a BSOD and had not saved the world losing all my work from the previous save. Upon loading the world again to replace what had not save the cubemaps were gone where as i know they were there before the BSOD.
Relevant issues

https://github.com/Neos-Metaverse/NeosPublic/issues/3600
To Reproduce

Create a world and add reflection probes

Load the world

Observe the cubemaps are now grey. this does not happen at every load and could take several days between

**Comment by orange3134** [comment]
I ran into a similar problem, but it wasn't headless.

How to reproduce the problem I encountered
1. Open a world that is already stored in my inventory.
2. Create a Reflection probe.
3. Save the world as a different one with Save as.
4. Close the world once.
5. When I open the newly saved world, the Reflection probe cubemap is 0kb.

Solution
Set "Direct load" of the cubemap to True.

**Comment by Bontebok** [comment]
Some notes for the Devs. Tonight I looked into this further and it appears that the Cubemap file format changed slightly and can no longer be read from the Neos client or the data is getting corrupt at some point and cannot be read.

At some point, likely on or before the last Neos update in November, the Cubemap header for asset variants changed and these files are no longer readable by the Neos client.

Before - (02 version)

```
00000000  07 42 6d 70 43 75 62 65  02 00 00 00 00 01 00 00  |.BmpCube........|
00000010  00 01 00 00 20 00 01 01  5d 00 00 20 00 f0 ff 3f  |.... ...].. ...?|
```

After - (03 version)

```
00000000  07 42 6d 70 43 75 62 65  03 00 00 00 80 00 00 00  |.BmpCube........|
00000010  80 00 00 00 45 00 00 01  04 73 52 47 42 5d 00 00  |....E....sRGB]..|
```

The reason why the Direct load option works is that the raw RGB/uncompressed asset is retrieved from the NeosDB and this file is still stored in the "02" version. In looking through older published worlds, all variants were uploaded in the "02" format and those Cubemaps continue to correctly load. I could not find a world with a Cubemap at version 3

I'm unable to isolate if the issue is within the Client or the Neos cloud (what generates the 03 variant files, the client or the cloud?) however it does not appear that a Neos client is able to process any of the 03 files coming from the NeosDB.

**Comment by Bontebok** [comment]
Additional information and a theory.

I set up a transparently mitm to capture the traffic to the Neos API and I found something interesting. In all cases and in two different Neos clients, I was able to find that the upload for the Cubemap variants are being rejected by the Neos API.

I installed Neos v 2021.11.10.896 (couldn't find the blobs for 2021.11.10.1253, if you have them please send!) and I can confirm that reflection probe / Cubemap issue is present in that version as well. When tracing the Neos API calls, I did find multiple Forbidden responses when my client attempted to upload the variant. 

```
192.168.1.100:54950: PUT https://api.neos.com/api/assets/343cf6e9fbd9fd50f09f4c23eef1432de63881f7b334f7eb1c5961403388bc83/cubemapMetadata
                << 200 OK 0b
192.168.1.100:54950: POST https://api.neos.com/api/users/U-Rucio/assets/343cf6e9fbd9fd50f09f4c23eef1432de63881f7b334f7eb1c5961403388bc83&compression=BC6H_LZMA&quality=60&size=128&mips=False/chunks?bytes=88702
                << 403 Forbidden 0b
192.168.1.100:54950: POST https://api.neos.com/api/users/U-Rucio/assets/343cf6e9fbd9fd50f09f4c23eef1432de63881f7b334f7eb1c5961403388bc83&compression=BC6H_LZMA&quality=60&size=256&mips=False/chunks?bytes=344150
                << 403 Forbidden 0b
192.168.1.100:54950: POST https://api.neos.com/api/users/U-Rucio/assets/343cf6e9fbd9fd50f09f4c23eef1432de63881f7b334f7eb1c5961403388bc83&compression=BC6H_LZMA&quality=60&size=32&mips=True/chunks?bytes=7470
                << 403 Forbidden 0b
192.168.1.100:54950: POST https://api.neos.com/api/users/U-Rucio/assets/343cf6e9fbd9fd50f09f4c23eef1432de63881f7b334f7eb1c5961403388bc83&compression=BC6H_LZMA&quality=60&size=64&mips=False/chunks?bytes=20548
                << 403 Forbidden 0b
192.168.1.100:54950: PUT https://api.neos.com/api/assets/674b3e7aabe4f2213a69a7c2b4bdbf07381ed182f19ece8f767dcfbcce681e28/bitmapMetadata
                << 200 OK 0b
```

However, even though this upload fails, I can still retrieve the asset variant from the cloud. ex: https://assets.neos.com/assets/343cf6e9fbd9fd50f09f4c23eef1432de63881f7b334f7eb1c5961403388bc83/compression=BC6H_LZMA&quality=60&size=256&mips=False&legacyHDR=False

I find it interesting that the file size has grown by exactly 5 bytes for each of the variants. Is it possible that the cloud is somehow processing and incorrectly creating the variants?

This tells me that the CLOUD is generating these asset variants in the background and this is where the issue may lie...

```
256 Chunk size failed = 344150
256 Asset size received = 344155

128 Chunk size failed = 88702
128 Asset size received = 88707

64 Chunk size failed = 20548
64 Asset size received = 20553
```

My working theory - the asset variant uploads from the Client are failing (being rejected by api.neos.com) and the cloud is creating the missing variants in some mysterious "03" format that the Neos client does not recognize. I believe the additional 5 bytes found in the file are the addition of the "sRGB" text in the header and one additional byte.

Suggestion for Devs: Determine why the Cubemap variant assets are being rejected by the Neos API, additionally determine why generated Cubemap variants generated in the cloud are being created in a version that the Neos client is unable to parse resulting in Cubemaps variants failing to load.

**Comment by shadowpanther** [comment]
This also affects other textures (not cubemap ones). An excerpt from @Aerizeon's [log](https://github.com/Neos-Metaverse/NeosPublic/files/8115838/DESKTOP-M6LBCPT.-.2022.1.28.1310.-.2022-02-22.03_45_05.log) from #3619:
```
5:26:28 AM.426 (105 FPS)	Starting GatherJob for neosdb:///9dbc06a3ba56bba79b0fe6840d0bcd52c887850e269b5832071e342ccc529ca9?version=2&compression=BC3_LZMA&quality=100&width=1024&height=1024&mips=False&filtering=Box&legacyHDR=False, AttemptsLeft: 5
5:26:28 AM.448 (105 FPS)	Finished Gather for: neosdb:///9dbc06a3ba56bba79b0fe6840d0bcd52c887850e269b5832071e342ccc529ca9?version=2&compression=BC3_LZMA&quality=100&width=1024&height=1024&mips=False&filtering=Box&legacyHDR=False. Elapsed: 0.0220035 s
5:26:28 AM.456 (105 FPS)	Exception decoding texture asset: C:/Users/Epsilion/AppData/Local/Temp/Solirax/NeosVR\Cache\vby1o6ht2li87evt
Variant: Type: Texture2D, FilterMode: Anisotropic, Aniso: 8, WrapU: Clamp, WrapV: Clamp, WrapW: Repeat, MipMapBias: 0, Readable: False, Exact: True, Compression: BC3_LZMA, Quality: 100, Width: 2048, Height: 2048, Mipmaps: True, Filtering: Box
VariantIdenfifier: version=2&compression=BC3_LZMA&quality=100&width=1024&height=1024&mips=False&filtering=Box&legacyHDR=False
System.IO.InvalidDataException: Version is too new: 1
  at CodeX.Bitmap2D.LoadRaw (System.IO.Stream stream) [0x00044] in <9305dcafe5b3481fab676401a77501cd>:0 
  at CodeX.Bitmap2D.LoadRaw (System.String file) [0x00007] in <9305dcafe5b3481fab676401a77501cd>:0 
  at FrooxEngine.Texture2D.DecodeFile (System.String file, FrooxEngine.Texture2DVariantDescriptor descriptor, System.Boolean forceMips) [0x000a3] in <a6ff441fca7c4a97bc5b9dca720b524b>:0 
  at FrooxEngine.Texture`5+<LoadTargetVariant>d__37[E,D,C,M,B].MoveNext () [0x005c5] in <a6ff441fca7c4a97bc5b9dca720b524b>:0 

   at void BaseX.UniLog.Error(string message, bool stackTrace)
   at async void FrooxEngine.Texture<FrooxEngine.Texture2DVariantDescriptor, CodeX.Texture2DVariantDescriptor, FrooxEngine.ITexture2DConnector, CodeX.BitmapMetadata, CodeX.Bitmap2D>+<LoadTargetVariant>d__37.MoveNext()
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(object stateMachine)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at void BaseX.WorkProcessor.ProcessQueue(ThreadWorker worker, ConcurrentQueue<Action> queue)
   at void BaseX.WorkProcessor.JobWorker(ThreadWorker worker)
   at BaseX.WorkProcessor+ThreadWorker(WorkProcessor processor, Worker worker, WorkType targetWorkType, ThreadPriority priority, int index)+() => { }
   at void System.Threading.ThreadHelper.ThreadStart_Context(object state)
   at void System.Threading.ThreadHelper.ThreadStart()
5:26:28 AM.460 (105 FPS)	Error decoding texture variant: Type: Texture2D, FilterMode: Anisotropic, Aniso: 8, WrapU: Clamp, WrapV: Clamp, WrapW: Repeat, MipMapBias: 0, Readable: False, Exact: True, Compression: BC3_LZMA, Quality: 100, Width: 2048, Height: 2048, Mipmaps: True, Filtering: Box, File: C:/Users/Epsilion/AppData/Local/Temp/Solirax/NeosVR\Cache\vby1o6ht2li87evt, URL: neosdb:///9dbc06a3ba56bba79b0fe6840d0bcd52c887850e269b5832071e342ccc529ca9
```

**Comment by shadowpanther** [comment]
[VIXEN - 2022.1.28.1310 - 2022-02-21 21_36_50.log](https://github.com/Neos-Metaverse/NeosPublic/files/8121147/VIXEN.-.2022.1.28.1310.-.2022-02-21.21_36_50.log)
Here's my log. Has both plain textures and cubemaps not loading:
![image](https://user-images.githubusercontent.com/675104/155244854-69c5629d-8a02-4b15-98e5-c9c18ec85ebe.png)

**Comment by Psychpsyo** [comment]
Just came here from #3620, this seems like it could be the same as #3574.

**Comment by kulzae** [comment]
Reflection probes failed to load again this morning
[DESKTOP-E2B6ON9 - 2022.1.28.1310 - 2022-02-23 09_57_48.log](https://github.com/Neos-Metaverse/NeosPublic/files/8125520/DESKTOP-E2B6ON9.-.2022.1.28.1310.-.2022-02-23.09_57_48.log)
g

**Comment by shiftyscales** [comment]
This should hopefully all be resolved. A script was run to clear out existing problematic variants, and they should be re-generated on loading the content again.
