### ISSUE TITLE
Opening SteamVR dashboard tanks performance

### ISSUE THREAD

**Issue by Nihlus** [Neos-Metaverse/NeosPublic#3640]
### Describe the bug?

When opening the SteamVR dashboard from inside NeosVR by pressing the System button on an HTC Vive controller, NeosVR's performance drops to the point of freezing the entire screen for seconds at a time. Input is near impossible, and closing the SteamVR dashboard is not possible.

NeosVR remains in this unusable state remains until it is forcibly closed, either via the system or via Steam.

### Relevant issues

I did not find any relevant issues.

### To Reproduce

1. Start SteamVR
2. Start NeosVR
3. Wait for the world to load in
4. Press the System button on the HTC Vive controller (labelled as 3 in the attached image) 
5. Observe that performance is severely degraded, and input is no longer possible
6. Observe that the dashboard can no longer be closed
7. Observe that NeosVR cannot be safely terminated

![image](https://user-images.githubusercontent.com/2340428/159977097-b82a1ae0-950a-49b8-b63b-53a91b5894ce.png)

### Expected behavior

NeosVR's performance should not be affected by opening SteamVR's dashboard, and should continue to run normally.

### Log Files

[Player.log](https://github.com/Neos-Metaverse/NeosPublic/files/8344082/Player.log)
[storburken - 2022.1.28.1335 - 2022-03-24 17_59_22.log](https://github.com/Neos-Metaverse/NeosPublic/files/8344083/storburken.-.2022.1.28.1335.-.2022-03-24.17_59_22.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

No

### Neos Version Number

2022.1.28.1335

### What Platforms does this occur on?

Linux

### Did this work before?

I Don't Know

### Additional context

System information:
[system.txt](https://github.com/Neos-Metaverse/NeosPublic/files/8344120/system.txt)

VR headset: HTC Vive

### Reporters

Jax#7487

**Comment by shiftyscales** [comment]
This isn't an issue that is experienced on Windows- and in fact, the opposite is usually true- SteamVR lowers the rendering resolution when the dashboard is open which can cause performance to increase, not decrease.

I saw from your system info that you're using a Linux Mint distro with a Cinnamon DE- by chance have you done any troubleshooting on your end?  A cursorary Google search has suggested that others running Mint have also had issues with SteamVR and performance.

I'd also be curious if the same issue occurs if you enable proton and used the Windows build.

**Comment by Nihlus** [comment]
I've tried the usual troubleshooting steps, but without much luck - I'll try the proton way tomorrow!

**Comment by Nihlus** [comment]
After testing with the Windows build via Proton (which worked fine, but performance in general was much worse), I went back to the Linux build to try again.... and the issue had magically fixed itself. I'll reopen the issue if I experience the problem again - thanks for the quick reply!

**Comment by Nihlus** [comment]
The issue has now returned, after running the native build a couple of times.
