### ISSUE TITLE
Share Browser WINDOW in-world

### ISSUE THREAD

**Issue by PR-Noyes** [Neos-Metaverse/NeosPublic#3644]
### Is your feature request related to a problem? Please describe.

Higher-Education use of Neos for Instruction.
If I can get Instructors to make their "learning material" accessible in a web browser, THEN I could get their presentation via Neos able to present by sharing that web browser window in-world. (not the whole desktop)

Please recognize this request as distinct form whole-desktop sharing. This request is to be able to set up multiple objects in an in-world classroom environment, each queued up with the display of an individual presenters-desktop-computer browser window, ready for presentation to attendees.

### Relevant issues

Screen sharing #144
This feature request here is not at all the same as #144.

### Describe the solution you'd like

In world, deploy a "monitor/screen/tv" object, and size it for presentation.
Edit the object to choose from computer desktop opened browser window(s). Select.
The in-world object (tv/monitor/display) displays that functional browser window on it's "screen".

er.

### Describe alternatives you've considered

Currently, Neos is only able to manage rtmp streams out of obs (for example) and this overhead of complexity prevents adoption by any but Neos enthusiasts, willing to solve how this is done.

I am not complaining. I am encouraging adoption of Neos for legitimate use implementation. Some instruction is ideal to take place in an MXR environment.

### Additional context

Attendees watch/witness a prepared presentation by the host, who can spawn numerous displays in-world, each prepped with the display of one of the host's desktop windows. In some cases the host clicks through (web pages) being discussed. In other cases the host clicks PLAY on a display displaying a YouTube Video (for example).

**Comment by sirkitree** [comment]
related: #142, 
possible duplicate: #60

**Comment by PR-Noyes** [comment]
No no no. This is not a duplicate.
(I was concerned that this would happen)
Please watch this short YouTube video to understand why this is not a duplicate.
(spun into timecode to save time and be specific) [https://youtu.be/8_mT7kHPnDs?t=26](https://youtu.be/8_mT7kHPnDs?t=26)

**Comment by ProbablePrime** [comment]
The feature shown is part of screen sharing. 

Therefore it is a duplicate. Thank you.

**Comment by PR-Noyes** [comment]
Screen sharing shows the entire screen.
I am searching for where I could see that "the feature shown is part of screen sharing".
I am desperately trying to not waste your valuable time.

**Comment by ProbablePrime** [comment]
We don't have details on that feature right now but from speaking about it to various team members we include all forms of screen sharing to be under that work item. Including this one. Duplicates aren't the end of the conversation they're included in our understandings of features.

**Comment by PR-Noyes** [comment]
Thank you for circling back, following up, and respectfully lending clarity to this.
Unfortunately this seems a log way off with other priorities.
Too bad, as it is an immediate need to identify a VR "open" platform that can, for higher education to take seriously this Spring.

**Comment by ProbablePrime** [comment]
That's unfourtunately just how our roadmap is right now. I'm sorry. You can keep up to date here: https://github.com/Neos-Metaverse/NeosPublic/projects/1
