### ISSUE TITLE
Neos webrequests for images do not send user agent.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3652]
### Is your feature request related to a problem? Please describe.

This is closely related to #525 which asked for the GET request node to send a user agent. This should be expanded to regular image requests for the same reasons. (And other media requests but I have not verified if those send the header.)

### Relevant issues

#525

### Describe the solution you'd like

When Neos loads an image (or anything else) the HTTP/S request should have the same User-Agent header that is currently used by the GET String logix node. ("Neos/2022.1.28.1310", for example.)

### Describe alternatives you've considered

Keeping it without but I do not see any reason to do that.

**Comment by epicEaston197** [comment]
and this is why this is not working lol
![image](https://github.com/Neos-Metaverse/NeosPublic/assets/76523692/ee66d9c8-37a4-4376-b114-7892649a557b)
