### ISSUE TITLE
Boolean Counter should be able to accept a single bool vector.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3673]
### Is your tweak request related to a problem? Please describe.

Currently there is no convenient way to count the number of true or false values in a bool2 or bool3.

### Describe what would you like tweaked

The Boolean Counter node seems to do exactly this but it only accepts a list of bool inputs. It should also accept a single bool2 or bool3.

### Describe alternatives you've considered

Unpacking the bool vector and summing all components after putting them through a 0-1 node.

**Comment by DoubleStyx** [comment]
Since book vectors are sometimes used for efficiently storing boolean values in cloud variables, perhaps the Boolean Counter should accept an arbitrary number of bool vectors of the same type. This would eliminate the need to unpack the bool vectors before counting them.
