### ISSUE TITLE
add UI unlit material to the NEOS guidelines button on the session rules panel

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3701]
### Is your tweak request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/76523692/178867233-7aa36090-2217-4df7-a775-48281a0214dc.png)
![image](https://user-images.githubusercontent.com/76523692/178880594-8c8d107c-0e45-4813-9eaa-c96c4edfc9c6.png)
![image](https://user-images.githubusercontent.com/76523692/178867462-d1b451dd-b848-4eeb-a97a-2c6d56beeeda.png)
![image](https://user-images.githubusercontent.com/76523692/178867467-44962045-6ae5-4339-b310-e9d37e49aeed.png)

### Describe what would you like tweaked

add a material to the background of the NEOS guidelines button
![image](https://user-images.githubusercontent.com/76523692/178867519-4c9bd8c7-cda2-483b-9890-1b9b3f12a525.png)

### Describe alternatives you've considered

adding it myself and saving it but this would not fix the panel by default inside of the essentials folder or MTC

**Comment by RaithSphere** [comment]
Hey [epicEaston197](https://github.com/epicEaston197)
I have looked into this and I am currently dealing with this now

**Comment by RaithSphere** [comment]
Okay this has been fixed in the MTC, Avatar MTC, Streaming MTC and NeosEssentials
![2022-07-14 21 55 21](https://user-images.githubusercontent.com/7329135/179094690-06c5b58a-d9c6-4874-a8df-c3d4a6b971cc.jpg)
