### ISSUE TITLE
Hand animation feature for Shadow PC

### ISSUE THREAD

**Issue by LuxytheLuxray** [Neos-Metaverse/NeosPublic#3707]
### Is your feature request related to a problem? Please describe.

So shadow PC and Plutosphere are unable to use hand animations in Neos due to a runtime issue, i would like to see if yall could work together to get something worked out so that we could.

### Relevant issues

No hand animation for Shadow PC

### Describe the solution you'd like

To be able to use hand animations

### Describe alternatives you've considered

there are none

**Comment by LexiBasilisk** [comment]
It sounds to me that they just aren't passing SteamVR skeletal input data. Other apps such as ALVR have implemented this properly on their end- and if they were using the skeletal data- it should just-work. This is something you will need to talk to their developers about.

**Comment by LexiBasilisk** [comment]
On another quick note- something you could possibly try on your end, is using the -LegacySteamVRInput command line argument.
> -LegacySteamVRInput - Force Legacy Steam VR Input Handling. Used as a work-around for some Steam VR devices that have a missing or bad hand skeletal model, such as Virtual Desktop used with the Oculus Quest.

https://wiki.neos.com/Command_Line_Arguments#Forcing_specific_hardware

**Comment by Lexevolution** [comment]
that launch option is required for those platforms otherwise the controllers are stuck in the ground.
