### ISSUE TITLE
OVR Toolkit kills tracking

### ISSUE THREAD

**Issue by GhostOfTheAshes** [Neos-Metaverse/NeosPublic#3712]
### Describe the bug?

when moving your hands over any OVR Toolkit windows Neos stops tracking your hands

### Relevant issues

unsure

### To Reproduce

open any OVR Toolkit windows and point your hand(s) at them

### Expected behavior

Neos continues tracking your hands when pointing at windows

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2022.1.28.1335

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

Ashes

**Comment by LexiBasilisk** [comment]
Hi, this is A setting in OVR toolkit you can disable.

> How to block input to games: ( > > EXPERIMENTAL < < )
> 
> This feature is currently experimental within SteamVR so expect issues, to enable it, follow these instructions:
> 1. Open SteamVR Settings.
> 2. In the bottom left, click 'Show' for 'Advanced Settings'.
> 3. Enter the 'Developer' tab.
> 4. Enable 'Enable global input from overlays (Experimental)'.
> 5. Enable the setting in OVR Toolkit! This can be found in 'Global Settings', 'Show advanced settings'.
> 6. Enjoy input blocking, and report bugs with it. (⊙‿⊙✿)

https://store.steampowered.com/news/app/1068820/view/1708492123045651130

But yeah- this is not a Neos issue- please feel free to post a reply if you need additional help figuring out how to prevent OVRToolkit from blocking your input.
