### ISSUE TITLE
"䨻龘䲜" looks blurry in game

### ISSUE THREAD

**Issue by KisaragiEffective** [Neos-Metaverse/NeosPublic#3718]
### Describe the bug?

The glyph looks blurry. The font is `StaticFont` (`neosdb:///c801b8d2522fb554678f17f4597158b1af3f9be3abd6ce35d5a3112a81e2bf39`, human-friendly: `Noto Sans`).

### Relevant issues

* Similar to #621, but not same character. #621 mentions about `う` (in unicode escape sequence: `\u3046`)

### To Reproduce

Type `䨻龘䲜` (in unicode escape sequence: `\u4a3b\u9f98\u4c9c`) somewhere (including UI)

### Expected behavior

Not being looks blurry.

### Log Files

[kisaragi-deb11 - 2022.1.28.1335 - 2022-08-02 06_25_51.log](https://github.com/Neos-Metaverse/NeosPublic/files/9237625/kisaragi-deb11.-.2022.1.28.1335.-.2022-08-02.06_25_51.log)

### Screenshots

![image](https://user-images.githubusercontent.com/48310258/182251482-4b58d031-6554-4504-87d2-de03e53fb515.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2022.1.28.1335

### What Platforms does this occur on?

Linux (using native build)

### Did this work before?

I Don't Know

### Reporters

* kokoa0429 (`U-kokoa0429`)
* kisaragi marine (`U-kisaragi-marine`)

**Comment by rassi0429** [comment]
The same problem occurs on Windows 10 (10.0.19044.1826).
![2022-08-02 06 59 37](https://user-images.githubusercontent.com/91118218/182253225-1efdc2a6-fc6d-47cd-b577-cf6f8f967333.jpg)

**Comment by Psychpsyo** [comment]
This is something that affects every character. It's just that most characters aren't detailed enough for it to be noticeable.
You can work around it by increasing the GlyphEmSize on the StaticFont component for the font.
Here's 䨻龘䲜 with it set to 64: (Note that higher values start to get laggy pretty fast.)
![image](https://user-images.githubusercontent.com/60073468/182399987-41e69483-2cf4-48e4-94ae-ead3274474f7.png)

**Comment by SnooperXP** [comment]
@Earthmark Would the changes you made on https://github.com/Neos-Metaverse/msdfgen/pull/1 work for this case?

Just double checking.
