### ISSUE TITLE
Feature: add "too many request" in Logix's `HttpStatusCode` input

### ISSUE THREAD

**Issue by KisaragiEffective** [Neos-Metaverse/NeosPublic#3719]
### Is your feature request related to a problem? Please describe.

I'd like to input `HttpStatusCode` statically, without `Int To Enum'1`.

### Relevant issues

None

### Describe the solution you'd like

Define custom enum and switch to it

### Describe alternatives you've considered

* Upgrade to .NET 5, and keep using native HttpStatusCode
This will be major update.

**Comment by ProbablePrime** [comment]
I'm not entirely sure, what this request is asking for, but I do see the gaps in our status code enum. I don't think breaking things out to be custom and away from the standard enum is suitable though.

This will most likely have to wait for .net as you say.

**Comment by KisaragiEffective** [comment]
There's an "too many request" (HTTP status code: 429) error, as defined in [RFC 6585](https://datatracker.ietf.org/doc/html/rfc6585). It has added since .NET 5 (or .NET Core 2.1).

There are also LogiX screen captures:
![image](https://user-images.githubusercontent.com/48310258/182478558-0ef36cfe-d396-44bf-9123-658ecba296e2.png)
![image](https://user-images.githubusercontent.com/48310258/182479784-005ed93a-6e20-49ec-8c29-0a727f057805.png)
