### ISSUE TITLE
the ability to hide nameplates on the streamer camera

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3724]
### Is your feature request related to a problem? Please describe.

I want the ability to hide name plates on the streamer camera

### Relevant issues

none I can think of

### Describe the solution you'd like

I would like there to be a extra button inside of the user tab on the streamer camera to hide nameplates

### Describe alternatives you've considered

go to your home menu and disable nameplates but this results in you not being able to see nameplates yourself

**Comment by ProbablePrime** [comment]
Hey, check the "Hide badges" checkbox on the streaming camera ui

**Comment by CoffeeKei** [comment]
I have just tested this and appears to be a bug. Nameplates are not being disabled by checking "Hide badges"

**Comment by ProbablePrime** [comment]
https://i.probableprime.co.uk/220806-OWEX2t5KuskAUUs8PnPc.mp4

Here's a recording showing how this checkbox works, I dont think its a bug?

**Comment by CoffeeKei** [comment]
aha! This is a different issue than what I originally thought. When I tested this, everyone in the world had a custom nameplate, The checkbox is working on default nameplates, but is not interacting with the visibility driver on custom nameplates.

Here's a video describing what I see in a bit more detail: https://youtu.be/OaROspAm5-U

**Comment by epicEaston197** [comment]
> 

I think it would be better to make a separate GitHub issue for this

**Comment by ProbablePrime** [comment]
Spinning this into its own issue, thanks for the work everyone.
