### ISSUE TITLE
Noise Gate & Normalization Thresholds in settings show too many digits of precision.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3728]
### Is your tweak request related to a problem? Please describe.

Currently the settings menu displays your noise gate threshold and normalization threshold with a ridiculous amount of precision. (like 10 or so digits)

### Describe what would you like tweaked

Make it display with only 2 or maybe 3 digits of precision. So instead of `2.918000318`, just show `2.92`.

### Describe alternatives you've considered

1. Keeping it like this. (why?)
2. Removing the number entirely. (bad)
3. Manually inspecting the dash and having everyone fix it themselves. (also awful)
4. Waiting for the UI rework. (that's the answer I'll get, isn't it?)

**Comment by XDelta** [comment]
Temporary fix that is effectively 2 points of precision that will change 0.02345678 into 2%.
You can update your primary locale file (`NeosVR\Locale\en.json`) to change the formatting a bit. This can be edited live without restarting Neos.
Locate the lines:
`"Settings.Audio.NoiseGateThreshold": "Noise Gate Threshold: {n}",`
`"Settings.Audio.NormzliationThreshold": "Normalization Threshold: {n}",`

replace them with: 
`"Settings.Audio.NoiseGateThreshold": "Noise Gate Threshold: {n,number,percent}",`
`"Settings.Audio.NormzliationThreshold": "Normalization Threshold: {n,number,percent}",`
