### ISSUE TITLE
Bone Manual-assignment for VRIK component on avatar creation

### ISSUE THREAD

**Issue by ModernBalloonie** [Neos-Metaverse/NeosPublic#3737]
### Is your feature request related to a problem? Please describe.

Sometimes when avatars don't have their finger bones named correctly, or there's a typo in any of the bone names, sometimes it's a pain to have to remake the avatar. I generally use the rig transfer tip for a lot of the stuff I do because I don't want to re-set up an entire avatar.

### Relevant issues

Not that i could find

### Describe the solution you'd like

Some sort of UI when creating an avatar kind of like Unity's humanoid rig assignment to assign certain bones manually so you don't need to rely on the Heuristics all the time (though you should name the bones right.). This could allow for re-initialization of the avatar rig in case you have your finger bones or something named wrong, or you made a typo and you can manually assign and fix it, not having to go back into blender and rename the bones, then re make the entire avatar.

### Describe alternatives you've considered

Remaking the entire avatar but that's really annoying when it comes to it.

**Comment by LexiBasilisk** [comment]
This is basically the same issue as #2826 and is also similar in scope to #3091.
