### ISSUE TITLE
MTC Avatar Public: Add Neoroid Creator2 in NeosAvatarPublic and set as a default

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#3743]
### Is your tweak request related to a problem? Please describe.

Plz see this tweet first.
https://twitter.com/lambdabase/status/1565468200451485697?t=25gZnXX02MgJVXoVNIH40g&s=19

In Japan, it is sensitive things for import an avatar from other games . anyone in japanese newbies thinks this character creation is iligal and also this game is iligaly content IF THIS GAME ISN'T ILIGAL.

"他のゲームのキャラクターを持ち込むことは一般的に法律に違反しているという認識です。たとえそれが厳密に精査した場合に合法でも、初心者にはこの違法なツールを使用して大丈夫なのかという不信感を与えてしまいます。"

And also, in current avatar world list doesn't exist Neoroid Creator 2.

### Describe what would you like tweaked

Add Avatar world list and set as a default, not to think iligal tool for Japanese newbies.

### Describe alternatives you've considered

Before world open, must long press and set a label "New world will open! Are you ok?".

For this problem, neos doesn't update at all due to current other problems include i18n.

**Comment by ProbablePrime** [comment]
As this is third party we can't really do much except potentially remove it from any official hubs/lists of avatars. 

Neos Essentials itself already had a re-work to remove similar avatars.

**Comment by kazu0617** [comment]
I chat after this reply and already will solve, but these chat is internally so reply from GitHub also.

As i said for MTC Avatar Public,not third party ones.
So i think can modify under neos itself.

**Comment by ProbablePrime** [comment]
We've updated the list in the MTC avatar lobby with some new worlds and removed Jazneo's world.

Thanks for the feedback.

**Comment by kazu0617** [comment]
I'm sorry but i checked just only "Neoroid creator" not "2".

Before this issue(deprecated, have to delete | MMC : NeoRoid Creator): neosrec:///U-orange/R-1f8165de-e12f-4905-accb-3260f947ee9b
Now added neoroid creator(Updated but version 1 | NeoRoid クリエイター): neosrec:///U-orange/R-9c8d2619-97fc-45d7-b251-64c778ead41e
As I said in issue(currently support, verison 2 | NeoRoid クリエイター 2): neosrec:///U-orange/R-a10c835b-8b59-4ea4-859c-936226bac693

**Comment by kazu0617** [comment]
![image](https://user-images.githubusercontent.com/6259214/188313362-484f0e43-7070-4c9d-be2c-a6f6d40991e8.png)

**Comment by ProbablePrime** [comment]
@AegisTheWolf Please update the urls as Kazu asks. Looks like we're using older versions of the worlds. 

Thanks Aegis.
