### ISSUE TITLE
Support Varjo Native SDK

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#3752]
### Is your feature request related to a problem? Please describe.

if use Varjo SDK, we can use neos it includes Varjo Native Features like; Mutiapp / XR function / better performance.

### Relevant issues

https://github.com/Neos-Metaverse/NeosPublic/issues/3226 eye tracking feature. soft relevent. This issue(#3752) is focused for rendering.

### Describe the solution you'd like

Support Varjo Native SDK as a launch option to use Varjo Headset natively.

Getting Started: https://developer.varjo.com/docs/get-started/get-started
SDK document: https://developer.varjo.com/docs/apidocs/index.html

If install Varjo Base and use analytics window, anyone can develop for Varjo Native SDK without HMD.

### Describe alternatives you've considered

nothing.

**Comment by Geenz** [comment]
Hey there!

This is already in the cards once things are moving again- I’ve already been familiarizing myself with the SDK since I got an Aero. I’ve also been helping to maintain the related eye tracking mod.

Will keep this one up to date once we’re moving again.

**Comment by EIA485** [comment]
this seems relevant: [dfgHiatus/NeosVarjoEyeTracking](https://github.com/dfgHiatus/NeosVarjoEyeTracking)
its a mod implementation of the Varjo Native SDK. due to its mit license t could potentially be up-streamed into neos its self.

**Comment by kazu0617** [comment]
> this seems relevant: [dfgHiatus/NeosVarjoEyeTracking](https://github.com/dfgHiatus/NeosVarjoEyeTracking) its a mod implementation of the Varjo Native SDK. due to its mit license t could potentially be up-streamed into neos its self.

I think soft relevent cuz' this issue focused for Native SDK for launching, like as "SteamVR" "RiftTouch" and "Varjo".
But yes, eye tracking is also require. https://github.com/Neos-Metaverse/NeosPublic/issues/3226

**Comment by Geenz** [comment]
> this seems relevant: [dfgHiatus/NeosVarjoEyeTracking](https://github.com/dfgHiatus/NeosVarjoEyeTracking) its a mod implementation of the Varjo Native SDK. due to its mit license t could potentially be up-streamed into neos its self.

That is the mod that I have been assisting with, yes.  The official implementation will be different, but not by much from what I've already contributed.

**Comment by kazu0617** [comment]
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/390
