### ISSUE TITLE
Lay Back Mode button

### ISSUE THREAD

**Issue by GearBell** [Neos-Metaverse/NeosPublic#3788]
### Is your feature request related to a problem? Please describe.

I know this sounds silly as hell but much like seated mode to accomidate those who are sitting and regulates your avatar to stand, what if we had a Laying Mode button on our dashboard that tilts your viewpoint 45 degrees forward, so when you are laying down you dont have to crane your neck?
Its not a huge issue. Just thought itd be harmless to throw that in the ring.

### Describe the solution you'd like

A dashboard button, similar to seated mode, that when you press it tilts your viewpoint forward by maybe 45 degrees so that people laying down dont crane thier necks to regulate thier view?
AKA "The Lazy Button"

### Describe alternatives you've considered

Yeah you can use logix but a button on the dashboard seems nicer.

**Comment by ModernBalloonie** [comment]
Kind of like horizon adjust in VRchat?

**Comment by Nytra** [comment]
Possibly related issue: https://github.com/Neos-Metaverse/NeosPublic/issues/225

**Comment by LexiBasilisk** [comment]
@GearBell This is describing "bed mode" #225, yeah. This was an issue that was previously blocked by Karel's worry about it 'promoting laziness'. Fortunately we don't give a fuck what Karel thinks anymore. :D

And yeah, pretty much exactly, @ModernBalloonie. I took note when they added that and was like "oh, they added 'bed mode'".

Marking this issue as a duplicate and closing. Subsequent discussion can be had on the bed mode issue.
