### ISSUE TITLE
DynamicBoneChain: Gravity only affects the first and last bones of the chain?

### ISSUE THREAD

**Issue by Hayden-Fluff** [Neos-Metaverse/NeosPublic#3801]
### Describe the bug?

so I'm trying to make a simple bone chain that reacts to gravity, though I seem to be having some issues in that no matter what I set the Gravity to in the DynamicBoneChain, only the first and last bones of the chain seems to be affected where all the rest essentially act as Gravity is set to [0,0,0].

The screenshots below show exactly what I'm seeing.

### Relevant issues

Could not find any

### To Reproduce

Create a DynamicBoneChain with more than 3 bones
set the Gravity to anything other than [0,0,0] (The higher the better)

### Expected behavior

The Gravity should apply to every bone in the chain, resulting in a natural curve towards the end of the chain following the Gravity direction.

### Log Files

*N/A*

### Screenshots

Gravity set to [0,-9.812,0] with a slight tilt
![image](https://user-images.githubusercontent.com/25524760/206821467-039143d6-908e-41ef-99ea-eb40e064a3ea.png)

Gravity set to [0,0,0] with same tilt as before
![image](https://user-images.githubusercontent.com/25524760/206821486-81d2a16b-d3dc-4cdf-9ac1-746fae93de2a.png)

Gravity set to [0,-9.612,0] with a 90 degree tilt
![image](https://user-images.githubusercontent.com/25524760/206821512-e8b00d98-dc2f-49ec-8a88-d80fc11740d1.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2022.1.28.1335

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Additional context

I'm quite sure that this has problem has existed since Dynamic Bones launched.

### Reporters

Hayden#3180

**Comment by LexiBasilisk** [comment]
See: #2141
