### ISSUE TITLE
Support Avif format

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#3813]
### Is your feature request related to a problem? Please describe.

Neos doesn't correctly support avif format for client & server side right now, so we cannot check avif photo/image in neos.

### Describe the solution you'd like

Support avif format for Camera or converting somewhere cuz' avif is much more reduce size between webp.

Avif: https://aomediacodec.github.io/av1-avif/
LibAvif: https://github.com/AOMediaCodec/libavif

### Describe alternatives you've considered

This issue is open for a completely new format. Therefore, there is no substitute.

**Comment by LexiBasilisk** [comment]
I'd be curious for @Geenz's input on this, but at the very least I'd imagine we would need to ensure compatibility with the crunch compression libraries we use for asset variant generation. I also don't know if our current Unity rendering pipeline can even support the decoding and display of this format as-is, so it might additionally be blocked/delayed by needing to make and implement the custom rendering engine, or adding a library specifically for the decoding/display of it, which sounds potentially messy just to add support for what seems to me at present, a fairly niche file format in the present day.

**Comment by LexiBasilisk** [comment]
In talking with Geenz about this and briefly investigating, it sounds that it is not currently supported in dependencies we use like FreeImage. Marking this as "waiting on 3rd party".

**Comment by kazu0617** [comment]
Thank you, I have heard that FreeImage can be supported by add-ons, so I will expand the information related to that. I hope you will find it useful.

AVIF Forum Page: https://sourceforge.net/p/freeimage/patches/137/
FreeImage-Sidecar(LGPL License | FreeImage Addon that compatible with avif / heif ): https://github.com/mnaydenov/FreeImage-Sidecar 

Also, it has already been 4~5 years since FreeImage stopped updating. As discussed in this thread, you may want to plan a long term plan (a plan to be implemented within 2-3 years) to migrate to OpenImageIO for better maintainability.
OpenImageIO(BSD3 License): https://github.com/OpenImageIO/oiio
FreeImage Forum: https://sourceforge.net/p/freeimage/discussion/36109/thread/1d36bd35/

**Comment by kazu0617** [comment]
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/880
