### ISSUE TITLE
Can't read Group's Value of a Group Cloud Variable through the Neos Bot.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3834]
### Describe the bug?

Sending  ``/getGroupVarValue G-Group-Name variableName G-Group-Name`` to the Neos bot results in ``Target user doesn't exist``.

### Relevant issues

Couldn't find any.

### To Reproduce

1. Create a group cloud variable. (this example uses one of type ``int``, called ``variableName``)
2. Set the group's value for it by sending something like ``/setGroupVarValue G-Group-Name variableName 123`` to the Neos bot.
3. Send ``/getGroupVarValue G-Group-Name variableName G-Group-Name`` to the Neos bot the read the value back.
4. Observe ``Target user doesn't exist``.

### Expected behavior

The bot should respond with the variable's value.
In the example case above, that'd be ``123`` instead of ``Target user doesn't exist``.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2022.1.28.1310

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

Cameron#7818

**Comment by Nytra** [comment]
I think the syntax should be `/getGroupVarValue <group> <path> (<target user>)` as per the wiki https://wiki.neosvr.com/Cloud_Variables#Cloud_Variable_Commands.
