### ISSUE TITLE
pasting YouTube videos no longer work/update YouTube DL

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3846]
### Describe the bug?

when I paste a YouTube link the video player never loads

### Relevant issues

didn't find any

### To Reproduce

copying YouTube link from any video and attempt to paste it the video player will never load

### Expected behavior

I should be able to view the YouTube content on the video player without issues

### Screenshots

![image](https://user-images.githubusercontent.com/76523692/219684068-95c99036-1ed1-4486-9c77-0d0eaf27862c.png)
![image](https://user-images.githubusercontent.com/76523692/219684079-b38a1f96-c9c9-4d1b-bbf6-271cc523a02c.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2022.1.28.1335

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

2022.1.28.1335

### Reporters

@epicEaston197 and others

**Comment by stiefeljackal** [comment]
[DESKTOP-PNID9H1 - 2022.1.28.1310 - 2023-02-17 09_40_02.log](https://github.com/Neos-Metaverse/NeosPublic/files/10767861/DESKTOP-PNID9H1.-.2022.1.28.1310.-.2023-02-17.09_40_02.log)

Here is a log file to prove that this is not working to assist on this matter. It seems like `youtube-dl` is getting a null response back from YouTube. Perhaps there was a recent change to YouTube's API?

**Comment by epicEaston197** [comment]
> [DESKTOP-PNID9H1 - 2022.1.28.1310 - 2023-02-17 09_40_02.log](https://github.com/Neos-Metaverse/NeosPublic/files/10767861/DESKTOP-PNID9H1.-.2022.1.28.1310.-.2023-02-17.09_40_02.log)
> 
> Here is a log file to prove that this is not working to assist on this matter. It seems like `youtube-dl` is getting a null response back from YouTube. Perhaps there was a recent change to YouTube's API?

I heard that YouTube added @ handles and it just doesn't know how to respond 

this might be our best solution
because this would allow everybody to see the YouTube video you paste
https://github.com/art0007i/PasteInvidious/releases/tag/2.0.1

**Comment by Geenz** [comment]
YouTube likely changed their APIs that broke the version of yt-dlp that we currently use.  The current release version of yt-dlp *should* fix this - and in order to test that, you can either open a command prompt in `path\to\Neos\RuntimeData`, then run `yt-dlp.exe -U`

Or, you can download the latest version of yt-dlp here: https://github.com/yt-dlp/yt-dlp/releases - you only need yt-dlp.exe.  From there you can just replace it in the above mentioned RuntimeData directory.

**Comment by epicEaston197** [comment]
> YouTube likely changed their APIs that broke the version of yt-dlp that we currently use. The current release version of yt-dlp _should_ fix this - and in order to test that, you can either open a command prompt in `path\to\Neos\RuntimeData`, then run `yt-dlp.exe -U`
> 
> Alternatively, you can download the latest version of yt-dlp here: https://github.com/yt-dlp/yt-dlp/releases - you only need yt-dlp.exe. From there you can just replace it in the above mentioned RuntimeData directory.

thanks it was instantly fixed
![image](https://user-images.githubusercontent.com/76523692/219687788-817d745a-ad28-4cd3-9cde-c6f5e7d5f60d.png)

**Comment by dfgHiatus** [comment]
Dropping this here for reference: https://github.com/dfgHiatus/YoutubeDL-Updater

**Comment by ProbablePrime** [comment]
resolved
