### ISSUE TITLE
ValueGradientDriver<int> adds numbers instead of interpolating between them

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3850]
### Describe the bug?

When using a ValueGradientDriver of type int, it adds a percentage of the target number to the source number instead of interpolating between them.

### Relevant issues

Didn't find any.

### To Reproduce

1. Make a ``ValueGradientDriver<int>``.
2. Make it interpolate from 100 at position 0 to 200 at position 1.
3. Set it to anywhere between.
4. Observe the wrong number.

### Expected behavior

It should interpolate between x and y, not x and x+y.

### Screenshots

![image](https://user-images.githubusercontent.com/60073468/221403518-73034626-639f-436c-bd2c-89f24383a468.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2022.1.28.1310

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

Cameron#7818

**Comment by epicEaston197** [comment]
yes this is a known issue

**Comment by Psychpsyo** [comment]
> yes this is a known issue

Well, no one's made an issue about it before.

**Comment by bontebok** [comment]
> Well, no one's made an issue about it before.

Thanks for submitting it, because now I know as well and I can avoid scenarios using it :)

**Comment by epicEaston197** [comment]
> > Well, no one's made an issue about it before.
> 
> Thanks for submitting it, because now I know as well and I can avoid scenarios using it :)

wait what I'm surprised there isn't an issue about this before this has been a issue and it has been reported multiple times lol
