### ISSUE TITLE
Add isSnapped boolean to Snapper component

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3854]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I need to know if a Snapper is actually snapped to a SnapTarget because it does not have a way to read that.

### Relevant issues

Didn't find any.

### Describe the solution you'd like

Add an ``isSnapped`` boolean to the Snapper component.
(A ``hasSnapper`` on the SnapTarget could also be neat but isn't all that necessary.)

### Describe alternatives you've considered

I can't think of an easy way to achieve this functionality.

**Comment by Beaned2000** [comment]
while a native solution would be nice to have, checking children count or using children events on the snaptarget could serve as an easy solution right now.
alternatively if you're familiar with Dynvars you can put a dynspace on the snaptarget and put a DynamicValueVariable of type bool onto it and make it true, then put a DynamicValueDriver of type bool onto the snapper and that should drive the snapperstate too

**Comment by Psychpsyo** [comment]
> alternatively if you're familiar with Dynvars you can put a dynspace on the snaptarget and put a DynamicValueVariable of type bool onto it and make it true, then put a DynamicValueDriver of type bool onto the snapper and that should drive the snapperstate too

Alternatively, Dynvars are absolutely overkill here and this is what ParentValue and ParentValueLink are for.
