### ISSUE TITLE
Option to disable physical touch on world orbs

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3855]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when accidently physical touching a world orb and going there, especially in desktop mode.

### Relevant issues

Didn't find any.

### Describe the solution you'd like

Add a boolean for toggling physical touch to the WorldOrb component, similar to what other button-like components have.

### Describe alternatives you've considered

1. Not doing this. (Why?)
2. Getting rid of my tip touch sources. (Would solve it for me but not others.)

### Additional context

I am making a custom item that acts as a world orb so this level of control would be really nice, given that a world orb is the only way to get the world-opening options context menu to show up.

**Comment by epicEaston197** [comment]
the thing is World orbs have been a thing in Neos for a long time and they are due for an overhaul / rework I think this would enable for the world orbs to act more like button components and you will be able to trigger different Behavior depending on what type of interaction you do to the world orb
