### ISSUE TITLE
make the world categories scrollable in the world's tab

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3856]
### Is your tweak request related to a problem? Please describe.

in neos we are encouraged to edit our Dash but if a user wants a lot of category tabs for the World Browser it will end up looking like the image below I basically want the buttons to stay at the same size and for the extra buttons to be scrollable
![image](https://user-images.githubusercontent.com/76523692/223176292-8e97f7cb-9731-4325-ab38-850e2831029c.png)

### Describe what would you like tweaked

for World categories to be scrollable 

### Describe alternatives you've considered

modifying the fast that yourself

**Comment by Beaned2000** [comment]
For the current UI the scroll function is not necessary therefore i don't see the point of having one. Like you said we as neos users are able to customize our menu's ourselves so i don't see why you couldn't just add the scroll yourself to suit your personal needs or ask someone to do it for you.

Here is a useful link to tutorials on how to work with UIX, in part 3 scrolling is explained so you should be able to pick this up fairly easily: https://www.youtube.com/watch?v=cLtD7uWrduI&list=PLxAzjHbHvNcUZwKOyR9A18JOnqKI4wBWc
