### ISSUE TITLE
Neos Cloud experiencing multiple issues

### ISSUE THREAD

**Issue by Lexevolution** [Neos-Metaverse/NeosPublic#3872]
### Describe the bug?

Currently there are multiple issues with the Neos Cloud. These include:
- The `api.neos.com` endpoint experiencing SSL errors.
  - This affects most ~headlesses~ and all Linux native users, as they never received a fix for this. (Headless has now been updated)
- The newer `CloudX.Shared.dll` which switches the api url to `cloudx.azurewebsites.net` that was supposed to fix the previous issue causes some functionality to be missing
  - This includes session thumbnails ~not being submitted~ Later determined to be a mis-formatted url, which cannot be read
  - ~Non-cached assets never loading~ Later determined to be specifically neosdb videos not loading

### Relevant issues

None that I could find

### To Reproduce

Launch Neos

### Expected behavior

Cloud based actions to work normally.

### Log Files

Old `CloudX.Shared.dll` (at line 173)
[LEXDESKTOP - 2022.1.28.1310 - 2023-04-02 18_01_19.log](https://github.com/Neos-Metaverse/NeosPublic/files/11131580/LEXDESKTOP.-.2022.1.28.1310.-.2023-04-02.18_01_19.log)

New `CloudX.Shared.dll`
[LEXDESKTOP - 2022.1.28.1310 - 2023-04-02 18_08_24.log](https://github.com/Neos-Metaverse/NeosPublic/files/11131593/LEXDESKTOP.-.2022.1.28.1310.-.2023-04-02.18_08_24.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2022.1.28.1310 and 2022.1.28.1335

### What Platforms does this occur on?

Windows, Linux

### Did this work before?

Yes

### If it worked before, on which build?

2022.1.28.1310 and 2022.1.28.1335

### Reporters

Lexevo#0876

**Comment by epicEaston197** [comment]
yell at Karel to fix it

**Comment by stiefeljackal** [comment]
The endpoint constant string variable is missing that trailing slash when the constant string variable is combined with the other part of the URL. I compared the new DLL with the old DLL and can confirm that. For videos.... unknown; it must be on the server-side.

**Comment by Lexevolution** [comment]
ok so here's what looks like is happening:
- the `*.neos.com` domain is not being used anymore in the Neos client, and instead being directly routed towards the direct azure servers.
- Some of these are currently non-functional (`https://cloudx-video.azureedge.net/`)
- Specifically the steam build of Neos contains a misformatted url in the cloudx.dll

I wish some of this was better communicated from the team.

**Comment by iamgreaser** [comment]
So, when are you pushing the fix for the Linux client for those of us who have to grab it from Steam?

**Comment by kazu0617** [comment]
This issue will fix with rollback from this hotfix to old one maybe, few days later.

**Comment by bontebok** [comment]
> So, when are you pushing the fix for the Linux client for those of us who have to grab it from Steam?

You can safely copy the CloudX.Shared.dll file from a Windows or the Linux Headless version over to your Linux client and it should work.

**Comment by iamgreaser** [comment]
Alright. Can someone upload that file to this issue tracker? I literally cannot use Discord.

**Comment by Lexevolution** [comment]
> Can someone upload that file to this issue tracker?

GitHub doesn't support uploading dll's in comments, but here's a link for a download from my server. DL at your own risk:
[Link removed]

**Comment by iamgreaser** [comment]
Thank you. The DLL works well enough for me to automatically log in and see sessions in the worlds tab.

**Comment by Lexevolution** [comment]
Just finished making a mod which "fixes" the thumbnail and video issues: https://github.com/Lexevolution/Cloud-Change

**Comment by Lexevolution** [comment]
A Neos update was just released which should fix the thumbnail and video issue, but linux native build still did not get this update, so this issue still applies.

**Comment by Lexevolution** [comment]
Another update has been pushed to the cloud, which fixes the old urls, and negates the need for this at all. It would've been nice for better communication from the team (not even a single comment on an issue that completely made Neos unusable for everyone for a short period, and for a subset of users for over a month is appaling IMO) but since this has been mostly fixed (the standalone still hasn't been reverted to the old urls yet), this issue can be closed.

**Comment by kazu0617** [comment]
It is already resolved in latest version, so now not need to remain this issue here. I close it.
少なくとも最新版では既に挙動はすべて修正されているため、Issueとして残しておく必要はないと考えます。Closeします。
