### ISSUE TITLE
Repository in GitHub how remove it comments 

### ISSUE THREAD

**Issue by ghost** [Neos-Metaverse/NeosPublic#3881]

**Comment by kazu0617** [comment]
I think each users get video from each own yt-dlp, so if you set maxsize for VideoTextureProvider, you can set lower resolution to set `maxSize`.
this solution is mid out-of-forcus, but you can set this solution currently.

**Comment by ghost** [comment]
.

**Comment by ghost** [comment]
how do i delete my Repository in GitHub how remove it comments in here so its not on my list on neosVR

**Comment by kazu0617** [comment]
@ghost due to limitations about github, you cannot destroy this issue. Just close it.
