### ISSUE TITLE
Finger photo haptic feedback

### ISSUE THREAD

**Issue by mpmxyz** [Neos-Metaverse/NeosPublic#3885]
### Is your feature request related to a problem? Please describe.

Learning how to do finger photo can be quite challenging and when switching avatars it can quickly feel completely different.
Usually you are not very much off, slightly skim over the initial range of hand positions and then you are lost trying to find the right spot again.

### Describe the solution you'd like

The experience can be improved by giving the user haptic feedback via the controllers.
There are multiple ideas:
-increase intensity the closer you are to the optimum position
-constant intensity but increase frequency/duty cycle the closer you are to the optimum
-maximum intensity around the "edge"

Individual feedback per hand would also be welcome.

### Describe alternatives you've considered

Visual indicators or sounds would also be possible but can be combined with the suggested solution.

**Comment by LexiBasilisk** [comment]
I don't think this is a good approach. I've had Index controllers that have their tracking jitter while the haptics were being pulsed causing the controller to shake wildly (this nearly made Half-Life: Alyx unplayable for me until I disabled haptics at the SteamVR level).

As such I believe it would interfere with attempts to take the photo/the framing of the photo.

I think a better solution is to rework the gesture/increase those thresholds, e.g. as per #1179.

If there is to be an indicator, my recommendation would be that it be a visual one.

Thank you for the feedback.
