### ISSUE TITLE
Neos Standalone will not download

### ISSUE THREAD

**Issue by Lexevolution** [Neos-Metaverse/NeosPublic#3890]
### Describe the bug?

Whenever I try and download Neos from a fresh standalone install, it will crash and none of the Neos files will appear.

### Relevant issues

N/A

### To Reproduce

Setup a fresh installation of the standalone Neos launcher, and run

### Expected behavior

For the update files to download, and it not to crash.

### Log Files

N/A

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

N/A

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### Additional context

This is likely due to https://assets.neos.com/install/Pro/Data/2022.1.28.1310_SSL_YTDLP.7z not existing.

### Reporters

Lexevo#0876

**Comment by Xlinka** [comment]
just had this issue as I wanted to use the standalone crashes on downloading due to non existent asset

**Comment by kazu0617** [comment]
This issue now fixed. the fixed version `2022.1.28.1310_YTDLP` is now released.
