### ISSUE TITLE
LocalAudioDeviceStream is downmixed

### ISSUE THREAD

**Issue by troyBORG** [Neos-Metaverse/NeosPublic#3898]
### Is your tweak request related to a problem? Please describe.

Audio for this is downmixed to mono, would like Independent channel control

### Describe what would you like tweaked

I would like to have to ability with this to choose either left, or right audio channels,

### Describe alternatives you've considered

I tried moving a slot near my left and right ears thinking it might give me different values

### Additional context

I'm using this to detect when people talk and using the volume to drive a gradient driver to make my ears perk up when I hear people talk near me.

**Comment by LexiBasilisk** [comment]
This is a duplicate of #421.
