### ISSUE TITLE
Eyes desynchronised on SteamVR Linux stable/beta

### ISSUE THREAD

**Issue by purplebar0** [Neos-Metaverse/NeosPublic#3921]
### Describe the bug?

Playing Neos on Linux, natively or under Proton 5.13-6 (or any other Proton version), moving the head around reveals that eyes are desynchronised and movement of one eye is delayed compared to the other.

This is not the case with SteamVR 1.14, however under the current stable and beta versions of SteamVR it makes the game unplayable.

### Relevant issues

N/A

### To Reproduce

1. Play SteamVR out of the box or choose beta "beta"
2. Launch Neos

### Expected behavior

The eyes move at the same rate and don't create the distracting effect.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2022.1.28.1335

### What Platforms does this occur on?

Linux

### Did this work before?

I Don't Know

**Comment by LexiBasilisk** [comment]
@purplebar0 Do you have any footage depicting the issue? When you say it is delayed, do you mean positionally?

That may be #1563 / #2334 which are basically describing what sounds to be the same issue.

How certain are you about platform specificity? Have you also tried replicating this under Windows?

**Comment by purplebar0** [comment]
Update: With a bit more testing, I concluded that this is an issue in some, but not all games -- SteamVR Home, Neos and King Kaiju had the issue, but not The Lab. It is clearly a SteamVR Linux issue in newer versions, it may not be worth fixing...

Here's footage, although I don't think the issue is demonstrated well in VR view:
https://github.com/Neos-Metaverse/NeosPublic/assets/107264962/613aa2b2-83bb-4c00-9b32-902c0c10773b

To be more specific, it appears to be a reprojection issue, one eye lags in a stuttery way behind the other. It's inconsistent and appears to only happen in some rotations.

I have not tested this on Windows and I don't have a Windows installation to test on, but it's safe to assume this is SteamVR Linux-specific because it's a known issue: https://github.com/ValveSoftware/SteamVR-for-Linux/issues/395 (I wrongly assumed that unsetting `cap_sys_nice` as per https://github.com/ValveSoftware/steamvr-for-linux/issues/576 fixed the stuttery reprojection).

**Comment by LexiBasilisk** [comment]
I don't think there's anything we can do on our end regarding this then- from what you're reporting, it sounds as though this is more of an issue with the compositor/VR runtime?

**Comment by purplebar0** [comment]
> I don't think there's anything we can do on our end regarding this then- from what you're reporting, it sounds as though this is more of an issue with the compositor/VR runtime?

Appears so; I doubt there's anything to do in regards to Neos about this, so I'm closing the issue.
