### ISSUE TITLE
[Logix Web Request] Have whitelist include port as well

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#620]
With my local machine I bind multiple ports on localhost but would like Neos to only be able to access the specific ports I whitelist. In my case I host multiple servers on localhost, but would prefer logix be able to send requests to ports I specifically whitelist as well as hosts.
Instead of whitelisting the whole host, can the whitelist apply to a specific host:port combo (defaulting to the defaults for the protocol if not defined)?

**Comment by Frooxius** [comment]
Hmm, what would be the reason for this? If you're allowing certain host, then you already trust that host. I don't see much of a scenario where certain ports would be trusted and some others wouldn't be.

**Comment by Earthmark** [comment]
Because I make a local webserver as a neos utility service I whitelist localhost, but I've got other services running that I'd rather not give access to. I get that in general ports are pretty open, but on specifically localhost I'd rather people not give access to every port on my machine.

**Comment by Earthmark** [comment]
So I guess in a way this isn't so much me trusting a host, as me trusting the other players in the world to respect the hosts I trust.

**Comment by mralext20** [comment]
alternative idea: allow once option on host access requests from HTTP GET/POST nodes. 

would allow one to trust specific hosts when they want to trust that host.

the Request Host Access node could still request permant allow explicitly.

**Comment by Earthmark** [comment]
The problem here is there is some ports on localhost I want to have constant access to, but I don't want all ports to have constant access.

Arguably saying the whitelist is a pattern that includes route may be good as well, as whitelisting services like cloud function or hosting services may end up whitelisting way more than you bargained for.

**Comment by ProbablePrime** [comment]
`- Host access now requires requesting access for each individual port to avoid security vulnerabilities like port scanning (based on report by @FRICK/フリック, Moderation Ticket #823623)`

We'll likely update the update notes to include this issue shortly. 

Thanks for your report :)
