### ISSUE TITLE
Avatar creator rotates on grabbing in headless

### ISSUE THREAD

**Issue by Beaned2000** [Neos-Metaverse/NeosPublic#651]
Every time the avatar creator is let go from grabbing it, it rotates a bit.
This issue seems to only happen in headless servers.
![AvCreatorissue](https://user-images.githubusercontent.com/29598202/83880618-b3d3c580-a73f-11ea-8f06-4f6e16a672f9.gif)

**Comment by shiftyscales** [comment]
This issue will be resolved by reworking the drive release mechanism as per #1270. Closing this issue to merge it into that one.
