### ISSUE TITLE
[Bug] Playback Nodes Don't Update on Headless

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Neos-Metaverse/NeosPublic#674]
While me and @Coffee-Maker were working on the Playlist, we noticed that any of the nodes that get playback data (in example, IsPlaying, PlaybackState, NormalizedPosition, etc.) Don't update for headless, and therefore don't return any information about the given clip.
This subsequently breaks systems that rely on these nodes such as the Playlist.

**Comment by Frooxius** [comment]
Are you using those with multimedia/video playback? Headless doesn't support video playback, so the Playback nodes won't provide correct information on it.

**Comment by shiftyscales** [comment]
Closing this issue due to lack of response, and the addition of a new issue (#2660) with a modern template.
