### ISSUE TITLE
Lasers not grabbing anymore for periods of time

### ISSUE THREAD

**Issue by GearBell** [Neos-Metaverse/NeosPublic#806]
lasers would stop grabbing for long periods of time until i switch to a new avatar. not sure if its related to the grabbing-clips-to-hand issue.

**Comment by shiftyscales** [comment]
Do you have any logs in which this has happened, and/or any way to replicate this behavior reliably? Is it just one specific avatar that's having that issue, or have other avatars/other users also been experiencing this issue?

**Comment by GearBell** [comment]
ill make a new log of it but its happened to all my avatars so far, and they each have different hand setups. not sure if "not grabbing by laser" will show up in logs though....

**Comment by H3BO3** [comment]
@GearBell Do you think this was a result of bad dynbone collider sizes? If so this issue could probably be closed since #845 was fixed.
