### ISSUE TITLE
Please make System.Type accessable through first level generics... preferably ValueUserOverride

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#870]
Currently I'm seemingly unable to populate a generic with only System.Type, I have yet to try fully qualified but I thought the core system library was accessible (like how System.Int32 is). Some nodes produce System.Type, such as standard controller, however without a way to store that string (or in my case do a user value override so the StandardController node and have yet to get either flavor of override to work, my own hackery or not I'm sure there's a normally supported reason to want this type in a generic for a ValueUserOverride or a data value field).

This came up when trying to detect what controller a user has to differentiate VC1 and normal quest controllers (I'm fairly sure using the type is a dead end, but this came up during the investigation).

**Comment by Frooxius** [comment]
I'm sorry, but this is not possible. You can't use just any type even from the system library as generics, because there are additional constraints on which ones can be used, since they need to be supported by Neos' data primitive coding and serialization functions. 

The System.Type is a complex type that cannot be supported directly by those coding and serialization functions, because it need to utilize the per-world type serialization/negotiation system, which maintains a list of supported types in the particular world. 

There is a specific field SyncType that handles this. I could make UserTypeOverride variant of the component for this purpose if it would help.

For specifically differentiating Touch controller model, I could expose the model in the node. They both use the same type, but there's a special field that indicates which model of the controller it is.

**Comment by Earthmark** [comment]
I'm curious first, what could I do with the type I get back from standard controller?

**Comment by Frooxius** [comment]
You check if it equals either CV1 or QuestAndRiftS (it's an enum).

**Comment by Earthmark** [comment]
I mean the type field right now, what can I do with System.Type in logix? Right now the controller type field is returning System.Type, I'm trying to understand what use case is supported by returning Type instead of an enum

**Comment by Frooxius** [comment]
Ah misunderstood sorry. There's no enum for the controller type. Each controller has a type class responsible for interfacing with the controller. That's what the node returns. You can only do equality comparison on it right now and not much else.

**Comment by Earthmark** [comment]
Can an enum be added? If the only thing I can do with the field is compare for equality that would be more helpful to be given the range of values the controller type can be.

Right now it's a guessing game that's very easy to get wrong, it would be very nice usability wise if I could be given the different values in some way. Currently I have to either wait for users using that controller type to join so I can get the ToString name, or skim the FrooxEngine dll for similar names and record them. Even if the enum grows over time I think that's fine, the work needed logix wise is the same, just now you are told what the new controller is.

Would that be a viable change? I do get that it's a breaking one and should be taken carefully. I know it's stretching the goal of this bug, but this bug started because an instance if System.Type was returned and it was difficult to use. If System.Type was not returned, it would similarly resolve the issue as the problematic value space no longer exists in the problem.

**Comment by sauermon** [comment]
Talking specifically on the type field for the standard controller type output, what if the type was instead a new enum type "ControllerType" or some derivative, which can be enumerated upon? This would only be specific to the type field on the standard controller. This is similar to the touch controller node, given how the model output is an enum type.

**Comment by chemicalcrux** [comment]
Did today's update help with any of the problems raised here? I'm a little unclear on what the issue was.

> - Added TypeField (under Data), which stores a Type (similar to ValueField and ReferenceField)
>   - It's highly recommended to use this as basis for any type comparisons, as in case of types being renamed or moved, it can be auto-upgraded
> - Added Type Input LogiX node, for Type values
>   - If you're checking and matching Type of an object (e.g. the ViewTargettingController), it's STRONGLY recommended to use GetType and compare that to the value you set on Input LogiX node. If you compare the string instead, it's likely that your content WILL BREAK and without ability to automatically fix it. Using Type Input node or TypeField lets us upgrade old types in case of internal changes

**Comment by Earthmark** [comment]
Yeah, this would make the original issue resolved. I'll verify later today (or tomorrow). If the concern is resolved I'll close the issue.
