### ISSUE TITLE
Adding support for proximity sensors.

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#897]
Certain Headsets have the availability to utilize the proximity sensor.

Feature: Make the sensor readable.
Could be used to turn avatar into away state or similar to reduce impact when user is not active but still online.

Headsets (AFAIK):
Valve Index, All Vive Headsets, aswell as most oculus Headsets

**Comment by Frooxius** [comment]
This is planned, but there's not much of an incentive or use for it right now. Turning the user into away state right away might introduce some weirdness. 

There's not really much impact that can be reduced by just turning the user into away state, other than just indicating to others that the user is away.

**Comment by shiftyscales** [comment]
I believe the initial request was also in the context of exposing the away state to Logix for custom away effects @Frooxius.

**Comment by Hayden-da-Serg** [comment]
That's also how I saw it, and I would love to have that in Logix, I think it'd also be neat to expose a user's IPD setting

**Comment by H3BO3** [comment]
yeah, this would be something open-ended, people would process the value as they pleased. The away effect was just an example of something it could be used for
