### ISSUE TITLE
Vive Controller trigger_hair not bound in SteamVR be default

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Neos-Metaverse/NeosPublic#898]
While messing with the SteamVR bindings for Vive controllers I found that the trigger_hair input is not bound to anything, as a result of this the Trigger Hair output on the Vive Controller node does not function, this can be fixed in the user's end by binding trigger_hair to a Button click on the Trigger, but should be in the default bindings.

**Comment by Frooxius** [comment]
Can you send me your customized binding file please? That'll make it quicker for me to add the binding to the default one.

**Comment by Hayden-da-Serg** [comment]
https://cdn.discordapp.com/attachments/459700241948737537/744163131621638215/steam.app.740250_vive_controller.json
This should be it
(Had to upload to Discord as GitHub for some reason doesn't support json files)

**Comment by Frooxius** [comment]
Thanks! This doesn't seem to be quite correct though, the trigger hair is just mapped the same as trigger click in this. Normally trigger hair should activate at the slightest press of it. I'm actually not sure if it's still supported directly, as this comes from the old Input API.

**Comment by Hayden-da-Serg** [comment]
Huh, it works like that on my end through my binding file, not entirely sure what all changed.

**Comment by TehTurk** [comment]
Going to close this as it seems to be a configuration issue.
