### ISSUE TITLE
Undo entries from the Create Field Undo Step node don't undo changes

### ISSUE THREAD

**Issue by Zyzyl** [Neos-Metaverse/NeosPublic#914]
Tested specifically with a ValueField<int> and changing the tint colour of a material. The undo entries created, either using just the node in isolation or wrapped intoan undo batch, do not revert the referenced value when the undo button is pressed on the radial menu.

**Comment by Frooxius** [comment]
This is odd. What does your setup look like?

**Comment by Zyzyl** [comment]
![2020-08-20 19 16 27](https://user-images.githubusercontent.com/66165438/90822212-02026900-e32c-11ea-8575-aa88c6c286f2.jpg)

**Comment by Frooxius** [comment]
Thanks! I think I know what's the issue, will fix.
