### ISSUE TITLE
Favorite keyboards not working

### ISSUE THREAD

**Issue by Zyro1331** [Neos-Metaverse/NeosPublic#917]
I've applied a custom keyboard, however clicking the pink heart does nothing. It highlights the item but does nothing, it still shows the little default keyboard.

**Comment by Frooxius** [comment]
Where is the keyboard you're trying to favorite located? By highlighting the item, does it change to purple? What if you restart Neos?

**Comment by mralext20** [comment]
Is the keyboard in a public folder?

**Comment by Zyro1331** [comment]
I have it saved into my inventory, I grabbed it from someone, customized it and saved it into my own folder. It does change to purple, but still no keyboard. Same with restarting neos, keyboard is still default.

**Comment by TehTurk** [comment]
I'm going to close this as for currently, favorited items need to wait to sync, at least in the case of keyboards. I know there's the issue #1444 which goes more into the details of the issue.
