### ISSUE TITLE
Sibling masks corrupt eachother

### ISSUE THREAD

**Issue by Coffee-Maker** [Neos-Metaverse/NeosPublic#946]
When adding a slot with a mask to a parent with more slots with masks, if the mask is at a lower child index it will corrupt some masks that come after it.

https://gyazo.com/fdd4bc06ba7e91588a2828816767dd0f

**Comment by Frooxius** [comment]
I'm not sure what I'm supposed to be looking for in the video. Is this something you can reproduce in isolated scenario? What does the hierarchy and masks look like? What exactly do you mean by "corrupt"?

**Comment by shiftyscales** [comment]
Closing due to lack of response for further information, and a lack of the modern template. Please feel free to create a new issue if you can provide more replication information such as answers to the above questions.
